slovar = {
    "table decoration": "украшение для стола",
    "table number": "номер стола",
    "table number holder": "держатель номера стола",
    "candelabra": "подсвечник",
    "napkin": "салфетка",
    "table cloth": "скатерть",
    "damask cloth": "дамасская скатерть (особый вид полотна)",
    "ashtray": "пепельница",
    "dinner set": "обеденный сервиз",
    "tray": "поднос",
    "serving trolley": "передвижной столик",
    "salt pot": "солонка",
    "pepper box": "перечница",
    "egg cup": "пашотница",
    "corkscrew": "штопор",
    "sugar-basin": "сахарница",
    "sugar-tongs": "щипцы для сахара",
    "coffee set": "кофейный сервиз",
    "coffee pot": "кофейник",
    "coffee strainer": "ситечко",
    "tea pot": "заварочный чайник",
    "cup, mug (stein)": "чашка, кружка",
    "pincers for ice": "щипцы для льда",
    "nut-crackers": "щипцы для орехов",
    "cheese board": "доска для сыров",
    "cream jug": "сливочник",
    "dinner knife": "большой нож",
    "fruit knife": "фруктовый нож",
    "cheese knife": "нож для сыра",
    "butter knife": "нож для масла",
    "caviar knife": "нож для икры",
    "knife rest": "подставка для ножа",
    "under plate": "подтарельник",
    "bottom plate": "подстановочная тарелка",
    "dessert plate": "тарелка для десерта",
    "dinner plate": "обеденная (большая) тарелка",
    "snack plate": "тарелка для закусок (средняя)",
    "salad bowl": "салатник",
    "sauce (gravy) boat": "соусница",
    "herring dish": "селедочница",
    "soup tureen": "супница",
    "soup ladle": "половник",
    "soup spoon": "суповая ложка",
    # GLASSES
    "short": "стопка",
    "old-fashioned": "Стакан для виски «Старомодный»",
    "tumbler": "русский стакан, пивной стакан",
    "tea glass": "чайный стакан",
    "water glass": "стакан для воды",
    "highball": "стакан 250 / 300 ml",
    "brandy glass": "стакан для бренди и коньяка",
    "tall wineglass": "фужер",
    "goblet": "стакан, бокал",
    "whisky glass": "стакан для виски",
    "jigger": "мерный стакан",
    "glass holder": "подстаканник",
    # СЕРВИРОВКА
    "cover, place setting": "Сервировка",
    "dining table": "Обеденный стол",
    "the meat dish, meat plate (в амер. meat platter)": "Блюдо для мяса",
    "the vegetable dish": "Блюдо для горячих овощей",
    "the cheese dish": "Блюдо для сыра",
    "the caucer": "Блюдце",
    "the wine glass": "Бокал для вина (фужер)",
    "The white wine glass": "Бокал для белого вина",
    "the sweet wine glass": "Бокал для десертного вина",
    "the red wine glass": "Бокал для красного вина",
    "champagne glass": "Бокал для шампанского",
    "the crystal glass": "Хрустальный бокал для шампанского",
    "rummer": "Рюмка для рома",
    "brandy glass": "Рюмка для коньяка",
    "liqueur glass": "Рюмка для ликера",
    "spirit glass": "рюмка для крепких напитков",
    "beer glass": "Стакан для пива",
    "taper glass": "Конический бокал",
    "the compout bowl": "Ваза для компота",
    "the potato dish": "Ваза с крышкой для картофеля",
    "the soup tureen": "Суповая ваза",
    "the fork": "Вилка",
    "handle": "черенок вилки",
    "prong (tang, tine)": "зубцы вилки",
    "the sandwich fork": "Вилка для бутерброда",
    "the salad fork": "Вилка для салата",
    "the carving fork": "Вилка для разделки мяса",
    "fish fork": "Вилка для рыбы",
    "serving fork": "Большая вилка",
    "sardine server": "Вилка для сардин",
    "lobster fork": "Вилка для омара",
    "oyster fork": "Вилка для устриц",
    "cocktail fork": "Коктейльная вилка",
    "the mustard-pot": "Горчичница",
    "water jug": "Графин (кувшин) для воды",
    "the oif and vinegar bottle": "Графинчик для масла  и уксуса",
    "the liqueur decanter": "Графинчик для ликера",
    "the place card": "Карточка с указанием места",
    "serviette (napkin)": "Салфетка",
    "the napkin (serviette) ring": "Кольцо для салфетки",
    "the compote dish": "Компотница",
    "the bread basket": "Корзинка для хлеба",
    "the coffee pot": "Кофейник",
    "the cocoa Jug": "Кувшин для какао",
    "the spoon": "Ложка",
    "handle": "Черенок ложки",
    "bowl": "Углубление ложки",
    "the table spoon": "Столовая ложка",
    "the dessert spoon": "Десертная ложка",
    "the coffee spoon (tea spoon)": "Кофейная ложка (чайная ложка)",
    "the sauce ladle": "Соусная ложка",
    "the salad spoon": "Ложка для салата",
    "the egg spoon": "Ложка для яиц",
    "vegetable spoon, a serving spoon": "сервировочная ложка для овощей",
    "potato server, serving spoon for potatoes": "ложка для картофеля",
    "the asparagus server(slise)": "Лопаточка для сервировки спаржи",
    "the butter dish": "Масленка",
    "the milk server": "Молочник",
    "the knife": "Нож",
    "handle": "черенок ножа",
    "tang (tongue)": "язычок",
    "ferrule": "ободок",
    "blade": "лезвие",
    "lobster": "заплечик черенка ножа",
    "back": "тупая сторона",
    "edge (cutting edge)": "режущая часть",
    "fish knife": "нож для рыбы",
    "carving set (serving cutlery)": "приборы для нарезания мяса",
    "carving knife": "большой нож",
    "fruit knife": "нож для фруктов",
    "cheese knife": "нож для сыра",
    "butter knife": "нож для масла",
    "caviare knife": "нож для икры",
    "knife rest": "подставка для ножа",
    "the egg cup": "Пашотница",
    "the pepper box": "Перечница",
    "the tray": "Поднос",
    "the under plate": "Подтарельник",
    "the crockery": "Посуда",
    "the corkscrew": "Пробочник",
    "the salad bowl": "Салатник",
    "the sugar-basin": "Сахарница",
    " the coffee set": "Сервиз кофейный",
    "the coffee strainer": "Ситечко для кофе",
    "the table cloth": "Скатерть",
    "a damask cloth": "Скатерть из камчатного полотна",
    "the cream jug": "Сливочник",
    "the sauce boat (gravy boat)": "Соусница",
    "soup tureen": "Супница",
    "soup ladle": "Половник",
    "cheese board": "Доска с сырами",
    "the tumbler": "Пивной стакан",
    "the tea glass": "Чайный стакан",
    "the serving trolley": "Передвижной столик",
    "the salt pot": "Солонка",
    "the cruet stand": "Судок",
    "the plate": "Тарелка",
    "the soup (deep) plate": "Тарелка глубокая",
    "dessert plate": "Тарелка десертная",
    "bottom plate": "Тарелка подстановочная",
    "the dinner plate": "Тарелка мелкая",
    "snack plate": "Тарелка закусочная",
    "the teapot": "Чайник для заварки",
    "the cup": "Чашка",
    "corkscrew": "Штопор",
    "the nut-crackers": "Щипцы для орехов",
    "the sugar tongs": "Щипцы для сахара",
    "crown cork bottle opener": "пробочник",
    "electric hotplate": "электроподогреватель",
    "candelabra": "подсвечник",
    "table decoration": "украшение для стола",
    "coffee-pot": "кофейник",
    "mug, stein": "кружка",
    "dinner set": "обеденный сервиз",
    "ash-tray": "пепельница",
    "pepper-box": "перечница",
    "glass holder": "подстаканник",
    "cutlery": "прибор",
    "short glass": "рюмка",
    "sugar-basin": "сахарница",
    "herring dish": "селедочница",
    "coffee service": "сервиз кофейный",
    "tea-kettle": "чайник",
    "tea-spoon": "чайная ложка",
    "tea service": "чайный сервиз",
    "pincers tor ice": "щипцы для льда",
    # КАМБУЗНАЯ ПОСУДА И ПРИБОРЫ
    "whisk": "Венчик для сбивания",
    "kneader": "веселка",
    "cook's fork": "вилка поварская",
    "funnel": "воронка",
    "colander": "дуршлаг",
    "loading pin": "игла шпиговальная",
    "pot": "кастрюля",
    "casserole": "кастрюля наплитная",
    "sauce pan": "кастрюля с ручкой",
    "lid": "крышка",
    "casserole dish": "кастрюля из жаро",
    "water dipper": "прочного стекла ковшик для воды",
    "cooking pot": "котел наплитный",
    "measuring cup": "кружка мерная",
    "draw-plate": "лист духовой",
    "confectionary plate, bake pan, baking tray, cookie-sheet": "лист кондитерский",
    "garnish spoon": "ложка гарнирная",
    "soup ladle": "ложка разливная",
    "cutlet spatula": "лопатка-нож для котлет",
    "steak turner": "лопатка для бифштекса",
    "utility turner": "лопатка поварская",
    "culinary shovel": "лопатка кулинарная",
    "knife-sharpener": "машинка для точки ножей",
    "meat slicer": "нож для мяса",
    "bread knife": "нож для резки хлеба",
    "tin opener": "нож консервный",
    "spatula knife": "нож-лопатка",
    "cook's knives": "ножи поварские",
    "butcher knife": "нож мясоразделочный",
    "boning knife": "нож для вырезания костей",
    "bone saw": "пила для костей",
    "chopping board": "стол для резки",
    "pastry cutter": "резак для теста",
    "cake cutter": "резак для торта",
    "cleaver": "секач",
    "rolling pin": "скалка для теста",
    "fry pan": "сковорода",
    "portion fry pan": "сковорода порционная",
    "mortal with pestle": "ступка с пестиком",
    "grater": "тёрка",
    "meat axe": "топор мнсницкий",
    "tea kettle": "чайник наплитный",
    "whistling kettle": "чайник со свистком",
    "confectionery pincers": "щипцы кондитерские",
    "grinder": "кофейная мельница",
    "mincing machine, meat-grinder, meat chopper": "мясорубка",
    "food slicer": "ломтерезка",
    "wooden spoon": "деревянная ложка",
    "mixing spoon": "мешалка",
    "Thermos jug": "кувшин-термос",
    "cheese dish with": "поднос для сыра со",
    "glasscover": "стеклянной крышкой",
    "Three-compartment dish": "трехсекционное блюдо",
    "juice extractor": "соковыжималка",
    "lemon squeezer": "соковыжималка для лимона",
    "milk pot": "кувшин для молока",
    "immersion heater": "электрокипятильник",
    "pressure cooker": "скороварка",
    "cake tin, muffin tin": "форма для выпечки",
    "spring form": "разъёмная форма",
    "toaster": "тостер",
    "spit": "вертел",
    "electric waffle iron": "электро вафельница",
    "scales": "весы",
    "chip pan": "фритюрница",
    "basket": "сетка-дуршлаг",
    "skimmer": "шумовка",
    "potato chipper": "картофелерезка",
    "mixer": "электромиксер",
    "blender": "электр ос мес итель",
    "apron": "фартук",
    "waste bin (trash bin), wastebasket": "ведро для отходов",
    "microwave": "микроволновая печь",
    "breadboard": "доска для резки хлеба",
    "washing machine": "посудомоечная машина",
    "freezer, deep-freezer": "морозильник",
    "towel, cloth": "полотенце",
    "scouring pad": "губка для мытья посуды",
    "scourer": "металлическая мочалка для мытья посуды",
    "sink": "мойка, раковина",
    "washing-up liquid, dishwashing liquid": "моющее средство",
    "cooker, stove": "плита",
    "(electric) ring, burner": "(электрическая) горелка",
    # КУХОННЫЕ ОПЕРАЦИИ
    "chop": "Рубить, крошить",
    "slice": "Отрезать, резать ломтиками",
    "dice": "Нарезать в форме кубиков",
    "carve": "Резать, разделывать",
    "sift / sieve": "Просеивать",
    "whisk": "Сбивать(белки и т.п.)",
    "mix": "Размешать, перемешать",
    "drain / strain": "Процедить, профильтровать",
    "peel": "Очищать (фрукты, овощи)",
    "grate": "Натереть на тёрке",
    "knead": "Замешивать, месить",
    "roll out": "Раскатывать",
    "crush": "Дробить, толочь, мять, размельчать",
    "mash": "Раздавливать, разминать",
    "squeeze": "Выжимать",
    "skewer": "Насаживать (на что-то)",
    "Sprinkle": "Посыпать, побрызгать",
    "Dip": "Окунуть, обмакнуть",
    "Spread": "Намазать",
    "Snip": "Резать (ножницами)",
}