slovar = {
    "that's fine, keep the change": "все в порядке, оставьте сдачу",
    "would you like a receipt?": "вы желаете чек?",
    "could I have a receipt, please?": "могу я получит чек, пожалуйста?",
    "could you pick me up here at?": "могли бы вы забрать меня отсюда в ?",
    "could you pick me up here at six o'clock?": "могли бы вы забрать меня отсюда в шесть часов?",
    "taxis": "Такси",
    "for hire": "Свободно",
    "ok": "ладно",
    "of course": "конечно",
    "of course not": "конечно нет",
    "that's fine": "хорошо",
    "that's right": "точно",
    "sure": "конечно",
    "certainly": "непременно",
    "definitely": "определенно",
    "absolutely": "безусловно",
    "as soon as possible": "как можно быстрее",
    "that's enough": "достаточно",
    "it doesn't matter": "это не важно",
    "it's not important": "это не важно",
    "it's not serious": "это не серьезно",
    "it's not worth it": "это того не стоит",
    "i'm in a hurry": "я тороплюсь",
    "i've got to go": "мне нужно идти",
    "i'm going out я": "собираюсь прогуляться",
    "sleep well": "спи хорошо",
    "same to you!": "и тебе того же!",
    "me too": "я(мне) тоже",
    "not bad": "неплохо",
    "i like": "мне нравится …",
    "i like him": "мне нравится он",
    "i like her": "мне нравится она",
    "i like it": "мне нравится это",
    "i don't like": "мне не нравится …",
    "i don't like him": "мне не нравится он",
    "i don't like her": "мне не нравится она",
    "i don't like it": "мне не нравится это",
    "thanks for your": "спасибо за …",
    "thanks for your help": "спасибо за помощь",
    "thanks for your hospitality": "спасибо за гостепреимство",
    "thanks for your email": "спасибо за имейл",
    "i'm sorry": "извините",
    "i'm really sorry": "прошу прощения",
    "sorry i'm late": "извините за опоздание",
    "sorry to keep you waiting": "прошу прощения за задержку",
    "sorry for the delay": "извините за задержку",
    "look!": "посмотри!",
    "great!": "чудесно!",
    "come on!": "давай!",
    "only joking!": "шутка!",
    "just kidding!": "шутка!",
    "bless you!": "будь здоров! (после чихания)",
    "that's funny!": "прикольно!",
    "that's life!": "такова жизнь!",
    "that's funny": "странно ...",
    "do you have a boyfriend?": "у тебя есть парень?",
    "do you have a girlfriend?": "у тебя есть девушка?",
    "are you married?": "ты женат?, ты замужем?",
    "are you single?": "ты холостой?, ты незамужняя?",
    "are you seeing anyone?": "ты с кем-нибудь встречаешься?",
    "i'm single": "я холостой (незамужняя)",
    "i'm engaged": "я обручен(а)",
    "i'm married": "я женат (замужем)",
    "i'm divorced": "я в разводе",
    "i'm separated": "я живу отдельно",
    "i'm a widow": "я вдова",
    "i'm a widower": "я вдовец",
    "i'm seeing someone": "у меня уже кто-то есть",
    "help!": "помогите!",
    "be careful!": "будьте осторожны!",
    "look out!": "осторожно!",
    "watch out!": "осторожно!",
    "please help me": "пожалуйста, помогите мне",
    "call an ambulance!": "вызовите скорую помощь!",
    "i need a doctor": "мне нужен доктор",
    "there's been an accident": "произошел несчастный случай",
    "please hurry!": "пожалуйста, поторопитесь!",
    "i've burnt myself": "я обжегся",
    "are you OK?": "вы в порядке?",
    "is everyone OK?": "все в порядке?",
    "stop, thief!": "остановите вора!",
    "call the police!": "вызовите полицию!",
    "my wallet's been stolen": "мой кошелек украли",
    "my purse has been stolen": "мой сумочку украли",
    "my handbag's been stolen": "мою сумку украли",
    "my laptop's been stolen": "мой ноутбук украли",
    "my phone's been stolen": "мой телефон украли",
    "i'd like to report a theft": "я хотел бы заявить о краже",
    "my car's been broken into": "мою машину вскрыли",
    "i've been mugged": "меня ограбили",
    "i've been attacked": "на меня напали",
    "fire!": "пожар!",
    "call the fire brigade!": "вызовите пожарных!",
    "can you smell burning?": "вы чувствуете запах гари?",
    "there's a fire": "там пожар",
    "the building's on fire": "здание горит",
    "i'm lost": "я заблудился",
    "we're lost": "мы заблудились",
    "i can't find my": "я не могу найти …",
    "i can't find my keys": "я не могу найти мои ключи",
    "i can't find my passport": "я не могу найти мой паспорт",
    "i can't find my mobile": "я не могу найти мой мобильный телефон",
    "i've lost my": "я потерял …",
    "i've lost my wallet": "я потерял мой кошелек",
    "i've lost my purse": "я потерял мой бумажник",
    "i've lost my camera": "я потерял мой фотоаппарат",
    "i've locked myself out of my": "моя … закрылась, а ключи внутри",
    "i've locked myself out of my car": "моя машина закрылась, а ключи внутри",
    "i've locked myself out of my room": "моя комната закрылась, а ключи внутри",
    "please leave me alone": "пожалуйста, оставьте меня в покое",
    "go away!": "уйдите!",
    "yes": "да",
    "no": "нет",
    "maybe": "может быть",
    "perhaps": "может быть",
    "please": "пожалуйста",
    "thanks": "спасибо",
    "thank you": "спасибо",
    "thanks very much": "большое спасибо",
    "thank you very much": "большое спасибо",
    "you're welcome": "пожалуйста",
    "don't mention it": "не за что",
    "not at all": "не стоит благодарности",
    "hi": "привет (дружеское)",
    "hello": "здравствуйте",
    "good morning": "доброе утро (используется до полудня)",
    "good afternoon": "добрый день (используется с полудня до 6 часов вечера)",
    "good evening": "добрый вечер (используется после 6 часов вечера)",
    "bye": "пока",
    "goodbye": "до свидания",
    "goodnight": "спокойной ночи",
    "see you!": "увидимся!",
    "see you soon!": "до скорого!",
    "see you later!": "увидимся!",
    "have a nice day!": "хорошего дня!",
    "have a good weekend!": "хороших выходных!",
    "excuse me": "простите (может использоваться для привлечения внимания или при извинении)",
    "sorry": "извините",
    "no problem": "ничего страшного",
    "that's OK": "все в порядке",
    "don't worry about it": "не стоит беспокойства",
    "do you speak English?": "вы говорите по-английски?",
    "i don't speak English": "я не говорю по-английски",
    "i don't speak much English": "я не очень хорошо говорю по-английски",
    "i only speak very little English": "я только чуть-чуть говорю по-английски",
    "i speak a little English": "я немного говорю по-английски",
    "please speak more slowly": "пожалуйста, говорите медленнее",
    "please write it down": "пожалуйста, напишите это",
    "i understand": "я понимаю",
    "i don't understand": "я не понимаю",
    "i know": "я знаю",
    "i don't know": "я не знаю",
    "excuse me, where's the toilet?": "извините, где находится туалет?",
    "excuse me, where's the Gents?": "извините, где мужской туалет?",
    "excuse me, where's the Ladies?": "извините, где женский туалет?",
    "entrance": "Вход",
    "exit": "Выход",
    "emergency exit": "Запасной выход",
    "push": "От себя",
    "pull": "На себя",
    "wc": "Туалет",
    "gentlemen": "Мужчины",
    "gents": "Мужчины",
    "ladies": "Женщины",
    "vacant": "Свободно",
    "occupied": "Занято",
    "engaged": "Занято",
    "out of order": "Не работает",
    "private": "Частная собственность",
    "the day before yesterday": "позавчера",
    "yesterday": "вчера",
    "today": "сегодня",
    "tomorrow": "завтра",
    "the day after tomorrow": "послезавтра",
    "last night": "вчера вечером",
    "tonight": "сегодня вечером",
    "tomorrow night": "завтра вечером",
    "in the morning": "утром",
    "in the afternoon": "днем",
    "in the evening": "вечером",
    "yesterday morning": "вчера утром",
    "yesterday afternoon": "вчера днем",
    "yesterday evening": "вчера вечером",
    "this morning": "сегодня утром",
    "this afternoon": "сегодня днем",
    "this evening": "сегодня вечером",
    "tomorrow morning": "завтра утром",
    "tomorrow afternoon": "завтра днем",
    "tomorrow evening": "завтра вечером",
    "last week": "на прошлой неделе",
    "last month": "в прошлом месяце",
    "last year": "в прошлом году",
    "this week": "на этой неделе",
    "this month": "в этом месяце",
    "this year": "в этом году",
    "next week": "на следующей неделе",
    "next month": "в следующем месяце",
    "next year": "в следующем году",
    "five minutes ago": "пять минут назад",
    "here": "здесь (тут)",
    "there": "там",
    "everywhere": "везде",
    "nowhere": "нигде",
    "somewhere": "где-то",
    "where are you?": "где ты?, где вы?",
    "what's this?": "что это здесь?",
    "what's that?": "что это там?",
    "is anything wrong?": "что-то не так?",
    "what's the matter?": "в чем дело?",
    "is everything ok?": "все в порядке?",
    "have you got a minute?": "у тебя есть свободная минутка?",
    "have you got a pen I could borrow?": "можно одолжить ручку?",
    "really?": "правда?",
    "are you sure?": "ты уверен?",
    "why?": "почему?",
    "why not ?": "почему бы и нет?",
    "what's going on?": "что происходит?",
    "what's happening?": "что происходит?",
    "what happened?": "что случилось?",
    "what?": "что?",
    "where?": "где?",
    "when?": "когда?",
    "who?": "кто?",
    "how?": "как?",
    "how many?": "сколько?",
    "how much?": "сколько?",
    "congratulations!": "поздравления!",
    "well done!": "хорошо сработано!",
    "good luck!": "удачи!",
    "bad luck!": "вот незадача!",
    "never mind!": "неважно!",
    "what a pity!": "как жаль!",
    "what a shame!": "как жаль!",
    "happy birthday!": "с днем рождения!",
    "happy New Year!": "с Новым Годом!",
    "happy Easter!": "хороших пасхальных праздников!",
    "happy Christmas!": "счастливого Рождества!",
    "merry Christmas!": "счастливого Рождества!",
    "happy Valentine's Day!": "с днем святого Валентина!",
    "glad to hear it": "рад это слышать",
    "sorry to hear that": "жаль это слышать",
    "i'm tired": "я устал",
    "i'm exhausted": "я изможден",
    "i'm hungry": "я хочу есть",
    "i'm thirsty": "я хочу пить",
    "i'm bored": "мне скучно",
    "i'm worried": "я обеспокоен",
    "i'm looking forward to it": "я с нетерпением жду этого",
    "i'm in a good mood": "я в хорошем настороении",
    "i'm in a bad mood": "я в плохом настроении",
    "i can't be bothered": "не беспокойте меня",
    "welcome!": "добро пожаловать!",
    "welcome to": "добро пожаловать в …",
    "welcome to England": "добро пожаловать в Англию",
    "long time, no see!": "давно не виделись!",
    "all the best!": "всего хорошего!",
    "see you tomorrow!": "до завтра!",
    "what do you think?": "что ты думаешь?",
    "i think that": "я думаю, что...",
    "i hope that": "я надеюсь, что...",
    "i'm afraid that": "я боюсь, что...",
    "in my opinion": "по моему мнению, ...",
    "i agree": "я согласен (согласна)",
    "i disagree": "я не согласен (согласна)",
    "i don't agree": "я не согласен (согласна)",
    "that's true": "это правда",
    "that's not true": "это не правда",
    "i think so": "думаю, что так",
    "i don't think so": "я так не думаю",
    "i hope so": "надеюсь",
    "i hope not": "надеюсь, что нет",
    "you're right": "ты прав",
    "you're wrong": "ты не прав",
    "i don't mind": "я не возражаю",
    "it's up to you": "это зависит от тебя",
    "that depends": "смотря как",
    "that's interesting": "это интересно",
    "what languages can you speak?": "на каких языках вы говорите?",
    "i speak": "я говорю …",
    "i speak French, Spanish, and a little Russian": "я говорю по-французски, по-испански и немного по-русски",
    "i speak fluent German": "я говорю свободно по-немецки",
    "i can get by in": "я неплохо говорю …",
    "i can get by in Italian": "я неплохо говорю по-итальянски",
    "i'm learning": "я учу …",
    "i'm learning Chinese": "я учу китайский",
    "where did you learn your English?": "где ты выучил английский?",
    "at school": "в школе",
    "at university": "в университете",
    "i took a course": "я ходил на курсы",
    "i taught myself": "я выучил самостоятельно",
    "do you understand?": "ты понимаешь?",
    "did you understand?": "ты понял?",
    "yes, I understood": "да, я понял",
    "sorry, I didn't understand": "извини, я не понял",
    "sorry?": "простите?",
    "excuse me?": "простите?",
    "how do you say ... in English?": "как будет по-английски ...?",
    "how do you spell that?": "как это пишется?",
    "how do you pronounce this word?": "как произносится это слово?",
    "you speak very good English": "ты очень хорошо говоришь по-английски",
    "your English is very good": "у тебя очень хороший английский",
    "i'm a little out of practice": "мне не хватает практики",
    "i'd like to practise my": "я хотел бы попрактиковаться в …",
    "i'd like to practise my Portuguese": "я хотел бы попрактиковаться в португальском",
    "let's speak in": "давайте поговорим …",
    "let's speak in English": "давайте поговорим по-английски",
    "let's speak in Italian": "давайте поговорим по-итальянски",
    "what's this called?": "как это называется?",
    "where are the windscreen wipers?": "где включаются дворники?",
    "how do you open the?": "как открывается …?",
    "how do you open the petrol tank?": "как открывается топливный бак?",
    "how do you open the boot?": "как открывается багажник?",
    "how do you open the bonnet?": "как открывается капот?",
    "do you know where I can get a taxi?": "ты знаешь, где можно поймать такси?",
    "do you have a taxi number?": "у тебя есть номер такси?",
    "I'd like a taxi, please": "я хотел бы заказать такси, пожалуйста",
    "sorry, there are none available at the moment": "извините, сейчас свободных такси нет",
    "what's the address?": "какой адрес?",
    "i'm": "я …",
    "i'm at the Metropolitan Hotel": "я в отеле «Метрополь»",
    "i'm at the train station": "я на железнодорожном вокзале",
    "i'm at the corner of Oxford Street and Tottenham Court Road": "я на углу Оксфордстрит и Тоттенхэмкортроад",
    "could I take your name, please?": "назовите свое имя, пожалуйста",
    "how long will I have to wait?": "как долго ждать?",
    "how long will it be?": "сколько ждать?",
    "quarter of an hour": "четверть часа",
    "about ten minutes": "около десяти минут",
    "it's on its way": "машина в пути",
    "where would you like to go?": "куда бы вы хотели поехать?",
    "i'd like to go to": "я хотел бы поехать …",
    "i'd like to go to charing Cross station": "я хотел бы поехать на станцию «Чаринг Кросс»",
    "could you take me to?": "не могли бы вы отвезти меня в …?",
    "could you take me to the city centre?": "не могли бы вы отвезти меня в центр города?",
    "how much would it cost to?": "сколько стоит доехать до …?",
    "how much would it cost to Heathrow Airport?": "сколько стоит доехать до аэропорта «Хитроу»?",
    "how much will it cost?": "сколько это будет стоить?",
    "could we stop at a cashpoint?": "могли бы мы остановиться у банкомата?",
    "is the meter switched on?": "включен ли таксометр?",
    "please switch the meter on": "пожалуйста, включите таксометр",
    "how long will the journey take?": "сколько туда ехать?",
    "do you mind if I close the window?": "вы не против, если я закрою окно?",
    "are we almost there?": "мы уже почти приехали?",
    "how much is it?": "сколько с меня?",
    "have you got anything smaller?": "у вас есть более мелкие деньги?",
    "do you have any brothers or sisters?": "у тебя есть брат или сестра?",
    "yes, I've got": "да, у меня есть …",
    "yes, I've got a brother": "да, у меня есть брат",
    "yes, I've got a sister": "да, у меня есть сестра",
    "yes, I've got an elder brother": "да, у меня есть старший брат",
    "yes, I've got a younger sister": "да, у меня есть младшая сестра",
    "yes, I've got two brothers": "да, у меня есть два брата",
    "yes, I've got two sisters": "да, у меня есть две сестры",
    "yes, I've got one brother and two sisters": "да, у меня есть брат и две сестры",
    "no, I'm an only child": "нет, я единственный ребенок",
    "have you got any kids?": "у тебя есть дети?",
    "do you have any children?": "у тебя есть дети?",
    "yes, I've got a boy and a girl": "да, у меня мальчик и девочка",
    "yes, I've got a young baby": "да, у меня малыш",
    "yes, I've got three kids": "да, у меня три ребенка",
    "i don't have any children": "у меня нет детей",
    "do you have any grandchildren?": "у вас есть внуки?",
    "where do your parents live?": "где живут твои родители?",
    "what do your parents do?": "чем занимаются твои родители?",
    "what does your father do?": "чем занимается твой отец?",
    "what does your mother do?": "чем занимается твоя мать?",
    "are your grandparents still alive?": "твои бабушка и дедушка еще живы?",
    "let me know if you can make it": "сообщи, если ты сможешь",
    "i'll call you later": "я позвоню тебе позже",
    "what's your address?": "какой твой адрес?",
    "i'm running a little late": "я немного опаздываю",
    "i'll be there in minutes": "я буду там через … минут",
    "i'll be there in five minutes": "я буду там через пять минут",
    "i'll be there in ten minutes": "я буду там через десять минут",
    "i'll be there in fifteen minutes": "я буду там через пятнадцать минут",
    "have you been here long?": "ты уже давно тут?",
    "have you been waiting long?": "ты долго ждал?",
    "come on in!": "входи!, входите!",
    "good to see you!": "рад тебя видеть, рад вас видеть",
    "you're looking well": "ты прекрасно выглядишь, вы прекрасно выглядите",
    "please take your shoes off": "пожалуйста, сними обувь, пожалуйста, снимите обувь",
    "can I take your coat?": "я возьму твое пальто",
    "sorry we're late": "извини, мы опоздали",
    "did you have a good journey?": "ты хорошо добрался?, вы хорошо добрались?",
    "did you find us alright?": "ты нашел нас без проблем?, вы нашли нас без проблем?",
    "i'll show you your room": "я покажу твою комнату, я покажу вашу комнату",
    "this is your room": "это твоя комната, это ваша комната",
    "would you like a towel?": "тебе нужно полотенце?",
    "make yourself at home": "чувствуй себя как дома, чувствуйте себя как дома",
    "can I get you anything to drink?": "хочешь что-нибудь выпить?, хотите что-нибудь выпить?",
    "would you like a tea or coffee?": "хочешь чай или кофе?, хотите чай или кофе?",
    "how do you take it?": "с чем ты хочешь?",
    "do you take sugar?": "сколько положить сахара?",
    "do you take milk?": "тебе нужно молоко?",
    "how many sugars do you take?": "сколько положить сахара?",
    "would you like a?": "хочешь …?",
    "would you like a soft drink?": "хочешь попить (буквально: безалкогольный напиток)?",
    "would you like a beer?": "хочешь пиво?",
    "would you like a glass of wine?": "хочешь бокал вина?",
    "would you like a gin and tonic?": "хочешь джин с тоником?",
    "have a seat!": "садись!, садитесь!",
    "let's go into the": "давай(те) пойдем в …",
    "let's go into the lounge": "давай(те) пойдем в гостиную",
    "let's go into the living room": "давай(те) пойдем в гостиную",
    "let's go into the dining room": "давай(те) пойдем в столовую",
    "do you mind if I smoke here?": "ты не против, если я здесь закурю?",
    "i'd prefer it if you went outside": "будет лучше, если ты выйдешь на улицу",
    "are you ready to eat now?": "ты готов есть?, вы готовы есть?",
    "who's driving tonight?": "кто сегодня за рулем?",
    "damn it!": "проклятие!",
    "come in !": "войдите!",
    "please sit down": "садитесь, пожалуйста",
    "could I have your attention, please?": "пожалуйста, внимание!",
    "let's go!": "пойдемте!",
    "hurry up!": "поторопись!",
    "get a move on!": "пошевеливайся!",
    "calm down": "успокойся",
    "steady on!": "осторожнее!",
    "hang on a second": "подожди секундочку",
    "hang on a minute": "подожди минутку",
    "one moment, please": "один момент, пожалуйста",
    "just a minute": "одну минутку",
    "take your time": "не торопись",
    "please be quiet": "пожалуйста, успокойтесь",
    "shut up!": "замолчи!",
    "stop it!": "прекрати!",
    "don't worry": "не волнуйся",
    "don't forget": "не забудь",
    "help yourself": "угощайся",
    "go ahead": "давай",
    "let me know!": "сообщи мне!",
    "after you!": "после вас!",
    "i'd like a single to Bristol": "я хотел бы билет в один конец до Бристоля",
    "i'd like a return to Bristol": "я хотел бы билет в оба конца до Бристоля",
    "i'd like a child single to Bristol": "я хотел бы детский билет в один конец до Бристоля",
    "i'd like a child return to Bristol": "я хотел бы детский билет в оба конца до Бристоля",
    "i'd like a senior citizens' single to Bristol": "я хотел бы пенсионерский билет в один конец до Бристоля",
    "i'd like a senior citizens' return to Bristol": "я хотел бы пенсионерский билет в оба конца до Бристоля",
    "i'd like a first class single to Bristol": "я хотел бы билет первого класса в один конец до Бристоля",
    "i'd like a first class return to Bristol": "я хотел бы билет первого класса в оба конца до Бристоля",
    "are there any reductions for off-peak travel?": "есть ли скидки на билеты не в час-пик?",
    "when would you like to travel?": "когда вы хотели бы выехать?",
    "when will you be coming back?": "когда вы хотели бы вернуться?",
    "i'd like a return to, coming back on Sunday": "я хотел бы билет в оба конца до …, с возвратом в воскресенье",
    "i'd like a return to Newcastle, coming back on Sunday": "я хотел бы билет в оба конца до Ньюкасла, с возвратом в воскресенье",
    "which platform do I need for?": "какая платформа на …?",
    "which platform do I need for Manchester?": "какая платформа на Манчестер?",
    "is this the right platform for?": "это правильная платформа для …?",
    "is this the right platform for Cardiff?": "это правильная платформа для Кардиффа?",
    "where do I change for?": "где мне надо сделать пересадку на …?",
    "where do I change for exeter?": "где мне надо сделать пересадку на Эксетер?",
    "you'll need to change at": "вам надо сделать пересадку в …",
    "you'll need to change at Reading": "вам надо сделать пересадку в Рединге",
    "can I have a timetable, please?": "не могли бы вы дать мне расписание, пожалуйста?",
    "how often do the buses run to?": "как часто ходят автобусы на …?",
    "how often do the buses run to Bournemouth?": "как часто ходят автобусы на Борнмут?",
    "how often do the trains run to?": "как часто ходят поезда на …?",
    "how often do the trains run to Coventry?": "как часто ходят поезда на Ковентри?",
    "i'd like to renew my season ticket, please": "я хотел бы продлить сезонный билет, пожалуйста",
    "the next train to arrive at Platform 2 is the 16.35 to Doncaster": "следующий поезд, прибывающий на вторую платформу, отправляется в 16:35 в Донкастер",
    "platform 11 for the 10.22 to guildford": "платформа 11 в 10:22 на Гилдфорд",
    "the next train to depart from Platform 5 will be the 18.03 service to Penzance": "следующий поезд, отправляющийся с пятой платформы, это рейс в 18:03 на Пензанс",
    "the train's running late": "поезд опаздывает",
    "the train's been cancelled": "поезд был отменен",
    "does this bus stop at?": "останавливается ли этот автобус в …?",
    "does this bus stop at Trafalgar Square?": "останавливается ли этот автобус в Трафальгарской площади?",
    "does this train stop at?": "останавливается ли этот поезд в …?",
    "does this train stop at Leicester?": "останавливается ли этот поезд в Лейчестере?",
    "could I put this in the hold, please?": "могу я положить это в багаж, пожалуйста?",
    "could you tell me when we get to?": "скажите мне, пожалуйста, когда мы доедем до …",
    "could you tell me when we get to the university?": "скажите мне, пожалуйста, когда мы доедем до университета",
    "could you please stop at?": "остановитесь, пожалуйста, в …",
    "could you please stop at the airport?": "остановитесь, пожалуйста, в аэропорту",
    "is this seat free?": "это место свободно?",
    "is this seat taken?": "это место занято?",
    "do you mind if I sit here?": "не возражаете, если я здесь сяду?",
    "tickets, please": "билеты, пожалуйста",
    "all tickets and railcards, please": "билеты и проездные карты, пожалуйста",
    "could I see your ticket, please?": "покажите ваш билет, пожалуйста",
    "i've lost my ticket": "я потерял билет",
    "what time do we arrive in?": "во сколько мы прибываем в …?",
    "what time do we arrive in Sheffield?": "во сколько мы прибываем в Шеффилд?",
    "what's this stop?": "что это за остановка?",
    "what's the next stop?": "какая следующая остановка?",
    "this is my stop": "это моя остановка",
    "i'm getting off here": "я выхожу здесь",
    "is there a buffet car on the train?": "есть ли в поезде вагон-ресторан?",
    "do you mind if I open the window?": "вы не возражаете, если я открою окно?",
    "we are now approaching London Kings Cross": "мы прибываем на станцию Кингс-кросс",
    "this train terminates here": "этот поезд дальше не идёт",
    "all change, please": "всем пересесть, пожалуйста",
    "please take all your luggage and personal belongings with you": "пожалуйста заберите багаж и все персональные вещи",
    "could you tell me where the nearest Tube station is?": "не могли бы вы сказать, где ближайшая станция метро?",
    "where's there a map of the Underground?": "где здесь схема метро?",
    "over there": "там",
    "which line do I need for Camden Town?": "на какой линии находится Камден-таун?",
    "how many stops is it to?": "сколько остановок до …?",
    "how many stops is it to Westminster?": "сколько остановок до Вестминстера?",
    "i'd like a Day travelcard, please": "я хотел бы билет на день, пожалуйста",
    "which zones?": "в какие зоны?",
    "zones 1-2": "зоны 1—2",
    "i'd like an Oyster card, please": "я хотел бы карту «Ойстер», пожалуйста (карта с предоплатой для путешествия на общественном транспорте в Лондоне)",
    "i'd like to put £10 on it": "я хотел бы положить 10 фунтов",
    "tickets": "Билеты",
    "platform": "Платформа",
    "waiting room": "Зал ожидания",
    "left luggage": "Багажное отделение",
    "lost property": "Бюро находок",
    "underground": "Метро",
    "bus stop": "Остановка автобуса",
    "request stop": "Остановка по требованию",
    "on time": "Вовремя",
    "expected": "Прибывает",
    "delayed": "Задерживается",
    "cancelled": "Отменен",
    "calling at": "Останавливается в ...",
    "seat": "Место",
    "car": "Купе",
    "priority seat": "Специальные места (места для беременных, пожилых или инвалидов)",
    "to trains": "К поездам",
    "trains to London": "Поезда на Лондон",
    "way out": "Выход",
    "mind the gap": "Осторожно, щель",
    "northbound platform": "Платформа северного направления",
    "eastbound platform": "Платформа восточного направления",
    "southbound platform": "Платформа южного направления",
    "westbound platform": "Платформа южного направления",
    "i'd like to hire a car": "я хотел бы взять автомобиль на прокат",
    "how long for?": "как надолго?",
    "for how many days?": "на сколько дней?",
    "for": "на …",
    "for one day": "на один день",
    "for two days": "на два дня",
    "for a week": "на неделю",
    "how much does it cost?": "сколько это стоит?",
    "40 a day with unlimited mileage": "40 фунтов в день без ограничения расстояния",
    "what type of car do you want — manual or automatic?": "какой тип коробки передач вы хотитe мануальный или автоматический?",
    "has this car got?": "в машине есть …?",
    "has this car got air conditioning?": "в машине есть кондиционер?",
    "has this car got central locking?": "в машине есть центральный замок?",
    "has this car got a CD player?": "в машине есть проигрыватель компакт-дисков?",
    "has this car got child locks?": "в машине есть «детские» замки?",
    "could I see your driving licence?": "покажите ваши водительские права",
    "you have to bring it back with a full tank": "вы должны вернуть её с полным баком",
    "it has to be returned by 2pm on Saturday": "она должна быть возвращена до 2 часов дня в воскресенье",
    "remember to drive on the": "двигайтесь по …",
    "remember to drive on the left": "двигайтесь по левой стороне",
    "remember to drive on the right": "двигайтесь по правой стороне",
    "does it take petrol or diesel?": "машина бензиновая или дизельная?",
    "is it manual or automatic?": "коробка передач мануальная или автоматическая?",
    "i'll show you the controls": "я покажу вам выключатели",
    "where are the?": "где включаются …?",
    "where are the lights?": "где включаются фары?",
    "where are the indicators?": "где включаются поворотники?",
    "regards,": "С пожеланиями,",
    "kind regards,": "С добрыми пожеланиями,",
    "best regards,": "С наилучшими пожеланиями,",
    "with kind regards,": "С добрыми пожеланиями,",
    "dear Mr Smith,": "Дорогой мистер Смит,",
    "dear Mrs Jones,": "Дорогая миссис Джонс",
    "dear Miss Richards,": "Дорогая мисс Ричардс",
    "dear Ms Shepherd,": "Дорогая госпожа Шепард",
    "dear Sir,": "Дорогой Господин,",
    "dear Madam,": "Дорогая Госпожа,",
    "dear Sir or Madam,": "Дорогой Господин или дорогая Госпожа,",
    "i am writing in reply to your letter of 4 September regarding your outstanding invoice.": "Пишу Вам в ответ на письмо от 4-го сентября, касательно Вашего неоплаченного счета.",
    "further to our conversation, I'm pleased to confirm our appointment for 9.30am on Tuesday, 7 January.": "В продолжение нашей беседы я рад подтвердить, что наша встреча состоится во вторник 7-го января в 9:30.",
    "i would be grateful if you could attend to this matter as soon as possible.": "Пожалуйста отреагируйте на это как можно быстрее.",
    "if you would like any further information, please don't hesitate to contact me.": "Если Вы заинтересованы в получении дополнительной информации, пожалуйста свяжитесь со мной.",
    "i look forward to hearing from you.": "С нетерпением жду Вашего ответа.",
    "yours sincerely,": "Искренне Ваш,",
    "yours faithfully,": "Искренне Ваш,",
    "hello!": "алло!",
    "john speaking": "говорит Джон",
    "it's Maria here": "это Мария",
    "could I speak to, please?": "могу я поговорить с, пожалуйста?",
    "could I speak to Bill, please?": "могу я поговорить с Билом, пожалуйста?",
    "speaking!": "это я! (буквально: говорю!)",
    "who's calling?": "кто звонит?",
    "could I ask who's calling?": "могу я узнать, кто звонит?",
    "where are you calling from?": "откуда вы звоните?",
    "what company are you calling from?": "из какой компании вы звоните?",
    "do you know what extension he's on?": "вы знаете на какой он линии?",
    "hold the line, please": "оставайтесь на линии, пожалуйста",
    "i'll put him on": "соединяю с ним",
    "i'll put her on": "соединяю с ней",
    "i'm sorry, he's": "извините, он",
    "i'm sorry, he's not available at the moment": "извините, он сейчас занят",
    "i'm sorry, he's in a meeting": "извините, он на встрече",
    "i'm sorry, she's": "извините, она",
    "i'm sorry, she's on another call": "извините, она говорит по другому телефону",
    "i'm sorry, she's not in at the moment": "извините, она отсутствует",
    "would you like to leave a message?": "вы хотите оставить сообщение?",
}


#    "after you!": "после вас!",
#    "that's not true": "это не правда",
