slovar = {
    "an hour ago": "час назад",
    "a week ago": "неделю назад",
    "two weeks ago": "две недели назад",
    "a month ago": "месяц назад",
    "a year ago": "год назад",
    "a long time ago": "давным-давно",
    "in ten minutes' time": "через десять минут",
    "in ten minutes": "через десять минут",
    "in an hour's time": "через час",
    "in an hour": "через час",
    "in a week's time": "через неделю",
    "in a week": "через неделю",
    "in ten days' time": "через десять дней",
    "in ten days": "через десять дней",
    "in three weeks' time": "через три недели",
    "in three weeks": "через три недели",
    "in two months' time": "через два месяца",
    "in two months": "через два месяца",
    "in ten years' time": "через десять лет",
    "in ten years": "через десять лет",
    "the previous day": "в предыдущий день",
    "the previous week": "на предыдущей неделе",
    "the previous month": "в предыдущем месяце",
    "the previous year": "в предыдущем году",
    "the following day": "на следующий день",
    "the following week": "на следующей неделе",
    "the following month": "в следующем месяце",
    "the following year": "в следующем году",
    "I lived in Canada for six months": "я жил в Канаде шесть месяцев",
    "I've worked here for nine years": "я работаю здесь девять лет",
    "I'm going to France tomorrow for two weeks": "завтра я уезжаю во Францию на две недели",
    "we were swimming for a long time": "мы долго плавали",
    "could I use your phone?": "можно воспользоваться телефоном?",
    "your taxi's here": "твое такси здесь, ваше такси здесь",
    "thanks for coming": "спасибо, что зашел; спасибо, что зашли",
    "have a safe journey home": "безопасного возвращения домой",
    "do you have any plans for the summer?": "у тебя есть планы на лето?",
    "what are you doing for …?": "что ты делаешь на …?",
    "what are you doing for Christmas?": "что ты делаешь на Рождество?",
    "what are you doing for New Year?": "что ты делаешь на Новый год?",
    "what are you doing for Easter?": "что ты делаешь на Пасху?",
    "I share with one other person": "я живу с одним человеком",
    "I share with … others": "я живу с … другими",
    "I share with two others": "я живу с двумя другими",
    "I share with three others": "я живу с тремя другими",
    "what's your email address?": "какой у тебя электронный адрес?",
    "could I take your email address?": "можно записать твой электронный адрес?",
    "are you on …?": "ты зарегистрирован в …?",
    "are you on Facebook?": "ты зарегистрирован в Facebook?",
    "are you on Skype?": "ты зарегистрирован в Skype?",
    "what's your username?": "какое у тебя там имя?",
    "have you got any pets?": "у тебя есть домашние животные?",
    "I've got …": "у меня …",
    "I've got a dog and two cats": "у меня собака и две кошки",
    "I've got a Labradorу": "меня лабрадор",
    "what's his name?": "как его зовут?",
    "he's called …": "его зовут …",
    "he's called Tom": "его зовут Том",
    "what's the time?": "сколько времени?",
    "what time is it?": "который час?",
    "could you tell me the time, please?": "скажите, пожалуйста, сколько времени?",
    "do you happen to have the time?": "не подскажете который час?",
    "do you know what time it is?": "вы знаете сколько сейчас времени?",
    "it's exactly ...": "сейчас ровно ...",
    "it's about ...": "сейчас примерно ...",
    "it's almost ...": "сейчас почти ...",
    "it's just gone ...": "сейчас немного больше, чем ...",
    "one o'clock": "час",
    "two o'clock": "два часа",
    "three o'clock": "три часа",
    "four o'clock": "четыре часа",
    "five o'clock": "пять часов",
    "six o'clock": "шесть часов",
    "seven o'clock": "семь часов",
    "eight o'clock": "восемь часов",
    "ten o'clock": "десять часов",
    "eleven o'clock": "одиннадцать часов",
    "twelve o'clock": "двенадцать часов",
    "nine o'clock": "девять часов",
    "quarter past …": "четверть …",
    "quarter past one": "четверть второго",
    "quarter past two": "четверть третьего",
    "quarter past three": "четверть четвертого",
    "half past …": "половина …",
    "half past one": "половина второго",
    "half past two": "половина третьего",
    "half past three": "половина четвертого",
    "quarter to …": "без четверти …",
    "quarter to one": "без четверти час",
    "quarter to two": "без четверти два",
    "quarter to three": "без четверти три",
    "five past one": "пять минут второго",
    "ten past one": "десять минут второго",
    "twenty past one": "двадцать минут второго",
    "twenty-five past one": "двадцать пять минут второго",
    "five to two": "без пяти два",
    "ten to two": "без десяти два",
    "twenty to two": "без двадцати два",
    "twenty-five to two": "без двадцати пяти два",
    "ten fifteen": "десять часов пятнадцать минут",
    "ten thirty": "десять часов тридцать минут",
    "Checkout": "Касса",
    "8 items or less": "8 предметов или меньше",
    "Basket only": "Только для корзинок",
    "Cash only": "Только наличные",
    "Best before end": "Годен до",
    "Use by": "Использовать до",
    "what times are you open?": "когда вы открыты?",
    "we're open from 9am to 5pm, Monday to Friday": "мы открыты с 9 утра до 5 вечера, с понедельника по пятницу",
    "we're open from 10am to 8pm, seven days a week": "мы открыты с 10 утра до 8 вечера, семь дней в неделю",
    "are you open on …?": "вы открыты в …?",
    "are you open on Saturday?": "вы открыты в субботу?",
    "are you open on Sunday?": "вы открыты в воскресенье?",
    "what time do you close?": "во сколько вы закрываетесь?",
    "what time do you close today?": "во сколько вы сегодня закроетесь?",
    "what time do you open tomorrow?": "во-сколько вы открываетесь завтра?",
    "can I help you?": "могу я вам помочь?",
    "I'm just browsing, thanks": "я просто присматриваюсь, спасибо",
    "how much is this?": "сколько за это?",
    "how much are these?": "сколько за эти?",
    "how much does this cost?": "сколько это стоит?",
    "how much is that … in the window?": "сколько стоит … на витрине?",
    "how much is that lamp in the window?": "сколько стоит лампа на витрине?",
    "that's cheap": "это дешево",
    "that's good value": "это подходящая цена",
    "that's expensive": "это дорого",
    "do you sell …?": "вы продаёте …?",
    "do you sell stamps?": "вы продаёте марки?",
    "do you have any …?": "у вас есть какие-нибудь …?",
    "do you have any postcards?": "у вас есть какие-нибудь открытки?",
    "sorry, we don't sell them": "извините, их нет в продаже",
    "sorry, we don't have any left": "извините, их не осталось",
    "I'm looking for …": "я ищу …",
    "I'm looking for the shampoo": "я ищу шампунь",
    "I'm looking for a birthday card": "я ищу поздравительную открытку",
    "could you tell me where the … is?": "могли бы вы сказать, где …?",
    "could you tell me where the washing up liquid is?": "могли бы вы сказать, где моющее средство?",
    "where can I find the …?": "где я могу найти …?",
    "where can I find the toothpaste?": "где я могу найти зубную пасту?",
    "it's not what I'm looking for": "это не то, что я ищу",
    "do you have this item in stock?": "у вас есть это в продаже?",
    "do you know anywhere else I could try?": "вы знаете, где ещё можно посмотреть?",
    "does it come with a guarantee?": "есть ли на это гарантия?",
    "it comes with a one year guarantee": "на это один год гарантии",
    "do you deliver?": "вы делаете доставку?",
    "I'll take it": "я это возьму",
    "anything else?": "что-то ещё?",
    "are you in the queue?": "вы в очереди?",
    "next, please!": "следующий, пожалуйста",
    "I'll pay by card": "я заплачу карточкой",
    "would you be able to gift wrap it for me?": "вы сможете упаковать это как подарок?",
    "would you like a bag?": "вам нужен пакет?",
    "I'd like to return this": "я хотел бы вернуть это",
    "I'd like to change this for a different size": "я хотел бы поменять это на другой размер",
    "it doesn't work": "это не работает",
    "it doesn't fit": "это не подходит",
    "could I have a refund?": "могу я получить деньги обратно?",
    "have you got the receipt?": "у вас есть чек?",
    "could I speak to the manager?": "могу я поговорить с менеджером?",
    "Open": "Открыто",
    "Closed": "Закрыто",
    "Open 24 hours a day": "Открыто 24 часа в день",
    "Special offer": "Спецпредложение",
    "Sale": "Распродажа",
    "Clearance sale": "Окончательная распродажа",
    "Closing down sale": "Распродажа по поводу закрытия",
    "Good value": "Выгодная цена",
    "Buy 1 get 1 free": "Купи 1, получи 1 бесплатно",
    "Buy 1 get 1 half price": "Купи 1, получи 1 за полцены",
    "Reduced to clear": "Уценено (потому что необходимо продать)",
    "Half price": "Полцены",
    "Out to lunch": "Ушёл на обед",
    "Back in 15 minutes": "Вернусь через 15 минут",
    "Shoplifters will be prosecuted": "Воры будут наказаны",
    "Enter your PIN": "Введите пин-код",
    "Please wait": "Пожалуйста, подождите",
    "Remove card": "Заберите карточку",
    "Signature": "Подпись",
    "do you have any free tables?": "у вас есть свободные столики?",
    "a table for …, please": "столик на …, пожалуйста",
    "a table for two, please": "столик на двоих, пожалуйста",
    "a table for three, please": "столик на троих, пожалуйста",
    "a table for four, please": "столик на четверых, пожалуйста",
    "I'd like to book a table, please": "я хотел бы заказать столик, пожалуйста",
    "when for?": "на когда?",
    "for what time?": "на какое время?",
    "this evening at …": "сегодня вечером в …",
    "can you recommend a good restaurant?": "вы можете порекоммендовать хороший ресторан?",
    "where can I get a taxi?": "где я могу поймать такси?",
    "excuse me, where's …?": "извините, где находится …?",
    "excuse me, where's the tourist information office?": "извините, где находится пункт туристической информации?",
    "excuse me, where's the bus station?": "извините, где находится автобусная станция?",
    "excuse me, where's the train station?": "извините, где находится железнодорожная станция?",
    "excuse me, where's the police station?": "извините, где находится полицейский участок?",
    "excuse me, where's the harbour?": "извините, где находится порт?",
    "is there a … near here?": "есть ли тут неподалёку …?",
    "is there a cashpoint near here?": "есть ли тут неподалёку банкомат?",
    "is there a bank near here?": "есть ли тут неподалёку банк?",
    "is there a supermarket near here?": "есть ли тут неподалёку супермаркет?",
    "is there a hairdressers near here?": "есть ли тут неподалёку парикмахерская?",
    "is there a chemists near here?": "есть ли тут неподалёку аптека?",
    "do you know where there's an internet café?": "вы не знаете, где здесь интернет-кафе?",
    "do you know where the … embassy is?": "вы знаете, где находится … посольство?",
    "do you know where the Japanese embassy is?": "вы знаете, где находится японское посольство?",
    "do you know where the Russian embassy is?": "вы знаете, где находится российское посольство?",
    "Town centre": "Центр города",
    "Hospital": "Больница",
    "Public library": "Публичная библиотека",
    "Post office": "Почта",
    "Keep off the grass": "По траве не ходить",
    "Wet paint": "Окрашено",
    "Look left": "Посмотрите налево",
    "Look right": "Посмотрите направо",
    "do you know where I can get my … repaired?": "вы не знаете, где я могу отремонтировать …?",
    "do you know where I can get my phone repaired?": "вы не знаете, где я могу отремонтировать телефон?",
    "do you know where I can get my watch repaired?": "вы не знаете, где я могу отремонтировать часы?",
    "do you know where I can get my camera repaired?": "вы не знаете, где я могу отремонтировать фотоаппарат?",
    "do you know where I can get my shoes repaired?": "вы не знаете, где я могу отремонтировать обувь?",
    "the screen’s broken": "экран треснул",
    "there's something wrong with …": "что-то не в порядке с …",
    "there's something wrong with my watch": "что-то не в порядке с моими часами",
    "there's something wrong with this radio": "что-то не в порядке с этим радио",
    "do you do … repairs?": "вы ремонтируете …?",
    "do you do television repairs?": "вы ремонтируете телевизоры?",
    "do you do computer repairs?": "вы ремонтируете компьютеры?",
    "do you do laptop repairs?": "вы ремонтируете ноутбуком?",
    "when will it be ready?": "когда это будет готово?",
    "I can do it straight away": "я могу это сразу сделать",
    "it'll be ready …": "это будет готово …",
    "it'll be ready by tomorrow": "это будет готово завтра",
    "it'll be ready next week": "это будет готово на следующей неделе",
    "I won't be able to do it for at least two weeks": "я не смогу это сделать ещё по меньшей мере две недели",
    "are you able to repair it?": "вы можете это отремонтировать?",
    "we can't do it here": "мы не можем это здесь сделать",
    "we're going to have to send it back to the manufacturers": "мы собираемся отправить это обратно изготовителю",
    "it's not worth repairing": "это не стоит ремонта",
    "my watch has stopped": "мои часы остановились",
    "can I have a look at it?": "могу я посмотреть?",
    "I think it needs a new battery": "я думаю, нужна новая батарейка",
    "I've come to collect my …": "я пришел забрать …",
    "I've come to collect my watch": "я пришел забрать часы",
    "I've come to collect my computer": "я пришел забрать компьютер",
    "could you print the photos on this memory card for me?": "вы могли бы распечать фотографии с этой карты памяти?",
    "could you print the photos on this memory stick for me?": "вы могли бы распечатать фотографии с этой флешки?",
    "would you like matt or gloss prints?": "вы хотите матовые или глянцевые снимки?",
    "what size prints would you like?": "какого размера фотографии вы бы хотели?",
    "could I have this suit cleaned?": "вы могли бы почистить этот костюм?",
    "could you take these trousers up an inch?": "могли бы вы укоротить эти брюки на дюйм?",
    "could you take these trousers down an inch?": "могли бы вы удленить эти брюки на дюйм?",
    "could you take these trousers in an inch?": "могли бы вы ушить эти брюки на дюйм?",
    "could you take these trousers out two inches?": "могли бы вы расширить эти брюки на два дюйма?",
    "could I have these shoes repaired?": "могли бы вы отремонтировать эту обувь?",
    "could you put new … on these shoes for me?": "могли вы сделать новые … для этих ботинок?",
    "could you put new heels on these shoes for me?": "могли вы сделать новые каблуки для этих ботинок?",
    "could you put new soles on these shoes for me?": "могли вы сделать новые подметки для этих ботинок?",
    "could I have this key cut?": "могли бы вы сделать такой ключ?",
    "could I have these keys cut?": "могли бы вы сделать такие ключи?",
    "I'd like one copy of each of these, please": "сделайте по одной копии каждого экземпляра, пожалуйста",
    "could I have a key ring?": "я хотел бы брелок для ключей",
    "could I try this on?": "можно это примерить?",
    "could I try these on?": "можно это примерить? (для обуви, брюк или когда вы хотите примерить несколько вещей)",
    "could I try these shoes on?": "могу я примерить эти ботинки?",
    "do you want to try it on?": "вы хотите это примерить?",
    "do you want to try them on?": "вы хотите их примерить?",
    "what size are you?": "какой у вас размер?",
    "what size do you take?": "какой размер вы возьмёте?",
    "I take a size …": "я возьму размер …",
    "I take a size 10": "я возьму размер 10",
    "do you have this in a size …?": "у вас есть это размера …?",
    "do you have this in a size 7?": "у вас есть это размера 7?",
    "do you have these in a size …?": "у вас есть это размера …?",
    "do you have these in a size 12?": "у вас есть это размера 12?",
    "do you have a fitting room?": "у вас есть примерочная?",
    "where's the fitting room?": "где находится примерочная?",
    "have you got this in a smaller size?": "у вас есть это размером меньше?",
    "have you got this in a larger size?": "у вас есть это размером больше?",
    "could you measure my …?": "вы можете измерить мне …?",
    "could you measure my waist?": "вы можете измерить мне бёдра?",
    "could you measure my neck?": "вы можете измерить мне шею?",
    "could you measure my chest?": "вы можете измерить мне грудь?",
    "is that a good fit?": "хорошо это сидит?",
    "it's much too small": "это слишком сильно мало",
    "it's a little too small": "это немного мало",
    "it's a little too big": "это немного велико",
    "it's much too big": "это слишком сильно велико",
    "it's just right": "это как раз подходит",
    "they're just right": "это как раз подходит",
    "they don't fit": "они не подходят",
    "how do they feel?": "как вам в них?",
    "do they feel comfortable?": "вам в них удобно?",
    "it suits you": "это идёт вам",
    "they suit you": "это идёт вам",
    "is this the only colour you've got?": "это только такого цвета?",
    "what do you think of these?": "что вы думаете об этом?",
    "I like them": "мне нравятся",
    "I don't like them": "мне не нравятся",
    "I don't like the colour": "мне не нравится цвет",
    "what are these made of?": "из чего это сделано?",
    "are these washable?": "это можно стирать?",
    "no, they have to be dry-cleaned": "нет, это надо чистить в химчистке",
    "I'll take them": "я возьму",
    "I'll take these": "я возьму эти",
    "Menswear": "Мужская одежда",
    "could I order a new chequebook, please?": "я хотел бы заказать новую чековую книжку, пожалуйста",
    "I'd like to cancel a cheque": "я хотел бы аннулировать чек",
    "I'd like to cancel this standing order": "я хотел бы прервать постоянное платежное поручение",
    "where's the nearest cash machine?": "где находится ближайший банкомат?",
    "what's the interest rate on this account?": "какая процентная ставка на этом счете?",
    "what's the current interest rate for personal loans?": "какая процентная ставка на персональный заём?",
    "I've lost my bank card": "я потерял свою банковскую карточку",
    "I want to report a …": "я хочу заявить о …",
    "I want to report a lost credit card": "я хочу заявить о потере кредитной карточки",
    "I want to report a stolen credit card": "я хочу заявить о краже кредитной карточки",
    "we've got a joint account": "у нас совместный счет",
    "I'd like to tell you about a change of address": "я хотел бы сообщить вам об изменении адреса",
    "I've forgotten my Internet banking password": "я забыл пароль для интернет-банка",
    "I've forgotten the PIN number for my card": "я забыл пароль моей карточки",
    "I'll have a new one sent out to you": "я вышлю вам новый",
    "could I make an appointment to see …?": "я хотел бы назначить встречу с …",
    "could I make an appointment to see the manager?": "я хотел бы назначить встречу с менеджером",
    "could I make an appointment to see a financial advisor?": "я хотел бы назначить встречу с финансовым советником",
    "I'd like to speak to someone about a mortgage": "я хотел бы поговорить с кем-нибудь о жилищном заёме",
    "Insert your card": "Вставьте карточку",
    "Incorrect PIN": "Неправильный пин-код",
    "Enter": "Ввод",
    "Correct": "Исправить",
    "Cancel": "Отмена",
    "Withdraw cash": "Снять наличные",
    "Other amount": "Другая сумма",
    "Your cash is being counted": "Деньги считаются",
    "Insufficient funds": "Недостаточно денег на счёте",
    "Balance": "Остаток счёта",
    "On screen": "На экране",
    "Printed": "Распечатано",
    "Another service?": "Другая услуга?",
    "Would you like a receipt?": "Желаете чек?",
    "Quit": "Прекратить",
    "how much is a first class stamp?": "сколько стоит марка первого класса?",
    "how much is a second class stamp?": "сколько стоит марка второго класса?",
    "I'd like …, please": "я хотел бы …, пожалуйста",
    "I'd like an envelope, please": "я хотел бы конверт, пожалуйста",
    "I'd like a packet of envelopes, please": "я хотел бы упаковку конвертов, пожалуйста",
    "I'd like a jiffy bag, please": "я хотел бы противоударный пакет, пожалуйста",
    "could I have …, please?": "я хотел бы …, пожалуйста",
    "could I have a first class stamp, please?": "я хотел бы марку первого класса, пожалуйста",
    "could I have a second class stamp, please?": "я хотел бы марку второго класса, пожалуйста",
    "could I have a book of first class stamps, please?": "я хотел бы набор марок первого класса, пожалуйста",
    "could I have some first class stamps, please?": "я хотел бы марки первого класса, пожалуйста",
    "how many would you like?": "сколько штук вы хотите?",
    "I'd like to send this to …": "я хотел бы отправить это в …",
    "I'd like to send this to Canada": "я хотел бы отправить это в Канаду",
    "I'd like to send this parcel to …": "я хотел бы отправить эту посылку в …",
    "I'd like to send this parcel to Brazil": "я хотел бы отправить эту посылку в Бразилию",
    "how much will it cost to send this letter to …?": "сколько будет стоит отправить это письмо в …?",
    "how much will it cost to send this letter to the United States?": "сколько будет стоит отправить это письмо в Америку?",
    "can you put it on the scales, please?": "положите это на весы, пожалуйста",
    "I'd like to send this letter by …": "я хотел бы отправить это письмо …",
    "I'd like to send this letter by Recorded Delivery": "я хотел бы отправить это письмо «Recorded Delivery» (при доставке необходима подпись)",
    "I'd like to send this letter by Special Delivery": "я хотел бы отправить это письмо «Special Delivery» (гарантированная доставка по Великобритании в течение суток с компенсацией потери или ущерба)",
    "where's the postbox?": "где находится почтовый ящик?",
    "what's the last date I can post this to … to arrive in time for Christmas?": "какой последний день для отправки этого в …, чтобы вовремя дошло на Рождество?",
    "what's the last date I can post this to Germany to arrive in time for Christmas?": "какой последний день для отправки этого в Германию, чтобы вовремя дошло на Рождество?",
    "what's the last date I can post this to Australia to arrive in time for Christmas?": "какой последний день для отправки этого в Австралию, чтобы вовремя дошло на Рождество?",
    "I've come to collect a parcel": "я пришел забрать посылку",
    "I'd like to pay this bill": "я хотел бы оплатить этот счет",
    "I'd like to send some money to …": "я хотел бы переслать деньги в …",
    "I'd like to send some money to Poland": "я хотел бы переслать деньги в Польшу",
    "I'd like to send some money to India": "я хотел бы переслать деньги в Индию",
    "do you sell postcards?": "вы продаёте открытки?",
    "do you sell birthday cards?": "вы продаёте поздравительные открытки?",
    "do you sell Christmas cards?": "вы продаёте рождественские открытки?",
    "can you fill in this form, please?": "заполните этот бланк, пожалуйста",
    "do you have a …?": "у вас есть …?",
    "do you have a photo booth?": "у вас есть фотобудка?",
    "do you have a photocopier?": "у вас есть копировальный аппарат?",
    "First class": "Первый класс",
    "Second class": "Второй класс",
    "International": "Международный",
    "Airmail": "Авиапочта",
    "we're looking for accommodation": "мы ищем где остановиться",
    "we need somewhere to stay": "нам надо где-то остановиться",
    "do you have a list of …?": "у вас есть список …?",
    "do you have a list of hotels?": "у вас есть список гостиниц?",
    "do you have a list of B&Bs?": "у вас есть список B&Bs?",
    "do you have a list of youth hostels?": "у вас есть список молодежных хостелов?",
    "do you have a list of campsites?": "у вас есть список мест для кемпинга?",
    "what sort of accommodation are you looking for?": "какой тип жилья вы ищите?",
    "can you book accommodation for me?": "вы могли бы забронировть жильё для меня?",
    "do you have a map of the …?": "у вас есть карта …?",
    "do you have a map of the city?": "у вас есть карта города (большой город)?",
    "do you have a map of the town?": "у вас есть карта города (небольшой или маленький город)?",
    "where's the …?": "где находится …?",
    "where's the city centre?": "где находится центр города?",
    "where's the art gallery?": "где находится художественная галерея?",
    "where's the museum?": "где находится музей?",
    "where's the main shopping area?": "где находится главный торговый квартал?",
    "where's the market?": "где находится рынок?",
    "where's the railway station?": "где находится железнодорожная станция?",
    "what's the best way of getting around the city?": "какой самый лучший маршрут по городу?",
    "where can I hire a car?": "где я могу взять на прокат автомобиль?",
    "what are you interested in?": "что вас интересует?",
    "are there any … on at the moment?": "тут сейчас проходят какие-нибудь …?",
    "are there any exhibitions on at the moment?": "тут сейчас проходят какие-нибудь выставки?",
    "are there any cultural events on at the moment?": "тут сейчас проходят какие-нибудь культурные мероприятия?",
    "are there any sporting events on at the moment?": "тут сейчас проходят какие-нибудь спортивные мероприятия?",
    "are there any …?": "есть ли какие-нибудь …?",
    "are there any excursions?": "есть ли какие-нибудь экскурсии?",
    "are there any tours?": "есть ли какие-нибудь туры?",
    "are there any day trips?": "есть ли какие-нибудь дневные путешествия?",
    "is there a city tour?": "есть ли тур по городу?",
    "could you tell us what's on at the …?": "могли бы вы сказать, что идёт в …?",
    "could you tell us what's on at the cinema?": "могли бы вы сказать, что идёт в кино?",
    "could you tell us what's on at the theatre?": "могли бы вы сказать, что идёт в театре?",
    "could you tell us what's on at the concert hall?": "могли бы вы сказать, что идёт в концертном зале?",
    "could you tell us what's on at the opera house?": "могли бы вы сказать, что идёт в опере?",
    "can I book tickets here?": "могу я заказать тут билеты?",
    "do you have any brochures on …?": "у вас есть какие-нибудь брошюры о …?",
    "do you have any brochures on local attractions?": "у вас есть какие-нибудь брошюры о местных развлечениях?",
    "do you want us to put you on our mailing list?": "вы хотите, чтобы мы добавили вас в список рассылок?",
    "how much is the rent?": "сколько стоит аренда?",
    "what's the asking price?": "какова запрашиваемая цена?",
    "is the price negotiable?": "цена может быть обговорена?",
    "are they willing to negotiate?": "они собираются торговаться?",
    "how long has it been on the market?": "сколько времени это выставлено на продажу?",
    "is there a … school nearby?": "есть ли там по близости … школа?",
    "is there a primary school nearby?": "есть ли там по близости начальная школа?",
    "is there a secondary school nearby?": "есть ли там по близости средняя школа?",
    "how far is it from the nearest station?": "как далеко это от ближайшей станции?",
    "are there any local shops?": "там рядом есть магазины?",
    "what are the car parking arrangements?": "каковы условия парковки машины?",
    "what sort of view does it have?": "какой там вид?",
    "what floor is it on?": "на каком это этаже?",
    "it's on the …": "это на …",
    "it's on the ground floor": "это на первом этаже",
    "it's on the first floor": "это на втором этаже",
    "it's on the second floor": "это на третьем этаже",
    "it's on the third floor": "это на четвертом этаже",
    "are pets allowed?": "там разрешено держать домашних животных?",
    "I'd like to have a look at this property": "я хотел бы посмотреть на имущество",
    "when would you be available to view the property?": "когда вам будет удобно посмотреть собственность?",
    "the rent's payable monthly in advance": "платить надо вперед ежемесячно",
    "there's a deposit of one month's rent": "надо заплатить депозит в размере месячной платы",
    "how soon would you be able to move in?": "как скоро вы сможете въехать?",
    "I'd like to make an offer": "я хотел бы предложить цену",
    "we'll take it": "мы возьмем",
    "For sale": "Продается",
    "To let": "Сдаётся",
    "Under offer": "Предложение",
    "Sold": "Продано",
    "Reduced": "Уценено",
    "New price": "Новая цена",
    "Offers around £250,000": "Предложения около 250 000 фунтов",
    "Offers in excess of £180,000": "Предложения выше 180 000 фунтов",
    "£200,000 ono": "200 000 фунтов или по договоренности",
    "or nearest offer": "или по договоренности",
    "POA": "Цену надо спросить",
    "price on application": "Цену надо спросить",
    "£280 pw": "280 фунтов в неделю",
    "per week": "в неделю",
    "£1200 pcm": "1200 фунтов в месяц",
    "per calendar month": "1200 фунтов в месяц",
    "I'd like a haircut, please": "я хотел бы постричься",
    "do I need to book?": "я должен записаться?",
    "are you able to see me now?": "я могу прийти сейчас?",
    "would you like to make an appointment?": "вы хотите назначить время?",
    "would you like me to wash it?": "вы хотите, чтобы я помыл вам волосы?",
    "what would you like?": "что вы желаете?",
    "how would you like me to cut it?": "как вы хотите постричься?",
    "I'll leave it to you": "ваш выбор",
    "I'd like a trim": "я желаю стрижку",
    "I'd like a new style": "я желаю новый фасон",
    "I'd like a perm": "я желаю химическую завивку",
    "I'd like a fringe": "я желаю прямую челку",
    "I'd like some highlights": "я желаю мелирование",
    "I'd like it coloured": "я желаю покрасить волосы",
    "just a trim, please": "просто стрижку, пожалуйста",
    "how short would you like it?": "какую длину вы хотите?",
    "not too short": "не слишком коротко",
    "quite short": "довольно коротко",
    "very short": "очень коротко",
    "grade one": "уровень первый (под машинку, длина 3 мм)",
    "grade two": "уровень второй (под машинку, длина 6 мм)",
    "grade three": "уровень третий (под машинку, длина 9 мм)",
    "grade four": "уровень четвертый (под машинку, длина 12 мм)",
    "completely shaven": "полностью сбрить",
    "do you have a parting?": "у вас есть пробор?",
    "square at the back, please": "сзади прямо, пожалуйста",
    "tapered at the back, please": "сзади со скосом, пожалуйста",
    "that's fine, thanks": "так хорошо, спасибо",
    "what colour would you like?": "какой цвет вы хотите?",
    "which of these colours would you like?": "какие из этих цветов вам нравятся?",
    "would you like it blow-dried?": "вам посушить феном?",
    "could you trim my beard, please?": "не могли бы вы подстричь мне бороду?",
    "could you trim my moustache, please?": "не могли бы вы подстричь мне усы?",
    "would you like anything on it?": "вы хотите что-нибудь добавить?",
    "a little wax": "немного воска",
    "some gel": "гель",
    "some hairspray": "лак для волос",
    "nothing, thanks": "спасибо, ничего",
    "how much do I owe you?": "сколько с меня?",
    "Hairdressers": "Парикмахерская",
    "Barbers": "Мужская парикмахерская",
    "I'd like to withdraw £100, please": "я хотел бы снять 100 фунтов, пожалуйста",
    "I want to make a withdrawal": "я хотел бы снять деньги",
    "how would you like the money?": "какими купюрами вы желаете?",
    "in tens, please": "десятками, пожалуйста (банкноты по десять фунтов)",
    "ten pound notes": "десятками, пожалуйста (банкноты по десять фунтов)",
    "could you give me some smaller notes?": "вы могли бы дать мне мелкими банкнотами?",
    "I'd like to pay this in, please": "я хотел бы положить это на свой счет, пожалуйста",
    "I'd like to pay this cheque in, please": "я хотел бы положить этот чек на свой счет, пожалуйста",
    "how many days will it take for the cheque to clear?": "сколько дней потребуется, чтобы активировать чек?",
    "have you got any …?": "у вас есть какое-нибудь …?",
    "have you got any identification?": "у вас есть какое-нибудь удостоверение личности?",
    "have you got any ID?": "у вас есть какое-нибудь удостоверение личности?",
    "I've got my …": "у меня есть …",
    "I've got my passport": "у меня есть паспорт",
    "I've got my driving licence": "у меня есть водительские права",
    "I've got my ID card": "у меня есть карточка удостоверения личности",
    "your account's overdrawn": "вы ушли в минус",
    "I'd like to transfer some money to this account": "я хотел бы положить деньги на этот счет",
    "could you transfer £1000 from my current account to my deposit account?": "могли бы вы перевести 1000 фунтов с моего текущего счёта на депозитный счёт?",
    "I'd like to open an account": "я хотел бы открыть счёт",
    "I'd like to open a personal account": "я хотел бы открыть личный счёт",
    "I'd like to open a business account": "я хотел бы открыть бизнес-счёт",
    "could you tell me my balance, please?": "могли бы вы сказать мой остаток счёта, пожалуйста?",
    "could I have a statement, please?": "могу я получить распечатку, пожалуйста?",
    "I'd like to change some money": "я хотел бы обменять деньги",
    "I'd like to order some foreign currency": "я хотел бы заказать иностранную валюту",
    "what's the exchange rate for euros?": "какой обменный курс евро?",
    "I'd like some …": "я хотел бы …",
    "I'd like some euros": "я хотел бы евро",
    "I'd like some US dollars": "я хотел бы доллары США",
    "I went to school in Bristol": "я учился в школе в Бристоле",
    "I left school at sixteen": "я ушел из школы в шестнадцать лет",
    "I'm taking a gap year": "у меня свободный от учебы год (год между окончанием школы и началом учебы в универсиете, обычно используемый для путешествий, волонтерской работы и т.д.)",
    "how many more years do you have to go?": "сколько лет тебе еще учиться?",
    "what do you want to do when you've finished?": "что ты собираешься делать, когда закончишь?",
    "get a job": "устроиться на работу",
    "go travelling": "путешествовать",
    "I don't know what I want to do after university": "я не знаю, что буду делать после университета",
    "are you religious?": "ты верующий?",
    "no, I'm …": "нет, я …",
    "no, I'm an atheist": "нет, я атеист",
    "no, I'm agnostic": "нет, я агностик",
    "what religion are you?": "какого ты вероисповедания?",
    "I'm a …": "я …",
    "I'm a Christian": "я христьянин",
    "I'm a Muslim": "я мусульманин",
    "I'm a Buddhist": "я буддист",
    "I'm a Sikh": "я сикх",
    "I'm a Hindu": "я хинду",
    "I'm a Protestant": "я протестант",
    "I'm a Catholic": "я католик",
    "I'm Jewish": "я иудей",
    "do you believe in God?": "ты веришь в Бога?",
    "I believe in God": "я верю в Бога",
    "I don't believe in God": "я не верю в Бога",
    "do you believe in life after death?": "ты веришь в жизнь после смерти?",
    "do you believe in reincarnation?": "ты веришь в перерождение?",
    "is there a church near here?": "здесь есть поблизости церковь?",
    "is there a mosque near here?": "здесь есть поблизости мечеть?",
    "is there a synagogue near here?": "здесь есть поблизости синагога?",
    "is there a temple near here?": "здесь есть поблизости храм?",
    "what do you do?": "чем ты занимаешься?",

}