slovar = {
    "Brighton": "это правильный путь до …?",
    "do you have a map?": "у вас есть карта?",
    "can you show me on the map?": "можете показать мне на карте?",
    "it's this way": "это сюда",
    "it's that way": "это туда",
    "you're going the wrong way": "вы двигаетесь неправильным путем",
    "you're going in the wrong direction": "вы двигаетесь в неправильном направлении",
    "take this road": "следуйте по этой дороге",
    "go down there": "идите туда",
    "take the first on the left": "поверните на первом повороте направо",
    "take the second on the right": "поверните на втором повороте направо",
    "turn right at the crossroads": "на перекрёстке поверните направо",
    "continue straight ahead for about a mile": "проедьте прямо еще примерно одну милю (одна миля — примерно 1,6 километра)",
    "continue past the fire station": "продолжайте двигаться после пожарной станции",
    "you'll pass a supermarket on your left": "слева будет супермаркет",
    "keep going for another …": "пройдите еще …",
    "keep going for another hundred yards": "пройдите еще сто ярдов (примерно 91 метр)",
    "keep going for another two hundred metres": "пройдите еще двести метров",
    "keep going for another half mile": "пройдите еще пол мили (примерно 800 метров)",
    "keep going for another kilometre": "пройдите еще километр",
    "it'll be …": "это будет …",
    "it'll be on your left": "это будет слева",
    "it'll be on your right": "это будет справа",
    "it'll be straight ahead of you": "это будет прямо",
    "how far is it?": "как далеко это находится?",
    "how far is it to …?": "как далеко до …?",
    "how far is it to the airport?": "как далеко до аэропорта?",
    "how far is it to … from here?": "как далеко до … отсюда?",
    "how far is it to the beach from here?": "скак далеко до пляжа отсюда?",
    "is it far?": "это далеко?",
    "is it a long way?": "это долгий путь?",
    "it's not far": "это недалеко",
    "it's quite close": "это довольно близко",
    "it's quite a long way": "это довольно далеко",
    "it's a long way on foot": "это довольно далеко",
    "it's a long way to walk": "это долгий путь пешком",
    "it's about a mile from here": "это около мили отсюда (одна миля — примерно 1,6 километра)",
    "follow the signs for …": "следуйте указателям для …",
    "follow the signs for the town centre": "следуйте указателям для центра города",
    "follow the signs for Birmingham": "следуйте указателям для Бирменгема",
    "continue straight on past some traffic lights": "после светофора продолжайте прямо",
    "at the second set of traffic lights, turn left": "на втором светофоре поверните налево",
    "go over the roundabout": "проедьте по кольцу",
    "take the second exit at the roundabout": "на кольце воспользуйтесь вторым выездом",
    "turn right at the T-junction": "поверните направо на Т-образном перекрестке",
    "go under the bridge": "проедьте под мостом",
    "go over the bridge": "проедьте по мосту",
    "you'll cross some railway lines": "вы проедете через железнодорожный переезд",
    "where do I get the … to Southampton from?": "откуда отправляется … на Саусэмптон?",
    "where do I get the bus to Southampton from?": "откуда отправляется автобус на Саусэмптон?",
    "where do I get the train to Southampton from?": "откуда отправляется поезд на Саусэмптон?",
    "where do I get the ferry to Southampton from?": "откуда отправляется паром на Саусэмптон?",
    "what time's the next … to Portsmouth?": "во сколько следующий … на Портмут?",
    "what time's the next bus to Portsmouth?": "во сколько следующий автобус на Портмут?",
    "what time's the next train to Portsmouth?": "во сколько следующий поезд на Портмут?",
    "what time's the next ferry to Portsmouth?": "во сколько следующий паром на Портмут?",
    "this … has been cancelled": "этот … отменили",
    "this bus has been cancelled": "этот автобус отменили",
    "this train has been cancelled": "этот поезд отменили",
    "this flight has been cancelled": "этот рейс (вылет) отменили",
    "this ferry has been cancelled": "этот паром отменили",
    "this … has been delayed": "этот … задерживается",
    "this bus has been delayed": "этот автобус задерживается",
    "this train has been delayed": "этот поезд задерживается",
    "this flight has been delayed": "этот рейс (вылет) задерживается",
    "this ferry has been delayed": "этот паром задерживается",
    "have you ever been to …?": "ты когда-нибудь был в …?",
    "have you ever been to Italy?": "ты когда-нибудь был в Италии?",
    "yes, I went there on holiday": "да, я ездил туда в отпуск",
    "no, I've never been there": "нет, я никогда там не был",
    "I've never been, but I'd love to go someday": "никогда там не был, но очень хочу съездить",
    "how long does the journey take?": "как долго продлится путешествие?",
    "what time do we arrive?": "во сколько мы прибываем?",
    "do you get travel sick?": "тебе становится плохо в дороге?",
    "have a good journey!": "хорошей поездки!",
    "enjoy your trip!": "хорошего путешествия!",
    "I'd like to travel to …": "я хотел бы поехать в …",
    "I'd like to travel to Spain": "я хотел бы поехать в Испанию",
    "I'd like to book a trip to …": "я хотел бы забронировать путевку в …",
    "I'd like to book a trip to Berlin": "я хотел бы забронировать путевку в Берлин",
    "how much are the flights?": "сколько стоит перелет?",
    "do you have any brochures on Switzerland?": "у вас есть какие-нибудь брошюры о Швейцарии?",
    "do I need a visa for …?": "мне нужна виза в …?",
    "do I need a visa for Turkey?": "мне нужна виза в Турцию?",
    "where would you like to meet?": "где ты хотел бы встретиться?",
    "I'll see you … at ten o'clock": "увидимся … в десять часов",
    "I'll see you in the pub at ten o'clock": "увидимся в пабе в десять часов",
    "I'll see you at the cinema at ten o'clock": "увидимся в кино в десять часов",
    "I'll meet you there": "встретимся там",
    "see you there!": "увидимся там!",
    "Dear Mark,": "Дорогой Марк,",
    "Dear Jane,": "Дорогая Джейн,",
    "Thanks for your …": "Спасибо за …",
    "Thanks for your letter": "Спасибо за письмо",
    "Thanks for your postcard": "Спасибо за открытку",
    "Thanks for your present": "Спасибо за подарок",
    "Thanks for your invitation": "Спасибо за приглашение",
    "Sorry it's taken me so long to write.": "Извини, что давно не писал.",
    "I hope you're well.": "Надеюсь, у тебя все хорошо.",
    "Good to see you again last week.": "Рад был тебя видеть на прошлой неделе.",
    "Look forward to seeing you soon!": "С нетерпением жду встречи!",
    "Best wishes,": "С наилучшими пожеланиями,",
    "Love,": "С любовью,",
    "where are you from?": "откуда ты?",
    "where do you come from?": "откуда ты?",
    "whereabouts are you from?": "из каких ты мест?",
    "I'm from …": "я из …",
    "I'm from England": "я из Англии",
    "whereabouts in … are you from?": "откуда в … ты?",
    "whereabouts in Canada are you from?": "откуда в Канаде ты?",
    "what part of … do you come from?": "из какой части … ты?",
    "what part of Italy do you come from?": "из какой части Италии ты?",
    "where do you live?": "где ты живешь?",
    "I live in …": "я живу …",
    "I live in London": "я живу в Лондоне",
    "I live in France": "я живу во Франции",
    "I'm originally from Dublin but now live in Edinburgh": "я на самом деле из Дублина, но сейчас живу в Эдинбурге",
    "I was born in Australia but grew up in England": "я родился в Австралии, но вырос в Англии",
    "what brings you to …?": "как ты оказался …?",
    "what brings you to England?": "как ты оказался в Англии?",
    "I live here": "я живу здесь",
    "I work here": "я работаю здесь",
    "I study here": "я учусь здесь",
    "why did you come to …?": "для чего ты приехал …?",
    "why did you come to the UK?": "для чего ты приехал в Великобританию?",
    "the UK": "я приехал работать",
    "I came here to study": "я приехал учиться",
    "I wanted to live abroad": "я хотел жить заграницей",
    "how long have you lived here?": "как долго ты здесь живешь?",
    "I've only just arrived": "недавно приехал",
    "about a year": "около года",
    "just over two years": "чуть больше двух лет",
    "three years": "три года",
    "how long are you planning to stay here?": "как долго ты собираешься здесь оставаться?",
    "until August": "до августа",
    "a few months": "несколько месяцев",
    "another year": "еще год",
    "I'm not sure": "я точно не знаю",
    "do you like it here?": "тебе здесь нравится?",
    "yes, I love it!": "да, очень нравится!",
    "I like it a lot": "очень нравится",
    "it's OK": "нормально",
    "what do you like about it?": "что тебе здесь нравится?",
    "I like the …": "мне нравится/нравятся …",
    "I like the food": "мне нравится/нравятся еда",
    "I like the weather": "мне нравится/нравятся погода",
    "I like the people": "мне нравится/нравятся люди",
    "how old are you?": "сколько тебе лет?",
    "I'm twenty-two": "мне двадцать два",
    "I'm thirty-eight": "мне тридцать восемь",
    "when's your birthday?": "когда у тебя день рождения?",
    "it's 16 May": "он 16 мая",
    "it's 2 October": "он 2 октября",
    "who do you live with?": "с кем ты живешь?",
    "do you live with anybody?": "ты живешь с кем-то?",
    "I live with …": "я живу …",
    "I live with my boyfriend": "я живу со своим другом",
    "I live with my girlfriend": "я живу со своей подругой",
    "I live with my partner": "я живу со своим сожителем",
    "I live with my husband": "я живу со своим мужем",
    "I live with my wife": "я живу со своей женой",
    "I live with my parents": "я живу со своими родителями",
    "I live with a friend": "я живу с другом",
    "I live with friends": "я живу с друзьями",
    "I live with relatives": "я живу с родственниками",
    "do you live on your own?": "ты живешь отдельно?",
    "I live on my own": "я живу отдельно",
    "I'd love to": "с удовольствием",
    "sounds good": "хорошее предложение",
    "that sounds like fun": "заманчивое предложение",
    "sorry, I can't make it": "извини, не смогу",
    "I'm afraid already have plans": "боюсь, что у меня уже есть планы",
    "I'm too tired": "я слишком устал",
    "I'm staying in tonight": "я останусь сегодня дома",
    "I've got too much work to do": "у меня очень много работы",
    "I need to study": "мне нужно учиться",
    "I'm very busy at the moment": "я сейчас очень занят",
    "what time shall we meet?": "во сколько встретимся?",
    "let's meet at …": "давайте встретимся в …",
    "let's meet at eight o'clock": "давайте встретимся в восемь часов",
    "thanks for a lovely evening": "спасибо за прекрасный вечер",
    "I'm interested in this position": "я заинтересован в этой должности",
    "I'd like to apply for this job": "я хотел бы устроиться на эту работу",
    "is this a temporary or permanent position?": "это временная или постоянная должность?",
    "what are the hours of work?": "какое рабочее время?",
    "will I have to work on Saturdays?": "должен ли я работать по субботам?",
    "will I have to work shifts?": "должен ли я буду работать посменно?",
    "how much does the job pay?": "какая заработная плата?",
    "£10 an hour": "10 фунтов в час",
    "£350 a week": "350 фунтов в неделю",
    "what's the salary?": "какая заработная плата?",
    "£2,000 a month": "2000 фунтов в месяц",
    "£30,000 a year": "30 000 фунтов в год",
    "will I be paid weekly or monthly?": "мне будут платить еженедельно или ежемесячно?",
    "will I get travelling expenses?": "будут ли покрываться транспортные расходы?",
    "will I get paid for overtime?": "мне будут платить за сверхурочное время?",
    "is there …?": "есть ли …?",
    "is there a company car?": "есть ли служебная машина?",
    "is there a staff restaurant?": "есть ли столовая для служащих?",
    "is there a pension scheme?": "есть ли пенсионная схема?",
    "is there free medical insurance?": "есть ли бесплатное медицинское страхование?",
    "how many weeks' holiday a year are there?": "сколько недель составляет отпуск?",
    "who would I report to?": "кому я должен сообщить?",
    "I'd like to take the job": "я хотел бы приступить к работе",
    "when do you want me to start?": "когда я должен начать?",
    "we'd like to invite you for an interview": "мы хотели бы пригласить вас на собеседование",
    "this is the job description": "это – описание работы",
    "have you got any experience?": "у вас есть какой-нибудь опыт?",
    "have you got any qualifications?": "вы обладаете какими-либо качествами?",
    "we need someone with experience": "нам нужен кто-то с опытом",
    "we need someone with qualifications": "нам нужен специалист",
    "what qualifications have you got?": "какими профессиональными качествами вы обладаете?",
    "44 BC — the death of Julius Caesar": "44 год до нашей эры — смерть Юлия Цезаря",
    "79 AD — eruption of Vesuvius": "79 год нашей эры — извержение Везувия",
    "what's the weather like?": "какая сейчас погода?",
    "it's sunny": "сейчас солнечно",
    "it's cloudy": "сейчас облачно",
    "it's windy": "сейчас ветренно",
    "it's foggy": "сейчас туман",
    "it's stormy": "сейчас буря",
    "it's raining": "сейчас идет дождь",
    "it's hailing": "сейчас идет град",
    "it's snowing": "сейчас идет снег",
    "what a nice day!": "какой чудесный день!",
    "what a beautiful day!": "какой прекрасный день!",
    "it's not a very nice day": "это не самый хороший день",
    "what a terrible day!": "какой ужасный день!",
    "what miserable weather!": "какая отвратительная погода!",
    "it's starting to rain": "начинается дождь",
    "it's stopped raining": "дождь закончился",
    "it's pouring with rain": "идет проливной дождь",
    "it's raining cats and dogs": "льет как из ведра",
    "the weather's fine": "отличная погода",
    "the sun's shining": "светит солнце",
    "there's not a cloud in the sky": "на небе ни облачка",
    "the sky's overcast": "небо затянуто облаками",
    "it's clearing up": "проясняется",
    "the sun's come out": "солнце вышло",
    "the sun's just gone in": "солнце зашло",
    "there's a strong wind": "дует сильный ветер",
    "the wind's dropped": "ветер прекратился",
    "that sounds like thunder": "похоже, гром гремит",
    "that's lightning": "молния сверкает",
    "we had a lot of heavy rain this morning": "этим утром шёл проливной дождь",
    "we haven't had any rain for a fortnight": "в течение двух недель не было дождя",
    "what's the temperature?": "какая сейчас температура?",
    "it's 22°C": "сейчас 22°C",
    "temperatures are in the mid-20s": "сейчас около двадцати пяти градусов",
    "what temperature do you think it is?": "как ты думаешь, какая сейчас температура?",
    "probably about 30°C": "возможно около 30°C",
    "it's hot": "сейчас жарко",
    "it's cold": "сейчас холодно",
    "it's baking hot": "сейчас очень жарко",
    "it's freezing": "сейчас очень холодно",
    "it's freezing cold": "сейчас очень холодно",
    "it's below freezing": "минусовая темрпература",
    "what's the forecast?": "какой прогноз погоды?",
    "what's the forecast like?": "какой прогноз погоды?",
    "it's forecast to rain": "будет дождь",
    "it's going to freeze tonight": "ночью будут заморозки",
    "it looks like rain": "похоже, что будет дождь",
    "it looks like it's going to rain": "похоже, что будет дождь",
    "we're expecting a thunderstorm": "ожидается буря",
    "it's supposed to clear up later": "скоро должно проясниться",
    "would anyone like a tea or coffee?": "кто-нибудь хочет чай или кофе?",
    "would anyone like a cup of tea?": "кто-нибудь хочет чашку чая?",
    "what's her name?": "как ее зовут?",
    "she's called …": "ее зовут …",
    "she's called Mary": "ее зовут Мери",
    "what are their names?": "как их зовут?",
    "they're called …": "их зовут …",
    "they're called Neil and Anna": "их зовут Нейл и Анна",
    "how old is he?": "сколько ему лет?",
    "he's …": "ему …",
    "he's twelve": "ему двенадцать",
    "how old is she?": "сколько ей лет?",
    "she's …": "ей …",
    "she's fifteen": "ей пятнадцать",
    "how old are they?": "сколько им лет?",
    "they're …": "им …",
    "they're six and eight": "им шесть и восемь",
    "I'm at Peter's": "я у Питера",
    "are you up to anything this evening?": "у тебя уже есть планы на вечер?",
    "have you got any plans for …?": "у тебя есть планы на …?",
    "have you got any plans for this evening?": "у тебя есть планы на этот вечер?",
    "have you got any plans for tomorrow?": "у тебя есть планы на завтра?",
    "have you got any plans for the weekend?": "у тебя есть планы на выходные?",
    "are you free …?": "ты свободен …?",
    "are you free this evening?": "ты свободен сегодня вечером?",
    "are you free tomorrow afternoon?": "ты свободен завтра днем?",
    "are you free tomorrow evening?": "ты свободен завтра вечером?",
    "what would you like to do this evening?": "чем бы ты хотел заняться сегодня вечером?",
    "do you want to go somewhere at the weekend?": "ты хочешь куда-нибудь поехать на выходных?",
    "would you like to join me for something to eat?": "ты хочешь вместе со мной поесть?",
    "do you fancy going out tonight?": "хочешь прогуляться сегодня вечером?",
    "what's your name?": "как тебя зовут?",
    "my name's Chris": "меня зовут Крис",
    "my name's Emily": "меня зовут Эмили",
    "I'm Ben": "я Бен",
    "I'm Sophie": "я Софи",
    "this is …": "это …",
    "this is Lucy": "это Люси",
    "this is my wife": "это моя жена",
    "this is my husband": "это мой муж",
    "this is my boyfriend": "это мой друг",
    "this is my girlfriend": "это моя подруга",
    "this is my son": "это мой сын",
    "this is my daughter": "это моя дочь",
    "I'm sorry, I didn't catch your name": "извини, я не расслышал как тебя зовут",
    "do you know each other?": "вы знакомы?",
    "nice to meet you": "рад познакомиться",
    "pleased to meet you": "приятно познакомиться",
    "how do you do?": "очень приятно (фраза обычно используется при знакомстве; вежливый ответ — how do you do?)",
    "how do you know each other?": "как вы познакомились?",
    "we work together": "мы вместе работаем",
    "we used to work together": "мы вместе работали",
    "we were at school together": "мы вместе учились в школе",
    "we're at university together": "мы вместе учимся в университете",
    "we went to university together": "мы вместе учились в университете",
    "through friends": "через друзей",
    "I hate …": "я ненавижу …",
    "I hate shopping": "я ненавижу ходить по магазинам",
    "I can't stand …": "я терпеть не могу …",
    "I can't stand football": "я терпеть не могу футбол",
    "I'm interested in …": "я интересуюсь …",
    "I'm interested in photography": "я интересуюсь фотографией",
    "I'm interested in history": "я интересуюсь историей",
    "I'm interested in languages": "я интересуюсь языками",
    "I read a lot": "я много читаю",
    "have you read any good books lately?": "ты читал какие-нибудь хорошие книги в последнее время?",
    "have you seen any good films recently?": "ты смотрел какие-нибудь хорошие фильмы в последнее время?",
    "do you play any sports?": "ты занимаешься спортом?",
    "yes, I play …": "да, я играю …",
    "yes, I play football": "да, я играю в футбол",
    "yes, I play tennis": "да, я играю в теннис",
    "yes, I play golf": "да, я играю в гольф",
    "I'm a member of a gym": "я член спортклуба",
    "no, I'm not particularly sporty": "нет, я не особенно спортивный",
    "I like watching football": "мне нравится смотреть футбол",
    "which team do you support?": "за какую команду ты болеешь?",
    "I support …": "я болею за …",
    "I support Manchester United": "я болею за «Манчестер Юнайтед»",
    "I support Chelsea": "я болею за «Челси»",
    "I'm not interested in football": "меня не интересует футбол",
    "do you play any instruments?": "ты играешь на каких-либо музыкальных инструментах?",
    "yes, I play the guitar": "да, я играю на гитаре",
    "yes, I've played the piano for … years": "да, я играю на фортепьяно … лет",
    "yes, I've played the piano for five years": "да, я играю на фортепьяно пять лет",
    "I'm learning to play …": "я учусь играть …",
    "I'm learning to play the violin": "я учусь играть на скрипке",
    "I'm in a band": " я играю в группе",
    "I sing in a choir": "я пою в хоре",
    "what sort of music do you like?": "какая музыка тебе нравится?",
    "what sort of music do you listen to?": "какую музыку ты слушаешь?",
    "pop": "поп",
    "rock": "рок",
    "dance": "танцевальную",
    "classical": "классическую",
    "anything, really": "любую",
    "lots of different stuff": "разных стилей и направлений",
    "have you got any favourite bands?": "у тебя есть любимые исполнители?",
    "do you want to watch a …?": "хочешь посмотреть …?",
    "do you want to watch a film?": "хочешь посмотреть фильм?",
    "do you want to watch a DVD?": "хочешь посмотреть DVD?",
    "do you want me to put the TV on?": "хочешь, я включу телевизор?",
    "could you pass me the remote control?": "можешь передать мне пульт?",
    "do you want a game of …?": "хочешь поиграть в …?",
    "do you want a game of chess?": "хочешь поиграть в шахматы?",
    "do you want a game of cards?": "хочешь поиграть в карты?",
    "what time's the match on?": "во сколько начинается матч?",
    "who's playing?": "кто играет?",
    "who's winning?": "кто выигрывает?",
    "what's the score?": "какой счет?",
    "who won?": "кто выиграл?",
    "it was a draw": "сыграли вничью",
    "what's for …?": "что на …?",
    "what's for breakfast?": "что на завтрак?",
    "what's for lunch?": "что на обед?",
    "what's for dinner?": "что на ужин?",
    "breakfast's ready": "завтрак готов",
    "lunch is ready": "обед готов",
    "dinner's ready": "ужин готов",
    "what would you like for …?": "что ты хотел бы на …?",
    "what would you like for breakfast?": "что ты хотел бы на завтрак?",
    "what would you like for lunch?": "что ты хотел бы на обед?",
    "what would you like for dinner?": "что ты хотел бы на ужин?",
    "would you like some toast?": "хочешь тост?",
    "could you pass the …, please?": "можешь передать мне …, пожалуйста?",
    "could you pass the salt, please?": "можешь передать мне соль, пожалуйста?",
    "could you pass the sugar, please?": "можешь передать мне сахар, пожалуйста?",
    "could you pass the butter, please?": "можешь передать мне масло, пожалуйста?",
    "would you like a glass of …?": "хочешь …?",
    "would you like a glass of water?": "хочешь стакан воды?",
    "would you like a glass of orange juice?": "хочешь стакан апельсинового сока?",
    "careful, the plate's very hot!": "осторожно, тарелка горячая!",
    "would you like some more?": "хочешь добавки?",
    "have you had enough to eat?": "ты наелся?",
    "would anyone like dessert?": "кто-нибудь хочет десерт?",
    "would anyone like coffee?": "кто-нибудь хочет кофе?",
    "what's for dessert?": "что на десерт?",
    "I'm full": "я наелся",
    "that was …": "это было …",
    "that was lovely": "это было отлично",
    "what's the date today?": "какое сегодня число?",
    "what's today's date?": "какое сегодня число?",
    "15 October": "15 октября",
    "October 15": "15 октября",
    "Monday, 1 January": "понедельник, 1 января",
    "on 2 February": "2-го февраля",
    "at the beginning of July": "в начале июля",
    "in mid-December": "в середине декабря",
    "at the end of March": "в конце марта",
    "by the end of June": "до конца июня",
    "in 2007": "в 2007 г.",
    "AD": "нашей эры",
    "BC": "до нашей эры",
    "the 17th century": "семнадцатый век",
    "the 18th century": "восемнадцатый век",
    "the 19th century": "девятнадцатый век",
    "the 20th century": "двадцатый век",
    "the 21st century": "двадцать первый век",
    "1066 — Battle of Hastings": "1066 — Битва при Гастинге",
    "1776 — US Declaration of Independence": "1776 — Провозглашение независимости США",
    "1789-1799 — the French Revolution": "1789–1799 — Великая французская революция",
    "1939-1945 — Second World War": "1939–1945 — Вторая мировая война",
    "1989 — Fall of the Berlin Wall": "1989 — Падение Берлинской стены",
    "2012 — London Olympics": "2012 — Олимпиада в Лондоне",
    "I'd like some oil": "мне нужно масло",
    "can I check my tyre pressures here?": "тут можно проверить давление в колесах?",
    "my car's broken down": "моя машина сломалась",
    "my car won't start": "моя машина не заводится",
    "we've run out of petrol": "у нас закончилось топливо",
    "the battery's flat": "аккамулятор сел",
    "have you got any jump leads?": "у вас есть «крокодилы»?",
    "I've got a flat tyre": "у меня спущены колеса",
    "I've got a puncture": "у меня прокол",
    "the … isn't working": "… не работает",
    "the speedometer isn't working": "спидометр не работает",
    "the petrol gauge isn't working": "топливный датчик не работает",
    "the fuel gauge isn't working": "топливный датчик не работает",
    "the … aren't working": "… не работают",
    "the brake lights aren't working": "стоп-сигналы не работают",
    "the indicators aren't working": "габаритные огни не работают",
    "there's something wrong with the engine": "что-то не в порядке с мотором",
    "there's something wrong with the steering": "что-то не в порядке с рулевым управлением",
    "there's something wrong with the brakes": "что-то не в порядке с тормозами",
    "the car's losing oil": "в машине течет масло",
    "do you know what speed you were doing?": "вы знаете, с какой скоростью вы ехали?",
    "are you insured on this vehicle?": "у вас есть страховка на машину?",
    "could I see your insurance documents?": "покажите вашу страховку",
    "have you had anything to drink?": "вы принимали алкоголь?",
    "how much have you had to drink?": "сколько вы выпили?",
    "could you blow into this tube, please?": "дуньте, пожалуйста, в эту трубку",
    "Stop": "Стоп",
    "Give way": "Уступить дорогу",
    "No entry": "Нет проезда",
    "One way": "Односторонняя дорога",
    "Parking": "Стоянка",
    "No parking": "Стоянка запрещена",
    "No stopping": "Не останавливаться",
    "Vehicles will be clamped": "Транспортные средства будут блокированы",
    "Keep left": "Держитесь левой стороны",
    "Get in lane": "Придерживайтесь полосы",
    "Slow down": "Сбавить скорость",
    "No overtaking": "Обгон запрещен",
    "School": "Школа",
    "Low bridge": "Низкий мост",
    "Level crossing": "Железнодорожный переезд",
    "Bus lane": "Автобусная полоса",
    "No through road": "Нет проезда",
    "Caution": "Внимание",
    "Fog": "Туман",
    "Diversion": "Объезд",
    "Road closed": "Дорога закрыта",
    "Roadworks": "Дорожные работы",
    "Accident ahead": "Впереди авария",
    "Queue ahead": "Впереди пробка",
    "Queues after next junction": "Пробка после следующего перекрестка",
    "On tow": "На буксире",
    "Services": "Зона отдыха",
    "Air": "Воздух",
    "Water": "Вода",
    "Don't drink and drive": "Не садись за руль, если выпил",
    "how are you?": "как дела?",
    "how's it going?": "как оно? (дружеское)",
    "how are you doing?": "как поживаешь? (дружеское)",
    "how's life?": "как жизнь? (дружеское)",
    "how are things?": "как делишки? (дружеское)",
    "I'm fine, thanks": "прекрасно, спасибо",
    "I'm OK, thanks": "нормально, спасибо",
    "not too bad, thanks": "неплохо, спасибо",
    "alright, thanks": "в порядке, спасибо",
    "not so well": "не особо хорошо",
    "how about you?": "как ты?",
    "and you?": "а ты?",
    "and yourself?": "а сам?",
    "what are you up to?": "чем занимаешься?",
    "what have you been up to?": "чем занимался?",
    "working a lot": "много работал",
    "studying a lot": "много учился",
    "I've been very busy": "я был очень занят",
    "same as usual": "тем же, чем обычно",
    "not much": "ничем особенным",
    "not a lot": "ничем особенным",
    "I've just come back from …": "я только что вернулся из …",
    "I've just come back from Portugal": "я только что вернулся из Португалии",
    "I'm at home": "я дома",
    "I'm at work": "я на работе",
    "I'm in town": "я в городе",
    "I'm in the countryside": "я на природе",
    "I'm at the shops": "я в магазине",
    "I'm on a train": "я в поезде",
    "what do you like doing in your spare time?": "что тебе нравится делать в свободное время?",
    "I like watching TV": "мне нравится смотреть телевизор",
    "I like listening to music": "мне нравится слушать музыку",
    "I like walking": "мне нравится гулять",
    "I like jogging": "мне нравится бегать",
    "I quite like …": "мне в некоторой степени нравится …",
    "I quite like cooking": "мне в некоторой степени нравится готовить",
    "I quite like playing chess": "мне в некоторой степени нравится играть в шахматы",
    "I quite like yoga": "мне в некоторой степени нравится заниматься йогой",
    "I really like …": "мне очень нравится …",
    "I really like swimming": "мне очень нравится плавать",
    "I really like dancing": "мне очень нравится танцевать",
    "I love …": "я люблю …",
    "I love the theatre": "я люблю театр",
    "I love the cinema": "я люблю кино",
    "I love going out": "я люблю тусоваться",
    "I love clubbing": "я люблю ходить в клубы",
    "I enjoy travelling": "я люблю путешествовать",
    "I don't like pubs": "мне не нравятся пабы",
    "I don't like noisy bars": "мне не нравятся шумные бары",
    "I don't like nightclubs": "мне не нравятся ночные клубы",
    "what do you do for a living?": "чем ты зарабатываешь на жизнь?",
    "what sort of work do you do?": "какую работу ты выполняешь?",
    "what line of work are you in?": "в какой области ты работаешь?",
    "I'm a teacher": "я учитель",
    "I'm a student": "я студент",
    "I'm a doctor": "я врач",
    "I work as a …": "я работаю …",
    "I work as a journalist": "я работаю журналистом",
    "I work as a programmer": "я работаю программистом",
    "I work in television": "я работаю на телевидении",
    "I work in publishing": "я работаю в издательстве",
    "I work in PR": "я работаю по связям с общественностью",
    "I work in sales": "я работаю в торговле",
    "I work in IT": "я работаю в области инфо-технологий",
    "I work with …": "я работаю …",
    "I work with computers": "я работаю с компьютерами",
    "I work with children with disabilities": "я работаю с детьми-инвалидами",
    "I stay at home and look after the children": "я сижу дома и воспитываю детей",
    "can I park here?": "здесь можно припарковаться?",
    "where's the nearest petrol station?": "где ближайшая автозаправочная станция?",
    "how far is it to the next services?": "как далеко до следующего пункта обслуживания? (заправка, магазины, кафе, туалеты и т.д.)",
    "are we nearly there?": "мы уже почти на месте?",
    "please slow down!": "пожалуйста, помедленнее",
    "we've had an accident": "мы попали в аварию",
    "sorry, it was my fault": "извините, это моя ошибка",
    "it wasn't my fault": "я в этом не виноват",
    "you've left your lights on": "ты забыл выключить фары",
    "have you passed your driving test?": "ты сдал экзамен по вождению?",
    "full, please": "полный бак, пожалуйста",
    "£25 worth, please": "на 25 фунтов, пожалуйста",
    "it takes …": "машина заправляется …",
    "it takes petrol": "машина заправляется бензином",
    "it takes diesel": "машина заправляется дизелем",
    "it’s an electric car": "это электромобиль",
}