slovar = {
    "how long does the crossing take?": "как долго продлится рейс?",
    "what time does the ferry arrive in …?": "во сколько паром прибывает в …?",
    "what time does the ferry arrive in Stockholm?": "во сколько паром прибывает в Стокгольм?",
    "how soon before the departure time do we have to arrive?": "за какое время до отправления мы должны приехать?",
    "where's the information desk?": "где находится информационный пункт?",
    "where's cabin number …?": "где каюта номер …?",
    "where's cabin number 258?": "где каюта номер 258?",
    "which deck's the … on?": "на какой палубе находится …?",
    "which deck's the buffet on?": "на какой палубе находится буфет?",
    "which deck's the restaurant on?": "на какой палубе находится ресторан?",
    "which deck's the bar on?": "на какой палубе находится бар?",
    "which deck's the shop on?": "на какой палубе находится магазин?",
    "which deck's the cinema on?": "на какой палубе находится кино?",
    "which deck's the bureau de change on?": "на какой палубе находится пункт обмена валюты?",
    "I feel seasick": "у меня морская болезнь",
    "the sea's very rough": "на море шторм",
    "the sea's quite calm": "на море довольно спокойно",
    "all car passengers, please make your way down to the car decks for disembarkation": "все пассажиры, пожалуйста проследуйте на автомобильную палубу для высадки",
    "we will be arriving in port in approximately 30 minutes' time": "мы прибудем в порт примерно через 30 минут",
    "please vacate your cabins": "пожалуйста, освободите каюты",
    "Cabin": "Каюта",
    "Deck": "Палуба",
    "Stairs": "Лестница",
    "Cinema": "Кино",
    "Shop": "Магазин",
    "Lifejackets": "Спасательные жилеты",
    "I've come to collect my tickets": "я хотел бы забрать свой билет",
    "I booked on the internet": "я заказал билет в интернете",
    "do you have your booking reference?": "у вас есть код брони?",
    "your passport and ticket, please": "ваш паспорт и билет, пожалуйста",
    "here's my booking reference": "это мой код бронирования",
    "where are you flying to?": "куда вы летите?",
    "did you pack your bags yourself?": "вы сами упаковывали свои вещи?",
    "has anyone had access to your bags in the meantime?": "кто-нибудь имел доступ к вашим вещам?",
    "do you have any liquids or sharp objects in your hand baggage?": "в важем багаже есть жидкости или острые предметы?",
    "how many bags are you checking in?": "сколько сумок вы сдаёте?",
    "could I see your hand baggage, please?": "покажите вашу ручную кладь, пожалуйста",
    "do I need to check this in or can I take it with me?": "я должен это сдать или могу взять с собой?",
    "there's an excess baggage charge of …": "дополнительная плата за багаж …",
    "there's an excess baggage charge of £30": "дополнительная плата за багаж 30 фунтов",
    "would you like a window or an aisle seat?": "вы хотите сидеть у окна или в проходе?",
    "enjoy your flight!": "счастливого полета!",
    "where can I get a trolley?": "где находятся тележки?",
    "are you carrying any liquids?": "у вас есть с собой какие-либо жидкости?",
    "could you take off your …, please?": "снимите …, пожалуйста",
    "could you take off your coat, please?": "снимите пальто, пожалуйста",
    "could you take off your shoes, please?": "снимите обувь, пожалуйста",
    "could you take off your belt, please?": "снимите ремень, пожалуйста",
    "could you put any metallic objects into the tray, please?": "полажите металлические предметы на поднос, пожалуйста",
    "please empty your pockets": "освободите карманы, пожалуйста",
    "please take your laptop out of its case": "пожалуйста достаньте ноутбук из сумки",
    "I'm afraid you can't take that through": "к сожалению, вы не можете взять это собой",
    "what's the flight number?": "какой номер рейса?",
    "which gate do we need?": "какие у нас ворота?",
    "last call for passenger Smith travelling to Miami, please proceed immediately to Gate number 32": "последний вызов пассажира Смита, путешествующего в Майами, пожалуйста пройдите к воротам номер 32",
    "the flight's been delayed": "рейс задерживается",
    "the flight's been cancelled": "рейс отменён",
    "we'd like to apologise for the delay": "мы хотели бы извиниться за задержку",
    "could I see your passport and boarding card, please?": "покажите ваш паспорт и посадочный билет, пожалуйста",
    "what's your seat number?": "какой у вас номер места?",
    "could you please put that in the overhead locker?": "уберите это, пожалуйста, в верхнее отделение",
    "please pay attention to this short safety demonstration": "пожалуйста, обратите внимание на эту небольшую презентацию",
    "please turn off all mobile phones and electronic devices": "пожалуйста, отключите мобильные телефоны и электронные приборы",
    "the captain has turned off the Fasten Seatbelt sign": "капитан выключил сигнал «Пристегнуть ремни»",
    "how long does the flight take?": "сколько времени продлится полет?",
    "would you like any food or refreshments?": "вы желаете еду или напитки?",
    "the captain has switched on the Fasten Seatbelt sign": "капитан включил сигнал «Пристегнуть ремни»",
    "we'll be landing in about fifteen minutes": "мы приземлимся примерно через 15 минут",
    "please fasten your seatbelt and return your seat to the upright position": "пожалуйста, пристегните ремни и верните кресло в исходное положение",
    "please stay in your seat until the aircraft has come to a complete standstill and the Fasten Seatbelt sign has been switched off": "пожалуйста, не вставайте до полной остановки самолета и выключения сигнала «Пристегнуть ремни»",
    "the local time is …": "местное время …",
    "the local time is 9.34pm": "местное время 21:34",
    "Short stay": "Краткосрочная парковка",
    "Short stay car park": "Краткосрочная парковка",
    "Long stay": "Долгосрочная парковка",
    "Long stay car park": "Долгосрочная парковка",
    "Arrivals": "Прибытие",
    "Departures": "Отправление",
    "International check-in": "Международная регистрация",
    "International departures": "Прибытие международных рейсов",
    "Domestic flights": "Местные рейсы",
    "Toilets": "Туалеты",
    "Information": "Информация",
    "Ticket offices": "Кассы",
    "Lockers": "Хранилище",
    "Payphones": "Телефон-автомат",
    "Restaurant": "Ресторан",
    "Check-in closes 40 minutes before departure": "Регистрация закрывается за 40 минут до отправления",
    "Gates 1-32": "Ворота 1—32",
    "Tax free shopping": "Магазины такс-фри",
    "Duty free shopping": "Магазины дьюти-фри",
    "Transfers": "Пересадка",
    "Flight connections": "Пересадка",
    "Baggage reclaim": "Выдача багажа",
    "Passport control": "Паспортный контроль",
    "Customs": "Таможня",
    "Car hire": "Прокат автомобилей",
    "Departures board": "Отправляющиеся рейсы",
    "Check-in open": "Регистрация открыта",
    "Go to Gate ...": "Пройдите к воротам ...",
    "Now boarding": "Посадка",
    "Last call": "Последний вызов",
    "Gate closing": "Ворота закрываются",
    "Gate closed": "Ворота закрыты",
    "Departed": "Вылетел",
    "Arrivals board": "Прибывающие рейсы",
    "Expected 23:25": "Ожидается в 23:25",
    "Landed 09:52": "Приземлился в 09:52",
    "where's the ticket office?": "где находятся кассы?",
    "where are the ticket machines?": "где находятся билетные автоматы?",
    "what time's the next bus to …?": "во сколько идет следующий автобус на …?",
    "what time's the next bus to Camden?": "во сколько идет следующий автобус на Камден?",
    "Camden": "во сколько идет следующий поезд на …?",
    "can I buy a ticket on the bus?": "можно купить билет в автобусе?",
    "can I buy a ticket on the train?": "можно купить билет в поезде?",
    "how much is a … to London?": "сколько стоит … до Лондона?",
    "how much is a single to London?": "сколько стоит билет в один конец до Лондона?",
    "how much is a return to London?": "сколько стоит билет в оба конца до Лондона?",
    "how much is a first class single to London?": "сколько стоит билет первого класса в один конец до Лондона?",
    "how much is a first class return to London?": "сколько стоит билет первого класса в оба конца до Лондона?",
    "I'd like a … to Bristol": "я хотел бы … до Бристоля",
    "breakfast's from 7am till 10am": "завтрак с 7 до 10 часов",
    "could I have breakfast in my room, please?": "могу я заказать завтрак в комнату, пожалуйста?",
    "what time's the restaurant open for dinner?": "во сколько ресторан открывается для ужина?",
    "dinner's served between 6pm and 9.30pm": "ужин подается с шести до половины десятого",
    "what time does the bar close?": "во сколько закрывается бар?",
    "would you like any help with your luggage?": "вам нужна помощь с багажом?",
    "here's your room key": "это ваш ключ от номера",
    "your room number's …": "ваш номер …",
    "your room number's 326": "ваш номер 326",
    "your room's on the … floor": "ваш номер на … этаже",
    "your room's on the first floor": "ваш номер на втором этаже",
    "your room's on the second floor": "ваш номер на третьем этаже",
    "your room's on the third floor": "ваш номер на четвертом этаже",
    "where are the lifts?": "где находятся лифты?",
    "Reception": "Регистрация",
    "Concierge": "Консьерж",
    "Lifts": "Лифты",
    "Bar": "Бар",
    "do you have any vacancies?": "у вас есть свободные места?",
    "from what date?": "с какого числа?",
    "for how many nights?": "на сколько дней?",
    "how long will you be staying for?": "как долго вы собираетесь пребывать?",
    "one night": "один день",
    "two nights": "два дня",
    "a week": "неделю",
    "a fortnight": "две недели",
    "two weeks": "две недели",
    "what sort of room would you like?": "какую комнату желаете?",
    "I'd like a …": "я желаю …",
    "I'd like a single room": "я желаю номер на одного",
    "I'd like a double room": "я желаю номер на двоих",
    "I'd like a twin room": "я желаю номер с двумя кроватями",
    "I'd like a triple room": "я желаю номер с тремя кроватями",
    "I'd like a suite": "я желаю номер-люкс",
    "I'd like a room with …": "я хотел бы номер с …",
    "I'd like a room with an en-suite bathroom": "я хотел бы номер с ванной комнатой",
    "I'd like a room with a bath": "я хотел бы номер с ванной",
    "I'd like a room with a shower": "я хотел бы номер с душем",
    "I'd like a room with a view": "я хотел бы номер с красивым видом",
    "I'd like a room with a sea view": "я хотел бы номер с видом на море",
    "I'd like a room with a balcony": "я хотел бы номер с балконом",
    "I'd like …": "я хотел бы …",
    "I'd like half board": "я хотел бы половину пансиона",
    "I'd like full board": "я хотел бы полный пансион",
    "could we have an extra bed?": "мы хотели бы дополнительную кровать",
    "does the room have …?": "есть ли в комнате …?",
    "does the room have internet access?": "есть ли в комнате интернет?",
    "does the room have air conditioning?": "есть ли в комнате кондиционер?",
    "does the room have television?": "есть ли в комнате телевизор?",
    "is there a …?": "есть ли тут …?",
    "is there a swimming pool?": "есть ли тут бассейн?",
    "is there a sauna?": "есть ли тут сауна?",
    "is there a gym?": "есть ли тут спортзал?",
    "is there a beauty salon?": "есть ли тут салон красоты?",
    "is there a lift?": "есть ли тут лифт?",
    "do you allow pets?": "здесь можно держать домашних животных?",
    "do you have wheelchair access?": "у вас есть вход для инвалидной коляски?",
    "do you have a car park?": "у вас есть автомобильная стоянка?",
    "the room has a shared bathroom": "туалет и ванная общие",
    "what's the price per night?": "сколько стоит одна ночь?",
    "is breakfast included?": "включен ли завтрак?",
    "that's a bit more than I wanted to pay": "это не много больше, чем я готов заплатить",
    "can you offer me any discount?": "вы можете сделать скидку?",
    "have you got anything …?": "у вас есть что-нибудь …?",
    "have you got anything cheaper?": "у вас есть что-нибудь подешевле?",
    "have you got anything bigger?": "у вас есть что-нибудь побольше?",
    "have you got anything quieter?": "у вас есть что-нибудь поспокойней?",
    "could I see the room?": "мог бы я посмотреть комнату?",
    "OK, I'll take it": "хорошо, я беру",
    "I'd like to make a reservation": "я хотел бы забронировать",
    "what's your name, please?": "ваше имя, пожалуйста",
    "could I take your name?": "назовите ваше имя",
    "can I take your …?": "назовите ваш …",
    "can I take your credit card number?": "назовите ваш номер кредитки",
    "can I take your telephone number?": "назовите ваш номер телефона",
    "what time will you be arriving?": "во сколько вы приедете?",
    "Vacancies": "Свободные места",
    "No vacancies": "Свободных мест нет",
    "can you recommend any good …?": "вы можете порекомендовать хорошие …?",
    "can you recommend any good hotels?": "вы можете порекомендовать хорошие гостиницы?",
    "can you recommend any good B&Bs?": "вы можете порекомендовать хорошие B&Bs (небольшие бюджетные гостиницы, в цену включен завтрак)?",
    "can you recommend any good self-catering apartments?": "вы можете порекомендовать хорошие съёмные квартиры?",
    "can you recommend any good youth hostels?": "вы можете порекомендовать хорошие молодежные хостелы?",
    "can you recommend any good campsites?": "вы можете порекомендовать хорошие места для кемпинга?",
    "how many stars does it have?": "сколько у него звёздочек?",
    "I'd like to stay in the city centre": "я хотел бы остановиться в центре города",
    "how much do you want to pay?": "сколько вы хотите заплатить?",
    "how far is it from the …?": "как далеко это от …?",
    "how far is it from the city centre?": "как далеко это от центра города?",
    "how far is it from the airport?": "как далеко это от аэропорта?",
    "how far is it from the railway station?": "как далеко это от железнодорожного вокзала?",
    "could I see your passport, please?": "пожалуйста, покажите ваш паспорт",
    "where have you travelled from?": "откуда вы прибыли?",
    "what's the purpose of your visit?": "какая цель вашего визита?",
    "I'm on holiday": "я в отпуске",
    "I'm on business": "это деловая поездка",
    "I'm visiting relatives": "я приехал к родственникам",
    "how long will you be staying?": "как долго вы собираетесь здесь пробыть?",
    "where will you be staying?": "где вы будете жить?",
    "you have to fill in this …": "вы должны заполнить …",
    "you have to fill in this landing card": "вы должны заполнить карту прибытия",
    "you have to fill in this immigration form": "вы должны заполнить иммиграционную карту",
    "enjoy your stay!": "хорошего пребывания!",
    "could you open your bag, please?": "откройте вашу сумку, пожалуйста",
    "do you have anything to declare?": "у вас есть что-нибудь, подлежащее декларации?",
    "you have to pay duty on these items": "вы должны уплатить за это пошлину",
    "EU citizens": "Граждане ЕС",
    "All passports": "Все паспорта",
    "Wait behind the yellow line": "Ждите за жёлтой чертой",
    "Please have your passport ready": "Пожалуйста, приготовьте паспорт",
    "Nothing to declare": "Нечего декларировать",
    "Goods to declare": "Вещи, подлежащие декларации",
    "what time's the next boat to …?": "во сколько следующий корабль на …?",
    "what time's the next boat to Calais?": "во сколько следующий корабль на Кале?",
    "I'd like a … cabin": "я хотел бы … каюту",
    "I'd like a two-berth cabin": "я хотел бы двух-местную каюту",
    "I'd like a four-berth cabin": "я хотел бы четырех-местную каюту",
    "we don't need a cabin": "нам не нужна каюта",
    "I'd like a ticket for a car and two passengers": "я хотел бы билет на машину и двух пассажиров",
    "I'd like a ticket for a foot passenger": "я хотел бы билет для пассажира",
    "another beer, please": "ещё пива, пожалуйста",
    "another two beers, please": "ещё два пива, пожалуйста",
    "same again, please": "то же самое, пожалуйста",
    "are you still serving drinks?": "вы ещё подаёте выпить?",
    "last orders!": "последние заказы!",
    "do you have any snacks?": "у вас есть какие-нибудь закуски?",
    "do you have any sandwiches?": "у вас есть какие-нибудь бутерброды?",
    "do you serve food?": "вы подаёте поесть?",
    "what time does the kitchen close?": "во-сколько закрывается кухня?",
    "are you still serving food?": "вы ещё подаёте поесть?",
    "a packet of crisps, please": "пачку чипсов, пожалуйста",
    "what flavour would you like?": "с каким вкусом вы бы хотели?",
    "ready salted": "соленые",
    "cheese and onion": "сыр с луком",
    "salt and vinegar": "соль и уксус",
    "what sort of sandwiches do you have?": "какие у вас есть бутерброды?",
    "do you have any hot food?": "у вас есть какая-нибудь горячая еда?",
    "today's specials are on the board": "сегодняшние специальные блюда написаны на доске",
    "is it table service or self-service?": "этот столик обслуживается или надо самим заказывать?",
    "would you like anything to eat?": "вы хотите что-нибудь поесть?",
    "could we see a menu, please?": "мы могли бы посмотреть меню, пожалуйста?",
    "eat in or take-away?": "здесь или с собой?",
    "does anyone fancy a game of …?": "кто-нибудь хочет поиграть в …?",
    "does anyone fancy a game of pool?": "кто-нибудь хочет поиграть в бильярд?",
    "does anyone fancy a game of darts?": "кто-нибудь хочет поиграть в дартс?",
    "does anyone fancy a game of cards?": "кто-нибудь хочет поиграть в карты?",
    "do you have internet access here?": "здесь есть интернет?",
    "do you have wireless internet here?": "здесь есть беспроводной интернет?",
    "what’s the password for the internet?": "какой пароль для интернета?",
    "I feel fine": "я прекрасно себя чувствую",
    "I feel terrible": "я ужасно себя чувствую",
    "I've got a hangover": "у меня похмелье",
    "I'm never going to drink again!": "я никогда больше не буду пить!",
    "do you smoke?": "ты куришь?, вы курите?",
    "no, I don't smoke": "нет, я не курю",
    "I've given up": "я бросил",
    "do you mind if I smoke?": "ты не против, если я закурю?",
    "would you like a cigarette?": "хочешь сигарету?",
    "have you got a light?": "у тебя есть прикурить?",
    "do you know any good restaurants?": "вы знаете какой-нибудь приличный ресторан?",
    "where's the nearest restaurant?": "где находится ближайший ресторан?",
    "can you recommend a good pub near here?": "можете порекомендовать хороший паб неподолёку?",
    "do you fancy a pint?": "может выпьем пива? (дружеское)",
    "do you fancy a quick drink?": "может зайдём выпьем что-нибудь? (дружеское)",
    "shall we go for a drink?": "может пойдем выпьем?",
    "do you know any good places to …?": "ты знаешь какое-нибудь хорошее место, чтобы …?",
    "do you know any good places to eat?": "ты знаешь какое-нибудь хорошее место, чтобы поесть?",
    "do you know any good places to get a sandwich?": "ты знаешь какое-нибудь хорошее место, чтобы съесть бутерброд?",
    "do you know any good places to go for a drink?": "ты знаешь какое-нибудь хорошее место, чтобы выпить?",
    "shall we get a take-away?": "может закажем с собой?",
    "let's eat out tonight": "давай поедим где-нибудь сегодня вечером",
    "would you like to …?": "ты хотел бы …?",
    "would you like to come for a drink after work?": "ты хотел бы пойти выпить после работы?",
    "would you like to come for a coffee?": "ты хотел бы выпить кофе?",
    "would you like to join me for lunch?": "ты хотел бы пообедать со мной?",
    "would you like to join me for dinner?": "ты хотел бы поужинать со мной?",
    "Reserved": "Резервировано",
    "No smoking": "Не курить",
    "I'd like to check out": "я хотел бы выехать",
    "I'd like to pay my bill, please": "я хотел бы оплатить счёт, пожалуйста",
    "I think there's a mistake in this bill": "я думаю, что счёт неправильный",
    "how would you like to pay?": "как вы желаете платить?",
    "I'll pay …": "я заплачу …",
    "I'll pay by credit card": "я заплачу кредитной карточкой",
    "I'll pay in cash": "я заплачу наличными",
    "have you used the minibar?": "вы пользовались мини-баром?",
    "we haven't used the minibar": "мы не пользовались мини-баром",
    "could we have some help bringing our luggage down?": "помогите нам снести вниз багаж, пожалуйста",
    "do you have anywhere we could leave our luggage?": "мы могли бы где-то оставить багаж?",
    "I hope you had an enjoyable stay": "надеюсь, ваше пребывание было приятным",
    "I've really enjoyed my stay": "мое пребывание было очень приятным",
    "we've really enjoyed our stay": "наше пребывание было очень приятным",
    "my room number's …": "мой номер …",
    "my room number's 215": "мой номер 215",
    "could I have a wake-up call at seven o'clock?": "могли бы вы разбудить меня в семь часов?",
    "where do we have breakfast?": "где мы завтракаем?",
    "where's the restaurant?": "где находится ресторан?",
    "could you please call me a taxi?": "вызовите мне, пожалуйста, такси",
    "do you lock the front door at night?": "вы закрываете вход на ночь?",
    "if you come back after midnight, you'll need to ring the bell": "если вы вернётесь после полуночи, позвоните в дверь",
    "I'll be back around ten o'clock": "я вернусь около десяти часов",
    "could I see your key, please?": "покажите ваш ключ, пожалуйста",
    "are there any laundry facilities?": "тут можно постирать?",
    "what time do I need to check out?": "во сколько я должен выехать?",
    "would it be possible to have a late check-out?": "возможно ли выехать попозже?",
    "the key doesn't work": "ключ не работает",
    "there isn't any hot water": "нет горячей воды",
    "the room's too …": "в комнате слишком …",
    "the room's too hot": "в комнате слишком жарко",
    "the room's too cold": "в комнате слишком холодно",
    "the room's too noisy": "в комнате слишком шумно",
    "the … doesn't work": "… не работает",
    "the heating doesn't work": "отопление не работает",
    "the shower doesn't work": "душ не работает",
    "the television doesn't work": "телевизор не работает",
    "one of the lights isn't working": "одна лампа не работает",
    "there's no …": "там нет …",
    "there's no toilet paper": "там нет туалетной бумаги",
    "there's no soap": "там нет мыла",
    "there's no shampoo": "там нет шампуня",
    "could I have a towel, please?": "не могли бы вы дать мне полотенце,",
    "could I have an extra blanket?": "не могли бы вы дать мне дополнительное одеяло, пожалуйста?",
    "my room's not been made up": "моя комната не прибрана",
    "could you please change the sheets?": "поменяйте постельное бельё, пожалуйста",
    "I've lost my room key": "я потерял ключ от номера",
    "Do not disturb": "Не беспокоить",
    "Please make up room": "Пожалуйста, приберитесь в комнате",
    "Lift out of order": "Лифт не работает",
    "I've got a reservation": "у меня забронировано",
    "your name, please?": "ваше имя, пожалуйста",
    "my name's …": "мое имя …",
    "my name's Mark Smith": "мое имя Марк Смит",
    "could I see your passport?": "покажите паспорт, пожалуйста",
    "could you please fill in this registration form?": "заполните регистрационную карту, пожалуйста",
    "my booking was for a twin room": "я бронировал номер с двумя кроватями",
    "my booking was for a double room": "я бронировал двухместный номер (с одной кроватью)",
    "would you like a newspaper?": "желаете газету?",
    "would you like a wake-up call?": "желаете, чтобы мы вас разбудили?",
    "what time's breakfast?": "во сколько завтрак?",
    "this evening at seven o'clock": "сегодня вечером в семь часов",
    "this evening at seven thirty": "сегодня вечером в семь тридцать",
    "this evening at eight o'clock": "сегодня вечером в восемь часов",
    "this evening at eight thirty": "сегодня вечером в восемь тридцать",
    "tomorrow at …": "затра в …",
    "tomorrow at noon": "затра в полдень",
    "tomorrow at twelve thirty": "затра в двенадцать тридцать",
    "tomorrow at one o'clock": "затра в час",
    "tomorrow at one thirty": "затра в час тридцать",
    "for how many people?": "на сколько людей?",
    "do you have a reservation?": "у вас зарезервировано?",
    "could I see the menu, please?": "могу я посмотреть меню, пожалуйста?",
    "could I see the wine list, please?": "могу я посмотреть карту вин, пожалуйста?",
    "can I get you any drinks?": "могу я принести вам что-нибудь выпить?",
    "are you ready to order?": "вы готовы заказать?",
    "do you have any specials?": "у вас есть специальные блюда?",
    "what's the soup of the day?": "какой сегодня суп?",
    "what do you recommend?": "что вы порекомендуете?",
    "what's this dish?": "что это за блюдо?",
    "I'm on a diet": "я на диете",
    "I'm allergic to …": "у меня аллергия на …",
    "I'm allergic to wheat": "у меня аллергия на пшеницу",
    "I'm allergic to dairy products": "у меня аллергия на молочные продукты",
    "I'm severely allergic to …": "у меня сильная аллергия на …",
    "I'm severely allergic to nuts": "у меня сильная аллергия на орехи",
    "I'm severely allergic to shellfish": "у меня сильная аллергия на моллюски",
    "I'm a vegetarian": "я вегетарианец / вегетарианка",
    "I don't eat …": "я не ем …",
    "I don't eat meat": "я не ем мясо",
    "I don't eat pork": "я не ем свинину",
    "I'll have the …": "я буду …",
    "I'll have the chicken breast": "я буду куриные грудки",
    "I'll have the roast beef": "я буду ростбиф",
    "I'll have the pasta": "я буду макароны",
    "I'll take this": "я возьму это",
    "I'm sorry, we're out of that": "извините, у нас это закончилось",
    "for my starter I'll have the soup, and for my main course the steak": "для начала я возьму суп, а как основное блюдо — кусок мяса",
    "how would you like your steak?": "какой прожарки вы желаете мясо?",
    "rare": "с кровью",
    "medium-rare": "немного с кровью",
    "medium": "средней прожарки",
    "well done": "хорошо прожарить",
    "is that all?": "это всё?",
    "would you like anything else?": "желаете что-нибудь ещё?",
    "nothing else, thank you": "больше ничего, спасибо",
    "we're in a hurry": "мы торопимся",
    "how long will it take?": "как скоро будет готово?",
    "it'll take about twenty minutes": "будет готово примерно через двадцать минут",
    "excuse me!": "извините!",
    "enjoy your meal!": "приятного аппетита!",
    "bon appétit!": "приятного аппетита!",
    "would you like to taste the wine?": "вы желаете попробовать вино?",
    "could we have …?": "мы хотели бы …",
    "could we have another bottle of wine?": "мы хотели бы ещё бутылку винаs",
    "could we have some more bread?": "мы хотели бы ещё хлеба",
    "could we have some more milk?": "мы хотели бы ещё молока",
    "could we have a jug of tap water?": "мы хотели бы кувшин воды из под крана",
    "could we have some water?": "мы хотели бы воды",
    "still or sparkling?": "без газов или с газами?",
    "would you like any coffee or dessert?": "вы хотите кофе или десерт?",
    "do you have any desserts?": "у вас есть какие-нибудь десерты?",
    "could I see the dessert menu?": "принесите меню с десертами",
    "was everything alright?": "всё было в порядке?",
    "thanks, that was delicious": "спасибо, это было очень вкусно",
    "this isn't what I ordered": "это не то, что я заказал(а)",
    "this food's cold": "еда холодная",
    "this is too salty": "блюдо слишком соленое",
    "this doesn't taste right": "вкус какой-то странный",
    "we've been waiting a long time": "мы долго ждали",
    "is our meal on its way?": "наш заказ уже готов?",
    "will our food be long?": "долго ждать пока приготовят?",
    "the bill, please": "счёт, пожалуйста",
    "could we have the bill, please?": "могли бы мы получить счёт, пожалуйста",
    "can I pay by card?": "можно заплатить карточкой?",
    "do you take credit cards?": "вы принимаете кредитные карточки?",
    "is service included?": "плата за обслуживание включена?",
    "can we pay separately?": "можем мы заплатить раздельно?",
    "I'll get this": "я буду это",
    "let's split it": "давайте разделим на двоих",
    "let's share the bill": "давайте заплатим вместе",
    "Please wait to be seated": "Пожалуйста подождите, вас посадят",
    "Service included": "Чаевые включены в цену",
    "Service not included": "Чаевые не включены в цену",
    "what would you like to drink?": "что бы вы хотели выпить? , что ты хотел бы выпить? (бармен клиентудруг другу)",
    "what are you having?": "что ты будешь?",
    "what can I get you?": "что я могу предложить?",
    "I'll have …, please": "я бы хотел …, пожалуйста",
    "I'll have a pint of lager, please": "я бы хотел пинту светлого пива (одна пинта немного больше половины литра), пожалуйста",
    "I'll have a pint of bitter, please": "я бы хотел пинту биттера (сорт традиционного английского пиво), пожалуйста",
    "I'll have a glass of white wine, please": "я бы хотел бокал белого вина, пожалуйста",
    "I'll have a glass of red wine, please": "я бы хотел бокал красного вина, пожалуйста",
    "I'll have an orange juice, please": "я бы хотел апельсиновый сок, пожалуйста",
    "I'll have a coffee, please": "я бы хотел кофе, пожалуйста",
    "I'll have a Coke, please": "я бы хотел кока-колу, пожалуйста",
    "I'll have a Diet Coke, please": "я бы хотел диетическую кока-колу, пожалуйста",
    "large or small?": "большой стакан или маленький?",
    "would you like ice with that?": "желаете со льдом?",
    "no ice, please": "без льда, пожалуйста",
    "a little, please": "немного, пожалуйста",
    "lots of ice, please": "много льда, пожалуйста",
    "a beer, please": "пиво, пожалуйста",
    "two beers, please": "два пива, пожалуйста",
    "three shots of tequila, please": "три стопки текилы, пожалуйста",
    "are you being served?": "вас уже обслуживают?",
    "I'm being served, thanks": "меня уже обслуживают, спасибо",
    "who's next?": "кто следующий?",
    "which wine would you like?": "какое вино вы бы хотели?",
    "house wine is fine": "столовое вино подойдёт",
    "which beer would you like?": "какое пиво вы бы хотели?",
    "would you like draught or bottled beer?": "вы желаете разливное или бутылочное пиво?",
    "I'll have the same, please": "я буду то же самое, пожалуйста",
    "nothing for me, thanks": "для меня ничего, спасибо",
    "I'll get these": "я буду это",
    "keep the change!": "оставьте сдачу себе!",
    "cheers!": "за здоровье!",
    "whose round is it?": "чья очередь платить?",
    "it's my round": "моя очередь",
    "it's your round": "твоя очередь",
    "Womenswear": "Женская одежда",
    "Ladieswear": "Женская одежда",
    "Childrenswear": "Детская одежда",
    "Babywear": "Одежда для малышей",
    "Fitting room": "Примерочные кабинки",
    "Size": "Размер",
    "S": "Маленький",
    "Small": "Маленький",
    "M": "Средний",
    "Medium": "Средний",
    "L": "Большой",
    "Large": "Большой",
    "XL": "Очень Большой",
    "Extra-large": "Очень Большой",
    "could you tell me where the milk is?": "могли бы вы сказать где молоко?",
    "could you tell me where the bread counter is?": "могли бы вы сказать где хлебный прилавок?",
    "could you tell me where the meat section is?": "могли бы вы сказать где мясной отдел?",
    "could you tell me where the frozen food section is?": "могли бы вы сказать где отдел замороженной пищи?",
    "I'd like that piece of cheese": "я хотел бы этот кусочек сыра",
    "I'd like a slice of pizza": "я хотел бы ломтик пиццы",
    "I'd like six slices of ham": "я хотел бы шесть ломтиков ветчины",
    "I'd like some olives": "я хотел бы оливки",
    "how much would you like?": "сколько вы хотели бы?",
    "300 grams": "300 грамм",
    "half a kilo": "полкило",
    "two pounds": "два фунта (один фунт ― приблизительно 450 граммов)",
    "that's £32.47": "это стоит 32,47 фунта",
    "could I have a carrier bag, please?": "можно пакет, пожалуйста?",
    "could I have another carrier bag, please?": "можно ещё пакет, пожалуйста?",
    "do you need any help packing?": "помочь вам упаковать?",
    "do you have a loyalty card?": "у вас есть клиентская карточка?",
    "could you ask him to call me?": "вы можете попросить его позвонить мне?",
    "could you ask her to call me?": "вы можете попросить её позвонить мне?",
    "can I take your number?": "могу я узнать ваш номер?",
    "what's your number?": "какой у вас номер?",
    "could I take your name and number, please?": "могу я узнать ваше имя и номер, пожалуйста?",
    "I'll call back later": "я перезвоню позже",
    "is it convenient to talk at the moment?": "вам удобно сейчас разговаривать?",
    "can I call you back?": "могу я вам перезвонить?",
    "please call back later": "пожалуйста, перезвоните позже",
    "thanks for calling": "спасибо, что позвонили",
    "how do I get an outside line?": "как выйти на внешнюю линию?",
    "have you got a telephone directory?": "у вас есть телефонный справочник?",
    "can I use your phone?": "можно воспользоваться вашим телефоном?",
    "I'm sorry, I'm not interested": "извините, я не заинтересован",
    "sorry, I'm busy at the moment": "извините, я сейчас занят",
    "I can't get a dialling tone": "нет гудка",
    "the line's engaged": "линия занята",
    "I can't get through at the moment": "я не могу дозвониться",
    "I'm only getting an answering machine": "я попадаю на автоответчик",
    "sorry, you must have the wrong number": "извините, вы ошиблись номером",
    "can you hear me OK?": "вы меня хорошо слышите?",
    "I can't hear you very well": "я плохо вас слышу",
    "it's a bad line": "связь плохая",
    "could you please repeat that?": "повторите это ещё раз, пожалуйста?",
    "I've been cut off": "меня разъединили",
    "do you know the number for …?": "вы знаете номер …?",
    "do you know the number for directory enquiries?": "вы знаете номер справки телефонных номеров?",
    "do you know the number for international directory enquiries?": "вы знаете номер справки международных телефонных номеров?",
    "could you tell me the number for …?": "вы могли бы сказать мне номер …?",
    "could you tell me the number for the National Gallery?": "вы могли бы сказать мне номер Национальной галереи?",
    "do you know the address?": "вы знаете адрес?",
    "I'm afraid that number's ex-directory": "боюсь, что этого номера нет в справочнике",
    "could you tell me the dialing code for …?": "могли бы вы сказать мне код набора …?",
    "could you tell me the dialing code for Manchester?": "могли бы вы сказать мне код набора Манчестера?",
    "my battery's about to run out": "моя батарея почти разрядилась",
    "I need to charge up my phone": "мне нужно зарядить свой телефон",
    "I'm about to run out of credit": "у меня почти закончился кредит",
    "sorry, I ran out of credit": "извините, у меня закончился кредит",
    "I can't get a signal": "я не могу поймать сигнал",
    "I've got a very weak signal": "у меня очень слабый сигнал",
    "I'll send you a text": "я пошлю тебе сообщение",
    "I'll text you later": "я позже пошлю тебе сообщение",
    "could I borrow your phone, please?": "можно воспользоваться твоим телефоном, пожалуйста?",
    "I'd like a phonecard, please": "я хотел бы телефонную карточку, пожалуйста",
    "Thank you for calling.": "Спасибо, что позвонили.",
    "There's no-one here to take your call at the moment.": "Сейчас нет никого, кто мог бы ответить на ваш звонок.",
    "Please leave a message after the tone, and we'll get back to you as soon as possible.": "Пожалуйста, оставьте сообщение после сигнала, и мы свяжемся с вами",
    "I saw your advert in the paper": "я видел ваше объявление в газете",
    "could I have an application form?": "могу я получить анкету?",
    "could you send me an application form?": "могли бы вы прислать мне анкету?",
    "where do you work?": "где ты работаешь?",
    "I work in …": "я работаю …",
    "I work in an office": "я работаю в офисе",
    "I work in a shop": "я работаю в магазине",
    "I work in a restaurant": "я работаю в ресторане",
    "I work in a bank": "я работаю в банке",
    "I work in a factory": "я работаю на заводе",
    "I work in a call centre": "я работаю в телефонном центре",
    "I work from home": "я работаю на дому",
    "I'm training to be …": "я прохожу обучение, чтобы стать …",
    "I'm training to be an engineer": "я прохожу обучение, чтобы стать инженером",
    "I'm training to be a nurse": "я прохожу обучение, чтобы стать медсестрой",
    "I'm a trainee …": "я стажёр-…",
    "I'm a trainee accountant": "я стажёр-бухгалтер",
    "I'm a trainee supermarket manager": "я стажёр-менеджер в супермаркете",

}