slovar = {
    "that's fine, keep the change": "все в порядке, оставьте сдачу",
    "would you like a receipt?": "вы желаете чек?",
    "could you pick me up here at?": "могли бы вы забрать меня отсюда в ?",
    "could you pick me up here at six o'clock?": "могли бы вы забрать меня отсюда в шесть часов?",
    "taxis": "Такси",
    "for hire": "Свободно",
    "ok": "ладно",
    "of course": "конечно",
    "of course not": "конечно нет",
    "that's fine": "хорошо",
    "that's right": "точно",
    "sure": "конечно",
    "certainly": "непременно",
    "definitely": "определенно",
    "that's enough": "достаточно",
    "i've got to go": "мне нужно идти",
    "i'm going out я": "собираюсь прогуляться",
    "sleep well": "спи хорошо",
    "not bad": "неплохо",
    "i like": "мне нравится …",
    "i like it": "мне нравится это",
    "i don't like": "мне не нравится …",
    "i don't like him": "мне не нравится он",
    "i don't like it": "мне не нравится это",
    "thanks for your": "спасибо за …",
    "thanks for your help": "спасибо за помощь",
    "thanks for your hospitality": "спасибо за гостепреимство",
    "sorry i'm late": "извините за опоздание",
    "sorry for the delay": "извините за задержку",
    "look!": "посмотри!",
    "great!": "чудесно!",
    "come on!": "давай!",
    "only joking!": "шутка!",
    "that's funny!": "прикольно!",
    "that's life!": "такова жизнь!",
    "that's funny": "странно ...",
    "do you have a boyfriend?": "у тебя есть парень?",
    "do you have a girlfriend?": "у тебя есть девушка?",
    "are you married?": "ты женат?, ты замужем?",
    "are you seeing anyone?": "ты с кем-нибудь встречаешься?",
    "i'm single": "я холостой (незамужняя)",
    "i'm engaged": "я обручен(а)",
    "i'm married": "я женат (замужем)",
    "i'm divorced": "я в разводе",
    "i'm a widower": "я вдовец",
    "i'm seeing someone": "у меня уже кто-то есть",
    "help!": "помогите!",
    "look out!": "осторожно!",
    "watch out!": "осторожно!",
    "please help me": "пожалуйста, помогите мне",
    "call an ambulance!": "вызовите скорую помощь!",
    "i need a doctor": "мне нужен доктор",
    "there's been an accident": "произошел несчастный случай",
    "please hurry!": "пожалуйста, поторопитесь!",
    "i've burnt myself": "я обжегся",
    "are you OK?": "вы в порядке?",
    "is everyone OK?": "все в порядке?",
    "my wallet's been stolen": "мой кошелек украли",
    "my purse has been stolen": "мой сумочку украли",
    "my laptop's been stolen": "мой ноутбук украли",
    "i've been attacked": "на меня напали",
    "fire!": "пожар!",
    "can you smell burning?": "вы чувствуете запах гари?",
    "the building's on fire": "здание горит",
    "i'm lost": "я заблудился",
    "we're lost": "мы заблудились",
    "i can't find my": "я не могу найти …",
    "i can't find my passport": "я не могу найти мой паспорт",
    "i can't find my mobile": "я не могу найти мой мобильный телефон",
    "i've lost my wallet": "я потерял мой кошелек",
    "i've lost my purse": "я потерял мой бумажник",
    "i've lost my camera": "я потерял мой фотоаппарат",
    "i've locked myself out of my": "моя … закрылась, а ключи внутри",
    "i've locked myself out of my car": "моя машина закрылась, а ключи внутри",
    "please leave me alone": "пожалуйста, оставьте меня в покое",
    "yes": "да",
    "no": "нет",
    "perhaps": "может быть",
    "please": "пожалуйста",
    "thank you very much": "большое спасибо",
    "you're welcome": "пожалуйста",
    "don't mention it": "не за что",
    "hello": "здравствуйте",
    "good afternoon": "добрый день (используется с полудня до 6 часов вечера)",
    "bye": "пока",
    "goodbye": "до свидания",
    "goodnight": "спокойной ночи",
    "see you later!": "увидимся!",
    "have a nice day!": "хорошего дня!",
    "have a good weekend!": "хороших выходных!",
    "excuse me": "простите (может использоваться для привлечения внимания или при извинении)",
    "no problem": "ничего страшного",
    "don't worry about it": "не стоит беспокойства",
    "i don't speak much English": "я не очень хорошо говорю по-английски",
    "i only speak very little English": "я только чуть-чуть говорю по-английски",
    "please speak more slowly": "пожалуйста, говорите медленнее",
    "please write it down": "пожалуйста, напишите это",
    "i don't understand": "я не понимаю",
    "i don't know": "я не знаю",
    "excuse me, where's the toilet?": "извините, где находится туалет?",
    "excuse me, where's the Gents?": "извините, где мужской туалет?",
    "excuse me, where's the Ladies?": "извините, где женский туалет?",
    "entrance": "Вход",
    "push": "От себя",
    "gentlemen": "Мужчины",
    "gents": "Мужчины",
    "ladies": "Женщины",
    "vacant": "Свободно",
    "engaged": "Занято",
    "the day before yesterday": "позавчера",
    "yesterday": "вчера",
    "today": "сегодня",
    "tomorrow": "завтра",
    "the day after tomorrow": "послезавтра",
    "tonight": "сегодня вечером",
    "in the morning": "утром",
    "in the evening": "вечером",
    "yesterday morning": "вчера утром",
    "yesterday afternoon": "вчера днем",
    "yesterday evening": "вчера вечером",
    "this morning": "сегодня утром",
    "this afternoon": "сегодня днем",
    "tomorrow morning": "завтра утром",
    "tomorrow afternoon": "завтра днем",
    "tomorrow evening": "завтра вечером",
    "last week": "на прошлой неделе",
    "last month": "в прошлом месяце",
    "last year": "в прошлом году",
    "next week": "на следующей неделе",
    "next month": "в следующем месяце",
    "next year": "в следующем году",
    "somewhere": "где-то",
    "where are you?": "где ты?, где вы?",
    "what's that?": "что это там?",
    "is anything wrong?": "что-то не так?",
    "is everything ok?": "все в порядке?",
    "have you got a minute?": "у тебя есть свободная минутка?",
    "have you got a pen I could borrow?": "можно одолжить ручку?",
    "really?": "правда?",
    "why?": "почему?",
    "why not ?": "почему бы и нет?",
    "what happened?": "что случилось?",
    "what?": "что?",
    "where?": "где?",
    "when?": "когда?",
    "well done!": "хорошо сработано!",
    "bad luck!": "вот незадача!",
    "never mind!": "неважно!",
    "what a shame!": "как жаль!",
    "happy Christmas!": "счастливого Рождества!",
    "happy Valentine's Day!": "с днем святого Валентина!",
    "i'm exhausted": "я изможден",
    "i'm thirsty": "я хочу пить",
    "i'm bored": "мне скучно",
    "i'm worried": "я обеспокоен",
    "i'm in a good mood": "я в хорошем настороении",
    "i'm in a bad mood": "я в плохом настроении",
    "i can't be bothered": "не беспокойте меня",
    "welcome!": "добро пожаловать!",
    "see you tomorrow!": "до завтра!",
    "what do you think?": "что ты думаешь?",
    "i think that": "я думаю, что...",
    "i hope that": "я надеюсь, что...",
    "that's true": "это правда",
    "that's not true": "это не правда",
    "i hope not": "надеюсь, что нет",
    "you're right": "ты прав",
    "you're wrong": "ты не прав",
    "i don't mind": "я не возражаю",
    "it's up to you": "это зависит от тебя",
    "that depends": "смотря как",
    "that's interesting": "это интересно",
    "what languages can you speak?": "на каких языках вы говорите?",
    "i speak": "я говорю …",
    "i can get by in": "я неплохо говорю …",
    "i can get by in Italian": "я неплохо говорю по-итальянски",
    "i'm learning": "я учу …",
    "i'm learning Chinese": "я учу китайский",
    "at school": "в школе",
    "at university": "в университете",
    "i took a course": "я ходил на курсы",
    "did you understand?": "ты понял?",
    "yes, I understood": "да, я понял",
    "sorry, I didn't understand": "извини, я не понял",
    "excuse me?": "простите?",
    "how do you say ... in English?": "как будет по-английски ...?",
    "how do you spell that?": "как это пишется?",
    "you speak very good English": "ты очень хорошо говоришь по-английски",
    "your English is very good": "у тебя очень хороший английский",
    "i'm a little out of practice": "мне не хватает практики",
    "i'd like to practise my": "я хотел бы попрактиковаться в …",
    "i'd like to practise my Portuguese": "я хотел бы попрактиковаться в португальском",
    "let's speak in English": "давайте поговорим по-английски",
    "let's speak in Italian": "давайте поговорим по-итальянски",
    "where are the windscreen wipers?": "где включаются дворники?",
    "how do you open the?": "как открывается …?",
    "how do you open the bonnet?": "как открывается капот?",
    "do you know where I can get a taxi?": "ты знаешь, где можно поймать такси?",
    "do you have a taxi number?": "у тебя есть номер такси?",
    "I'd like a taxi, please": "я хотел бы заказать такси, пожалуйста",
    "what's the address?": "какой адрес?",
    "i'm": "я …",
    "i'm at the train station": "я на железнодорожном вокзале",
    "i'm at the corner of Oxford Street and Tottenham Court Road": "я на углу Оксфордстрит и Тоттенхэмкортроад",
    "could I take your name, please?": "назовите свое имя, пожалуйста",
    "how long will I have to wait?": "как долго ждать?",
    "how long will it be?": "сколько ждать?",
    "about ten minutes": "около десяти минут",
    "it's on its way": "машина в пути",
    "i'd like to go to charing Cross station": "я хотел бы поехать на станцию «Чаринг Кросс»",
    "could you take me to the city centre?": "не могли бы вы отвезти меня в центр города?",
    "how much would it cost to?": "сколько стоит доехать до …?",
    "could we stop at a cashpoint?": "могли бы мы остановиться у банкомата?",
    "please switch the meter on": "пожалуйста, включите таксометр",
    "do you mind if I close the window?": "вы не против, если я закрою окно?",
    "are we almost there?": "мы уже почти приехали?",
    "do you have any brothers or sisters?": "у тебя есть брат или сестра?",
    "yes, I've got an elder brother": "да, у меня есть старший брат",
    "yes, I've got a younger sister": "да, у меня есть младшая сестра",
    "yes, I've got two brothers": "да, у меня есть два брата",
    "yes, I've got one brother and two sisters": "да, у меня есть брат и две сестры",
    "no, I'm an only child": "нет, я единственный ребенок",
    "have you got any kids?": "у тебя есть дети?",
    "do you have any children?": "у тебя есть дети?",
    "yes, I've got three kids": "да, у меня три ребенка",
    "i don't have any children": "у меня нет детей",
    "do you have any grandchildren?": "у вас есть внуки?",
    "what do your parents do?": "чем занимаются твои родители?",
    "what does your father do?": "чем занимается твой отец?",
    "what does your mother do?": "чем занимается твоя мать?",
    "are your grandparents still alive?": "твои бабушка и дедушка еще живы?",
    "let me know if you can make it": "сообщи, если ты сможешь",
    "what's your address?": "какой твой адрес?",
    "i'm running a little late": "я немного опаздываю",
    "i'll be there in minutes": "я буду там через … минут",
    "i'll be there in five minutes": "я буду там через пять минут",
    "i'll be there in fifteen minutes": "я буду там через пятнадцать минут",
    "have you been waiting long?": "ты долго ждал?",
    "come on in!": "входи!, входите!",
    "good to see you!": "рад тебя видеть, рад вас видеть",
    "please take your shoes off": "пожалуйста, сними обувь, пожалуйста, снимите обувь",
    "can I take your coat?": "я возьму твое пальто",
    "did you have a good journey?": "ты хорошо добрался?, вы хорошо добрались?",
    "i'll show you your room": "я покажу твою комнату, я покажу вашу комнату",
    "would you like a towel?": "тебе нужно полотенце?",
    "make yourself at home": "чувствуй себя как дома, чувствуйте себя как дома",
    "would you like a tea or coffee?": "хочешь чай или кофе?, хотите чай или кофе?",
    "how do you take it?": "с чем ты хочешь?",
    "do you take milk?": "тебе нужно молоко?",
    "would you like a beer?": "хочешь пиво?",
    "would you like a glass of wine?": "хочешь бокал вина?",
    "have a seat!": "садись!, садитесь!",
    "let's go into the": "давай(те) пойдем в …",
    "let's go into the lounge": "давай(те) пойдем в гостиную",
    "do you mind if I smoke here?": "ты не против, если я здесь закурю?",
    "i'd prefer it if you went outside": "будет лучше, если ты выйдешь на улицу",
    "who's driving tonight?": "кто сегодня за рулем?",
    "damn it!": "проклятие!",
    "come in !": "войдите!",
    "could I have your attention, please?": "пожалуйста, внимание!",
    "let's go!": "пойдемте!",
    "hurry up!": "поторопись!",
    "calm down": "успокойся",
    "one moment, please": "один момент, пожалуйста",
    "please be quiet": "пожалуйста, успокойтесь",
    "shut up!": "замолчи!",
    "stop it!": "прекрати!",
    "don't forget": "не забудь",
    "help yourself": "угощайся",
    "go ahead": "давай",
    "let me know!": "сообщи мне!",
    "after you!": "после вас!",
    "i'd like a child single to Bristol": "я хотел бы детский билет в один конец до Бристоля",
    "i'd like a child return to Bristol": "я хотел бы детский билет в оба конца до Бристоля",
    "i'd like a senior citizens' return to Bristol": "я хотел бы пенсионерский билет в оба конца до Бристоля",
    "i'd like a first class single to Bristol": "я хотел бы билет первого класса в один конец до Бристоля",
    "are there any reductions for off-peak travel?": "есть ли скидки на билеты не в час-пик?",
    "i'd like a return to, coming back on Sunday": "я хотел бы билет в оба конца до …, с возвратом в воскресенье",
    "which platform do I need for Manchester?": "какая платформа на Манчестер?",
    "is this the right platform for?": "это правильная платформа для …?",
    "is this the right platform for Cardiff?": "это правильная платформа для Кардиффа?",
    "where do I change for?": "где мне надо сделать пересадку на …?",
    "you'll need to change at": "вам надо сделать пересадку в …",
    "can I have a timetable, please?": "не могли бы вы дать мне расписание, пожалуйста?",
    "how often do the trains run to?": "как часто ходят поезда на …?",
    "how often do the trains run to Coventry?": "как часто ходят поезда на Ковентри?",
    "the next train to arrive at Platform 2 is the 16.35 to Doncaster": "следующий поезд, прибывающий на вторую платформу, отправляется в 16:35 в Донкастер",
    "the train's been cancelled": "поезд был отменен",
    "does this train stop at Leicester?": "останавливается ли этот поезд в Лейчестере?",
    "could you tell me when we get to?": "скажите мне, пожалуйста, когда мы доедем до …",
    "is this seat free?": "это место свободно?",
    "is this seat taken?": "это место занято?",
    "all tickets and railcards, please": "билеты и проездные карты, пожалуйста",
    "could I see your ticket, please?": "покажите ваш билет, пожалуйста",
    "what time do we arrive in?": "во сколько мы прибываем в …?",
    "what time do we arrive in Sheffield?": "во сколько мы прибываем в Шеффилд?",
    "what's this stop?": "что это за остановка?",
    "what's the next stop?": "какая следующая остановка?",
    "this is my stop": "это моя остановка",
    "i'm getting off here": "я выхожу здесь",
    "is there a buffet car on the train?": "есть ли в поезде вагон-ресторан?",
    "do you mind if I open the window?": "вы не возражаете, если я открою окно?",
    "please take all your luggage and personal belongings with you": "пожалуйста заберите багаж и все персональные вещи",
    "could you tell me where the nearest Tube station is?": "не могли бы вы сказать, где ближайшая станция метро?",
    "where's there a map of the Underground?": "где здесь схема метро?",
    "over there": "там",
    "how many stops is it to?": "сколько остановок до …?",
    "i'd like a Day travelcard, please": "я хотел бы билет на день, пожалуйста",
    "zones 1-2": "зоны 1—2",
    "i'd like to put £10 on it": "я хотел бы положить 10 фунтов",
    "platform": "Платформа",
    "waiting room": "Зал ожидания",
    "left luggage": "Багажное отделение",
    "lost property": "Бюро находок",
    "bus stop": "Остановка автобуса",
    "request stop": "Остановка по требованию",
    "delayed": "Задерживается",
    "cancelled": "Отменен",
    "car": "Купе",
    "priority seat": "Специальные места (места для беременных, пожилых или инвалидов)",
    "to trains": "К поездам",
    "way out": "Выход",
    "mind the gap": "Осторожно, щель",
    "eastbound platform": "Платформа восточного направления",
    "westbound platform": "Платформа южного направления",
    "i'd like to hire a car": "я хотел бы взять автомобиль на прокат",
    "how long for?": "как надолго?",
    "for": "на …",
    "for two days": "на два дня",
    "for a week": "на неделю",
    "40 a day with unlimited mileage": "40 фунтов в день без ограничения расстояния",
    "what type of car do you want — manual or automatic?": "какой тип коробки передач вы хотитe мануальный или автоматический?",
    "has this car got?": "в машине есть …?",
    "has this car got air conditioning?": "в машине есть кондиционер?",
    "has this car got central locking?": "в машине есть центральный замок?",
    "has this car got child locks?": "в машине есть «детские» замки?",
    "could I see your driving licence?": "покажите ваши водительские права",
    "remember to drive on the": "двигайтесь по …",
    "remember to drive on the left": "двигайтесь по левой стороне",
    "remember to drive on the right": "двигайтесь по правой стороне",
    "does it take petrol or diesel?": "машина бензиновая или дизельная?",
    "is it manual or automatic?": "коробка передач мануальная или автоматическая?",
    "where are the?": "где включаются …?",
    "regards,": "С пожеланиями,",
    "kind regards,": "С добрыми пожеланиями,",
    "dear Mrs Jones,": "Дорогая миссис Джонс",
    "dear Sir,": "Дорогой Господин,",
    "i am writing in reply to your letter of 4 September regarding your outstanding invoice.": "Пишу Вам в ответ на письмо от 4-го сентября, касательно Вашего неоплаченного счета.",
    "i look forward to hearing from you.": "С нетерпением жду Вашего ответа.",
    "hello!": "алло!",
    "it's Maria here": "это Мария",
    "could I speak to, please?": "могу я поговорить с, пожалуйста?",
    "speaking!": "это я! (буквально: говорю!)",
    "who's calling?": "кто звонит?",
    "do you know what extension he's on?": "вы знаете на какой он линии?",
    "hold the line, please": "оставайтесь на линии, пожалуйста",
    "i'll put him on": "соединяю с ним",
    "i'll put her on": "соединяю с ней",
    "i'm sorry, he's in a meeting": "извините, он на встрече",
    "i'm sorry, she's": "извините, она",
    "would you like to leave a message?": "вы хотите оставить сообщение?",

}


#    "i've got to go": "мне нужно идти",
#    "is this seat free?": "это место свободно?",
#    "can I have a timetable, please?": "не могли бы вы дать мне расписание, пожалуйста?",
#    "i've lost my purse": "я потерял мой бумажник",
#    "has this car got child locks?": "в машине есть «детские» замки?",
#    "i'd like a senior citizens' return to Bristol": "я хотел бы пенсионерский билет в оба конца до Бристоля",
#    "i'd like to practise my": "я хотел бы попрактиковаться в …",
#    "who's driving tonight?": "кто сегодня за рулем?",
#    "excuse me, where's the Ladies?": "извините, где женский туалет?",
#    "push": "От себя",
#    "do you have a girlfriend?": "у тебя есть девушка?",
#    "how long will I have to wait?": "как долго ждать?",
#    "i took a course": "я ходил на курсы",
#    "would you like to leave a message?": "вы хотите оставить сообщение?",
#    "excuse me?": "простите?",
#    "call an ambulance!": "вызовите скорую помощь!",
#    "ladies": "Женщины",
#    "i can't find my passport": "я не могу найти мой паспорт",
#    "please be quiet": "пожалуйста, успокойтесь",
#    "yesterday afternoon": "вчера днем",
#    "regards,": "С пожеланиями,",
#    "stop it!": "прекрати!",
#    "I'd like a taxi, please": "я хотел бы заказать такси, пожалуйста",
#    "what do you think?": "что ты думаешь?",
#    "do you have a boyfriend?": "у тебя есть парень?",
#    "dear Sir,": "Дорогой Господин,",
#    "sure": "конечно",
#    "damn it!": "проклятие!",
#    "that's fine, keep the change": "все в порядке, оставьте сдачу",
#    "thanks for your help": "спасибо за помощь",
#    "i need a doctor": "мне нужен доктор",
#    "sleep well": "спи хорошо",
#    "have you got any kids?": "у тебя есть дети?",
#    "goodnight": "спокойной ночи",
#    "i'm worried": "я обеспокоен",
#    "at university": "в университете",
#    "i don't like": "мне не нравится …",
#    "that's funny": "странно ...",
#    "could you tell me where the nearest Tube station is?": "не могли бы вы сказать, где ближайшая станция метро?",
#    "have a seat!": "садись!, садитесь!",
#    "let's go!": "пойдемте!",
#    "come on in!": "входи!, входите!",
#    "about ten minutes": "около десяти минут",
#    "well done!": "хорошо сработано!",
#    "i like it": "мне нравится это",
#    "car": "Купе",
#    "tomorrow afternoon": "завтра днем",
#    "do you mind if I open the window?": "вы не возражаете, если я открою окно?",
#    "calm down": "успокойся",
#    "i'm": "я …",
#    "zones 1-2": "зоны 1—2",
#    "would you like a tea or coffee?": "хочешь чай или кофе?, хотите чай или кофе?",
#    "how many stops is it to?": "сколько остановок до …?",
#    "are we almost there?": "мы уже почти приехали?",
#    "could I see your ticket, please?": "покажите ваш билет, пожалуйста",
#    "please write it down": "пожалуйста, напишите это",
#    "sorry, I didn't understand": "извини, я не понял",
#    "yesterday": "вчера",
#    "is this the right platform for?": "это правильная платформа для …?",
#    "do you take milk?": "тебе нужно молоко?",
#    "does it take petrol or diesel?": "машина бензиновая или дизельная?",
#    "do you have any brothers or sisters?": "у тебя есть брат или сестра?",
#    "thank you very much": "большое спасибо",
#    "what's this stop?": "что это за остановка?",
#    "are you married?": "ты женат?, ты замужем?",
#    "your English is very good": "у тебя очень хороший английский",
#    "dear Mrs Jones,": "Дорогая миссис Джонс",
#    "how do you open the bonnet?": "как открывается капот?",
#    "which platform do I need for Manchester?": "какая платформа на Манчестер?",
#    "cancelled": "Отменен",
#    "today": "сегодня",
#    "sorry for the delay": "извините за задержку",
#    "platform": "Платформа",
#    "have a nice day!": "хорошего дня!",
#    "that's funny!": "прикольно!",
#    "i like": "мне нравится …",
#    "do you have any children?": "у тебя есть дети?",
#    "next year": "в следующем году",
#    "why not ?": "почему бы и нет?",
#    "where are you?": "где ты?, где вы?",
#    "are you seeing anyone?": "ты с кем-нибудь встречаешься?",
#    "can you smell burning?": "вы чувствуете запах гари?",
#    "i'm learning": "я учу …",
#    "can I take your coat?": "я возьму твое пальто",
#    "let's go into the": "давай(те) пойдем в …",
#    "i can get by in": "я неплохо говорю …",
#    "what does your mother do?": "чем занимается твоя мать?",
#    "that's right": "точно",
#    "thanks for your": "спасибо за …",
#    "what time do we arrive in Sheffield?": "во сколько мы прибываем в Шеффилд?",
#    "at school": "в школе",
#    "i'm thirsty": "я хочу пить",
#    "for a week": "на неделю",
#    "i can't find my": "я не могу найти …",
#    "look out!": "осторожно!",
#    "remember to drive on the left": "двигайтесь по левой стороне",
#    "does this train stop at Leicester?": "останавливается ли этот поезд в Лейчестере?",
#    "bad luck!": "вот незадача!",
#    "last month": "в прошлом месяце",
#    "i think that": "я думаю, что...",
#    "what's the address?": "какой адрес?",
#    "could you pick me up here at?": "могли бы вы забрать меня отсюда в ?",
#    "yes": "да",
#    "how often do the trains run to?": "как часто ходят поезда на …?",
#    "that's enough": "достаточно",
#    "i've been attacked": "на меня напали",
#    "way out": "Выход",
#    "last week": "на прошлой неделе",
#    "please help me": "пожалуйста, помогите мне",
#    "i'll be there in fifteen minutes": "я буду там через пятнадцать минут",
#    "really?": "правда?",
#    "hello": "здравствуйте",
#    "mind the gap": "Осторожно, щель",
#    "i've lost my wallet": "я потерял мой кошелек",
#    "you speak very good English": "ты очень хорошо говоришь по-английски",
#    "last year": "в прошлом году",
#    "no, I'm an only child": "нет, я единственный ребенок",
#    "i can't find my mobile": "я не могу найти мой мобильный телефон",
#    "has this car got central locking?": "в машине есть центральный замок?",
#    "where are the?": "где включаются …?",
#    "have you been waiting long?": "ты долго ждал?",
#    "i've burnt myself": "я обжегся",
#    "in the morning": "утром",
#    "let me know!": "сообщи мне!",
#    "i'd like to go to charing Cross station": "я хотел бы поехать на станцию «Чаринг Кросс»",
#    "is everything ok?": "все в порядке?",
#    "i'm learning Chinese": "я учу китайский",
#    "are your grandparents still alive?": "твои бабушка и дедушка еще живы?",
#    "did you understand?": "ты понял?",
#    "of course": "конечно",
#    "in the evening": "вечером",
#    "please": "пожалуйста",
#    "let me know if you can make it": "сообщи, если ты сможешь",
#    "westbound platform": "Платформа южного направления",
#    "i don't like him": "мне не нравится он",
#    "that's life!": "такова жизнь!",
