slovar = {
    "ten forty-five": "десять часов сорок пять минут",
    "ten am": "десять часов утра",
    "six pm": "шесть часов вечера",
    "noon": "полдень",
    "midday": "полдень",
    "midnight": "полночь",
    "11.47am": "11:47",
    "2.13pm": "14:13",
    "my watch is …": "мои наручные часы …",
    "my watch is fast": "мои наручные часы спешат",
    "my watch is slow": "мои наручные часы отстают",
    "that clock's a little …": "эти часы немного …",
    "that clock's a little fastя": "эти часы немного спешат",
    "that clock's a little slow": "эти часы немного отстают",
    "which university are you at?": "в каком университете ты учишься?",
    "can I buy you a drink?": "могу я купить тебе что-нибудь выпить?",
    "would you like a drink?": "желаешь что-нибудь выпить?",
    "can I get you a drink?": "могу я предложить тебе что-нибудь выпить?",
    "are you on your own?": "ты без компании?",
    "would you like to join us?": "хочешь присоединиться к нам?",
    "do you mind if I join you?": "не против, если я присоединюсь?",
    "do you mind if we join you?": "не против, если мы присоединимся?",
    "do you come here often?": "ты часто здесь бываешь?",
    "is this your first time here?": "ты здесь впервые?",
    "have you been here before?": "ты бывал здесь раньше?",
    "would you like to dance?": "хочешь потанцевать?",
    "do you want to go for a drink sometime?": "давай как-нибудь пойдем вместе выпьем?",
    "I was wondering if you'd like to go out for a drink sometime": "не хочешь как-нибудь пойти вместе выпить?",
    "if you'd like to meet up sometime, let me know!": "если захочешь как-нибудь встретиться, сообщи мне!",
    "would you like to join me for a coffee?": "хочешь выпить со мной кофе?",
    "do you fancy getting a bite to eat?": "хочешь перекусить?",
    "do you fancy lunch sometime?": "хочешь как-нибудь вместе пообедать?",
    "do you fancy dinner sometime?": "хочешь как-нибудь вместе поужинать?",
    "do you fancy going to see a film sometime?": "хочешь сходить как-нибудь в кино?",
    "that sounds good": "хорошее предложение",
    "I'd love to!": "с удовольствием!",
    "sorry, I'm busy": "извини, я занят(а)",
    "sorry, you're not my type!": "прости, ты не в моём вкусе!",
    "here's my number": "вот мой номер",
    "what's your phone number?": "какой у тебя номер телефона?",
    "could I take your phone number?": "можно записать твой телефон?",
    "you look great": "ты прекрасно выглядишь",
    "you look very nice tonight": "ты очень хорошо сегодня выглядишь",
    "I like your outfit": "мне нравится твой наряд",
    "you're beautiful": "ты красивая (женщине)",
    "you're really good-looking": "ты очень хорошо выглядишь",
    "you're really sexy": "ты очень сексуальный/ая",
    "you've got beautiful eyes": "у тебя красивые глаза",
    "you've got a great smile": "у тебя великолепная улыбка",
    "thanks for the compliment!": "спасибо за комплимент!",
    "what do you think of this place?": "что ты думаешь об этом месте?",
    "shall we go somewhere else?": "может пойдем в другое место?",
    "I know a good place": "я знаю хорошее место",
    "can I kiss you?": "можно тебя поцеловать?",
    "can I walk you home?": "можно проводить тебя домой?",
    "can I drive you home?": "можно отвезти тебя домой?",
    "would you like to come in for a coffee?": "хочешь пройти и выпить кофе?",
    "would you like to come back to mine?": "хочешь пойти ко мне?",
    "thanks, I had a great evening": "спасибо, это был прекрасный вечер",
    "when can I see you again?": "когда мы сможем снова увидиться?",
    "give me a call!": "позвони мне!",
    "I'll call you": "я позвоню",
    "what do you think of me?": "что ты обо мне думаешь?",
    "I enjoy spending time with you": "мне нравится быть вместе с тобой",
    "I find you very attractive": "я считаю тебя очень привлекательным/ой",
    "I like you": "ты мне нравишься",
    "I like you a lot": "ты мне очень нравишься",
    "I'm crazy about you": "я без ума от тебя",
    "I love you!": "я люблю тебя!",
    "will you marry me?": "ты выйдешь за меня замуж?",
    "I miss you": "я соскучился",
    "I've missed you": "я очень скучал",
    "do you have any condoms?": "у тебя есть презервативы?",
    "I'm straight": "я традиционной ориентации",
    "I'm gay": "я гомосексуалист/лесбиянка",
    "I'm bisexual": "я бисексуал/бисексуалка",
    "I'll put the kettle on": "я включу чайник",
    "the kettle's boiled": "чайник вскипел",
    "can you put the light on?": "можешь включить свет?",
    "can you switch the light on?": "можешь включить свет?",
    "can you turn the light off?": "можешь выключить свет?",
    "can you switch the light off?": "можешь выключить свет?",
    "is there anything I can do to help?": "могу я чем-нибудь помочь?",
    "could you help me wash the dishes?": "можешь помочь мне помыть посуду?",
    "I'll wash and you dry": "я буду мыть, а ты вытирай",
    "I'm going to bed": "я пойду спать",
    "is there anything good on TV?": "есть что-нибудь хорошее по телевизору?",
    "is there anything good on television tonight?": "есть что-нибудь хорошее по телевизору сегодня вечером?",
    "there's a good film on later": "попозже будет хороший фильм",
    "Beware of the dog": "Осторожно, собака",
    "that was excellent": "это было превосходно",
    "that was very tasty": "это было очень вкусно",
    "that was delicious": "это было очень вкусно",
    "excuse me, could you tell me how to get to …?": "простите, вы не скажете как добраться до …?",
    "excuse me, could you tell me how to get to the bus station?": "простите, вы не скажете как добраться до автобусной станции?",
    "excuse me, do you know where the … is?": "простите, вы знаете где находится …?",
    "excuse me, do you know where the post office is?": "простите, вы знаете где находится почта?",
    "I'm sorry, I don't know": "извините, я не знаю",
    "sorry, I'm not from around here": "извините, я не местный",
    "I'm looking for this address": "я ищу этот адрес",
    "are we on the right road for …?": "мы на правильной дороге до …?",
    "are we on the right road for Brighton?": "мы на правильной дороге до Брайтон?",
    "it's in Spanish": "он на испанском",
    "with English subtitles": "с английскими субтитрами",
    "it's just been released": "он только что вышел на экраны",
    "it's been out for about two months": "он вышел около двух месяцев назад",
    "it's meant to be good": "он должен быть хорошим",
    "shall we get some popcorn?": "возьмем попкорн?",
    "salted or sweet?": "соленый или сладкий?",
    "do you want anything to drink?": "ты хочешь что-нибудь пить?",
    "where do you want to sit?": "где ты хочешь сидеть?",
    "in the middle": "в середине",
    "what did you think?": "что ты думаешь? (буквально: что ты думал?)",
    "I enjoyed it": "мне понравилось",
    "it was great": "это было великолепно",
    "it was really good": "он был действительно хорош",
    "it wasn't bad": "это было неплохо",
    "I thought it was rubbish": "я думаю это было ужасно",
    "it was one of the best films I've seen for ages": "это был лучший фильм, который я когда-либо видел",
    "it had a good plot": "сюжет был хороший",
    "the plot was quite complex": "сюжет был довольно запутанным",
    "it was too slow-moving": "было слишком затянуто",
    "it was very fast-moving": "было очень захватывающе",
    "the acting was …": "игра актеров была …",
    "the acting was excellent": "игра актеров была отличной",
    "the acting was good": "игра актеров была хорошей",
    "the acting was poor": "игра актеров была плачевной",
    "the acting was terrible": "игра актеров была ужасной",
    "he's a very good actor": "он очень хороший актер",
    "she's a very good actress": "она очень хорошая актриса",
    "Screen": "Экран",
    "do we need to book?": "мы должны забронировать?",
    "what tickets do you have available?": "какие билеты у вас есть в наличии?",
    "I'd like two tickets, please": "мне, пожалуйста, два билета",
    "I'd like two tickets for …": "мне, пожалуйста, два билета на …",
    "I'd like two tickets for tomorrow night": "мне, пожалуйста, два билета на завтрашний вечер",
    "I'd like two tickets for next Saturday": "мне, пожалуйста, два билета на следующую субботу",
    "I'd like four tickets to see …": "мне, пожалуйста, четыре билета на …",
    "I'd like four tickets to see Les Misérables": "мне, пожалуйста, четыре билета на «Отверженные»",
    "I'm sorry, it's fully booked": "извините, всё уже забронировано",
    "sorry, we've got nothing left": "извините, у нас ничего не осталось",
    "how much are the tickets?": "сколько стоят билеты?",
    "is there a discount for …?": "есть ли скидка …?",
    "is there a discount for students?": "есть ли скидка студентам?",
    "is there a discount for senior citizens?": "есть ли скидка пенсионерам?",
    "is there a discount for the unemployed?": "есть ли скидка безработным?",
    "is there a discount for children?": "есть ли скидка детям?",
    "where would you like to sit?": "где бы вы хотели сидеть?",
    "near the front": "впереди",
    "near the back": "сзади",
    "somewhere in the middle": "в центре",
    "what's the expiry date?": "когда у неё истекает срок действия?",
    "what's the start date?": "когда у неё начало срока действия?",
    "what's the security number on the back?": "какой секретный код на обратной стороне?",
    "please enter your PIN": "пожалуйста, введите ваш PIN-код",
    "where do I collect the tickets?": "где я могу получить билеты?",
    "the tickets were very cheap": "билеты были очень дешевыми",
    "the tickets were expensive": "билеты были дорогие",
    "Ticket office": "Билетные кассы",
    "Box office": "Билетные кассы",
    "Row": "Ряд",
    "where's the cinema?": "где находится кинотеатр?",
    "where's the theatre?": "где находится театр?",
    "where's the concert hall?": "где находится концертный зал?",
    "where's the stadium?": "где находится стадион?",
    "do you want to go out tonight?": "хочешь прогуляться сегодня вечером?",
    "let's go to …": "давай пойдем в …",
    "let's go to the pub": "давай пойдем в паб",
    "let's go to the cinema": "давай пойдем в кино",
    "let's go to the theatre": "давай пойдем в театр",
    "let's go to a concert": "давай пойдем в концерт",
    "let's go to a nightclub": "давай пойдем в ночной клуб",
    "what's on at the …?": "что идет в …?",
    "what's on at the cinema?": "что идет в кино?",
    "what's on at the theatre?": "что идет в театре?",
    "is there anything good on?": "там идет что-нибудь хорошее?",
    "shall we go …?": "может пойдем …?",
    "shall we go swimming?": "может пойдем поплаваем?",
    "shall we go skating?": "может пойдем покатаемся на коньках?",
    "shall we go bowling?": "может пойдем поиграем в боулинг?",
    "shall we go for a walk?": "может пойдем погуляем?",
    "shall we go for a bike ride?": "может покатаемся на велосипеде?",
    "excuse me, could you take a photo for me?": "извините, вы могли бы меня сфотографировать?",
    "excuse me, could you take a photo for us?": "извините, вы могли бы нас сфотографировать?",
    "I'd like to hire a bike": "я хотел бы взять велосипед на прокат",
    "I'd like to hire a canoe": "я хотел бы взять байдарку на прокат",
    "it's a beautiful view": "красивый вид",
    "what kind of accommodation are you looking for?": "какой вид жилья вы ищете?",
    "I'm looking for a flat": "я ищу квартиру",
    "I'm looking for an apartment": "я ищу квартиру",
    "I'm looking for a semi-detached house": "я ищу дом, с одной стороны соединенный с соседним домом стеной",
    "I'm looking for a detached house": "я ищу отдельный дом",
    "I'm looking for a terraced house": "я ищу рядный дом",
    "I'm looking for a cottage": "я ищу маленький коттедж",
    "I'm looking for a bungalow": "я ищу бунгало",
    "I only need a …": "мне всего лишь нужна…",
    "I only need a one-bedroomed flat": "мне всего лишь нужнаквартира с одной спальней",
    "I only need a studio flat": "мне всего лишь нужнаквартира-студия",
    "are you looking to buy or to rent?": "вы желаете купить или снять?",
    "which area are you thinking of?": "в каком районе вы хотите?",
    "something not too far from the city centre": "что-нибудь недалеко от центра города",
    "how much are you prepared to pay?": "сколько вы готовы заплатить?",
    "what's your budget?": "каков ваш бюджет?",
    "what price range are you thinking of?": "каков предел вашей цены?",
    "how many bedrooms do you want?": "сколько спален вы хотите?",
    "it's got two bedrooms, a kitchen, a living room, and a bathroom": "там есть две спальни, кухня, гостиная и ванная комната",
    "are you looking for furnished or unfurnished accommodation?": "вы ищете меблированное или немеблированное жильё?",
    "do you want a modern or an old property?": "вы хотите новую или старую собственность?",
    "do you want a …?": "вы хотите …?",
    "do you want a garden?": "вы хотите сад?",
    "do you want a garage?": "вы хотите гараж?",
    "do you want a parking space?": "вы хотите место для парковки?",
    "are you going to need a mortgage?": "вам будет нужен жилищный кредит?",
    "have you got a property to sell?": "у вас есть собственность на продажу?",
    "are you a cash buyer?": "у вас уже есть платежные средства? (не нужен жилищный кредит)",
    "my … are hurting": "у меня болит …",
    "my feet are hurting": "у меня болит ступня",
    "my knees are hurting": "у меня болит колено",
    "my back hurts": "у меня болит спина",
    "have you got any painkillers?": "у тебя есть болеутоляющие средства?",
    "have you got any paracetamol?": "у тебя есть парацетамол?",
    "have you got any aspirin?": "у тебя есть аспирин?",
    "have you got any plasters?": "у тебя есть пластыри?",
    "how are you feeling?": "как ты себя чувствуешь?",
    "are you feeling alright?": "ты себя нормально чувствуешь?",
    "are you feeling any better?": "ты себя лучше чувствуешь?",
    "I hope you feel better soon": "я надеюсь, тебе скоро станет лучше",
    "get well soon!": "выздоравливай поскорее!",
    "I need to see a doctor": "мне нужен доктор",
    "I think you should go and see a doctor": "я думаю, тебе следует пойти к врачу",
    "do you know a good …?": "ты знаешь хорошего …?",
    "do you know a good doctor?": "ты знаешь хорошего доктора?",
    "do you know a good dentist?": "ты знаешь хорошего дантиста?",
    "do you know where there's an all-night chemists?": "ты знаешь круглосуточную аптеку?",
    "is there an admission charge?": "за вход надо платить?",
    "only for the exhibition": "только за выставки",
    "the museum's closed on Mondays": "музей закрыт по понедельникам",
    "can I take photographs?": "можно фотографировать?",
    "would you like an audio-guide?": "вы желаете аудио-гида?",
    "are there any guided tours today?": "сегодня есть какие-либо экскурсии с гидом?",
    "what time does the next guided tour start?": "во сколько начинается следующая экскурсия?",
    "we have to leave our bags in the cloakroom": "мы должны оставить свои сумки в гардеробе",
    "do you have a plan of the museum?": "у вас есть план музея?",
    "who's this painting by?": "чья это картина?",
    "this museum's got a very good collection of …": "у этого музея очень хорошая коллекция …",
    "this museum's got a very good collection of oil paintings": "у этого музея очень хорошая коллекция картин, написанных маслом",
    "this museum's got a very good collection of watercolours": "у этого музея очень хорошая коллекция акварелей",
    "this museum's got a very good collection of portraits": "у этого музея очень хорошая коллекция портретов",
    "this museum's got a very good collection of landscapes": "у этого музея очень хорошая коллекция пейзажей",
    "this museum's got a very good collection of sculptures": "у этого музея очень хорошая коллекция скульптур",
    "this museum's got a very good collection of ancient artifacts": "у этого музея очень хорошая коллекция старинных предметов",
    "this museum's got a very good collection of pottery": "у этого музея очень хорошая коллекция керамики",
    "do you like …?": "тебе нравится/нравятся …?",
    "do you like modern art?": "тебе нравится/нравятся современное искусство?",
    "do you like classical paintings?": "тебе нравится/нравятся классические картины?",
    "do you like impressionist paintings?": "тебе нравится/нравятся картины импрессионистов?",
    "Free admission": "Вход свободный",
    "No photography": "Не фотографировать",
    "Cloakroom": "Гардероб",
    "Café": "Кафе",
    "Gift shop": "Магазин сувениров",
    "do you want to go to a club tonight?": "ты хочешь пойти сегодня вечером в клуб?",
    "do you know any good clubs near here?": "ты знаешь какие-нибудь хорошие клубы поблизости?",
    "what time are you open until?": "до скольки вы открыты?",
    "how much is it to get in?": "сколько стоит вход?",
    "is there a dress code?": "дресс-код есть?",
    "what nights are you open?": "по каким дням вы открыты?",
    "what sort of music is it?": "какой это стиль музыки?",
    "what's on tonight?": "какая сегодня программа?",
    "do you have any live music tonight?": "сегодня будет концерт?",
    "sorry, you can't come in": "извините, вы не можете войти",
    "you can't come in with trainers on": "вы не можете войти в спортивных штанах",
    "there's a private party tonight": "сегодня здесь закрытая вечеринка",
    "the club's full": "в клубе нет мест",
    "I'm on the guest list": "я в списке гостей",
    "I'm a member": "я — член",
    "what do you think of the DJ?": "что вы думаете о диджее?",
    "the music's great!": "отличная музыка!",
    "it's very lively tonight": "очень оживленно сегодня",
    "it's a bit empty": "здесь немного пусто",
    "it's dead in here": "здесь тоска (слэнг)",
    "where's the bar?": "где находится бар?",
    "there's a long queue at the bar": "в баре длинная очередь",
    "it's too loud": "слишком громко",
    "it's too hot in here": "здесь слишком жарко",
    "are you ready to go home?": "ты готов идти домой?",
    "I'm going home": "я пойду домой",
    "is there anything on at the theatre …?": "что-нибудь идет в театре …?",
    "is there anything on at the theatre tonight?": "что-нибудь идет в театре сегодня?",
    "is there anything on at the theatre this week?": "что-нибудь идет в театре на этой неделе?",
    "is there anything on at the theatre this month?": "что-нибудь идет в театре в этом месяце?",
    "when's the play on until?": "во сколько заканчивается спектакль?",
    "what type of production is it?": "что это за представление?",
    "it's …": "это — …",
    "it's a tragedy": "это — трагедия",
    "it's a musical": "это — мюзикл",
    "it's an opera": "это — опера",
    "it's a ballet": "это — балет",
    "have you seen it before?": "ты уже раньше видел это?",
    "what time does the performance start?": "во сколько начинается представление?",
    "what time does it finish?": "во сколько это закачнивается?",
    "where's the cloakroom?": "где находится гардероб?",
    "would you like a programme?": "желаете программку?",
    "could I have a programme, please?": "не могли бы вы дать мне программку, пожалуйста?",
    "shall we order some drinks for the interval?": "закажем в антракте что-нибудь выпить?",
    "we'd better go back to our seats": "нам лучше вернуться на свои места",
    "did you enjoy it?": "тебе понравилось?",
    "Stalls": "Партер",
    "Circle": "Ярус",
    "Balcony": "Балкон",
    "Boxes": "Ложа",
    "is there anything good on at the cinema?": "в кино идет что-нибудь достойное?",
    "what's this film about?": "о чем это фильм?",
    "have you seen it?": "ты его уже видел?",
    "who's in it?": "кто в нем снимается?",
    "it's a thriller": "это — триллер",
    "it's a comedy": "это — комедия",
    "it's a romantic comedy": "это — романтическая комедия",
    "it's a horror film": "это — фильм ужасов",
    "it's a documentary": "это — документальный фильм",
    "it's an animation": "это — мультфильм",
    "it's a war film": "это — фильм про войну",
    "it's a western": "это — вестерн",
    "it's a science fiction film": "это — научно-популярный фильм",
    "it's a foreign film": "это — зарубежный фильм",
    "it's in …": "он на …",
    "it's in French": "он на французском",
    "what's the problem?": "в чем проблема?",
    "what are your symptoms?": "какие у вас симптомы?",
    "I've got a …": "у меня …",
    "I've got a temperature": "у меня температура",
    "I've got a sore throat": "у меня болит горло",
    "I've been feeling sick": "меня тошнило",
    "I've been having headaches": "у меня болела голова",
    "I'm very congested": "у меня мокрота в легких и насморк",
    "my joints are aching": "у меня болят суставы",
    "I've got diarrhoea": "у меня понос",
    "I'm constipated": "у меня запор",
    "I've got a lump": "у меня опухоль",
    "I've got a swollen …": "у меня опухла …",
    "I've got a swollen ankle": "у меня опухла лодыжка000",
    "I'm in a lot of pain": "у меня очень сильная боль",
    "I've got a pain in my back": "у меня боль в спине",
    "I've got a pain in my chest": "у меня боль в груди",
    "I think I've pulled a muscle in my leg": "я думаю, что растянул мышцу на ноге",
    "I'm asthmatic": "я астматик",
    "I'm diabetic": "я диабетик",
    "I'm epileptic": "я эпилептик",
    "I need …": "мне нужен …",
    "I need another inhaler": "мне нужен ингалятор",
    "I need some more insulin": "мне нужен еще инсулин",
    "I'm having difficulty breathing": "мне трудно дышать",
    "I've got very little energy": "я очень слаб",
    "I've been feeling very tired": "я чувствую большую усталость",
    "I've been feeling depressed": "я чувствую себя подавленным",
    "I've been having difficulty sleeping": "у меня проблемы со сном",
    "how long have you been feeling like this?": "как долго вы уже себя так чувствуете?",
    "how have you been feeling generally?": "как вы вообще себя чувствуете?",
    "is there any possibility you might be pregnant?": "допустимо ли, что вы беременны?",
    "I think I might be pregnant": "я думаю, я беременна",
    "do you have any allergies?": "у вас есть на что-либо аллергия?",
    "I'm allergic to antibiotics": "у меня аллергия на антибиотики",
    "are you on any sort of medication?": "вы принимаете какие-либо лекарства?",
    "I need a sick note": "мне нужна справка о болезни",
    "can I have a look?": "могу я взглянуть?",
    "where does it hurt?": "где болит?",
    "it hurts here": "здесь болит",
    "does it hurt when I press here?": "вам больно, когда я сюда нажимаю?",
    "I'm going to take your …": "я собираюсь измерить …",
    "I'm going to take your blood pressure": "я собираюсь измерить кровяное давление",
    "I'm going to take your temperature": "я собираюсь измерить температуру",
    "I'm going to take your pulse": "я собираюсь измерить пульс",
    "could you roll up your sleeve?": "закатайте рукав",
    "your blood pressure's …": "ваше кровяное давление …",
    "your blood pressure's quite low": "ваше кровяное давление довольно низкое",
    "your blood pressure's normal": "ваше кровяное давление в норме",
    "your blood pressure's rather high": "ваше кровяное давление немного повышено",
    "your blood pressure's very high": "ваше кровяное давление очень высокое",
    "your temperature's …": "ваша температура …",
    "your temperature's normal": "ваша температура нормальная",
    "your temperature's a little high": "ваша температура немного повышена",
    "your temperature's very high": "ваша температура очень высокое",
    "open your mouth, please": "откройте, пожалуйста, рот",
    "cough, please": "покашляйте, пожалуйста",
    "you're going to need a few stiches": "вам придется нанести несколько швов",
    "I'm going to give you an injection": "я собираюсь сделать вам укол",
    "we need to take a …": "нам нужно взять …",
    "we need to take a urine sample": "нам нужно взять анализ мочи",
    "we need to take a blood sample": "нам нужно взять анализ крови",
    "you need to have a blood test": "вы должны сделать анализ крови",
    "I'm going to prescribe you some antibiotics": "я собираюсь выписать вам антибиотики",
    "take two of these pills three times a day": "принимайте по две таблетки три раза в день",
    "take this prescription to the chemist": "возьмите этот рецепт",
    "you should stop smoking": "вы должны бросить курить",
    "how much alcohol do you drink a week?": "сколько алкоголя вы потребляете в неделю?",
    "you should cut down on your drinking": "вы должны бросить пить",
    "you need to try and lose some weight": "вы должны постарвться сбросить немного вес",
    "I want to send you for an x-ray": "я хочу отправить вас на рентген",
    "I want you to see a specialist": "я хочу, чтобы вы посетили специалиста",
    "I'd like some toothpaste": "мне нужна зубная паста",
    "I'd like some paracetamol": "мне нужна парацетамол",
    "I've got a prescription here from the doctor": "у меня есть рецепт от врача",
    "have you got anything for …?": "у вас что-нибудь от …?",
    "have you got anything for cold sores?": "у вас что-нибудь от герписа?",
    "have you got anything for a sore throat?": "у вас что-нибудь от боли в горле?",
    "have you got anything for chapped lips?": "у вас что-нибудь от обветренных губ?",
    "have you got anything for a cough?": "у вас что-нибудь от кашля?",
    "have you got anything for travel sickness?": "у вас что-нибудь от укачивания?",
    "have you got anything for athlete's foot?": "у вас что-нибудь от ножного грибка?",
    "can you recommend anything for a cold?": "вы можете что-нибудь порекомендовать от простуды?",
    "I'm suffering from …": "я страдаю от …",
    "I'm suffering from hay fever": "я страдаю от сенной аллергии",
    "I'm suffering from indigestion": "я страдаю от несварения желудка",
    "I'm suffering from diarrhoea": "я страдаю от диареи",
    "I've got a rash": "у меня сыпь",
    "you could try this cream": "вы можете попробовать этот крем",
    "if it doesn't clear up after a week, you should see your doctor": "если это не пройдет в течение недели, вы должны обратиться к врачу",
    "have you got anything to help me stop smoking?": "у вас есть что-нибудь, чтобы помочь мне бросить курить?",
    "have you tried nicotine patches?": "вы пробовали никотиновые пластыри?",
    "can I buy this without a prescription?": "могу я это купить без рецепта?",
    "it's only available on prescription": "это можно купить только с рецептом",
    "does it have any side-effects?": "есть ли какие-нибудь побочные эффекты?",
    "it can make you feel drowsy": "вы можете почувствовать сонливость",
    "you should avoid alcohol": "вам следует воздержаться от алкоголя",
    "I'd like to speak to the pharmacist, please": "я хотел бы поговорить с аптекарем, пожалуйста",
    "I'm not feeling well": "я нехорошо себя чувствую",
    "I'm not feeling very well": "я нехорошо себя чувствую",
    "I feel ill": "я заболел",
    "I feel sick": "меня тошнит",
    "I've cut myself": "я порезался",
    "I've got a headache": "у меня болит голова",
    "I've got a splitting headache": "у меня ужасная головная боль",
    "I'm not well": "мне нехорошо",
    "I've got flu": "у меня грип",
    "I'm going to be sick": "меня тошнит",
    "I've been sick": "меня тошнило",
    "I've got a pain in my …": "у меня болит …",
    "I've got a pain in my neck": "у меня болит шея",
    "have you got a current driving licence?": "у вас есть водительские права?",
    "how much were you paid in your last job?": "сколько вы зарабатывали на прежней работе?",
    "do you need a work permit?": "вам нужно разрешение на работу?",
    "we'd like to offer you the job": "мы бы хотели предложить вам работу",
    "when can you start?": "когда вы сможете начать?",
    "how much notice do you have to give?": "как долго вы должны еще оставаться на нынешней работе?",
    "there's a three month trial period": "три месяца — испытательный срок",
    "we'll need to take up references": "нам нужно получить рекомендации",
    "this is your employment contract": "это ваш рабочий договор",
    "Name": "Имя",
    "Address": "Адрес",
    "Telephone number": "Телефонный номер",
    "Email address": "Адрес электронной почты",
    "Date of birth": "Дата рождения",
    "Nationality": "Национальность",
    "Marital status": "Семейное положение",
    "Career objective": "Предположительный карьерный рост",
    "Education": "10",
    "Qualifications": "Качества",
    "Employment history": "История трудоустройства",
    "Leisure interests": "8",
    "Referees": "Поручители",
    "how long have you worked here?": "как долго ты здесь работаешь?",
    "I'm going out for lunch": "я пойду обедать",
    "I'll be back at 1.30": "я вернусь в полвторого",
    "how long does it take you to get to work?": "сколько времени ты добираешься до работы?",
    "the traffic was terrible today": "сегодня было очень много машин",
    "how do you get to work?": "как ты добираешься до работы?",
    "you're fired!": "ты уволен!",
    "she's on maternity leave": "она в декретном отпуске",
    "he's on paternity leave": "он в отпуске по уходу за ребенком",
    "he's off sick today": "он сегодня приболел",
    "he's not in today": "его сегодня нет",
    "she's on holiday": "она в отпуске",
    "I'm afraid I'm not well and won't be able to come in today": "боюсь, что я плохо себя чувствую и не смогу сегодня прийти",
    "he's with a customer at the moment": "он сейчас общается с клиентом",
    "I'll be with you in a moment": "один момент, пожалуйста",
    "do you need any help?": "вам нужна помощь?",
    "what can I do for you?": "что я могу для вас сделать?",
    "he's in a meeting": "он на собрании",
    "what time does the meeting start?": "во сколько начинается собрание?",
    "what time does the meeting finish?": "во сколько заканчивается собрание?",
    "the reception's on the first floor": "приемная на втором этаже",
    "I'll be free after lunch": "я освобожусь после обеда",
    "she's having a leaving-do on Friday": "у нее прощальная вечеринка в пятницу (разговорное)",
    "she's resigned": "она уходит с работы",
    "this invoice is overdue": "этот счет просроченный",
    "he's been promoted": "его повысили в должности",
    "here's my business card": "это моя визитка",
    "can I see the report?": "могу я посмотреть отчет?",
    "I need to do some photocopying": "мне нужно сделать копии",
    "where's the photocopier?": "где копировальная машина?",
    "the photocopier's jammed": "копировальная машина заела",
    "I've left the file on your desk": "я оставил папку на твоем столе",
    "there's a problem with my computer": "у меня проблема с компьютером",
    "the system's down at the moment": "система в данный момент не работает",
    "the internet's down at the moment": "интернета в данный момент нет",
    "I can't access my emails": "я не могу открыть свой почтовый ящик",
    "the printer isn't working": "принтер не работает",
    "do you offer free eye tests?": "вы делаете бесплатную проверку зрения?",
    "I'd like to have an eye test, please": "я хотел бы проверить зрение, пожалуйста",
    "I need a new …": "мне нужны …",
    "I need a new pair of glasses": "мне нужны новые очки",
    "I need a new pair of reading glasses": "мне нужны новые очки для чтения",
    "I need a new glasses' case": "мне нужны новый футляр для очков",
    "could I order some more contact lenses?": "могу я заказать дополнительные контактные линзы?",
    "the frame on these glasses is broken": "оправа этих очков сломана",
    "can you repair it?": "вы можете починить?",
    "do you sell sunglasses?": "у вас продаются солнечные очки?",
    "how much are these designer frames?": "сколько стоят эти дизайнерские оправы?",
    "my eyesight's getting worse": "у меня портится зрение",
    "do you wear contact lenses?": "вы носите контактные линзы?",
    "are you short-sighted or long-sighted?": "вы близорукий или дальнозоркий?",
    "could you read out the letters on the chart, starting at the top?": "прочитайте, пожалуйста, буквы в столбце, начиная сверху",
    "could you close your left eye, and read this with your right?": "закройте, пожалуйста, ваш левый глаз и читайте это правым",
    "do you do hearing tests?": "вы проверяете слух?",
    "can I make an appointment to see the …?": "можно записаться на прием к …?",
    "can I make an appointment to see the dentist?": "можно записаться на прием к дантисту?",
    "can I make an appointment to see the hygienist?": "можно записаться на прием к гигиенисту?",
    "I'd like a check-up": "я бы хотел провериться",
    "please take a seat": "садитесь, пожалуйста",
    "would you like to come through?": "проходите",
    "when did you last visit the dentist?": "когда вы в последний раз посещали дантиста?",
    "have you had any problems?": "у вас есть какие-то жалобы?",
    "I've got toothache": "у меня зубная боль",
    "one of my fillings has come out": "у меня отошла одна из пломб",
    "I've chipped a tooth": "у меня раскрошился зуб",
    "I'd like a clean and polish, please": "я хотел бы сделать чистку и шлифовку, пожалуйста",
    "can you open your mouth, please?": "откройте рот, пожалуйста",
    "a little wider, please": "немного пошире, пожалуйста",
    "I'm going to give you an x-ray": "я собираюсь сделать вам рентген",
    "you've got a bit of decay in this one": "у вас небольшое повреждение в этом зубе",
    "you've got an abscess": "у вас воспаление",
    "you need two fillings": "вам нужны две пломбы",
    "I'm going to have to take this tooth out": "я собираюсь вырвать этот зуб",
    "do you want to have a crown fitted?": "вы хотите поставить коронку?",
    "let me know if you feel any pain": "скажите мне, если почувствуете боль",
    "would you like to rinse your mouth out?": "хотите прополоскать рот?",
    "you should make an appointment with the hygienist": "вам нужно записаться на приём к гигиенисту",
    "I'd like to see a doctor": "я хотел бы попасть на прием к врачу",
    "do you have an appointment?": "у вас назначено?",
    "is it urgent?": "это срочно?",
    "I'd like to make an appointment to see Dr …": "я хотел бы записаться на прием к доктору …",
    "I'd like to make an appointment to see Dr Robinson": "я хотел бы записаться на прием к доктору Робинсона",
    "do you have any doctors who speak …?": "у вас есть врачи, которые говорят …?",
    "do you have any doctors who speak Spanish?": "у вас есть врачи, которые говорят по-испански?",
    "do you have private medical insurance?": "у вас есть медицинская страховка?",
    "have you got a European Health Insurance card?": "у вас есть карточка Европейского Страхования Здоровья?",
    "the doctor's ready to see you now": "доктор готов принять вас сейчас",
    "how can I help you?": "чем я могу вам помочь?",
    "I'm on a course at the moment": "я сейчас прохожу обучение",
    "I'm on work experience": "я прохожу практику (короткий период)",
    "I'm doing an internship": "я прохожу практику (более долгий период)",
    "are you a student?": "ты студент?",
    "what do you study?": "что ты изучаешь?",
    "I'm studying …": "я изучаю …",
    "I'm studying history": "я изучаю историю",
    "I'm studying economics": "я изучаю экономику",
    "I'm studying medicine": "я изучаю медицину",
    "where do you study?": "где ты учишься?",
    "which university are you at?/": "в каком университете ты учишься?",
    "what university do you go to?": "в каком университете ты учишься?",
    "I'm at …": "я учусь …",
    "I'm at Liverpool University": "я учусь в Ливерпульском университете",
    "which year are you in?": "на каком ты курсе?",
    "I'm in my … year": "я на … курсе",
    "I'm in my first year": "я на первом курсе",
    "I'm in my second year": "я на втором курсе",
    "I'm in my third year": "я на третьем курсе",
    "I'm in my final year": "я на последнем курсе",
    "I'm in my first year at university": "я учусь на первом курсе в университете",
    "do you have any exams coming up?": "у тебя будут скоро экзамены?",
    "I've just graduated": "я недавно закончил",
    "I'm doing a masters in …": "я в магистратуре по …",
    "I'm doing a masters in law": "я в магистратуре по юриспруденции",
    "law1": "я в докторантуре по …",
    "law": "я в докторантуре по химии",
    "did you go to university?": "ты учился в университете?",
    "I didn't go to university": "я не учился в университете",
    "I never went to university": "я никогда не учился в университете",
    "where did you go to university?": "где ты учился в университете?",
    "I went to …": "я учился в …",
    "I went to Cambridge": "я учился в Кембридже",
    "what did you study?": "что ты изучал?",
    "I studied …": "я изучал …",
    "I studied maths": "я изучал математику",
    "I studied politics": "я изучал политологию",
    "where did you go to school?": "где ты учился в школе?",
    "I went to school in …": "я учился в школе в …",


}