slovar = {
    # i need it
    "i need your help": "",
    "i need your advice": "",
    "i need your recommendation": "",
    "i need more practice": "",
    "i need a good teacher": "",
    "i need more lessons": "",
    "i need these lessons": "",
    "i need a pen": "",
    "i need a pencil": "",
    "i need money": "",
    "i need more money": "",
    "i need to learn English": "",
    "i need to find good job": "",
    "i need to know it right now": "",
    "i need to check it": "",
    "i need to go to that place": "",
    "i need to call him": "",
    "i need to visit her": "",
    "i need to work very hard": "",
    "i need to study more": "",
    "i need to remember all these words and phrases": "",
    "i need to save this document": "",
    "i need to save this file": "",
    "i need to write a letter": "",
    "i need to write it down": "",
    "i need to watch this lesson one more time": "",
    "i need to watch this lesson again": "",
    "i need to watch these lessons": "",
    "i need to watch that movie": "",
    "i need to read these books": "",
    "i need to train every day": "",
    "i need to study English regularly": "",
    "we need more exercises": "",
    "you need more rest": "",
    "they need more lessons": "",
    "he needs more money": "",
    "she needs more practice": "",
    "my friend needs to learn English": "",
    "my brother needs to go there": "",
    "my friends need to buy this thing": "",
    "my parents need to work more": "",
    "i need to do this thing now": "",
    "i need to study more": "",
    "he needs to do more physical exercises": "",
    "i need to write it down": "",
    " need to watch this lesson one more time": "",
    "i need to watch that movie": "",
    "my friend needs to learn English": "",
    "we need to visit him": "",
    "i need to watch your English": "",
    "you need more rest": "",
    "i need to relax more": "",
    "i need to have more rest": "",
    "they need more lessons": "",
    "he needs more money": "",
    "i need to find it": "",
    "i need to say it": "",
    "i need to go to America": "",
    "we need more exercises": "",
    "i need to try it": "",
    "i need to train every day": "",
    "i need to save this file": "",
    "i need to visit her": "",
    "i need to translate this text": "",
    "my brother needs to go there": "",
    "i need to go to work": "",
    "i need to call him": "",
    "i need to study English more regularly": "",
    "i also need to know it": "",
    "i need to go to the gym": "",
    "he needs to go to China": "",
    "i need to go to that place": "",
    "i need to find a good job": "",
    "i need to listen to this song": "",
    "i need to understand it right now": "",
    "i need to read these books": "",
    "my parents need to work more": "",
    "she needs more practice": "",
    "i need to watch these lessons": "",
    "i need to see him": "",
    "i need to write a latter": "",
    "i need to relax": "",
    "i need to have a rest": "",
    "i need to tell you about this problem": "",
    "i need to try to do it": "",
    "i need to save this document": "",
    "i need to remember it": "",
    "i need to order it": "",
    "my friends need to buy this thing": "",
    "i need to check it": "",
    "i need to know all the information": "",
    "i go to China": "",
    "i go the united states": "",
    "i go the united kingdom": "",
    "i want this thing": "",
    "i want to buy this thing": "",
    "she wants to speak English fluently": "",
    "my friend wants to translate text": "",
    "i want a cup of tea": "",
    "i'd like a cup of tea": "",
    "i'd like to drink a cup of tea": "",
    "she'd like to visit this place": "",
    "they'd like to order it online": "",
    # i / we / you / don't +г
    # he / she / it doesn't + г
    "i don't understand": "",
    "it doesn't seem interesting": "",
    "this idea doesn't seem interesting": "",
    "my parents don't want to sell this house": "",
    "i need you help": "",
    "i need to check it": "",
    "i need to do it again": "",
    "she needs to go shopping": "",
    "my cousin needs to see it": "",
    "she often calls us": "",
    "she often calls you": "",
    "she often calls him": "",
    "she often calls her": "",
    "she often calls them": "",
    "she often calls me": "",
    "she has a car": "",
    "she has a good car": "",
    "he has a big house": "",
    "i need your help": "",
    "i really need your help": "",
    "i'd like to hear this story": "",
    "i want to listen to this song": "",
    "my brother wants to try to do it": "",
    "he wants to learn English to communicate with people from other countries": "",
    "i also like it": "",
    "i like it, too": "",
    "i need to know all the information": "",
    "i need to know everything": "",
    "my father does business": "",
    "my sister really likes it": "",
    "she often washes up the dishes": "",
    "mu sister often flies to the united states": "",
    "he reads a lot": "",
    "he doesn't read much": "",
    "i know a lot": "",
    "i don't know much about this problem": "",
    "my brother has many friends": "",
    "it often happens": "",
    "i see you'd like to live here": "",
    "my brother wants to study in another place": "",
    "my aunt wants to sell her house": "",
    "i don't learn English there": "",
    "i prefer learn English here": "",
    "she doesn't teach English": "",
    "she teaches maths": "",
    "i'd like to read a book in English": "",
    "my brother would like to try to do it": "",
    "i'd like to eat fish": "",
    "we'd like to play football": "",
    "i'd like to talk to you": "",
    "i'd like to tell you everything": "",
    "i'd like to work more": "",
    "i'd like to fly to New York": "",
    "she'd like to learn English here": "",
    "my brother wants to try to do it": "",
    "i'd like to get more money": "",
    "i don't watch her channel every day": "",
    "we'd like to invite you to the party": "",
    "i'd like to have my own business": "",
    "i want to do it now but very well": "",
    "my sister wants to buy this dress": "",
    "i'd like to thank you": "",
    "i'd like to hear this story": "",
    "i'd like to eat meat": "",
    "i'd like to watch your channel every day": "",
    "i don't go to school": "",
    "i go to university": "",
    "i'd like to drink a cup of tea": "",
    "i don't buy any newspapers or magazines": "",
    "i read them online": "",
    "we'd like to learn English here": "",
    "she doesn't say it": "",
    "she works a lot": "",
    "she wants to work less": "",
    "i don't live in Moscow": "",
    "i live in New York": "",
    "he goes to work by car": "",
    "i'd like to go the party": "",
    "i'd like to become a manager": "",
    "i don't live in England": "",
    "they'd like to call us": "",
    "i want to help you": "",
    "i'd like to thank you for your help": "",
    "i'd like to thank you for support": "",
    "i'd like to talk to you right now": "",
    "my friend wants to study in another place": "",
    "my friends don't order it online": "",
    "they buy it here": "",
    "i'd like to live in another country": "",
    "i want to learn English": "",
    "i don't go to work": "",
    "i don't work": "",
    "i stay at home": "",
    "i'd like to live abroad": "",
    "my boss doesn't want to do it": "",
    "it doesn't help me": "",
    "i want to read this book": "",
    "i want to live abroad": "",
    "i don't go to work every day": "",
    "i work from home": "",
    "i'd like to talk about this problem": "",
    "i'd really like to thank you": "",
    "i'd like to drink a cup of tea": "",
    "i don't go to university": "",
    "i go to work": "",
    "i don't understand native speakers": "",
    "my teacher doesn't like those lessons": "",
    "he likes these lessons": "",
    "my sister goes to school on foot": "",
    "my sister walks to school": "",
    "next": "",
    "i want to call him": "",
    "thanks": "",
    "thank you": "",
    "my sister would like to teach English": "",
    "i want to help my friend": "",
    "we want to know all the information": "",
    "she doesn't watch that channel": "",
    "she watches this channel": "",
    "my sister goes to school by car": "",
    "i'd like to be a manager": "",
    "i'd like to speak English very well": "",
    "he doesn't eat little": "",
    "he eats a lot": "",
    "i want to have a car": "",
    "my sitter would like to buy this dress": "",
    "she wants to know all the information": "",
    "he'd like to get this job": "",
    "i want to buy this thing": "",
    "i like it": "",
    "that lessons doesn't help": "",
    "this lesson helps": "",
    "all your lessons really help": "",
    "i don't play tennis": "",
    "she plays it": "",
    "she doesn't visit him": "",
    "she works hard": "",
    "she doesn't have free time": "",
    "i want to go to Italy next year": "",
    "my brother doesn't want to do this thing": "",
    "i'd like to be a teacher": "",
    "my sister also wants to teach English": "",
    "they want to call me": "",
    "i want to have a flat": "",
    "it doesn't interest me": "",
    "i'd like to have more free time": "",
    "i want to visit that place one more time": "",
    "i'd like to listen to this song": "",
    "we want to know all the information": "",
    "my brother doesn't understand me": "",
    "my relative wats to play this game": "",
    "we usually play different game": "",
    "we want to thank you": "",
    "my friend doesn't go to school on foot": "",
    "my friend doesn't walk to school": "",
    "we want to have our own business": "",
    "she doesn't like that channel": "",
    "she likes this channel": "",
    "i don't eat meat but i eat fish": "",
    "you don't understand it": "",
    "i'd like to listen to it": "",
    "i want to visit this place": "",
    "i'd like to learn English very hard": "",
    "she wants to work more": "",
    "i want to work less": "",
    "i'd like to hear this story right now": "",
    "i'd like to drink a glass of water": "",
    "her relative wants to rent a flat": "",
    "my uncle doesn't want to call her": "",
    "i'd like to visit that place": "",
    "i'd like to fo to that restaurant": "",
    "we'd like to go to the party": "",
    "i'd like to know English very well": "",
    "i'd like to hear all the story": "",
    "i want a cup of coffee": "",
    "i think i'd like to work more": "",
    "i want to go to America next month": "",
    "we'd like to talk to you": "",
    "she'd like to become an English teacher": "",
    "i want to see it": "",
    "we want to see this thing": "",
    "my relative wants to study abroad": "",
    "i'd like to order it": "",
    "i want to have a house": "",
    "i'd like to translate this word": "",
    "we'd like to translate thi phrase": "",
    "i don't speak English fluently": "",
    "i try to learn it": "",
    "her cousin doesn't want to do it right now": "",
    "he wants to do it later": "",
    "i'd like to visit this places": "",
    "i want to watch your channel every day": "",
    "we want to learn English here": "",
    "i'd really like to thank you for your help": "",
    "i don't buy food": "",
    "my parents buy all the food": "",
    "they'd like to join us": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",



}