slovar = {
    "wake(up) - woke - woken": "",
    "I woke up very early": "",
    "I got up very early": "",
    "I woke up at 6 o'clock in the morning": "",
    "He woke up late": "",
    "leave - left - left": "",
    "I live in this city": "",
    "I left my wallet at home": "",
    "I left it in my room": "",
    "I left Russia": "",
    "We left America": "",
    "Break - broke - broken": "",
    "They broke the rules": "",
    "He broke the window": "",
    "Break down": "",
    "His car often broke down": "",
    "keep - kept - kept": "",
    "I kept his secret": "",
    "I kept my promise": "",
    "He kept his word": "",
    "Hold - held - held": "",
    "He held her bag": "",
    "He held that box": "",
    "He held it in his arms": "",
    "let - let - let": "",
    "His parents let him go out": "",
    "---let somebody do something---": "",
    "They let him be there until midnight": "",
    "They let him stay there until midnight": "",
    "His parents let him play outside": "",
    "Mean - meant - meant": "",
    "It meant the following": "",
    "His behavior meant the following thing": "",
    "mean nothing": "",
    "It meant nothing": "",
    "It didn't mean anything": "",
    "win - won - won": "",
    "I won in that competition": "",
    "We won in that tournament": "",
    "We won the game": "",
    "blow - blew - blown": "",
    "The wind blew suddenly": "",
    "The wind blew so strongly": "",
    "They often broke the rules": "",
    "He held that box": "",
    "They stole this information": "",
    "He kept his money in a safe place": "",
    "His car broke down": "",
    "Her car broke down quite often": "",
    "His behavior meant the following": "",
    "My car broke down very rarely": "",
    "Their team won unexpectedly": "",
    "They let him stay there until midnight": "",
    "His parents let him go out": "",
    "He broke her pen": "",
    "He held her bag": "",
    "We won the game": "",
    "He stole such expensive things": "",
    "I meant the following thing": "",
    "They stole his idea": "",
    "I won 500( five hundred) dollars": "",
    "I left Russia": "",
    "His parents let him play outside": "",
    "He stole her bag": "",
    "We left Russia last year": "",
    "I woke up as usual": "",
    "He held the door": "",
    "We left America": "",
    "I left my wallet at home": "",
    "The wind blew suddenly": "",
    "I left money at home": "",
    "He held her hand": "",
    "I won in that competition": "",
    "I left it in your room": "",
    "It meant nothing": "",
    "It didn't mean anything": "",
    "He woke up late": "",
    "Our team won suddenly": "",
    "He broke his promise": "",
    "They stole his clothes": "",
    "I kept his secret": "",
    "I left my keys": "",
    "My car broke down very rarely": "",
    "Her words meant a strange thing": "",
    "She kept her money in a bank": "",
    "I woke up at 6 o'clock in the morning": "",
    "I woke up very early": "",
    "The car often broke down": "",
    "We won in that tournament": "",
    "He broke the window": "",
    "I left home 20 minutes ago": "",
    "The wind blew so strongly": "",
    "I left the office late": "",
    "I left home at 8 o'clock in the morning": "",
    "grow - grew - grown": "",
    "He grew vegetables in his own garden": "",
    "grow up": "",
    "I grew up in Russia": "",
    "He grew up in America": "",
    "lie - lay - lain": "",
    "lie down": "",
    "I lay down": "",
    "The pen lay on the desk": "",
    "lie - lied -lied": "",
    "She lied to me": "",
    "fall - fell - fallen": "",
    "The price fell sharply": "",
    "fall down": "",
    "He fell down": "",
    "She fell down and broke her arm": "",
    "spend - spent - spent": "",
    "He spent all his money": "",
    "He spent more than he wanted": "",
    "I spent two hours on it": "",
    "She spent 200 dollars": "",
    "drive - drove - driven": "",
    "I drove a car yesterday": "",
    "drive home": "",
    "drive to work": "",
    "I drove to work": "",
    "I drove home": "",
    "draw - drew - drawn": "",
    "He drew a picture": "",
    "She drew such a beautiful picture": "",
    "She drew his face": "",
    "wear - wore - worn": "",
    "I wore school uniform": "",
    "I wore glasses": "",
    "He wore casual clothes": "",
    "Hurt - hurt - hurt": "",
    "He hurt his leg": "",
    "She fell down and hurt her leg": "",
    "She hurt her arm": "",
    "He hurt her feelings": "",
    "cut - cut- cut": "",
    "He cut the meat": "",
    "She cut the fish": "",
    "He cut himself": "",
    "She cut herself": "",
    "He cut the meat into small pieces": "",
    "forget - forgot - forgotten": "",
    "I forgot his name": "",
    "I forgot to do it": "",
    "I forgot to call her": "",
    "I forgot to close the door": "",
    "I forgot to lock the door": "",
    "He cut the meat": "",
    "She sut herself": "",
    "He lay down": "",
    "The book lay on the table": "",
    "She grew flowers": "",
    "He lied to her": "",
    "She lied to her boss": "",
    "He grew vegetables in his own garden": "",
    "I grew up in Russia": "",
    "I forgot to call her": "",
    "She fell down and broke her arm": "",
    "He drove to me": "",
    "I forgot his name": "",
    "It lay near that place": "",
    "it lay far from that place": "",
    "The bag lay far from there": "",
    "The price fell suddenly": "",
    "I wore school uniform": "",
    "I spent 2 hours on it": "",
    "He grew up in America": "",
    "She hurt her arm": "",
    "The price fell sharply": "",
    "He drew such a funny picture": "",
    "She drew a picture": "",
    "My friend drove home": "",
    "She spent her last money": "",
    "I forgot to do it one more time": "",
    "I spent so much time on it": "",
    "She spent 200 dollars": "",
    "She drew such a beautiful picture": "",
    "I drove to school": "",
    "He spent all his money": "",
    "I forgot to lock the door": "",
    "The pen lay on the desk": "",
    "He hurt his leg": "",
    "We drove to the airport": "",
    "She wore informal clothes": "",
    "She drew his face": "",
    "She wore casual clothes": "",
    "I drove a car yesterday": "",
    "He cut his finger": "",
    "She spent too much time on it": "",
    "I forgot to do it": "",
    "He fell down": "",
    "I wore glasses": "",
    "He cut himself": "",
    "I forgot how to use it": "",
    "He fell down and broke his leg": "",
    "They always spent more money": "",
    "He cut the meat into small pieces": "",
    "I spent 3 hours on it": "",
    "I forgot the name of this street": "",
    "She wore formal clothes": "",
    "I drove to work": "",
    "He grew up in Canada": "",
    "He hurt her feelings": "",
    "She cur the fish": "",
    "It hurt her feelings": "",
    "He spent more than he wanted": "",
    "The last example": "",
    "I spent a lot of energy(lots of energy)": "",
    "I spent lots of energy on this project": "",
    "sing - sang - sung": "",
    "She sang a very beautiful song": "",
    "She sang very beautifully": "",
    "He sang his favorite song": "",
    "Teach - taught - taught": "",
    "I taught English": "",
    "He taught them Russian": "",
    "He taught history": "",
    "throw - threw - thrown": "",
    "He threw a ball to him": "",
    "He threw a ball at him": "",
    "throw away": "",
    "He threw it away": "",
    "feed - fed - fed": "",
    "He fed his dog": "",
    "She fed her cat": "",
    "She fed her baby": "",
    "They fed the children": "",
    "lend - lent - lent": "",
    "I lent him some money": "",
    "I lent him 300 dollars": "",
    "They lent him a big sum of money": "",
    "Ring - rang - rung": "",
    "The bell rang": "",
    "My alarm clock rang": "",
    "I called him": "",
    "I rang him": "",
    "hide - hid - hidden": "",
    "He hid from them": "",
    "She hid behind the tree": "",
    "He hid behind that building": "",
    "Hit - hit - hit": "",
    "He hit the ball": "",
    "He hit the door": "",
    "beat - beat - beaten": "",
    "They beat him very badly": "",
    "Strongly": "",
    "beat someone badly": "",
    "They beat that team": "",
    "ride - rode - ridden": "",
    "I rode a bike": "",
    "I rode a horse": "",
    "I rode a camel": "",
    "I can ride a bike": "",
    "go cycling": "",
    "I went cycling": "",
    "It sounds very natural": "",
    "run - ran - run": "",
    "go jogging": "",
    "I went jogging": "",
    "for free": "",
    "He has too much money": "",
    "He has too many mistakes": "",
    "uncountable": "",
    "countable": "",
    "I know a lot": "",
    "He doesn't know much": "",
    "I speak English a lot": "",
    "can + verb": "",
    "I can say it": "",
    # past
    "I could say it": "",
    "It's mistake": "",
    "Is it a mistake?": "",
    "horrible": "",
    "It's a revolutionary method": "",
    "The bell rang": "",
    "He sang his favorite song": "",
    "He taught this subject last year": "",
    "She taught several subject there": "",
    "He taught history": "",
    "She fed the children": "",
    "She hid from them": "",
    "His alarm clock rang suddenly": "",
    "He hid from them": "",
    "She fed her cat": "",
    "She sang three beautiful songs": "",
    "She taught us English very well": "",
    "She fed her baby": "",
    "They beat that team": "",
    "He threw a ball to him": "",
    "I lent him some money": "",
    "He taught English when he was 20 years old": "",
    "She threw it away": "",
    "She sang very beautifully": "",
    "I went cycling": "",
    "I rode a bike": "",
    "He threw it away": "",
    "He sang professionally": "",
    "I lent him 500 euros": "",
    "I rode a horse": "",
    "He hid behind that building": "",
    "He hit the ball": "",
    "He fed his dog": "",
    "They hid from us": "",
    "They fed the children": "",
    "He hit him first": "",
    "They sang their favorite song": "",
    "He lent her 200 pounds": "",
    "We went jogging three times a week": "",
    "They lent him a very big sum of money": "",
    "He threw a small ball to him": "",
    "They beat him very badly": "",
    "He taught them Russian": "",
    "He fed his pet": "",
    "I taught English": "",
    "He threw them away": "",
    "She taught English there 2 years ago": "",
    "He hit the door": "",
    "I taught him a lesson": "",
    "She hid behind the tree": "",
    "I rode a camel": "",
    "My alarm clock rang": "",
    "I lent him 300 dollars": "",
    "She sang a very beautiful song": "",
    "I went jogging": "",
    "I ran very fast": "",
    "break - broke - broken": "",
    "His car broke down": "",
    "lie - lay - lain": "",
    "The pen lie on the desk": "",
    "lie - lied - lied": "",
    "She lied to her parents": "",
    "Write - wrote - written": "",
    "She wrote a letter": "",
    "leave - left - left": "",
    "I left Russia": "",
    "come - came - come": "",
    "He came to me": "",
    "think - thought - thought": "",
    "I thought about this problem": "",
    "Hear - heard - heard": "",
    "I heard it from him": "",
    "Know - knew - known": "",
    "I knew her secret": "",
    "Keep - kept - kept": "",
    "He kept his word": "",
    "find - found - found": "",
    "He found his keys": "",
    "He found his lost keys": "",
    "mean - meant - meant": "",
    "I meant the following thing": "",
    "be - was/were - been": "",
    "It was such a good idea": "",
    "swim - swam - swum": "",
    "We swam in the sea": "",
    "ride - rode - ridden": "",
    "I rode a horse": "",
    "hold - held - held": "",
    "I held the door": "",
    "get - got - got": "",
    "I got up very early": "",
    "Hurt - hurt - hurt": "",
    "He fell down and hurt his arm": "",
    "feed - fed - fed": "",
    "She fed her cat": "",
    "stand - stood - stood": "",
    "He stood up": "",
    "fly - flew - flown": "",
    "She flew to Canada": "",
    "Drive - drove - driven": "",
    "I drove to work": "",
    "meet - met - met": "",
    "I met this word for the first time": "",
    "sit - sat - sat": "",
    "He sat down": "",
    "sing - sang - sung": "",
    "She sang so beautifully": "",
    "I drank a glass of juice": "",
    "let - let - let": "",
    "They let her stay there until midnight": "",
    "grow - grew - grown": "",
    "I grew up in America": "",
    "We went there together": "",
    "beat - beat - beaten": "",
    "They beat him very badly": "",
    "Become - became - become": "",
    "He became famous": "",
    "Wake - woke - woken": "",
    "I woke up very early": "",
    "fall - fell - fallen": "",
    "The price fell unexpectedly": "",
    "Feel - felt - felt": "",
    "I felt better": "",
    "Wear - wore - worn": "",
    "She wore stylish fashionable clothes": "",
    "read = read - read": "",
    "I read a lot": "",
    "buy - bought - bought": "",
    "He bought a house": "",
    "ring = rang - rung": "",
    "The bell rang": "",
    "lend - lent = lent": "",
    "I lend him 2000 dollars": "",
    "make - made = made": "",
    "He made a big mistake": "",
    "Have - had = had": "",
    "She had a boyfriend": "",
    "begin = began - begun": "",
    "The meeting began on time": "",
    "steal - stole - stolen": "",
    "They stole his wallet": "",
    "do = did - done": "",
    "He did his homework": "",
    "cost - cost - cost": "",
    "It cost little": "",
    "Lose = lost - lost": "",
    "He lost this money": "",
    "blow = blew - blown": "",
    "The wind blew suddenly": "",
    "spend - spent = spent": "",
    "she spent more less": "",
    "cut - cut - cut": "",
    "he cut his finger": "",
    "Understand = understood": "",
    "I understood you perfectly": "",
    "Hit - hit - hit": "",
    "He hit the ball": "",
    "see - saw - seen": "",
    "I saw progress": "",
    "I saw progress": "",
    "send - sent - sent": "",
    "She sent me a letter": "",
    "Show = showed - shown": "",
    "He showed me his excellent results": "",
    "Pay = paid = paid": "",
    "I paid for her": "",
    "throw - threw = thrown": "",
    "I threw it away": "",
    "draw ": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

}