slovar = {
    "I don't buy food": "",
    "My parents usually buy it": "",
    "I need it": "",
    "I need your help": "",
    "I need your advice": "",
    "I need your recommendation": "",
    "I need more practice": "",
    "I need a good teacher": "",
    "I need more lessons": "",
    "I need these lessons": "",
    "I need a pen": "",
    "I need a pencil": "",
    "I need money": "",
    "I need more money": "",
    "I need to find a good job": "",
    "I need to know it right now": "",
    "I need to check it": "",
    "I need to go to that place": "",
    "We need more exercises": "",
    "You need more rest": "",
    "They need more lessons": "",
    "He needs more lessons": "",
    "She needs more practice": "",
    "My friend needs to learn English": "",
    "My brother needs to go there": "",
    "My friends need to buy this things": "",
    "I go to China": "",
    "I go to the United States": "",
    "I want this thing": "",
    "I want to buy this thing": "",
    "She wants to speak English fluently": "",
    "My friend wants to translate this text": "",
    "I want a cup of tea": "",
    "I'd like a cup of tea": "",
    "I'd like to drink a cup of tea": "",
    "She'd like to visit this place": "",
    "They'd like to order it online": "",
    "I don't understand": "",
    "It doesn't seem interesting": "",
    "This idea doesn't seem interesting": "",
    "She often calls us": "",
    "She often calls you": "",
    "She has a car": "",
    "She has a good car": "",
    "He has a big house": "",
    "I need your help": "",
    "I really need your help": "",
    "I'd like to hear this story": "",
    "I want to listen to this song": "",
    "My brother wants to try to do it": "",
    "My father does business": "",
    "My sister really likes it": "",
    "She often washes up the dishes": "",
    "My sister often flies to the United States": "",
    "We go ahead slowly but very effectively": "",
    "I see you'd like to live here": "",
    "My brother wants to study in another place": "",
    "My aunt wants to sell her house": "",
    "I prefer to learn English here": "",
    "She teaches mathematics": "",
    "I'd like to read a book in English": "",
    "You have a job": "",
    "Do you have a job?": "",
    "I show good results": "",
    "Do I show good results?": "",
    "We have an interesting offer": "",
    "Do we have an interesting offer?": "",
    "You do it professionally": "",
    "Do you do it professionally?": "",
    "More examples and exercises": "",
    "Do I know it better?": "",
    "We often hear these things": "",
    "Do we often hear these things?": "",
    "You often say it": "",
    "Do you often say it?": "",
    "They get 500 dollars a month": "",
    "Do you understand me?": "",
    "Yes, I understand you": "",
    "Does she understand us": "",
    "Does she speak English?": "",
    "Does he live there?": "",
    "Does it help you a lot?": "",
    "Does it seem interesting?": "",
    "Does it look beautiful?": "",
    "Does it happen from time to time?": "",
    "Does it interest you?": "",
    "Does she believe in God?": "",
    "Does she remember it?": "",
    "Does she support this idea?": "",
    "Does he agree with you?": "",
    "Does he do business?": "",
    "Does he often stay at home?": "",
    "Does he often travel?": "",
    "Does she feel good?": "",
    "Does he feel bad?": "",
    "Does it work?": "",
    "Does it really work?": "",
    "Does he need it urgently?": "",
    "Does she need your advice?": "",
    "Does she call him?": "",
    "Does she often call him?": "",
    "Does she often visit him?": "",
    "Does he often see them?": "",
    "Does it help you?": "",
    "Does it really help you?": "",
    "Do his parents believe in God?": "",
    "Does your cousin believe in ghosts?": "",
    "He wants to be a businessman": "",
    "He doesn't want to be a businessman": "",
    "They have their own business": "",
    "They don't have their own business": "",
    "Do they have their own business?": "",
    "My brother often waits for it": "",
    "My brother doesn't wait for it": "",
    "Does my brother wait for it?": "",
    "My ticket includes it": "",
    "My ticket doesn't include it": "",
    "Does my ticket include it?": "",
    "When do you do it?": "",
    "When do you watch English movies?": "",
    "When do you learn English?": "",
    "When do you go to school?": "",
    "When does she see him?": "",
    "When do they see her?": "",
    "When does it happen?": "",
    "When does he come?": "",
    "Why do you learn English?": "",
    "Why do you support him?": "",
    "Why do you teach English?": "",
    "Why do you do it?": "",
    "Why does it happen?": "",
    "Why does it seem interesting?": "",
    "Why does it seem boring?": "",
    "Why does it interest you?": "",
    "Why do you think so?": "",
    "What do you think about it?": "",
    "What do you sell?": "",
    "What do you buy there?": "",
    "What do you teach?": "",
    "What do you mean?": "",
    "What do you want to say?": "",
    "What does it mean?": "",
    "What do you need?": "",
    "What does she need?": "",
    "What does he need?": "",
    "What do you want?": "",
    "How do you do it?": "",
    "How do you explain it?": "",
    "How do they speak?": "",
    "How do they understand it?": "",
    "How do you pay?": "",
    "How do you feel?": "",
    "How does she feel?": "",
    "How do you get to work?": "",
    "How do you get to school?": "",
    "How does she study?": "",
    "How does he feel?": "",
    "Where does she live?": "",
    "Where does your sister live?": "",
    "When do these lessons start?": "",
    "What does your brother do at work?": "",
    "What do your parents know?": "",
    "Where does your father work?": "",
    "Why does your boss learn English?": "",
    "How does his girlfriend look like?": "",
    "When does your boyfriend find time for it?": "",
    "What does your grandmother grow in her garden?": "",
    "When does this lessons usually start?": "",
    "When does that lessons usually finish?": "",
    "When do the lessons start?": "",
    "When do the lessons finish?": "",
    "What does your wife cook?": "",
    "What does your wife usually cook?": "",
    "What does your husband usually eat?": "",
    "Where do your children study?": "",
    "Where does your son study?": "",
    "Where does your daughter study?": "",
    "What do your suppliers produce?": "",
    "What do your partners think about this situation?": "",
    "What do your clients usually answer(reply)?": "",
    "What does this ticket include?": "",
    "How does the company work?": "",
    "Why does your best friend hate it?": "",
    "How does yor sister swim?": "",
    "What does your boss promise?": "",
    "When do the exams start?": "",
    "Why does your friend think differently?": "",
    "Why does your friend think another way?": "",
    "Where does your son want to study?": "",
    "How does she find time for everything?": "",
    "Why do they refuse do it?": "",
    "Why does he complain?": "",
    "My partner doesn't have an interesting offer": "",
    "I don't have a car": "",
    "I haven't got a car": "",
    "I go to work": "",
    "I have a job": "",
    "I like my job": "",
    "We work together very well": "",
    "I learn English online on the channel English Galaxy": "",
    "When do the lessons finish?": "",
    "When does the lesson finish?": "",
    "Does he want to have a car?": "",
    "He runs fast": "",
    "She usually says it very quickly": "",
    "He doesn't have his own business": "",
    "Do his students fell progress?": "",
    "I think differently": "",
    "I think another way": "",
    "Do your parents also think so?": "",
    "I am in the park": "",
    "I'm in the park": "",
    "We are at home": "",
    "We're at home": "",
    "You are a good teacher": "",
    "You're a good teacher": "",
    "He is my good friend": "",
    "He's my good friend": "",
    "She's my girlfriend": "",
    "It is interesting": "",
    "I'm in my room": "",
    "I'm outside": "",
    "We're good students": "",
    "We're hard-working": "",
    "We're hard-working students": "",
    "You're the best teacher": "",
    "You're a good teacher": "",
    "You're kind": "",
    "It's a long story": "",
    "It's an interesting detail": "",
    "It's a short phrase": "",
    "It's important": "",
    "The lesson is interesting": "",
    "Your lessons are really good": "",
    "This students is talented": "",
    "The room is small": "",
    "This idea is very interesting": "",
    "This result is real": "",
    "I am at home": "",
    "I am not at home": "",
    "We are not inside": "",
    "You are right": "",
    "You are not right": "",
    "It isn't cold. It's warm": "",
    "It isn't good. It's bad": "",
    "It isn't interesting. It's boring": "",
    "It's isn't strange. It's normal": "",
    "It isn't difficult. It's easy. It's obvious": "",
    "It isn't sunny. It's cloudy. It's rainy": "",
    "It's windy": "",
    "It isn't an interesting job": "",
    "Their ideas aren't so innovative": "",
    "This thing isn't popular now": "",
    "These things aren't popular now": "",
    "Are we in the right place?": "",
    "Are you in his office?": "",
    "Are they your colleagues?": "",
    "Is he your acquaintance?": "",
    "Is she a housewife?": "",
    "Is it expensive?": "",
    "Am I a good student?": "",
    "Am I wrong?": "",
    "Am I in the wrong place?": "",
    "Are we far from this place?": "",
    "Are we near this place?": "",
    "Are we in one group?": "",
    "Are you really happy?": "",
    "Are you together?": "",
    "Are you in one team?": "",
    "Are they good specialists?": "",
    "Are they experts in this area?": "",
    "Are they experienced?": "",
    "Is he happy?": "",
    "Is he a happy person?": "",
    "Is he a businessman?": "",
    "Is he a successful businessman?": "",
    "Is she an actress?": "",
    "Are these lessons really effective?": "",
    "Is his father rich?": "",
    "Is his mother a businesswoman?": "",
    "Are our friends there?": "",
    "Is this word new for you?": "",
    "Is this school good enough?": "",
    "Is this detail important?": "",
    "Is this hotel so expensive?": "",
    "Is your computer so powerful?": "",
    "Is this thing really necessary?": "",
    "Is his method different?": "",
    "Is this level basic?": "",
    "Is his level high enough?": "",
    "Are all these videos really useful?": "",
    "Is his girlfriend very emotional": "",
    "Are your ideas similar?": "",
    "Are his ideas the same?": "",
    "Are these methods traditional?": "",
    "Are your parents at home?": "",
    "Is your father a businessman?": "",
    "Is your brother a freelancer?": "",
    "Is your mother a housewife?": "",
    "Is this money enough?": "",
    "Is our knowledge enough?": "",
    "Is the news sad?": "",
    "Is this information reliable?": "",
    "Are the boys busy at the moment?": "",
    "Are the girls with a teacher?": "",
    "Is the boy really so talented?": "",
    "Is the girl the best student?": "",
    "Is the computer expensive?": "",
    "Is the result good enough?": "",
    "Are the results satisfactory?": "",
    "Is the progress slow?": "",
    "Is the lesson very informative?": "",
    "Is the video so funny?": "",
    "Are the boys poor?": "",
    "Are the girls rich?": "",
    "Are their ideas the same?": "",
    "Is this hotel good enough?": "",
    "Are these lessons really so effective?": "",
    "They're in a safe place": "",
    "They aren't in a safe place": "",
    "Are they in a safe place?": "",
    "He's an expert in this area": "",
    "He isn't an expert in this area": "",
    "Is he an expert in this area?": "",
    "She's a native speaker": "",
    "Is she a native speaker?": "",
    "How are you?": "",
    "Why is she still there?": "",
    "When are they in the office?": "",
    "Where is they nearest supermarket?": "",
    "What is it?": "",
    "Who is he?": "",
    "How much is it?": "",
    "How far is it?": "",
    "Where are you from?": "",
    "I'm from Russia": "",
    "Where is he from?": "",
    "He's from England": "",
    "How is life?": "",
    "How is this project?": "",
    "How are his parents?": "",
    "Why are we here?": "",
    "Why is she so sure?": "",
    "Why is it so important?": "",
    "When is he at home?": "",
    "When are they together?": "",
    "When are you free?": "",
    "Where is the nearest hotel?": "",
    "Where is this place?": "",
    "Where are my keys?": "",
    "What is in this box?": "",
    "What is in his head?": "",
    "What is there?": "",
    "Who is right?": "",
    "Who is present?": "",
    "Who is absent?": "",
    "Who knows it?": "",
    "Who likes it?": "",
    "Why is this offer so attractive?": "",
    "Why is this detail so important?": "",
    "Why are these things necessary?": "",
    "Why is this level basic?": "",
    "Why are you so surprised?": "",
    "He worked to much": "",
    "She wanted to find a better job": "",
    "He went there by car": "",
    "I lived there a long time ago": "",
    "They lived happily": "",
    "They played in one time": "",
    "I played football yesterday": "",
    "I tried to help him": "",
    "I tried to pass the exam": "",
    "I needed more time": "",
    "I needed to fined it urgently": "",
    "She helped me a lot": "",
    "That experience helped me a lot": "",
    "It happened to me": "",
    "A strange thing happened to my boss": "",
    "I remember it at last": "",
    "I remembered the meaning of this word": "",
    "She closed her eyes": "",
    "I closed the door": "",
    "I opened the door": "",
    "She opened her eyes": "",
    "I decided to learn English here": "",
    "We decided to meet tomorrow": "",
    "She asked me to wait for her": "",
    "I asked her to help": "",
    "I improved my English a lot": "",
    "I improved my English greatly": "",
    "I improved my English greatly thanks to this channel": "",
    "It wasn't a strange offer. That offer was quite normal": "",
    "They weren't satisfied with his decision": "",
    "She didn't know what to say": "",
    "She didn't find her lost keys": "",
    "He didn't thank them for help": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

}