slovar = {
    "Does it work?": "",
    "Does it really work?": "",
    "Does he need urgently?": "",
    "Does she need your advice?": "",
    "Does she call him?": "",
    "Does she often call him?": "",
    "Does she often visit him?": "",
    "Does he often see him?": "",
    "Does it help you?": "",
    "Does it really help you?": "",
    "Does he go to bed early?": "",
    "Does she use the internet every day?": "",
    "Does he like orange juice?": "",
    "Does she like this subject?": "",
    "This/That/my/your/our ...another": "",
    "Does he need money now?": "",
    "Does she need support?": "",
    "Does he smoke?": "",
    "Does she read magazines?": "",
    "Does he read newspapers?": "",
    "Does she often to the United States?": "",
    "Does she usually sleep well?": "",
    "Does she sing songs?": "",
    "Does it seem strange?": "",
    "Does it seem boring?": "",
    "Does it look wonderful?": "",
    "Does he play the guitar?": "",
    "Does she draw well?": "",
    "Does he dance professionally?": "",
    # present simple ( Question )
    "Does his friend want to continue it?": "",
    "Does our rest include it?": "",
    "Does her sister often meet her?": "",
    "Do their friends often pay for it?": "",
    "Does this thing happen very rarely/seldom?": "",
    "Do his parents believe in God?": "",
    "Does your cousin believe in Ghosts?": "",
    "Does your boyfriend believe him?": "",
    "Do your colleagues live near this place?": "",
    "Does your classmate run very fast?": "",
    "Do your neighbors often hear this story?": "",
    "Do these lessons help?": "",
    "Does this lesson help?": "",
    "Does this idea seem interesting?": "",
    "Do these ideas seem interesting?": "",
    "Does his wife usually buy expensive things?": "",
    "Does her husband usually buy cheap things?": "",
    "Do the boys remember it very well?": "",
    "The --- this/that/these/those": "",
    "Do the girls know it perfectly?": "",
    "Does the lesson seem very long?": "",
    "Does the story seem very short?": "",
    "He wants to be a businessman": "",
    "He doesn't want to be a businessman": "",
    "Does he want to be a businessman?": "",
    "They have their own business": "",
    "They don't have their own business": "",
    "Do they have their own business?": "",
    "My brother often waits for it": "",
    "My brother doesn't wait for it": "",
    "Does my brother wait for it?": "",
    "My sister loves him": "",
    "My sister doesn't love him": "",
    "Does my sister love him?": "",
    "his - her - book": "",
    "My teacher remembers everything": "",
    "all these thing / all these fact / all the information": "",
    "My teacher doesn't remember everything": "",
    "Does my teacher remember everything?": "",
    "My boss forgets different things": "",
    "forgets - leaves": "",
    "My boss doesn't forget these things": "",
    "Does my boss forget these things?": "",
    "The company offers us new workers": "",
    "The company doesn't offer us new workers": "",
    "Does the company offer us new workers?": "",
    "The book seems very useful": "",
    "The book doesn't seem very useful": "",
    "Does the book seem very useful": "",
    "My ticket includes it": "",
    "My ticket doesn't include it": "",
    "Does my ticket include it?": "",
    "The lessons start(begin) very early": "",
    "The lessons don't start very early": "",
    "Do the lessons start very early?": "",
    # when / where / why / how / what  + do/does + S -----?
    "When do you do it?": "",
    "When do you watch English movies?": "",
    "When do you learn English?": "",
    "When do you go to school?": "",
    "When does she see him?": "",
    "When do they see her?": "",
    "When does it happen?": "",
    "When does he come?": "",
    "Why do you learn English?": "",
    "Why do you support him?": "",
    "Why do you teach English?": "",
    "Why do you do it?": "",
    "Why does it happen?": "",
    "Why does it seem interesting?": "",
    "Why does it seem boring?": "",
    "Why does it interest you?": "",
    "Why do you think so?": "",
    "What do you think about it?": "",
    "What do you sell?": "",
    "What do you buy there?": "",
    "What do you teach?": "",
    "What do you mean?": "",
    "What do you want to say?": "",
    "What does it mean?": "",
    "What do you need?": "",
    "What does she need?": "",
    "What does he need?": "",
    "What do you want?": "",
    "How do you do it?": "",
    "How do you explain it?": "",
    "How do they speak?": "",
    "How do they understand it?": "",
    "How do you pay?": "",
    "How do you feel?": "",
    "How does she feel?": "",
    "How do you get to work?": "",
    "How do you get to school?": "",
    "How does she study?": "",
    "How does he feel?": "",
    # when /Where / why / how / what + do/does + S + verb
    "Where does she live?": "",
    "Where does your sister live?": "",
    "When do these lessons start?": "",
    "What does your brother do at work?": "",
    "What do your parents know?": "",
    "Where does your father work?": "",
    "Why does your boss learn English?": "",
    "How does his girlfriend look like?": "",
    "When does your boyfriend find time for it?": "",
    "What does your grandmother grow in her garden?": "",
    "When does this lesson usually start?": "",
    "When does that lesson usually finish?": "",
    "When do the lessons start?": "",
    "When do the lessons finish?": "",
    "What does your wife cook?": "",
    "What does your wife usually cook?": "",
    "What does your husband usually eat?": "",
    "Where do your children study?": "",
    "Where does your son study?": "",
    "Where does your daughter study?": "",
    "What do your suppliers produce?": "",
    "What do your partners think about this situation?": "",
    "What do your clients usually answer?": "",
    "What do your clients usually reply?": "",
    "What does this ticket include?": "",
    "How does the company work?": "",
    "Why does your best friend hate it?": "",
    "How does your sister swim?": "",
    "What does your boss promise?": "",
    "When do the exams start?": "",
    "Why does your friend think differently?": "",
    "Why does your friend think another way?": "",
    "Where does your son want to study?": "",
    "How does she find time for everything?": "",
    "Why do they refuse to do it?": "",
    # Do + I/we/you/they + verb?
    # Does + he/she/it + verb?
    "Do you find it interesting?": "",
    "Does she find it boring?": "",
    "Do your parents find it strange?": "",
    "Does your friend consider it a waste of time?": "",
    # When/where/why/how/what + do/does + S + verb?
    "Why does he complain?": "",
    "What do they buy?": "",
    "What do they usually buy?": "",
    "What does your girlfriend usually cook?": "",
    "When does your teacher check it?": "",
    "How do their parents control it?": "",
    "I want to learn English really fast": "",
    "He runs fast": "",
    "When do the exams finish?": "",
    "Does your boyfriend want to buy a new car?": "",
    "Does she run fast?": "",
    "What do they usually have for breakfast?": "",
    "Do you have your own business?": "",
    "My partner doesn't have an interesting offer": "",
    "I don't have a car": "",
    "I haven't got a car": "",
    "Does she get 300 dollars a month?": "",
    "I go to work": "",
    "I work very hard": "",
    "I have a job": "",
    "I like my job": "",
    "I have good colleagues": "",
    "We work together very well": "",
    "I have different hobbies": "",
    "I like English": "",
    "I learn English online on the channel English Galaxy": "",
    "I prefer to learn English effectively": "",
    "Where do you study?": "",
    "Do you have a job?": "",
    "Do you have good friends?": "",
    "Where does your friend work?": "",
    "Where does your friend study?": "",
    "How does he spend his free time?": "",
    "How does she prefer to learn English?": "",
    "Why does she learn Spanish?": "",
    "I really like it": "",
    "I think I like it": "",
    "I get up early": "",
    "I usually get up early": "",
    "Really, I like it": "",
    "It works well": "",
    "It doesn't work well": "",
    "Does it work well?": "",
    "This idea seems good": "",
    "This idea doesn't seem good": "",
    "Does this idea seem good?": "",
    "I would like to learn English here": "",
    "She would like to study there": "",
    "I'd like .....she'd like": "",
    # I/we/you/they/ have an idea
    # he/she has an idea
    "When do the lessons finish?": "",
    "When does the lesson finish?": "",
    "Does he want to have a car?": "",
    "He runs fast": "",
    "She usually says it very quickly": "",
    "Why do these problems interest you?": "",
    "What do all these things mean?": "",
    "it's my new car": "",
    "it's his old car": "",
    "it's a big building": "",
    "it's a small house": "",
    "it's on the table": "",
    "it's on my desk": "",
    "it's on my bed": "",
    "it's in this city": "",
    "it's on this town": "",
    "it's good": "",
    "It's a good idea": "",
    "It's bad": "",
    "It's a bad idea": "",
    "It's a good result": "",
    "It's a long story": "",
    "It's an interesting detail": "",
    "It's a short phrase": "",
    "It's important": "",
    "It's an important thing": "",
    "It's difficult": "",
    "It's a big problem": "",
    "It's a small problem": "",
    "It's very interesting": "",
    "It's so interesting": "",
    "I'm busy": "",
    "I'm tired": "",
    "We're at the airport": "",
    "You're a good friend": "",
    "They're in Russia": "",
    "They're in the United States": "",
    "They're in the United Kingdom": "",
    "He's in China": "",
    "She's in America": "",
    "It's in our country": "",
    # Present Simple - to be
    # I'm / We're You're / They're / He's / She's / It's
    "The lesson is interesting": "",
    "Your lessons are really good": "",
    "This student is talented": "",
    "The room is small": "",
    "This idea is very interesting": "",
    "This result is real": "",
    "These things are very strange": "",
    "These results are wonderful": "",
    "These results are terrible": "",
    "This teacher is the best teacher in the world": "",
    "This lesson is free": "",
    "All these lessons are free": "",
    "This lesson is very useful": "",
    "All these lessons are very useful": "",
    "This method is very effective": "",
    "The boy is talented": "",
    "My sister is in bad": "",
    "My brother is in the kitchen": "",
    "MY mother is in the bathroom": "",
    "My parents are angry": "",
    "The keys are on the table": "",
    "The book is red": "",
    "The number is short": "",
    "The hotel is expensive": "",
    "The ticket is cheap": "",
    "The tickets are cheap": "",
    "My friend is ill": "",
    "My friend is sick": "",
    "The chair is comfortable": "",
    "This chair is comfortable": "",
    "These chairs are comfortable": "",
    "The information is useful": "",
    "This information is useful": "",
    "These recommendations are the best": "",
    "You are the best": "",
    "These lessons are the best": "",
    "The boy is strong": "",
    "The girl is beautiful": "",
    "The book is boring": "",
    "The information is useless": "",
    "full of use - without use": "",
    "These people are rich": "",
    "His uncle is poor": "",
    "I'm 30": "",
    "I'm thirty": "",
    "I'm twenty": "",
    "I'm from Russia": "",
    "I'm Russian": "",
    "I'm a manager": "",
    "My friend is 25": "",
    "He's 25": "",
    "He's from America": "",
    "He's from the United States": "",
    "My friend is from the United States": "",
    "He's American": "",
    "My friend is American": "",
    "He's a designer": "",
    "My friend is a designer": "",
    # Present Simple (negative)
    # I am at home - I am not at home
    "We are inside": "",
    "We are not inside": "",
    "You are right": "",
    "You are not right": "",
    "He is a businessman": "",
    "He is not a businessman": "",
    "She is a manager": "",
    "She is not a manager": "",
    "It is a new car": "",
    "It is not a new car": "",
    "I'm at home": "",
    "I'm not at home": "",
    "I'm at work": "",
    "We're inside": "",
    "We aren't inside": "",
    "We're outside": "",
    "You're right": "",
    "You aren't right": "",
    "You're wrong": "",
    "They're rich": "",
    "They aren't rich": "",
    "They're poor": "",
    "He's a businessman": "",
    "He isn't a businessman": "",
    "He's a manager": "",
    "She's a manager": "",
    "She isn't a manager": "",
    "She's a businessman": "",
    "It isn't a new car": "",
    "It's an old car": "",
    "I'm not": "",
    # I'm not We / you / They aren't
    # He / She / It isn't
    "I'm not married": "",
    "I'm single": "",
    "We aren't friends and we aren't enemies": "",
    "They aren't partners": "",
    "They are only friends": "",
    "They are just friends": "",
    "He isn't hungry": "",
    "He is thirsty": "",
    "She isn't American": "",
    "She's Russian": "",
    "It isn't bad": "",
    "It's very good": "",
    "I'm not hungry": "",
    "I don't want to eat": "",
    "We aren't at home": "",
    "We are in the park": "",
    "You aren't lazy": "",
    "You're hard-working": "",
    "They aren't stupid": "",
    "They aren't silly": "",
    "They're clever": "",
    "They're smart": "",
    "She isn't our teacher": "",
    "She's their teacher": "",
    "He isn't her friend": "",
    "He's our friend": "",
    "It isn't a good idea": "",
    "It's a very bad idea": "",
    "I'm not busy": "",
    "I'm free": "",
    "We aren't students": "",
    "We work": "",
    "You aren't right": "",
    "You're wrong": "",
    "They are together but they aren't married": "",
    "He isn't tall": "",
    "He is short": "",
    "It isn't on the table": "",
    "It's on the chair": "",
    "If I'm not mistaken": "",
    "I think he is right if I'm not mistaken": "",
    "It isn't cold": "",
    "It's warm": "",
    "It isn't good": "",
    "It's bad": "",
    "It isn't interesting": "",
    "It's boring": "",
    "It isn't strange": "",
    "It's normal": "",
    "It's easy": "",
    "It's obvious": "",
    "It isn't difficult": "",
    "It isn't sunny": "",
    "It's cloudy": "",
    "It's rainy": "",
    "It's windy": "",
    "It isn't an interesting job": "",
    "It's a boring job": "",
    "It isn't on the right": "",
    "It's on the left": "",
    "It isn't a good choice": "",
    "It's a bad choice": "",
    # Present Simple to be (negative)
    # I'm not : We / You / They / aren't:
    # He / She / It  isn't
    "The man isn't rich": "",
    "The woman isn't a manager": "",
    "My result isn't so bad": "",
    "Our results aren't brilliant": "",
    "This information isn't so important": "",
    "His flat isn't small": "",
    "These ideas aren't new": "",
    "Their ideas aren't so innovative": "",
    "This thing isn't popular now": "",
    "These things aren't popular now": "",
    "This knowledge isn't basic": "",
    "His life isn't easy": "",
    "Her life isn't very difficult": "",
    "These lessons aren't useless": "",
    "They are very useful": "",
    "My partner isn't afraid of difficulties": "",
    "The car isn't new": "",
    "It's old": "",
    "His lifestyle isn't healthy": "",
    "style of life": "",
    "Her way of life isn't healthy": "",
    "His sister isn't pregnant": "",
    "This job isn't well-paid": "",
    "This place isn't dangerous": "",
    "My friends aren't in Moscow": "",
    "Your money isn't enough": "",
    "Our computer isn't powerful": "",
    "His partners aren't reliable": "",
    "Her boyfriend isn't businessman": "",
    "Their plan isn't so bad": "",
    "This money isn't enough": "",
    "Thar money isn't enough": "",
    "This channel isn't so bad": "",
    "That channel isn't popular": "",
    "These videos aren't so funny": "",
    "Those videos aren't good enough": "",
    "This story isn't long": "",
    "That book isn't short": "",
    "These things aren't so important": "",
    "Those people aren't right": "",
    # Am I: Are we/ you / they : Is he/ she / it?
    "Am I talented?": "",
    "Are we in the right place?": "",
    "Are you in his office?": "",
    "Are they your colleagues?": "",
    "Is he your acquaintance?": "",
    "Is she a housewife?": "",
    "Is it expensive?": "",
    "Am I a good student?": "",
    "Am I wrong?": "",
    "Am I in the wrong place?": "",
    "Are we far from this place?": "",
    "Are we near this place?": "",
    "Are we in one group?": "",
    "Are you really happy?": "",
    "Are you together?": "",
    "Are you in one team?": "",
    "Are they good specialists?": "",
    "Are they experts in this area?": "",
    "Are they experienced?": "",
    "Is he happy?": "",
    "Is he a happy person?": "",
    "Is he married?": "",
    "Is she his wife?": "",
    "Is she afraid of it?": "",
    "Is she a native speaker?": "",
    "Is it a pleasant feeling?": "",
    "Is it effective?": "",
    "IS it an effective method?": "",
    "Is it a popular channel?": "",
    "Is it a strange thing?": "",
    "Is it a global problem?": "",
    "Is it sunny?": "",
    "It is sunny": "",
    "It is windy": "",
    "Is it windy?": "",
    "It is cold": "",
    "Is it cold?": "",
    "Is it a cold day?": "",
    "Is it a warm day?": "",
    "Is he a businessman?": "",
    "Is he a successful businessman?": "",
    "Is he a very successful businessman?": "",
    "Is she an actress?": "",
    "Is she a talented actress?": "",
    "Is she a very talented actress?": "",
    # Am I; Are we/you/they; Is he/she/it?
    "Are these lessons really effective?": "",
    "Is his father rich?": "",
    "Is his mother a businesswoman?": "",
    "Are our friends there?": "",
    "Is this word new for you?": "",
    "Is it school good enough?": "",
    "Is this detail important?": "",
    "Is this hotel so expensive?": "",
    "Is your computer so powerful?": "",
    "Is this thing really necessary?": "",
    "Is his method different?": "",
    "Is this level basic?": "",
    "Is his level high enough?": "",
    "Are all these videos really useful?": "",
    "Is his girlfriend very emotional?": "",
    "Are your ideas similar?": "",
    "Are his ideas the same?": "",
    "Are these methods traditional?": "",
    "Are your parents at home?": "",
    "Is your father a businessman?": "",
    "Is your brother a freelancer?": "",
    "Is your mother a housewife?": "",
    "Is this money enough?": "",
    "Is our knowledge enough?": "",
    "Is the news sad?": "",
    "Is this information reliable?": "",
    "Are the boys busy at the moment?": "",
    "Are the girls with a teacher?": "",
    "Is the boy really so talented?": "",
    "Is the girl the best student?": "",
    "Is the computer expensive?": "",
    "Is the result good enough?": "",
    "Are the results satisfactory?": "",
    "Is the progress slow?": "",
    "Is the lesson very informative?": "",
    "Is the video so funny?": "",
    "Are the boys poor?": "",
    "Are the girls rich?": "",
    # Present Simple to be
    # I'm ; We/You/They're; He/She/It's
    "I'm a sales manager": "",
    "We're in one group": "",
    "You're in one team": "",
    "They're independent": "",
    "He's an outstanding person": "",
    "She's our special guest": "",
    "It's very unusual": "",
    "This thing is strange": "",
    "The result is good enough": "",
    "The results are brilliant": "",
    "The news is shocking": "",
    "knowledge is power": "",
    "This money is enough": "",
    # I'm not; we/you/they aren't ; he/she/isn't
    "I'm not surprised at all": "",
    "We aren't tired of these things": "",
    "You aren't happy": "",
    "They aren't professional workers": "",
    "He isn't available at the moment": "",
    "She isn't afraid of difficulties": "",
    "The boys aren't at school": "",
    "The offer isn't interesting enough": "",
    "sentence": "",
    "Our results aren't good enough": "",
    "This idea isn't new": "",
    "Money isn't everything": "",
    # Am I; Are we/you/they; Is he/she/it?
    "Am I the best student?": "",
    "Are we in the right place?": "",
    "Are you angry?": "",
    "Are they surprised?": "",
    "Is he tall?": "",
    "Is he an experienced lawyer?": "",
    "Is it his idea?": "",
    "Is this singer very popular?": "",
    "Are your colleagues very friendly?": "",
    "Are their ideas the same?": "",
    "Is this hotel good enough?": "",
    "Are these lessons really so effective?": "",
    "Of course, sure , certainly": "",
    "He's my boss": "",
    "They're in the United States": "",
    "We're busy now": "",
    "This thing isn't popular now": "",
    "Is it a good plan?": "",
    "My farther is there": "",
    "They're in Great Britain": "",
    "They're in the  United Kingdom": "",
    "He's a professional teacher": "",
    "It's a good lesson": "",
    "My boss is very busy": "",
    "It's cloudy": "",
    "My friend is 25": "",
    "My friend is 35 years old": "",
    "My relative are in America": "",
    "Are you here?": "",
    "The lesson is boring": "",
    "Are they serious people?": "",
    "It isn't an expensive thing": "",
    "It isn't windy": "",
    "She's a housewife": "",
    "Are they strange people?": "",
    "He isn't an angry person": "",
    "My progress is real": "",
    "I want to speak English naturally": "",
    "She's beautiful": "",
    "You're a good teacher": "",
    "He's a good person": "",
    "It's in my flat": "",
    "Are you together?": "",
    "Her ideas are interesting": "",
    "He's a director": "",
    "The books aren't cheap": "",
    "books aren't cheap": "",
    "Are you there?": "",
    "Is your mother a housewife?": "",
    "Is it a sonny day?": "",
    "Is this thing really so important?": "",
    "Are you in his office?": "",
    "It isn't in America": "",
    "It's in China": "",
    "It's a bad idea": "",
    "It's a interesting offer": "",
    "Is he busy at the moment?": "",
    "He's the best teacher in the world": "",
    "English is easy": "",
    "He's a designer": "",
    "It's an important detail": "",
    "That book isn't short": "",
    "They're from American": "",
    "I'm a manager": "",
    "Their results are brilliant": "",
    "She's tired": "",
    "Is your father a businessman?": "",
    "It's in our country": "",
    "The offer is so interesting": "",
    "Is he wrong?": "",
    "They're talented students": "",
    "This idea is new": "",
    "Is he a talented student?": "",
    "This information is enough": "",
    "Your lesson is very informative": "",
    "Are you a designer?": "",
    "It's an excellent result": "",
    "My results isn't so bad": "",
    "We aren't students": "",
    "It's so interesting": "",
    "You're kind": "",
    "Is the chair comfortable?": "",
    "Is all this money enough?": "",
    "It's on the right": "",
    "These words aren't important": "",
    "My computer is very powerful": "",
    "Is it rainy?": "",
    "The book isn't expensive": "",
    "It's a good exercise": "",
    "Really, it's a good training": "",
    "Is he a popular singer?": "",
    "It isn't an interesting book": "",
    "This idea isn't new": "",
    "These exercises are so useful": "",
    "Their problems arent small": "",
    "Is she an actress?": "",
    "This building is very high": "",
    "It's important": "",
    "I think it's a good result": "",
    "They're students": "",
    "Is it an effective lesson?": "",
    "The key is on the table": "",
    "Is your brother in hospital?": "",
    "I'm not hungry": "",
    "The tickets are cheap": "",
    "I'm not American": "",
    "I'm Russian": "",
    "This exercises isn't difficult": "",
    "These things aren't so important": "",
    "It's so difficult": "",
    "They're in Russia": "",
    "Is your classmate ill?": "",
    "Is it in this area?": "",
    "The book isn't so cheap": "",
    "Is it a strange thing?": "",
    "The hotel is expensive": "",
    "Are they wrong?": "",
    "My boss isn't at work": "",
    "We aren't friends and we aren't enemies": "",
    "It isn't bad": "",
    "It's good": "",
    "Is his mother a businesswoman?": "",
    "His girlfriend isn't here": "",
    "The chair is comfortable": "",
    "They aren't expensive": "",
    "His friend isn't reliable enough": "",
    "My friend is quire reliable": "",
    "They aren't in the park": "",
    "They're in another place": "",
    "Is his method different?": "",
    "That house is old": "",
    "Those videos aren't good enough": "",
    "Is she a native speaker?": "",
    "They aren't stupid": "",
    "They aren't silly": "",
    "They aren't foolish": "",
    "The results aren't good enough": "",
    "It's obvious": "",
    "The boy is talented": "",
    "Is this information reliable?": "",
    "It isn't a new car": "",
    "It's an old car": "",
    "This person is very good": "",
    "Is he a professional teacher?": "",
    "This money isn't enough": "",
    "Are these lessons really effective?": "",
    "The problem is small": "",
    "Are these recommendations so good?": "",
    "His idea is good": "",
    "It's boring": "",
    "Are they right?": "",
    "It isn't boring": "",
    "The offer isn't interesting enough": "",
    "It's on the table": "",
    "Is she a businesswoman?": "",
    "Are they experts in this area?": "",
    "The woman isn't a manager": "",
    "It's a good idea": "",
    "Is she a famous writer?": "",
    "These videos aren't so funny": "",
    "They're good parents": "",
    "Is he very successful?": "",
    "Is it a cold day?": "",
    "Are they rich?": "",
    "Is he a rich person?": "",
    "He isn't our boss": "",
    "They aren't professional workers": "",
    "It isn't a cheap thing": "",
    "Is she your classmate?": "",
    "These ideas aren't new": "",
    "Is he your acquaintance?": "",
    "He's my old friend": "",
    "Are they reliable friends?": "",
    "It's so easy": "",
    "We aren't tired of these things": "",
    "Is she afraid of it?": "",
    "Is it an interesting book?": "",
    "It's easy": "",
    "It's in this city": "",
    "The girl is talented": "",
    "Those people aren't right": "",
    "You're talented": "",
    "I'm Russian": "",
    "You're a good teacher": "",
    "He's a lazy person": "",
    "We're hard-working": "",
    "Is his level high enough?": "",
    "Is he a strange person?": "",
    "This knowledge isn't basic": "",
    "Are you really happy?": "",
    "My bag isn't in my room": "",
    "He's my boyfriend": "",
    "Is he happy?": "",
    "It isn't cold": "",
    "It's warm": "",
    "I'm not tired": "",
    "Are the girls rich?": "",
    "Is the news sad?": "",
    "The problem isn't big": "",
    "Is the result good enough?": "",
    "Everyone knows it": "",
    "They're clever": "",
    "They're smart": "",
    "You're the best teacher": "",
    "It isn't strange": "",
    "Is she a talented actress?": "",
    "His progress isn't big": "",
    "The chair isn't so comfortable": "",
    "Our computer isn't powerful": "",
    "His lifestyle isn't healthy": "",
    "Are our friends there?": "",
    "Is he a talented actor?": "",
    "I'm in the park": "",
    "She isn't my girlfriend": "",
    "Is she a housewife?": "",
    "He's Russian": "",
    "These things aren't good enough": "",
    "It's a long story": "",
    "She's Russian": "",
    "He's American but he lives in Russia": "",
    "Is it a cheap thing?": "",
    "Are our relatives in America?": "",
    "It isn't a boring lesson": "",
    "Your lessons aren't boring at all": "",
    "They aren't rich": "",
    "They're poor": "",
    "I'm right": "",
    "I'm not right": "",
    "Am I right?": "",
    "We're sure": "",
    "We're certain": "",
    "We aren't sure": "",
    "Are we sure?": "",
    "You're near the park": "",
    "You aren't near the park": "",
    "Are you near the park?": "",
    "They're in a safe place": "",
    "They aren't in a safe place": "",
    "Are they in a safe place?": "",
    "He's an expert in this area": "",
    "He isn't an expert in this area": "",
    "Is he an expert in this area?": "",
    "She's a native speaker": "",
    "She isn't a native speaker": "",
    "Is she a native speaker?": "",
    "It's the best decision": "",
    "It isn't the best decision": "",
    "Is it the best decision?": "",
    "The rule is very important": "",
    "The rule isn't very important": "",
    "Is the rule very important?": "",
    "The phrases are very common": "",
    "The phrases aren't very common": "",
    "Are the phrases very common?": "",
    "His English is fluent": "",
    "His English isn't fluent": "",
    "Is his English fluent?": "",
    "The news is strange": "",
    "The news isn't strange": "",
    "Is the news strange?": "",
    "Our knowledge is enough": "",
    "Our knowledge isn't enough": "",
    "Is our knowledge enough?": "",
    "His sister is 17(seventeen)": "",
    "His sister isn't 17": "",
    "Is his sister 17?": "",
    "His friend is married": "",
    "His friend isn't married": "",
    "Is his friend married?": "",
    "This idea isn't new": "",
    "It's an old idea": "",
    "My mother is a doctor": "",
    "Is it very important?": "",
    "Your lessons are really good": "",
    "Her lifestyle isn't healthy": "",
    "Her way of life isn't healthy": "",
    "He's my father": "",
    "This information is useless": "",
    "It isn't difficult": "",
    "It isn't hard": "",
    "The book is in the kitchen": "",
    "The book is boring": "",
    "These things aren't popular now": "",
    "It's my new car": "",
    "Is your computer powerful?": "",
    "Are they your colleagues?": "",
    "I'm in my room": "",
    "Am I a good student?": "",
    "My friends aren't in Moscow": "",
    "Is the video really useful?": "",
    "My parents aren't in the park": "",
    "Is it a cheap thing?": "",
    "My mother is in the bathroom": "",
    "Are they managers?": "",
    "Is it a new project?": "",
    "It isn't a bad idea": "",
    "My best friend is businessman": "",
    "The story isn't long": "",
    "Is this girl the best student?": "",
    "That money isn't enough": "",
    "Are your ideas similar?": "",
    "That exercises is too easy": "",
    "Is this word new for you": "",
    "Is her boyfriend Russian?": "",
    "Is it windy?": "",
    "It snows": "",
    "It rains": "",
    "It's snowy": "",
    "It's rainy": "",
    "This house is new": "",
    "This place isn't dangerous": "",
    "Is this school good enough?": "",
    "Are all these videos really useful?": "",
    "Is it easy or difficult?": "",
    "His life isn't easy": "",
    "Is he reliable enough?": "",
    "His son is lazy": "",
    "He's American": "",
    "Those exercises are useless": "",
    "I'm nor from Canada": "",
    "I'm from the United States": "",
    "Are they very good workers?": "",
    "It's on the chair": "",
    "Is it a powerful computer?": "",
    "My partner isn't afraid of difficulties": "",
    "Is your wife at home?": "",
    "It's a small mistake": "",
    "Is the ticket expensive?": "",
    "Is his father rich?": "",
    "She's his daughter": "",
    "Is it interesting or boring?": "",
    "We are inside": "",
    "The book is red": "",
    "Is she a teacher?": "",
    "This room is small": "",
    "Is she a famous actress or not?": "",
    "She's 25": "",
    "is the video so funny?": "",
    "The girl is beautiful": "",
    "You aren't happy": "",
    "These results are wonderful": "",
    "These results are brilliant": "",
    "These results are excellent": "",
    "These results are amazing": "",
    "These results are surprising": "",
    "These results are unexpected": "",
    "Are his ideas the same?": "",
    "Is it sunny?": "",
    "Is it rainy?": "",
    "He isn't at school": "",
    "Is he a hard-working person?": "",
    "It isn't a boring movie": "",
    "Is your husband at work?": "",
    "It's a good idea": "",
    "He isn't a businessman": "",
    "He's a manager": "",
    "Are they experienced?": "",
    "We're in the park now": "",
    "Is he a businessman or an employee?": "",
    "Are all these houses new?": "",
    "Is our boss very busy now?": "",
    "I'm tired": "",
    "It's a difficult thing": "",
    "You aren't right": "",
    "You're wrong": "",
    "These results are terrible": "",
    "I'm not surprised at all": "",
    "Their plan isn't so bad": "",
    "Her daughter is very hard-working": "",
    "Is he a happy person": "",
    "It isn't far": "",
    "Is his son lazy?": "",
    "Is it an innovative idea?": "",
    "Our results aren't good enough": "",
    "The result isn't good enough": "",
    "The boys aren't at school": "",
    "They aren't partners": "",
    "They are only friends": "",
    "Is this lesson very informative?": "",
    "We aren't classmates": "",
    "This idea is quite old": "",
    "Money isn't everything": "",
    "She's in America": "",
    "His flat is quite small": "",
    "He isn't rich": "",
    "Is this level basic?": "",
    "It isn't sunny": "",
    "This job isn't well-paid": "",
    "Is he your best friend?": "",
    "Is your cousin at the airport?": "",
    "I think our results aren't good enough": "",
    "Are the results satisfactory?": "",
    "These students are so talented": "",
    "It isn't free": "",
    "You need to pay": "",
    "His partners aren't reliable": "",
    "Are they just friends?": "",
    "She thinks her result isn't good enough": "",
    "It's an easy exam": "",
    "It isn't the best choice": "",
    "The test in this book aren't easy": "",
    "It's a short phrase": "",
    "I'm sure all these lessons are very useful": "",
    "Is he your boss?": "",
    "It's on the left": "",
    "It's his old car": "",
    "Is your brother a professional sportsman?": "",
    "The manager is very strange": "",
    "We aren't at home": "",
    "We're in the park": "",
    "Are we in the right place?": "",
    "Are your parents at home?": "",
    "It's too long": "",
    "It's an interesting thing": "",
    "Are they professional workers?": "",
    "Is it cloudy?": "",
    "I'm not at home": "",
    "I'm at work": "",
    "Is she your acquaintance?": "",
    "Are they good specialists?": "",
    "She's a manager": "",
    "Is it effective?": "",
    "It's really difficult": "",
    "It's a big mistake": "",
    "My sister is in bad": "",
    "It's too short": "",
    "All those houses are old": "",
}