slovar = {
    "i speak English": "говорить по английски ",
    "i speak Russian": "я говорю по русский ",
    "i understand": "я понимаю",
    "i understand you": "я понимаю тебя ",
    "i understand you very well": "я понимаю тебя очень хорошо ",
    "i know English": "я знаю по английски ",
    "i know it": "я знаю это",
    "i work": "я работаю",
    "i work there": "я работаю там",
    "i study": "я учусь ",
    "i study at school": "я учусь в школе ",
    "i study university": "я учусь в университете",
    "i study there": "я учусь там",
    "i read": "я читаю",
    "i read books": "я читаю книги",
    "i read English books": "я читаю английский книги",
    "i live in Russia": "я живу в России",
    "i want it ": "я хочу это",
    "i want it": "я хочу это ",
    "i play": "я играю",
    "i play football": "я играю футбол ",
    "i do it well": "я делаю это хорошо ",
    "i have a car": "у меня есть машина",
    "i have a house": "у меня есть дом",
    "i like english": "мне нравится английский ",
    "i like it": "мне нравится это",
    "i live in Moscow": "я живу в Москве ",
    "we speak English": "мы говорим по английски ",
    "you understand": "ты понимаешь ",
    "they read English books": "они читают английские книги",
    "i know english": "я знаю английский ",
    "we want it": "мы хотим это",
    "you know it": "ты знаешь это",
    "they have a house": "у них есть дом",
    "l like it": "мне нравится ",
    "we like it": "нам это нравится ",
    "you like it": "тебе это нравится ",
    "they like it": "им нравится это ",
    # present simple i/we/you/they     he/she/it глагол + s
    "he works": "он работает ",
    "she speaks English": "она говорить по английски ",
    "it helps me": "это помогает мне",
    "it helps you": "это помогает тебе ",
    "it really helps": "это реально помогает",
    "he lives in london": "он живет в Лондоне",
    "he works hard": "он работает усердно",
    "he works very hard": "он работает очень усердно ",
    "she works a lot": "она работает много ",
    "he plays computer games": "он играет компьютерные игры ",
    "she likes it": "ей нравится это ",
    "he likes it": "ему нравится это",
    "she likes this lesson": "ей нравится этот урок",
    "she likes these lessons": "ей нравится эти уроки",
    "i like this lesson": "мне нравится этот урок ",
    "i like your lessons": "мне нравится твои уроки",
    "i like these lessons": "мне нравится эти уроки",
    "i really like it": "мне действительно нравится это",
    "i really like these lessons": "мне действительно нравится эти уроки",
    "he swims very well": "он плавает очень хорошо",
    "she understands this lesson": "она понимает этот урок",
    "he remembers it": "он помнить это",
    "it works well": "это работает хорошо",
    "she speaks Spanish": "она говорить по испанский",
    "i speak English fluently": "я говорю по английски свободно",
    "he speaks English fluently": "он говорит по английски свободно",
    "he wants it": "он хочет это",
    "she sees it": "она видеть это",
    "she understands you": "она понимает тебя ",
    "it seems interesting": "это кажется интересным",
    "she eats meat": "она есть мясо ",
    "he eats fish": "он есть рыбу",
    "it happens": "это случается",
    "he plays tennis": "он играет в теннис ",
    "she plays different games": "она играет в различные игры",
    "he plays the guitar": "он играет на гитаре",
    "i get up early": "я встаю рано",
    "she gets up early": "она встаёт рано",
    "i get up late": "я встаю поздно",
    "he gets up late": "он встаёт поздно",
    "i get up very early": "я встаю очень рано",
    "he gets up very late": "он встаёт очень поздно ",
    "they read": "они читают",
    "you know English well": "ты знаешь английский хорошо ",
    "we understand you very well": "мы понимаем тебя очень хорошо",
    "you speak Russian": "ты говоришь по русский",
    "i have a flat": "у меня есть квартира",
    "we know English very well": "мы знаем английский очень хорошо ",
    "they know it": "они знает это",
    "they have an apple": "они имеет яблоко",
    "they work": "они работают",
    "they have a car": "у них есть машина",
    "i know English well": "я знаю английский хорошо ",
    "they speak English": "они говорят по английски ",
    "we study at school": "мы учимся в школе",
    "you study at school": "ты учишься в школе",
    "we work there": "мы работаем там",
    "we work": "мы работаем",
    "they know English very well": "они знают английский очень хорошо ",
    "i study at university": "я учусь в университете",
    "you have a house": "у тебя есть дом",
    "they live in Moscow": "они живут в Москве",
    "we play": "мы играем",
    "we understand": "мы понимаем",
    "you have a car": "у тебя есть машина",
    "they study there": "они учиться там ",
    "we live in Russia": "мы живем в России ",
    "you play football": "ты играешь футбол",
    "they do it well": "они делают это хорошо",
    "they study": "они изучает",
    "i like English": "мне нравится английский ",
    "we understand you": "мы понимаем тебя ",
    "we play football": "мы играем футбол",
    " they speak Russian": "они говорят по русский ",
    "you work there": "ты работаешь там",
    "we like English": "нам нравится английский ",
    "we read books": "мы читаем книги ",
    "we have a car": "у нас есть машина",
    "they study at university": "они учится в университете ",
    "they study at school": "они учиться в школе ",
    "they want it": "они хотят это",
    "we do it well": "мы делаем это хорошо ",
    "we know it": "мы знаем это",
    "they understand": "они понимают",
    "you study at university": "ты учишься в университете ",
    "i have a care": "у меня есть машина",
    "we have a house": "у нас есть дом",
    "they play": "они играют",
    "we study": "мы учимся",
    "we study there": "мы учимся там",
    "they understand you": "они понимает тебя ",
    "i know English very well": "я знаю английский очень хорошо ",
    "you speak English": "ты говоришь по английски ",
    "they work there": "они работают там ",
    "we read": "мы читаем ",
    "you read": "ты читаешь ",
    "they know English well": "они знают английский хорошо ",
    "you know English": "ты знаешь английский ",
    "you study": "ты учишься ",
    "you want it": "ты хочешь это",
    "we speak Russian": "мы говорим по русский ",
    "we know English well": "мы знаем английский хорошо ",
    "you read books": "ты читаешь книги ",
    "they read books": "они читают книги",
    "you do it well": "ты делаешь это хорошо ",
    "we live in Moscow": "мы живем в Москве ",
    "they know English": "они знают английский ",
    "they play football": "они играют футбол",
    "they understand you very well": "они понимает тебя очень хорошо ",
    "they like English": "им нравится английский ",
    "you live in Moscow": "ты живёшь в Москве ",
    "you work": "ты работаешь ",
    "you like English": "тебе нравится английский ",
    "ypu know English very well": "ты знаешь английский очень хорошо ",
    "he reads English books": "он читает английские книги",
    "she really likes it": "ей реально нравится это",
    "she remembers it": "она помнить это",
    "she reads English books": "она читает английские книги",
    "he understands you": "он понимает тебя",
    "she works well": "она работает хорошо ",
    "she works there": "она работает там",
    "he speaks Russian": "он говорит по русский ",
    "he works well": "он работает хорошо ",
    "she gets up late": "она встаёт поздно ",
    "he sees it": "он видит это",
    "he helps you": "он помогает тебе",
    "he plays": "он играет",
    "he really likes it": "ему реально это нравится ",
    "really, i like it ": "действительно мне это нравится ",
    "really, he likes it": "действительно ему это нравится ",
    "he plays different games": "он играет в различные игры",
    "he lives in Russia": "он живет а России",
    "he understands you very well": "он понимает тебя очень хорошо ",
    "she speaks Russian": "она говорить по русский ",
    "she likes English": "ей нравится английский ",
    "he knows English very well": "он знает английский очень хорошо ",
    "she understands you very well": "она понимает тебя очень хорошо ",
    "he knows English": "он знает английский ",
    "he knows English well": "он знает английский хорошо ",
    "he lives in Moscow": "он живет в Москве ",
    "he eats meat": "он есть мясо",
    "she helps me": "она помогает мне",
    "she knows English well": "она знает английский хорошо ",
    "she works very hard": "она работает очень усердно",
    "she understands": "она понимает",
    "she knows it": "она знает это",
    "he works a lot": "он работает много",
    "he works too much": "он работает слишком много ",
    "he gets up early": "он встаёт рано",
    "he speaks English": "он говорить по английски ",
    "he understands": "он понимает",
    "she plays tennis": "она играет в теннис ",
    "she knows English": "она знает английский ",
    "she reads books": "она читает книги ",
    "he knows it": "он знает это",
    "she lives in Russia": "она живет в России ",
    "he likes English": "ему нравится английский ",
    "he helps me": "он помогает мне",
    "she eats fish": "она есть рыбу",
    "he works there": "он работает там",
    "she reads": "она читает",
    "he reads books": "он читает книги",
    "she gets up very early": "она встаёт очень рано",
    "she swims very well": "она плавает очень хорошо ",
    "he speaks fluently": "он говорить свободно",
    "he likes these lessons": "ему нравится эти уроки",
    "he speaks Spanish": "он говорить по испанский",
    "she works hard": "она работает усердно",
    "she speaks English fluently": "она говорит по английски свободно",
    "she plays": "она играет",
    "she lives in london": "она живет в Лондоне ",
    "he reads": "он читает ",
    "she knows English very well": "она знает английский очень хорошо ",
    "she helps you": "она помогает тебе",
    "she plays computer games": "она играет компьютерные игры ",
    "he gets up very early": "он встаёт очень рано",
    "he speaks Spanish fluently": "он говорить по испанский свободно ",
    "she speaks Spanish very well": "она говорить по испанский очень хорошо ",
    "she lives in Moscow": "она живет в Москве ",
    # i / we / you / they + глагол
    "we know it very well": "мы знаем это очень хорошо ",
    "you understand me": "ты понимаешь меня",
    "they live in English": "они живут в Англии ",
    # he she it глагол + s
    "it really helps me": "это реально помогает мне",
    # o - es; go
    "i go": "я иду ",
    "she goes": "она идёт",
    "she goes there": "она идёт туда",
    "she does it well": "она делает это хорошо ",
    "i do housework": "я делаю уборку дома",
    "she does housework": "она делает домашние дела",
    "i go to work": "я хожу на работу ",
    "he goes to work": "он ходит на работу ",
    "she goes to work": "она ходит на работу",
    "i go to school": "я хожу в школу",
    "he goes to school": "он ходить в школу",
    "she goes to school": "она ходит в школу",
    "i go to the park": "я хожу в парк",
    "he goes to the park": "он ходить в парк",
    "she goes to the park": "она ходит в парк",
    "i go to the cinema": "я хожу в кино",
    "i go to the theatre": "я хожу в театр",
    "he goes to the cinema": "он ходить в кино",
    "she goes to the cinema": "она ходить в кино",
    "he goes to the theatre": "он ходить в театр ",
    "she goes to the theatre": "она ходит в театр ",
    "i often go there": "я часто туда хожу",
    "i often do it": "я часто это делаю",
    "he often goes there": "он часто ходит туда",
    "she often does it": "она часто это делает",
    # ch, sh, x,  + es
    "i teach English": "я преподаю английский ",
    "she teaches English": "она преподаёт английский ",
    "i watch tv": "я смотрю тв",
    "he watches tv": "он смотрит тв ",
    "i watch tv every day": "я смотрю тв каждый день",
    "he watches tv every day": "он смотрит тв каждый день",
    "i wash up the dishes": "я мою посуду ",
    "she washes up the dishes": "она моет посуду ",
    "i usually relax in the evening": "я обычно отдыхая вечером",
    "she usually relaxes in the evening": "она обычно отдыхает вечером",
    # гласная + y + s
    "we play computer games": "мы играем компьютерные игры ",
    # согласная + y + ies
    "i often fly to America": "я часто летаю в Америку ",
    "he often flies to America": "он часто летает в Америку ",
    "she often flies to England": "она часто летает в Лондон ",
    "i often fly to the United States": "я часто летаю Штаты ",
    "i often go to China": "я часто езжу в Китай ",
    "he often flies to the United States": "он часто летает в Штаты ",
    "she often goes to China": "она часто ездит в Китай ",
    "he often cries": "он часто плачет",
    #   rule double
    "she tries to do it": "она старается делать это",
    "he tries to help him": "он старается помочь ему",
    "i try to learn English": "я пытаюсь учить английский ",
    "he tries to learn Spanish": "он пытается выучить испанский ",
    # i / we / you / they have
    # he she it has
    "he has a car": "у него есть машина",
    "i have a computer": "у меня есть компьютер ",
    "i have many friends": "у меня много друзей ",
    "she has a flat": "у неё есть квартира ",
    "i have a job": "у меня есть работа ",
    "he has a girlfriend": "у него есть девушка ",
    "she pays computer games": "она играет компьютерные игры ",
    "he often ties to do ti": "он часто пытается сделать это",
    "he does it well": "он делает это хорошо ",
    "he works herd": "он работает усердно",
    "he often goes to Chine": "он часто ездит в Китай ",
    "he has a lot of fiends": "у него много друзей 2",
    "he has lots of friends": "у него много друзей 3",
    "she ties learn Spanish": "она пытается учить испанский ",
    "she tries to help him": "она пытается помочь ему",
    "he teaches English": "он преподаёт английский ",
    "he tries to do it": "он пытается сделать это",
    "he relaxes in the evening": "он отдыхает вечером",
    "he has a rest": "он отдыхает",
    "she has a car": "у неё есть машина",
    "he often flies to England": "он часто летает в Англию ",
    "he has a friend": "у него есть друг",
    "she has many friends": "у неё есть много друзей ",
    "she has a lot of friends": "у неё есть много друзей 2",
    "she has lots of friends": "у неё есть много друзей 3",
    "he often does it": "он часто делает это",
    "she studies at school": "она учится в школе",
    "he tries to learn English": "он пытается выучить английский ",
    "he studies at school": "он учится в школе ",
    "she relaxes in the evening": "она отдыхает вечером",
    "she has a rest the evening": "она отдыхает вечером 2",
    "she watches tv very day": "она смотрит тв каждый день ",
    "she plays football": "она играет футбол ",
    "she tries to learn English": "она пытается выучить английский ",
    "he usually relaxes in the evening": "он обычно отдыхает вечером",
    "she usually relaxes in the morning": "она обычно отдыхает утром",
    "she usually has a rest in the morning": "она обычно отдыхает утром 2",
    "he has a computer": "у него есть компьютер ",
    "she has a house": "у неё есть дом",
    "he plays football": "он играет футбол",
    "she watches tv in the morning": "она смотреть тв утром ",
    "he watches tv in the evening": "он смотреть тв вечером",
    "he washes up the dishes": "он моет посуду",
    "he has a job": "у него есть работа ",
    "she often flies to America": "она часто летает в Америку ",
    "she has a friend": "у неё есть друг",
    "she studies at university": "она учится в университете ",
    "he studies at university": "он учится в университете ",
    "she ties to help him": "она пытается помочь ему ",
    "she often goes there": "она часто туда ходить ",
    # i /we / you they  + гл
    # he/ she /it + гл + s
    "this lesson helps me(it)": "",
    "these lessons help me(they)": "",
    "my sister lives in Russia(she)": "",
    "it costs 20(twenty) pounds": "",
    "it is 20 pounds": "",
    "this dress costs 50 (fifty) dollars(it)": "",
    "this dress is 50 dollars": "",
    "my friend often sees him": "",
    "my teacher know English very well": "",
    "my best friend plays basketball (he)": "",
    "my brother lives in this house (he)": "",
    "my sister lives in that house (she)": "",
    "your idea seems interesting (it)": "",
    "she likes this idea": "",
    "Kate likes this idea": "",
    "Max lives in this  city": "",
    "i often listen to music": "",
    "my sister often listens to music (she)": "",
    "my father has a job (he)": "",
    "my mather has a car (she)": "",
    "my sister goes to school (she)": "",
    "my brother go to work (he)": "",
    "our teacher knows English very well": "",
    "i also think so": "",
    "i think so, too": "",
    "our father also thinks so": "",
    "our father thinks so, too": "",
    "their teacher says it": "",
    # i - my
    "i have a brother": "",
    "my brother goes to school": "",
    # we - our
    "we have an uncle": "",
    "our uncle speaks English fluently": "",\
    # you - your
    "your house looks beautiful": "",
    # they - their
    "their teacher says so": "",
    # he - his
    "his parents work there": "",
    "his mother teaches french": "",
    # she - her
    "her father do business": "",
    "her father does business": "",
    "i know it very well": "",
    "i can speak English": "",
    "i like this place": "",
    "we live in this city": "",
    "you speak English very well": "",
    "i really want it": "",
    "i really understand this lesson": "",
    "i see it very well": "",
    "you really help me": "",
    "i sometimes think about it ": "",
    "i think so": "",
    "these lessons help me": "",
    "my father goes to work": "",
    "my uncle works very hard": "",
    "me sister lives in this house": "",
    "his sister goes to school": "",
    "my brother often plays basketball": "",
    "my parents work very hard": "",
    "my sister gets up late": "",
    "my friend tries to help my brother": "",
    "this house costs a lot": "",
    "my sister has a boyfriend": "",
    "your brother plays computer games": "",
    "our parents really like these lessons": "",
    "my friend likes this house": "",
    "that flat costs a lot": "",
    "my father speaks English fluently": "",
    "your brother often relaxes": "",
    "your brother often has a rest": "",
    "my uncle often goes to China": "",
    "their mother has a car": "",
    "his brother goes to school": "",
    "this lesson helps me": "",
    "my mother has a job": "",
    "your father knows it very well": "",
    "my sister tries to learn spanish": "",
    "my boyfriend often listens to music": "",
    "my brother lives in that house": "",
    "her parents work there": "",
    "my best friend lives in this city": "",
    "your sister has a computer": "",
    "this dress costs 20 dollars": "",
    "my mother understands it very well": "",
    "my mother does housework": "",
    "their mother often flies the united states": "",
    "this flat costs a lot": "",
    "my teacher does it well": "",
    "it costs 50 pounds": "",
    "my best friend lives in Moscow": "",
    "my best friend really likes it": "",
    "i have an uncle": "",
    "my brother studies at university": "",
    "my girlfriend often listens to music": "",
    "my friend plays football very well": "",
    "my teacher thinks so": "",
    "my brother has many friends": "",
    "my father likes this idea": "",
    "my brother has a girlfriend": "",
    "their parents have a house": "",
    # go home /be home /stay home /come home
    "my father does business": "",
    "my sister studies at school": "",
    "your idea seems interesting": "",
    "my friend often sees her": "",
    "my father has a job": "",
    "her brother goes to work": "",
    "my sister lives in Russia": "",
    "my brother goes to work": "",
    "my friend often tries to do it": "",
    "their uncle often watches tv": "",
    "her mother teaches English": "",
    "my brother works in England": "",
    "their house looks very beautiful": "",
    "her sister goes to work": "",
    "your friend often goes there": "",
    "my sister goes to school": "",
    "that house costs it a lot": "",
    "my mother often says it": "",
    "my uncle lives in America": "",
    "my best friend plays different games": "",
    "your lesson helps me": "",
    "my friend knows English very well": "",
    "your parents often go to the park": "",
    "my brother really likes it": "",
    "your brother swims very well": "",
    "my mother likes this idea": "",
    "my parents know it": "",
    # 5
    # i / we / you / they + г
    # he / she  / it + г + s
    # o + es / ch,sh,x + es
    # i go to work ----she goes to work /   i do it very well ----- he does it very well
    # i often watches tv / she washes up the dishes/ he often relaxes in the evening/ he often has a rest in the evening
    # my father works there/ my sister knows it very well/ their parents live there /this lesson seems interesting
    # these lessons seem very interesting
    # it seems interesting / i work a lot / she works very hard / he lives in this house/ she lives in that house
    # my friend speaks English fluently / i like it / he likes it / she likes it / he likes it / they like it
    # he really likes it/ i often go to the park / my sister has many friends
    "this dress costs 20 pounds": "",
    "this dress is 20 pounds": "",
    "she often flies to the united states": "",
    "my brother often plays computer games": "",
    "my brother likes different computer games": "",
    "i want this dress": "",
    "i want to buy this dress": "",
    "i want this thing": "",
    "i want to buy this thing": "",
    "i want to order it": "",
    "i want to buy a house": "",
    "i want to know English really well": "",
    "i want to speak English very well": "",
    "i want to speak English fluently": "",
    "i want to eat": "",
    "i want to drink": "",
    "i want to eat meat": "",
    "i want to eat fish": "",
    "i want to drink tea": "",
    "i want to drink coffee": "",
    "i want to drink a cup of tea": "",
    "i want to drink a cup of coffee": "",
    "i want to learn English": "",
    "i want to go to America next month": "",
    "i want to go to Italy next year": "",
    "i want to read this book": "",
    "i want to call her": "",
    "i want to call him": "",
    "i want to call them": "",
    "they want to call me": "",
    "they want to call us": "",
    "i want to visit this place": "",
    "i want to get more money": "",
    "i want to live in another country": "",
    "i want to live abroad": "",
    "i want to study in the united states": "",
    "i want to have my own business": "",
    "i want to watch this video": "",
    "i want to watch your channel every day": "",
    "i want to go to the cinema": "",
    "i want to learn English with you": "",
    "my boss wants more money": "",
    "my brother wants to study in another place": "",
    "my aunt wants to sell her house": "",
    "my uncle wants to sell his flat": "",
    "her relative wants to rent a flat": "",
    "his secretary wants a new job": "",
    "his secretary wants to find a new job": "",
    "hi wants to know everything": "",
    "she wants to know all the information": "",
    # a/an + при + сущ
    "i want to help you": "",
    "i want to thank you": "",
    "thank": "",
    "thank you": "",
    "thank you very much": "",
    "thanks a lot": "",
    "i also want to thank you": "",
    # 6_2
    "i want to play computer games": "",
    "i want to have a car": "",
    "i eat meat": "",
    "i want tea": "",
    "my aunt wants to sell her flat": "",
    "my friend wants to study in another place": "",
    "i want to visit that place": "",
    "i want to drink tea": "",
    "i want to drink coffee": "",
    "i want to order it": "",
    "i want to eat meat": "",
    "i want to call them": "",
    "we want to play football": "",
    "i want to watch this video": "",
    "i want to live abroad": "",
    "i  want to have my own business": "",
    "my brother wants to try to do it": "",
    "he wants to know everything": "",
    "i want to eat": "",
    "my relative wants to play this game": "",
    "i want to read this book": "",
    "my aunt wants to sell her house": "",
    "i want to play this computer game": "",
    "i want to call him": "",
    "i want to buy a house": "",
    "i want to fly to New York": "",
    "his secretary wants to find a new  job": "",
    "my boss wants to know everything": "",
    "i want to know English": "",
    "i want coffee": "",
    "i want to go to America next month": "",
    "i want to go to the cinema": "",
    "my sister wants to buy this dress": "",
    "it often happens": "",
    "i want to help you": "",
    "she wants to know all the information": "",
    "i want to get more money": "",
    "i want to drink": "",
    "we want to thank you": "",
    "i want a cup of tea": "",
    "i want to learn English": "",
    "they want to call me ": "",
    "we want to know all the information": "",
    "i want to speak English fluently": "",
    "i want to watch your channel every day": "",
    "i want to go to Italy next year": "",
    "her relative wants to rent a flat": "",
    "my sister wants to play different games": "",
    "i want to buy this beautiful dress": "",
    "i want to study there": "",
    "we want to learn English here": "",
    "my sister wants to teach English": "",
    "i want a cup of coffee": "",
    "i want to live in another country": "",
    "i want to ses it": "",
    "i want to buy this thing": "",
    "i want to help my friend": "",
    "my relative wants to study abroad": "",
    "they want to help me": "",
    "i really want to thank you": "",
    "my friend, i really want to thank you": "",
    "i want to learn English": "",
    "i want to order it": "",
    # would like to + г
    "i would like to learn English": "",
    "i would like to order it": "",
    "i'd like to learn English": "",
    "i'd like to order it": "",
    "i'd like to do it now": "",
    "i'd like to do right now": "",
    "i'd like to talk about it": "",
    "i'd like to speak about it": "",
    "i'd like to talk about that": "",
    "i'd like to talk about this problem": "",
    "i'd like to know it": "",
    "i'd like to do it again": "",
    "i'd like to do it one more time": "",
    "i'd like to buy a new computer": "",
    "i'd like to read a book in English": "",
    "i'd like to write it down": "",
    "i'd like to listen to music": "",
    "i'd like to listen to this song": "",
    "i'd like to go to the party": "",
    "i'd like to go to this party": "",
    "i'd like to go to the restaurant": "",
    "i'd like to go to this restaurant": "",
    "i'd like to tell you everything": "",
    "i'd like to say it": "",
    "i'd like to know all the news": "",
    "i'd like to tell you all the information": "",
    "i'd like to hear this story": "",
    "i'd like to hear all the story": "",
    "i'd like to translate this word": "",
    "i'd like to translate this phrase": "",
    "i'd like to translate this sentence": "",
    "i'd like to work more": "",
    "i'd like to work less": "",
    "i'd like to work more to get more money": "",
    "i'd like to work more to earn more money": "",
    "i'd like to work less to have more free time": "",
    "i'd like to understand English speech": "",
    "i'd like to understand native speakers": "",
    "i'd like to be a teacher": "",
    "i'd like to become a teacher": "",
    "i'd like to be a manager": "",
    "i'd like to become a manager": "",
    "i'd like to be a businessman": "",
    "i'd like to become a businessman": "",
    "i'd like to have my own business": "",
    "i'd like to have my own YouTube channel": "",
    "we'd like to invite you to the party": "",
    "they'd like to join us": "",
    "you'd like to live here": "",
    "i see you'd like to live here": "",
    "he'd like to get this job": "",
    "she'd like to learn English in this place": "",
    "i'd like to thank you": "",
    "i really want to thank you": "",
    "i'd really like to thank you for your help": "",
    "i'd really like to thank you for support": "",
    "i'd really like to thank you for everything": "",
    "very good words": "",
    "my aunt would like to sell her house": "",
    "i'd like to know it right now": "",
    "i'd like to have more free time": "",
    "my relative would like to sell his flat": "",
    # his flat /her flat /their flat /our flat
    "my brother would like to play this game": "",
    "i'd like this dress": "",
    "i'd like to buy this dress": "",
    "i'd like to help my friend": "",
    "i'd like to do it one more time": "",
    "i'd like to do it again": "",
    "i'd like to see it": "",
    "i'd like to thank you": "",
    "i'd like to learn English very hard": "",
    "i'd like to talk about it with you": "",
    "i'd like to talk with you about it": "",
    "i'd like to talk to yoy about it": "",
    "i'd like to speak with you about it": "",
    "i'd like to go to Italy next year": "",
    "i'd like to live abroad": "",
    "i'd like to listen to this song": "",
    "i'd like to hear this story": "",
    "i'd like to read this book": "",
    "i'd like to buy a house": "",
    "i'd like to know English very well": "",
    "i'd like to buy this thing": "",
    "i'd like to work less": "",
    "they'd like to call us": "",
    "i'd like to go to this restaurant": "",
    "my friend would like to study in another place": "",
    "my sister would like to teach English": "",
    "i'd like to study there": "",
    "i'd like to listen to music": "",
    "i'd like to hear all the story": "",
    "i'd like to learn English here": "",
    "next": "",
    "he'd like to get this job": "",
    "his secretary would like to get a new job": "",
    "i'd like to call them": "",
    "i'd like to know all the news": "",
    "i'd like to translate this phrase": "",
    "i'd like to go to America next month": "",
    "i'd like to buy this beautiful dress": "",
    "i'd like to get more money": "",
    "i'd like to have a car": "",
    "we'd like to play football": "",
    "i'd like to a cup of coffee": "",
    "i'd like to speak English fluently": "",
    "i'd like to watch this video": "",
    "i'd like to read a book in English": "",
    "i'd like to live in another country": "",
    "i see": "",
    "i understand": "",
    "i'd really like to thank you": "",
    "i'd like to tell you all everything": "",
    "i'd like to translate this word": "",
    "my brother would like try to do it": "",
    "i'd like to work more": "",
    "i'd like to call her": "",
    "i'd like to thank you for your help": "",
    "i'd like to thank you for support": "",
    "i'd like to thank you everything": "",
    "i'd like to visit this place": "",
    "i'd like to visit that place": "",
    "i'd like to visit these places": "",
    "i'd like to speak English very well": "",
    "we'd like to go the party": "",
    "i'd like to fly to New York": "",
    "i'd like to eat meat": "",
    "my sister would like to buy this dress": "",
    "i'd like to drink a cup of tea": "",
    "i'd like to drink a cup of coffee": "",
    "my boss would like to know everything": "",
    "i'd like to write it down": "",
    "i'd like to buy a new computer": "",
    "i'd like to work more to get more money": "",
    "i'd like to work more to earn more money": "",
    "my relative would like to study abroad": "",
    "she'd like to study English here": "",
    "she'd like to study English in this place": "",
    "they'd like to study in the united states": "",
    "i'd like to talk to you about this problem": "",
    "our relative wants to rent a flat": "",
    "i'd like to drink a cup of tea": "",
    "i'd like to drink a cup of coffee": "",
    "i'd like to drink a glass of juice": "",
    "i'd like to drink a glass of water": "",
    "i'd like to translate these sentences": "",
    "i'd like to translate this text": "",
    "i'd like to have my own business": "",
    "i'd like to say it": "",
    "i'd like to watch your channel every day": "",
    "we'd liker to order it right now": "",
    "i'd like to eat fish": "",
    "he would like to know everything": "",
    # 8
    # present simple
    # i / we / you/ they don't + г
    # he / she it doesn't + г
    "i watch this channel every day": "",
    "i don't watch this channel every day": "",
    "i live in England": "",
    "i don't live in England": "",
    "we don't work here": "",
    "we don't work there": "",
    "you don't understand it": "",
    "they don't see him": "",
    "i don't get up late": "",
    "i get up early": "",
    "i don't go to school": "",
    "i go to university": "",
    "i go to work": "",
    "i don't go to university": "",
    "i don't go to work": "",
    "i don't work": "",
    "i stay at home": "",
    "i don't like this place": "",
    "i like another place": "",
    "i like that place": "",
    "it doesn't cost much": "",
    "it costs a lot": "",
    "it costs little": "",
    "it doesn't cost little": "",
    "she doesn't teach English": "",
    "she teaches mathematics": "",
    "i don't live in New York": "",
    "i live in Los Angeles": "",
    "i don't like this game": "",
    "i like that game": "",
    "i don't play the piano": "",
    "i play computer games": "",
    "i play the guitar": "",
    "i don't go to work every day": "",
    "i work from home": "",
    "i work at home": "",
    "i don't buy newspapers ot magazines": "",
    "i read them online": "",
    "i don't know much about politics": "",
    "it doesn't interest me": "",
    "i don't speak Chinese": "",
    "i speak English and Spanish": "",
    "she doesn't like her job": "",
    "she wants to find another job": "",
    "i don't eat meat but i eat fish": "",
    "i don't play tennis": "",
    "she plays it": "",
    "i don't do physical exercises at home": "",
    "i go to the gym": "",
    "i don't play computer game all day": "",
    "i like sport": "",
    "i don't watch her channel every day": "",
    "i don't go to school": "",
    "i go to university": "",
    "he work a lot": "",
    "he wants to work less": "",
    "i don't live in England": "",
    "i don't talk to him": "",
    "i don't want to do it right now": "",
    "i want to do it later": "",
    "she doesn't teach English": "",
    "she teaches maths": "",
    "i don't like this song": "",
    "i like that song": "",
    "i watch this channel every day": "",
    "i don't play tennis": "",
    "she plays it": "",
    "i don't get up late": "",
    "i get up early": "",
    "it doesn't cost much": "",
    "it costs little": "",
    "i don't play the piano": "",
    "i play the guitar": "",
    "i don't see him": "",
    "we don't work there": "",
    "she doesn't want to sell her house": "",
    "she wants to sell her flat": "",
    "it doesn't cost little": "",
    "it costs a lot": "",
    "i understand you but don't understand native speakers": "",
    "it doesn't help me": "",
    "i don't buy newspapers or magazines": "",
    "i read them online": "",
    "she doesn't like her job": "",
    "she wants to find another job": "",
    "i don't want to do it again": "",
    "i want to do it now but very well": "",
    "you don't understand it": "",
    "i don't go to work every day": "",
    "i work from home": "",
    "i don't do physical exercises ar home": "",
    "i don't eat meat but i eat fish": "",
    "she doesn't think so": "",
    "i don't know much about politics": "",
    "it doesn't interest me": "",
    "i don't have much free time": "",
    "i have little free time": "",
    "i don't speak English fluently": "",
    "i try to learn it": "",
    "i don't live in Moscow": "",
    "i live in New York": "",
    "i don't play computer games all day": "",
    "i like sport": "",
    "she works little": "",
    "she wants to work more": "",
    "i don't go to work": "",
    "i don't work": "",
    "i stay at home": "",
    "i don't go to university": "",
    "i go to work": "",
    "i don't like this place": "",
    "i like another place": "",
    "i don't order it here": "",
    "i order it online": "",
    "we don't know it": "",
    "she doesn't say it": "",
    "she doesn't tell us everything": "",
    "she doesn't like that channel": "",
    "she likes this channel": "",
    "we don't like those lessons": "",
    "we like these lessons": "",
    "she doesn't visit him": "",
    "she works very hard": "",
    "she doesn't have free time": "",
    "i don't learn English there": "",
    "i prefer to learn English here": "",
    "i learn English on the channel English Galaxy": "",
    # i / we / they + г
    #  he /she / it + г + s
    # i / we / they + don't + г
    #  he /she / it doesn't + г(verb)
    "my girlfriend lives there": "",
    "my girlfriend doesn't live there": "",
    "my brother doesn't want to do this homework": "",
    "my cousin doesn't go to concerts": "",
    "he doesn't like it": "",
    "my best friend doesn't smoke": "",
    "he wants to be healthy": "",
    "he doesn't eat little": "",
    "he eats a lot": "",
    "he eats too much": "",
    "our director doesn't ask many questions": "",
    "my friend doesn't like classical music": "",
    "our lessons don't finish late because they start early": "",
    "his parents don't live together": "",
    "they live separately": "",
    "my friend doesn't drive fast": "",
    "he drives very slowly": "",
    "my brother doesn't go shopping": "",
    "my sister goes shopping": "",
    "my father doesn't teach history": "",
    "he teaches English": "",
    "my brother doesn't watch football on tv but he likes it": "",
    "my friend doesn't walk to work": "",
    "he goes to work by car": "",
    "he goes to work on foot": "",
    "my sister goes to school by car": "",
    "my sister goes to school on foot": "",
    "my sister walk to school": "",
    "my sister doesn't listen to him": "",
    "she listens to her": "",
    "my friends  don't listen to them": "",
    "they listen to us": "",
    "i don't buy food": "",
    "my parents usually buy all the food": "",
    "he doesn't eat little": "",
    "my parents don't want to buy this thing": "",
    "my brother doesn't get up early": "",
    "he gets up very late": "",
    "my patents don't like this place": "",
    "they like another place": "",
    "my boss doesn't want to do it": "",
    "my brother doesn't want to study abroad": "",
    "he wants to study in Russia": "",
    "my friends don't order it online": "",
    "they buy it here": "",
    "my brother doesn't know it but i know it": "",
    "my sister walks to school": "",
    "my sister goes to school on foot": "",
    "she doesn't watch that channel": "",
    "she watches this channel": "",
    "my sister goes to school by car": "",
    "my brother doesn't understand me": "",
    "my best friend doesn't smoke": "",
    "he wants to be healthy": "",
    "my brother doesn't watch football on tv but he likes it": "",
    "he doesn't eat much but she eats too much": "",
    "my sister doesn't listen to him": "",
    "she listens to her": "",
    "my cousin doesn't go to concerts": "",
    "he doesn't like it": "",
    "that lesson doesn't help": "",
    "this lesson helps": "",
    "all your lessons really help": "",
    "my uncle doesn't want to call here": "",
    "my parents don't want to live in another city": "",
    "they want to live in this city": "",
    "her cousin doesn't want to do it right now": "",
    "he wants to do it later": "",
    "my friend doesn't walk to work": "",
    "my friend doesn't go to work on foot": "",
    "he goes to work by car": "",
    "my teacher doesn't like those lessons": "",
    "he likes these lessons": "",
    "my friend doesn't talk to her": "",
    "my friends don't listen to them": "",
    "they listen to us": "",
    "i don't buy food": "",
    "my parents usually buy all the food": "",
    "my brother doesn't to do that homework": "",
    "my sister doesn't go to school": "",
    "she goes to university": "",
    "my brother doesn't go shopping": "",
    "my sister goes shopping": "",
    "my father doesn't teach history": "",
    "he teaches English": "",
    "my friends don't watch that channel every day": "",
    "they watch this channel": "",
    "this idea doesn't seem interesting": "",
    "my brother doesn't want to do this thing": "",
    "my sister doesn't want to study abroad but i want it": "",
    "my girlfriend doesn't live there": "",
    "she lives here": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}