slovar = {
    "It's snowy": "",
    "It's rainy": "",
    # Present Continuous
    "I'm discussing it with them": "",
    "I'm becoming more experienced": "",
    "I'm learning English now": "",
    "My friend and I are going there": "",
    "I'm going there with my friend": "",
    "My partner and I are looking for a new investor": "",
    "My colleagues and I are considering this invitation": "",
    "Your friends are choosing this hotel": "",
    "My brothers are reading your message now": "",
    "My relative is travelling now": "",
    "My boss is reading this report": "",
    "My colleagues are preparing these documents": "",
    # we use Present Simple instead of Present Continuous
    "I understand you very well now": "",
    "I want to thank you now": "",
    "I know it": "",
    "I see my progress now": "",
    "It seems very strange now": "",
    "It sounds very unusual now": "",
    "I like your idea now": "",
    "I love you very much now": "",
    "I hate you": "",
    "I prefer to talk about it": "",
    "I prefer not to talk about it": "",
    "I wish you good luck": "",
    "It costs 10 dollars now": "",
    "This house belongs to me now": "",
    "have": "",
    "I have a car": "",
    "I have a brother": "",
    "Have a rest": "",
    "have a good time": "",
    "have a great time": "",
    "I'm having a rest": "",
    "We're having a good time": "",
    "They're having a great time together": "",
    "I think it's best decision ": "",
    "It's my opinion": "",
    "I'm thinking about this problem": "",
    "I'm thinking about this conflict": "",
    # Present Continuous
    # I'm not ; We aren't / You aren't / They aren't; He isn't she/isn't it isn't + verb + ing
    "I'm not watching this movie now": "",
    "I'm not taking an exam now": "",
    "I'm not walking in the park now": "",
    "We aren't overworking now": "",
    "We're working normally": "",
    "We aren't waiting for his help": "",
    "We aren't thinking about it seriously": "",
    "You aren't speaking without mistakes": "",
    "You aren't learning English effectively": "",
    "You aren't doing the right thing": "",
    "They aren't living in this house now": "",
    "They aren't ignoring this problem": "",
    "They aren't staying at home now": "",
    "He isn't wasting time": "",
    "He isn't closing his eyes on these problems": "",
    "He isn't listening to music now": "",
    "She isn't teaching history now": "",
    "She isn't working far from that place": "",
    "She isn't listening to them now": "",
    "It isn't getting more expensive": "",
    "It's raining": "",
    "It's showing": "",
    "It isn't raining": "",
    "It isn't showing": "",
    "I'm not learning Spanish": "",
    "I'm learning English": "",
    "We aren't having a rest": "",
    "We're working": "",
    "You aren't helping him": "",
    "I think you're very busy": "",
    "They aren't living in this house now": "",
    "They're living in that house": "",
    "He isn't overworking now": "",
    "He's working little": "",
    "She isn't improving her English now": "",
    "Her motivation isn't high enough": "",
    "It isn't raining": "",
    "It's snowing": "",
    # Present Continuous ( negative form )
    "My parents aren't leaving the country": "",
    "My partner isn't making me problems": "",
    "His company isn't experiencing difficulties": "",
    "The factory isn't producing these goods at the moment": "",
    "Their business isn't expanding": "",
    "My colleagues aren't comparing these things": "",
    "His employees aren't complaining now": "",
    "His employer isn't providing good conditions": "",
    "This teacher isn't explaining it using simple words": "",
    "I'm teaching English now giving simple explanations": "",
    "This computer doesn't cost 500 dollars now": "",
    "This idea doesn't seem interesting now": "",
    "It's my opinion": "",
    "I think": "",
    "I don't think it's the best strategy now": "",
    "He doesn't have a house now": "",
    "I'm not thinking about this problem now( a mental process)": "",
    "He isn't having a rest now": "",
    # Present Continuous (Questions)
    # AM I + verb + ing
    # Are we/you/they/ + verb + ing
    # Is he/she/it + verb + ing
    "Am I training intensively?": "",
    "Am I increasing my vocabulary using effective methods?": "",
    "enlarge / widen / enrich vocabulary": "",
    "Am I becoming stronger?": "",
    "Are we changing?": "",
    "Are we preparing for this exam well enough?": "",
    "This lesson is good enough": "",
    "Are we learning English effectively?": "",
    "Are you joking?": "",
    "Are you kidding?": "",
    "Are you combining different methods now?": "",
    "Are you recovering now?": "",
    "Are they hiding from him?": "",
    "Are they smoking now?": "",
    "Are they kissing?": "",
    "Is he swimming now?": "",
    "Is he thinking about our offer now?": "",
    "Is he lying to you?": "",
    "Is she smiling?": "",
    "Is she dancing now?": "",
    "Is she checking his work?": "",
    "It's raining": "",
    "Is it raining?": "",
    "It's snowing": "",
    "Is it snowing?": "",
    "It's getting dark": "",
    "Is it getting dark?": "",
    "Am I wasting time?": "",
    "Are we giving you a good chance?": "",
    "Are you leading a healthy lifestyle?": "",
    "way of life": "",
    "Are they controlling this situation now?": "",
    "Is he cooking?": "",
    "Is she washing up the dishes?": "",
    "Is it bringing you money now?": "",
    "I sat on a soft chair": "",
    "They ran very fast": "",
    "They were together": "",
    "I felt better": "",
    "He sold his flat": "",
    "I wrote a very long message": "",
    "I was shocked": "",
    "I ate some fish": "",
    "I paid for her": "",
    "He gave me this information": "",
    "He showed me his excellent results": "",
    "He came to the party": "",
    "I wore school uniform": "",
    "It meant nothing": "",
    "It didn't mean anything": "",
    "He cut himself": "",
    "He hit the ball": "",
    "He sent her flowers": "",
    "It lay near that place": "",
    "He lent her 200 pounds": "",
    "I spent so much time on it": "",
    "They did it again and again": "",
    "He was such an experienced worker": "",
    "As you understand we spoke English": "",
    "I knew what to say": "",
    "They hid from us": "",
    "He stole her bag": "",
    "He threw a ball to him": "",
    "She told me how to do it": "",
    "I spoke English a lot": "",
    "He threw a small ball to him": "",
    "She taught English there 2 years ago": "",
    "We met in a local restaurant": "",
    "He came to us": "",
    "They sang the favorite song": "",
    "We had a great time": "",
    "We were surprised by the news": "",
    "He lost his wallet": "",
    "He fell down and broke his leg": "",
    "I wrote a message": "",
    "He spent all his money": "",
    "I left my wallet at home": "",
    "I felt we had a big problem": "",
    "I understood him immediately": "",
    "He got up too late": "",
    "I read that text": "",
    "It cost too much": "",
    "I chose this channel": "",
    "She hid behind the tree": "",
    "I chose your method": "",
    "His car broke down": "",
    "We chose another room": "",
    "He drank a glass of wine": "",
    "I rode a bike": "",
    "I went cycling": "",
    "I felt I knew everything": "",
    "She sold her car": "",
    "I took her with me": "",
    "I drove a car yesterday": "",
    "I put it near my computer": "",
    "They always spent more money": "",
    "We flew to another city": "",
    "I felt bad": "",
    "I was the best student": "",
    "She grew vegetables in her own garden": "",
    "I found a good job": "",
    "The wind blew suddenly": "",
    "I spent 2 hours on it": "",
    "I did my homework": "",
    "He swam in the lake": "",
    "She grew flowers": "",
    "He sang professionally": "",
    "I drank a cup of coffee": "",
    "He said it one more time": "",
    "The price fell sharply": "",
    "My friend drove home": "",
    "I went to the park": "",
    "I got up very early": "",
    "I went jogging": "",
    "His parents let him play outside": "",
    "I felt good": "",
    "He did a strange thing": "",
    "We swam un the river": "",
    "I often heard it when I was there": "",
    "She was a leader": "",
    "I felt much better": "",
    "She kept her money in a bank": "",
    "I wrote a letter": "",
    "I knew how to say it": "",
    "She told me her secret": "",
    "I saw progress": "",
    "I left home 20 minutes ago": "",
    "I forgot to call her": "",
    "He broke her pen": "",
    "She told me to call him": "",
    "We knew it very well": "",
    "He bought a beautiful dress for her": "",
    "He hurt her feelings": "",
    "I paid for this service": "",
    "We got all the necessary information": "",
    "He paid for us": "",
    "I'm doing homework": "",
    "you're making progress": "",
    "He's playing outside": "",
    "I'm considering this job offer": "",
    "She's doing housework": "",
    "I'm checking his work": "",
    "I'm thinking about this problem": "",
    "He's recording this video": "",
    "You're making a mistake": "",
    "She's feeding the children": "",
    "They're leaving": "",
    "She's making progress": "",
    "I'm teaching English": "",
    "They're experiencing big difficulties": "",
    "I'm doing physical exercises": "",
    "We're recording his speech": "",
    "I'm trying to concentrate": "",
    "It's getting late": "",
    "They're playing football": "",
    "You're speaking without mistakes": "",
    "It's raining": "",
    "He's working on this project": "",
    "I'm recording this lesson": "",
    "You're saying everything correctly": "",
    "He's saying such strange things": "",
    "They're playing chess": "",
    "We're experiencing big problems": "",
    "We're waiting for you": "",
    "You're saying very interesting things": "",
    "I'm waiting for your answer": "",
    "He's waiting for our decision": "",
    "I'm talking on the phone": "",
    "She's teaching Spanish": "",
    "She's waiting for his message": "",
    "We're waiting for your e-mail": "",
    "They're laughing at them": "",
    "They're losing": "",
    "I'm looking at you": "",
    "He's laughing at their mistakes": "",
    "I'm trying to solve this problem": "",
    "We're talking on the phone right now": "",
    "We're thinking about it": "",
    "It's snowing": "",
    "She's expressing her opinion": "",
    "I'm preparing for a very difficult exam": "",
    "He's explaining the meaning of this phrase": "",
    "She's considering your offer": "",
    "I'm making progress": "",
    "She's laughing at his behavior": "",
    "They're winning": "",
    "Are our results getting better?": "",
    "Is the situation getting worse?": "",
    "good better the best": "",
    "it's the best channel": "",
    "bad worse the worst": "",
    "It's the worst scenario": "",
    "Is your girlfriend looking for a new job?": "",
    "Are these lessons becoming more difficult?": "",
    "Is your friend considering this job offer?": "",
    "Is your director creating new opportunities for his employees?": "",
    "Is our economy growing?": "",
    "Are his students improving their results?": "",
    "Is your friend describing this situation?": "",
    "Is your teacher explaining it very clearly now?": "",
    "Are his parents arguing at the moment": "",
    "Are the investors calculating their losses now?": "",
    "Do you like this idea now?": "",
    "In this case we use present simple instead of present continuous": "",
    "Does this computer cost the same now?": "",
    "Does your friend know the meaning of this phrase now?": "",
    "Do your friends really understand it now?": "",
    "Does this offer sound really strange now?": "",
    "Present Continues Special Question": "",
    "Question word + am/is/are + subject + verb + ing?": "",
    "What is she describing?": "",
    "What is happening?": "",
    "What is getting more expensive?": "",
    "What is bringing him money now?": "",
    "Where is he waiting?": "",
    "Where is she working now?": "",
    "Where are they going?": "",
    "Where are you having a rest?": "",
    "Why are you learning English?": "",
    "Why are you teaching English here?": "",
    "Why are you thinking about their offer?": "",
    "Why are you paying him so much money?": "",
    "Why are your reading such a strange book?": "",
    "Who is waiting for you?": "",
    "Who is knocking?": "",
    "Who is coming?": "",
    "Who is supporting you?": "",
    "How is she cooking it?": "",
    "How are you learning English?": "",
    "How are you doing your homework?": "",
    "How is she looking after her baby": "",
    "take care of": "",
    "How are they behaving?": "",
    "What is she telling you?": "",
    "Where are you leaving?": "",
    "Why is it happening?": "",
    "Who is joining us?": "",
    "How is he treating them?": "",
    "treat someone": "",
    "Why is your colleague calling you now?": "",
    "Why is the teacher recording this lessons now?": "",
    "What are your friends doing now?": "",
    "What is your brother writing at the moment?": "",
    "What are the students writing  down now?": "",
    "What ideas are these students discussing now?": "",
    "What job is your brother trying to find?": "",
    "What job is your brother looking for?": "",
    "What kind of job is your sister looking for?": "",
    "Where are your friends going?": "",
    "where is your father working now?": "",
    "Where is your friend going?": "",
    "Where is this thing happening": "",
    "happening / going on": "",
    "Who is correcting his mistakes now?": "",
    "Who is checking his homework now?": "",
    "Who is building that house?": "",
    "Who is training him?": "",
    "What is moving?": "",
    "What is really helping you now?": "",
    "What is he saying so quietly?": "",
    "What is he telling you?": "",
    "Where is she living now?": "",
    "Why does he agree with you now?": "",
    "What books do your friends prefer to read now?": "",
    "How does your teacher see so many mistakes now?": "",
    "How do our guests hear me now?": "",
    "Why does this result depend only on me now": "",
    "It depends on you": "",
    "We're are looking at this slide": "",
    "You're teaching English": "",
    "They're having about our offer": "",
    "She's talking okn the phone": "",
    "It's snowing": "",
    "I'm listening to you": "",
    "Negative Form": "",
    "I'm not waiting for him now": "",
    "We aren't speaking Russian": "",
    "You aren't choosing the right answer": "",
    "They aren't staying at home now": "",
    "He isn't working now": "",
    "She isn't considering their offer": "",
    "It isn't raining now": "",
    "Am I recording an interesting lesson?": "",
    "Are we making progress?": "",
    "Are you writing it down?": "",
    "Are they joining us?": "",
    "Is he walking in the park now?": "",
    "Is she discussing this problem now?": "",
    "Is it getting late?": "",
    "I'm learning English very intensively now": "",
    "I'm not learning English very intensively now": "",
    "Am I learning English very intensively now?": "",
    "He's showing outstanding results now": "",
    "He isn't showing outstanding results now": "",
    "Is he showing outstanding results now": "",
    "His parents are having a rest": "",
    "That channel is getting unpopular": "",
    "and the last thing": "",
    "Special Question": "",
    # Question word + am/is/are + verb + ing
    "Why are you watching this video now?": "",
    "I want to get this knowledge now": "",
    "What king of movie are you watching?": "",
    "What game are you playing now?": "",
    "What game is you brother playing now?": "",
    "agree - Why do you agree with him now?": "",
    "believe in God: believe you - Do you believe him now?": "",
    "belong to - Does this flat belong to you now?": "",
    "depend on - Does the final decision depend on you?": "",
    "disagree - Why do you disagree with me now?": "",
    "hate - Why do you hate it now?": "",
    "hear - I hear it for the first time. I hear you well": "",
    "know - I know the answer now": "",
    "like - I really like this idea now": "",
    "love - I love you with all my heart now": "",
    "mean - What do you mean now?": "",
    "need - I need it right now": "",
    "prefer - I prefer to avoid discussing it( avoid doing something)": "",
    "remember - I remember it very clearly": "",
    "seem - It seems wrong now": "",
    "sound - Your words sound very optimistic now": "",
    "suppose - I suppose you're right": "",
    "understand - I perfectly understand you now": "",
    "want - I want it to happen now - want someone to do something": "",
    "I want you to learn English": "",
    "I want you to enjoy learning English": "",
    "It's the mission of this channel": "",
    "I wish you good luck!": "",
    "Think - i think it's a brilliant idea( It's my opinion - you express your opinion": "",
    "I'm thinking about this idea": "",
    "have": "",
    "I have a car": "",
    "have a good / great time": "",
    "have a rest": "",
    "have fun (entertain - entertainment": "",
    "We're having fun now": "",
    "present simple": "",
    "past simple": "",
    "future simple": "",
    "He (work) very hard": "",
    "He works very hard": "",
    "He worked very hard": "",
    "He will work very hard": "",
    "He is working very hard": "",
    "He doesn't work very hard": "",
    "He didn't work very hard": "",
    "He won't work very hard": "",
    "He isn't working very hard": "",
    "Does he work very hard?": "",
    "Did he work very hard?": "",
    "Will he work very hard?": "",
    "Is he working very hard?": "",
    "It (interesting)": "",
    "It is interesting": "",
    "It was interesting": "",
    "It will be interesting": "",
    "It isn't interesting": "",
    "Is it interesting?": "",
    "It wasn't interesting": "",
    "Was it interesting?": "",
    "It won't be interesting": "",
    "Will it be interesting?": "",
    "What do you know about this thing?": "",
    "manage to do something": "",
    "How did you manage to win?": "",
    "Why will he refuse to pay?": "",
    "Where are they waiting for you now?": "",
    "What seemed strange?": "",
    "How will you cope with this problem?": "",
    "Why are you shouting at him now?": "",
    "Where does this conference take place?": "",
    "How often did it happen?": "",
    "How much money do you owe him?": "",
    "What are they discussing now?": "",
    "What places will you visit next time?": "",
    "How often do you check their work?": "",
    "How much will it cost to buy a house here?": "",
    "What book are you reading now?": "",
    "What are you talking about?": "",
    "Where are you from?": "",
    "What king of lessons will you take?": "",
    "How long did it rake you to get to work?": "",
    "How interesting was the lesson?": "",
    "How interesting will the lecture be?": "",
    "What kind of teacher did you meet?": "",
    "How long is the way?": "",
    "Who is sating it?": "",
    "Who says it?": "",
    "Who are you telling it now?": "",
    "What interests him?": "",
    "What interested him?": "",
    "What will interest him?": "",
    "Who helps you most of all?": "",
    "Who did you include in your team?": "",
    "What (you) tell her?": "",
    "What do you tell her?": "",
    "What did you tell her?": "",
    "What will you tell her?": "",
    "What are you telling her?": "",
    "Who translate this text?": "",
    "Who translates this text?": "",
    "Who translated this text?": "",
    "Who will translate this text?": "",
    "Who is translating this text?": "",
    "Who care about these things?": "",
    "Who cares about these things?": "",
    "Who cared about those things?": "",
    "Who will care about these things?": "",
    "Who is caring about these things?": "",
    "Why do they criticize him so sharply?": "",
    "Why did they criticize him so sharply?": "",
    "Why will they criticize him so sharply?": "",
    "Why are they criticizing him so sharply?": "",
    "Why does it belong to her?": "",
    "Why did it belong to her?": "",
    "Why will it belong to her?": "",
    "How much does this dress cost?": "",
    "How much did this dress cost?": "",
    "How much wil this dress cost?": "",
    "How does your friend like these changes?": "",
    "How did your friend like those changes?": "",
    "How will your friend like these changes?": "",
    "I did it": "",
    "I was doing it": "",
    "discuss": "",
    "We discussed it": "",
    "We were discussing it": "",
    "short action": "",
    "long action": "",
    "When": "",
    "When he (come) home, I (check) my e-mail": "",
    "When he came home, I was checking my e-mail": "",
    "When he ( call ) my, I (drive) a car": "",
    "When he called me, I was driving a car": "",
    "work perfectly": "",
    "I was working perfectly": "",
    "We were working perfectly": "",
    "You were working perfectly": "",
    "They were working perfectly": "",
    "He was working perfectly": "",
    "She was working perfectly": "",
    "It was working perfectly": "",
    "Look strange": "",
    "I was looking strange": "",
    "We were looking strange": "",
    "You were looking strange": "",
    "They were looking strange": "",
    "He was looking strange": "",
    "She was looking strange": "",
    "It was looking strange": "",
    "seem strange": "",
    "I understood it": "",
    "I wanted it": "",
    "The teacher was pointing at our mistakes": "",
    "His children were living together": "",
    "His children were living separately": "",
    "The children were playing football": "",
    "His secretary was sitting on a chair": "",
    "The boss was sitting in an armchair": "",
    "Her boss was treating her unfairly": "",
    "His friend was sleeping on the floor": "",
    "Our manager was trying to change the situation": "",
    "An old woman was feeding her cat": "",
    "My friend was smiling at her": "",
    "The children were collecting coins": "",
    "The criminals were denying all the accusations": "",
    "My English was really improving": "",
    "His son was preparing for a difficult exam": "",
    "The soldiers were fighting very bravely": "",
    "His new worker was making him problems": "",
    "The authorities were using power": "",
    "They didn't agree with us": "",
    "He didn't believe in God": "",
    "That problem concerned us": "",
    "The book consisted of five chapters": "",
    "That information contained strange things": "",
    "His success depended on him": "",
    "She deserved respect": "",
    "I doubted that it was the right decision": "",
    "She hated that song": "",
    "I heard that thing for the first time": "",
    "That list included our names": "",
    "That project involved lost of risks": "",
    "We knew it perfectly": "",
    "They loved each other": "",
    "We needed their help": "",
    "He owed him something": "",
    "He owned that company": "",
    "She promised that she would do it": "",
    "I realized it": "",
    "His words seemed very strange": "",
    "His offer sounded very strange, too": "",
    "I perfectly understood him": "",
    "He wanted much more": "",
    "I wished him true happiness": "",
    "think": "",
    "I thought that I was right( it was my opinion)": "",
    "I was thinking about my future( it was a mental process)": "",
    "have": "",
    "He had 2 cars( He owned 2 cars)": "",
    "They were having a good time( it was in progress)": "",
    "great time": "",
    "When she came hom , he was playing computer games": "",
    "When he came home, I was learning English": "",
    "When she arrived, They were discussing that problem": "",
    "When he arrived, I was telling him about that thing": "",
    "When I saw her, she was going upstairs": "",
    "When he noticed her, she was going downstairs": "",
    "When the bell rang, he was taking a shower": "",
    # When + Past Simple, Past Continuous
    # While + Past Continuous, Past Continuous
    # 2 actions happening at the same time
    "While I was working , they were having a rest/ relaxing": "",
    "While we were preparing for that exam, they were in India": "",
    "When I was staying at home, they were walking in the park": "",
    "When we were living in Spain, we depended on them": "",
    "When I was competing with them , I needed their help": "",
    "if possible": "",
    "When we describe something in the past": "",
    "The sun was shining brightly. We were having a rest. We were looking at them": "",
    "all day. all night": "",
    "I was preparing for my exam all day": "",
    # I.he.she.it  -- wasn't / we.you.they---- weren't + verb + ing
    "I wasn't having a rest": "",
    "He wasn't making any mistakes": "",
    "She wasn't translating it": "",
    "It wasn't making us problems": "",
    "We weren't helping them": "",
    "You weren't following our recommendations": "",
    "They weren't criticizing us": "",
    "Our boss wasn't ignoring our problems": "",
    "My friends weren't celebrating that holiday": "",
    "The managers weren't calculating all the costs": "",
    "That client wasn't complaining": "",
    "When we were living there, we didn't like their attitude": "",
    "While we were looking for a job, he didn't want to change anything": "",
    "While they were talking about that problem, it didn't concern us": "",
    "When he came home, she didn't greet him": "",
    # When + past simple + past simple
    "He didn't agree with us": "",
    "He doesn't agree with us now": "",
    "He didn't believe us": "",
    "That business didn't belong to him": "",
    "It didn't concern us": "",
    "His success didn't depend only on him": "",
    "He didn't deserve such bad words": "",
    "She didn't hate him": "",
    "We didn't know what to do": "",
    "She didn't understand me at all": "",
    "It didn't mean anything": "",
    "The offer didn't seem attractive": "",
    "His ex-girlfriend didn't wish him anything bad": "",
    "His words didn't sound convincing": "",
    "We weren't thinking about that job offer seriously": "",
    "I didn't think it was right ( in other words, It wasn't my opinion that it was right)": "",
    "We were talking about 'think' ": "",
    "What about 'have' ": "",
    "How about 'have' ": "",
    "Have - possess": "",
    "I didn't have free time": "",
    "have a rest": "",
    "have a good / great time": "",
    "I wasn't having a rest": "",
    "When she was reading a book aloud, I wasn't listening to her": "",
    "When I was studying there, I didn't have any problems": "",
    "When I was studying there , I wasn't experiencing any problem": "",
    "When she saw me, I wasn't talking to him": "",
    "When she saw me, I didn't know what to say": "",
    "When she returned, I left home": "",
    "I was leaving home": "",
    # Was I.he.she.it + verb + ing
    # were we.you.they + verb + ing
    "Was I thinking about it seriously?": "",
    "Was he lying to her?": "",
    "Was she trying to concentrate?": "",
    "Was it bringing him money?": "",
    "Were we making progress?": "",
    "Were you praying?": "",
    "Were they staling money?": "",
    "Were you thinking about her when she arrived?": "",
    "Were you laughing when she saw you?": "",
    "Were you walking in the park when it started raining": "",
    "Were they discussing that problem when you noticed them?": "",
    "What were you doing when she called you?": "",
    "they knocked at the door?": "",
    "the bell rang?": "",
    "she saw you?": "",
    "he came back?": "",
    "he came home?": "",
    "he returned home?": "",
    "Were you listening to music at 6 o'clock yesterday?": "",
    # Past Continuous
    # +( statement / affirmative )
    # was/were + verb + ing --- a long action in the past
    "I was having a rest": "",
    "He was giving a party": "",
    "She was preparing for a very important exam": "",
    "It was influencing her": "",
    "We were practicing English": "",
    "They were swimming in the lake": "",
    "I know you were dancing all night": "",
    "I wasn't translating those texts": "",
    "He didn't agree with us": "",
    "She wasn't reacting to his words": "",
    "It didn't belong to us": "",
    "We weren't advising it": "",
    "You didn't like it": "",
    "They weren't constructing that building": "",
    "Let's have a look at...": "",
    # Was / Were + subject + verb + ing
    "Did I understand it very well?": "",
    "Was he interrupting you?": "",
    "Was she crying?": "",
    "Was it motivating you?": "",
    "Were we showing the best results?": "",
    "Were you tired?": "",
    "Were they laughing at him?": "",
    "Were you proud of his achievements?": "",
    "When...., (Past simple), Past Continuous": "",
    "When she came in , I was typing that text": "",
    "Past Continuous when (Past Simple)": "",
    "I was typing that text when she came in": "",
    "When she called me, I wasn't thinking about her": "",
    "I wasn't thinking about her when she called me": "",
    "Were you leaving home": "",
    "Were you leaving home when he shouted to you?": "",
    # You need to open the brackets using
    # Past Continuous
    # she (drive a car)
    "She was driving a car": "",
    "She wasn't driving a car": "",
    "I speak English": "",
    "I speak Russian": "",
    "I understand": "",
    "I understand you": "",
    "I understand you very well": "",
    "I know English": "",
    "I know it": "",
    "I work": "",
    "I work there": "",
    "I study": "",
    "I study at school": "",
    "I study at university": "",
    "I study there": "",
    "I play": "",
    "I play football": "",
    "I have a car": "",
    "they have a house": "",
    "I speak English": "",
    "She speaks English ": "",
    "It helps me": "",
    "It helps you": "",
    "He lives in London": "",
    "He works hard": "",
    "He works very hard": "",
    "She works a lot": "",
    "He plays computer games": "",
    "He swims very well": "",
    "She understands this lesson": "",
    "He remembers it": "",
    "It works well": "",
    "She speaks English/Spanish": "",
    "I speak English fluently": "",
    "He speaks English fluently": "",
    "She eats meat. He eats fish": "",
    "It happens": "",
    "He plays tennis": "",
    "She plays different gemas": "",
    "I work there": "",
    "We know it very well": "",
    "You understand me": "",
    "They live in England": "",
    "He works in London": "",
    "She works a lot": "",
    "It really helps me": "",
    "I go there": "",
    "She goes there": "",
    "I do it well": "",
    "He does it well": "",
    "I do housework": "",
    "She does housework": "",
    "I go to work": "",
    "She goes to work": "",
    "I go to school": "",
    "She goes to school": "",
    "I go to the park": "",
    "He goes to the park": "",
    "I go to the cinema": "",
    "He goes to the cinema": "",
    "I go to the theatre": "",
    "She goes to the theatre": "",
    "I go there": "",
    "I ofter go there": "",
    "He often goes there": "",
    "She often does it": "",
    "I teach English": "",
    "She teaches English": "",
    "I watch TV": "",
    "He watches TV": "",
    "I watch TV everyday": "",
    "He watches TV everyday": "",
    "I play football": "",
    "He plays football": "",
    "We play computer games": "",
    "He plays computer games": "",
    "I often fly to America": "",
    "He often flies to America": "",
    "She often flies to England": "",
    "He often cries": "",
    "She ties to do it": "",
    "I try to learn English": "",
    "He tries to learn Spanish": "",
    "I have a car": "",
    "He has a car": "",
    "I have a computer": "",
    "She has a computer": "",
    "I have a house": "",
    "He has a house": "",
    "I have a flat": "",
    "She has a flat": "",
    "I have many friends": "",
    "He has many friends": "",
    "I have a job": "",
    "She has a job": "",
    "He has a girlfriend": "",
    "She has a boyfriend": "",
    "This lesson helps me": "",
    "These lessons help me": "",
    "My sister live in Russia": "",
    "My best fiend plays basketball": "",
    "My brother lives in this house": "",
    "My sister lives in that house": "",
    "Your idea seems interesting": "",
    "She likes this idea": "",
    "Kate likes this idea": "",
    "Max lives in this city": "",
    "I often listen to music": "",
    "My sister often listens to music": "",
    "I - my": "",
    "I have a brother": "",
    "My brother goes to school": "",
    "We - our": "",
    "We have an uncle": "",
    "Our uncle speaks English fluently": "",
    "You - your": "",
    "You have a house": "",
    "Your house looks beautiful": "",
    "They - their": "",
    "Their teacher says so": "",
    "He - his": "",
    "His parents work there": "",
    "His mother teaches French": "",
    "She - her": "",
    "Her father does business": "",
    "She eats fish": "",
    "I go to work": "",
    "She goes to work": "",
    "I do it very well": "",
    "He does it very well": "",
    "I often watch TV": "",
    "She often watches TV": "",
    "She washes up the dishes": "",
    "he often relaxes in the evening": "",
    "He often has a rest in the evening": "",
    "My father works there": "",
    "My sister knows it very well": "",
    "Their parents live there": "",
    "This lesson seems interesting": "",
    "These lessons seem very interesting": "",
    "I want this dress": "",
    "I want to buy this dress": "",
    "I want this thing": "",
    "I want to buy this thing": "",
    "I want to order it": "",
    "I want to buy a house": "",
    "I want to know English really well": "",
    "I want to speak English fluently": "",
    "I want to eat": "",
    "I want to drink": "",
    "I want to drink a cup of tea": "",
    "I want to drink a cup of coffee": "",
    "I want to learn English": "",
    "I want to go to America next month": "",
    "I want to go to Italy next year": "",
    "I want ot read this book": "",
    "I want to call her": "",
    "They want to call me": "",
    "They want to call us": "",
    "I want to visit this place": "",
    "I want to get more money": "",
    "I want to live in another country": "",
    "I want to live abroad": "",
    "My boss wants more money": "",
    "My brother wants to study in another place": "",
    "My aunt wants to sell her house": "",
    "My uncle wants to sell his falt": "",
    "Her relative wants to rent a flat": "",
    "His secretary wants a new job": "",
    "His secretary wants to find a new job": "",
    "He wants to know everything": "",
    "I want to help you": "",
    "I want to thank you": "",
    "Thank! Thanks a lot": "",
    "I want to learn English": "",
    "I want to order it": "",
    "I would like to learn English": "",
    "I would like to order it": "",
    "I'd like to learn English": "",
    "I'd like to order it": "",
    "I'd like to do it now": "",
    "I'd like to do it right now": "",
    "I'd like to talk about it": "",
    "I'd like to speak about it": "",
    "or/and": "",
    "I'd like to talk about this problem": "",
    "I'd like to know it": "",
    "I'd like to do it again": "",
    "I'd like to do it one more time": "",
    "I'd like to buy a new computer": "",
    "I'd like to read book in English": "",
    "I'd like to write it down": "",
    "I'd like to listen to music": "",
    "I'd like to go to the party": "",
    "I'd like to go to this party": "",
    "I'd like to go to the restaurant": "",
    "I'd like to tell you everything": "",
    "I'd like to say it": "",
    "I'd like to know all the news": "",
    "I'd like to tell you all the information": "",
    "I'd like to hear this story": "",
    "I'd like to hear all the story": "",
    "I'd like to be a teacher": "",
    "I'd like to become a teacher": "",
    "I'd like to be a manager": "",
    "I'd like to became a manager": "",
    "I'd like to be a businessman": "",
    "I'd like to became a businessman": "",
    "I'd like to have my own business": "",
    "I'd like to have my own YouTube channel": "",
    "We'd like to invite you to the party": "",
    "They'd like to join us": "",
    "I see you'd like to live here": "",
    "He'd like to get this job": "",
    "She'd like to learn English here": "",
    "I watch this channel every day": "",
    "I don't watch this channel every day": "",
    "I live in England": "",
    "I don't live in England": "",
    "We don't work here": "",
    "we don't work there": "",
    "You don't understand it": "",
    "They don't see him": "",
    "I don't get up late": "",
    "I get up early": "",
    "I don't go to school": "",
    "I go to university": "",
    "I go to work": "",
    "I don't go to university": "",
    "I don't go to work": "",
    "I don't work": "",
    "I stay at home": "",
    "I don't like this place": "",
    "I like another place": "",
    "It doesn't cost much": "",
    "It consts a lot": "",
    "It costs little": "",
    "It doesn't cost little": "",
    "She doesn't teach English": "",
    "She teaches mathematics": "",
    "I don't live in New York": "",
    "I live in Los Angeles": "",
    "I don't like this game": "",
    "I like that game": "",
    "I don't do physical exercises at home": "",
    "I go to the gym": "",
    "I don't play computer games all day": "",
    "I like sport": "",
    "My girlfriend lives there": "",
    "My girlfriend doesn't live there": "",
    "My brother doesn't want to do this homework": "",
    "My cousin doesn't go to the concerts": "",
    "He doesn't like it": "",
    "Our director doesn't ask many questions": "",
    "My friend doesn't like classical music": "",
    "My sister doesn't listen to him": "",
    "She listens to her": "",
    "My friends don't listen to them": "",
    "They listen to us": "",
    "I don't buy food": "",
    "": "",

}