slovar = {
    "Is his father angry?": "",
    "They're our friends": "",
    "He's a talented student": "",
    "He's my classmate": "",
    "Her boyfriend isn't there": "",
    "My cousin is tired": "",
    "It's so bad": "",
    "Their ideas aren't innovative": "",
    "Are you afraid of difficulties": "",
    "Is your brother in bed?": "",
    "I'm American": "",
    "Is that exercise difficult?": "",
    "Is it a dangerous place?": "",
    "Are your colleagues very professional?": "",
    "The story is so long": "",
    "Is the progress slow?": "",
    "It's normal": "",
    "Is it a rainy day?": "",
    "His English isn't fluent": "",
    "His progress isn't good enough": "",
    "Are the boys busy at the moment?": "",
    "It's a very good lesson": "",
    "All his lessons are free": "",
    "Is it a warm day?": "",
    "Are we far from this place?": "",
    "It's good": "",
    "Is it very effective?": "",
    "Is this thing really necessary?": "",
    "Is this detail important?": "",
    "Are you in this hotel?": "",
    "The lesson is interesting": "",
    "She isn't American": "",
    "Is their offer so interesting?": "",
    "Is she a very talented actress?": "",
    "He isn't a rich person": "",
    "He's the best student": "",
    "My friend is ill": "",
    "The problem isn't big": "",
    "Is your friend tired?": "",
    "Is the manager experienced enough?": "",
    "Is our knowledge enough?": "",
    "Is he a successful businessman?": "",
    "She isn't a designer": "",
    "She's a doctor": "",
    "Is his lesson really so effective?": "",
    "My computer is new": "",
    "Is it a popular channel?": "",
    "Are we near this place?": "",
    "Is this exercise easy?": "",
    "Is he often angry?": "",
    "The lesson is difficult": "",
    "The test isn't easy": "",
    "The method is really effective": "",
    "My English teacher is very professional": "",
    "Those problems aren't big": "",
    "This phrase isn't important": "",
    "Are the boys poor?": "",
    "Are those exercises really useless?": "",
    "His father is rich": "",
    "Is it a well-paid job?": "",
    "My parents are angry": "",
    "Am I right or not?": "",
    "Am I right or wrong?": "",
    "Is this sentence interesting?": "",
    # Present Simple special question
    # How / Why / When / Where / What / Who
    # SQ + Am/Is/Are + S  + ....?
    "How are you?": "",
    "Why is she still there?": "",
    "When are they in the office?": "",
    "Where is the nearest supermarket?": "",
    "What is it?": "",
    "Who is he?": "",
    "How much is it?": "",
    "How far is it?": "",
    "Where are you from?": "",
    "I'm from Russia": "",
    "Where is he from?": "",
    "He's from England": "",
    "How much does it cost?": "",
    "How is life?": "",
    "How is this project?": "",
    "How are his parents?": "",
    "Why are we here?": "",
    "Why is she so sure?": "",
    "Why is it so important?": "",
    "When is he at home?": "",
    "When are they together?": "",
    "When are you free?": "",
    "Where is the nearest hotel?": "",
    "Where is this place?": "",
    "Where are my keys?": "",
    "What is in this box?": "",
    "What is in his head?": "",
    "What is there?": "",
    "Who is right?": "",
    "Who is present?": "",
    "Who is absent?": "",
    "Who knows it?": "",
    "Who likes it?": "",
    # Special Question
    # SQ + am/is/are + ....
    "Why is this offer so attractive?": "",
    "How is your cousin?": "",
    "Where are my mistakes?": "",
    "What is love?": "",
    "What is his idea?": "",
    "Who is this man?": "",
    "When are you tired?": "",
    "I'm tired": "",
    "Why is this detail so important?": "",
    "Why are these things necessary?": "",
    "Why is this level basic?": "",
    "Why are you so surprised?": "",
    "Why are you friends shocked?": "",
    "Why is your brother so tired?": "",
    "Why are your parents angry?": "",
    "Why are these topics boring?": "",
    "How is this dish?": "",
    "How is her new dress?": "",
    "How is my new suit?": "",
    "Where are these clothes?": "",
    "Where is our English teacher?": "",
    "Where is justice in the world?": "",
    "Where is his file?": "",
    "What is confidence?": "",
    "What is professionalism?": "",
    "What is in his bag?": "",
    "Who are all these people?": "",
    "Who is this guest?": "",
    "Who is free?": "",
    "When is your boss in this building?": "",
    "When is your mother angry?": "",
    "When is your father tired?": "",
    "How much is it?": "",
    "How much is this computer?": "",
    "How much are the tickets?": "",
    "How often is she late?": "",
    "How often is your boss late?": "",
    "How often are they together?": "",
    "How long is the way?": "",
    "How long is one English lesson?": "",
    "How cheap is it?": "",
    "How expensive is it?": "",
    "How popular is it?": "",
    "How much does it cost?": "",
    "come late": "",
    "How often does she come late?": "",
    "How long is the lesson?": "",
    "How long does the lesson last?": "",
    "Where are you from?": "",
    "Where is he from?": "",
    "What books are interesting for you?": "",
    "Which book is more interesting?": "",
    "What YouTube channels are popular nowadays?": "",
    "What time is it?": "",
    "What's the time?": "",
    # Present Simple (Statement)
    # When we have a verb
    # I/we/you/they + verb
    # He/she/it + verb + s
    "I know the truth": "",
    "We often discuss it": "",
    "You expect this result": "",
    "They want more knowledge": "",
    "She thinks the same": "",
    "He disagrees with this statement": "",
    "It looks surprising": "",
    # When we don't have a verb
    # I'm we/you/they're ; he/she/it's
    "I'm in the garden": "",
    "We're very different": "",
    "You're in a difficult situation": "",
    "They're divorced": "",
    "He's a strange person": "",
    "She's the most beautiful girl in the world": "",
    "It's a bad idea": "",
    # When we have a verb (negative)
    #  i/we/you/they + don't + verb
    # he/ she/ it + doesn't + verb
    "I don't know the answer": "",
    "We don't think so": "",
    "You don't realize it": "",
    "They don't control the situation": "",
    "He doesn't do it": "",
    "She doesn't travel every year": "",
    "This thing doesn't seem strange": "",
    # When we don't have a verb (negative)
    # I'm not
    # we/you/they + aren't
    # he/she/it + isn't
    "I'm not at home": "",
    "We aren't satisfied with this result": "",
    "They aren't professional enough": "",
    "He isn't afraid of it": "",
    "It isn't interesting at all": "",
    # When we have a verb (question)
    # Do I/we/you/they + verb ....?
    # Does he/she/it + verb .... ?
    "Do you know how it works?": "",
    "Do they fully support you?": "",
    "Does she have a similar opinion?": "",
    "Does he know her address?": "",
    "Do I speak English fluently?": "",
    "Do we snow excellent results?": "",
    "Is this problem really difficult?": "",
    # When we don't have a verb (question)
    # Am I; Are we/you/they ? Is he/she/it?
    "Are these lessons really good?": "",
    "Is your friend married?": "",
    "Does he earn more than 200 dollars a month?": "",
    "What is your weight?": "",
    "What's your weight?": "",
    "How much is 1 hour?": "",
    "How long does the course last?": "",
    "How long is the course?": "",
    "Do your parents know it?": "",
    "Is this thing really useful?": "",
    "The results aren't good enough": "",
    "Does that thing interest them?": "",
    "Your lessons aren't boring at all": "",
    "The book isn't so cheap": "",
    "Is the ticket expensive?": "",
    "All these things don't interest them": "",
    "When do these exams start?": "",
    "Is it easy or difficult?": "",
    "Do you need it right now?": "",
    "Is your brother in hospital?": "",
    "They're in the United States": "",
    "We're very different": "",
    "Is it cloudy?": "",
    "Do her parents always take her?": "",
    "These results are terrible": "",
    "Does this lesson help you?": "",
    "Does that thing really interest you?": "",
    "He's my old friend": "",
    "Does she understand us?": "",
    "Is she a native speaker?": "",
    "Who is here?": "",
    "Who are all these people?": "",
    "When does this lesson usually start?": "",
    "Is the result good enough?": "",
    "Do you often go there?": "",
    "Why do they refuse to do it?": "",
    "Is your brother a professional sportsman?": "",
    "Why do you support them?": "",
    "Do these lessons really help?": "",
    "Am I right or not?": "",
    "Why are they still there?": "",
    "What does your brother do at work?": "",
    "Why are you so surprised?": "",
    "Why is your father so angry today?": "",
    "This thing isn't popular now": "",
    "Why does your best friend hate it?": "",
    "You expect this result": "",
    "All people know that money isn't everything": "",
    "I hope": "",
    "Is he your best friend?": "",
    "Where does she play this game?": "",
    "Her mother usually stays at home": "",
    "How well does your sister swim?": "",
    "Does it really work?": "",
    "Is all this money enough?": "",
    "Why is this detail so important?": "",
    "Does it interest you?": "",
    "Not at all": "",
    "He's my classmate": "",
    "Is your brother in bed?": "",
    "This idea is quite old": "",
    "All his lessons are free and I'm so happy": "",
    "It's boring": "",
    "How are these dishes?": "",
    "Are we far from this place?": "",
    "What does it mean?": "",
    "Is the news sad?": "",
    "His father is rich": "",
    "The book isn't expensive": "",
    "How is my new sweater?": "",
    "Are they right?": "",
    "Is this girl the best student?": "",
    "Where is our English teacher?": "",
    "The problem is small": "",
    "His partners aren't reliable": "",
    "When does he come home?": "",
    "Why do you learn English?": "",
    "You're in a difficult situation": "",
    "Their results are brilliant": "",
    "Is it in this area?": "",
    "Are they your colleagues?": "",
    "Does your friend have an interesting offer?": "",
    "I think differently": "",
    "I think another way": "",
    "Where is he from?": "",
    "He's from England": "",
    "Is she a businesswoman?": "",
    "They're our friends": "",
    "How are your relatives?": "",
    "Why are these clothes so cheap? ": "",
    "You're kind": "",
    "They aren't stupid": "",
    "They aren't silly": "",
    "They aren't foolish": "",
    "It's a foolish mistake": "",
    "You need to start a new playlist": "",
    "Is he a professional teacher?": "",
    "Do you often see her?": "",
    "I'm tired": "",
    "Is the video so funny?": "",
    "Does she like this subject?": "",
    "Does his parents believe in God?": "",
    "What do they sell there?": "",
    "Do we learn English effectively?": "",
    "Your lessons are really good": "",
    "Do you work or study?": "",
    "Does she live there?": "",
    "This information is enough": "",
    "My mother is in the bathroom": "",
    "Do these things interest you?": "",
    "Is it a dangerous place?": "",
    "I'm Russian": "",
    "How long is the way?": "",
    "His son is lazy": "",
    "They're in Great Britain": "",
    "They're in UK": "",
    "They're in the United Kingdom": "",
    "Does this result seem very good?": "",
    "What do you think about it?": "",
    "How often are they together?": "",
    "Does he do business?": "",
    "They're from America": "",
    "Is our knowledge enough?": "",
    "You're a good teacher": "",
    "It's a good idea": "",
    "It isn't cold": "",
    "It's warm": "",
    "His parents tell him everything": "",
    "It isn't a boring lesson": "",
    "Is it detail really so important?": "",
    "How much is it in that shop?": "",
    "How much does it cost in that shop?": "",
    "Why does your friend think so?": "",
    "Does that thing seem interesting?": "",
    "They aren't expensive": "",
    "Are these lessons really good?": "",
    "The boys aren't at school": "",
    "Does his house look expensive?": "",
    "Does your classmate run very fast?": "",
    "Do these boys remember it very well?": "",
    "Why are these things necessary?": "",
    "Do you usually come early?": "",
    "Is she a very talented actress?": "",
    "How are his lessons?": "",
    "He's my father": "",
    "Are all these houses new?": "",
    "Do they fully support you?": "",
    "How good are these lessons?": "",
    "These results seem good": "",
    "The woman isn't a manager": "",
    "This phrase isn't important": "",
    "Where is this place?": "",
    "Does he play the guitar?": "",
    "my sister is in bed": "",
    "Does it really help you?": "",
    "When does it usually happen?": "",
    "Do those things interest her?": "",
    "Is this thing really necessary?": "",
    "How does she say it?": "",
    "Do they want to try to do it?": "",
    "He's my boss": "",
    "It's an interesting offer"
    "Where does your father work?": "",
    "MY computer is new": "",
    "Are they very good workers?": "",
    "Why is it so?": "",
    "My boss is very busy": "",
    "The offer isn't interesting at all": "",
    "He isn't at school": "",
    "Is he wrong?": "",
    "Why does it seem strange?": "",
    "Why is your teacher so angry?": "",
    "Does she need to rent a flat?": "",
    "Does she need to rent an apartment?": "",
    "Their plan isn't so bad": "",
    "I'm not tired": "",
    "It's a big mistake": "",
    "Does she feel good?": "",
    "Does this story seem short?": "",
    "Do you live together?": "",
    "Are we near this place?": "",
    "Are you here?": "",
    "Do you live in Russia?": "",
    "His lifestyle isn't healthy": "",
    "style of life": "",
    "My best friend needs support now": "",
    "Why is it so easy?": "",
    "Is the manager experienced enough?": "",
    "It's good": "",
    "This place isn't dangerous": "",
    "How interesting is this movie?": "",
    "How does it seem to you?": "",
    "Who is in the garden?": "",
    "What do you see?": "",
    "Is it a sunny day?": "",
    "Do you speak English?": "",
    "Do you get 500 dollars a month?": "",
    "Is this sentence difficult?": "",
    "Is it sunny?": "",
    "Her mother doesn't work there": "",
    "She works in another place": "",
    "He's a professional teacher": "",
    "How do they get this money?": "",
    "They aren't rich": "",
    "They're poor": "",
    "Where does your brother study?": "",
    "Is he happy person?": "",
    "These result don't seem very good": "",
    "Where is the nearest supermarket?": "",
    "The story is so long": "",
    "Is your computer powerful?": "",
    "Does he read newspapers?": "",
    "How much is this toy?": "",
    "How much does this toy cost?": "",
    "Is this word new for you?": "",
    "Is it free or not?": "",
    "Who is this woman?": "",
    "The news isn't surprising at all": "",
    "Does she support this idea?": "",
    "It's easy": "",
    "Does their rest include it?": "",
    "Do his students feel progress?": "",
    "Do you do it professionally?": "",
    "Is he very successful?": "",
    "It's a difficult lesson": "",
    "It isn't a difficult lesson": "",
    "Is it a difficult lesson?": "",
    "The lesson is for strong students": "",
    "The lesson isn't for strong students": "",
    "Is the lesson for strong students?": "",
    "easy - weak": "",
    "It's his weak point": "",
    "It isn't his weak point": "",
    "Is it his weak point?": "",
    "It depends on him": "",
    "It doesn't depend on him": "",
    "Does it depend on him?": "",
    "They combine work and studies": "",
    "They don't combine work and studies": "",
    "Do they combine work and studies?": "",
    "His speech is full of mistakes": "",
    "His speech isn't full of mistakes": "",
    "Is his speech full of mistakes": "",
    "Is it cold outside?": "",
    "It's cold outside": "",
    "it isn't cold outside": "",
    "It's warm inside": "",
    "It isn't warm inside": "",
    "Is it warm inside": "",
    "This money is enough": "",
    "This money isn't enough": "",
    "Is this money enough?": "",
    # General Question / Special Question
    "He wants to know English perfectly for many reasons": "",
    "Does he want to know English perfectly for many reasons": "",
    "Who wants to know English perfectly?": "",
    "How does he want to know English?": "",
    "What does he want to do?": "",
    "Why does hes want to know English perfectly?": "",
    "What does he want to know?": "",
    "She goes to the gym three times a week": "",
    "Does she go to the gym three times a week?": "",
    "Where does she go three times a week?": "",
    "How often does she go to the gym?": "",
    "How many times a week does she go to the gym?": "",
    "My friend wants to discuss it tomorrow": "",
    "When does my friend want to discuss it?": "",
    "What does my friend want to discuss?": "",
    "It's five o'clock": "",
    "What time is it?": "",
    "What's the time?": "",
    "What time is it now?": "",
    "Is it right or not?": "",
    "How are you?": "",
    "His knowledge is really good": "",
    "How good is his knowledge?": "",
    "She wants to try to get this job": "",
    "What job does she want to try to get?": "",
    "Does she want to try to get this job?": "",
    "Who wants to try to get this job?": "",
    "What does she want to do?": "",
    "What does she want to try to do?": "",
    "What does she want to try to get?": "",
    # Past Simple
    # if it's a regular verb, we add 'ed'
    # Regular verbs   --   verb + ed
    "He worked too much": "",
    "He works too much": "",
    "She wanted to find a better job": "",
    # irregular verbs
    "He said ": "",
    # Future Simple
    # Will + verb
    "I'll - I will ": "",
    "I'll learn English with great pleasure": "",
    "We will reach the next level soon": "",
    "We'll reach the next leve soon": "",
    "You'll get what you want": "",
    "They'll lose the game": "",
    "He'll correct our mistakes": "",
    "She'll have better results": "",
    "It'll surprise you greatly": "",
    "I'll pack my clothes": "",
    "I'll translate this text": "",
    "We'll discuss it later": "",
    "We'll inform him soon": "",
    "You'll take the first place": "",
    "You'll need our help": "",
    "They'll explain everything soon": "",
    "They'll do the same things again and again": "",
    "He'll apologize for his behavior": "",
    "He'll do it anyway": "",
    "She'll introduce him to them": "",
    "she'll cancel the meeting": "",
    "It'll interest them": "",
    "It'll shock you": "",
    "My teacher will check my work tomorrow": "",
    "My colleague will answer the day after tomorrow": "",
    "My boss will leave the city quite soon": "",
    "My parents will return to New York next week": "",
    "My parents will come back to New York next year": "",
    "I hope I'll win in this tournament": "",
    "I'm sure it'll happen sooner of later": "",
    "I promise I'll keep my word": "",
    "I expect I'll improve my English greatly soon": "",
    "I'm absolutely sure I'll do it with your help": "",
    "I'm absolutely sure I'll do it with the help of this channel": "",
    "I'll call him": "",
    "I will not call him": "",
    "I won't call him": "",
    "I won't repeat the same mistakes": "",
    "We won't sign this contract": "",
    "You won't know all the truth": "",
    "I will be able to do it": "",
    "I won't be able to do it": "",
    "They won't be able to win": "",
    "He won't support them": "",
    "She won't deny this fact": "",
    "It won't change my decision": "",
    # won't + verb
    "It won't help you much": "",
    "You'll only waste time": "",
    "He won't get this parcel next week": "",
    "He'll get it later": "",
    "I won't see him tomorrow": "",
    "He'll stay at home": "",
    "You won't learn 3000 English words in one day": "",
    "In two days": "",
    "In a week": "",
    "In a month": "",
    "It's impossible": "",
    "I think you won't learn it in 10 days": "",
    "I won't translate this text": "",
    "I don't need it": "",
    "You won't find an answer to this question immediately": "",
    "You'll need more time": "",
    "You won't find a solution to this problem immediately": "",
    "one hundred": "",
    "He won't take the first place but i think he'll take the second place": "",
    "She won't change her job this year": "",
    "I think she'll do it next year": "",
    "I won't send her a letter tomorrow": "",
    "I'll do it the day after tomorrow": "",
    "I won't work on my reading skills": "",
    "I'll work on my listening skills and grammar first of all": "",
    "I won't learn English little": "",
    "I'll learn English very hard to have a good level": "",
    "I want to speak English fluently": "",
    "It's my dream": "",
    # Will you do it?
    #  Will it be interesting?
    # will + subject + verb ?
    "Will I reach the next level soon?": "",
    "Will we continue working on this project?": "",
    "Will you need our help?": "",
    "Will they vote for him?": "",
    "Will he take part in the election?": "",
    "participate": "",
    "Will he show outstanding results?": "",
    "Will it bring good results?": "",
    "Will I improve my speaking?": "",
    "Will I be able to speak English without any mistakes at all?": "",
    "I will be able": "",
    "Will I show excellent results?": "",
    "Will we pay less money?": "",
    "Will we be able to pass the exam?": "",
    "Will we develop our skills there?": "",
    "Will you have one more offer?": "",
    "Will you lend him this sum of money?": "",
    "Will you stop doing it?": "",
    "Will they take part in this championship?": "",
    "Will they fully support us?": "",
    "Will they change their decision?": "",
    "Will he refuse to sell these goods?": "",
    "Will he be against this decision?": "",
    "Will he create a new channel?": "",
    "Will she explain how it works?": "",
    "Will she express her point of view?": "",
    "Will she share her secrets with us?": "",
    "Will it happen to our company?": "",
    "Will it lead to new problems?": "",
    "Will it be a big loss?": "",
    "Will my grammar be better?": "",
    "Will this course improve my English?": "",
    "Will this book become popular?": "",
    "Will the government support this project?": "",
    "Will your parents travel around the world?": "",
    # Future Simple Special Question
    # SQ + will + subject + verb
    "Why will you start learning English so intensively?": "",
    "Why will you go to that party together?": "",
    "Why will it be sensation?": "",
    "Why will they lose?": "",
    "How will you manage to cope with this problem?": "",
    "How will you learn English?": "",
    "How will hou work from home?": "",
    "What will you do in the end?": "",
    "What will happen if you don't change your decision?": "",
    "When will you visit your grandmother?": "",
    "When will you be free?": "",
    "When will he be busy?": "",
    "Which mistake will be more serious?": "",
    "Which answer will be correct?": "",
    "Who will take part in this competition?": "",
    "Who will disagree with this statement?": "",
    "Who will tell us all the truth?": "",
    "What books will you read in English?": "",
    "What channels will you watch?": "",
    "What skills will you start improving first of all?": "",
    "How much will you spend?": "",
    "How much money will you spend?": "",
    "How much will it cost?": "",
    "How many call will you be able to make?": "",
    "How many calls will you manage to make?": "",
    "How often will you go the gym?": "",
    "How long will our lesson be?": "",
    "How long will our lesson last?": "",
    # Future Simple - will + verb
    # I'll , We'll ...
    "I'll write it down": "",
    "I'll write it": "",
    "We'll try to understand what to do": "",
    "You'll need more time to find a better job": "",
    "He'll watch this video one more time": "",
    "She'll be with us": "",
    "They'll only laugh": "",
    "It'll help you greatly": "",
    "It'll help you a lot": "",
    "I won't worry about this problem": "",
    "We won't say such things": "",
    "You won't have this problem again": "",
    "They won't manage to solve this task": "",
    "manage to do something": "",
    "They won't be able to solve this tack": "",
    "I won't be able to do it": "",
    "I'll be able to do it": "",
    "He won't be able to show the best results": "",
    "She won't study in such a bad place": "",
    "It won't change anything": "",
    # will subject + verb ?
    "to be able to do something": "",
    "Will I be able to take the first place?": "",
    "Will we be able to double our income?": "",
    "Will you manage to find new clients?": "",
    "Will they play honestly?": "",
    "Will he be successful?": "",
    "Will she become famous or not?": "",
    "Will it be such a successful project?": "",
    # SQ + will + subject + verb
    "Why will it happen to our country soon?": "",
    "When will you be proud of your results?": "",
    "to be proud of something / someone": "",
    "How will you manage to solve such a difficult problem?": "",
    "Where will you spend this weekend?": "",
    "Who will continue working in an international company?": "",
    "Who will continue working for international company?": "",
    "What changes will we need?": "",
    "How much money will you be able to spend on it?": "",
    "How many calls will you make?": "",
    "You won't find a solution to this problem immediately": "",
    "What will you do in the end?": "",
    "How difficult will the test be?": "",
    "They'll do the same things again and again": "",
    "She won't study in such a bad place": "",
    "You won't have this problem again": "",
    "Will they fully support us?": "",
    "Who will do the same?": "",
    "I'll translate this text": "",
    "I'll learn English": "",
    "Will he refuse to sell it?": "",
    "Will she share her secrets with us?": "",
    "What work will he be able to do?": "",
    "I'll do this work": "",
    "I have a job": "",
    "How much will it be?": "",
    "How much will it cost?": "",
    "Will this channel become popular?": "",
    "She'll correct these mistakes": "",
    "My colleagues will inform our boss": "",
    "We won't sign this contract": "",
    "I'll win in this tournament": "",
    "He'll help you with great pleasure": "",
    "Will they supply these goods?": "",
    "What choice will she make?": "",
    "When will she express her point of view?": "",
    "She'll have better results": "",
    "I think he'll take the second place": "",
    "He won't say such things": "",
    "Will it lead to new problems?": "",
    "Will I be able to show the best result?": "",
    "When will you be absent?": "",
    "What will she do if he doesn't lend her money?": "",
    "What skills will you start improving first of all": "",
    "When will you be proud of your results?": "",
    "Why will they lose?": "",
    "This news will surprise you greatly": "",
    "Why will he start discussing it again?": "",
    "We'll reach a new level soon": "",
    "He'll explain all the details": "",
    "He won't be able to show the best result": "",
    "Will they pay less money?": "",
    "When will I be able to speak English without any mistakes at all": "",
    "Will we continue working on this project?": "",
    "She'll introduce him to them": "",
    "She'll reach the next level soon": "",
    "Will he refuse to pay?": "",
    "Why will he refuse to help us?": "",
    "How will you learn English?": "",
    "Will you need our help?": "",
    "They'll only laugh": "",
    "You won't learn 3000 English words in one day": "",
    "It's impossible": "",
    "It isn't possible": "",
    "I think you'll learn it in 10 days": "",
    "What books will you read in English?": "",
    "I hope he won't repeat this mistake": "",
    "I won't see him tomorrow": "",
    "He'll stay at home": "",
    "You'll take the first place": "",
    "They know he won't win but he'll try to do it anyway": "",
    "Why will you go to that party together?": "",
    "How will you manage to cope with this problem?": "",
    "Will she show outstanding results?": "",
    "I won't worry about this problem": "",
    "She won't be disappointed": "",
    "Everything will be OK": "",
    "alright - fine": "",
    "Will I be able to speak English fluently without any mistakes at all?": "",
    "Who will disagree with this statement?": "",
    "It won't help your business": "",
    "Will he create new videos for us?": "",
    "Will he have one more offer?": "",
    "How will we know the truth?": "",
    "How many calls will you be able to make?": "",
    "Will he be against this decision?": "",
    "Will you work from home?": "",
    "They'll explain everything soon": "",
    "Wil they change their decision?": "",
    "Will they pay us more money?": "",
    "I won't work on my reading skills": "",
    "I'll work on my listening skills and grammar first of all": "",
    "Will you need our advise?": "",
    "It'll interest them": "",
    "It won't change anything": "",
    "How long will the meeting last?": "",
    "Why will you start doing it tomorrow?": "",
    "I won't translate this text": "",
    "I don't need it": "",
    "How will it happen?": "",
    "Her progress will be very slow if she doesn't change anything": "",
    "How long will the lesson last?": "",
    "She won't be able to come to the party": "",
    "It won't help you much": "",
    "You'll only waste time": "",
    "Who will also support this plan?": "",
    "How many messages will you send?": "",
    "How will you manage to solve such a serious problem?": "",
    "Will he have the best results?": "",
    "Will they vote against it?": "",
    "How easy will the exam be?": "",
    "I'll join you with great pleasure": "",
    "Will it help us to get more experience?": "",
    "What will happen if she refuses": "",
    "Will it be such a successful project?": "",
    "Who will take part in this competition?": "",
    "He'll apologize for his behavior": "",
    "I'll learn English very hard to have a good level": "",
    "She won't take new students": "",
    "She'll be very busy": "",
    "He'll correct our mistakes": "",
    "Will it help you improve your level?": "",
    "It won't work": "",
    "It won't improve your grammar": "",
    "It'll improve only your reading skills": "",
    "I want to tell you the following": "",
    "This exam will be very difficult": "",
    "If you had a high per cent in these lessons": "",
    "It doesn't mean that you'll show an excellent result": "",
    "Why do i think so?": "",
    "You need to revise everything and know it very well": "",
    "If you don't do it": "",
    "You'll be disappointed": "",
    "You'll see different tenses, words, phrases, structures, exceptions and lots of different aspects of grammar in one test": "",
    "I hope you remember how you worked with these lessons": "",
    "You watched several lessons and then you had on exam": "",
    "It was more difficult because you saw different rules in it": "",
    "It was more difficult for you to remember everything": "",
    "I think you were in this situation": "",
    "You got 90% in the first lesson": "",
    "91% in the second lesson 95 % in the third lesson": "",
    "Then you had an exam where you saw exercises witch were in all these lessons and your result wasn't good enough": "",
    "It was more difficult to remember all those rules": "",
    "You're in a similar situation now": "",
    "You need to remember everything": "",
    "My recommendation is the following": "",
    "You need to watch these lessons one more time": "",
    "It will be easy for you but it's very good for your knowledge revision and progress in general": "",
    "If you make a mistakes, fix it": "",
    "Take notes and look at it from time to time to refresh it in your memory": "",
    "Only this way": "",
    "You need to work on your mistakes and weak points": "",
    "You need to focus on": "",
    "tenses (present simple, past simple, future simple different cases)": "",
    "grammar structures(need , want ,  be able, manage, ing - verb and so on": "",
    "new words and phrases": "",
    "You need to prepare": "",
    "If you prepare well": "",
    "I'm sure you'll show a better result": "",
    "Practice makes perfect": "",
    "if you want to show a better result or if you don't want to be disappointed": "",
    "do these exercises one more time": "",
    "You'll feel real progress and It'll help you revise your knowledge": "",
    # Present Simple
    # When we have a verb
    # verb , verb + s
    "I learn English with great pleasure": "",
    "She learns ...": "",
    "I go to that place from time to time": "",
    "She goes to that place ...": "",
    "I have a brilliant idea": "",
    "She has an interesting idea": "",
    # don't / he/she/it doesn't want to do it
    # do / does he/ she/ it ...?
    "Does she feel happy?": "",
    # you don't have a verb
    # I am he/she/it is - we/you/they are
    "It is boring": "",
    "The lessons are boring and ineffective but these lessons are really good": "",
    # I'm not we/you/they aren't; he/she/it isn't
    "It's rainy": "",
    "It isn't rainy": "",
    "The method isn't effective": "",
    "It isn't sunny": "",
    # Am I - Is he/she/it is - are we/you/they
    "Is he a popular singer?": "",
    "Is the book popular?": "",
    "She lives in New York": "",
    "She doesn't live in New York": "",
    "Does she live in New York?": "",
    "These materials are useful": "",
    "These materials aren't useful": "",
    "Are these materials useful?": "",
    # Special Question
    # SQ + do / does + subject + verb?
    "Why do you learn English?": "",
    # SQ + am/is/are + subject?
    "Where is this place?": "",
    "Who knows it?": "",
    "Who do you recommend?": "",
    "What is it?": "",
    "What do you know?": "",
    "What helps you?": "",
    # Past Simple - we use the second form English verbs can be
    # regular
    # irregular
    "We have two cases / situations": "",
    "When we have a verb ( bur not ' to be _": "",
    "When we have the verb 'to be' -was /were": "",
    # + the second form
    "We walked in the park": "",
    "She let him play computer games": "",
    "let somebody do something": "",
    # didn't + verb
    "He didn't apologize for his behavior": "",
    # Did + subject + verb?
    "Did he come there on time?": "",
    # the second form
    # I/he/she/it was; were
    "It was an excellent result": "",
    "They were really happy together": "",
    "The test was too difficult": "",
    # wasn't weren't
    "I wasn't disappointed at all": "",
    # Was / were + subject... ?
    "Was it the best result?": "",
    "to be tired": "",
    "were they tired?": "",
    "They were tired": "",
    # Special Question
    # verb ( but not 'to be')
    # SQ + did + subject + verb?
    "Where did you go yesterday?": "",
    "How did it happen?": "",
    "It takes me 20 minutes to get to work": "",
    "How long did it take you to get to work?": "",
    # to be - was / were
    # SQ + was / were + subject
    "Where were you yesterday?": "",
    "How was the party?": "",
    "How difficult was the test?": "",
    # Future Simple
    # will + verb
    "I'll do it": "",
    "I'll / We'll / You'll / They'll / She'll / He'll / It'll": "",
    "He will join us with great pleasure": "",
    "I'll speak English fluently and correctly": "",
    "This business will be successful": "",
    # will not - won't + verb
    "I won't take this offer": "",
    "She won't agree to try to do it": "",
    "His business partner will refuse to invest this money": "",
    # will + subject + verb ...?
    "Will you continue creating new videos for us?": "",
    "Will it be a big success?": "",
    "I don't know": "",
    "It depends on you": "",
    "If you support it": "",
    "I'll do it": "",
    "If you don't support it": "",
    "I won't do it": "",
    "If not": "",
    "He'll arrive late": "",
    "He won't arrive late": "",
    "Will he arrive late?": "",
    "It will be such a big mistake": "",
    "It won't be such a big mistake": "",
    "Will it be such a big mistake?": "",
    # Special Question
    # SQ + will + Subject + verb?
    "When will it happen?": "",
    "When will you return?": "",
    "When will you come back?": "",
    "When will I stop making mistakes?": "",
    "Stop doing": "",
    "Stop to do": "",
    "I stopped to greet him": "",
    "I stopped to ask him a question": "",
    "I stopped asking him questions": "",
    # Present Simple, Past Simple, Future
    "It's a big success": "",
    "It isn't a big success": "",
    "Is it a big success?": "",
    "It was a big success": "",
    "It wasn't a big success": "",
    "Was it a big success?": "",
    "It will be a big success": "",
    "It won't be a big success": "",
    "Will it be a big success?": "",
    "The lessons are boring": "",
    "The lessons aren't boring": "",
    "Are the lessons boring?": "",
    "The lessons were boring": "",
    "The lessons weren't boring": "",
    "Were the lessons boring": "",
    "The lessons will be boring": "",
    "The lessons won't be boring": "",
    "Will the lessons be boring?": "",
    "He shows good results": "",
    "He doesn't show good results": "",
    "Does he show good results?": "",
    "He showed good results": "",
    "He didn't show good results": "",
    "Did he show good results?": "",
    "He'll show good results": "",
    "He won't show good results": "",
    "Will he show good results?": "",
    "How much does it cost?": "",
    # Question word + do / does + subject + verb
    "": "",
    "": "",
    # SQ + am/is/are + S ...?
    "How much is it?": "",
    "": "",
    "": "",
    #  Question word + did + subject + verb
    "How much did it cost?": "",
    "": "",
    "": "",
    #  Question word + was/were+ subject + verb
    "": "",
    "": "",
    # Future Simple
    #  Question word + will + subject + verb?
    "How much wil it cost?": "",
    "": "",
    #  Question word + will + subject + be?
    "How much will it be?": "",
    "": "",
    "Why does he live in New York?": "",
    "Why did he live in New York?": "",
    "Why will he live in New York?": "",
    "Why is this lesson useful?": "",
    "Why was this lesson useful?": "",
    "Why will this lesson be useful?": "",
    "manage to do something": "",
    "be able to do something": "",
    # Present Simple
    # Past Simple
    # Future Simple
    # Present Continuous(now , at the moment)
    # am/is/are + verb + ing
    # I'm ; We're ; You're ; They're ; He's ; She's ; It's + verb + ing
    "It's easy": "",
    "It's happening now": "",
    "I'm listening to you": "",
    "I'm watching this video": "",
    "I'm looking at you": "",
    "I'm recording this lesson": "",
    "I work(in general) - I have a job": "",
    "I'm working(now) - I'm busy": "",
    "We're waiting for you": "",
    "You're making progress": "",
    "They're laughing at them": "",
    "He's watching this video": "",
    "She's reading a book": "",
    "get dark": "",
    "It's getting dark": "",
    "I'm talking on the phone now": "",
    "I'm trying to solve this problem now": "",
    "I'm doing physical exercises": "",
    "We're considering your offer": "",
    "We're experiencing big problems": "",
    "We're thinking about it": "",
    "You're saying very interesting things": "",
    "You're speaking English without mistakes": "",
    "You're making progress": "",
    "Look! They're playing football": "",
    "They're playing chess": "",
    "He's leaving": "",
    "He's explaining the meaning of this phrase": "",
    "He explains difficult things very easily simply": "",
    "He's working on this project": "",
    "He's waiting for our decision": "",
    "She's teaching Spanish": "",
    "She's feeding the children": "",
    "She's expressing her opinion": "",
    "It's getting dark": "",
    "It's getting late": "",
    "rain": "",
    "show": "",
    "It's raining": "",
    "It's snowing": "",
    "compare": "",

}