slovar = {
    "Is the lesson very informative?": "",
    "Is the video so funny?": "",
    "Are the boys poor?": "",
    "Are the girls rich?": "",
    "His salary is quite high": "",
    "His salary is high enough": "",
    "Enough!": "",
    "This money is enough": "",
    "It is enough": "",
    "Thanks!": "",
    "It's your turn": "",
    "Are the lessons free?": "",
    "Is your bother in bed?": "",
    "Are your relatives in America?": "",
    "Is your sister in hospital?": "",
    "Is this money enough?": "",
    "Are his ideas the same?": "",
    "Is this thing really necessary?": "",
    "Is this thing really so important?": "",
    "Is his level high enough?": "",
    "Are these exercises useful?": "",
    "Is the video rally useful?": "",
    "Is the boy really so talented?": "",
    "Is that exercises difficult?": "",
    "Is the book boring?": "",
    "Are those exercises useless?": "",
    "Are your colleagues very professional?": "",
    "Is his girlfriend American?": "",
    "I'm Russian": "",
    "Are the girls rich?": "",
    "Is the news sad?": "",
    "Is his son very lazy?": "",
    "Are your ideas similar?": "",
    "Is this girl the best student?": "",
    "Are your parents at home?": "",
    "Is your cousin at the airport?": "",
    "Are the girls with a teacher?": "",
    "Is this information reliable?": "",
    "Is the computer expensive?": "",
    "Are the boys busy at the moment?": "",
    "Is this school good enough?": "",
    "Are these methods traditional?": "",
    "Is the lesson free?": "",
    "Is your brother a professional sportsman?": "",
    "Is the chair comfortable?": "",
    "Is the progress slow?": "",
    "Is the result good enough?": "",
    "Is your computer so powerful?": "",
    "Is his father rich?": "",
    "Is this hotel so expensive?": "",
    "Is the father a businessman?": "",
    "Is this exercise easy?": "",
    "Is his father a rich man?": "",
    "Is your classmate ill?": "",
    "Is your husband at work?": "",
    "Is his mother a businesswoman?": "",
    "Is this detail important?": "",
    "Is our knowledge enough?": "",
    "Is the ticket expensive?": "",
    "Is your brother a freelancer?": "",
    "Is this subject so important?": "",
    "Are these lessons really effective?": "",
    "Is her boyfriend Russian?": "",
    "Is his method different?": "",
    "Is this teacher really so experienced?": "",
    "Is their mother a housewife?": "",
    "Is the movie so funny?": "",
    "Is the lesson very informative?": "",
    "Is this word new for you?": "",
    "Are the results satisfactory?": "",
    "Is your brother in the bathroom?": "",
    "Is your wife at home?": "",
    "Is her daughter very hard-working?": "",
    "Are his lessons really effective?": "",
    "Is this level basic?": "",
    "Is this story long?": "",
    "Is our boss very busy now?": "",
    "Is your boss a difficult person?": "",
    "Is his father angry?": "",
    "Are these recommendations good?": "",
    "Are our friends there?": "",
    "Is his girlfriend very emotional?": "",
    "Is their offer so interesting?": "",
    "Is your mother in the kitchen?": "",
    "Are the boys poor?": "",
    "Is your friend tired?": "",
    "Is this manager experienced enough?": "",
    "Are all these videos really useful?": "",
    "Of course": "",
    "Certainly": "",
    "Sure": "",
    # I'm :  we you they're he she it's
    "I'm a sales manager": "",
    "We're in one group": "",
    "You're in one team": "",
    "They're independent": "",
    "He's an outstanding person": "",
    "She's our special guest": "",
    "It's very unusual": "",
    "This thing is strange": "",
    "The result is good enough": "",
    "The results are brilliant": "",
    "The news is shocking": "",
    "Knowledge is power": "",
    "This money is enough": "",
    "I'm not surprised at all": "",
    "We aren't tired of these things": "",
    "you aren't happy": "",
    "They aren't professional workers": "",
    "He isn't available at the moment": "",
    "She isn't afraid of difficulties": "",
    "The boys aren't at school": "",
    "The offer isn't interesting enough": "",
    "Our results aren't good enough": "",
    "This idea isn't new": "",
    "Money isn't everything": "",
    "Am i the best student?": "",
    "Are we in the right place?": "",
    "Are you angry?": "",
    "Are they surprised?": "",
    "Is he tall?": "",
    "Is he an experienced lawyer?": "",
    "Is it his idea?": "",
    "Is this singer very popular?": "",
    "Are your colleagues very friendly?": "",
    "Are Their ideas the same?": "",
    "Is this hotel good enough?": "",
    "Are these lessons really so effective?": "",
    "of course sure certainly": "",
    "He's my boss": "",
    "They're in the United States": "",
    "We're busy now": "",
    "This thing isn't popular now": "",
    "Is it a good plan?": "",
    "My father is there": "",
    "They're in Great Britain": "",
    "They're in the United Kingdom": "",
    "He's a professional teacher": "",
    "It's a good lesson": "",
    "My boss is very busy": "",
    "It's cloudy": "",
    "My friend is 25 years old": "",
    "My relatives in America": "",
    "Are you here?": "",
    "The lesson is boring": "",
    "Are they serious people?": "",
    "It isn't an expensive thing": "",
    "It isn't windy": "",
    "She's a housewife": "",
    "Are they strange people?": "",
    "He isn't an angry person": "",
    "My progress is real": "",
    "I want ro speak English naturally": "",
    "She's beautiful": "",
    "You're a good teacher": "",
    "He's a good person": "",
    "It's in my flat": "",
    "Are you together?": "",
    "Her ideas are interesting": "",
    "He's a director": "",
    "The books aren't cheap": "",
    "Are you there?": "",
    "Is your mother a housewife?": "",
    "Is it a sunny day?": "",
    "Is this thing really so important?": "",
    "Are you in his office?": "",
    "It isn't in America": "",
    "It's in China": "",
    "It's a bad idea": "",
    "It's an interesting offer": "",
    "Is he busy at the moment?": "",
    "He's the best teacher in the world": "",
    "English is easy": "",
    "He's a designer": "",
    "It's an important detail": "",
    "That book isn't short": "",
    "They're from America": "",
    "I'm a manager": "",
    "Their results are brilliant": "",
    "She's tired": "",
    "Is your father a businessman?": "",
    "It's in our country": "",
    "The offer is so interesting": "",
    "Is he wrong?": "",
    "They're talented students": "",
    "This idea is new": "",
    "Is he a talented student?": "",
    "This information is enough": "",
    "Your lesson is very informative": "",
    "Are you a designer?": "",
    "It's an excellent result": "",
    "My result isn't so bad": "",
    "We aren't students": "",
    "It's so interesting": "",
    "You're kind": "",
    "Is the chair comfortable?": "",
    "Is all this money enough?": "",
    "It's on the right": "",
    "These words aren't important": "",
    "My computer is very powerful": "",
    "Is it rainy?": "",
    "The book isn't expensive": "",
    "It's a good exercise": "",
    "Really, It's a good training": "",
    "Is he a popular singer?": "",
    "It isn't an interesting book": "",
    "This idea isn't new": "",
    "These exercises are so useful": "",
    "Their problems aren't small": "",
    "Is she an actress?": "",
    "This building is very high": "",
    "It's important": "",
    "I think it's a good result": "",
    "They're students": "",
    "Is it an effective lesson?": "",
    "The key is on the table": "",
    "Is your brother in hospital?": "",
    "I'm not hungry": "",
    "The tickets are cheap": "",
    "I'm not American": "",
    "I'm Russian": "",
    "This exercises isn't difficult": "",
    "These things aren't so important": "",
    "It's so difficult": "",
    "They're in Russia": "",
    "Is your classmate ill?": "",
    "Is it in this area?": "",
    "The book isn't so cheap": "",
    "Is it a strange thing?": "",
    "The hotel is expensive": "",
    "Are they wrong?": "",
    "My boss isn't at work": "",
    "We aren't friends and we aren't enemies": "",
    "I'm right": "",
    "I'm not right": "",
    "Am i right": "",
    "We're sure(certain)": "",
    "We aren't sure": "",
    "Are we sure?": "",
    "You're near the park": "",
    "You aren't near the park": "",
    "Are you near the park?": "",
    "They're in a safe place": "",
    "They aren't in a safe place": "",
    "Are they in a safe place?": "",
    "He's an expert in this area": "",
    "He isn't an expert in this area": "",
    "Is he an expert in this area?": "",
    "She's a native speaker": "",
    "She isn't a native speaker": "",
    "Is she a native speaker?": "",
    "It's the best decision": "",
    "It isn't the best decision": "",
    "Is it the best decision?": "",
    "The rule is very important": "",
    "The rule isn't very important": "",
    "Is the rule very important?": "",
    "The phrases are very common(popular)": "",
    "The phrases aren't very common": "",
    "Are the phrases very common?": "",
    "His English is fluent": "",
    "His English isn't fluent": "",
    "Is his English fluent?": "",
    "The news is strange": "",
    "The news isn't strange": "",
    "Is the news strange?": "",
    "Our knowledge is enough": "",
    "Our knowledge isn't enough": "",
    "Is our knowledge enough?": "",
    "His sister is 17": "",
    "His sister isn't 17": "",
    "Is his sister 17?": "",
    "His friend is married": "",
    "His friend isn't married": "",
    "Is his friend married?": "",
    "Thank you": "",
    "My result(per cent)": "",
    "It doesn't satisfy you": "",
    "and it isn't acceptable for me": "",
    "and it isn't acceptable for my progress": "",
    "How does he look like?": "",
    "What's his appearance?": "",
    "method - methods": "",
    "Kate's car is very comfortable": "",
    "They really help me": "",
    "They're really helpful": "",
    "to make my dream come true": "",
    "This idea isn't new": "",
    "It's an old idea": "",
    "My mother is a doctor": "",
    "Is it very important?": "",
    "Your lessons are really good": "",
    "Her way of life isn't healthy": "",
    "He's my father": "",
    "This information is useless": "",
    "It isn't difficult": "",
    "It isn't hard": "",
    "The book is in the kitchen": "",
    "The book is boring": "",
    "These things aren't popular now": "",
    "It's my new car": "",
    "Is your computer powerful?": "",
    "Are they your colleagues?": "",
    "I'm in my room": "",
    "Am I a good student?": "",
    "My friends aren't in Moscow": "",
    "Is the video really useful?": "",
    "My parents aren't in the park": "",
    "Is it a cheap thing?": "",
    "My mother is in the bathroom": "",
    "Are they managers?": "",
    "Is it a new project?": "",
    "It isn't a bad idea": "",
    "My best friend is a businessman": "",
    "The story isn't long": "",
    "Is this girl the best student?": "",
    "That money isn't enough": "",
    "Are your ideas similar?": "",
    "That exercise is too easy": "",
    "Is this word new for you?": "",
    "Is her boyfriend Russian?": "",
    "is it windy?": "",
    "It snows": "",
    "It rains": "",
    "It's snowy": "",
    "It's rainy": "",
    "This house is new": "",
    "This place isn't dangerous": "",
    "Is this school good enough?": "",
    "Are all these videos really useful?": "",
    "Is it easy or difficult?": "",
    "His life isn't easy": "",
    "Is he reliable enough?": "",
    "His son is lazy": "",
    "He's American": "",
    "Those exercises are useless": "",
    "I'm not from Canada": "",
    "I'm from the United States": "",
    "Are they very good workers?": "",
    "It's on the chair": "",
    "Is it a powerful computer?": "",
    "My partner isn't afraid of difficulties": "",
    "Is your wife at home?": "",
    "It's a small mistake": "",
    "Is the ticket expensive?": "",
    "Is his father rich?": "",
    "She's his daughter": "",
    "Is it interesting or boring?": "",
    "We are inside": "",
    "The book is red": "",
    "Is she a teacher?": "",
    "This room is small": "",
    "Is she a famous actress or not?": "",
    "She's 25": "",
    "Is the video so funny?": "",
    "The girl is beautiful": "",
    "You aren't happy": "",
    "These results are wonderful / brilliant / excellent / amazing / surprising / unexpected!": "",
    "Are his ideas the same?": "",
    "Is it sunny?": "",
    "He isn't at school": "",
    "Is he a hard-working person?": "",
    "It isn't a boring movie": "",
    "Is you husband at work?": "",
    "It's a good idea": "",
    "He isn't a businessman": "",
    "He's a manager": "",
    "Are they experienced?": "",
    "We're in the park now": "",
    "Is he a businessman or an employee?": "",
    "Are all these houses new?": "",
    "Is our boss very busy now?": "",
    "I'm tired": "",
    "It's a difficult thing": "",
    "You aren't right": "",
    "You're wrong": "",
    "These results are terrible": "",
    "I'm not surprised at all": "",
    "Their plan isn't so bad": "",
    "Her daughter is very hard-working": "",
    "Is he a happy person?": "",
    "It isn't far": "",
    "Is his son lazy?": "",
    "Is it an innovative idea?": "",
    "Our results aren't good enough": "",
    "The result isn't good enough": "",
    "The boys aren't at school": "",
    "They aren't partners": "",
    "They are only friends": "",
    "Is this lesson very informative?": "",
    "We aren't classmates": "",
    "This idea is quite old": "",
    "money isn't everything": "",
    "She's in America": "",
    "His flat is quite small": "",
    "He isn't rich": "",
    "Is this level basic?": "",
    "It isn't sunny": "",
    "This job isn't well-paid": "",
    "Is he your best friend?": "",
    "Is your cousin at the airport>?": "",
    "I think our results aren't good enough": "",
    "Are the results satisfactory?": "",
    "These students are so talented": "",
    "It isn't free": "",
    "You need to pay": "",
    "His partners aren't reliable": "",
    "Are they just friends?": "",
    "She thinks her result isn't good enough": "",
    "It's an easy exam": "",
    "It isn't the best choice": "",
    "The tests in this book aren't easy": "",
    "It's a short phrase": "",
    "I'm sure all these lessons are very useful": "",
    "Is he your boss?": "",
    "It's on the left": "",
    "It's his old car": "",
    "Is your brother a professional sportsman?": "",
    "The manager is very strange": "",
    "We aren't at home": "",
    "We're in the park": "",
    "Are we in the right place?": "",
    "Are your parents at home?": "",
    "It's too long": "",
    "It's an interesting thing": "",
    "Are they professional workers?": "",
    "Is it cloudy?": "",
    "I'm not at home": "",
    "I'm at work": "",
    "Is she your acquaintance?": "",
    "Are they good specialists?": "",
    "She's a manager": "",
    "Is it effective?": "",
    "It's really difficult": "",
    "It's a big mistake": "",
    "My sister is in bed": "",
    "It's too short": "",
    "All those houses are old": "",
    "Is his father angry?": "",
    "They're our friends": "",
    "He's a talented student": "",
    "He's my classmate": "",
    "Her boyfriend isn't there": "",
    "My cousin is tired": "",
    "It's so bad": "",
    "Their ideas aren't innovative": "",
    "Are you afraid of difficulties?": "",
    "Is your brother in bed?": "",
    "I'm American": "",
    "Is that exercise difficult?": "",
    "Is it a dangerous place?": "",
    "Are your colleagues very professional?": "",
    "The story is so long": "",
    "Is the progress slow?": "",
    "It's normal": "",
    "Is it a rainy day?": "",
    "His English isn't fluent": "",
    "His progress isn't good enough": "",
    "Are the boys busy at the moment?": "",
    "It's a very good lesson": "",
    "All his lessons are free": "",
    "Is it a warm day?": "",
    "Are we far from this place?": "",
    "It's good": "",
    "Is it very effective?": "",
    "Is this thing really necessary?": "",
    "Is this detail important?": "",
    "Are you in this hotel?": "",
    "The lesson is interesting": "",
    "She isn't American": "",
    "Is their offer so interesting?": "",
    "Is she a very talented actress?": "",
    "He isn't a rich person": "",
    "He's the best student": "",
    "My friend is ill": "",
    "The problem isn't big": "",
    "Is your friend tired?": "",
    "Is the manager experienced enough?": "",
    "Is our knowledge enough?": "",
    "Is he a successful businessman?": "",
    "She isn't a designer": "",
    "She's a doctor": "",
    "Is his lesson really so effective?": "",
    "My computer is new": "",
    "Is it a popular channel?": "",
    "Are we near this place?": "",
    "Is this exercise easy?": "",
    "Is he often angry?": "",
    "The lesson is difficult": "",
    "The test isn't easy": "",
    "This method is really effective": "",
    "My English teacher is very professional": "",
    "Those problems aren't big": "",
    "This phrase isn't important": "",
    "Are the boys poor?": "",
    "Are those exercises really useless?": "",
    "His father is rich": "",
    "Is it a well-paid job?": "",
    "My parents are angry": "",
    "Am I right or wrong?": "",
    "Am I right or not?": "",
    "Is this sentence interesting?": "",
    # Present simple special question
    # How? - Why? - When? - Where? - What? -Who?
    # Q + am/is/are ...?
    #
    "How are you?": "",
    "Why is she still there?": "",
    "When are they in the office?": "",
    "Where is the nearest supermarket? ": "",
    "What is it?": "",
    "Who is he?": "",
    "How much is it?": "",
    "How far is it?": "",
    "Where are you from?": "",
    "From where are you?": "",
    "Where are your from?": "",
    "I'm from Russia": "",
    "where is he From?": "",
    "He's from England": "",
    "How much is it?": "",
    "How mush does it cost?": "",
    "How is life?": "",
    "How is this project?": "",
    "How are his parents?": "",
    "Why are we here?": "",
    "Why is she so sure?": "",
    "Why is it so important?": "",
    "When is he at home?": "",
    "When are they together?": "",
    "When are you free?": "",
    "Where is the nearest hotel?": "",
    "Where is this place?": "",
    "Where are my keys?": "",
    "What is in this box?": "",
    "What is in his head?": "",
    "What is there?": "",
    "Who is right?": "",
    "Who is present?": "",
    "Who is absent?": "",
    "Who knows it?": "",
    "Who likes it?": "",
    "Where is this place?": "",
    "How is it?": "",
    "Why is she afraid?": "",
    "How far is it?": "",
    "Where is your car?": "",
    "Who is present?": "",
    "What is in the box?": "",
    "Who is at work?": "",
    "How are his lessons": "",
    "Who is in the garden?": "",
    "How are his patients?": "",
    "Where are you from?": "",
    "I'm from Russia": "",
    "Who are they?": "",
    "Who is outside?": "",
    "Who is right?": "",
    "When are they in the office?": "",
    "Who is inside?": "",
    "How much is it in that shop?": "",
    "Who is there?": "",
    "When is he at home?": "",
    "When are they together?": "",
    "What is in this box?": "",
    "Where is the nearest hotel?": "",
    "Who is absent today?": "",
    "How much is it in this shop?": "",
    "What is it?": "",
    "What is there?": "",
    "Why is it so important?": "",
    "Why is it so easy?": "",
    "Why is she still there?": "",
    "Where is he from?": "",
    "He's from England": "",
    "How is the lesson?": "",
    "Where is your girlfriend?": "",
    "How are you?": "",
    "Where are your parents now?": "",
    "When are they busy?": "",
    "Who is he?": "",
    "Where is the nearest bank?": "",
    "What is there?": "",
    "Who is right?": "",
    "Who is present today?": "",
    "Where is the nearest supermarket?": "",
    "Who is at home?": "",
    "How much is it?": "",
    "Where are my keys?": "",
    "Who is wrong?": "",
    "Why is it so difficult?": "",
    "What is in your bag?": "",
    "How is this project?": "",
    "How are these videos?": "",
    "Why are we here?": "",
    "Why are they still there?": "",
    "Who is here?": "",
    "Where is this place?": "",
    "What is in his head?": "",
    "Where is she wife?": "",
    "Why are you still there?": "",
    "When are they free?": "",
    "Why is it free?": "",
    "Why are the lessons free?": "",
    "Why is it so?": "",
    "Why are you so sure that she's right?": "",
    "Where is my book?": "",
    "Where is my wallet?": "",
    # Special Question
    # Q + am/is/are....?
    # What / Where / How .... + am/is/are
    "Why is this offer so attractive?": "",
    "How is your cousin?": "",
    "Where are my mistakes?": "",
    "What is love?": "",
    "What is his idea?": "",
    "Who is this man?": "",
    "When are you tired?": "",
    "I'm tired": "",
    "Why is this detail so important?": "",
    "Why are these things necessary?": "",
    "Why is this level basic?": "",
    "Why are you so surprised?": "",
    "Why are your friends shocked?": "",
    "Why is your brother so tired?": "",
    "Why are your parents angry?": "",
    "Why are these topics boring?": "",
    "How is this dish?": "",
    "How is her new dress?": "",
    "How is my new suit?": "",
    "Where are these clothes?": "",
    "Where is our English teacher?": "",
    "Where is justice in the world?": "",
    "Where is his file?": "",
    "What is confidence?": "",
    "What is professionalism?": "",
    "What is in his bag?": "",
    "Who are all these people?": "",
    "Who is this guest?": "",
    "Who is free?": "",
    "When is your boss in this building?": "",
    "When is your mother angry?": "",
    "When is your father tired?": "",
    "How much is it?": "",
    "How much is this computer?": "",
    "How much are the tickets?": "",
    "How often is she late?": "",
    "be late": "",
    "How often is your boss late?": "",
    "How often are they together?": "",
    "How long is the way?": "",
    "How long is one English lesson?": "",
    "How cheap is it?": "",
    "How expensive is it?": "",
    "How popular is it?": "",
    "How much does it cost?": "",
    "How often does she come late": "",
    "How long is the lesson?": "",
    "How long does the lesson last?": "",
    "Where are you from?": "",
    "Where is he from?": "",
    "What books are interesting for you?": "",
    "Which book is more interesting?": "",
    "What YouTube channels are popular nowadays?": "",
    "What time is it?": "",
    "What's the time?": "",
    "What is this level?": "",
    "How expensive is it?": "",
    "When are you in our area?": "",
    "What magazines are popular now?": "",
    "Which book is more interesting?": "",
    "What is confidence when you speak English?": "",
    "Why are you so surprised?": "",
    "How long is the lesson?": "",
    "How good is this teacher?": "",
    "Who is your fitness trainer?": "",
    "Where is your instructor?": "",
    "What is free?": "",
    "How long is one English lesson?": "",
    "Who are you friends?": "",
    "Where are my mistakes?": "",
    "How interesting is this movie?": "",
    "How is your cousin?": "",
    "Why are these things necessary?": "",
    "What is success?": "",
    "When are you happy?": "",
    "How good is your memory?": "",
    "Where is this teacher from?": "",
    "What are your thoughts?": "",
    "When are you in this building?": "",
    "What is love?": "",
    "What is the meaning of this word?": "",
    "Why is it impossible?": "",
    "what's the meaning of this phrase?": "",
    "Who is your friend?": "",
    "Which website is better?": "",
    "What is happiness?": "",
    "How is my new sweater?": "",
    "When are these clothes?": "",
    "How are your relatives?": "",
    "How often are they together?": "",
    "Why is your teacher so angry?": "",
    "Why are you so angry?": "",
    "Who is this man?": "",
    "Why are they shocked?": "",
    "How much is this toy?": "",
    "How popular is it?": "",
    "Why is the suit so expensive?": "",
    "What books are interesting for you?": "",
    "Where is his friend from?": "",
    "How good are these lessons?": "",
    "How is her new dress?": "",
    "How cheap is it?": "",
    "What YouTube channels are popular nowadays?": "",
    "Why is this level basic?": "",
    "Why is this offer so attractive?": "",
    "Where is justice in the world?": "",
    "What is in his bag?": "",
    "When are you tired?": "",
    "How often is she late?": "",
    "Why are you so tired?": "",
    "What are my mistakes?": "",
    "How is your brother in American?": "",
    "What are his ideas?": "",
    "Why are these topics boring?": "",
    "What time is it?": "",
    "What's the time?": "",
    "What are your ideas?": "",
    "How much are the tickets?": "",
    "How much do the tickets cost?": "",
    "Who are all these people?": "",
    "Why is his offer so attractive?": "",
    "When is she angry?": "",
    "How is my new suit?": "",
    "When are you tired?": "",
    "How much is this computer?": "",
    "Who is this guest?": "",
    "How long is the video?": "",
    "Why are these clothes so cheap?": "",
    "Where is this file?": "",
    "Where are these documents?": "",
    "Why is this phrase so funny?": "",
    "What newspapers are interesting for you?": "",
    "How is this dish?": "",
    "How are these dishes?": "",
    "How long is the way?": "",
    "Why is this detail so important?": "",
    "Why is all this information so important?": "",
    "Where is our English teacher?": "",
    "Who is this woman?": "",
    "What is professionalism?": "",
    "We see it here": "",
    # Present simple(statement)
    # When we have a verb
    # I/we/you/they + verb
    # He/she/it + verb + s
    "I know the truth": "",
    "We often discuss it": "",
    "You expect this result": "",
    "They want more knowledge": "",
    "she thinks the same": "",
    "He disagrees with this statement": "",
    "It looks surprising": "",
    # When we don't have a verb
    # I'm we/you/they're he/she/it's
    "I'm in the garden": "",
    "We're very different": "",
    "You're in a difficult situation": "",
    "They're divorced": "",
    "He's a strange person": "",
    "She's the most beautiful girl in the world": "",
    "It's a bad idea": "",
    # When we have a verb (negative)
    #I/we/you/they don't + verb
    #He/she/it  doesn't + verb
    "I don't know the answer": "",
    "We don't think so": "",
    "You don't realize it": "",
    "They don't control the situation": "",
    "He doesn't do it": "",
    "She doesn't travel every year": "",
    "This thing doesn't seem strange": "",
    # When we don't have a verb (negative)
    # We/you/they aren't
    # i'm not
    # he/she/it isn't
    "i'm not at home": "",
    "we aren't satisfied with this result": "",
    "They aren't professional enough": "",
    "He isn't afraid of it": "",
    "It isn't interesting at all": "",
    # When we have a verb(question)
    # do  i/we/you/they + verb ...?
    # does he/she / it + verb  ....?
    "Do you know how it works?": "",
    "Do they fully support you?": "",
    "Does she have a similar opinion?": "",
    "Does he know her address?": "",
    "Do I speak English fluently?": "",
    "Do we show excellent results?": "",
    "Is this problem really difficult?": "",
    # When we don't have a verb (question)
    # Am i are /we/you/they? Is he/she/it?
    "Are these lessons really good?": "",
    "Is your friend married?": "",
    "Does he earn more than 200 dollars a month?": "",
    "pounds a month": "",
    "What is your weight?": "",
    "How much is 1 hour?": "",
    "How long is the course last?": "",
    "How long is the course?": "",
    "Do your parents know it?": "",
    "When do the lessons finish?": "",
    "When does this lesson finish?": "",
    "Does he want to have a car?": "",
    "He runs fast": "",
    "She usually says it very quickly": "",
    "Why do these problems interest you?": "",
    "What do all these things mean?": "",
    "Sorry, what do you mean?": "",
    "Why does it seem to you so?": "",
    "My friends don't have an interesting offer": "",
    "Does his wife usually buy expensive things?": "",
    "Cheap / always / often / sometimes ": "",
    "Does she listen to this music?": "",
    "Does she support this idea?": "",
    "Does my best friend need my support now?": "",
    "It doesn't interest me": "",
    "i have different interests / hobbies": "",
    "I usually get up early": "",
    "Does he want to study in another place?": "",
    "Do your colleagues get 500 dollars a month": "",
    "Does your cousin believe in ghosts?": "",
    "I believe you": "",
    "I believe in God": "",
    "Why does your husband need it urgently?": "",
    "now / right now": "",
    "My brother doesn't try to learn English": "",
    "Does the teacher want to tell us all the news?": "",
    "Why do those thing seem boring?": "",
    "interesting / boring": "",
    "Do you need it right now?": "",
    "Does he play the guitar": "",
    "Violin": "",
    "Do I show good results?": "",
    "Does he need to learn English more regularly? often?": "",
    "Does her mother usually stay at home?": "",
    "Do you know it better?": "",
    "I know it better": "",
    "I know it worse": "",
    "He doesn't have his own business": "",
    "Do his students feel progress?": "",
    "I think differently": "",
    "I think another way": "",
    "Do your parents also think so?": "",
    "Do your parents think so, too?": "",
    "Does his friend want to continue?": "",
    "Let's continue!": "",
    "Let's + verb": "",
    "Why does it seem strange?": "",
    "Does your classmate run very fast?": "",
    "Does he feel bad?": "",
    "Does she like this idea?": "",
    "What does your mother teach?": "",
    "Does he want to do it one more time?": "",
    "Do you have house?": "",
    "Does she often fly to the United States?": "",
    "What does it mean?": "",
    "Does she teach English?": "",
    "Why does your best friend support them?": "",
    "How does your teacher explain it?": "",
    "Does this lesson seem very long?": "",
    "Does your brother use the internet every day?": "",
    "Do you work or study?": "",
    "Why do those things seem bad?": "",
    "Do they know all the information?": "",
    "Does this house look expensive?": "",
    "Does she also know it?": "",
    "What does your brother do at work?": "",
    "Do you often see her?": "",
    "Does she use the internet every day?": "",
    "How does your sister dance?": "",
    "Does it seem boring?": "",
    "Does she speak English?": "",
    "Do you want to tell her this thing?": "",
    "Does her mother stay at home?": "",
    "Does she need to rent a flat?": "",
    "When do you watch English movies?": "",
    "Does it interest you?": "",
    "Do your friends have an interesting offer?": "",
    "What does your boss need?": "",
    "How does the company work?": "",
    "Do you see your progress?": "",
    "Does she know it, too?": "",
    "When does he come home?": "",
    "Do you need his help?": "",
    "Those thing don't interest him": "",
    "What do you think about it?": "",
    "His parents don't tell him everything": "",
    "Do they usually come late?": "",
    "Why does he try to do it?": "",
    "Does this boy show a good result?": "",
    "Does she usually sleep well?": "",
    "Does he do business?": "",
    "Do the results seem good?": "",
    "Does thing happen rarely?": "",
    "How do these students prefer to learn English?": "",
    "Does our rest include it?": "",
    "Does she need it urgently?": "",
    "Does he need all the information?": "",
    "How does she explain it?": "",
    "Do your parents think so, too?": "",
    "Does your mother work or stay at home?": "",
    "Do i do it very well?": "",
    "Does it really help you?": "",
    "Do you have any brothers or sisters?": "",
    "Do they see her?": "",
    "Do you think so?": "",
    "Does she need this information?": "",
    "How does your friend spend his free time?": "",
    "When does it usually happen?": "",
    "Where does your father work?": "",
    "Does his sister often meet him?": "",
    "Why does it seem boring?": "",
    "My friends don't have an interesting offer": "",
    "Do you understand me?": "",
    "These results don't seem very good": "",
    "Does she understand us?": "",
    "Does she often forger it?": "",
    "Do you really understand me?": "",
    "When does your boyfriend find time for it?": "",
    "Does it seem really strange?.": "",
    "Do you have a boyfriend?": "",
    "Does your cousin know it better?": "",
    "Does it help him?": "",
    "Does she want to call them?": "",
    "Do these results seem very good?": "",
    "My teacher doesn't say it": "",
    "Where does their daughter study?": "",
    "Does she believe in God?": "",
    "When do you do it?": "",
    "Why do you agree?": "",
    "Does this lesson help you?": "",
    "Why does this idea seem strange": "",
    "Do these ideas seem interesting?": "",
    "Does it really work?": "",
    "Do they come late?": "",
    "Does it interest you?": "",
    "Do you do it professionally?": "",
    "What does she know about this thing?": "",
    "Does your friend have an interesting offer?": "",
    "Do these girl know it very well?": "",
    "Does he want to ger more money?": "",
    "Does your father try to do it?": "",
    "Do your parents know it?": "",
    "Is this thing really useful?": "",
    "The results aren't good enough": "",
    "Does that thing interest them?": "",
    "Your lessons aren't boring at all": "",
    "The book isn't so cheap": "",
    "Is the ticket expensive?": "",
    "All these things don't interest them": "",
    "When do these exams start?": "",
    "Is it easy or difficult?": "",
    "Do you need it right now?": "",
    "Is your brother in hospital?": "",
    "They're in the United States": "",
    "We're very different": "",
    "Is it cloudy?": "",
    "Do her parents always take her?": "",
    "These results are terrible": "",
    "Does this lesson help you?": "",
    "Does that thing really interest you?": "",
    "He's my old friend": "",
    "Does she understand us?": "",
    "Is she a native speaker?": "",
    "Who is here?": "",
    "Who are all these people?": "",
    "When does this lesson usually start?": "",
    "Is the result good enough?": "",
    "Do you often go there?": "",
    "Why do they refuse to do it?": "",
    "Is your brother a professional sportsman?": "",
    "Why do you support them?": "",
    "Do these lessons really help?": "",
    "Am I right or not?": "",
    "Why are they still there?": "",
    "What does your brother do at work?": "",
    "Why are you so surprised?": "",
    "Why is your father so angry today?": "",
    "This thing isn't popular now?": "",
    "Why does your best friend hate it?": "",
    "You expect this result": "",
    "I hope all people know that money isn't everything": "",
    "Is he your best friend?": "",
    "Where does she play this game?": "",
    "Her mother usually stay at home": "",
    "How well does your sister swim?": "",
    "Does it really work?": "",

}