slovar = {
    "It's snowy": "",
    "It's rainy": "",
    # Present Continuous
    "I'm discussing it with them": "",
    "I'm becoming more experienced": "",
    "I'm learning English now": "",
    "My friend and I are going there": "",
    "I'm going there with my friend": "",
    "My partner and I are looking for a new investor": "",
    "My colleagues and I are considering this invitation": "",
    "Your friends are choosing this hotel": "",
    "My brothers are reading your message now": "",
    "My relative is travelling now": "",
    "My boss is reading this report": "",
    "My colleagues are preparing these documents": "",
    # we use Present Simple instead of Present Continuous
    "I understand you very well now": "",
    "I want to thank you now": "",
    "I know it": "",
    "I see my progress now": "",
    "It seems very strange now": "",
    "It sounds very unusual now": "",
    "I like your idea now": "",
    "I love you very much now": "",
    "I hate you": "",
    "I prefer to talk about it": "",
    "I prefer not to talk about it": "",
    "I wish you good luck": "",
    "It costs 10 dollars now": "",
    "This house belongs to me now": "",
    "have": "",
    "I have a car": "",
    "I have a brother": "",
    "Have a rest": "",
    "have a good time": "",
    "have a great time": "",
    "I'm having a rest": "",
    "We're having a good time": "",
    "They're having a great time together": "",
    "I think it's best decision ": "",
    "It's my opinion": "",
    "I'm thinking about this problem": "",
    "I'm thinking about this conflict": "",
    # Present Continuous
    # I'm not ; We aren't / You aren't / They aren't; He isn't she/isn't it isn't + verb + ing
    "I'm not watching this movie now": "",
    "I'm not taking an exam now": "",
    "I'm not walking in the park now": "",
    "We aren't overworking now": "",
    "We're working normally": "",
    "We aren't waiting for his help": "",
    "We aren't thinking about it seriously": "",
    "You aren't speaking without mistakes": "",
    "You aren't learning English effectively": "",
    "You aren't doing the right thing": "",
    "They aren't living in this house now": "",
    "They aren't ignoring this problem": "",
    "They aren't staying at home now": "",
    "He isn't wasting time": "",
    "He isn't closing his eyes on these problems": "",
    "He isn't listening to music now": "",
    "She isn't teaching history now": "",
    "She isn't working far from that place": "",
    "She isn't listening to them now": "",
    "It isn't getting more expensive": "",
    "It's raining": "",
    "It's showing": "",
    "It isn't raining": "",
    "It isn't showing": "",
    "I'm not learning Spanish": "",
    "I'm learning English": "",
    "We aren't having a rest": "",
    "We're working": "",
    "You aren't helping him": "",
    "I think you're very busy": "",
    "They aren't living in this house now": "",
    "They're living in that house": "",
    "He isn't overworking now": "",
    "He's working little": "",
    "She isn't improving her English now": "",
    "Her motivation isn't high enough": "",
    "It isn't raining": "",
    "It's snowing": "",
    # Present Continuous ( negative form )
    "My parents aren't leaving the country": "",
    "My partner isn't making me problems": "",
    "His company isn't experiencing difficulties": "",
    "The factory isn't producing these goods at the moment": "",
    "Their business isn't expanding": "",
    "My colleagues aren't comparing these things": "",
    "His employees aren't complaining now": "",
    "His employer isn't providing good conditions": "",
    "This teacher isn't explaining it using simple words": "",
    "I'm teaching English now giving simple explanations": "",
    "This computer doesn't cost 500 dollars now": "",
    "This idea doesn't seem interesting now": "",
    "It's my opinion": "",
    "I think": "",
    "I don't think it's the best strategy now": "",
    "He doesn't have a house now": "",
    "I'm not thinking about this problem now( a mental process)": "",
    "He isn't having a rest now": "",
    # Present Continuous (Questions)
    # AM I + verb + ing
    # Are we/you/they/ + verb + ing
    # Is he/she/it + verb + ing
    "Am I training intensively?": "",
    "Am I increasing my vocabulary using effective methods?": "",
    "enlarge / widen / enrich vocabulary": "",
    "Am I becoming stronger?": "",
    "Are we changing?": "",
    "Are we preparing for this exam well enough?": "",
    "This lesson is good enough": "",
    "Are we learning English effectively?": "",
    "Are you joking?": "",
    "Are you kidding?": "",
    "Are you combining different methods now?": "",
    "Are you recovering now?": "",
    "Are they hiding from him?": "",
    "Are they smoking now?": "",
    "Are they kissing?": "",
    "Is he swimming now?": "",
    "Is he thinking about our offer now?": "",
    "Is he lying to you?": "",
    "Is she smiling?": "",
    "Is she dancing now?": "",
    "Is she checking his work?": "",
    "It's raining": "",
    "Is it raining?": "",
    "It's snowing": "",
    "Is it snowing?": "",
    "It's getting dark": "",
    "Is it getting dark?": "",
    "Am I wasting time?": "",
    "Are we giving you a good chance?": "",
    "Are you leading a healthy lifestyle?": "",
    "way of life": "",
    "Are they controlling this situation now?": "",
    "Is he cooking?": "",
    "Is she washing up the dishes?": "",
    "Is it bringing you money now?": "",
    "I sat on a soft chair": "",
    "They ran very fast": "",
    "They were together": "",
    "I felt better": "",
    "He sold his flat": "",
    "I wrote a very long message": "",
    "I was shocked": "",
    "I ate some fish": "",
    "I paid for her": "",
    "He gave me this information": "",
    "He showed me his excellent results": "",
    "He came to the party": "",
    "I wore school uniform": "",
    "It meant nothing": "",
    "It didn't mean anything": "",
    "He cut himself": "",
    "He hit the ball": "",
    "He sent her flowers": "",
    "It lay near that place": "",
    "He lent her 200 pounds": "",
    "I spent so much time on it": "",
    "They did it again and again": "",
    "He was such an experienced worker": "",
    "As you understand we spoke English": "",
    "I knew what to say": "",
    "They hid from us": "",
    "He stole her bag": "",
    "He threw a ball to him": "",
    "She told me how to do it": "",
    "I spoke English a lot": "",
    "He threw a small ball to him": "",
    "She taught English there 2 years ago": "",
    "We met in a local restaurant": "",
    "He came to us": "",
    "They sang the favorite song": "",
    "We had a great time": "",
    "We were surprised by the news": "",
    "He lost his wallet": "",
    "He fell down and broke his leg": "",
    "I wrote a message": "",
    "He spent all his money": "",
    "I left my wallet at home": "",
    "I felt we had a big problem": "",
    "I understood him immediately": "",
    "He got up too late": "",
    "I read that text": "",
    "It cost too much": "",
    "I chose this channel": "",
    "She hid behind the tree": "",
    "I chose your method": "",
    "His car broke down": "",
    "We chose another room": "",
    "He drank a glass of wine": "",
    "I rode a bike": "",
    "I went cycling": "",
    "I felt I knew everything": "",
    "She sold her car": "",
    "I took her with me": "",
    "I drove a car yesterday": "",
    "I put it near my computer": "",
    "They always spent more money": "",
    "We flew to another city": "",
    "I felt bad": "",
    "I was the best student": "",
    "She grew vegetables in her own garden": "",
    "I found a good job": "",
    "The wind blew suddenly": "",
    "I spent 2 hours on it": "",
    "I did my homework": "",
    "He swam in the lake": "",
    "She grew flowers": "",
    "He sang professionally": "",
    "I drank a cup of coffee": "",
    "He said it one more time": "",
    "The price fell sharply": "",
    "My friend drove home": "",
    "I went to the park": "",
    "I got up very early": "",
    "I went jogging": "",
    "His parents let him play outside": "",
    "I felt good": "",
    "He did a strange thing": "",
    "We swam un the river": "",
    "I often heard it when I was there": "",
    "She was a leader": "",
    "I felt much better": "",
    "She kept her money in a bank": "",
    "I wrote a letter": "",
    "I knew how to say it": "",
    "She told me her secret": "",
    "I saw progress": "",
    "I left home 20 minutes ago": "",
    "I forgot to call her": "",
    "He broke her pen": "",
    "She told me to call him": "",
    "We knew it very well": "",
    "He bought a beautiful dress for her": "",
    "He hurt her feelings": "",
    "I paid for this service": "",
    "We got all the necessary information": "",
    "He paid for us": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

}