slovar = {
    "wake(up) - woke - woken": "",
    "I woke up very early": "",
    "I got up very early": "",
    "I woke up at 6 o'clock in the morning": "",
    "He woke up late": "",
    "leave - left - left": "",
    "I live in this city": "",
    "I left my wallet at home": "",
    "I left it in my room": "",
    "I left Russia": "",
    "We left America": "",
    "Break - broke - broken": "",
    "They broke the rules": "",
    "He broke the window": "",
    "Break down": "",
    "His car often broke down": "",
    "keep - kept - kept": "",
    "I kept his secret": "",
    "I kept my promise": "",
    "He kept his word": "",
    "Hold - held - held": "",
    "He held her bag": "",
    "He held that box": "",
    "He held it in his arms": "",
    "let - let - let": "",
    "His parents let him go out": "",
    "---let somebody do something---": "",
    "They let him be there until midnight": "",
    "They let him stay there until midnight": "",
    "His parents let him play outside": "",
    "Mean - meant - meant": "",
    "It meant the following": "",
    "His behavior meant the following thing": "",
    "mean nothing": "",
    "It meant nothing": "",
    "It didn't mean anything": "",
    "win - won - won": "",
    "I won in that competition": "",
    "We won in that tournament": "",
    "We won the game": "",
    "blow - blew - blown": "",
    "The wind blew suddenly": "",
    "The wind blew so strongly": "",
    "They often broke the rules": "",
    "He held that box": "",
    "They stole this information": "",
    "He kept his money in a safe place": "",
    "His car broke down": "",
    "Her car broke down quite often": "",
    "His behavior meant the following": "",
    "My car broke down very rarely": "",
    "Their team won unexpectedly": "",
    "They let him stay there until midnight": "",
    "His parents let him go out": "",
    "He broke her pen": "",
    "He held her bag": "",
    "We won the game": "",
    "He stole such expensive things": "",
    "I meant the following thing": "",
    "They stole his idea": "",
    "I won 500( five hundred) dollars": "",
    "I left Russia": "",
    "His parents let him play outside": "",
    "He stole her bag": "",
    "We left Russia last year": "",
    "I woke up as usual": "",
    "He held the door": "",
    "We left America": "",
    "I left my wallet at home": "",
    "The wind blew suddenly": "",
    "I left money at home": "",
    "He held her hand": "",
    "I won in that competition": "",
    "I left it in your room": "",
    "It meant nothing": "",
    "It didn't mean anything": "",
    "He woke up late": "",
    "Our team won suddenly": "",
    "He broke his promise": "",
    "They stole his clothes": "",
    "I kept his secret": "",
    "I left my keys": "",
    "My car broke down very rarely": "",
    "Her words meant a strange thing": "",
    "She kept her money in a bank": "",
    "I woke up at 6 o'clock in the morning": "",
    "I woke up very early": "",
    "The car often broke down": "",
    "We won in that tournament": "",
    "He broke the window": "",
    "I left home 20 minutes ago": "",
    "The wind blew so strongly": "",
    "I left the office late": "",
    "I left home at 8 o'clock in the morning": "",
    "grow - grew - grown": "",
    "He grew vegetables in his own garden": "",
    "grow up": "",
    "I grew up in Russia": "",
    "He grew up in America": "",
    "lie - lay - lain": "",
    "lie down": "",
    "I lay down": "",
    "The pen lay on the desk": "",
    "lie - lied -lied": "",
    "She lied to me": "",
    "fall - fell - fallen": "",
    "The price fell sharply": "",
    "fall down": "",
    "He fell down": "",
    "She fell down and broke her arm": "",
    "spend - spent - spent": "",
    "He spent all his money": "",
    "He spent more than he wanted": "",
    "I spent two hours on it": "",
    "She spent 200 dollars": "",
    "drive - drove - driven": "",
    "I drove a car yesterday": "",
    "drive home": "",
    "drive to work": "",
    "I drove to work": "",
    "I drove home": "",
    "draw - drew - drawn": "",
    "He drew a picture": "",
    "She drew such a beautiful picture": "",
    "She drew his face": "",
    "wear - wore - worn": "",
    "I wore school uniform": "",
    "I wore glasses": "",
    "He wore casual clothes": "",
    "Hurt - hurt - hurt": "",
    "He hurt his leg": "",
    "She fell down and hurt her leg": "",
    "She hurt her arm": "",
    "He hurt her feelings": "",
    "cut - cut- cut": "",
    "He cut the meat": "",
    "She cut the fish": "",
    "He cut himself": "",
    "She cut herself": "",
    "He cut the meat into small pieces": "",
    "forget - forgot - forgotten": "",
    "I forgot his name": "",
    "I forgot to do it": "",
    "I forgot to call her": "",
    "I forgot to close the door": "",
    "I forgot to lock the door": "",
    "He cut the meat": "",
    "She sut herself": "",
    "He lay down": "",
    "The book lay on the table": "",
    "She grew flowers": "",
    "He lied to her": "",
    "She lied to her boss": "",
    "He grew vegetables in his own garden": "",
    "I grew up in Russia": "",
    "I forgot to call her": "",
    "She fell down and broke her arm": "",
    "He drove to me": "",
    "I forgot his name": "",
    "It lay near that place": "",
    "it lay far from that place": "",
    "The bag lay far from there": "",
    "The price fell suddenly": "",
    "I wore school uniform": "",
    "I spent 2 hours on it": "",
    "He grew up in America": "",
    "She hurt her arm": "",
    "The price fell sharply": "",
    "He drew such a funny picture": "",
    "She drew a picture": "",
    "My friend drove home": "",
    "She spent her last money": "",
    "I forgot to do it one more time": "",
    "I spent so much time on it": "",
    "She spent 200 dollars": "",
    "She drew such a beautiful picture": "",
    "I drove to school": "",
    "He spent all his money": "",
    "I forgot to lock the door": "",
    "The pen lay on the desk": "",
    "He hurt his leg": "",
    "We drove to the airport": "",
    "She wore informal clothes": "",
    "She drew his face": "",
    "She wore casual clothes": "",
    "I drove a car yesterday": "",
    "He cut his finger": "",
    "She spent too much time on it": "",
    "I forgot to do it": "",
    "He fell down": "",
    "I wore glasses": "",
    "He cut himself": "",
    "I forgot how to use it": "",
    "He fell down and broke his leg": "",
    "They always spent more money": "",
    "He cut the meat into small pieces": "",
    "I spent 3 hours on it": "",
    "I forgot the name of this street": "",
    "She wore formal clothes": "",
    "I drove to work": "",
    "He grew up in Canada": "",
    "He hurt her feelings": "",
    "She cur the fish": "",
    "It hurt her feelings": "",
    "He spent more than he wanted": "",
    "The last example": "",
    "I spent a lot of energy(lots of energy)": "",
    "I spent lots of energy on this project": "",
    "sing - sang - sung": "",
    "She sang a very beautiful song": "",
    "She sang very beautifully": "",
    "He sang his favorite song": "",
    "Teach - taught - taught": "",
    "I taught English": "",
    "He taught them Russian": "",
    "He taught history": "",
    "throw - threw - thrown": "",
    "He threw a ball to him": "",
    "He threw a ball at him": "",
    "throw away": "",
    "He threw it away": "",
    "feed - fed - fed": "",
    "He fed his dog": "",
    "She fed her cat": "",
    "She fed her baby": "",
    "They fed the children": "",
    "lend - lent - lent": "",
    "I lent him some money": "",
    "I lent him 300 dollars": "",
    "They lent him a big sum of money": "",
    "Ring - rang - rung": "",
    "The bell rang": "",
    "My alarm clock rang": "",
    "I called him": "",
    "I rang him": "",
    "hide - hid - hidden": "",
    "He hid from them": "",
    "She hid behind the tree": "",
    "He hid behind that building": "",
    "Hit - hit - hit": "",
    "He hit the ball": "",
    "He hit the door": "",
    "beat - beat - beaten": "",
    "They beat him very badly": "",
    "Strongly": "",
    "beat someone badly": "",
    "They beat that team": "",
    "ride - rode - ridden": "",
    "I rode a bike": "",
    "I rode a horse": "",
    "I rode a camel": "",
    "I can ride a bike": "",
    "go cycling": "",
    "I went cycling": "",
    "It sounds very natural": "",
    "run - ran - run": "",
    "go jogging": "",
    "I went jogging": "",
    "for free": "",
    "He has too much money": "",
    "He has too many mistakes": "",
    "uncountable": "",
    "countable": "",
    "I know a lot": "",
    "He doesn't know much": "",
    "I speak English a lot": "",
    "can + verb": "",
    "I can say it": "",
    # past
    "I could say it": "",
    "It's mistake": "",
    "Is it a mistake?": "",
    "horrible": "",
    "It's a revolutionary method": "",
    "The bell rang": "",
    "He sang his favorite song": "",
    "He taught this subject last year": "",
    "She taught several subject there": "",
    "He taught history": "",
    "She fed the children": "",
    "She hid from them": "",
    "His alarm clock rang suddenly": "",
    "He hid from them": "",
    "She fed her cat": "",
    "She sang three beautiful songs": "",
    "She taught us English very well": "",
    "She fed her baby": "",
    "They beat that team": "",
    "He threw a ball to him": "",
    "I lent him some money": "",
    "He taught English when he was 20 years old": "",
    "She threw it away": "",
    "She sang very beautifully": "",
    "I went cycling": "",
    "I rode a bike": "",
    "He threw it away": "",
    "He sang professionally": "",
    "I lent him 500 euros": "",
    "I rode a horse": "",
    "He hid behind that building": "",
    "He hit the ball": "",
    "He fed his dog": "",
    "They hid from us": "",
    "They fed the children": "",
    "He hit him first": "",
    "They sang their favorite song": "",
    "He lent her 200 pounds": "",
    "We went jogging three times a week": "",
    "They lent him a very big sum of money": "",
    "He threw a small ball to him": "",
    "They beat him very badly": "",
    "He taught them Russian": "",
    "He fed his pet": "",
    "I taught English": "",
    "He threw them away": "",
    "She taught English there 2 years ago": "",
    "He hit the door": "",
    "I taught him a lesson": "",
    "She hid behind the tree": "",
    "I rode a camel": "",
    "My alarm clock rang": "",
    "I lent him 300 dollars": "",
    "She sang a very beautiful song": "",
    "I went jogging": "",
    "I ran very fast": "",
    "break - broke - broken": "",
    "His car broke down": "",
    "lie - lay - lain": "",
    "The pen lie on the desk": "",
    "lie - lied - lied": "",
    "She lied to her parents": "",
    "Write - wrote - written": "",
    "She wrote a letter": "",
    "leave - left - left": "",
    "I left Russia": "",
    "come - came - come": "",
    "He came to me": "",
    "think - thought - thought": "",
    "I thought about this problem": "",
    "Hear - heard - heard": "",
    "I heard it from him": "",
    "Know - knew - known": "",
    "I knew her secret": "",
    "Keep - kept - kept": "",
    "He kept his word": "",
    "find - found - found": "",
    "He found his keys": "",
    "He found his lost keys": "",
    "mean - meant - meant": "",
    "I meant the following thing": "",
    "be - was/were - been": "",
    "It was such a good idea": "",
    "swim - swam - swum": "",
    "We swam in the sea": "",
    "ride - rode - ridden": "",
    "I rode a horse": "",
    "hold - held - held": "",
    "I held the door": "",
    "get - got - got": "",
    "I got up very early": "",
    "Hurt - hurt - hurt": "",
    "He fell down and hurt his arm": "",
    "feed - fed - fed": "",
    "She fed her cat": "",
    "stand - stood - stood": "",
    "He stood up": "",
    "fly - flew - flown": "",
    "She flew to Canada": "",
    "Drive - drove - driven": "",
    "I drove to work": "",
    "meet - met - met": "",
    "I met this word for the first time": "",
    "sit - sat - sat": "",
    "He sat down": "",
    "sing - sang - sung": "",
    "She sang so beautifully": "",
    "I drank a glass of juice": "",
    "let - let - let": "",
    "They let her stay there until midnight": "",
    "grow - grew - grown": "",
    "I grew up in America": "",
    "We went there together": "",
    "beat - beat - beaten": "",
    "They beat him very badly": "",
    "Become - became - become": "",
    "He became famous": "",
    "Wake - woke - woken": "",
    "I woke up very early": "",
    "fall - fell - fallen": "",
    "The price fell unexpectedly": "",
    "Feel - felt - felt": "",
    "I felt better": "",
    "Wear - wore - worn": "",
    "She wore stylish fashionable clothes": "",
    "read = read - read": "",
    "I read a lot": "",
    "buy - bought - bought": "",
    "He bought a house": "",
    "ring = rang - rung": "",
    "The bell rang": "",
    "lend - lent = lent": "",
    "I lend him 2000 dollars": "",
    "make - made = made": "",
    "He made a big mistake": "",
    "Have - had = had": "",
    "She had a boyfriend": "",
    "begin = began - begun": "",
    "The meeting began on time": "",
    "steal - stole - stolen": "",
    "They stole his wallet": "",
    "do = did - done": "",
    "He did his homework": "",
    "cost - cost - cost": "",
    "It cost little": "",
    "Lose = lost - lost": "",
    "He lost this money": "",
    "blow = blew - blown": "",
    "The wind blew suddenly": "",
    "spend - spent = spent": "",
    "she spent more less": "",
    "cut - cut - cut": "",
    "he cut his finger": "",
    "Understand = understood": "",
    "I understood you perfectly": "",
    "Hit - hit - hit": "",
    "He hit the ball": "",
    "see - saw - seen": "",
    "I saw progress": "",
    "I saw progress": "",
    "send - sent - sent": "",
    "She sent me a letter": "",
    "Show = showed - shown": "",
    "He showed me his excellent results": "",
    "Pay = paid = paid": "",
    "I paid for her": "",
    "throw - threw = thrown": "",
    "I threw it away": "",
    "draw - drew - drawn": "",
    "She drew a picture": "",
    "tell - told - told": "",
    "choose - chose - chosen": "",
    "I chose your course": "",
    "hide - hid - hidden": "",
    "He hid this sum of money": "",
    "say- said - said": "",
    "He said it very loudly": "",
    "take - took - taken": "",
    "I took her with me": "",
    "eat - ate - eaten": "",
    "I ate a little": "",
    "I ate a bit": "",
    "I ate little": "",
    "speak - spoke - spoken": "",
    "He said it": "",
    "I want to say": "",
    "He told me to do it": "",
    "He told me this secret": "",
    "Let's speak English": "",
    "Let's talk about it": "",
    "talk-discuss": "",
    "win - won - won": "",
    "I won at last": "",
    "give - gave - given": "",
    "He gave me this information": "",
    "put - put - put": "",
    "I put it on the table": "",
    "forget - forgot - forgotten": "",
    "I forgot how to do it": "",
    "teach - taught - taught": "",
    "She taught English there": "",
    "sell - sold - sold": "",
    "She sold her old car": "",
    "sleep - slept - slept": "",
    "He slept in his new room": "",
    "run - ran - run": "",
    "He ran to the their house": "",
    # Past simple ( Negative form)
    # I improved my English a lot
    # didn't + verb
    # + the second form
    # 1 regular verb - verb + ed
    # 2 irregular verb - remember v2
    # He told me all the truth
    "I improved my English greatly thanks to this channel": "",
    "I didn't improve my English there": "",
    "He didn't tell me all the truth": "",
    "be - was/were - been": "",
    "I/He/She/They wasn't": "",
    "We/You/THey weren't": "",
    "It wasn't a strange offer": "",
    "That offer was quite normal": "",
    "They weren't satisfied with his decision": "",
    "She didn't know what to say": "",
    "She didn't find her lost keys": "",
    "He didn't Thank them for help": "",
    "I didn't remember the correct answer": "",
    "I didn't like the performance": "",
    "She didn't see him yesterday": "",
    "I didn't want to study there": "",
    "We continued discussing that problem": "",
    "continue doing something": "",
    "hate doing": "",
    "enjoy doing": "",
    "We didn't know how to solve it": "",
    "I continued learning English here": "",
    "I hated talking about this problem": "",
    "I enjoyed spending time with them": "",
    "solve a problem/task": "",
    "We solved that problem": "",
    "I decided to learn English really seriously": "",
    # past simple
    # I/He/She/It wasn't
    # We/You/They weren't
    "It wasn't an important event for us": "",
    "He wasn't available": "",
    "He was unavailable": "",
    "We focus on modern English": "",
    "This singer wasn't so popular": "",
    "It wasn't hot": "",
    "It was very cold": "",
    "The lesson wasn't useful": "",
    "It was useless": "",
    "I wasn't near": "",
    "I was very far from that place": "",
    "His car wasn't new": "",
    "It was an old car": "",
    "I wasn't tired": "",
    "I was full of energy": "",
    "The weather wasn't good": "",
    "It was very bad": "",
    "I wasn't hungry": "",
    "I didn't want to eat": "",
    "It wasn't a big mistake": "",
    "It was a small mistake": "",
    "My room wasn't comfortable but it was very expensive to live there": "",
    "This thing wasn't expensive": "",
    "It was very cheap": "",
    "The exam wasn't difficult": "",
    "It was really easy": "",
    "It wasn't the best decision": "",
    "The decision was very bad": "",
    "That method wasn't effective": "",
    "It was so ineffective": "",
    "It was such an ineffective method": "",
    "The conference wasn't boring": "",
    "I learnt lots of new interesting things": "",
    "We learn something": "",
    "a lots of, lots of": "",
    "I have a lot of friends": "",
    "I have lots of energy": "",
    "I don't have many friends": "",
    "I don't have much energy": "",
    "It wasn't a short way": "",
    "It was a very long way": "",
    "more informal": "",
    # past simple ( Question )
    # did + subject + verb ?
    "Did you go there?": "",
    "Did she call him?": "",
    "Did you see this website?": "",
    "Did you get my message?": "",
    "Did it happen to him?": "",
    "Did you forget the date of our meeting?": "",
    "Did you hear the latest news?": "",
    "Did you speak English yesterday?": "",
    "Did you improve your English?": "",
    "Did you decide to stay at home?": "",
    "Did you think about my offer?": "",
    "Did you solve this problem at last?": "",
    "Did you follow his advice?": "",
    "Did she come back/return ?": "",
    "Did she get a call from him?": "",
    "Did he believe her immediately": "",
    "Did you achieve your aim?": "",
    "I achieved my aim": "",
    "Did you prepare for your exams?": "",
    "Did you start learning English seriously?": "",
    "enjoy,hate,continue + start": "",
    "Did you start doing it regularly?": "",
    "Did you do it?": "",
    "Did you improve your pronunciation?": "",
    "Did you improve your speaking?": "",
    "I want to improve my speaking": "",
    "Did you improve your speaking skills": "",
    "reading skills": "",
    "writing skills": "",
    "vocabulary": "",
    "One more question": "",
    "Did you start speaking English fluently?": "",
    # be - was/were been
    "Was I right?": "",
    "Was he right?": "",
    "Was she right?": "",
    "Was it right?": "",
    "Were we right?": "",
    "Were you right?": "",
    "Were they right?": "",
    "Was it a good idea?": "",
    "Was he really happy?": "",
    "Was it the best decision?": "",
    "Was it a big success?": "",
    "Was it an important event?": "",
    "Was it impossible for you?": "",
    "Was she sad?": "",
    "Were you really surprised by the news?": "",
    "Was it cold yesterday?": "",
    "Was he really disappointed?": "",
    "be proud of": "",
    "I was proud of my results": "",
    "Was she proud of her results?": "",
    "Was it a special offer?": "",
    "Were they hospitable enough?": "",
    "Were they friendly?": "",
    "Was it a good school?": "",
    "Were you in America last year?": "",
    "Were you in India last month?": "",
    "Were you in this city last year?": "",
    "Was it a serious problem?": "",
    "Were you against this decision?": "",
    "Was it a profitable company?": "",
    "Was your brother right?": "",
    "Were your parents abroad last month?": "",
    "Was his lesson really interesting?": "",
    "Was this money too little?": "",
    "Was this knowledge enough?": "",
    # past simple
    # present simple
    # 1 verb
    # 2 no verb
    # statement, negative sentences , form questions , general questions , special question
    # past simple
    # 1 verb
    # was/were
    # statement, negative sentences , form questions , general questions , special question
    # irregular verbs
    #  did / was / were / didn't / wasn't / weren't
    #
    # To form past simple you need to use the second form verb. We have 2 situations"
    #1 regular verb
    # verb + ed
    # She plays tennis - She played tennis
    # I watch football - i watched football
    #2 irregular verbs
    # go - went
    # I went there with her
    # be - was/were
    # I / he / she / it was in America
    # We/ you / they were surprised
    # negative
    # 1 didn't + verb
    # 2 wasn't / weren't ...
    "We didn't like that movie": "",
    "She didn't like this idea": "",
    "She found it very strange": "",
    "It wasn't the best decision": "",
    "We had another alternative": "",
    # 3 Did + subject + verb
    # Was I / he / she / it
    #  were we / you / they
    "Did you prepare for this test?": "",
    "Did you work on your mistakes?": "",
    "Did you improve your English level?": "",
    "Did she agree with this statement?": "",
    "Was she the most popular singer at that time?": "",
    "Was he very educated?": "",
    "Were my mistakes serious?": "",
    "Did she get a new job?": "",
    "Was he proud of his success?": "",
    "Did you forget the time of our meeting?": "",
    "He cut the meat into small pieces": "",
    "He told me all the information": "",
    "Were you in India last year?": "",
    "Was it a profitable company?": "",
    "I lost concentration": "",
    "I enjoyed spending time with them": "",
    "He drove to me": "",
    "I ate some fish": "",
    "I didn't like that channel": "",
    "I didn't want to study in another place": "",
    "He sat on a chair": "",
    "She lost her keys": "",
    "I continued learning English here": "",
    "Was it a bad idea?": "",
    "We weren't tired": "",
    "We wanted to continue working": "",
    "I did what you wanted": "",
    "This thing wasn't expensive": "",
    "It was very cheap": "",
    "I spent lots of energy": "",
    "I spent a lot of energy on this project": "",
    "He didn't lend her 200 dollars": "",
    "He stole her bag": "",
    "I enjoyed visiting that place": "",
    "Was she sad?": "",
    "We had a good time": "",
    "Did you follow these recommendations": "",
    "Was he a very successful businessman?": "",
    "I told her only some things": "",
    "Did you believe his promises?": "",
    "He was unavailable": "",
    "He wasn't available": "",
    "She spoke Spanish": "",
    "My progress wasn't big enough": "",
    "As you understand we spoke English": "",
    "He ate meat and fish": "",
    "Did you think about your future?": "",
    "He hid behind that building": "",
    "She improved her spanish a lot": "",
    "It was a big success": "",
    "I wasn't tired": "",
    "I was full of energy": "",
    "Was it a good idea?": "",
    "Were your friends in the same place?": "",
    "Was your brother there, too?": "",
    "Was it a true story?": "",
    "We decided to meet again": "",
    "She didn't say it": "",
    "The dress wasn't expensive": "",
    "It was very cheap": "",
    "We paid for them": "",
    "He cut himself": "",
    "He didn't make any mistakes": "",
    "He didn't see his mistakes": "",
    "Did you get my message?": "",
    "He got up too late": "",
    "Was he the best worker?": "",
    "It wasn't the best choice for us": "",
    "We felt we had such a big problem": "",
    "It wasn't a big mistake": "",
    "It was a small mistake": "",
    "I woke up at 6 O'clock in the morning": "",
    "He didn't forget to do it": "",
    "Was it a serious problem?": "",
    "Did you hear the latest news?": "",
    "I took their offer": "",
    "I wanted to know English like educated native speakers": "",
    "Did she believe him immediately?": "",
    "I paid for this service": "",
    "Did you start doing it regularly?": "",
    "Did she solve this problem at last?": "",
    "We thought about the future of our company": "",
    "My alarm clock rang": "",
    "I came home": "",
    "She hurt her arm": "",
    "He lost his wallet": "",
    "They didn't come to our party": "",
    "we continued discussing that problem": "",
    "We didn't know how to solve it": "",
    "Was it the vest offer?": "",
    "I went cycling": "",
    "I rode a bike": "",
    "Were your parents abroad last year?": "",
    "I got your message": "",
    "She found her passport": "",
    "It wasn't a short way": "",
    "It was a very long way": "",
    "He didn't thank them for help": "",
    "Was it a good school?": "",
    "She taught us English very well": "",
    "Did she come back?": "",
    "Did she return?": "",
    "I didn't want to study there": "",
    "He didn't tell us all the truth": "",
    "His car broke down quite often": "",
    "She drew a picture": "",
    "I communicated with people from other countries": "",
    "It was wonderful great!": "",
    "Was he really happy?": "",
    "My car broke down unexpectedly": "",
    "Were they hospitable?": "",
    "Were they friendly?": "",
    "Did you speak English yesterday?": "",
    "I didn't speak Russian there": "",
    "I spoke only English": "",
    "Was it a good choice?": "",
    "Did you improve your listening skills?": "",
    "Was she friendly with you?": "",
    "They told me everything": "",
    "Was it impossible for you": "",
    "I didn't know what to do": "",
    "It was such a big problem": "",
    "We were in a very difficult situation": "",
    "They know English perfectly": "",
    "They don't know English perfectly": "",
    "Do they know English perfectly": "",
    "They knew English perfectly": "",
    "They didn't know English perfectly": "",
    "Did they know English perfectly?": "",
    "It's an excellent result": "",
    "It isn't an excellent result": "",
    "Is it an excellent result?": "",
    "It was an excellent result": "",
    "It wasn't an excellent result": "",
    "Was it an excellent result?": "",
    "The offer seems interesting": "",
    "The offer doesn't seem interesting": "",
    "Does the offer seem interesting?": "",
    "The offer seemed interesting": "",
    "The offer didn't seem interesting": "",
    "Did the offer seem interesting": "",
    "His result is terrible": "",
    "His result isn't terrible": "",
    "Is his result terrible?": "",
    "His result was terrible": "",
    "His result wasn't terrible": "",
    "Was his result terrible?": "",
    "Your friends are right": "",
    "Your friends aren't right": "",
    "Are your friends right?": "",
    "Your friends were right": "",
    "Your friends weren't right": "",
    "were your friends right?": "",
    "His boss lends him money": "",
    "His boss doesn't lent him money": "",
    "Does his boss lend him money?": "",
    "His boss lent him money": "",
    "His boss didn't lend him money": "",
    "Did his boss lend him money?": "",
    # present simple
    "My teachers are very professional": "",
    "My teachers aren't very professional": "",
    "Are my teachers very professional?": "",
    "My teachers were very professional": "",
    "My teachers weren't very professional": "",
    "Were my teachers very professional?": "",
    "We didn't expect such bad results": "",
    "It wasn't a strange offer": "",
    "That offer was quite normal": "",
    "I drove to school": "",
    "Did it happen to you last year?": "",
    "He had a strange offer": "",
    "I was far from that place": "",
    "It wasn't near": "",
    "I slept very long": "",
    "I knew what to say": "",
    "I didn't agree with them": "",
    "I disagreed with them": "",
    "Was this knowledge enough": "",
    "I decided to change my job": "",
    "I didn't believe him first": "",
    "Did he prepare for his last exam?": "",
    "I wore school uniform": "",
    "The conference began the day before yesterday": "",
    "I didn't like those lessons": "",
    "He was such an experience worker": "",
    "Did you improve your English?": "",
    "She sold her car": "",
    "Did you follow his advice?": "",
    "She said everything": "",
    "I wasn't satisfied with my results": "",
    "He was a very talented boy": "",
    "I was the best": "",
    "Their team won unexpectedly": "",
    "She lost her bag": "",
    "Were you surprised by his offer?": "",
    "I was shocked by this news": "",
    "He cut the meat": "",
    "Was it a special price?": "",
    "Was it a real problem for you?": "",
    "My car broke down very rarely": "",
    "He lived in the twentieth century": "",
    "Did you get her latter?": "",
    "I gave him 200 dollars": "",
    "Did you speak only English?": "",
    "We didn't like that food": "",
    "I felt we had a big problem": "",
    "He sent me two e-mails": "",
    "Did he thank you for help?": "",
    "I wasn't hungry": "",
    "I didn't want to eat": "",
    "We knew it perfectly": "",
    "He broke the window": "",
    "He held that box": "",
    "I taught him a lesson": "",
    "I saw progress": "",
    "She drew such a beautiful picture": "",
    "I didn't hear what she wanted": "",
    "He threw a small ball to him": "",
    "He didn't become a successful businessman": "",
    "I decided to watch all the playlist": "",
    "Did you call your relative yesterday?": "",
    "I didn't want to go to another place": "",
    "Were you together?": "",
    "Did you prepare for these exams?": "",
    "I knew how to say it": "",
    "Did you improve your writing skills?": "",
    "My friend drove home": "",
    "She drew his face": "",
    "I enjoyed watching your videos": "",
    "I improved my English greatly thanks to this channel": "",
    "We didn't solve that problem": "",
    "I chose your method": "",
    "I understood you without any problems at all": "",
    "Did it happen to him?": "",
    "She flew to America": "",
    "The event wasn't so important": "",
    "He kept his money in a safe place": "",
    "Did she always help you?": "",
    "Did you achieve your aim?": "",
    "He threw it away": "",
    "He didn't improve his pronunciation": "",
    "It was a big success": "",
    "I started speaking English regularly": "",
    "The game wasn't boring at all": "",
    "I really liked it": "",
    "Did you decide to stay at home?": "",
    "I felt good": "",
    "We met at last": "",
    "Did she improve her results?": "",
    "It wasn't the best decision": "",
    "The decision was very bad": "",
    "Were you in Canada two years ago?": "",
    "They were together": "",
    "He didn't pay for her": "",
    "He found a well-paid job": "",
    "She told me to call him": "",
    "I didn't watch all your videos": "",
    "It meant nothing": "",
    "It didn't mean anything": "",
    "I wrote a very long message": "",
    "He didn't go to America last year": "",
    "He fell down and broke his leg": "",
    "It wasn't an important event for us": "",
    "It was unimportant": "",
    "I hated talking about that problem": "",
    "He fed his dog": "",
    "She bought a very powerful computer": "",
    "The price fell sharply": "",
    "The exam wasn't difficult": "",
    "It was easy": "",
    "I drank a cup of coffee": "",
    "He lied to her": "",
    "Did he improve his level?": "",
    "I won in that competition": "",
    # past simple special question
    # question + helping verb + s + verb
    "What did you answer to his question?": "",
    "What did you answer him?": "",
    "What did he recommend?": "",
    "What did you do yesterday?": "",
    "When did she complain?": "",
    "When did he check our work?": "",
    "When did the meeting begin?": "",
    "How did he react to it?": "",
    "How did he manage to solve problem?": "",
    "manage to do something": "",
    "I manage to pass this exam": "",
    "How did he explain this thing?": "",
    "How did he translate this text?": "",
    "Why did he complain?": "",
    "Why did you disagree with him?": "",
    "Why did you arrive so late?": "",
    "Why did she change her job?": "",
    # Present Simple
    # Who knows it?
    # Who understands it?
    # Who knew it?    Who understood it?      Who knew how to do it?    Who called you?
    # Whom did you call? - Who did you call?
    # Who helped you?
    # Who did you help?
    "What did you do yesterday?": "",
    # Present Simple
    # What interests you? cars
    # What seems strange to you ? This thing
    # Past Simple
    "What interested you?": "",
    "What seemed strange to you?": "",
    "What time did you get up?": "",
    "What time did you go to bed?": "",
    "What time did you come back?": "",
    "What time did she call you?": "",
    "Which book did you buy?": "",
    "Which drink did you choose?": "",
    "Which lesson did you watch?": "",
    "What books did you raed?": "",
    "What kind of books did you read?": "",
    "What sort of books did you read?": "",
    "What interesting things did he say?": "",
    "How much did it cost?": "",
    "How much money did he invest?": "",
    "How many games did he win?": "",
    "How often did you go to the swimming pool?": "",
    "How often did you go jogging?": "",
    "How often did you go to the gym?": "",
    # Past simple special question was/ were
    # question word
    # Q + was/were _______?
    "What were his achievements?": "",
    "What was so unusual?": "",
    "What were his mistakes?": "",
    "When was this club?": "",
    "Where was my mistake?": "",
    "Where were my mistakes?": "",
    "Where were your parents last month?": "",
    "When were you at home?": "",
    "When was the best time for it?": "",
    "When were they together?": "",
    "How was the party?": "",
    "How was the meeting?": "",
    "How were his lessons?": "",
    "Why was it really necessary?": "",
    "Why was that thing so important?": "",
    "Why was it such a bad idea?": "",
    "Who was there?": "",
    "Who was right?": "",
    "Who was in this situation, too?": "",
    "What books were on the table?": "",
    "What information was available?": "",
    "What mistakes were serious?": "",
    "What time was he at home?": "",
    "What time were you there?": "",
    "What time was your brother at school?": "",
    "Which answer was correct?": "",
    "Which book did you decide to buy?": "",
    "What kind of contract was it?": "",
    "How much was it?": "",
    "How much did it cost?": "",
    "How much was the computer?": "",
    "How much was the dress?": "",
    "How long was the lesson?": "",
    "How difficult was the text?": "",
    "How interested was he?": "",
    "How rich were they?": "",
    "How expensive was it?": "",
    "He decided to learn English very intensively two years ago because he really needed it": "",
    "How decided to learn English?": "",
    "What did he decide to do?": "",
    "What did he decide to learn?": "",
    "How did he decide to learn English?": "",
    "How intensively did he decide to learn English?": "",
    "When did he decide to learn English?": "",
    "How many years ago ded he decide to learn English?": "",

}