slovar = {
    "Is all this money enough?": "",
    "Why is this detail so important?": "",
    "Does it interest you?": "",
    "Not at all": "",
    "He's my classmate": "",
    "Is your brother in bed?": "",
    "This idea is quite old": "",
    "All his lessons are free and I'm so happy": "",
    "It's boring": "",
    "How are these dishes?": "",
    "Are we far from this place?": "",
    "What does it mean?": "",
    "Is the news sad?": "",
    "His father is rich": "",
    "The book isn't expensive": "",
    "How is my new sweater?": "",
    "Are they right?": "",
    "Is this girl the best student?": "",
    "Where is our English teacher?": "",
    "The problem is small": "",
    "His partners aren't reliable": "",
    "When does he come home?": "",
    "Why do you learn English?": "",
    "Why do you study English?": "",
    "You're in a difficult situation": "",
    "Their results are brilliant": "",
    "Is it in this area?": "",
    "Are they your colleagues?": "",
    "Does your friend have an interesting offer?": "",
    "I think differently": "",
    "I think another way": "",
    "Where is he from?": "",
    "He's from England": "",
    "Is she a businesswoman?": "",
    "They're our friends": "",
    "How are your relative?": "",
    "Why are these clothes so cheap?": "",
    "You're kind": "",
    "They aren't stupid": "",
    "They aren't silly": "",
    "They aren't foolish": "",
    "It's a foolish mistake": "",
    "You need to start a new playlist": "",
    "Is he a professional teacher?": "",
    "Do you often see her?": "",
    "I'm tired": "",
    "Is the video so funny?": "",
    "Does she like this subject?": "",
    "Do his parents believe in God?": "",
    "What do they sell there?": "",
    "Do we learn English effectively?": "",
    "Your lessons are really good": "",
    "Do you work or study?": "",
    "Does she live there?": "",
    "This information is enough": "",
    "My mother is in the bathroom": "",
    "Do these things interest you?": "",
    "Is it a dangerous place?": "",
    "I'm Russian": "",
    "How long is the way?": "",
    "His son is lazy": "",
    "They're in Great Britain": "",
    "They're in the United Kingdom": "",
    "They're in the UK": "",
    "Does this result seem very good?": "",
    # So + при
    "It's so wonderful": "",
    # such a/an при + суш
    "such a wonderful teacher": "",
    "the exam": "",
    "ready for the exam": "",
    "this lesson - these lessons": "",
    "What else?": "",
    "I don't hurry": "",
    "Be in a hurry": "",
    "I'm not in a hurry": "",
    "What do you think about it?": "",
    "How often are they together?": "",
    "Does he do business?": "",
    "They're from America": "",
    "Is our knowledge enough?": "",
    "You're a good teacher": "",
    "It's a good idea": "",
    "It isn't cold": "",
    "It's warm": "",
    "His parents tell him everything": "",
    "It isn't a boring lesson": "",
    "Is this detail really so important?": "",
    "How much is it in that shop?": "",
    "How much does it cost in that shop?": "",
    "Why does your friend think so?": "",
    "Does that thing seem interesting?": "",
    "They aren't expensive": "",
    "Are these lessons really good?": "",
    "The boys aren't ar school": "",
    "Does his house look expensive?": "",
    "Does your classmate run very fast?": "",
    "Do these boys remember it very well?": "",
    "Why are these things necessary?": "",
    "Do you usually come early?": "",
    "Is she a very talented actress?": "",
    "How are his lessons?": "",
    "He's my father": "",
    "Are all these houses new?": "",
    "Do they fully support you?": "",
    "How good are these lessons?": "",
    "This results seem good": "",
    "The woman isn't a manager": "",
    "This phrase isn't important": "",
    "Where is this place?": "",
    "Does he play the guitar?": "",
    "My sister is in bed": "",
    "Does it really help you?": "",
    "When does it usually happen?": "",
    "Do those things interest her?": "",
    "Is this thing really necessary?": "",
    "How does she say it?": "",
    "Do they want to try to do it?": "",
    "He's my boss": "",
    "It"
    "It's an interesting offer": "",
    "Where does your father work?": "",
    "My computer is new": "",
    "Are they very good workers?": "",
    "Why is it so?": "",
    "My boss is very busy": "",
    "The offer isn't interesting at all": "",
    "He isn't at school": "",
    "Is he wrong?": "",
    "Why does it seem strange?": "",
    "Why is your teacher so angry?": "",
    "Does she need to rent a flat?": "",
    "Their plan isn't so bad": "",
    "I'm not tired": "",
    "It's a big mistake": "",
    "Does she feel good?": "",
    "Does this story seem short?": "",
    "Do you live together?": "",
    "Are we near this place?": "",
    "Are you here?": "",
    "Do you live in Russia?": "",
    "His lifestyle isn't healthy": "",
    "style os life": "",
    "My best friend needs support now": "",
    "Why is it so easy?": "",
    "Is the manager experienced enough?": "",
    "It's good": "",
    "This place isn't dangerous": "",
    "How interesting is this movie?": "",
    "How does it seem to you?": "",
    "Who is in the garden?": "",
    "What do you see?": "",
    "Is it a sunny day?": "",
    "Do you speak English?": "",
    "Do you get 500 dollars a month?": "",
    "Is this sentence difficult?": "",
    "Is it sunny?": "",
    "Her mother doesn't work there": "",
    "She works in another place": "",
    "He's a professional teacher": "",
    "How do they get this money?": "",
    "They aren't rich": "",
    "They're poor": "",
    "Where does your brother study?": "",
    "Is he a happy person?": "",
    "These result don't seem very good": "",
    "Where is the nearest supermarket?": "",
    "The story is so long": "",
    "Is your computer powerful?": "",
    "Does he read newspapers?": "",
    "How much is this toy?": "",
    "How much does this toy cost?": "",
    "Is this word new for you?": "",
    "Is it free or not?": "",
    "Who is this woman?": "",
    "The news isn't surprising at all": "",
    "Does she support this idea?": "",
    "It's easy": "",
    "Does their rest include it?": "",
    "Do his students feel progress?": "",
    "Do you do ir professionally?": "",
    "Is he very successful?": "",
    "I want to tell you this news": "",
    "I want to talk to you about this problem right now": "",
    "How well do you know English?": "",
    "How good is your knowledge?": "",
    "I know English well": "",
    "My knowledge is good": "",
    "How well do you work with this playlist?": "",
    "per cent": "",
    "I don't have considerable mistakes": "",
    "I haven't got considerable mistakes": "",
    "It's a difficult lesson": "",
    "It isn't a difficult lesson": "",
    "Is it a difficult lesson?": "",
    "The lesson is for strong students": "",
    "The lesson isn't for strong students": "",
    "Is the lesson for strong students?": "",
    "easy - weak": "",
    "It's his weak point": "",
    "It isn't his weak point": "",
    "Is it his weak point?": "",
    "It depends on him": "",
    "It doesn't depend on him?": "",
    "They combine work and studies": "",
    "They don't ...": "",
    "Do they combine work and studies": "",
    "His speech is full of mistakes": "",
    "His speech isn't ...": "",
    "Is his speech ...?": "",
    "It's cold outside": "",
    "It isn't cold outside": "",
    "Is it cold outside?": "",
    "It's warm inside": "",
    "It isn't warm inside": "",
    "Is it warm inside?": "",
    "This money is enough": "",
    "This money isn't enough": "",
    "Is this money enough?": "",
    "Do you try to learn English?": "",
    "This house doesn't look expensive": "",
    "This idea isn't new": "",
    "Why is this offer so attractive?": "",
    "Does his friend want to continue?": "",
    "It's important": "",
    "Does her mother stay at home?": "",
    "When do your patents come home?": "",
    "I'm American": "",
    "Are your parents at home?": "",
    "Does he want to do it one more time?": "",
    "Is he often angry?": "",
    "His parents don't tell him everything": "",
    "My father is there": "",
    "When do the lessons finish?": "",
    "Does she read magazines?": "",
    "Is it an innovative idea?": "",
    "Is this lesson very informative?": "",
    "This result seems good": "",
    "It isn't strange": "",
    "We're inside": "",
    "Is he busy at the moment?": "",
    "We're hard-working": "",
    "Does he often travel?": "",
    "Are they experienced?": "",
    "Who is present?": "",
    "They're in Russia": "",
    "These things aren't so important": "",
    "What's your weight?": "",
    "Does it help him?": "",
    "Why is the suit so expensive?": "",
    "You don't realize it": "",
    "Who are your friends?": "",
    "The tests in this book aren't easy": "",
    "Is this level basic?": "",
    "What does she have?": "",
    "Where does you son study?": "",
    "My mother is a doctor": "",
    "He's the best student": "",
    "When do the lessons start?": "",
    "How are his patients?": "",
    "Are your relatives in America?": "",
    "This idea is new": "",
    "Are they strange people?": "",
    "How does he get money?": "",
    "Do your colleagues get 500 dollars a month": "",
    "Does it interest you?": "",
    "Is it a pleasant feeling?": "",
    "Are the boys poor?": "",
    "How long is the lesson?": "",
    "Does he like those lessons?": "",
    "It's too short": "",
    "What ideas do you have?": "",
    "What are your ideas?": "",
    "How are these videos?": "",
    "Where is your instructor?": "",
    "How does he sell this product?": "",
    "Does she often fly to America?": "",
    "Do you help your parents?": "",
    "Why are we here?": "",
    "It's on the left": "",
    "Why does it happen so often?": "",
    "What magazines are popular now?": "",
    "Do your parents also think so?": "",
    "Why is she still there?": "",
    "who is right?": "",
    "That exercise is too easy": "",
    "What's the meaning of this word?": "",
    "My friend is 25 years old": "",
    "what is it?": "",
    "The book is boring": "",
    "Does he go to bed early?": "",
    "It's too difficult and I don't know what to do": "",
    "What does she need?": "",
    "Are your ideas similar?": "",
    "Do they come home early?": "",
    "When do you learn English?": "",
    "Where is the nearest supermarket?": "",
    "Do they know all the information?": "",
    "Do we show excellent results?": "",
    "Does she need to study more?": "",
    "Do they often say it?": "",
    "Why are you so sure that she's right?": "",
    "You're a good teacher": "",
    "This sentence seems very strange": "",
    "It's an old idea": "",
    "All your lessons are very useful": "",
    "He's a designer": "",
    "This thing interests me": "",
    "Is she a famous actress or not?": "",
    "Is he happy": "",
    "I don't think so": "",
    "Where is this file?": "",
    "He runs fast": "",
    "How long is one English lesson?": "",
    "You aren't happy": "",
    "Is she your classmate?": "",
    "How do you do these exercises?": "",
    "Do you need his help?": "",
    "Why do your parents watch TV so late?": "",
    "Does it look wonderful?": "",
    "Do you think so?": "",
    "I want to know it": "",
    "I need your answer": "",
    "General Question/ special question": "",
    "He wants to know English perfectly for many reasons": "",
    "Does he want to know English perfectly for many reasons": "",
    "Who wants to know English perfectly?": "",
    "How does he want to know English?": "",
    "What does he want to do?": "",
    "Why does he want to know English perfectly?": "",
    "What does he want to know?": "",
    "Does she go to the gym three time a week?": "",
    "Where does she go three times a week?": "",
    "How often does she go the gym?": "",
    "How many times a week does she go to the gym?": "",
    "My friend wants to discuss it tomorrow": "",
    "When does my friend want to discuss it?": "",
    "What does my friend want to discuss?": "",
    "It's five o'clock": "",
    "What time is it?": "",
    "What's the time?": "",
    "Is it right or not?": "",
    "How are you?": "",
    "His knowledge is really good": "",
    "How good is his knowledge?": "",
    "She wants to try to get this job": "",
    "What job does she want to try to get?": "",
    "Does she want to try to get this job?": "",
    "Who wants to try to get this job?": "",
    "What does she want to do?": "",
    "What does she want to try to do?": "",
    "What does she want to try to get?": "",
    "This job isn't well-paid": "",
    "Is he your best friend?": "",
    "Is your cousin at the airport?": "",
    "Our results aren't good enough": "",
    "Are the results satisfactory?": "",
    "Is he a strange person?": "",
    "These students are so talented": "",
    "It isn't free": "",
    "You need to pay": "",
    "His partners aren't reliable": "",
    "Are they only friends?": "",
    "It isn't an easy exam": "",
    "It isn't the best choice": "",
    "The tests in the book aren't so easy": "",
    "It's a short phrase": "",
    "I'm sure all these lessons are very useful": "",
    "Is he your boss?": "",
    "I know it's on the left": "",
    "It's his old car": "",
    "Is you brother a professional sportsman or not?": "",
    "The manager is very strange": "",
    "We aren't at home": "",
    "We're in the park": "",
    "Are we in the right place?": "",
    "Are your parents at home?": "",
    "It's too long": "",
    "It's an interesting thing": "",
    "Are they professional workers?": "",
    "I'm not at home": "",
    "I'm at work": "",
    "Is she your acquaintance?": "",
    "Are they good specialists?": "",
    "She's a manager": "",
    "Is it effective?": "",
    "It's difficult": "",
    "It's a big mistake": "",
    "My sister is in bed": "",
    "The story is too short": "",
    "All those houses are old": "",
    "Is his father angry": "",
    "They're our friends": "",
    "He's a talented student": "",
    "He's my classmate": "",
    "Her boyfriends isn't there": "",
    "My cousin is tired": "",
    "It's so bad": "",
    "Their ideas aren't innovative enough": "",
    "Are you afraid of difficulties?": "",
    "Is your brother in bed?": "",
    "I'm American but she's Russian": "",
    "Are those exercises difficult?": "",
    "Is it a safe place or not?": "",
    "Are your colleagues very professional?": "",
    "Is his progress slow?": "",
    "He thinks his progress isn't good enough": "",
    "It's normal": "",
    "Is it a rainy day?": "",
    "His English isn't fluent": "",
    "Are the boys busy at the moment?": "",
    "I'm very busy": "",
    "It's a very good lesson": "",
    "All his lessons are free": "",
    "Is it a warm day?": "",
    "Are we far from this place?": "",
    "It's good": "",
    "Is it an effective method or not?": "",
    "Is this thing really necessary?": "",
    "Is this detail really important?": "",
    "Are you in this place?": "",
    "The lesson is interesting": "",
    "She isn't American": "",
    "Is this book really interesting?": "",
    "Is she a talented actress?": "",
    "He isn't a rich person": "",
    "Is your friend tired?": "",
    "He's the best student": "",
    "My friend is ill": "",
    "This problem isn't big": "",
    "Is this manager experienced enough?": "",
    "Is our knowledge enough or not?": "",
    "Is he a successful businessman?": "",
    "He isn't a designer": "",
    "Are his lessons really effective?": "",
    "My computer is new": "",
    "Is it a popular channel?": "",
    "Are we near this place?": "",
    "Is this exercise easy?": "",
    "Is he often angry?": "",
    "The lesson is very difficult": "",
    "The test isn't easy": "",
    "This method is wonderful": "",
    "My English teacher is very professional": "",
    "Those problems aren't big": "",
    "This phrase isn't important": "",
    "Are the boys poor": "",
    "Are those exercises useless?": "",
    "His father is rich": "",
    "She isn't at home": "",
    "She's out": "",
    "It's on my bed": "",
    "Is it a well-paid job?": "",
    "Is his girlfriend American?": "",
    "The pen is black": "",
    # Past simple
    # v2
    # verbs -1 Regular verbs
    # if it's a regular verb , we add 'ed'
    # verb + ed
    # present simple
    # He works too much - He worked too much
    # 2-Irregular verbs
    # Say - said - said
    # He said it loudly(quiet - quietly)
    # go - went - gone
    "She wanted to find a better job": "",
    "He went there by car": "",
    "I lived there a long time ago": "",
    "They lived happily": "",
    "They played in one team": "",
    "I played football yesterday": "",
    "I tried to help him": "",
    "I tried to pass the exam": "",
    "I needed more time": "",
    "I needed to find it urgently": "",
    "She helped me a lot": "",
    "That experience helped me a lot": "",
    "It happened to me /us /him / her / them/": "",
    "Strange thing happened to my boss": "",
    "I remembered it at last": "",
    "I remembered the meaning of this word": "",
    "She closed her eyes": "",
    "I closed the door": "",
    "I opened the door": "",
    "She opened her eyes": "",
    "I decided to learn English here": "",
    "We decided to meet tomorrow": "",
    "She asked me to wait for her": "",
    "I asked her to help me": "",
    "I feel progress": "",
    "I make progress": "",
    "I see progress": "",
    "I'm grateful to you for it": "",
    "these free English lessons": "",
    "instead of": "",
    "a mistake": "",
    "I worked hard": "",
    "She said it loudly": "",
    "I needed more time": "",
    "They wanted to find a better place": "",
    "We decided to meet tomorrow": "",
    "I remembered the meaning of this word": "",
    "We lived in America": "",
    "I played football yesterday": "",
    "I needed to find urgently": "",
    "She needed your support": "",
    "I closed the door": "",
    "It happened to me": "",
    "She worked too little": "",
    "They played in one team": "",
    "It happened to his family": "",
    "She tried to find her mistakes": "",
    "I decided to become a businessman": "",
    "He decided to buy an expensive car": "",
    "He worked too much": "",
    "We played together": "",
    "A strange thing happened to my boss": "",
    "They lived unhappily": "",
    "I decided to learn English here": "",
    "I decided to watch all the videos": "",
    "She opened her eyes": "",
    "We wanted better lessons": "",
    "I remembered the meaning of this phrase": "",
    "Your lesson helped me a lot": "",
    "I needed your help": "",
    "That experience helped me a lot": "",
    "I asked her to help me": "",
    "He went there by car": "",
    "I opened the door": "",
    "I went there by bus": "",
    "I tried to pass test": "",
    "I needed to pass that exam": "",
    "I tried to help him": "",
    "He asked me to read it urgently": "",
    "I remembered everything": "",
    "It happened a long time ago": "",
    "We passed the test": "",
    "They failed the test": "",
    "An interesting thing happened to our company": "",
    "I lived there a long time ago": "",
    "I remembered it at last": "",
    "She wanted to find a better job": "",
    "She helped me a lot": "",
    "They said it very quietly": "",
    "I remembered all the words": "",
    "She closed her eyes": "",
    "She asked me to wait for her": "",
    "say - said - said": "",
    "He said it very loudly": "",
    "She said it very quietly": "",
    "I said it again and again": "",
    "go -went - gone": "",
    "I went to school": "",
    "I went to the park": "",
    "They went there": "",
    "know - knew - known": "",
    "We knew it very well": "",
    "We knew it perfectly": "",
    "I knew how to say it": "",
    "I knew the answer": "",
    "I knew the right answer": "",
    "I knew the correct answer": "",
    "get - got - got": "",
    "I got your message": "",
    "We got all the necessary information": "",
    "I got up very early": "",
    "have - had - had": "",
    "He had everything": "",
    "He had a strange offer": "",
    "Have a good time": "",
    "We had a good time": "",
    "We had a great time together": "",
    "understand - understood - understood": "",
    "I understood you very well": "",
    "I understood you without any problems at all": "",
    "I understood everything": "",
    "read - read - read": "",
    "I read a book in English": "",
    "I read you message": "",
    "I read a very interesting article": "",
    "I read that text": "",
    "Write - wrote - written": "",
    "I wrote a message": "",
    "I wrote a letter": "",
    "I wrote a very long message": "",
    "Do - did - done": "",
    "I did it": "",
    "I did everything": "",
    "He did a very good thing": "",
    "I did my homework": "",
    "She did housework": "",
    "make - made - made": "",
    "I made a mistake": "",
    "He made some mistakes": "",
    "He made several mistakes": "",
    "They made a terrible mistake": "",
    "I wrote a very long message": "",
    "I understood you without any problems at all": "",
    "I read a very interesting article": "",
    "I got up very early": "",
    "I knew how to translate that text": "",
    "He had everything": "",
    "We got all the necessary information": "",
    "I knew the correct answer": "",
    "They gor all the money": "",
    "I went there": "",
    "I read that text": "",
    "I understood you very well": "",
    "We understood each other": "",
    "I understood everything": "",
    "I read a book in English": "",
    "He had a strange offer": "",
    "I read your message": "",
    "They did it again and again": "",
    "I went to work yesterday": "",
    "I knew too little to pass that exam": "",
    "I got your message": "",
    "We knew it very well": "",
    "I got your letter": "",
    "He said it one more time": "",
    "She said it very quietly": "",
    "I made several mistakes": "",
    "I understood him immediately": "",
    "She read that document": "",
    "I did what you wanted": "",
    "I did my homework": "",
    "He did a strange thing": "",
    "I went to school": "",
    "I knew the answer": "",
    "She made a terrible mistake": "",
    "I said it again and again": "",
    "We knew it perfectly": "",
    "She did housework": "",
    "I went to the park": "",
    "He said it very loudly": "",
    "I knew very little": "",
    "He had a big problem": "",
    "We had a great time together": "",
    "I wrote a message": "",
    "We had a good time": "",
    "I knew how to say it": "",
    "He made too many mistakes": "",
    "He gor up too late": "",
    "She said everything": "",
    "I went to that place": "",
    "I knew what to say": "",
    "I wrote a letter": "",
    "I did everything": "",
    "one - the first": "",
    "two - the second": "",
    "an irregular verb": "",
    "a regular verb": "",
    "tell - told - told": "",
    "He told me this story": "",
    "She told me how to do it": "",
    "He told me call her": "",
    "They told me everything": "",
    "think - thought - thought": "",
    "I thought about this problem": "",
    "We thought about the future of this company": "",
    "I thought so": "",
    "come - came - come": "",
    "go / come to ( go / come  ) home": "",
    "He came to the party": "",
    "They came to the meeting": "",
    "I came home": "",
    "She came back": "",
    "See - saw - seen": "",
    "I saw progress": "",
    "I saw her near that place": "",
    "I saw my mistake at last": "",
    "give - gave - given": "",
    "He gave me this information": "",
    "They gave me this file": "",
    "Take - took - taken": "",
    "Take an offer": "",
    "We need the second form to form past simple": "",
    "It's ok": "",
    "I took their offer": "",
    "We took him /her/them with us": "",
    "They took her with them": "",
    "find - found - found": "",
    "I found a good job": "",
    "She found a well-paid job": "",
    "I found my keys on the floor": "",
    "become - became - become": "",
    "She became very successful": "",
    "He became a very successful businessman": "",
    "She became so popular": "",
    "He became such a popular singer": "",
    "such a/an + adjective + noun": "",
    "so + adjective": "",
    "feel - felt - felt": "",
    "I felt good": "",
    "I felt bad": "",
    "I felt better": "",
    "I felt much better": "",
    "I felt (That) we had a big problem": "",
    "I felt I had some mistakes": "",
    "Put - put - put": "",
    "I put it on the table": "",
    "I put it on the desk": "",
    "I put my bag on the floor": "",
    "I saw progress": "",
    "They gave me this file": "",
    "We felt that we had such a big problem": "",
    "We took him with us": "",
    "I saw my mistakes at last": "",
    "We thought about the future of our company": "",
    "They gave us those materials": "",
    "I took her with me": "",
    "I gave him 200 dollars": "",
    "two hundred": "",
    "two thousand": "",
    "two million": "",
    "I put it near my computer": "",
    "They came to the meeting": "",
    "I felt bad": "",
    "She became very successful": "",
    "He became an English teacher": "",
    "I felt I had only correct answers": "",
    "He saw her in the park": "",
    "He told me call her": "",
    "I thought so": "",
    "I found my wallet": "",
    "She found a well-paid job": "",
    "I found my keys on the floor": "",
    "We felt we had big problems": "",
    "I thought about this problem": "",
    "She found her passport": "",
    "I told her only some things": "",
    "It became a well-known fact": "",
    "He told me this story": "",
    "I felt better": "",
    "I put my bag on the floor": "",
    "She came back": "",
    "He became a successful businessman": "",
    "double cc and ss": "",
    "I felt I knew everything": "",
    "I felt I had some mistakes": "",
    "We saw his excellent results": "",
    "He gave me this information": "",
    "I found a good job": "",
    "I took their offer": "",
    "I want to know English like educated native speakers": "",
    "I felt we had a big problem": "",
    "I felt real progress": "",
    "I put it on the table": "",
    "She felt progress immediately": "",
    "I felt much better": "",
    "He became such a popular singer": "",
    "She told me how to do it": "",
    "She became a very successful businesswoman": "",
    "They told me everything": "",
    "He told me how to learn English fast": "",
    "We thought so, too": "",
    "She told me to call him": "",
    "I put it on the desk": "",
    "I thought about our future": "",
    "I felt good": "",
    "He came to us": "",
    "She became so popular": "",
    "They took her with them": "",
    "He came to the party": "",
    "We saw her near that place": "",
    "I came home": "",
    "We also thought so": "",
    "She told me her secret": "",
    "He came to the party": "",
    "explain to": "",
    "be - was/were - been": "",
    # I/He/She/It was
    # We/You/They were
    "We were surprised by the news": "",
    "I was shocked": "",
    "You were the best student": "",
    "They were so inexperienced": "",
    "He was so shy": "",
    "She was a leader": "",
    "It was a very difficult task": "",
    "Show - showed - shown": "",
    "He showed me his excellent results": "",
    "I showed him my progress": "",
    "begin - began - begun": "",
    "The lesson began an hour ago": "",
    "The meeting began two hours ago": "",
    "The conference began the day before yesterday": "",
    "Sit - sat - sat": "",
    "He sat down": "",
    "He sat on a chair": "",
    "He sat in an armchair": "",
    "Stand - stood - stood": "",
    "I stood up": "",
    "He sat down and then he stood up": "",
    "Hear - heard - heard": "",
    "I heard that story for the first time": "",
    "I often heard it when I was there": "",
    "lose - lost - lost": "",
    "She lost her keys": "",
    "He lost his wallet": "",
    "I lost concentration": "",
    "speak - spoke - spoken": "",
    "I spoke English a lot": "",
    "As you understand we spoke English": "",
    "He spoke Spanish": "",
    "pay - paid - paid": "",
    "I paid for her": "",
    "I paid for this service": "",
    "We paid for the delivery": "",
    "Meet - met - met": "",
    "We met in a local restaurant": "",
    "I met her by chance": "",
    "I met her by accident": "",
    "I met her almost every day": "",
    "I often met new words": "",
    "I met him there for the second time": "",
    "We met in a local restaurant": "",
    "I was shocked": "",
    "I was really surprised": "",
    "I was surprising for us": "",
    "I paid for her": "",
    "I sat on a soft chair": "",
    "She sat in an armchair": "",
    "He lost his wallet": "",
    "He lost his passport": "",
    "He sat down and then he stood up": "",
    "He was such an experienced worker": "",
    "I stood up": "",
    "The lesson began an hour ago": "",
    "She often heard it when she was young": "",
    "I was shocked by the results": "",
    "to be surprised/ shocked by/at": "",
    "I lost concentration": "",
    "I spoke English a lot": "",
    "The meeting began two hours ago": "",
    "We were surprised by the news": "",
    "I heard that story for the first time": "",
    "I heard loud music": "",
    "He was their leader": "",
    "She showed us her achievements": "",
    "We paid for the delivery": "",
    "I met her almost every day": "",
    "I often heard it when I was there": "",
    "She was a leader": "",
    "He sat down": "",
    "I met him there for the second time": "",
    "I met her by chance": "",
    "As you understand we spoke English": "",
    "It was such a difficult task": "",
    "You were the best student": "",
    "He was a very talented boy": "",
    "It was a very important test": "",
    "As you know I met him three days ago": "",
    "He paid for us": "",
    "She lost her keys": "",
    "We met each other yesterday": "",
    "The lesson began on time": "",
    "She spoke Spanish": "",
    "I paid for this service": "",
    "She lost her bag": "",
    "He sat on a chair": "",
    "He showed me his excellent results": "",
    "He was so shy": "",
    "They were so inexperienced": "",
    "I often met new words": "",
    "I showed him my progress": "",
    "We heard his voice": "",
    "It was a very big problem": "",
    "I paid for everything": "",
    "I was the best student": "",
    "The girl was very shy": "",
    "The conference began the day before yesterday": "",
    "It was a big success": "",
    "They were together": "",
    "The place was so dangerous": "",
    "It was such a dangerous place": "",
    "We met at last": "",
    "boy - bought - bought": "",
    "He bought a flat": "",
    "He bought a very reliable car": "",
    "She bought a very powerful computer": "",
    "sell - sold - sold": "",
    "He sold his flat": "",
    "She sold her car": "",
    "she sold it for 200 dollars": "",
    "Choose - chose - chosen": "",
    "I chose your lessons": "",
    "I chose this method": "",
    "She chose such a beautiful present": "",
    "send - sent - sent": "",
    "I sent her a message": "",
    "He sent me an e-mail": "",
    "We sent her a couple of letters": "",
    "eat -ate - eaten": "",
    "I ate everything": "",
    "I ate it for breakfast": "",
    "He ate meat and fish": "",
    "I ate some fish": "",
    "I ate two sandwiches": "",
    "drink - drank - drunk": "",
    "She drank milk": "",
    "He drank a glass of wine": "",
    "I drank a glass of juice": "",
    "I drank tea": "",
    "fly - flew - flown": "",
    "I flew ro New York": "",
    "They flew very high": "",
    "She flew to America": "",
    "go/come/fly home": "",
    "The bird flew away": "",
    "sleep - slept - slept": "",
    "I slept very long": "",
    "She slept normally": "",
    "I slept in my new room": "",
    "He slept like a baby": "",
    "swim - swam -swum": "",
    "I swam in the sea": "",
    "We swam in the river": "",
    "He swam in the lake": "",
    "cost - cost - cost": "",
    "It cost too much": "",
    "It cost a lot": "",
    "The computer cost 500 dollars": "",
    "He sold his old car": "",
    "I slept like a baby": "",
    "I slept in my new room": "",
    "He sent me two e-mails": "",
    "I sent her an e-mail": "",
    "We flew to another city": "",
    "I bought it for 300 dollars": "",
    "I chose your lessons": "",
    "I drank a glass of water": "",
    "I ate two sandwiches": "",
    "She chose such a beautiful present": "",
    "She sold it for 200 dollars": "",
    "I chose your method": "",
    "She sent him two messages": "",
    "I ate my portion": "",
    "She slept normally": "",
    "I slept very long": "",
    "She drank milk": "",
    "I ate some fish": "",
    "He ate meat and fish": "",
    "We swam in the swimming pool": "",
    "He slept little": "",
    "She bought a very powerful computer": "",
    "We ate together": "",
    "The bird flew away": "",
    "The computer cost 500 ( five hundred ) dollars": "",
    "She flew to America": "",
    "He drank a glass of wine": "",
    "He swam in the lake": "",
    "I drank a cup of coffee": "",
    "She sold her car": "",
    "It cost a lot": "",
    "It cost too much": "",
    "I ate enough": "",
    "He ate everything": "",
    "I drank tea": "",
    "I bought one more computer": "",
    "I ate it for breakfast": "",
    "I drank a glass of juice": "",
    "We chose another room": "",
    "I chose this channel": "",
    "He bought a flat": "",
    "We sent her a couple of letters": "",
    "She bought a new car": "",
    "He bought a very beautiful dress for her": "",
    "He drank some milk": "",
    "I flew to New York": "",
    "He slept too long": "",
    "I sent her a message": "",
    "The ticker cost 20(twenty) dollars": "",
    "They flew very high": "",
    "She ate only vegetables": "",
    "I swam in the sea": "",
    "He sold his flat": "",
    "He bought a very reliable car": "",
    "He sent her flowers": "",
    "We drank a carton of milk": "",
    "We swam in the river": "",
    "I drank a cop of tea": "",
    "We bought a bottle of milk": "",
    "I want to tell you that we chose another place": "",
    "steal - stole - stolen": "",
    "They stole this information": "",
    "He stole her bag": "",
    "They stole his idea": "",

}