slovar = {
    # i need it
    "i need your help": "",
    "i need your advice": "",
    "i need your recommendation": "",
    "i need more practice": "",
    "i need a good teacher": "",
    "i need more lessons": "",
    "i need these lessons": "",
    "i need a pen": "",
    "i need a pencil": "",
    "i need money": "",
    "i need more money": "",
    "i need to learn English": "",
    "i need to find good job": "",
    "i need to know it right now": "",
    "i need to check it": "",
    "i need to go to that place": "",
    "i need to call him": "",
    "i need to visit her": "",
    "i need to work very hard": "",
    "i need to study more": "",
    "i need to remember all these words and phrases": "",
    "i need to save this document": "",
    "i need to save this file": "",
    "i need to write a letter": "",
    "i need to write it down": "",
    "i need to watch this lesson one more time": "",
    "i need to watch this lesson again": "",
    "i need to watch these lessons": "",
    "i need to watch that movie": "",
    "i need to read these books": "",
    "i need to train every day": "",
    "i need to study English regularly": "",
    "we need more exercises": "",
    "you need more rest": "",
    "they need more lessons": "",
    "he needs more money": "",
    "she needs more practice": "",
    "my friend needs to learn English": "",
    "my brother needs to go there": "",
    "my friends need to buy this thing": "",
    "my parents need to work more": "",
    "i need to do this thing now": "",
    "i need to study more": "",
    "he needs to do more physical exercises": "",
    "i need to write it down": "",
    " need to watch this lesson one more time": "",
    "i need to watch that movie": "",
    "my friend needs to learn English": "",
    "we need to visit him": "",
    "i need to watch your English": "",
    "you need more rest": "",
    "i need to relax more": "",
    "i need to have more rest": "",
    "they need more lessons": "",
    "he needs more money": "",
    "i need to find it": "",
    "i need to say it": "",
    "i need to go to America": "",
    "we need more exercises": "",
    "i need to try it": "",
    "i need to train every day": "",
    "i need to save this file": "",
    "i need to visit her": "",
    "i need to translate this text": "",
    "my brother needs to go there": "",
    "i need to go to work": "",
    "i need to call him": "",
    "i need to study English more regularly": "",
    "i also need to know it": "",
    "i need to go to the gym": "",
    "he needs to go to China": "",
    "i need to go to that place": "",
    "i need to find a good job": "",
    "i need to listen to this song": "",
    "i need to understand it right now": "",
    "i need to read these books": "",
    "my parents need to work more": "",
    "she needs more practice": "",
    "i need to watch these lessons": "",
    "i need to see him": "",
    "i need to write a latter": "",
    "i need to relax": "",
    "i need to have a rest": "",
    "i need to tell you about this problem": "",
    "i need to try to do it": "",
    "i need to save this document": "",
    "i need to remember it": "",
    "i need to order it": "",
    "my friends need to buy this thing": "",
    "i need to check it": "",
    "i need to know all the information": "",
    "i go to China": "",
    "i go the united states": "",
    "i go the united kingdom": "",
    "i want this thing": "",
    "i want to buy this thing": "",
    "she wants to speak English fluently": "",
    "my friend wants to translate text": "",
    "i want a cup of tea": "",
    "i'd like a cup of tea": "",
    "i'd like to drink a cup of tea": "",
    "she'd like to visit this place": "",
    "they'd like to order it online": "",
    # i / we / you / don't +г
    # he / she / it doesn't + г
    "i don't understand": "",
    "it doesn't seem interesting": "",
    "this idea doesn't seem interesting": "",
    "my parents don't want to sell this house": "",
    "i need you help": "",
    "i need to check it": "",
    "i need to do it again": "",
    "she needs to go shopping": "",
    "my cousin needs to see it": "",
    "she often calls us": "",
    "she often calls you": "",
    "she often calls him": "",
    "she often calls her": "",
    "she often calls them": "",
    "she often calls me": "",
    "she has a car": "",
    "she has a good car": "",
    "he has a big house": "",
    "i need your help": "",
    "i really need your help": "",
    "i'd like to hear this story": "",
    "i want to listen to this song": "",
    "my brother wants to try to do it": "",
    "he wants to learn English to communicate with people from other countries": "",
    "i also like it": "",
    "i like it, too": "",
    "i need to know all the information": "",
    "i need to know everything": "",
    "my father does business": "",
    "my sister really likes it": "",
    "she often washes up the dishes": "",
    "mu sister often flies to the united states": "",
    "he reads a lot": "",
    "he doesn't read much": "",
    "i know a lot": "",
    "i don't know much about this problem": "",
    "my brother has many friends": "",
    "it often happens": "",
    "i see you'd like to live here": "",
    "my brother wants to study in another place": "",
    "my aunt wants to sell her house": "",
    "i don't learn English there": "",
    "i prefer learn English here": "",
    "she doesn't teach English": "",
    "she teaches maths": "",
    "i'd like to read a book in English": "",
    "my brother would like to try to do it": "",
    "i'd like to eat fish": "",
    "we'd like to play football": "",
    "i'd like to talk to you": "",
    "i'd like to tell you everything": "",
    "i'd like to work more": "",
    "i'd like to fly to New York": "",
    "she'd like to learn English here": "",
    "my brother wants to try to do it": "",
    "i'd like to get more money": "",
    "i don't watch her channel every day": "",
    "we'd like to invite you to the party": "",
    "i'd like to have my own business": "",
    "i want to do it now but very well": "",
    "my sister wants to buy this dress": "",
    "i'd like to thank you": "",
    "i'd like to hear this story": "",
    "i'd like to eat meat": "",
    "i'd like to watch your channel every day": "",
    "i don't go to school": "",
    "i go to university": "",
    "i'd like to drink a cup of tea": "",
    "i don't buy any newspapers or magazines": "",
    "i read them online": "",
    "we'd like to learn English here": "",
    "she doesn't say it": "",
    "she works a lot": "",
    "she wants to work less": "",
    "i don't live in Moscow": "",
    "i live in New York": "",
    "he goes to work by car": "",
    "i'd like to go the party": "",
    "i'd like to become a manager": "",
    "i don't live in England": "",
    "they'd like to call us": "",
    "i want to help you": "",
    "i'd like to thank you for your help": "",
    "i'd like to thank you for support": "",
    "i'd like to talk to you right now": "",
    "my friend wants to study in another place": "",
    "my friends don't order it online": "",
    "they buy it here": "",
    "i'd like to live in another country": "",
    "i want to learn English": "",
    "i don't go to work": "",
    "i don't work": "",
    "i stay at home": "",
    "i'd like to live abroad": "",
    "my boss doesn't want to do it": "",
    "it doesn't help me": "",
    "i want to read this book": "",
    "i want to live abroad": "",
    "i don't go to work every day": "",
    "i work from home": "",
    "i'd like to talk about this problem": "",
    "i'd really like to thank you": "",
    "i'd like to drink a cup of tea": "",
    "i don't go to university": "",
    "i go to work": "",
    "i don't understand native speakers": "",
    "my teacher doesn't like those lessons": "",
    "he likes these lessons": "",
    "my sister goes to school on foot": "",
    "my sister walks to school": "",
    "next": "",
    "i want to call him": "",
    "thanks": "",
    "thank you": "",
    "my sister would like to teach English": "",
    "i want to help my friend": "",
    "we want to know all the information": "",
    "she doesn't watch that channel": "",
    "she watches this channel": "",
    "my sister goes to school by car": "",
    "i'd like to be a manager": "",
    "i'd like to speak English very well": "",
    "he doesn't eat little": "",
    "he eats a lot": "",
    "i want to have a car": "",
    "my sitter would like to buy this dress": "",
    "she wants to know all the information": "",
    "he'd like to get this job": "",
    "i want to buy this thing": "",
    "i like it": "",
    "that lessons doesn't help": "",
    "this lesson helps": "",
    "all your lessons really help": "",
    "i don't play tennis": "",
    "she plays it": "",
    "she doesn't visit him": "",
    "she works hard": "",
    "she doesn't have free time": "",
    "i want to go to Italy next year": "",
    "my brother doesn't want to do this thing": "",
    "i'd like to be a teacher": "",
    "my sister also wants to teach English": "",
    "they want to call me": "",
    "i want to have a flat": "",
    "it doesn't interest me": "",
    "i'd like to have more free time": "",
    "i want to visit that place one more time": "",
    "i'd like to listen to this song": "",
    "we want to know all the information": "",
    "my brother doesn't understand me": "",
    "my relative wats to play this game": "",
    "we usually play different game": "",
    "we want to thank you": "",
    "my friend doesn't go to school on foot": "",
    "my friend doesn't walk to school": "",
    "we want to have our own business": "",
    "she doesn't like that channel": "",
    "she likes this channel": "",
    "i don't eat meat but i eat fish": "",
    "you don't understand it": "",
    "i'd like to listen to it": "",
    "i want to visit this place": "",
    "i'd like to learn English very hard": "",
    "she wants to work more": "",
    "i want to work less": "",
    "i'd like to hear this story right now": "",
    "i'd like to drink a glass of water": "",
    "her relative wants to rent a flat": "",
    "my uncle doesn't want to call her": "",
    "i'd like to visit that place": "",
    "i'd like to fo to that restaurant": "",
    "we'd like to go to the party": "",
    "i'd like to know English very well": "",
    "i'd like to hear all the story": "",
    "i want a cup of coffee": "",
    "i think i'd like to work more": "",
    "i want to go to America next month": "",
    "we'd like to talk to you": "",
    "she'd like to become an English teacher": "",
    "i want to see it": "",
    "we want to see this thing": "",
    "my relative wants to study abroad": "",
    "i'd like to order it": "",
    "i want to have a house": "",
    "i'd like to translate this word": "",
    "we'd like to translate thi phrase": "",
    "i don't speak English fluently": "",
    "i try to learn it": "",
    "her cousin doesn't want to do it right now": "",
    "he wants to do it later": "",
    "i'd like to visit this places": "",
    "i want to watch your channel every day": "",
    "we want to learn English here": "",
    "i'd really like to thank you for your help": "",
    "i don't buy food": "",
    "my parents buy all the food": "",
    "they'd like to join us": "",
    "i speak English": "",
    "i speak Russian": "",
    "i understand": "",
    "i understand you": "",
    "i understand you very well": "",
    "i know English": "",
    "i know it": "",
    "i work": "",
    "i work there": "",
    "i study": "",
    "i study at school": "",
    "i study at university": "",
    "i study there": "",
    "i read": "",
    "i read books": "",
    "i read English books": "",
    "i live in Russia": "",
    "i want it": "",
    "i play": "",
    "i play football": "",
    "i do it well": "",
    "i have a car": "",
    "i have a house": "",
    "i like English": "",
    "i like it": "",
    "i live in Moscow": "",
    "we speak English": "",
    "you understand": "",
    "they read English books": "",
    "i know English": "",
    "we want it": "",
    "you know it": "",
    "they have house": "",
    "i like it": "",
    "we like it": "",
    "they like it": "",
    "you like it": "",
    "i work": "",
    "he works": "",
    "i speak English": "",
    "she speaks English": "",
    "it helps me": "",
    "it helps you": "",
    "it really helps": "",
    "he lives in London": "",
    "he works hard": "",
    "he works very hard": "",
    "she works a lot": "",
    "he plays computer games": "",
    "i like it": "",
    "she likes it": "",
    "he likes it": "",
    "she likes this lesson": "",
    "she likes these lessons": "",
    "i like this lesson": "",
    "i like your lessons": "",
    "i like these lessons": "",
    "i really like it": "",
    "i really like these lessons": "",
    "he swims very well": "",
    "she understands this lesson": "",
    "he remembers it": "",
    "it works well": "",
    "she speaks Spanish": "",
    "she speaks English": "",
    "i speak English fluently": "",
    "he speaks English fluently": "",
    "he wants it": "",
    "she sees it": "",
    "she understands you": "",
    "it seems interesting": "",
    "she eats meat": "",
    "he eats fish": "",
    "it happens": "",
    "he plays tennis": "",
    "she plays different games": "",
    "he plays the guitar": "",
    "i get up early": "",
    "she gets up early": "",
    "i get up late": "",
    "he gets up late": "",
    "i get up very early": "",
    "he gets up very late": "",
    "i work there": "",
    "we know it very well": "",
    "you understand me": "",
    "they live in England": "",
    "he works in London": "",
    "she works a lot": "",
    "it really helps me": "",
    "i go there": "",
    "she goes there": "",
    "i do it well": "",
    "she does it well": "",
    "i do housework": "",
    "she does housework": "",
    "i go to work": "",
    "he goes to work": "",
    "she goes to work": "",
    "i go to school": "",
    "he goes to school": "",
    "she goes to school": "",
    "i go to the park": "",
    "he goes to the park": "",
    "she goes to the park": "",
    "i go the cinema": "",
    "i go the theatre": "",
    "he goes the cinema": "",
    "she goes the cinema": "",
    "he goes the theatre": "",
    "she goes the theatre": "",
    "i go there": "",
    "i often go there": "",
    "i often do it": "",
    "he often goes there": "",
    "she often does it": "",
    "i teach English": "",
    "she teaches English": "",
    "i watch tv": "",
    "i watch tv every day": "",
    "he watches tv very day": "",
    "i wash up the dishes": "",
    "she washes up the dishes": "",
    "i usually relax in the evening": "",
    "she usually relaxes in the evening": "",
    "i play football": "",
    "he plays football": "",
    "we play computer games": "",
    "he plays computer games": "",
    "i often fly to America": "",
    "he often flies to America": "",
    "she often flies to England": "",
    "i often fly to the united states": "",
    "i often go to China": "",
    "he often flies to the united states": "",
    "she often goes to China": "",
    "he often cries": "",
    "she tries to do it": "",
    "he tries to help him": "",
    "i try to learn English": "",
    "he tries to learn Spanish": "",
    "i have a car": "",
    "he has a car": "",
    "i have a computer": "",
    "she has a computer": "",
    "i have a house": "",
    "he has a house": "",
    "i have a flat": "",
    "she has a flat": "",
    "i have many friends": "",
    "he has many friends": "",
    "i have a job": "",
    "she has a job": "",
    "he has a girlfriend": "",
    "she has a boyfriend": "",
    "this lesson helps me": "",
    "these lessons help me": "",
    "my sister lives in Russia": "",
    "it costs 20 pounds": "",
    "it is 20 pounds": "",
    "this dress costs 50 dollars": "",
    "this dress is 50 dollars": "",
    "my friend often sees him": "",
    "my teacher knows English very well": "",
    "my best friend plays basketball": "",
    "my brother lives in this house": "",
    "my sister lives in that house": "",
    "your idea seems interesting": "",
    "she likes this idea": "",
    "Kate likes this idea": "",
    "Max lives in this city": "",
    "i often listen to music": "",
    "my sister often listens to music": "",
    "my father has a job": "",
    "my mother has a car": "",
    "my sister goes to school": "",
    "my brother goes to work ": "",
    "our teacher knows English very well": "",
    "i also think so": "",
    "i think so, too": "",
    "our father also thinks so": "",
    "our father thinks so, too": "",
    "they teacher says it": "",
    "their teacher says so": "",
    "i have a brother": "",
    "my brother goes t school": "",
    "we have an uncle": "",
    "our uncle speaks English fluently": "",
    "you have a house": "",
    "your house looks beautiful": "",
    "their teacher says so": "",
    "his parent works there": "",
    "his mother teaches french": "",
    "her father does business": "",
    "she eats fish": "",
    "they read English books": "",
    "i know it": "",
    "they read": "",
    "i study at school": "",
    "you know English well": "",
    "we understand you very well": "",
    "you speak Russian": "",
    "i play": "",
    "i have a house": "",
    "they know it": "",
    "we know English very well": "",
    "they a have house": "",
    "they work": "",
    "they have a car": "",
    "they speak English": "",
    "we study at school": "",
    "you study at school": "",
    "we work there": "",
    "we work": "",
    "i live in Moscow": "",
    "they know English very well": "",
    "i study at university": "",
    "you have a house": "",
    "they read English books": "",
    "i read books": "",
    "they live in Moscow": "",
    "we read English books": "",
    "we play": "",
    "we understand": "",
    "you have a car": "",
    "they study there": "",
    "i understand": "",
    "we live in Russia": "",
    "i work there": "",
    "you play football": "",
    "they do ot well": "",
    "they study": "",
    "i like English": "",
    "you play": "",
    "we understand you": "",
    "we play football": "",
    "i work": "",
    "they speak Russian": "",
    "i study": "",
    "you work there": "",
    "we like English": "",
    "we read books": "",
    "we have a car": "",
    "they study at university": "",
    "they study at school": "",
    "they want it": "",
    "we do it well": "",
    "we know it": "",
    "they understand": "",
    "i study there": "",
    "you study at university": "",
    "i play football": "",
    "i do it well": "",
    "i have a car": "",
    "we have a house": "",
    "they play": "",
    "we study": "",
    "you read English books": "",
    "we read English books": "",
    "we study there": "",
    "they understand you": "",
    "i know English very well": "",
    "you speak English": "",
    "i live in Russia": "",
    "they work there": "",
    "we read": "",
    "i understand you": "",
    "we speak English": "",
    "you read": "",
    "they know English well": "",
    "you understand": "",
    "you know English": "",
    "you study": "",
    "i read English books": "",
    "you want it": "",
    "we speak Russian": "",
    "i live in Russia": "",
    "we know English well": "",
    "i speak English": "",
    "you read books": "",
    "you read English books": "",
    "you know it": "",
    "they read books": "",
    "you do it well": "",
    "you play": "",
    "we live in Moscow": "",
    "they know English": "",
    "they play football": "",
    "i know English": "",
    "i speak Russian": "",
    "they understand you very well": "",
    "they like English": "",
    "you live in Moscow": "",
    "you work": "",
    "you like English": "",
    "i want it": "",
    "i live in Russia": "",
    "you know English very well": "",
    "i read": "",
    "she understands you": "",
    "she really likes it": "",
    "he reads English books": "",
    "it seems interesting": "",
    "she remembers it": "",
    "she reads English books": "",
    "he understand you": "",
    "she works well": "",
    "she works there": "",
    "he speaks Russian": "",
    "he works well": "",
    "she gets up late": "",
    "she speaks English": "",
    "he sees it": "",
    "he helps you": "",
    "he likes this lesson": "",
    "it happens": "",
    "he plays": "",
    "he really likes it": "",
    "i really like it": "",
    "he plays different games": "",
    "he lives in Russia": "",
    "he understands you very well": "",
    "he gets up very late": "",
    "she plays different games": "",
    "she speaks Russian": "",
    "she likes English": "",
    "he knows English very well": "",
    "she speaks Spanish": "",
    "she understands you very well": "",
    "he knows English": "",
    "he knows English well": "",
    "he lives in Moscow": "",
    "he works very hard": "",
    "he eats meat": "",
    "she helps me": "",
    "she likes this lesson": "",
    "she knows English well": "",
    "he likes your lessons": "",
    "she works very hard": "",
    "she likes it": "",
    "she understands": "",
    "she knows it": "",
    "he works a lot": "",
    "he works hard": "",
    "he works too much": "",
    "he swims very well": "",
    "he gets up early": "",
    "he works in London": "",
    "she likes you lessons": "",
    "he speaks English": "",
    "she works": "",
    "he likes your lessons": "",
    "he understands": "",
    "she plays tennis": "",
    "she knows English": "",
    "she wants it": "",
    "she reads books": "",
    "he plays tennis": "",
    "he knows it": "",
    "she lives in Russia": "",
    "he likes English": "",
    "she sees it": "",
    "he helps me": "",
    "she eats fish": "",
    "he likes this lesson": "",
    "he works there": "",
    "she likes your lessons": "",
    "he plays football": "",
    "she reads": "",
    "he plays computer games": "",
    "he works": "",
    "he reads books": "",
    "she gets up very early": "",
    "she swims very well": "",
    "he speaks English fluently": "",
    "he wants it": "",
    "she likes this lesson": "",
    "he likes these lessons": "",
    "she wants it": "",
    "he speaks Spanish": "",
    "she works hard": "",
    "she speaks English fluently": "",
    "she plays": "",
    "she works a lot": "",
    "she eats meat": "",
    "he gets up late": "",
    "she works": "",
    "she lives in London": "",
    "he remembers it": "",
    "he likes it": "",
    "he works hard": "",
    "he reads": "",
    "he eats fish": "",
    "she knows English very well": "",
    "she helps you": "",
    "she plays computer games": "",
    "she gets up early": "",
    "she likes these lessons": "",
    "he gets up very early": "",
    "he speaks Spanish fluently": "",
    "she speaks Spanish very well": "",
    "she lives in Moscow": "",
    "she plays computer games": "",
    "he watches tv": "",
    "she has a boyfriend": "",
    "he speaks English fluently": "",
    "he often tries to do it": "",
    "he does it well": "",
    "he works hard": "",
    "she does housework": "",
    "she works hard": "",
    "he often goes to China": "",
    "he has many friends": "",
    "he has a lot of friends": "",
    "he has lots of friends": "",
    "she often flies to England": "",
    "she often goes to China": "",
    "she tries to learn Spanish": "",
    "he tries to help him": "",
    "he goes to work": "",
    "she swims very well": "",
    "he gets up late": "",
    "he teaches English": "",
    "he tries learn Spanish": "",
    "she goes to the park": "",
    "he tries to do it": "",
    "he often flies to the united states": "",
    "he goes to school": "",
    "he works very hard": "",
    "he relaxes in the evening": "",
    "he has a rest": "",
    "she goes to there": "",
    "she has a car": "",
    "she goes to work": "",
    "he gets up early": "",
    "he often flies to England": "",
    "she gets up early": "",
    "he has a friend": "",
    "he plays different games": "",
    "she has many friends": "",
    "she has a lot of friends": "",
    "she has a computer": "",
    "she goes to the cinema": "",
    "he goes to the cinema": "",
    "she works very hard": "",
    "he has a house": "",
    "he works a lot": "",
    "he often does it": "",
    "she plays different games": "",
    "he goes to the theatre": "",
    "she studies at school": "",
    "she does it well": "",
    "she has a job": "",
    "it happens": "",
    "he tries to learn English": "",
    "she gets up late": "",
    "she tries to do it": "",
    "he studies at school": "",
    "she has a boyfriend": "",
    "she often does it": "",
    "she relaxes in the evening": "",
    "she has a rest in the evening": "",
    "he swims very well": "",
    "she watches tv every day": "",
    "she plays football": "",
    "she speaks English fluently": "",
    "she tries to learn English": "",
    "he often flies to the united states": "",
    "he usually relaxes in the evening": "",
    "he usually has a rest in the evening": "",
    "he goes to the park": "",
    "she usually relaxes in the morning": "",
    "she usually has a rest in the morning": "",
    "he has a computer": "",
    "she teaches English": "",
    "he really likes it": "",
    "he watches tv every day": "",
    "he plays computer games": "",
    "he reads English books": "",
    "she has a house": "",
    "it seems interesting": "",
    "he plays football": "",
    "she watches tv in the morning": "",
    "he watches tv in the evening": "",
    "he washes up the dishes": "",
    "she goes to the theatre": "",
    "she really likes it": "",
    "he has a job": "",
    "she often flies to America": "",
    "she washes up the dishes": "",
    "she has a friend": "",
    "she goes to school": "",
    "she reads English books": "",
    "she studies at university": "",
    "she goes there": "",
    "he has a car": "",
    "he studies at university": "",
    "she tries to help him": "",
    "he often flies to America": "",
    "he goes there": "",
    "he often goes there": "",
    "she often flies to England": "",
    "these lessons help me": "",
    "my father goes to work": "",
    "my uncle works very hard": "",
    "he speaks English fluently": "",
    "my sister lives in this house": "",
    "his sister goes to school": "",
    "my brother often plays basketball": "",
    "my parents work very hard": "",
    "my sister gets up late": "",
    "my sister gets up early": "",
    "my friend tries to help my brother": "",
    "this house costs a lot": "",
    "my sister has a boyfriend": "",
    "your brother plays computer games": "",
    "i also think so": "",
    "i think so, too": "",
    "our parents really like these": "",
    "my friend likes this house": "",
    "that flat costs a lot": "",
    "my father speaks English fluently": "",
    "your brother often relaxes": "",
    "your brother often has a rest": "",
    "my uncle often goes to China": "",
    "they mother has a car": "",
    "his brother goes to School": "",
    "this lesson helps me": "",
    "my mother has a job": "",
    "your father knows it very well": "",
    "my sister tries to learn Spanish": "",
    "my boyfriend often listens to music": "",
    "my brother lives in that house": "",
    "her parents work there": "",
    "my best friend lives in this city": "",
    "your sister has a computer": "",
    "this dress costs 20 dollars": "",
    "this dress is 20 dollars": "",
    "my mother understands it very well": "",
    "my mother does housework": "",
    "they mother often flies to the united states": "",
    "this flat costs a lot": "",
    "my teacher does it well": "",
    "it costs 50 pounds": "",
    "my best friend lives in Moscow": "",
    "my best friend really likes it": "",
    "i have an uncle": "",
    "my brother studies at university": "",
    "they have a house": "",
    "my girlfriend often listens to music": "",
    "my friend plays football very well": "",
    "my teacher thinks so": "",
    "my brother has many friends": "",
    "my brother has a lot of friends": "",
    "my father likes this idea": "",
    "my brother has a girlfriend": "",
    "i often listen to music": "",
    "their parents have a house": "",
    "go home / be home  / stay home / come home": "",
    "my father does business": "",
    "my sister studies at school": "",
    "your idea seems interesting": "",
    "my friend often sees her": "",
    "my father has a job": "",
    "her brother goes to work": "",
    "my sister lives in Russia": "",
    "my brother goes to work": "",
    "my friend often tries to do it": "",
    "they uncle often watches tv": "",
    "her mother teaches English": "",
    "my brother works in England": "",
    "they house looks very beautiful": "",
    "her sister goes to work": "",
    "your friend often goes there": "",
    "my sister goes to school": "",
    "that house costs a lot": "",
    "it happens": "",
    "my mother often says it": "",
    "my uncle lives in America": "",
    "my best friend plays different games": "",
    "your lesson helps me": "",
    "my friend knows English very well": "",
    "your parents often go to the park": "",
    "my brother really likes it": "",
    "i have a job": "",
    "your brother swims very well": "",
    "my mother likes this idea": "",
    "my parents know it": "",
    "we go ahead slowly but very effectively": "",
    "I see you'd like to live here": "",
    "my brother wants to study in another place": "",
    "my aunt wants to sell her house": "",
    "i prefer to learn English here": "",
    "she teaches maths": "",
    "i'd like to read a book in English": "",
    "my brother would like to try to do it": "",
    "i'd like to talk to you": "",
    "i'd like to talk about politics": "",
    "i'd like to talk about this problem": "",
    "i'd like to say it": "",
    "i'd like to say your lessons really help": "",
    "i'd like to tell your lessons help me a lot": "",
    "i'd like to tell everything": "",
    "i'd like to fly to New York": "",
    "We'd like to invite you to the party": "",
    "i'd like to have my own business": "",
    "i'd like to hear this story": "",
    "i'd like to listen to this song": "",
    "i don't buy any newspapers or magazines": "",
    "i read them online": "",
    "she works a lot": "",
    "she doesn't work much": "",
    "she works too much": "",
    "i'd like to live in another country": "",
    "i'd like to study abroad": "",
    "my friend wants to study in another place": "",
    "so": "",
    "next": "",
    "thank you": "",
    "thanks": "",
    "thank you very much": "",
    "thanks a lot": "",
    "i want to call him": "",
    "they want to call me": "",
    "We want to know all the information": "",
    "i want to have a flat": "",
    "i want to have a house": "",
    "it doesn't interest me": "",
    "we usually play different games": "",
    "i'd like to drink a glass of water": "",
    "her relative wants to rent a flat": "",
    "she'd like to become an English teacher": "",
    "i'd like to go to this restaurant": "",
    "we'd like to go to the party = cinema = theatre = park": "",
    "but we say": "",
    "we go to school": "",
    "we go to work": "",
    "i want to drink a cup of tea": "",
    "we don't know it": "",
    "his secretary wants a new job": "",
    "they want to help me": "",
    "you need more rest": "",
    "i'd like to buy this beautiful dress": "",
    "we need more exercises": "",
    "my brother would like to play this game": "",
    "i want to help you": "",
    "i'd like to call her": "",
    "i'd like to do it right now": "",
    "i'd like to translate this word": "",
    "i'd like to go to America next month": "",
    "i'd like to study there": "",
    "my brother doesn't want to do that homework": "",
    "i want to play computer games": "",
    "i need to watch these lessons": "",
    "i'd like go to the restaurant": "",
    "i want to drink a cap of tea": "",
    "you need more rest": "",
    "you need to relax more": "",
    "my brother would like to play this game": "",
    "i'd like to study there": "",
    "i study at school": "",
    "i study at university": "",
    "i learn English by myself": "",
    "i learn English here": "",
    "i want to know it, too": "",
    "i also want to know it": "",
    "she doesn't tell us everything": "",
    "she doesn't tell us all the information": "",
    "i'd like to be a businessman": "",
    "i'd like to be a businesswoman": "",
    "i need to train every day": "",
    "i need to find it": "",
    "i don't like this place": "",
    "i don't like these places": "",
    "i like other places": "",
    "i want to communicate with people from other countries": "",
    "my friend doesn't go to concerts": "",
    "i'd like to write it down": "",
    "i don't do physical exercises at home": "",
    "i often stay at home": "",
    "i work at home": "",
    "i have a house": "",
    "i go the gym": "",
    "i need to try it": "",
    "she'd like to study English here": "",
    "she'd like to study in this place": "",
    "i'd like to know all the news": "",
    "this idea doesn't seem interesting": "",
    "i need to save this document": "",
    "i'd like to work less to have more free time": "",
    "i'd like to have my own YouTube channel": "",
    "": "",
}