slovar = {
    "She was there quite often": "",
    "Who was there quite often?": "",
    "Where was she quite often?": "",
    "When was she there?": "",
    "How often was she there?": "",
    # did / was / were /
    "when did it happen to him?": "",
    "When were they in that place?": "",
    "What did you tell him?": "",
    "What was there?": "",
    "What happened?": "",
    "What seemed interesting to you?": "",
    "Where did he go yesterday?": "",
    "Where was the museum?": "",
    "How did you manage to solve this problem?": "",
    "manage to do something?": "",
    "How did you manage to cope with this problem?": "",
    "How was the party?": "",
    "Which drink did you choose?": "",
    "which book did she decide to buy in the ro buy in the end?": "",
    "Who answered correctly?": "",
    "Who answered rightly?": "",
    "Who answered incorrectly?": "",
    "Who answered wrongly?": "",
    "Who knew how to solve that task?": "",
    "Who was at the party?": "",
    "Who was in India last year?": "",
    "What conclusions did you make?": "",
    "What examples were really useful?": "",
    "What kind of books did you prefer to read?": "",
    "What kind of movies did you usually watch?": "",
    "How good were his lessons?": "",
    "How interesting was this information?": "",
    "How long was the way?": "",
    "How much did it cost?": "",
    "How much was it?": "",
    "How much did one English lesson cost?": "",
    "How much was one English lesson?": "",
    "What time did you wake up yesterday?": "",
    "What time was the meeting?": "",
    "How many tickets did you buy?": "",
    "How much money did you spend on it?": "",
    "How many mistakes did i make?": "",
    "How much knowledge was necessary to pass that test?": "",
    "How many interesting things did you hear?": "",
    "I speak English": "",
    "I speak Russian": "",
    "I understand": "",
    "I understand you": "",
    "I understand you very well": "",
    "I know English": "",
    "I know it": "",
    "I work": "",
    "I work there": "",
    "I study": "",
    "I study at school": "",
    "I study at university": "",
    "I study there": "",
    "I read books": "",
    "I read English books": "",
    "I live in Russia": "",
    "I want it": "",
    "I pay": "",
    "I play football": "",
    "I do it well": "",
    "I have a car": "",
    "I have a house": "",
    "I like English": "",
    "I like it": "",
    "I / We / You / They + verbs": "",
    "I live in Moscow": "",
    "We speak English": "",
    "You understand": "",
    "They read English books": "",
    "I know English": "",
    "We want it": "",
    "You know it": "",
    "They have a house": "",
    "I like it": "",
    "We like it": "",
    "They like it": "",
    "You like it": "",
    "I work": "",
    "He works": "",
    "I speak English": "",
    "She speaks English": "",
    "It helps me": "",
    "It helps you": "",
    "It really helps": "",
    "He lives in London": "",
    "He works hard": "",
    "He works very hard": "",
    "She works a lot": "",
    "He plays computer games": "",
    "I like it": "",
    "She likes it": "",
    "He likes it": "",
    "She likes this lesson": "",
    "She likes these lessons": "",
    "I like this lesson": "",
    "I like your lessons": "",
    "I like these lessons": "",
    "I really like these lessons": "",
    "I really it": "",
    "He swims very well": "",
    "She understands this lesson": "",
    "He remembers it": "",
    "It works well": "",
    "She speaks English": "",
    "She speaks Spanish": "",
    "I speak English fluently": "",
    "He speaks English fluently": "",
    "He want it": "",
    "She sees it": "",
    "She understands you": "",
    "It seems interesting": "",
    "She eats meat": "",
    "He eats fish": "",
    "It happens": "",
    "He plays tennis": "",
    "She plays different games": "",
    "He plays the guitar": "",
    "I get up early": "",
    "She gets up early": "",
    "I get up late": "",
    "He gets up late": "",
    "I get up very early": "",
    "He gets up very late": "",
    # I / We / You / They + verb
    "I work there": "",
    "We know it very well": "",
    "You understand me": "",
    "They live in England": "",
    # He / She / It + verb+s
    "He works in London": "",
    "She works a lot": "",
    "It really helps me": "",
    # O - es go - goes, do - does
    "I go there": "",
    "She goes there": "",
    "I do it well": "",
    "She does it well": "",
    "He does it well": "",
    "I do housework": "",
    "She does housework": "",
    "He does housework": "",
    "I go to work": "",
    "He goes to work": "",
    "She goes to work": "",
    "I go to school": "",
    "He goes to school": "",
    "She goes to school": "",
    "I go to the park": "",
    "He goes to the park": "",
    "She goes to the park": "",
    "I go to the cinema": "",
    "I go to the theatre": "",
    "He goes to the cinema": "",
    "she goes to the theatre": "",
    "I go there": "",
    "I often go there": "",
    "I often do it": "",
    "He often goes there": "",
    "She often does it": "",
    # ch/sh/x + es
    "I teach English": "",
    "She teaches English": "",
    "I watch TV": "",
    "He watches TV": "",
    "I watch TV every day": "",
    "He watches TV every day": "",
    "Wash up the dishes": "",
    "I wash up the dishes": "",
    "She washes up the dishes": "",
    "I usually relax in the evening": "",
    "She usually relaxes in the evening": "",
    # V + y + s
    "I play football": "",
    "He plays football": "",
    "We play computer games": "",
    "He play computer games": "",
    # C + y + ies
    "I often fly to America": "",
    "He often flies to America": "",
    "She often flies to England": "",
    "I often fly to the United States": "",
    "I often go to China": "",
    "He often flies to the United States": "",
    "She often goes to China": "",
    "He often cries": "",
    "She tries to do it": "",
    "He tries to help him": "",
    "I try to learn English": "",
    "He tries to learn Spanish": "",
    # I / We / You / They have
    # He / She / It has
    "I have a car": "",
    "He has a car": "",
    "I have a computer": "",
    "She has a computer": "",
    "I have a house": "",
    "She has a house": "",
    "I have a flat": "",
    "She has a flat": "",
    "I have many friends": "",
    "He has many friends": "",
    "I have a job": "",
    "She has a job": "",
    "He has a girlfriend": "",
    "She has a boyfriend": "",
    # present simple
    # I / We / You / They + verb
    #  He / She / It + verb + s
    #
    "This lesson helps me": "",
    "These lessons help me": "",
    "My sister lives in Russia": "",
    "It costs 20(twenty) pounds": "",
    "It is 20 pounds": "",
    "This dress costs 50(fifty) dollars": "",
    "This dress is 50 dollars": "",
    "My friend often sees him": "",
    "My teacher knows English very well": "",
    "My best friend plays basketball": "",
    "My brother lives in this house": "",
    "My sister lives in that house": "",
    "Your idea seems interesting": "",
    "She likes this idea": "",
    "Kate likes this idea": "",
    "Max lives in this city": "",
    "I often listen to music": "",
    "My sister often listens to music": "",
    "My father has a job": "",
    "My mother has a car": "",
    "My sister goes to school": "",
    "My brother goes to work": "",
    "Our teacher knows English very well": "",
    "I also think so": "",
    "I think so, too": "",
    "Our father also thinks so": "",
    "Our father thinks so, too": "",
    "Their teacher says it": "",
    "Their teacher says so": "",
    # I - My
    "I have a brother": "",
    "My brother goes to school": "",
    # We - Our
    "We have an uncle": "",
    "Our uncle speaks English fluently": "",
    # You - Your
    "You have a house": "",
    "Your house looks beautiful": "",
    # They - their
    "Their teacher says so": "",
    # He - his
    "His parents work there": "",
    "His mother teaches French": "",
    # She - her
    "Her father does business": "",
    "She eats fish": "",
    "She eats meat": "",
    # present simple
    # S + verb
    # I / We / You / They + verbs
    # He / She / It  + verbs + s
    # o + es
    # ch, sh, x, + es
    "I go to work": "",
    "She goes to work": "",
    "Do - does  go - goes": "",
    "I do it very well": "",
    "He does it very well": "",
    "I often watch TV": "",
    "She often watches TV": "",
    "She washes up the dishes": "",
    "He often relaxes in the evening": "",
    "have a rest": "",
    "He often has a rest in the evening": "",
    "My father works there": "",
    "My sister knows it very well": "",
    "Their parents live there": "",
    "This lesson seems interesting": "",
    "These lessons seem very interesting": "",
    "It seems interesting": "",
    "I work a lot": "",
    "She works very hard": "",
    "He lives in this house": "",
    "She lives in that house": "",
    "My friend speaks English fluently": "",
    "I like it": "",
    "He likes it": "",
    "She likes it": "",
    "They like it": "",
    "We like it": "",
    "He really likes it": "",
    "I often go to the park": "",
    "My sister has many friends": "",
    "a lot of / lots of": "",
    "This dress costs 20 pounds": "",
    "This dress is 20 pounds": "",
    "My father does business": "",
    "She eats fish": "",
    "She often flies to the United States": "",
    "My brother often plays computer games": "",
    "My brother likes different computer games": "",
    "I try to learn English": "",
    "She tries to help him": "",
    "I get up early": "",
    "He gets up late": "",
    # present simple
    "It seems interesting": "",
    "She often does it": "",
    "She has a boyfriend": "",
    "She plays different games": "",
    "She has many friends": "",
    "She has a lot of friends": "",
    "She has lots friends": "",
    "I do business in China": "",
    "We study": "",
    "He often tries to do it": "",
    "It really seems interesting": "",
    "She goes there": "",
    "I like English": "",
    "She has a friend": "",
    "She plays football": "",
    "My uncle has a car": "",
    "He watches TV": "",
    "I work very hard": "",
    "He plays computer games": "",
    "She watches TV every day": "",
    "It seems very interesting": "",
    "I often go to China": "",
    "He washes up the dishes": "",
    "We do business": "",
    "He has a friend": "",
    "She works very hard": "",
    "She teaches English": "",
    "He often flies to the United States": "",
    "He reads English books": "",
    "He often flies to England": "",
    "She studies at school": "",
    "He often relaxes in the evening": "",
    "He often has a rest in the evening": "",
    "My sister has a friend": "",
    "I have a job": "",
    "My best friend lives in England": "",
    "He has a girlfriend": "",
    "He watches TV every day": "",
    "He gets up early": "",
    "He does it well": "",
    "She tries to learn English": "",
    "He studies at school": "",
    "She gets up late": "",
    "He studies": "",
    "She plays computer games": "",
    "She plays different games": "",
    "He tries to learn English": "",
    "He does housework": "",
    "This lesson seems interesting": "",
    "I often go to the cinema": "",
    "She has a job": "",
    "He goes there": "",
    "She really likes it": "",
    "We read English books": "",
    "She gets up early": "",
    "I play different games": "",
    "He often watches TV": "",
    "She goes to the theater": "",
    "She reads English books": "",
    "She has a car": "",
    "I often fly to America": "",
    "She works hard": "",
    "She reads English books": "",
    "He really likes it": "",
    "We often go to the cinema": "",
    "He reads a lot": "",
    "She goes to work": "",
    "I often do housework": "",
    "She goes to school": "",
    "We often go to the park": "",
    "My friend speaks English fluently": "",
    "He gets up late": "",
    "She speaks English fluently": "",
    "I play": "",
    "He often goes to China": "",
    "He has a house": "",
    "He works hard": "",
    "They often watch TV": "",
    "She often flies to England": "",
    "We often play football": "",
    "I often listen to music": "",
    "She relaxes a lot": "",
    "She has a rest a lot": "",
    "She relaxes too much": "",
    "I really like this car": "",
    "My father often flies to the United States": "",
    "He often does it": "",
    "My friend studies at university": "",
    "He has a job": "",
    "My mother wants it": "",
    "My father does it very well": "",
    "She tries to help him": "",
    "He really likes it": "",
    "He goes to school": "",
    "She gets up late": "",
    "He often relaxes": "",
    "He often has a rest": "",
    "We really like it": "",
    "She does it well": "",
    "She goes to the cinema": "",
    "He has a car": "",
    "She swims very well": "",
    "We have a car": "",
    "I work a lot": "",
    "He swims very well": "",
    "She watches TV": "",
    "He often tries to help him": "",
    "It happens": "",
    "He has a friend": "",
    "My sister often flies to the United States": "",
    "She speaks English fluently": "",
    "He works hard": "",
    "I get up early": "",
    "She often does it": "",
    "She washes up the dishes": "",
    "He often does it": "",
    "She has a computer": "",
    "She watches TV every day": "",
    "He plays football": "",
    "He has a house": "",
    "He has many friends": "",
    "He has a lot of friends": "",
    "He has lots of friends": "",
    "He reads English books": "",
    "He goes to school": "",
    "She studies at school": "",
    "He tries to learn Spanish": "",
    "She often goes to China": "",
    "She washes up th dishes": "",
    "He often tries to do it": "",
    "She tries to help him": "",
    "She works very hard": "",
    "She goes to work": "",
    "This lesson seems very interesting": "",
    "She tries to learn French": "",
    "He goes to the cinema": "",
    "I often relax in the morning": "",
    "I often have a rest in the morning": "",
    "She goes there": "",
    "He gets up late": "",
    "He often goes to China": "",
    "She often relaxes in the evening": "",
    "she often has a rest in the evening": "",
    "I live in Moscow": "",
    "She often flies to America": "",
    "He works very hard": "",
    "He does it well": "",
    "She tries to learn Spanish": "",
    "She has a house": "",
    "Their parents have a job": "",
    "I study at university": "",
    "He often flies to England": "",
    "He plays different games": "",
    "She plays": "",
    "He goes to the park": "",
    "He goes to the cinema": "",
    "He has many friends": "",
    "He has a lot of friends": "",
    "He has lots of friends": "",
    "She works a lot": "",
    "We try to learn English": "",
    "I have a girlfriend": "",
    "He often goes there": "",
    "We often relax in the evening": "",
    "He tries to help me": "",
    "She has a computer": "",
    "I often play computer games": "",
    "My sister has many friends": "",
    "My sister has a lot of friends": "",
    "She swims very well": "",
    "He often flies to America": "",
    "He goes to work": "",
    "She often goes to China": "",
    "She tries to do it": "",
    "They have a house": "",
    "I have a boyfriend": "",
    "He works a lot": "",
    "She goes there": "",
    "He speaks English fluently": "",
    "She washes up the dishes": "",
    "I try to learn English": "",
    "She goes to the park": "",
    "My brother plays different games": "",
    "He often tries to do it": "",
    "I study at school": "",
    "My mother often goes there": "",
    "He does housework": "",
    "I get up late": "",
    "It seems interesting": "",
    "She studies at university": "",
    "My brother reads a lot": "",
    "He goes to the park": "",
    "He tries to learn English": "",
    "She often flies to America": "",
    "He often flies to England": "",
    "She often goes to the theatre": "",
    "She plays computer games": "",
    "My sister tries to learn English": "",
    "You teach English very well": "",
    "He goes to the theatre": "",
    "My brother often relaxes in the evening": "",
    "My brother has a rest in the evening": "",
    "My mother often watches TV": "",
    "We get up early": "",
    "She does housework": "",
    "I live in Russia": "",
    "My sister goes to school": "",
    "He goes to work": "",
    "It often happens": "",
    "Your parents often go there": "",
    "She studies at university": "",
    "I study at university": "",
    "I have a friend": "",
    "She goes to the cinema": "",
    "He plays computer games every day": "",
    "She goes to the park": "",
    "She has a job": "",
    "She tries to do it": "",
    "My parents speak English fluently": "",
    "He often goes to the theatre": "",
    "My best friend studies there": "",
    "She studies at school": "",
    "I often go there": "",
    "He teaches English": "",
    "She has a car": "",
    "She has a house": "",
    "He plays football": "",
    "My sister reads books": "",
    "He swims very well": "",
    "We read a lot": "",
    "We often fly to America": "",
    "We study at school": "",
    "They have a computer": "",
    "He tries to do it": "",
    "She works every day": "",
    "She teaches English ": "",
    "My brother works very hard": "",
    "She gets up early": "",
    "They study at university": "",
    "He teaches English": "",
    "We often do it": "",
    "She has a boyfriend": "",
    "My brother studies at university": "",
    "She does housework": "",
    "His father has a job": "",
    "My brother has a computer": "",
    "My parents often fly to the United States": "",
    "My uncle works a lot": "",
    "My friend tries to learn Spanish": "",
    "I want this dress": "",
    "I want to buy this dress": "",
    # want + to + verbs
    "I want this thing": "",
    "I want to buy this thing": "",
    "I want to order it": "",
    "I want to buy a house": "",
    "I want to know English really well": "",
    "I want to speak English very well": "",
    "I want to speak English fluently": "",
    "I want to eat": "",
    "I want to drink": "",
    "I want to eat meat": "",
    "I want to eat fish": "",
    "I want to drink tea": "",
    "I want to drink coffee": "",
    "I want to drink a cup of tee": "",
    "I want to drink a cup of coffee": "",
    "I want to learn English": "",
    "I want to go to America next month": "",
    "I want to go to Italy next year": "",
    "I want to read this book": "",
    "I want to call her": "",
    "I want to call him": "",
    "I want to call them": "",
    "They want to call me": "",
    "They want to call us": "",
    "I want to visit this place": "",
    "I want to get more money": "",
    "I want to live in another country": "",
    "I want to live abroad": "",
    "I want to study in the United States": "",
    "I want to have my own business": "",
    "I want to watch this video": "",
    "I want to watch your channel every day": "",
    "I want to go to the cinema": "",
    "I want to learn English with you": "",
    "My boss wants more money": "",
    "My brother wants to study in another place": "",
    "My aunt wants to sell her house": "",
    "My uncle wants to sell his flat": "",
    "Her relative wants to rent a flat": "",
    "His secretary wants a new job": "",
    # a/an + adjective + nouns
    "His secretary wants to find a new job": "",
    "He wants to know everything": "",
    "She wants to know all the information": "",
    "I want to help you": "",
    "I want to thank you": "",
    "Thanks": "",
    "Thank you": "",
    "Thank you very much": "",
    "Thanks a lot": "",
    "I also thank you": "",
    "I want to learn English": "",
    # Want to + verbs
    "I want to order it": "",
    "I would like to learn English": "",
    # would like to + verbs
    "I would like to order it": "",
    "I'd like to learn English": "",
    "I'd like to order it": "",
    "I'd like to do it now": "",
    "I'd like to do it right now": "",
    "I'd like to talk about it": "",
    "I'd like to speak it": "",
    "I'd like to talk about that": "",
    "I'd like to talk about this problem": "",
    "I'd like to know it": "",
    "I'd like to do it one more time": "",
    "I'd like to do it again": "",
    "I'd like to buy a new computer": "",
    "I'd like to read a book in English": "",
    "I'd like to write it down": "",
    "I'd like to listen to music": "",
    "I'd like to listen to this song": "",
    "I'd like to go to the party": "",
    "I'd like to go to this party": "",
    "I'd like to go to the restaurant": "",
    "I'd like to go to this restaurant": "",
    "I'd like to tell you everything": "",
    "I'd like to say it": "",
    "I'd like to know all the news": "",
    "I'd like to tell you all the information": "",
    "I'd like to hear this story": "",
    "I'd like to hear all the story": "",
    "I'd like to translate this word": "",
    "I'd like to translate this phrase": "",
    "I'd like to translate this sentence": "",
    "I'd like to work more": "",
    "I'd like to work less": "",
    "I'd like to more to get more money": "",
    "I'd like to work less to have more free time": "",
    "I'd like to understand English speech": "",
    "I'd like to understand native speakers": "",
    "I'd like to be a teacher": "",
    "I'd like to become a teacher": "",
    "I'd like to be a manager": "",
    "I'd like to become a manager": "",
    "I'd like to be a businessman": "",
    "I'd like to become a businessman": "",
    "I'd like to have my own business": "",
    "I'd like to have my own YouTube channel": "",
    "We'd like to invite you to the party": "",
    "They'd like to join us": "",
    "I see you'd like to live here": "",
    "He'd like to get this job": "",
    "She'd like to learn English in this place": "",
    "I'd like to thank you": "",
    "I really want to thank you": "",
    "I'd really like to thank you for your help": "",
    "support / everything": "",
    "very good words": "",
    # Present simple
    # S + verbs
    # I / We / You / They + don't + verbs
    # He / She / It + doesn't verbs
    # negative form
    "I watch this channel every day": "",
    "I don't watch this channel every day": "",
    "I live in England": "",
    "I don't live in England": "",
    "We don't work here": "",
    "We don't work there": "",
    "You don't understand it": "",
    "They don't see him": "",
    "I don't get up late": "",
    "I get up early": "",
    "I don't go to school": "",
    "I go to university": "",
    "I go to work": "",
    "I don't go to university": "",
    "I don't go to work": "",
    "I don't work": "",
    "sit on a chair": "",
    "stay at home": "",
    "I stay at home": "",
    "I don't like this place": "",
    "I like another place": "",
    "I like that place": "",
    "It doesn't cost much": "",
    "It costs a lot": "",
    "It costs little": "",
    "It doesn't cost little": "",
    "She doesn't teach English": "",
    "She teaches mathematics(math)": "",
    "I don't live in New York": "",
    "I live in Los Angeles": "",
    "I don't like this game": "",
    "I like that game": "",
    "I don't play the piano": "",
    "I play the guitar": "",
    "I don't go to work every day": "",
    "I work from home": "",
    "I work at home": "",
    "I don't buy newspapers ot magazines": "",
    "I read them online": "",
    "I don't know much about politics": "",
    "It doesn't interest me": "",
    "I don't speak Chinese": "",
    "I speak English and Spanish": "",
    "She doesn't like her job": "",
    "She wants to find another job": "",
    "I don't eat meat but I eat fish": "",
    "I don't play tennis": "",
    "She plays it": "",
    "I don't do physical exercises at home": "",
    "I go to the gym": "",
    "I don't play computer games all day": "",
    "I like sport": "",
    # present simple
    # I/we/you/they + verbs
    # he/she/it + verbs + s
    # present simple negative form
    # i/we/you/they + don't + verbs
    # he/she/it + doesn't + verbs
    "My girlfriend lives there": "",
    "My girlfriend doesn't live there": "",
    "My brother doesn't want to do this homework": "",
    "My cousin doesn't go to the concerts": "",
    "He doesn't like it": "",
    "My best friend doesn't smoke": "",
    "He wants to be healthy": "",
    "He doesn't eat little": "",
    "He eats a lot": "",
    "He eats too much": "",
    "Our director doesn't ask many questions": "",
    "MY friend doesn't like classical music": "",
    "Our lessons don't finish late because they start early": "",
    "His parents don't live together": "",
    "They live separately": "",
    "My friend doesn't drive fast": "",
    "He drives very slowly": "",
    "My brother doesn't go shopping": "",
    "My sister goes to shopping": "",
    "My father doesn't teach history": "",
    "He teaches English": "",
    "My brother doesn't watch football on TV but he likes it": "",
    "My friend doesn't walk to work": "",
    "He goes to work by car": "",
    "He goes to work on foot": "",
    "MY sister goes to school by car": "",
    "My sister goes to school on foot": "",
    "MY sister walks to school": "",
    "My sister doesn't listen to him": "",
    "She listens to her": "",
    "My friends don't listen to them": "",
    "They listen to us": "",
    "I don't buy food": "",
    "My patents usually buy all the food": "",
    #
    "I need it": "",
    "I need your help": "",
    "I need your advice": "",
    "I need your recommendation": "",
    "I need more practice": "",
    "I need a good teacher": "",
    "I need a good English teacher": "",
    "I need more lessons": "",
    "I need these lessons": "",
    "I need a pen": "",
    "I need a pencil": "",
    "I need money": "",
    "I need more money": "",
    "I need to learn English": "",
    # need to + verb
    "I need to find a good job": "",
    "I need to know it right now": "",
    "I need to check it": "",
    "I need to go to that place": "",
    "I need to call him": "",
    "I need to visit her": "",
    "I need to work very hard": "",
    "I need to study more": "",
    "I need to remember all these words and phrases": "",
    "I need to safe this document": "",
    "I need to safe this file": "",
    "I need to write a letter": "",
    "I need to write it down": "",
    "I need to watch this lesson one more time": "",
    "I need to watch this lesson again": "",
    "I need to watch these lessons": "",
    "I need to watch that movie": "",
    "I like it more": "",
    "I need to read these books": "",
    "I need to train every day": "",
    "I need to study English regularly": "",
    "We need more exercises": "",
    "You need more rest": "",
    "They need more lessons": "",
    "He needs more money": "",
    "She needs more practice": "",
    "My friend needs to learn English": "",
    "My brother needs to go there": "",
    "My friends need to buy this thing": "",
    "My parents need to work more": "",
    "I go to China": "",
    "I go to the United States": "",
    "I go to Spanish": "",
    "I go to England": "",
    "I go to the United Kingdom": "",
    "I want this thing": "",
    "I want to buy this thing": "",
    "She wants to speak English fluently": "",
    "My friend wants to translate this text": "",
    "I want to a cup of tea": "",
    "I'd like a cup of tea": "",
    "I'd like to drink a cup of tea": "",
    "She'd like to visit this place": "",
    "They'd like to order it online": "",
    #I/ WE / You / They + don't + verbs
    # He / She / It + doesn't + verbs
    "I don't understand": "",
    "It doesn't seem interesting": "",
    "This idea doesn't seem interesting": "",
    "My parents don't want to sell this house": "",
    "I need your help": "",
    # need to + verbs
    "I need to check it": "",
    "I need to do it again": "",
    "She needs to go shopping": "",
    "My cousin needs to see it": "",
    "She often calls us": "",
    "She often calls you": "",
    "She often calls him": "",
    "She often calls her": "",
    "She often calls them": "",
    "She often calls me": "",
    "She has a car": "",
    "She has a good car": "",
    "He has a big house": "",
    "I need your help": "",
    "I really need your help": "",
    "I'd like to hear this story": "",
    "I want to listen to this song": "",
    "My brother wants to try to do it": "",
    "He wants to learn English to communicate with people from other countries": "",
    "I like it": "",
    "I also like it": "",
    "I like it, too": "",
    "I need to know all the information": "",
    "I need to know everything": "",
    "I need to know all the news": "",
    "My father does business": "",
    "my sister really likes it": "",
    "She often washes up the dishes": "",
    "My sister often flies to the United States": "",
    "He reads a lot": "",
    "He doesn't raed much": "",
    "I know a lot": "",
    "I don't know much": "",
    "about this problem": "",
    "My brother has many friends": "",
    "My brother has a lot of friends": "",
    "It often happens": "",
    "We go ahead slowly but very effectively": "",
    "I see you would like to live here": "",
    "My brother wants to study in another place": "",
    "My aunt wants to sell her house": "",
    "I prefer to learn English here": "",
    "She teaches maths": "",
    "She teaches mathematics": "",
    "I'd like to read a book in English": "",
    "My brother would like to try to do it": "",
    "I'd like to talk to you": "",
    "I'd like to speak to you": "",
    "I'd like to talk about politics": "",
    "I'd like to talk about this problem": "",
    "I'd like to say it": "",
    "I'd like to say your lessons really help": "",
    "I'd like to tell you your lessons help me a lot": "",
    "I'd like to tell you everything": "",
    "I'd like to fly to New York": "",
    "We'd like to invite you to the party": "",
    "I'd like to have my own business": "",
    "I'd like to hear this story": "",
    "I'd like to listen to this song": "",
    "I don't buy any newspapers or magazines": "",
    "I read them online": "",
    "She works a lot": "",
    "She doesn't work too much": "",
    "She works too much": "",
    "I'd like to live in another country": "",
    "I'd like to live abroad": "",
    "My friend wants to study in another place": "",
    "So - next - Thank you! - Thanks - Thank you very much": "",
    "I want to call him": "",
    "I want to call her": "",
    "I want to call them": "",
    "They want to call me": "",
    "They want to call us": "",
    "We want to know all the information": "",
    "I want to have a flat": "",
    "I want to have a house": "",
    "It doesn't interest me": "",
    "we usually play different games": "",
    "I'd like to drink a glass of water": "",
    "Her relative wants to rent a flat": "",
    "She'd like to become an English teacher": "",
    "I'd like to go this restaurant": "",
    "We'd like to go to the party": "",
    "cinema": "",
    "theatre": "",
    "park": "",
    "but we say we go to school": "",
    "we go to work": "",
    "I'd like to go to the restaurant": "",
    "I want to drink a cup of tea": "",
    "You need more rest": "",
    "You need to relax more": "",
    "My brother would like to play this game": "",
    "I'd like to study there": "",
    "student ; I study at school": "",
    "I study at university English courses": "",
    "I learn English by myself": "",
    "I learn English here": "",
    "I want to know it, too": "",
    "I also want to know it": "",
    "She doesn't tell us everything": "",
    "She doesn't tell us all the information": "",
    "I'd like to be a businessman": "",
    "I'd like to be a businesswoman": "",
    "I need to train every day": "",
    "I need to find it": "",
    "I don't like this place": "",
    "I don't like that place": "",
    "I don't like these places": "",
    "I don't like those places": "",
    "I like another place": "",
    "I like other places": "",
    "I want to communicate with people from other countries": "",
    "My friend doesn't go to concerts": "",
    "I'd like to write it down": "",
    "I don't do physical exercises at home": "",
    "I often stay at home": "",
    "I work at home": "",
    "I have a house": "",
    "I go to the gym": "",
    "I need to try it": "",
    "She'd like to study English here": "",
    "there; in this place ; in that place": "",
    "I'd like to know all the news": "",
    "This idea doesn't seem interesting": "",
    "I need to safe this document/ file": "",
    "I'd like to work less to have more free time": "",
    "I'd like to have my own YouTube channel": "",
    "business/house/flat": "",
    # present simple (negative form)
    "You have a job": "",
    "Do you have a job?": "",
    # Do + S + verb?
    "Do I show a good results": "",
    "Do we have an interesting offer?": "",
    "We have an interesting offer": "",
    "You do it professionally ( English professionally - our channel)": "",
    "Do you do it professionally?": "",
    "They often say it": "",
    "Do they often say it?": "",
    "More examples and exercises": "",
    "I know it better": "",
    "Do i know it better?": "",
    "We often hear these thing": "",
    "Do we often hear these ting?": "",
    "You often say it": "",
    "Do you often say it?": "",
    "They get 500(five hundred) dollars a month": "",
    "Do they get 500 dollars a month?": "",
    "I make mistakes": "",
    "Do I make mistakes?": "",
    "You also think so": "",
    "Do you think so?": "",
    "We always take her": "",
    "Do we always take her?": "",
    "You see your progress": "",
    "Do you see your progress?": "",
    "Do They often come late?": "",
    "Do you want to come?": "",
    "Do you want to tell her this thing?": "",
    "Do you want to try to do it?": "",
    "Do you need it right now?": "",
    "Do you live there?": "",
    # Present Simple
    # Do + S + verb?
    "Do you understand me?": "",
    "Yes, I understand you": "",
    # Does + S + verb?
    "Does she understand us": "",
    "Does she speak English?": "",
    "Does he live there?": "",
    "Does it help you a lot?": "",
    "Does it seem interesting?": "",
    "Does it look beautiful?": "",
    "Does it happen from time to time?": "",
    "Does it interest you?": "",
    "Does she believe in God?": "",
    "Does she remember it?": "",
    "Does she often forget it?": "",
    "Does she support this idea?": "",
    "Does he agree with you?": "",
    "Does he do business?": "",
    "Does he often stay at home?": "",
    "Does he often travel?": "",
    "Does she feel good?": "",
    "Does he feel bad?": "",

}