slovar = {
    "you have a job": "",
    "do you have a job?": "",
    "do---i / we / you / they  + г ": "",
    "i show good results": "",
    "do i show good results?": "",
    "we have an interesting offer": "",
    "do we have an interesting offer?": "",
    "you do it professionally": "",
    "do you do it professionally?": "",
    "they often say it": "",
    "do they often say it?": "",
    "more examples and exercises": "",
    "i know it better": "",
    "do i know it better?": "",
    "we often hear these things": "",
    "do we often hear these things?": "",
    "you often say it": "",
    "do you often say it?": "",
    "they get 500 dollars a month": "",
    "do they get 500 dollars a month?": "",
    "i make mistakes": "",
    "do i make mistakes?": "",
    "you also think so": "",
    "do you think so?": "",
    "we always take her": "",
    "do we always take her?": "",
    "you see your progress": "",
    "do you see your progress": "",
    "do they often come late?": "",
    "do you want to come?": "",
    "do you want to tell her this thing": "",
    "do you want to try to do it?": "",
    "do you need it right now?": "",
    "do you live there?": "",
    "do --- i / we / you / they + г ": "",
    "do you understand me?": "",
    "yes, i understand you": "",
    "does + he / she / it + verb": "",
    "does she understand us?": "",
    "she speak English": "",
    "does she speak English?": "",
    "does he live there?": "",
    "does it help you a lot?": "",
    "does it seem interesting?": "",
    "does it look beautiful?": "",
    "does it happen from time to time?": "",
    "does it interest you?": "",
    "does she believe in god?": "",
    "does she remember it?": "",
    "does she often forget it?": "",
    "does she support this idea?": "",
    "does he agree with you?": "",
    "does he do business?": "",
    "does he often stay at home?": "",
    "does he often traver?": "",
    "does she feel good?": "",
    "does he feel bad?": "",
    "does it work?": "",
    "does it really work?": "",
    "does he need it urgently?": "",
    "does she need your advice?": "",
    "does she call him?": "",
    "does she often call him?": "",
    "does she often visit him?": "",
    "does he often see them?": "",
    "does it help you?": "",
    "does it really help you?": "",
    "does he go to bad early?": "",
    "does she use the internet every day?": "",
    "does he like orange juice?": "",
    "does she like this subject?": "",
    "this / that / my / your / our .... another": "",
    "does he need money now?": "",
    "does she need support?": "",
    "does she read magazines?": "",
    "does he read newspapers?": "",
    "does she often fly to the United states?": "",
    "does she usually sleep well?": "",
    "does she sing songs?": "",
    "does it seem strange?": "",
    "does it seem boring?": "",
    "does it look wonderful?": "",
    "does he play the guitar?": "",
    "does she draw well?": "",
    "does he dance professionally?": "",
    "does his friends want to continue it?": "",
    "does our rest include it?": "",
    "does her sister often meet her?": "",
    "do their friends often pay for it?": "",
    "does this thing happen very rarely?": "",
    "does this thing happen very seldom?": "",
    "do his parents believe in god?": "",
    "does your cousin believe in ghosts?": "",
    "does your boyfriend believe him?": "",
    "do my colleagues live near this place?": "",
    "does your classmate run very fast?": "",
    "do your neighbors often hear this story?": "",
    "do these lessons help?": "",
    "does this lesson help?": "",
    "does this idea seem interesting?": "",
    "do these ideas seem interesting?": "",
    "does his wife usually buy expensive things?": "",
    "does her husband usually buy cheap things?": "",
    "do the boys remember it very well?": "",
    "do the girls know it perfectly?": "",
    "does the lesson seem very long?": "",
    "does the story very short?": "",
    "he wants to be a businessman": "",
    "he doesn't want to be a businessman": "",
    "does he want to be a businessman?": "",
    "they have their own business": "",
    "they don't have their own business": "",
    "do they have their own business?": "",
    "my brother waits for it": "",
    "my brother doesn't wait for it": "",
    "does my brother wait for it?": "",
    "my sister loves him": "",
    "my sister doesn't love him": "",
    "does my sister love him?": "",
    "my teacher remembers everything": "",
    "all these thing / all these fact  / all the information": "",
    "my teacher doesn't remember everything": "",
    "does my teacher remember everything?": "",
    "my boss forgets these things": "",
    "my boss leaves different things": "",
    "my boss doesn't forget these things": "",
    "does my boss forget these things?": "",
    "the company offer us new workers": "",
    "the company doesn't offer us new workers": "",
    "does the company offer us new workers?": "",
    "the book seems very useful": "",
    "the book doesn't seem very useful": "",
    "does the book seem very useful?": "",
    "my ticket includes it": "",
    "my ticket doesn't include it": "",
    "does my ticker include it?": "",
    "the lessons start very early": "",
    "the lessons don't start very early": "",
    "do the lessons start very early?": "",
    # when / where  why / how  / what  + do/does + subject (general scheme)
    # when do i / we  you / they ...?
    #  when does he / she / it .... ?
    "when do you do it?": "",
    "when do you watch English movie?": "",
    "when do you learn English?": "",
    "when do you go to school?": "",
    "when does she see him?": "",
    "when do they see her?": "",
    "when does it happen?": "",
    "when does he come?": "",
    "why do you learn English?": "",
    "why do you support him?": "",
    "why do you teach English?": "",
    "why do you do it?": "",
    "why does it happen?": "",
    "why does it seem interesting?": "",
    "why does it seem boring?": "",
    "why does it interest you?": "",
    "why do you think so?": "",
    "what do you think about it?": "",
    "what do you sell?": "",
    "what do you buy there?": "",
    "what do you teach?": "",
    "what do you mean?": "",
    "what do you want to say?": "",
    "what does it mean?": "",
    "what do you need?": "",
    "what does she need?": "",
    "what does he need?": "",
    "what do you want?": "",
    "how do you do it?": "",
    "how do you explain it?": "",
    "how do they speak?": "",
    "how do they understand it?": "",
    "how do you pay?": "",
    "how do you feel?": "",
    "how does she feel?": "",
    "how do you get to work?": "",
    "how do you get to school?": "",
    "how does she study?": "",
    "how does he feel?": "",
    # when / where / why / how / what + do/does + subject
    "where does she live?": "",
    "where does your sister live?": "",
    "when do these lessons start?": "",
    "what does your brother do at work?": "",
    "what do your parents know?": "",
    "where does your father work?": "",
    "why does your boss learn English?": "",
    "how does his girlfriend look like?": "",
    "when does your boyfriend find time for it?": "",
    "what does your grandmother grow in her garden?": "",
    "when does this lesson usually start?": "",
    "when does that lesson usually finish?": "",
    "when do the lessons start?": "",
    "when do the lessons finish?": "",
    "what does your wife cook?": "",
    "what does your wife usually cook?": "",
    "what does your husband usually eat?": "",
    "where do your children study?": "",
    "where does your son study?": "",
    "where does your daughter study?": "",
    "what do your suppliers produce?": "",
    "what do your partners think about this situation?": "",
    "what do your clients usually answer?": "",
    "what do your clients usually reply?": "",
    "what does this ticket include?": "",
    "how does the company work?": "",
    "why does your best friend hate it?": "",
    "how does your sister swim?": "",
    "what does your boss promise?": "",
    "when do the exams start?": "",
    "why does your friend think differently?": "",
    "why does your friend think another way?": "",
    "where does your son want to study?": "",
    "how does she find time for everything?": "",
    "why do they refuse to do it?": "",
    # do / i / we / you / they + г ?
    # does he / she / it + verb ?
    "do you find it interesting?": "",
    "does she find it boring?": "",
    "do your parents find it strange?": "",
    "does your friend consider it a waste of time?": "",
    # when / where / why / how / what + do/does + subject + verb?
    "why does he complain?": "",
    "what do they buy?": "",
    "what do they usually buy?": "",
    "what does your girlfriend usually cook?": "",
    "when does your teacher check it?": "",
    "how do their parents control it?": "",
    "he runs fast": "",
    "i want to learn English really fast": "",
    "when do the exams finish?": "",
    "does your boyfriend want to buy a new car?": "",
    "does she run fast?": "",
    "what do they usually have for breakfast?": "",
    "do you have your own business?": "",
    "my partner doesn't have an interesting offer?": "",
    "i don't have a car": "",
    "i haven't got a car": "",
    "does she get 300 dollars a month?": "",
    "i go to work": "",
    "i work very hard": "",
    "i have a job": "",
    "i like my job": "",
    "i have good colleagues": "",
    "we work together very well": "",
    "i have different hobbies": "",
    "i like English": "",
    "i learn English online on the channel English Galaxy": "",
    "i prefer to learn English effectively": "",
    "where do you study?": "",
    "do you have a job?": "",
    "do you have good friends?": "",
    "where does your friend work?": "",
    "where does your friend study?": "",
    "how does he spend his free time?": "",
    "how does she prefer to learn English?": "",
    "why does she learn Spanish?": "",
    "I really like it": "",
    "I think I like it": "",
    "I get up early": "",
    "I usually get up early": "",
    "Really, I like it": "",
    "It works well": "",
    "It doesn't work well": "",
    "Does it work well": "",
    "This idea seems good": "",
    "This idea doesn't seem good": "",
    "Does this idea seem good?": "",
    "they'd like to study in the united states": "",
    "I want to know it, too": "",
    "I also want to know it": "",
    "I need to check it": "",
    "My uncle wants to sell his flat": "",
    "She doesn't tell us everything": "",
    "I want to buy a house": "",
    "I'd like to know it right now": "",
    "My friend doesn't talk to hir": "",
    "Very good words": "",
    "I'd like to call them": "",
    "My friends, I really want to thank you": "",
    "I'd like to be a businessman": "",
    "I need to train every day": "",
    "I need to find it": "",
    "I'd like to speak English fluently": "",
    "I don't want to do it again": "",
    "We want to play football": "",
    "Her relative wants to rent a flat": "",
    "I"
    "I'd like to buy a house": "",
    "I need to visit her": "",
    "I watch this channel every day": "",
    "She wants to know all the information right now": "",
    "I need to call him": "",
    "I don't like this place": "",
    "I like another place": "",
    "His secretary would like to get a new job": "",
    "Next": "",
    "I need to translate this text": "",
    "I'd like to study there": "",
    "My friend doesn't go to work on foot": "",
    "They want to call me": "",
    "She needs more practice": "",
    "My friend needs to learn English": "",
    "My friend doesn't go to concerts": "",
    "He doesn't like it": "",
    "I'd like to understand English speech": "",
    "I need to say it": "",
    "I need to study more": "",
    "I want to call them": "",
    "I want to drink": "",
    "I'd like to write it down": "",
    "I'd like to go this party": "",
    "I'd like to talk to you about this problem": "",
    "She needs to go to China": "",
    "We'd like to listen to music": "",
    "I don't want to do it right now": "",
    "I want to do it later": "",
    "You see he doesn't understand you": "",
    "I don't see him": "",
    "We don't work there": "",
    "I also need to know it": "",
    "I want to speak English fluently": "",
    "I want to study in the United states": "",
    "I don't do physical exercises at home": "",
    "I go to the gym": "",
    "I need to go to America": "",
    "I need to try it": "",
    "I'd like to study in this place": "",
    "My aunt wants to sell her flat": "",
    "My boss wants to know everything": "",
    "My parents don't want to live in another city": "",
    "They want to live in this city": "",
    "I want to order it": "",
    "I'd like to go to Italy next year": "",
    "My parents don't like this place": "",
    "They like another place": "",
    "We wants to listen to this song": "",
    "I need to order it": "",
    "I'd like to go to the restaurant": "",
    "She'd like to study English here": "",
    "She works little": "",
    "I'd like to know all the news": "",
    "I need to go to another place": "",
    "I want to get more money": "",
    "I'd like to read this book": "",
    "She doesn't think so": "",
    "He wants to know everything": "",
    "We want to know all the information": "",
    "We want to learn English with you": "",
    "I need to go to work": "",
    "I want to order it": "",
    "I need to remember it": "",
    "I need to tell you about this problem": "",
    "I don't know much about politics": "",
    "My parents need to work more": "",
    "I really want to thank you for your support": "",
    "I'd like to have a car": "",
    "I'd like to know it": "",
    "I'd like to say it": "",
    "I need to read these books": "",
    "This idea doesn't seem interesting": "",
    "I'd like to study in that place": "",
    "My sister doesn't want to study abroad but I want it": "",
    "I don't play computer games all day": "",
    "I like sport": "",
    "I need to save this document": "",
    "My brother doesn't know it but I know it": "",
    "I'd like to help my friend": "",
    "I need to watch your English lessons": "",
    "I'd like to work less to have more free time": "",
    "I want to get more money and he also wants it": "",
    "She would like to sell her house": "",
    "I'd like to read a book": "",
    "She doesn't like her job": "",
    "She wants to find another job": "",
    "I need to watch that movie": "",
    "I'd like to have my own YouTube channel": "",
    "We'd like to work less": "",
    "She needs to know all the information now": "",
    "I don't need to study abroad": "",
    "I want to study in Russia": "",
    "I don't have much free time": "",
    "I have little free time": "",
    "He doesn't eat much": "",
    "I want to watch your videos": "",
    "He eats too much": "",
    "I need this information": "",
    "I'd like to buy this thing": "",
    "I want a cup of tea": "",
    "My brother doesn't get up early": "",
    "He gets up late": "",
    "I need to see him": "",
    "He needs to do more physical exercises": "",
    "I'd like to have my own business": "",
    "I want to go to the cinema": "",
    "I need to watch this lesson one more time": "",
    "Thanks / Thank you": "",
    "It often happens": "",
    "I'd like to tell you everything": "",
    "They want to call us": "",
    "I'd like to go this restaurant": "",
    "I'd like to drink a glass of juice": "",
    "I need to go to the gym": "",
    "His secretary wants to find a new job": "",
    "I want coffee": "",
    "I see": "",
    "I need to relax more": "",
    "I need more rest": "",
    "I need to have more rest": "",
    "We need to visit him": "",
    "I want to buy this beautiful dress": "",
    "My parents don't want to buy this thing": "",
    "I'd like to translate these sentences": "",
    "I want to drink coffee": "",
    "I'd like a cup of coffee": "",
    "I want to drink a glass if water": "",
    "I also want to thank you": "",
    "I don't talk to him": "",
    "We don't like those lessons": "",
    "We like these lessons": "",
    "I'd like to fly to New York": "",
    "My boss wants more money": "",
    "I'd like to work less": "",
    "My sister doesn't liston to him": "",
    "She listens to her": "",
    "My brother needs to go there": "",
    "I'd like to do it one more time": "",
    "I'd like to do it again": "",
    "It doesn't cost much": "",
    "I need to understand it right now": "",
    "I'd like to hear all the story": "",
    "My brother doesn't watch football on tv": "",
    "My girlfriend doesn't live there": "",
    "She lives here": "",
    "We want to thank you": "",
    "I want to call her": "",
    "I'd like to translate this phrase": "",
    "My friends need to buy this thing": "",
    "I'd like to learn English": "",
    "My sister wants to play different games": "",
    "I want tea": "",
    "I don't like this song": "",
    "I like that song": "",
    "I'd like to do it again": "",
    "Our relative wants to rent a flat": "",
    "I'd like to buy a new computer": "",
    "I'd like to order it": "",
    "I'd like to do it one more time": "",
    "He wants more money": "",
    "He wants to know everything": "",
    "He'd like to get this job": "",
    "I don't order it here": "",
    "I order it online": "",
    "I want to eat meat": "",
    "I need to find a good job": "",
    "I want to watch this video": "",
    "I want to know English": "",
    "I want to study there": "",
    "My best friend doesn't smoke": "",
    "We want to find a new job": "",
    "I want to try to do it": "",
    "I want to speak English fluently": "",
    "I don't play the piano": "",
    "I play the guitar": "",
    "I need to write it down": "",
    "I'd like to order it": "",
    "You need to relax more": "",
    "You need to have more rest": "",
    "It doesn't cost little": "",
    "It costs a lot": "",
    "I want to eat fish": "",
    "They need more lessons": "",
    "He wants to know everything": "",
    "I'd like to become a businessman": "",
    "I'd like to become a businesswoman": "",
    "He needs more money": "",
    "I'd like to know all the news": "",
    "My boss would like to know everything": "",
    "I want this dress": "",
    "I'd like to thank you": "",
    "My friends don't listen to them": "",
    "They listen to us": "",
    "I want to learn English right now": "",
    "I'd like to buy a computer": "",
    "We need to save this file": "",
    "I need to write a letter": "",
    "I'd like to watch this video now": "",
    "We need to translate this sentence": "",
    "I want to speak English very well": "",
    "I want to drink tea": "",
    "I'd like to understand native speakers": "",
    "I'd like to get more money": "",
    "I'd like to drink a cop of coffee": "",
    "I need to do this thing now": "",
    "I really want to thank you": "",
    "I really want to learn English": "",
    "I really need to translate this text": "",
    "I'd like to work more to get more money": "",
    "I don't get up late": "",
    "I get up early": "",
    "I want to live in another country": "",
    "My relative wants to sell his flat": "",
    "We'd like to order it right now": "",
    "He wants to be healthy": "",
    "I'd like to say it": "",
    "I understand you very well": "",
    "I'd like to see it": "",
    "We want to learn English": "",
    "She doesn't want to sell her house": "",
    "She wants to sell her flat": "",
    "I also want to know it": "",
    "I need to study English more regularly": "",
    "I want to play this computer game": "",
    "I need to listen to this song": "",
    "They want to than us": "",
    "My relative would like to study abroad": "",
    "I want to help you": "",
    "I want to have a car": "",
    # I / we / you / they + verb ... ?
    "Do you speak English?": "",
    "Do you speak Spanish?": "",
    "Do you live in Russia?": "",
    "Do they know all the information?": "",
    "Do I do it very well?": "",
    "Do I show good results?": "",
    "Do you live together?": "",
    "Do we learn English effectively?": "",
    "Do they work there?": "",
    "Do you try to learn English?": "",
    "Of course": "",
    "Do we always take her?": "",
    "Do you see your progress?": "",
    "Do they often say it?": "",
    "Do you want to tell her this thing?": "",
    "Do we have an interesting offer?": "",
    "Do you do it professionally?": "",
    "Do you know it better?": "",
    "Do they come late?": "",
    "Do they usually come late?": "",
    "Do they come early?": "",
    "Do they usually come early?": "",
    "Do you live there?": "",
    "Do you want to come?": "",
    "Do you need it right now?": "",
    "Do you think so?": "",
    "Do you also think so?": "",
    "Do you think so, too?": "",
    "Do I make mistakes?": "",
    "Do they want to try to do it?": "",
    "Do they get 500 dollars a month?": "",
    "Do they get this money?": "",
    "Do you have a boyfriend?": "",
    "Do you have a girlfriend?": "",
    "Do you have a car?": "",
    "Do you have a house?": "",
    "Do you have a flat?": "",
    "Do you have a brother or a sister?": "",
    "Do you have any brother or sister?": "",
    "Do you often go to the cinema?": "",
    "Do you work or study?": "",
    "Do you help your parents?": "",
    "Do they help you?": "",
    "Do they call him?": "",
    "Do they see her?": "",
    "Do you often see her?": "",
    "Does he want to help them?": "",
    "Does it help you a lot?": "",
    "Does she often visit him?": "",
    "Does she remember it?": "",
    "Does it help him?": "",
    "Does he dance professionally?": "",
    "Does it seem strange?": "",
    "Does she draw well?": "",
    "Does she speak English?": "",
    "I speak English": "",
    "I read in English": "",
    "Does she feel good?": "",
    "Does he need all the information?": "",
    "Does he like these lessons?": "",
    "Does she know it, too?": "",
    "Does he want to study in another place?": "",
    "Does it happen from to time?": "",
    "Does she call him?": "",
    "Does he often call her?": "",
    "Does he want read ths book?": "",
    "Does it really help you?": "",
    "Does he often travel?": "",
    "Does it seem interesting?": "",
    "Does she like this idea?": "",
    "Does it seem boring?": "",
    "Does she want to call them?": "",
    "Does she often fly to the United states?": "",
    "Does she need your advice?": "",
    "Does he need your help?": "",
    "Does she teach English?": "",
    "Does he need money now?": "",
    "Does he need it urgently?": "",
    "Does she often call him?": "",
    "Does he prefer to learn English here?": "",
    "Does he listen to this music?": "",
    "Does she use the internet every day?": "",
    "Does he like those lessons?": "",
    "Does he play the guitar?": "",
    "Does she need to rent a flat?": "",
    "Does he need to study English more regularly?": "",
    "Does she like this subject?": "",
    "Does he feel bad?": "",
    "Does she try to do it?": "",
    "Does he often stay at home?": "",
    "Does she read magazines?": "",
    "Does he need to work more?": "",
    "Does she need to study more?": "",
    "Does he read newspapers?": "",
    "Does it look beautiful?": "",
    "Does she want to become a teacher?": "",
    "Does he really like it?": "",
    "Does she usually sleep well?": "",
    "Does she often sing this song?": "",
    "Do you want to have your own business?": "",
    "Do you understand me?": "",
    "Yes, I understand you": "",
    "Does he live there?": "",
    "Does it really help you and your friends?": "",
    "Does it work?": "",
    "Does he smoke?": "",
    "Does he play the piano?": "",
    "Does he live there?": "",
    "Does it really work?": "",
    "Does he agree with you?": "",
    "Does it look wonderful?": "",
    "Does it interest you?": "",
    "Does she often forget it?": "",
    "Does she need this information?": "",
    "Does she talk to him?": "",
    "Does he want to have a car?": "",
    "Does he want to get more money?": "",
    "Does she also know it?": "",
    "Does she believe in God?": "",
    "Does he often see them?": "",
    "Does he want to do it one more time?": "",
    "Does he go to bed early?": "",
    "Does she support this idea?": "",
    "Does her boyfriend believe him?": "",
    "Does this lesson seem very long?": "",
    "Does your cousin know it better?": "",
    "Does your father try to do it?": "",
    "Does your classmate run very fast?": "",
    "I want to learn English fast": "",
    "Does the history seem very short?": "",
    "Does this thing happen rarely?": "",
    "Do your parents try to learn English?": "",
    "Does his friend want to continue it?": "",
    "Does your brother use the Internet every day?": "",
    "Does it interest you?": "",
    "Does this thing interest you?": "",
    "Do these things interest you?": "",
    "Do your colleagues get 500 dollars a month?": "",
    "Does this boy show a good result?": "",
    "Do these ideas seem interesting?": "",
    "Does the teacher want to tell us all the news?": "",
    "Does his sister often meet him?": "",
    "Do their friends often pay for it?": "",
    "Do your neighbors often hear this story?": "",
    "Does your cousin believe in ghosts?": "",
    "Do his students feel progress?": "",
    "Does his husband usually buy cheap things?": "",
    "Do these things interest you?": "",
    "Do his parents believe in God?": "",
    "Do these boys show good results?": "",
    "Does this boy often make mistakes?": "",
    "Does this idea seem very interesting?": "",
    "Does your mother work or stay at home?": "",
    "Do your colleagues live near this place?": "",
    "Does his wife usually buy expensive things?": "",
    "Do the boys remember it very well?": "",
    "Does your teacher also think so?": "",
    "Does your boss know all the information?": "",
    "Do your parents think so, too?": "",
    "Does your teacher agree with it?": "",
    "Does this lesson help?": "",
    "Do the girls know it perfectly?": "",
    "Do her parents always take her?": "",
    "Do these lessons help?": "",
    "Does that thing seem interesting?": "",
    "Does uor rest include it?": "",
    "Does his student learn English effectively?": "",
    "This doesn't result seems very good": "",
    "Does this result seem very good?": "",
    "These results seem very good": "",
    "These results don't seem very good": "",
    "Do these results seem very good?": "",
    "The results seem  good": "",
    "The results don't seem good": "",
    "Do the results seem good": "",
    "The result seems good": "",
    "The result doesn't seem good": "",
    "Does the result seem good?": "",
    "My friend has an interesting offer": "",
    "Mu friend doesn't have an interesting offer": "",
    "Does my friend have an interesting offer": "",
    "My friends have an interesting offer": "",
    "My friends don't have an interesting offer": "",
    "Do my friends have an interesting offer?": "",
    "My teacher says it": "",
    "My teacher doesn't say it": "",
    "Does my teacher say it?": "",
    "His parents tell him everything": "",
    "His patents don't tell him everything": "",
    "Do his parents tell him everything?": "",
    "My brother tries to learn English": "",
    "My brother doesn't try to learn English": "",
    "Does my brother try to learn English?": "",
    "That thing interests them": "",
    "That thing doesn't interest them": "",
    "Does that thing interest them?": "",
    "Those things interest her": "",
    "Those things don't interest her": "",
    "Do those things interest her?": "",
    "Her mother stay at home": "",
    "Her mother doesn't stay at home": "",
    "Does her mother stay at home?": "",
    "My best friend needs support now": "",
    "My best friend doesn't need support now": "",
    "Does my best friend need support now?": "",
    "He has his own business": "",
    "He doesn't have his own business": "",
    "Does he have his own business?": "",
    "Our rest includes it": "",
    "Our rest doesn't include it": "",
    "Does our rest include it": "",
    "This house looks very expensive": "",
    "This house doesn't look very expensive": "",
    "Does this house look very expensive?": "",
    # when where why how what + do/ does + subject
    "when do you do to work?": "",
    "How does he explain it?": "",
    "Where do they live?": "",
    "Where does it happen?": "",
    "what do you think about it?": "",
    "How does he work?": "",
    "What does she remember?": "",
    "What do you buy there?": "",
    "What does she have?": "",
    "What do you see?": "",
    "How does he sell this product?": "",
    "How do they sell these things?": "",
    "What do they do?": "",
    "What does she say?": "",
    "How does she spend her free time?": "",
    "How do you spend your free time?": "",
    "What do you usually eat for breakfast?": "",
    "What do you teach?": "",
    "When does it start?": "",
    "How does she speak English?": "",
    "Why does he try to do it?": "",
    "What does he need?": "",
    "How does he get money?": "",
    "When does it usually happen?": "",
    "Why does he do it?": "",
    "Why do you believe him?": "",
    "Why do you learn English?": "",
    "What do they offer?": "",
    "Why does he teach English?": "",
    "Where do you work?": "",
    "Why does it seem boring?": "",
    "What do they sell there?": "",
    "How does it seem to you?": "",
    "It seems to me": "",
    "When do they see her?": "",
    "Where do they see her?": "",
    "When does she see him?": "",
    "Why does it happen so often?": "",
    "What do you want to say?": "",
    "When do you do it?": "",
    "Why do you support them?": "",
    "Why does she support him?": "",
    "What do they sell online?": "",
    "When do you watch English movies?": "",
    "Why does it seem interesting to you?": "",
    "Where do you study?": "",
    "What does she know about this thing?": "",
    "How do you use it?": "",
    "Why do you agree?": "",
    "Where does he go?": "",
    "What does it mean?": "",
    "What do you mean?": "",
    "How does she do it?": "",
    "Why do you do it?": "",
    "Why does she tell him about it?": "",
    "When does he come home?": "",
    "Where do they do it?": "",
    "What does she need?": "",
    "How does he say it?": "",
    "When do you learn English?": "",
    "Why do you think so?": "",
    "What do you need?": "",
    "Why does it interest you?": "",
    "Where does he run?": "",
    "Where does he play this game?": "",
    "Why does it seem strange?": "",
    # when where why how what + do/does + subject + verb
    "where does she live?": "",
    "Where does your sister live?": "",
    "When do these lessons start?": "",
    "What does your brother do at work?": "",
    "What do your parents know?": "",
    "Where does your father work?": "",
    "Why does your boss learn English?": "",
    "How does his girlfriend look like?": "",
    "When does your boyfriend find time for it?": "",
    "What does your grandmother grow in her garden?": "",
    "When does this lesson usually start?": "",
    "When does that lesson usually finish?": "",
    "When do the lessons start?": "",
    "When do the lessons finish?": "",
    "What does your wife cook?": "",
    "What does your wife usually cook?": "",
    "What does your husband usually eat?": "",
    "Where do your children study?": "",
    "Where does your sun study?": "",
    "Where does your daughter study?": "",
    "What do your suppliers produce?": "",
    "What do your partners think about this situation?": "",
    "What do your clients usually answer?": "",
    "What does this ticker include?": "",
    "How does the company work?": "",
    "Why does your best friend hate it?": "",
    "How does your sister swim?": "",
    "What does your boss promise?": "",
    "When do the exams start?": "",
    "Why does your friend think differently?": "",
    "Why does your friend think another way?": "",
    "Where does your sun want to study?": "",
    "How does she find time for everything?": "",
    "Why do they refuse to do it?": "",
    "I go to school / work university / i go the park / cinema /  ": "",
    "I want to go there": "",
    "I do it well": "",
    "I do this work well": "",
    "I do this thing well": "",
    "I do these things well": "",
    "How do this students prefer learn English?": "",
    "How does your sister dance?": "",
    "When does this lesson usually start?": "",
    "Why do you use the Internet so often?": "",
    "What does your mother teach?": "",
    "How does your teacher explain it?": "",
    "Why do those things seem so bad?": "",
    "What do all this things mean? ": "",
    "When does your friend usually listen to music?": "",
    "What does your boss need?": "",
    "When do the lessons start?": "",
    "Where does your classmate live?": "",
    "Why does that thing seem bad?": "",
    "Where does your neighbor work?": "",
    "How does your brother play the guitar?": "",
    "Where does your brother study English?": "",
    "Why do your parents watch tv so late?": "",
    "Why does your boss think so?": "",
    "How does the company work?": "",
    "How does his girlfriend look like?": "",
    "What does your grandmother grow in her garden?": "",
    "Why does your husband need it urgently?": "",
    "How does your sister swim?": "",
    "Why do these problems interest you?": "",
    "What does your boss promise?": "",
    "How does your sister do it?": "",
    "Why does your aunt rent a flat?": "",
    "What does this word mean?": "",
    "When do your parents come home?": "",
    "How do your teachers explain it?": "",
    "Where does your teacher write these words?": "",
    "What does this ticket include?": "",
    "When does your boyfriend find time for it?": "",
    "Where does your son study?": "",
    "When does that lesson usually finish?": "",
    "Why does your best friend hate it?": "",
    "How does your friend spend his free time?": "",
    "What does your brother do ar work?": "",
    "How does she find time for everything?": "",
    "How does your brother find time for all these things?": "",
    "What do your parents know?": "",
    "How often does your friend use the Internet?": "",
    "How do your friends pay for it?": "",
    "When do the exams start?": "",
    "Where does your father work?": "",
    "When do the lessons finish?": "",
    "Why do these things seem interesting?": "",
    "Why do these things seem boring?": "",
    "What do your clients usually answer?": "",
    "Why do they refuse to do it?": "",
    "Why does your friend think differently?": "",
    "Why does this idea seem strange?": "",
    "Why does your best friend support them?": "",
    "Where does his wife work?": "",
    "Where does their daughter study?": "",
    "Why does this student need to learn English?": "",
    "I would like to learn English here": "",
    "She would like to study there": "",
    "I'd like": "",
    "She'd like": "",
    "When do the lessons finish?": "",
    "When does the lesson finish?": "",
    "Does he want to have a car?": "",
    "He runs fast": "",
    "Why do these problems interest you?": "",
    "What do all these things mean?": "",
    "Sorry, what do you mean?": "",
    "Why does it seem to you so?": "",
    "My friends don't have an interesting offer": "",
    "Does his wife usually buy expensive things?": "",
    "cheap / always / often / sometimes/": "",
    "Does she listen to this music?": "",
    "Does she support this idea?": "",
    "Does my best friend need my support now?": "",
    "It doesn't interest me": "",
    "I have different interests": "",
    "hobbies": "",
    "I usually get up early": "",
    "Does he want to study in another place?": "",
    "Do your colleagues get 500 dollars a month?": "",
    "Does your cousin believe in ghosts?": "",
    "I believe you": "",
    "I believe in God": "",
    "Why does your husband need it urgently?": "",
    "now / right now": "",
    "My brother doesn't try to learn English": "",
    "Does the teacher want to tell us all the news?": "",
    "Why do those things seem boring?": "",
    "Do you need it right now?": "",
    "Does he play the guitar?": "",
    "violin?": "",
    "Do I show good results?": "",
    "Does he need to learn English more regularly?": "",
    "Does her mother usually stay at home?": "",
    "Do you know it better?": "",
    "I know it better": "",
    "I know it worse": "",
    "He doesn't have his own business": "",
    "Do his students feel progress?": "",
    "I think differently": "",
    "I think another way": "",
    "Do your parents also think so?": "",
    "Do your parents think so, too": "",
    "Does his friend want to continue?": "",
    "Let's continue!": "",
    "Why does it seem strange?": "",
    "Does your classmate run very fast?": "",
    "Does he feel bad?": "",
    "Does she like this idea?": "",
    "What does your mother teach?": "",
    "Does he want to do it one more time?": "",
    "Do you have a house?": "",
    "Does she often fly to the United States?": "",
    "What does it mean?": "",
    "Does she teach English?": "",
    "Why does your best friend support them?": "",
    "How does your teacher explain it?": "",
    "Does this lesson seem very long?": "",
    "Does your brother use the Internet every day?": "",
    "Do you work or study?": "",
    "Why do those things seem bad?": "",
    "Do they know all the information?": "",
    "Does this house look expensive?": "",
    "Does she also know it?": "",
    "What does your brother do at work?": "",
    "Do you often see her?": "",
    "Does she use the Internet every day?": "",
    "How does your sister dance?": "",
    "Does it seem boring?": "",
    "Does she speak English?": "",
    "Do you want to tell her this thing?": "",
    "Does her mother stay at home?": "",
    "Does she need to rent a flat?": "",
    "When do you watch English movies?": "",
    "Does it interest you?": "",
    "Do your friends have an interesting offer?": "",
    "What does your boss need?": "",
    "How does the company work?": "",
    "Do you see your progress?": "",
    "Does she know it, too?": "",
    "When does he come home?": "",
    "Do you need his help?": "",
    "Those things don't interest him": "",
    "What do you think about it?": "",
    "His parents don't tell him everything": "",
    "Do they usually come late?": "",
    "Why does he try to do it?": "",
    "Does this boy show a good result?": "",
    "Does she usually sleep well?": "",
    "Does he do business?": "",
    "Do the results seem good?": "",
    "Does this thing happen rarely?": "",
    "How do these students prefer to learn English?": "",
    "Does our rest include it?": "",
    "Does she need it urgently?": "",
    "Does he need all the information?": "",
    "How does she explain it?": "",

}