slovar = {
    "Do your parents think so, too?": "",
    "Does your mother work or stay at home?": "",
    "Do I do it very well?": "",
    "Does it really help you?": "",
    "Do you have any brothers or sisters?": "",
    "Do they see her?": "",
    "Do you think so?": "",
    "Does she need this information?": "",
    "How does your friend spend his free time?": "",
    "When does it usually happen?": "",
    "Where does your father work?": "",
    "Does his sister often meet him?": "",
    "Why does it seem boring?": "",
    "My friends don't have an interesting offer": "",
    "Do you understand me?": "",
    "These results don't seem very good": "",
    "Does she understand us?": "",
    "Does she often forget it?": "",
    "Do you really understand me?": "",
    "When does your boyfriend find time for it?": "",
    "Does it seem really strange?": "",
    "Do you have a boyfriend?": "",
    "Does your cousin know it better?": "",
    "Does it help him?": "",
    "Does she want to call them?": "",
    "Do these results seem very good?": "",
    "My teacher doesn't say it": "",
    "Where does their daughter study?": "",
    "Does she believe in God?": "",
    "When do you do it?": "",
    "Why do you agree?": "",
    "Does this lesson help you?": "",
    "Why does this idea seem strange?": "",
    "Do these ideas seem interesting?": "",
    "Does it really work?": "",
    "Do they come late?": "",
    "Does it interest you?": "",
    "Do you do it professionally?": "",
    "What does she know about this thing?": "",
    "Does your friend have an interesting offer?": "",
    "Do these girls know it very well?": "",
    "Does he want to get more money?": "",
    "Does your father try to do it?": "",
    "Do these boys remember it very well?": "",
    "Does the read magazines?": "",
    "How does it seem to you?": "",
    "Does she need your advice?": "",
    "What does she need?": "",
    "Does your teacher often say it?": "",
    "Do you have a flat?": "",
    "Why do you learn English?": "",
    "Why does he make so many mistakes?": "",
    "This result seems good": "",
    "Does this result seem very good?": "",
    "Why does he do it?": "",
    "Do you help your parents?": "",
    "How does your brother play the guitar?": "",
    "This thing interests them": "",
    "How does she spend her free time?": "",
    "What does she remember?": "",
    "Do you want to have your own business?": "",
    "Why do you support them?": "",
    "Where do you work?": "",
    "What does your boss promise?": "",
    "Does your teacher agree with it?": "",
    "Where do they live?": "",
    "My friends have an interesting offer": "",
    "What do they offer?": "",
    "Why does it happen so often?": "",
    "How does his girlfriend look like?": "",
    "What do you need?": "",
    "How does she speak English?": "",
    "When do the lessons start?": "",
    "Do those things interest her?": "",
    "Does she want to become a teacher?": "",
    "My brother tries to learn English": "",
    "Why does your friend think so?": "",
    "Does he live there?": "",
    "Why do you think so?": "",
    "Those things interest her": "",
    "Does she try to do it?": "",
    "Do we learn English effectively?": "",
    "Do these boys show good results?": "",
    "Why does that thing seem bad?": "",
    "Where does his neighbor work?": "",
    "What do your clients usually answer?": "",
    "Why does this student need to learn English?": "",
    "What do they want to say?": "",
    "Why does your aunt want to rent a flat?": "",
    "When does she see him?": "",
    "Why does your best friend hate it?": "",
    "Does she often visit him?": "",
    "Does she like this subject?": "",
    "Does she talk to him?": "",
    "Do you have an interesting offer now?": "",
    "Does he play the piano?": "",
    "These results don't seem good": "",
    "What do they sell there?": "",
    "Why do you use the internet so often?": "",
    "Does this story seem short?": "",
    "Does her husband usually buy cheap things?": "",
    "That thing doesn't interest them": "",
    "This house looks very expensive": "",
    "Does it really help you and your friends?": "",
    "Does he often stay at home?": "",
    "My best friend needs support now": "",
    "Does that thing seem interesting?": "",
    "Do your colleagues live near this place?": "",
    "Does it seem really interesting?": "",
    "What do they do?": "",
    "Do you try to learn English?": "",
    "Do these girls make mistakes when they speak English?": "",
    "Why do you believe him?": "",
    "Where do they see her?": "",
    "Why do they refuse to do it?": "",
    "Do you live together?": "",
    "Where does his wife work?": "",
    "How does your brother find time for all these things?": "",
    "His parents tell him everything": "",
    "Where does he go?": "",
    "Our rest doesn't include it": "",
    "Do you often go there?": "",
    "Her mother doesn't stay at home": "",
    "She works ": "",
    "My teacher says it": "",
    "Does he go to bed early?": "",
    "This result seems good": "",
    "Why does she tell him about it?": "",
    "Does she live there?": "",
    "How does she say it?": "",
    "Does it help you a lot": "",
    "Does it help you greatly?": "",
    "Does this result seem very good?": "",
    "How does it work?": "",
    "Does that thing interest you?": "",
    "Do these things interest you?": "",
    "When do you see him?": "",
    "Do they want to try to do it?": "",
    "Why do your parents watch tv so late?": "",
    "When does this lesson usually start?": "",
    "Do their friends usually pay for it?": "",
    "Do they work there?": "",
    "Does she often see her boss?": "",
    "Does you teacher also think so?": "",
    "When do your parents come home?": "",
    "Does she draw well?": "",
    "How does he get money?": "",
    "Where does it happen?": "",
    "Do they often say it?": "",
    "Where does your son study?": "",
    "When do these exams start?": "",
    "Why does it interest you?": "",
    "What does your grandmother grow in the garden?": "",
    "Of course": "",
    "Certainly": "",
    "Sure": "",
    "Does he read newspapers?": "",
    "Does it happen from time to time?": "",
    "How does your sister swim?": "",
    "How do you spend your free time?": "",
    "Does he prefer to learn English here?": "",
    "Does their rest include it?": "",
    "Hoe do your teacher explain it?": "",
    "Does he live there?": "",
    "What does he need?": "",
    "Do they help you?": "",
    "Does it seem to her really interesting": "",
    "Does his student learn English effectively?": "",
    "When does your friend listen to music?": "",
    "What do they sell online?": "",
    "My friend has an interesting offer": "",
    "Does he need money now?": "",
    "Do you have a brother or a sister?": "",
    "Do I make mistakes?": "",
    "He has his own business": "",
    "Do your parents know it?": "",
    "What do they know?": "",
    "How do you do these exercises?": "",
    "What results do you have?": "",
    # Present simple - to be
    # I am : We /You /They are: He /She / Ir is:
    # I am in the park
    "Speak English naturally": "",
    "I'm in the park": "",
    "We are at home": "",
    "We're at home": "",
    "You are a good teacher": "",
    "You're a good teacher": "",
    "They are talented students": "",
    "They're talented students": "",
    "He is my good friend": "",
    "He's my good friend": "",
    "She is my girlfriend": "",
    "It is interesting": "",
    "I'm /We're / You're  / They're / He's /She's /It's": "",
    "I'm in my room": "",
    "I'm outside": "",
    "I'm inside": "",
    "We're good students": "",
    "We're hard-working": "",
    "We're hard-working students": "",
    "You're the best teacher": "",
    "You're a good teacher": "",
    "You're kind": "",
    "They're good people": "",
    "person-people": "",
    "He is a good person": "",
    "They're here": "",
    "They're there": "",
    "He's the best student": "",
    "He's a sportsman": "",
    "He's my boss": "",
    "She's a manager": "",
    "She's a housewife": "",
    "She's a beautiful girl": "",
    "She's beautiful": "",
    "It's my new car": "",
    "It's hia old car": "",
    "It's a big building": "",
    "It's a small house": "",
    "It's on the table": "",
    "It's on my desk": "",
    "It's on my bed": "",
    "It's in this city": "",
    "It's in this town": "",
    "It's good": "",
    "It's a good idea": "",
    "It's bad": "",
    "It's a bad idea": "",
    "It's a good result": "",
    "It's a long story": "",
    "It's an interesting detail": "",
    "It's a short phrase": "",
    "It's important": "",
    "It's an important thing": "",
    "It's difficult": "",
    "It's a big problem": "",
    "It's a small problem": "",
    "It's very interesting": "",
    "It's so interesting": "",
    "I'm busy": "",
    "I'm tired": "",
    "We're at the airport": "",
    "You're a good friend": "",
    "They're in Russia": "",
    "They're in the United States": "",
    "He's in China": "",
    "She's in America": "",
    "It's in our country": "",
    "It's good": "",
    "It's a good idea": "",
    "It's so difficult": "",
    "He's my good friend": "",
    "Do it": "",
    "Say it": "",
    "Check it": "",
    "Speak English naturally": "",
    "It's my new car": "",
    "It's an interesting offer": "",
    "She's beautiful": "",
    "We're good students": "",
    "It's too long": "",
    "It's bad": "",
    "It's a bad idea": "",
    "It's so important": "",
    "It's an easy exam": "",
    "It's a difficult exam": "",
    "She's a manager": "",
    "I'm a sales manager": "",
    "It's a good example": "",
    "I'm in the park": "",
    "You're a good teacher": "",
    "They are talented students": "",
    "You are talented": "",
    "I'm in my room": "",
    "It's a sort phrase": "",
    "It's difficult": "",
    "They're in Russia": "",
    "It's a small problem": "",
    "It's a very good lesson": "",
    "It's a big problem": "",
    "It's so good": "",
    "Yoy speak English very well": "",
    "We're in the park now": "",
    "He's a sportsman": "",
    "It's so easy": "",
    "It's in this country": "",
    "He is my father": "",
    "He's at school": "",
    "It's a big building": "",
    "It's his old car": "",
    "He's the best student": "",
    "We're busy now": "",
    "It's a good result": "",
    "It's a excellent result": "",
    "She's in America": "",
    "I'm tired": "",
    "I want to speak English naturally": "",
    "It's in this city": "",
    "It's a small mistake": "",
    "It's very interesting": "",
    "It's in my flat": "",
    "She's tired": "",
    "She's my mother": "",
    "It's interesting": "",
    "She's a beautiful": "",
    "They're good parents": "",
    "It's on the table": "",
    "It's on my desk": "",
    "You're a good teacher": "",
    "She's her daughter": "",
    "It's on my bad": "",
    "It's a big mistake": "",
    "It's an important thing": "",
    "He's a talented student": "",
    "It's a important subject": "",
    "It's a good lesson": "",
    "I'm inside": "",
    "It's a good exercise": "",
    "It's really interesting": "",
    "He's my boss": "",
    "You're a good friend": "",
    "He's tired": "",
    "He's a director": "",
    "They're friends": "",
    "They're our friends": "",
    "They're in the United States": "",
    "They're in the United Kingdom": "",
    "It's boring": "",
    "He's a professional teacher": "",
    "You're the best teacher": "",
    "We're hard-working students": "",
    "He's the best teacher in the world": "",
    "I'm a hard-working student": "",
    "He's his son": "",
    "It's too short": "",
    "It's so bad": "",
    "It's an interesting thing": "",
    "It's important": "",
    "It's a difficult thing": "",
    "It's a long story": "",
    "I'm outside": "",
    "It's a very interesting lesson": "",
    "They're students": "",
    "He's my old friend": "",
    "It's a bad result": "",
    "He's my classmate": "",
    "She's a housewife": "",
    "We're hard-working": "",
    "He's my boyfriend": "",
    "You're kind": "",
    "He's a good person": "",
    "It's an interesting detail": "",
    "It's so interesting": "",
    "We're at home": "",
    "They're in Spain": "",
    "It's the best thing": "",
    "We're at the airport": "",
    "It's a very interesting thing": "",
    "I'm busy": "",
    "He's a kind person": "",
    "They're good people": "",
    "I'm at home": "",
    "I'm a good students and you're a good teacher": "",
    # present simple - to be
    # I'm / we're / you're / they're / he's / she's / it's
    # The lesson is interesting
    # Your lessons are really good
    # This student is talented
    "The room is small": "",
    "This idea is very interesting": "",
    "This result is real": "",
    "These things are very strange": "",
    "These results are wonderful": "",
    "These results are terrible": "",
    "This teacher is the best in the world": "",
    "This lesson is free": "",
    "All these lessons are free": "",
    "This lesson is very useful": "",
    "All these lessons are very useful": "",
    "This method is very effective": "",
    "The boy is talented": "",
    "My sister is in bad": "",
    "My brother is in the kitchen": "",
    "My mother is in the bathroom": "",
    "My parents are angry": "",
    "The keys are on the table": "",
    "The book is red": "",
    "The number is short": "",
    "The hotel is expensive": "",
    "The ticket is cheap": "",
    "The tickets are cheap": "",
    "My friend is ill": "",
    "The chair is comfortable": "",
    "This chair is comfortable": "",
    "These chairs are comfortable": "",
    "The information is useful": "",
    "This information is useful": "",
    "These recommendations are the best": "",
    "You're the best": "",
    "These lessons are the best": "",
    "The boy is strong": "",
    "The girl is beautiful": "",
    "The book is boring": "",
    "The information is useless": "",
    "useful- full of use": "",
    "useless - without use": "",
    "These people are rich": "",
    "His uncle is poor": "",
    "I'm 30": "",
    "I'm from Russia": "",
    "I'm Russian": "",
    "I'm a manager": "",
    "My friend is 25": "",
    "He's 25": "",
    "He's from the United States": "",
    "My friend is from the United States": "",
    "He's American": "",
    "My friend is American": "",
    "He's a designer": "",
    "My friend is a designer": "",
    "All these lessons are very useful": "",
    "The ticket is expensive": "",
    "The chair is comfortable": "",
    "My friend is 25": "",
    "My cousin is tired": "",
    "These lessons are the best": "",
    "The pen is black": "",
    "The offer is so interesting": "",
    "I'm Russian": "",
    "The girl is beautiful": "",
    "The video is really useful": "",
    "His father is a businessman": "",
    "My relatives are in America": "",
    "This information is useless": "",
    "The key is on the table": "",
    "These results are wonderful": "",
    "His son is lazy": "",
    "This teacher is the best teacher in the world": "",
    "This lesson is free": "",
    "These people are rich": "",
    "He is a designer": "",
    "Your lessons are really good": "",
    "The book is boring": "",
    "My best friend is a businessman": "",
    "The lesson is difficult": "",
    "You are the best teacher in the world": "",
    "The hotel is expensive": "",
    "My parents are happy": "",
    "This room is small": "",
    "My mother is in the bathroom": "",
    "This lesson is very useful": "",
    "The number is too long": "",
    "He's a student": "",
    "This result is real": "",
    "The tickers are cheap": "",
    "My parents are angry": "",
    "The chair is comfortable": "",
    "My boss is very busy": "",
    "These chairs are comfortable": "",
    "All his lessons are free": "",
    "He is ill": "",
    "He feels sick": "",
    "This method is really effective": "",
    "My mother is a doctor": "",
    "Your lesson is very informative": "",
    "My relative is in England": "",
    "These recommendations are the best": "",
    "Her car is new": "",
    "He's Russian": "",
    "This thing is terrible": "",
    "That method is very effective": "",
    "The story is so long": "",
    "These results are terrible": "",
    "This boy is the best student": "",
    "This information is useful": "",
    "These students are so talented": "",
    "He's American": "",
    "The lesson is interesting": "",
    "The manager is very strange": "",
    "This idea is new": "",
    "His keys are on the table": "",
    "The boy is talented": "",
    "The exam is easy": "",
    "I'm 30": "",
    "His brother is in hospital": "",
    "This student is very talented": "",
    "The book is red": "",
    "Her daughter is very hard-working": "",
    "This lesson is free": "",
    "We all know it": "",
    "Everyone knows it": "",
    "All people know it": "",
    "This lesson is boring": "",
    "The girl is talented": "",
    "Your ideas are wonderful": "",
    "His father is a businessman and his mother is a doctor": "",
    "His girlfriend is beautiful": "",
    "these things are very strange": "",
    "She's 25": "",
    "The book is in the kitchen": "",
    "This problem is small": "",
    "My father is 40": "",
    "I'm a manager": "",
    "His father is rich": "",
    "His idea is good": "",
    "Her ideas are interesting": "",
    "This house is new": "",
    "That house is old": "",
    "All these houses are now": "",
    "All those houses are old": "",
    "This building is very high": "",
    "This person is very good": "",
    "My computer is very powerful": "",
    "My computer is new": "",
    "I'm American": "",
    "They're from America": "",
    "My progress is real": "",
    "My friend is ill": "",
    "My sister is in bad": "",
    "This exercise is too difficult": "",
    "That exercise is too easy": "",
    "These exercise are so useful": "",
    "Those exercise are useless": "",
    "My English teacher is very professional": "",
    # present simple negative
    # I am at home
    # I am not at home
    # We are inside
    # We are not inside
    "You are right": "",
    "You are not right": "",
    "They are rich": "",
    "They are not rich": "",
    "He is a businessman": "",
    "He is not a businessman": "",
    "She is a manager": "",
    "She is not a manager": "",
    "It is new car": "",
    "It is not new car": "",
    "I'm at home": "",
    "I'm not at home": "",
    "I'm at work": "",
    "We're inside": "",
    "We aren't inside": "",
    "you're right": "",
    "You aren't right": "",
    "You're wrong": "",
    "They're rich": "",
    "They aren't rich": "",
    "They're poor": "",
    "He's a businessman": "",
    "He isn't a businessman": "",
    "He's a manager": "",
    "She's a manager": "",
    "She isn't a manager": "",
    "She's a businesswoman": "",
    "It's a new car": "",
    "It isn't a new car": "",
    "It's an old car": "",
    "I'm not / we /you / they aren't   he / she / it / isn't": "",
    "I'm not married": "",
    "I'm single": "",
    "We aren't friends and we aren't enemies": "",
    "They aren't partners": "",
    "They are only friends": "",
    "He isn't hungry": "",
    "He is thirsty": "",
    "She isn't American": "",
    "She's Russian": "",
    "it isn't bad": "",
    "It's very good": "",
    "I'm not hungry": "",
    "I don't want to eat": "",
    "We aren't at home": "",
    "We are in the park": "",
    "You aren't lazy": "",
    "You're hard-working": "",
    "They aren't stupid": "",
    "They're clever": "",
    "silly": "",
    "She isn't our teacher": "",
    "She's their teacher": "",
    "He isn't her friend": "",
    "He's our friend": "",
    "It isn't a good idea": "",
    "It's a very bad idea": "",
    "I'm not busy": "",
    "I'm free": "",
    "we aren't student": "",
    "We work": "",
    "You aren't right": "",
    "You're wrong": "",
    "You're mistaken": "",
    "They are together but they aren't married": "",
    "He isn't tall": "",
    "He is short": "",
    "It isn't on the table": "",
    "It's on the chair": "",
    "if I'm not mistaken": "",
    "I think he is right if I'm not mistaken": "",
    "It isn't cold": "",
    "It's warm": "",
    "It isn't good": "",
    "It's a bad": "",
    "It isn't interesting": "",
    "It's boring": "",
    "It isn't strange": "",
    "It's normal": "",
    "It's easy": "",
    "It's obvious": "",
    "It isn't difficult": "",
    "It isn't sunny": "",
    "It's cloudy": "",
    "It's rainy": "",
    "It's windy": "",
    "It isn't an interesting job": "",
    "It's a boring job": "",
    "It isn't on the right": "",
    "It's on the left": "",
    "It isn't a good choice": "",
    "It's a bad choice": "",
    # present simple to be (negative)
    "He isn't lazy": "",
    "He isn't a lazy person": "",
    "I'm not at home": "",
    "I'm at work": "",
    "We aren't at home": "",
    "We're in the park": "",
    "It isn't an effective method": "",
    "I'm not married": "",
    "I'm single": "",
    "She isn't a designer": "",
    "She's a doctor": "",
    "He isn't hungry": "",
    "He is thirsty": "",
    "He isn't a businessman": "",
    "He is a manager": "",
    "We aren't friends and we aren't enemies": "",
    "It isn't cold": "",
    "It's warm": "",
    "I'm not tired": "",
    "It isn't bad": "",
    "it's good": "",
    "It isn't a bad idea": "",
    "It's a good idea": "",
    "I'm not American": "",
    "I'm Russian": "",
    "It isn't sunny": "",
    "It's cloudy": "",
    "It's rainy": "",
    "It isn't windy": "",
    "They aren't expensive": "",
    "It isn't a cheap thing": "",
    "They aren't rich": "",
    "They're poor": "",
    "It isn't the best choice": "",
    "It isn't comfortable": "",
    "It isn't effective": "",
    "She isn't manage": "",
    "She's a housewife": "",
    "It isn't an expensive thing": "",
    "It isn't strange": "",
    "It's normal": "",
    "You aren't right": "",
    "It isn't interesting": "",
    "It isn't an interesting book": "",
    "It isn't boring": "",
    "It isn't a boring movie": "",
    "They aren't stupid - silly - foolish": "",
    "They're clever - smart": "",
    "It isn't on the table": "",
    "It's on the chair": "",
    "It isn't free": "",
    "You need to pay": "",
    "It isn't difficult": "",
    "It's easy": "",
    "It's obvious": "",
    "He isn't an angry person": "",
    "He isn't rich": "",
    "He isn't a rich person ans he isn't busy": "",
    "We aren't inside": "",
    "We're outside": "",
    "It isn't an interesting offer": "",
    "My friends aren't there": "",
    "My friends are here": "",
    "I'm not hungry": "",
    "I don't want to eat": "",
    "I'm not from Canada": "",
    "I'm from the United States": "",
    "She isn't American": "",
    "She's Russian": "",
    "It isn't a new car": "",
    "It's an old car": "",
    "They aren't in America": "",
    "They're in London": "",
    "It isn't a bad choice": "",
    "It's a very good choice": "",
    "They aren't in the park": "",
    "They're in another place": "",
    "It isn't on the right": "",
    "It's on the left": "",
    "It isn't a boring lesson": "",
    "It isn't useful": "",
    "You aren't lazy": "",
    "You are hard-working": "",
    "They are only friends": "",
    "I'm not at home": "",
    "I'm in the office": "",
    "We aren't students": "",
    "He isn't our boss": "",
    "She isn't our teacher": "",
    "We aren't classmates": "",
    "She isn't my girlfriend": "",
    "He isn't my boyfriend": "",
    "It isn't far": "",
    "It's near": "",
    # present simple to be (negative)
    # I'm not // We/you/they aren't // he/ she / it isn't
    "The man isn't rich": "",
    "The woman isn't a manager": "",
    "My result isn't so bad": "",
    "Our results aren't brilliant": "",
    "This information isn't so important": "",
    "His flat isn't small": "",
    "These ideas aren't new": "",
    "Their ideas aren't so innovative": "",
    "This thing isn't popular now": "",
    "These things aren't popular now": "",
    "This knowledge isn't basic": "",
    "His life isn't easy": "",
    "Her life isn't very difficult": "",
    "These lessons aren't useless": "",
    "They are very useful": "",
    "My partner isn't afraid of difficulties": "",
    "The car isn't new": "",
    "It's old": "",
    "His lifestyle isn't healthy": "",
    "Her way of life isn't healthy": "",
    "His sister isn't pregnant": "",
    "This job isn't well-paid": "",
    "This place isn't dangerous": "",
    "My friends aren't in Moscow": "",
    "You money isn't enough": "",
    "Our computer isn't powerful": "",
    "His partners aren't reliable": "",
    "Her boyfriend isn't businessman": "",
    "They plan isn't so bad": "",
    "This money isn't enough": "",
    "That money isn't enough": "",
    "This channel isn't so bad": "",
    "That channel isn't popular": "",
    "These videos aren't so funny": "",
    "Those videos aren't good enough": "",
    "This story isn't long": "",
    "That book isn't short": "",
    "These things aren't so important": "",
    "Those people aren't right": "",
    "Those problems aren't big": "",
    "It isn't an old building": "",
    "The book isn't cheap": "",
    "The result isn't good enough": "",
    "My problems aren't big": "",
    "This thing isn't popular now": "",
    "The tests in this book aren't easy": "",
    "My boss isn't at work": "",
    "His progress isn't big": "",
    "His lifestyle isn't healthy": "",
    "My friends aren't in Moscow": "",
    "The results aren't good enough": "",
    "These things aren't good enough": "",
    "Her progress isn't good enough": "",
    "These ideas aren't new": "",
    "That problem isn't big": "",
    "This story isn't long": "",
    "This job isn't well-paid": "",
    "These videos aren't so funny": "",
    "My parents aren't in the park": "",
    "Those videos aren't good enough": "",
    "Tests aren't so easy for me": "",
    "His money isn't enough": "",
    "The books aren't expensive": "",
    "These things aren't so important": "",
    "Her boyfriend isn't there": "",
    "That book isn't short": "",
    "Their plan isn't so bad": "",
    "The man isn't rich": "",
    "It isn't in America": "",
    "It's in China": "",
    "Our computer isn't powerful": "",
    "That money isn't enough": "",
    "The books aren't cheap": "",
    "My bag isn't in my room": "",
    "This information isn't enough": "",
    "The exercises aren't difficult": "",
    "My result isn't so bad": "",
    "This thing isn't serious": "",
    "These problems aren't big": "",
    "Their problems aren't small": "",
    "The lesson isn't boring": "",
    "This knowledge isn't basic": "",
    "English isn't easy": "",
    "That channel isn't so popular": "",
    "My partner isn't afraid of difficulties": "",
    "The book isn't expensive": "",
    "This channel isn't so bad": "",
    "The test isn't easy": "",
    "His sister isn't pregnant": "",
    "Those people aren't right": "",
    "Her life isn't very difficult": "",
    "This product isn't new": "",
    "These exams aren't easy": "",
    "His life isn't easy": "",
    "Her way of life isn't healthy": "",
    "This problem isn't big": "",
    "This place isn't dangerous": "",
    "These things aren't popular now": "",
    "The car isn't new": "",
    "It's old": "",
    "His girlfriend isn't here": "",
    "This method isn't good enough": "",
    "His flat isn't small": "",
    "All this money isn't enough": "",
    "His partners aren't reliable": "",
    "The woman isn't a manager": "",
    "This exercises isn't difficult": "",
    "The exercises isn't difficult": "",
    "His friend isn't reliable enough": "",
    "This money isn't enough": "",
    "These lessons aren't useless": "",
    "They are very useful": "",
    "Your lesson aren't boring at all": "",
    "Their results aren't brilliant": "",
    "Their ideas aren't so innovative": "",
    "His English isn't fluent": "",
    "Her boyfriend isn't a businessman": "",
    "These words aren't important": "",
    "This phrase isn't important": "",
    # Am i : Are we/you/they: Is he/she/it ?
    # Am I talented?
    # Are we in the right place?
    "Are you in his office?": "",
    "Are they your colleagues?": "",
    "Is he your acquaintance?": "",
    "Is she a housewife?": "",
    "Is it expensive?": "",
    "Am I a good student?": "",
    "Am I wrong?": "",
    "Am I in the wrong place?": "",
    "Are we far from this place?": "",
    "Are we near this place?": "",
    "Are we in one group?": "",
    "Are you really happy?": "",
    "Are you together?": "",
    "Are you in one team?": "",
    "Are they good specialists?": "",
    "Are they experts in this area?": "",
    "Are they experienced?": "",
    "Is he happy?": "",
    "Is he a happy person?": "",
    "Is he married?": "",
    "Is she his wife?": "",
    "Is she afraid of it?": "",
    "Is she a native speaker?": "",
    "Is it a pleasant feeling?": "",
    "Is it effective?": "",
    "Is it an effective method?": "",
    "Is it a popular channel?": "",
    "Is it a strange thing?": "",
    "Is it a global problem?": "",
    "Is it sunny?": "",
    "Is it windy?": "",
    "It is cold": "",
    "Is it cold?": "",
    "Is it a cold day?": "",
    "Is it a warm day?": "",
    "Is he a businessman?": "",
    "Is he a successful businessman?": "",
    "Is he a very successful businessman?": "",
    "Is she an actress?": "",
    "Is she a talented actress?": "",
    "Is she a very talented actress?": "",
    "It is effective": "",
    "It is interesting": "",
    "It is obvious": "",
    "It is good": "",
    "It is bad": "",
    "It is clear": "",
    "It is right": "",
    "We learn English effectively": "",
    "It's an effective method": "",
    "Is he a successful businessman?": "",
    "Are they professional workers?": "",
    "Is it a cold day?": "",
    "Is he a strange person?": "",
    "Is he a popular singer?": "",
    "Is it a well-paid job?": "",
    "Is she a famous writer?": "",
    "Are you there?": "",
    "Are they right?": "",
    "Am I a good student?": "",
    "Is she a talented actress?": "",
    "Is he often angry?": "",
    "Are we in the right place?": "",
    "Are they only friends?": "",
    "Am I in the wrong place?": "",
    "Are you together?": "",
    "Are they your colleagues?": "",
    "Are they managers?": "",
    "Is it an interesting book?": "",
    "Are you afraid of difficulties?": "",
    "Is he busy at the moment?": "",
    "Is he a hard-working person": "",
    "Is she pregnant?": "",
    "Is he wrong?": "",
    "Is it rainy day?": "",
    "Is he a businessman?": "",
    "Is it windy?": "",
    "Is it a long story?": "",
    "Is it a new project?": "",
    "Is she a famous actress?": "",
    "Are we near this place?": "",
    "Is he a professional teacher?": "",
    "Is it in China or in America?": "",
    "Is he happy?": "",
    "Is he a very successful businessman?": "",
    "Are they serious people?": "",
    "Is it a cheap thing?": "",
    "Are they strange people?": "",
    "Are you in this hotel?": "",
    "Is it rainy?": "",
    "Is it a popular channel?": "",
    "Are they healthy?": "",
    "Is he a talented student?": "",
    "Is it easy or difficult?": "",
    "Am I wrong?": "",
    "Is he your boss?": "",
    "Is it a powerful computer?": "",
    "Is it an expensive thing?": "",
    "Is she a housewife?": "",
    "Are you a designer?": "",
    "Is it cold?": "",
    "Is he strong?": "",
    "Is he married?": "",
    "Is he reliable enough?": "",
    "Is he a lazy boy?": "",
    "Are we in one group?": "",
    "Is she a very talented actress?": "",
    "Is it a dangerous place?": "",
    "Is it sunny?": "",
    "Are they very good workers?": "",
    "Is he a talented actor?": "",
    "Are they wrong?": "",
    "Is it an innovative idea?": "",
    "Is he an experienced teacher?": "",
    "Are they good specialists?": "",
    "Is it a global problem?": "",
    "Is he your best friend?": "",
    "Is it expensive or cheap?": "",
    "Are they native speakers?": "",
    "Are you really happy?": "",
    "Is she a businesswoman?": "",
    "Is it a warm day?": "",
    "Is it a good plan?": "",
    "Is it cloudy?": "",
    "Is he your acquaintance?": "",
    "Is he right?": "",
    "Is it a strange thing?": "",
    "Is she an actress?": "",
    "Is it a funny video?": "",
    "Is it very important?": "",
    "Are they experts in this area?": "",
    "Are we far from this place?": "",
    "Is she your acquaintance?": "",
    "Is she a successful businesswoman?": "",
    "Are you here?": "",
    "Is it effective?": "",
    "Is he a happy person?": "",
    "Is she afraid of it?": "",
    "Are they reliable friends?": "",
    "Am I talented?": "",
    "Are you in his office?": "",
    "Is it a very effective method?": "",
    "Is it windy?": "",
    "Is he really happy?": "",
    "Are they experienced?": "",
    "Is she a teacher?": "",
    "Is it interesting or boring?": "",
    "Is it expensive?": "",
    "Is it a sunny day?": "",
    "Are you in one team or not?": "",
    "Is she a native speaker?": "",
    "Is it a pleasant feeling?": "",
    "Is it an effective lesson?": "",
    "Is she your classmate?": "",
    "Are they rich?": "",
    "Is it good or bad?": "",
    "Is it a wonderful result?": "",
    # Am i : Are we/you/ they : is he /she /it?
    "Are these lessons really effective?": "",
    "Is his father rich?": "",
    "Is her mother a businesswoman?": "",
    "Are our friends there?": "",
    "Is word new for you?": "",
    "Is this school good enough?": "",
    "Is this detail important?": "",
    "Is this hotel so expensive?": "",
    "Is your computer so powerful?": "",
    "Is this thing really necessary?": "",
    "Is his method different?": "",
    "Is this level basic?": "",
    "Is his level high enough?": "",
    "Are all  these videos really useful?": "",
    "Is his girlfriend very emotional": "",
    "Are your ideas similar?": "",
    "Are his ideas the same?": "",
    "Are these methods traditional?": "",
    "Are your parents at home?": "",
    "Is your father a businessman?": "",
    "Is your brother a freelancer?": "",
    "Is your mother a housewife?": "",
    "Is this money enough?": "",
    "Is our knowledge enough?": "",
    "Is the news sad?": "",
    "Is this information reliable?": "",
    "Are the boys busy at the moment?": "",
    "Are the girls with a teacher?": "",
    "Is the boy really so talented?": "",
    "Is the girl the best student?": "",
    "Is the computer expensive?": "",
    "Is the result good enough?": "",
    "Are the results satisfactory?": "",
    "Is the progress slow?": "",


}