slovar = {

    "dear Miss Richards,": "Дорогая мисс Ричардс",
    "this is your room": "это твоя комната, это ваша комната",
    "i'm in a hurry": "я тороплюсь",
    "my handbag's been stolen": "мою сумку украли",
    "good luck!": "удачи!",
    "the train's running late": "поезд опаздывает",
    "do you mind if I sit here?": "не возражаете, если я здесь сяду?",
    "everywhere": "везде",
    "good morning": "доброе утро (используется до полудня)",
    "pull": "На себя",
    "all the best!": "всего хорошего!",
    "you'll need to change at Reading": "вам надо сделать пересадку в Рединге",
    "underground": "Метро",
    "welcome to England": "добро пожаловать в Англию",
    "i don't agree": "я не согласен (согласна)",
    "i like him": "мне нравится он",
    "is the meter switched on?": "включен ли таксометр?",
    "i taught myself": "я выучил самостоятельно",
    "i understand": "я понимаю",
    "have you been here long?": "ты уже давно тут?",
    "would you like a soft drink?": "хочешь попить (буквально: безалкогольный напиток)?",
    "i'm looking forward to it": "я с нетерпением жду этого",
    "yes, I've got a young baby": "да, у меня малыш",
    "happy Easter!": "хороших пасхальных праздников!",
    "see you soon!": "до скорого!",
    "congratulations!": "поздравления!",
    "i'm at the Metropolitan Hotel": "я в отеле «Метрополь»",
    "tomorrow night": "завтра вечером",
    "it's not serious": "это не серьезно",
    "i can't find my keys": "я не могу найти мои ключи",
    "could you tell me when we get to the university?": "скажите мне, пожалуйста, когда мы доедем до университета",
    "private": "Частная собственность",
    "what's this called?": "как это называется?",
    "as soon as possible": "как можно быстрее",
    "how much would it cost to Heathrow Airport?": "сколько стоит доехать до аэропорта «Хитроу»?",
    "i speak French, Spanish, and a little Russian": "я говорю по-французски, по-испански и немного по-русски",
    "how do you open the boot?": "как открывается багажник?",
    "does this bus stop at?": "останавливается ли этот автобус в …?",
    "i'd like a first class return to Bristol": "я хотел бы билет первого класса в оба конца до Бристоля",
    "hang on a second": "подожди секундочку",
    "bless you!": "будь здоров! (после чихания)",
    "sorry to hear that": "жаль это слышать",
    "have you got anything smaller?": "у вас есть более мелкие деньги?",
    "there's a fire": "там пожар",
    "i'll show you the controls": "я покажу вам выключатели",
    "calling at": "Останавливается в ...",
    "would you like a?": "хочешь …?",
    "i don't like her": "мне не нравится она",
    "this week": "на этой неделе",
    "where are the indicators?": "где включаются поворотники?",
    "please sit down": "садитесь, пожалуйста",
    "i'd like to report a theft": "я хотел бы заявить о краже",
    "i'm sorry": "извините",
    "get a move on!": "пошевеливайся!",
    "it has to be returned by 2pm on Saturday": "она должна быть возвращена до 2 часов дня в воскресенье",
    "same to you!": "и тебе того же!",
    "which platform do I need for?": "какая платформа на …?",
    "there": "там",
    "what's happening?": "что происходит?",
    "my phone's been stolen": "мой телефон украли",
    "yes, I've got two sisters": "да, у меня есть две сестры",
    "how do you pronounce this word?": "как произносится это слово?",
    "i speak fluent German": "я говорю свободно по-немецки",
    "are you sure?": "ты уверен?",
    "in my opinion": "по моему мнению, ...",
    "i don't think so": "я так не думаю",
    "platform 11 for the 10.22 to guildford": "платформа 11 в 10:22 на Гилдфорд",
    "just a minute": "одну минутку",
    "thanks for your email": "спасибо за имейл",
    "how often do the buses run to Bournemouth?": "как часто ходят автобусы на Борнмут?",
    "absolutely": "безусловно",
    "what's the matter?": "в чем дело?",
    "happy birthday!": "с днем рождения!",
    "dear Madam,": "Дорогая Госпожа,",
    "not at all": "не стоит благодарности",
    "i'd like a return to Newcastle, coming back on Sunday": "я хотел бы билет в оба конца до Ньюкасла, с возвратом в воскресенье",
    "with kind regards,": "С добрыми пожеланиями,",
    "i'd like to renew my season ticket, please": "я хотел бы продлить сезонный билет, пожалуйста",
    "don't worry": "не волнуйся",
    "my car's been broken into": "мою машину вскрыли",
    "how?": "как?",
    "how many stops is it to Westminster?": "сколько остановок до Вестминстера?",
    "i speak a little English": "я немного говорю по-английски",
    "be careful!": "будьте осторожны!",
    "can I get you anything to drink?": "хочешь что-нибудь выпить?, хотите что-нибудь выпить?",
    "call the fire brigade!": "вызовите пожарных!",
    "expected": "Прибывает",
    "could I have a receipt, please?": "могу я получит чек, пожалуйста?",
    "what a pity!": "как жаль!",
    "do you take sugar?": "сколько положить сахара?",
    "yes, I've got": "да, у меня есть …",
    "i've lost my": "я потерял …",
    "i'm really sorry": "прошу прощения",
    "in the afternoon": "днем",
    "stop, thief!": "остановите вора!",
    "what's going on?": "что происходит?",
    "sorry, there are none available at the moment": "извините, сейчас свободных такси нет",
    "it doesn't matter": "это не важно",
    "who?": "кто?",
    "long time, no see!": "давно не виделись!",
    "on time": "Вовремя",
    "trains to London": "Поезда на Лондон",
    "i'd like a single to Bristol": "я хотел бы билет в один конец до Бристоля",
    "sorry?": "простите?",
    "occupied": "Занято",
    "where would you like to go?": "куда бы вы хотели поехать?",
    "this evening": "сегодня вечером",
    "happy New Year!": "с Новым Годом!",
    "i'd like a return to Bristol": "я хотел бы билет в оба конца до Бристоля",
    "yes, I've got a brother": "да, у меня есть брат",
    "where do your parents live?": "где живут твои родители?",
    "how much will it cost?": "сколько это будет стоить?",
    "this year": "в этом году",
    "where do I change for exeter?": "где мне надо сделать пересадку на Эксетер?",
    "glad to hear it": "рад это слышать",
    "for one day": "на один день",
    "how long will the journey take?": "сколько туда ехать?",
    "just kidding!": "шутка!",
    "thank you": "спасибо",
    "out of order": "Не работает",
    "thanks very much": "большое спасибо",
    "welcome to": "добро пожаловать в …",
    "sorry": "извините",
    "i would be grateful if you could attend to this matter as soon as possible.": "Пожалуйста отреагируйте на это как можно быстрее.",
    "i'm sorry, she's not in at the moment": "извините, она отсутствует",
    "i'm sorry, he's not available at the moment": "извините, он сейчас занят",
    "where are you calling from?": "откуда вы звоните?",
    "yours sincerely,": "Искренне Ваш,",
    "what company are you calling from?": "из какой компании вы звоните?",
    "i'm sorry, he's": "извините, он",
    "i'm sorry, she's on another call": "извините, она говорит по другому телефону",
    "call the police!": "вызовите полицию!",
    "how much?": "сколько?",
    "go away!": "уйдите!",
    "me too": "я(мне) тоже",
    "exit": "Выход",
    "yours faithfully,": "Искренне Ваш,",
    "would you like a gin and tonic?": "хочешь джин с тоником?",
    "could you please stop at the airport?": "остановитесь, пожалуйста, в аэропорту",
    "merry Christmas!": "счастливого Рождества!",
    "i've locked myself out of my room": "моя комната закрылась, а ключи внутри",
    "you're looking well": "ты прекрасно выглядишь, вы прекрасно выглядите",
    "i'd like an Oyster card, please": "я хотел бы карту «Ойстер», пожалуйста (карта с предоплатой для путешествия на общественном транспорте в Лондоне)",
    "i know": "я знаю",
    "i'm hungry": "я хочу есть",
    "could I ask who's calling?": "могу я узнать, кто звонит?",
    "this train terminates here": "этот поезд дальше не идёт",
    "where are the lights?": "где включаются фары?",
    "are you single?": "ты холостой?, ты незамужняя?",
    "john speaking": "говорит Джон",
    "let's go into the living room": "давай(те) пойдем в гостиную",
    "could I speak to Bill, please?": "могу я поговорить с Билом, пожалуйста?",
    "i agree": "я согласен (согласна)",
    "northbound platform": "Платформа северного направления",
    "yes, I've got a sister": "да, у меня есть сестра",
    "i disagree": "я не согласен (согласна)",
    "i'll be there in ten minutes": "я буду там через десять минут",
    "how much does it cost?": "сколько это стоит?",
    "does this bus stop at Trafalgar Square?": "останавливается ли этот автобус в Трафальгарской площади?",
    "i don't speak English": "я не говорю по-английски",
    "steady on!": "осторожнее!",
    "tickets, please": "билеты, пожалуйста",
    "we are now approaching London Kings Cross": "мы прибываем на станцию Кингс-кросс",
    "dear Mr Smith,": "Дорогой мистер Смит,",
    "do you understand?": "ты понимаешь?",
    "if you would like any further information, please don't hesitate to contact me.": "Если Вы заинтересованы в получении дополнительной информации, пожалуйста свяжитесь со мной.",
    "i'm separated": "я живу отдельно",
    "i think so": "думаю, что так",
    "which zones?": "в какие зоны?",
    "i like her": "мне нравится она",
    "does this train stop at?": "останавливается ли этот поезд в …?",
    "sorry to keep you waiting": "прошу прощения за задержку",
    "nowhere": "нигде",
    "did you find us alright?": "ты нашел нас без проблем?, вы нашли нас без проблем?",
    "best regards,": "С наилучшими пожеланиями,",
    "how often do the buses run to?": "как часто ходят автобусы на …?",
    "when will you be coming back?": "когда вы хотели бы вернуться?",
    "thanks": "спасибо",
    "let's speak in": "давайте поговорим …",
    "i hope so": "надеюсь",
    "where did you learn your English?": "где ты выучил английский?",
    "all change, please": "всем пересесть, пожалуйста",
    "do you speak English?": "вы говорите по-английски?",
    "quarter of an hour": "четверть часа",
    "how much is it?": "сколько с меня?",
    "yes, I've got a boy and a girl": "да, у меня мальчик и девочка",
    "could you please stop at?": "остановитесь, пожалуйста, в …",
    "see you!": "увидимся!",
    "take your time": "не торопись",
    "last night": "вчера вечером",
    "you have to bring it back with a full tank": "вы должны вернуть её с полным баком",
    "when would you like to travel?": "когда вы хотели бы выехать?",
    "that's OK": "все в порядке",
    "how many sugars do you take?": "сколько положить сахара?",
    "what's this?": "что это здесь?",
    "southbound platform": "Платформа южного направления",
    "could you take me to?": "не могли бы вы отвезти меня в …?",
    "how do you open the petrol tank?": "как открывается топливный бак?",
    "this month": "в этом месяце",
    "good evening": "добрый вечер (используется после 6 часов вечера)",
    "i'm tired": "я устал",
    "five minutes ago": "пять минут назад",
    "which line do I need for Camden Town?": "на какой линии находится Камден-таун?",
    "i've been mugged": "меня ограбили",
    "i'll call you later": "я позвоню тебе позже",
    "hi": "привет (дружеское)",
    "dear Ms Shepherd,": "Дорогая госпожа Шепард",
    "are you ready to eat now?": "ты готов есть?, вы готовы есть?",
    "tickets": "Билеты",
    "hang on a minute": "подожди минутку",
    "maybe": "может быть",
    "how many?": "сколько?",
    "it's not worth it": "это того не стоит",
    "wc": "Туалет",
    "here": "здесь (тут)",
    "i'd like a senior citizens' single to Bristol": "я хотел бы пенсионерский билет в один конец до Бристоля",
    "i'd like to go to": "я хотел бы поехать …",
    "it's not important": "это не важно",
    "dear Sir or Madam,": "Дорогой Господин или дорогая Госпожа,",
    "i'm afraid that": "я боюсь, что...",
    "for how many days?": "на сколько дней?",
    "has this car got a CD player?": "в машине есть проигрыватель компакт-дисков?",
    "let's go into the dining room": "давай(те) пойдем в столовую",
    "emergency exit": "Запасной выход",
    "i've lost my ticket": "я потерял билет",
    "i'm a widow": "я вдова",
    "sorry we're late": "извини, мы опоздали",
    "seat": "Место",
    "the next train to depart from Platform 5 will be the 18.03 service to Penzance": "следующий поезд, отправляющийся с пятой платформы, это рейс в 18:03 на Пензанс",
    "could I put this in the hold, please?": "могу я положить это в багаж, пожалуйста?",

}