slovar = {
    "We are fond of classical music": "",
    "My aunt is fond of growing flowers": "",
    "I am not fond of knitting": "",
    "She is fond of playing the guitar": "",
    "Marcus isn't interested in flowers": "",
    "I doubt he's interested in politics": "",
    "They are interested in becoming cooks": "",
    "I think you are hungry after your journey": "",
    "When he is hungry, he is grumpy": "",
    "It is crazy about skiing": "",
    "My brother is crazy about parachuting": "",
    "My grandmother is crazy about her cats": "",
    "Why are you afraid of dogs?": "",
    "She is afraid of writing tests": "",
    "My son is afraid of dentists": "",
    "Are you afraid of scary films?": "",
    "He is jealous of her talent": "",
    "They are jealous of our happiness": "",
    "One of my colleagues is sick": "",
    "What's wrong? Are you sick?": "",
    "I am good at organizing parties": "",
    "My friend is good at making furniture": "",
    "She is rally bad at explaining mathematics": "",
    "Her son is bad at studying": "",
    "This answer is wrong": "",
    "I am sorry, but you are wrong": "",
    "Is anything wrong": "",
    "Yes, mom, you are absolutely right": "",
    "I guess she is right": "",
    "The driver is responsible for the safety of the passengers": "",
    "Who is responsible for this? Anyway I am responsible for you": "",
    "There are many trees in the garden": "",
    "There are a lot of parks and squares here": "",
    "There are a few people in the room": "",
    "There are very few flowers on the flowerbed": "",
    "There are plenty of mistakes in the test": "",
    "There is a great number of rocks in the mountains": "",
    "There are some students in the hall": "",
    "There aren't any pictures in the book": "",
    "There isn't much litter in the street": "",
    "There is a lot of noise in the classroom": "",
    "There is a little milk in the glass": "",
    "There is very little sugar in the cake": "",
    "There is plenty of fruit in the shop": "",
    "There is a large amount of money in a bank": "",
    "There is some tea in the glass": "",
    "There isn't any cream in the coffee": "",
    "What number of students is there in your group?": "",
    "What amount of milk is there in the cup?": "",
    "jack is at home today. He is sitting on the sofa now. He is watching TV": "",
    "She is unhappy now. She is reading the letter. There is something wrong with her cousin": "",
    "They are in the swimming pool at the moment. They are swimming and enjoying it": "",
    "It is raining now. People are wearing raincoats": "",
    "He is repairing his car this week. He is very busy": "",
    "My brother is building a house at the moment": "",
    "They are changing their old furniture this week. They are buying some new": "",
    "She is ill. She is lying in bed. She is taking some medicine": "",
    "I go to teh cinema every Saturday": "",
    "She always cooks very well": "",
    "We usually have dinner at 7 p.m": "",
    "He drives a car very well": "",
    "Helen rarely watches TV in the morning": "",
    "I live in Madrid. My sister lives in Rome": "",
    "He eats meat. His friends eat fruit and vegetables": "",
    "It snows a lot in winter": "",
    "Diana has breakfast at 8 o'clock every day": "",
    "My friend has a holiday in the mountains every year": "",
    "I like my job": "",
    "The supermarkets open at 8 o'clock and close at 8:30": "",
    "Sandra walks to school every day. She leaves her house at 7:30 and comes back home": "",
    "at 2 o'clock in the afternoon": "",
    "The Earth goes round the Sun": "",
    "We do the shopping every week": "",
    "It costs a lot of money to eat at the new Italian restaurant": "",
    "It rains a lot summer here": "",
    "They usually meet at a cafe": "",
    "Mary always phones her parents": "",
    "I usually go to work by bike but sometimes I walk": "",
    "Tom never buys expensive clothes": "",
    "My brother lives near us. We often visit him": "",
    "She occasionally drinks coffee": "",
    "They seldom speak Arabic": "",
    "I work": "",
    "Do you work?": "",
    "Yes, I do": "",
    "No, I don't": "",
    "We read": "",
    "Do we read?": "",
    "Yes, we do": "",
    "No, we don't": "",
    "They speak": "",
    "Do they speak?": "",
    "Yes, they do": "",
    "No, they don't": "",
    "You cook": "",
    "Do you cook?": "",
    "Yes, I do": "",
    "No, I don't": "",
    "He smokes": "",
    "Does he smoke?": "",
    "Yes, he does": "",
    "No, he doesn't ": "",
    "She studies": "",
    "Does she study?": "",
    "Yes, she does": "",
    "No, she doesn't": "",
    "Who cooks dinner at home every day?": "",
    "He cooks dinner every day": "",
    "What does he do?": "",
    "He cooks": "",
    "What does he cook?": "",
    "He cooks dinner": "",
    "Where does he cook?": "",
    "He cooks at home": "",
    "When does he cook?": "",
    "He cooks every day": "",
    "Do you always get up early?": "",
    "Does Mary often go to a dentist?": "",
    "What do they usually do in the evenings?": "",
    "What do you do?": "",
    "I work in a supermarket": "",
    "Do you like chocolate?": "",
    "Yes, I do": "",
    "Do your parents speak English?": "",
    "No, they don't": "",
    "You can turn off the television. I'm not watching It": "",
    "I'm riding a bike to get work because my car is broken": "",
    "They are not talking to each other after the last argument": "",
    "Mary is working at McDonald's": "",
    "They are working hard to earn money": "",
    "Mike is studying hard to become a doctor": "",
    "I don't watch television very often": "",
    "He drives to another city evey day": "",
    "My mother sews patients in hospitals": "",
    "Nurses look after patients in hospitals": "",
    "Snow melts at 0 degrees": "",
    "Every twelve months, the Earth circles Sun": "",
    "The sun rises in the east": "",
    "My mother works in a factory. This week she isn't working": "",
    "The kids usually sleep at this time, but now they aren't sleeping": "",
    "I want to study abroad so I'm learning English now": "",
    "I usually wear makeup when I go to work, but I'm not wearing any make up now because I'm working at home today": "",
    "I think we should leave immediately": "",
    "He's thinking hard over the problem": "",
    "They have a lot of plants in the garden": "",
    "They are having a rest this month": "",
    "I have a brother": "",
    "I have got a brother": "",
    "I've got a brother": "",
    "I don't have a brother": "",
    "I have not got a brother": "",
    "I haven't got a brother": "",
    "You have a sister": "",
    "You have got a sister": "",
    "You've got a sister": "",
    "You don't have a sister": "",
    "You haven't got a sister": "",
    "I've not got a sister": "",
    "He has a cat": "",
    "He has got a cat": "",
    "He's got a cat": "",
    "He doesn't have a cat": "",
    "He has not got a cat": "",
    "He hasn't got a cat": "",
    "She has a dog": "",
    "She has got a dog": "",
    "She's got a dog": "",
    "She doesn't have a dog": "",
    "She has not got a dog": "",
    "She's not got a dog": "",
    "It has Bluetooth": "",
    "It has got Bluetooth": "",
    "It's got Bluetooth": "",
    "It doesn't have Bluetooth": "",
    "It has not got Bluetooth": "",
    "It hasn't got Bluetooth": "",
    "We have books": "",
    "We have got books": "",
    "We've got books": "",
    "We don't have books": "",
    "We have not got books": "",
    "We haven't got books": "",
    "They have pets": "",
    "They have got pets": "",
    "They've got pets": "",
    "They don't have pets": "",
    "They haven't got pets": "",
    "They've not got pets": "",
    "Do i have any rights?": "",
    "Yes, I do": "",
    "Have I got any rights?": "",
    "Yes, I have": "",
    "Do you have any small pets?": "",
    "Yes, you do": "",
    "No, I don't": "",
    "No, I haven't": "",
    "No, you don't": "",
    "Have you got any pets?": "",
    "Yes, you have": "",
    "No, you haven't": "",
    "Does he have a computer?": "",
    "Yes, he does": "",
    "No, he doesn't": "",
    "Has he got a computer?": "",
    "Yes, he has": "",
    "No, he hasn't": "",
    "Does it have WhatsApp?": "",
    "Yes, it does": "",
    "No, it doesn't": "",
    "Has it got WhatsApp?": "",
    "Yes, it has": "",
    "No, it hasn't": "",
    "Do we have fresh ketchup?": "",
    "Yes, we do": "",
    "No, we don't": "",
    "Have we got fresh ketchup?": "",
    "Yes, we have": "",
    "No, we haven't": "",
    "Do they have nice friends?": "",
    "Yes, they do": "",
    "No, they don't": "",
    "Have they got nice teachers?": "",
    "Yes, they have": "",
    "No, they haven't": "",
    "She was sad yesterday. She is happy today": "",
    "I was at the cinema last week": "",
    "She was tired last night": "",
    "We were very busy last week": "",
    "He was at the football match last Friday": "",
    "Was she ill last Saturday?": "",
    "Yes, she was": "",
    "Were your kids with you last holiday?": "",
    "No, they weren't": "",
    "Where were at the last night": "",
    "They were at the disco": "",
    "When was he at the conference?": "",
    "He was there in February": "",
    "Why was she so happy yesterday?": "",
    "Who was in the park last Sunday?": "",
    "Was he tired last night? Yes, he was": "",
    "Were they with you at the disco last Friday?": "",
    "No, they weren't": "",
    "Was your at the conference last year?": "",
    "No, I wasn't": "",
    "I was ill last week": "",
    "She was late yesterday": "",
    "They weren't happy with my clothes yesterday": "",
    "Where were you last week?": "",
    "Why was she sad yesterday?": "",
    "Why were you angry with me yesterday?": "",
    "He was worried about his job last week": "",
    "When I was a child I was interested in cartoons": "",
    "I was disappointed with my friend's behavior at the last party": "",
    "She worked on her computer yesterday": "",
    "We played football last week": "",
    "They cooked lamb chops last Friday": "",
    "He repaired his car yesterday": "",
    "When I was a child, I played baseball": "",
    "She painted the house last month": "",
    "I talked to him about my work a few days ago": "",
    "My brother changed his car last week": "",
    "I studied French five years ago": "",
    "The lesson began ten minutes ago": "",
    "They ran in the stadium yesterday": "",
    "We flew to Los-Angeles last year": "",
    "She came home, took off her coat and her shoes and prepared dinner": "",
    "He got up at seven o'clock in the morning yesterday": "",
    "Helen bought a new car last week": "",
    "I saw him yesterday": "",
    "Who swept the floor yesterday?": "",
    "What did she do yesterday?": "",
    "What did she sweep?": "",
    "Where did she sweep?": "",
    "When did she sweep?": "",
    "She swept": "",
    "She swept the floor": "",
    "She swept in her room": "",
    "She swept yesterday": "",
    "Did she go to the cinema yesterday?": "",
    "Did your friends visit you last week?": "",
    "Did they play football last month?": "",
    "Did you work last Saturday?": "",
    "He went to the cinema last night": "",
    "Did he go to the film last night": "",
    "He watched the film last night": "",
    "Did he watch the film yesterday?": "",
    "Did he go to the cinema?": "",
    "Who wrote the letter Yesterday?": "",
    "Who drank coffee last night?": "",
    "Who cooked salad last weekend?": "",
    "Who played baseball last week?": "",
    "When did he come home?": "",
    "What did they read last night?": "",
    "How did it happen?": "",
    "When did he write to her?": "",
    "Where did you work last year?": "",
    "They didn't to the circus last week": "",
    "She didn't cook yesterday": "",
    "My brother didn't read the letter last night": "",
    "We didn't see him when we were on holiday": "",
    "He didn't take part in the meeting yesterday": "",
    "They were having breakfast at 8:30 a.m yesterday": "",
    "She was cooking the dinner this time yesterday": "",
    "When I saw him, he was walking in the park": "",
    "While Nelly was washing up, her husband was repairing his car": "",
    "When I came, my brother was plying": "",
    "It was raining all night yesterday": "",
    "She cut her finger while she was cooking": "",
    "She came when we were having lunch": "",
    "They met him while they were walking in the park": "",
    "I was standing near the window and was looking at the street. It was snowing and a strong wind wind was blowing": "",
    "I am reading (now)": "",
    "It isn't snowing (now)": "",
    "I was reading at 9 o'clock": "",
    "It was snowing when I went out": "",
    "At 3 o'clock yesterday afternoon I was reading a book": "",
    "I started reading 2 o'clock": "",
    "I was reading a book 3 o'clock": "",
    "I finished reading 4 o'clock": "",
    "When we went out, it was raining": "",
    "It started raining": "",
    "When we went out": "",
    "It stopped raining": "",
    "It was raining": "",
    "Yesterday morning I got up very late. I go dressed very quickly and left home without having breakfast": "",
    "I got up": "",
    "I got dressed": "",
    "I left home": "",
    "When I arrived at the airport, my friend was waiting for me": "",
    "When I arrived at the airport, I look a taxi from the airport to the hotel in the city centre": "",
    "We were having lunch, when james came": "",
    "When james came, we went to the cinema": "",
    "While I was reading a book, my sister was doing her homework": "",
    "I read a book and helped my sister to do her homework": "",
    "We were playing basketball when it started raining": "",
    "When we finished playing basketball, it started raining": "",
    "Margaret was working at her desk when Tom came into the office": "",
    "When Tom came, everybody stopped working and looked at him": "",
    "When I came into the room Tom was sitting in the armchair. He had a book in his hand but he wasn't reading it. He was watching TV": "",
    "Tom bought a book yesterday but he didn't read it, he didn't have time": "",
    "I have bought a new car(we have a new car now). Do you want to see it?": "",
    "Have you seen my wallet anywhere? I've lost it(I can't find it now)": "",
    "Where is James? He has gone out(he isn't at home now)": "",
    "My father has started a new job": "",
    "It's Sarah's birthday tomorrow and I haven't bought her a present": "",
    "Can I take this magazine? Have you finished with it?": "",
    "Where is your key? I don't know. I have lost it": "",
    "I can't find my pen. Have you seen it?": "",
    "Ann is on holiday. Is she? Where has she gone?": "",
    "She told me her name but I have forgotten it": "",
    "Where is your new umbrella? I have left it": "",
    "Fred's face is angry. He has got a bad mark on his English test": "",
    "The cat's muzzle is satisfied. He has caught a mouse": "",
    "I can't play with my friends this evening. I haven't finished my homework": "",
    "Look! The tree has fallen across the road!": "",
    "You have made some mistakes in this text": "",
    "Does she know that song? - Yes, she has learnt it": "",
    "Is mum at home? - No, she hasn't come": "",
    "I am still writing exercise. I haven't finished it": "",
    "Is David here?": "",
    "Yes, he has just arrived": "",
    "Are you hungry?": "",
    "No, I've just had lunch": "",
    "Are you reading a book now?": "",
    "What time is Kate coming?": "",
    "She has already come": "",
    "It is 10 o'clock now": "",
    "All the children have already gone to bed": "",
    "Do you know the song?": "",
    "Yes, I have already heard it": "",
    "John hasn't arrived yet": "",
    "I haven't done my work yet": "",
    "He hasn't called me yet": "",
    "She hasn't written me yet": "",
    "I haven't told him yet": "",
    "They haven't finished University yet": "",
    "Have you finished your article yet?": "",
    "NO, I have just begun to write it": "",
    "Has Mary started her new job yet?": "",
    "Yes, she has": "",
    "Have you finished cooking yet?": "",
    "No, I haven't": "",
    "Have they bought a house yet?": "",
    "No, they haven't earned enough money yet": "",
    "Has Tom passed his exam yet?": "",
    "Yes, he has": "",
    "Has he finished his work yet?": "",
    "Yes, and he has already left home": "",
    "Have they discussed the problem yet?": "",
    "No, they haven't stated discussing it yet": "",
    "Has she made the tea yet?": "",
    "Yes, she has already poured it into the cups": "",
    "Have you ever been to Europe?": "",
    "Yes, I have been there many times": "",
    "Have you ever been to Canada?": "",
    "No, I have never been to Canada": "",
    "We have been to London but we haven't been to Paris": "",
    "Sue has travelled a lot. She has been to many countries in the world. She has stayed at hotels, She has seen a lot of interesting places. She has met a lot of different people": "",
    "I have seen that many times but I have never spoken to him": "",
    "How many times has Germany won the World Cup?": "",
    "Has Portugal won the World Cup?": "",
    "Has he read this book?": "",
    "Yes, he has": "",
    "Have you ever travelled by train?": "",
    "No I haven't. I have never travelled by train": "",
    "Have you ever played football?": "",
    "Yes, I often play football": "",
    "Has she ever been late for work?": "",
    "Yes, She has been late several times": "",
    "My mother has never driven a car": "",
    "Who is that woman?": "",
    "I don't know. I have never met her before": "",
    "Have you ever used this kind of computer?": "",
    "No, I haven't": "",
    "I have never liked pop music, I prefer jazz": "",
    "Have you ever slept outside?": "",
    "Exams have never worried me": "",
    "I have never been abroad": "",
    "Have you ever gone skiing?": "",
    "Have you ever milked a cow?": "",
    "Has he ever lived in a tent?": "",
    "He isn't at the office at the moment. He has gone away to London on business": "",
    "He has just come back from London. He has been there on business": "",
    "I am looking for Helen. Where has she gone?": "",
    "Hello, Helen! I haven't seen you for a long time. Where have you been to?": "",
    "He has gone to the bank. He has decided to takes some money to develop the business": "",
    "Paul isn't in New-York any more. He has gone on a journey to Thailand": "",
    "She started working on the computer 20 minutes ago. She is working now. She has been working for 20 minutes": "",
    "He started driving a car when he was 20. He is 35 years old now. He drives a car very well": "",
    "He has been driving a car for fifteen years": "",
    "He started playing baseball when he was 10 years old. He plays very well. He has been playing since he was 10.": "",
    "She started playing golf an hour ago. She is playing now. She has been playing for an hour": "",
    "The children sleeping. They have been sleeping for two hours": "",
    "He speaks English. He has been speaking English since he was 12": "",
    "It is raining. It started to rain in the morning. It is evening now. It has been raining all day": "",
    "She is having lunch now. She has been having lunch since 12 o'clock afternoon": "",
    "Peter likes playing baseball. He has been playing since he was 11 years old": "",
    "I am making dinner. How long have you been cooking? I have been cooking some soup and some salad for twenty minutes": "",
    "Tracy is in the living room. She is speaking on the phone. She has been speaking to her friend for a few minutes": "",
    "They are walking in the park. They started walking 20 minutes ago. They have been walking for 20 minutes": "",
    "Mr.Parker is in the garage. He is washing his car. He started two hours ago. He has been washing his car for two hours": "",
    "They are having dinner now(at the time of speaking)": "",
    "They have been having dinner for 10 minutes(for a period)": "",
    "Mother is cooking now(at the time of speaking)": "",
    "Mother has been cooking since 2 o'clock(for a period)": "",
    "I am in the classroom now. I came five minutes ago. I have been in the classroom for 5 minutes": "",
    "She is ill. She got ill a few days ago. She has been ill for a few days": "",
    "He is happy. He has been happy since yesterday": "",
    "She has got a car. She bought the car five years ago. She has had the car for five years": "",
    "We have got a wonderful house by the sea. We bought the house last summer. We have had the house since last summer": "",
    "I know Margaret. I have known her since we were at school": "",
    "She knows him very well. They studied at school together. She has known him for a long time": "",
    "How long have you been ill? I have been ill since last week": "",
    "How long have you had this bag? I have had it for a few days": "",
    "How long have you known her? I have known her since I was at school": "",
    "They are on holiday. They have been on holiday since last week": "",
    "She is married. She has been married for two years": "",
    "He is at work now. He left home for work at 8 o'clock. He has been at work since 8 o'clock": "",
    "I have been to Canada(it's my experience)": "",
    "I have been in Canada for three days(i'm in Canada at the moment)": "",
    "She has been to the bank(she is not in the bank now)": "",
    "She has been in the bank for 20 minutes(she is in the bank now)": "",
    "She has been living or(she has lived) here for five years": "",
    "He has been working or(he has worked) in a bank since last year": "",
    "They live in London. They have lived in London all their lives": "",
    "Do your parents live in their old house? No, they haven't lived there for three years": "",
    "How long has she lived in this apartment? She has lived here all her life": "",
    "She has worked in the project since she finished University": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",
    # "": "",

}
