slovar = {
    "color = 'red'": "",
    "if": "",
    "==": "",
    "print('')": "",
    "elif": "",
    "else": "",
    "for i in range(1, 5):": "",
    "print(i, end=' ')": "",
    "while True:": "",
    "!=": "",
    "friend = ['Kevin', 'Karen', 'Jim']": "",
    "print()": "",
    "print(friend[0]": "",
    "print(friend[1:]": "",
    "friend[1] = 'Make'": "",
    ".extend('')": "",
    ".append('')": "",
    ".insert(1, 'Kelly'": "",
    ".remove('Jim')": "",
    ".clear()": "",
    ".pop()": "",
    ".index('Kevin')": "",
    ".count('Jim')": "",
    ".sort()": "",
    ".copy()": "",
    "coordinates = (4, 5)": "",
    "def say_hi():": "",
    "def say_hi(name, age)": "",
    "str()": "",
    "return": "",
    "or": "",
    "and": "",
    "not()": "",
    "elif is_male and not(is_male)": "",
    "def": "",
    ">=": "",
    "<=": "",
    ">": "",
    "<": "",
    "input()": "",
    "input('')": "",
    "float": "",
    ".get('')": "",
    "while": "",
    "+=": "",
    "False": "",
    "True": "",
    "in": "",
    "for": "",
    "range()": "",
    "len()": "",
    "CharField": "",
    "TextField": "",
    "__str__": "",
    "self": "",
    "model": "",
    "migrate": "",
    "createsuperuser": "",
    "register": "",
    "from": "",
    "rest_framework": "",
    "decorators": "",
    "import": "",
    "api_view": "",
    "response": "",
    "Response": "",
    "request": "",
    "@api_view(['GET','POST'])": "",
    "integer": "",
    "string": "",
    "boolean": "",
    "list": "",
    "urlpatterns": "",
    "django": "",
    "admin": "",
    "urls": "",
    "path": "",
    "contrib": "",
    "site": "",
    "api/v1/": "",
    "views": "",
    "max_length": "",
    "null=True": "",
    "blank=True": "",
    "FloatField": "",
    "DateTimeField": "",
    "auto_now_add=True": "",
    "auto_now=True": "",
    "serializers": "",
    "pip install django": "",
    "django-admin startproject ...": "",
    "python manage.py runserver": "",
    "python manage.py migrate": "",
    "python manage.py startapp ...": "",
    "default=True": "",
    "on_delete=models": "",
    "BooleanField": "",
    "ForeignKey": "",
    "db_index=True": "",
    "python manage.py makemigrations": "",
    "python manage.py createsuperuser": "",
    "pip install djangorestframework": "",
    "generics": "",
    "queryset": "",
    "objects": "",
    "ModelSerializers": "",
    "Meta": "",
    "fields": "",
    "APIView": "",
    "ListAPIView": "",
    "get": "",
    "values()": "",
    "create()": "",
    "data[]": "",
    "post()": "",
    "model_to_dict()": "",
    "__init__": "",
    "encode()": "",
    "model_sr.data": "",
    "type": "",
    "JSONRenderer": "",
    "render": "",
    "python manage.py shell": "",
    "io.ByresIo": "",
    "JSONParser()": "",
    "pars(stream)": "",
    "serializer.is_valid()": "",
    "quit": "",
    "many=True": "",
    "read_only": "",
    "save()": "",
    "put": "",
    "*args": "",
    "class": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

}