slovar = {
    "threaten": "угрожать",
    "occupied": "занятый",
    "species": "разновидность",
    "landscape": "пейзаж",
    "cruel": "жестокий",
    "harmless": "безобидный",
    "disappoint": "разочаровывать",
    "secluded": "уединенный",
    "transmute": "превращать",
    "disobedient": "непослушный",
    "advantages": "преимущества",
    "wraith": "призрак",
    "wealth": "богатство",
    "pervert": "извращать",
    "warpath": "тропа войны",
    "dialling": "набирать номер",
    "disguise": "маскировка",
    "distract": "отвлечь",
    "disturb": "беспокоить",
    "toddler": "малыш",
    "infant": "младенческий",
    "splendid": "великолепный",
    "great": "большой",
    "excellent": "отличный",
    "struggle": "бороться",
    "trout": "форель",
    "participant": "участник",
    "participate": "участвовать",
    "contest": "конкурс",
    "permanent": "постоянный",
    "whale": "кит",
    "purchase": "закупка",
    "bargain": "сделка",
    "prescription": "рецепт",
    "entrepreneur": "предприниматель",
    "condition": "условия",
    "miserable": "жалкий",
    "smoulder": "тлеть",
    "necessarily": "обязательно",
    "innocent": "невинный",
    "sue": "засудить",
    "scratch": "чесать",
    "beforehand": "заранее",
    "diligence": "усердие",
    "consistently": "последовательно",
    "determined": "решительный",
    "earnestness": "серьезность",
    "approval": "одобрение",
    "admire": "восхищаться",
    "acquaintance": "знакомый",
    "transparent": "прозрачный",
    "thorns": "шипы",
    "gross": "грубый",
    "bribe": "взятка",
    "bribery": "подкуп",
    "suspect": "подозреваемый",
    "witness": "свидетель",
    "twist": "поворот",
    "sketch": "обрисовать",
    "crime": "преступность",
    "smuggle": "вывезти",
    "rape": "изнасилование",
    "regrettably": "к сожалению",
    "convict": "осудить",
    "evidence": "доказательство",
    "proof": "улика",
    "prosecutor": "прокурор",
    "investigation": "расследование",
    "sentimental": "чувствительный",
    "rational": "рациональный",
    "sucker": "сосунок",
    "tyke": "малыш",
    "rescue": "выручать",
    "peacefully": "мирно",
    "ruining": "портить",
    "lug": "Тащить",
    "suddenly": "вдруг, внезапно",
    "rhinoceros": "носорогов",
    "escaped": "сбежавший",
    "enormous": "громадный",
    "punctured": "проколоть",
    "defined": "определённый",
    "concatenate": "соединять",
    "confirm": "подтверждать",
    "unresolved": "неразрешённый",
    "impetuous": "стремительный",
    "shameless": "бесстыжий",
    "faithful": "верный",
    "handshake": "рукопожатия",
    "quarrel": "ссориться",
    "ripe": "спелый",
    "immortal": "бессмертный",
    "sociable": "общительный",

    
    






}