slovar = {
    "Arctic fox": "песец 	",
    "asp": "гадюка, аспид 	",
    "aurochs": "зубр 	",
    "baboon": "бабуин, павиан, бабуин",
    "badger": "барсук",
    "bat": "летучая мышь 	",
    "beaver": "бобр ",
    "bee": "пчела 	",
    "beetle": "жук 	",
    "billy goat": "козё",
    "bison": "бизон ",
    "blackbird": "дроз",
    "boa": "удав",
    "boar": "боров 	",
    "budgie": "волнистый попугайчик ",
    "bug": "клоп 	",
    "bull": "бык 	",
    "butterfly": "бабочка 	",
    "buzzard": "канюк ",
    "calf": "теленок 	",
    "camel": "верблюд 	",
    "canary": "канарейка 	",
    "cat": "кошка,кот ",
    "caterpillar": "гусеница 	",
    "cavy": "морская свинка 	",
    "cayman": "кайман ",
    "chameleon": "хамелеон",
    "chamois": "серна",
    "cheetah": "гепард 	",
    "chicken": "курица, цыпленок 	",
    "chimpanzee": "шимпанзе 	",
    "chinchilla": "шиншилла ",
    "chipmunk": "бурундук",
    "cobra": "кобра 	",
    "cock": "петух",
    "cockroach": "тарака",
    "coon": "енот",
    "cougar": "пума",
    "coyote": "койот 	",
    "crane": "журавль",
    "crawfish": "рак 	",
    "crayfish": "рак 	",
    "crocodile": "крокодил",
    "cuckoo": "кукушка ",
    "deer": "олень",
    "desman": "выхухоль ",
    "dingo": "динго ",
    "dinosaur": "динозавр ",
    "dog": "собака",
    "dogfish": "морс",
    "donkey": "осёл",
    "duck": "утка",
    "duckbill": "утконос ",
    "duckling": "утенок ",
    "eagle": "орел 	",
    "echidna": "ехидна ",
    "elephant": "слон 	",
    "elk": "лось",
    "falcon": "сокол 	",
    "fallow-deer": "лань",
    "ferret": "хорёк",
    "flamingo": "фламинго ",
    "fox": "лисица ",
    "frog": "лягушка ",
    "gazelle": "газель",
    "gecko": "геккон",
    "gibbon": "гиббон",
    "giraffe": "жираф ",
    "glutton": "росомаха",
    "gnat": "комар, москит",
    "gnu": "гну",
    "goat": "коза, козел ",
    "goose": "гусь ",
    "gorilla": "горилла",
    "grass snake": "медянка, уж 	",
    "grasshopper": "кузнечик 	",
    "grizzly": "гризли ",
    "ground squirrel": "суслик",
    "guinea pig": "морская свинка",
    "hamster": "хомяк",
    "hare": "заяц",
    "hawk": "ястреб ",
    "he-goat": "козёл 	",
    "hedgehog": "ёж",
    "hen": "курица",
    "heron": "цапля ",
    "hog": "свинья",
    "hyena": "гиена ",
    "iguana": "игуана ",
    "jaguar": "ягуар",
    "kangaroo": "кенгуру 	",
    "kid": "козленок",
    "kitten": "котенок 	",
    "koala": "коала 	",
    "ladybird": "божья коровка ",
    "lama": "лама",
    "lamb": "ягненок",
    "lark": "жаворонок ",
    "least weasel": "ласка 	",
    "leech": "пиявка 	",
    "lemming": "лемминг",
    "lemur": "лемур",
    "leopard": "леопард",
    "lion": "лев",
    "lizard": "ящерица",
    "lobster": "лобстер, омар ",
    "lynx": "рысь",
    "macaque": "макака ",
    "magpie": "сорока ",
    "mallard": "кряква",
    "mammoth": "мамонт",
    "manatee": "ламантин",
    "mandrill": "мандрил 	",
    "marmoset": "мартышка ",
    "marmot": "сурок ",
    "marten": "куница ",
    "mole": "крот ",
    "mollusc": "моллюск ",
    "mongoose": "мангуст 	",
    "monitor lizard": "варан",
    "monkey": "обезьяна",
    "moose": "амер. лось ",
    "moth": "моль",
    "mouse": "мышь ",
    "muskrat": "выхухоль, ондатра 	",
    "musquash": "ондатра 	",
    "nanny goat": "коза",
    "narwhal": "нарвал 	",
    "nightingale": "соловей 	",
    "nutria, coypu": "нутрия",
    "octopus": "осьминог ",
    "okapi": "окапи ",
    "opossum": "опоссум",
    "ostrich": "страус ",
    "otter": "выдра",
    "owl": "сова 	",
    "ox": "вол, бык 	",
    "panther": "пантера 	",
    "partridge": "куропатка ",
    "peacock": "павлин",
    "penguin": "пингвин ",
    "pheasant": "фазан 	",
    "pig": "свинья, поросенок 	",
    "pigeon, dove": "голубь",
    "platypus": "утконос 	",
    "polar bear": "белый медведь",
    "polar fox": "песец ",
    "polecat": "хорёк ",
    "pony": "пони 	",
    "porcupine": "дикобраз ",
    "puma": "пума",
    "puppy": "щенок ",
    "rabbit": "кролик 	",
    "raccoon": "енот ",
    "ram": "баран",
    "rat": "крыса",
    "raven": "ворон 	",
    "rhea": "нанду",
    "rhino": "носорог",
    "rocky lobster": "лангуст 	",
    "rooster": "петух ",
    "sable": "соболь",
    "saiga": "сайгак",
    "salamander": "саламандра",
    "scorpion": "скорпион 	",
    "seagull": "чайка ",
    "seal": "тюлень ",
    "serpent": "змея",
    "serval": "сервал",
    "shark": "акула ",
    "she-goat": "коза 	",
    "sheep": "баран,овца ",
    "skunk": "скунс 	",
    "sloth": "ленивец 	",
    "snail": "улитка 	",
    "snake": "змея 	",
    "snipe": "бекас 	",
    "snow leopard": "ирбис",
    "sparrow": "воробей",
    "sperm whale": "кашалот",
    "spider": "паук",
    "spiny lobster": "лангуст",
    "spurdog": "катран",
    "squirrel": "белка 	",
    "starfish": "морская звезда 	",
    "stork": "аист ",
    "suslik": "суслик ",
    "swallow": "ласточка",
    "swan": "лебедь",
    "swine": "свинья ",
    "tapir": "тапир",
    "tiger": "тигр 	",
    "titmouse": "синица",
    "toad": "жаба",
    "tomcat": "кот ",
    "tortoise": "черепаха",
    "tree frog": "квакша ",
    "turkey": "индейка, ",
    "turtledove": "горлица ",
    "viper": "гадюка 	",
    "vixen": "самка лисицы 	",
    "vulture": "гриф",
    "walrus": "морж ",
    "wasp": "оса",
    "wild boar": "кабан, дикий каб",
    "wild duck": "кряква",
    "wild ram": "архара",
    "wildebeest": "гну 	",
    "wolf": "волк ",
    "wolverine": "росомаха",
    "woodpecker": "дятел ",
    "worm": "червь ",
    "yak": "як",
    "zebra": "зебра",
    "hide": "прятать",
    "shine": "светить",
    "copy": "копировать",
    "grip": "схватить",
    "glow": "светиться",
    "impress": "производить впечатление",
    "inform": "уведомлять",
    "injure": "ушибить",
    "inject": "впрыскивать",
    "invite": "приглашать",
    "introduce": "представлять",
    "irritate": "возмущать",
    "joke": "шутить",
    "juggle": "обманывать",
    "kick": "пинать",
    "kiss": "целовать",
    "knot": "скреплять узлом",
    "label": "навешивать бирку",
    "license": "разрешать",
    "meddle": "интересоваться",
    "melt": "растворяться",
    "mend": "чинить",
    "muddle": "перемешивать",
    "arrive": "прибывать",
    "ascend": "восходить",
    "brake": "тормозить",
    "catch up": "догонять",
    "come across": "встречаться",
    "creep, crawl": "ползти",
    "depart, start, leave": "отправляться",
    "drown": "тонуть",
    "emerge": "всплывать",
    "float": "держаться на поверхности воды / не тонуть",
    "go (along)": "идти (вдоль)",
    "go in": "входить",

}
