slovar = {
    "Arctic fox": "песец 	",
    "asp": "гадюка, аспид 	",
    "aurochs": "зубр 	",
    "badger": "барсук",
    "beaver": "бобр ",
    "beetle": "жук 	",
    "blackbird": "дроз",
    "boa": "удав",
    "boar": "боров 	",
    "budgie": "волнистый попугайчик ",
    "bug": "клоп 	",
    "bull": "бык 	",
    "buzzard": "канюк ",
    "calf": "теленок 	",
    "canary": "канарейка 	",
    "caterpillar": "гусеница 	",
    "cavy": "морская свинка 	",
    "chamois": "серна",
    "cheetah": "гепард 	",
    "chinchilla": "шиншилла ",
    "chipmunk": "бурундук",
    "cock": "петух",
    "cockroach": "тарака",
    "coon": "енот",
    "cougar": "пума",
    "crane": "журавль",
    "crocodile": "крокодил",
    "cuckoo": "кукушка ",
    "desman": "выхухоль ",
    "duckling": "утенок ",
    "eagle": "орел 	",
    "elk": "лось",
    "fallow-deer": "лань",
    "ferret": "хорёк",
    "frog": "лягушка ",
    "giraffe": "жираф ",
    "glutton": "росомаха1",
    "gnat": "комар, москит",
    "goose": "гусь ",
    "grass snake": "медянка, уж 	",
    "grasshopper": "кузнечик 	",
    "grizzly": "гризли ",
    "ground squirrel": "суслик",
    "guinea pig": "морская свинка",
    "hamster": "хомяк",
    "hare": "заяц",
    "hawk": "ястреб ",
    "hedgehog": "ёж",
    "heron": "цапля ",
    "hog": "свинья",
    "hyena": "гиена ",
    "kangaroo": "кенгуру 	",
    "kid": "козленок",
    "kitten": "котенок 	",
    "ladybird": "божья коровка ",
    "lark": "жаворонок ",
    "least weasel": "ласка 	",
    "leech": "пиявка 	",
    "leopard": "леопард",
    "lizard": "ящерица",
    "lynx": "рысь",
    "macaque": "макака ",
    "magpie": "сорока ",
    "mallard": "кряква",
    "mammoth": "мамонт",
    "manatee": "ламантин",
    "mandrill": "мандрил 	",
    "marmoset": "мартышка ",
    "marmot": "сурок ",
    "marten": "куница ",
    "mole": "крот ",
    "mollusc": "моллюск ",
    "mongoose": "мангуст 	",
    "monitor lizard": "варан",
    "moose": "амер. лось ",
    "moth": "моль",
    "muskrat": "выхухоль, ондатра 	",
    "musquash": "ондатра 	",
    "narwhal": "нарвал 	",
    "nightingale": "соловей 	",
    "nutria, coypu": "нутрия",
    "opossum": "опоссум",
    "otter": "выдра",
    "ox": "вол, бык 	",
    "partridge": "куропатка ",
    "peacock": "павлин",
    "penguin": "пингвин ",
    "pheasant": "фазан 	",
    "pigeon, dove": "голубь",
    "platypus": "утконос 	",
    "polar bear": "белый медведь",
    "polar fox": "песец ",
    "polecat": "хорёк ",
    "porcupine": "дикобраз ",
    "rabbit": "кролик 	",
    "raccoon": "енот ",
    "ram": "баран",
    "raven": "ворон 	",
    "rhea": "нанду",
    "rhino": "носорог",
    "rocky lobster": "лангуст 	",
    "rooster": "петух ",
    "sable": "соболь",
    "saiga": "сайгак",
    "salamander": "саламандра",
    "scorpion": "скорпион 	",
    "seagull": "чайка ",
    "seal": "тюлень ",
    "serpent": "змея",
    "serval": "сервал",
    "shark": "акула ",
    "skunk": "скунс 	",
    "snail": "улитка 	",
    "snipe": "бекас 	",
    "sparrow": "воробей",
    "sperm whale": "кашалот",
    "spiny lobster": "лангуст",
    "spurdog": "катран",
    "squirrel": "белка 	",
    "starfish": "морская звезда 	",
    "stork": "аист ",
    "suslik": "суслик ",
    "swallow": "ласточка",
    "swan": "лебедь",
    "tapir": "тапир",
    "titmouse": "синица",
    "toad": "жаба",
    "tomcat": "кот ",
    "tortoise": "черепаха",
    "tree frog": "квакша ",
    "turtledove": "горлица ",
    "viper": "гадюка 	",
    "walrus": "морж ",
    "wasp": "оса",
    "wild boar": "кабан, дикий каб",
    "wild duck": "кряква",
    "wild ram": "архара",
    "wildebeest": "гну 	",
    "wolverine": "росомаха",
    "woodpecker": "дятел ",
    "grip": "схватить",
    "glow": "светиться",
    "impress": "производить впечатление",
    "injure": "ушибить",
    "inject": "впрыскивать",
    "invite": "приглашать",
    "irritate": "возмущать",
    "knot": "скреплять узлом",
    "label": "навешивать бирку",
    "license": "разрешать",
    "meddle": "интересоваться",
    "melt": "растворяться",
    "mend": "чинить",
    "muddle": "перемешивать",
    "arrive": "прибывать",
    "ascend": "восходить",
    "brake": "тормозить",
    "catch up": "догонять",
    "come across": "встречаться",
    "creep, crawl": "ползти",
    "depart, start, leave": "отправляться",
    "drown": "тонуть",
    "emerge": "всплывать",
    "float": "держаться на поверхности воды / не тонуть",
    "go (along)": "идти (вдоль)",

}
