slovar = {
    "consent": "согласие",
    "gnaw": "грызть",
    "withstand": "выдерживать",
    "mermaid": "русалка",
    # "insincere": "неискренний",
    "trinket": "брелок",
    # "mentor": "наставник",
    "bond": "связь",
    "purebred": "породистый",
    # "annoy": "раздражать",
    # "vivid": "яркий",
    # "define": "Определять",
    # "cheat": "обмануть",
    # "slouch": "сутулиться",
    # "special": "Особенный",
    "resist": "сопротивляться",
    "palaver": "лесть",
    # "yet": "еще",
    "seldom": "редко",
    # "anywise": "каким нибуд образом",
    # "altogether": "вполне",
    # "alike": "одинаково",
    "approximately": "приблизительно",
    "deliberately": "умышленно",
    # "frankly": "откровенно",
    "gradually": "понемногу",
    "instantly": "немедленно",
    "jointly": "вместе",
    "nevertheless": "тем не менее",
    "partly": "частично",
    "regardless": "невзирая ни на что",
    # "utterly": "чрезвычайно",
    # "clumsy": "неуклюжий",
    "comparison": "сравнение",
    "decry": "осуждать",
    "deferential": "почтительный",
    "demure": "скромный",
    "deride": "высмеивать",
    # "diligent": "прилежный",
    "disown": "отрекаться",
    "eloquent": "красноречивый",
    "empathy": "сочувствие",
    "enmity": "вражда",
    "fractious": "капризный",
    "furtive": "скрытый",
    "gluttony": "обжорство",
    "haughty": "высокомерный",
    "hypocrisy": "лицемерие",
    "impeccable": "безупречный",
    "impudent": "нахальный",
    # "improved": "улучшенный",
    # "revenge": "мстить",
    # "entertain": "развлекать",
    # "disagreement": "разногласие",
    # "broom": "метла",
    "appeasement": "умиротворение",
    # "doze": "дремать",
    "abyss": "пропасть",
    # "betray": "предавать",
    # "mad": "безумный",
    "fix": "чинить",
    "lifeguard": "спасатель",
    # "apologize": "извиняться",
    # "talkative": "болтливый",
    "affection": "привязанность",
    # "fang": "клык",
    "villain": "злодей",
    "pretend": "притворяться",
    "interrogate": "допрашивать",
    "devoted": "преданный",
    "adversary": "соперник",
    "amiable": "добродушный",
    # "rob": "грабить",
    # "upset": "расстраивать",
    "reflection": "отражение",
    "suffer": "страдать",
    # "ginger": "рыжий",
    "desperate": "отчаянный",
    # "ornament": "разрисовывать",
    # "queue": "очередь",
    # "protect": "защитить",
    "sneaky": "подлый",
    "unreliable": "ненадежный",
    "adhesive": "скотч",
    "tenderness": "нежность",
    # "socket": "розетка",
    # "unsafe": "небезопасный",
    "leisurely": "неторопливый",
    "vile": "мерзкий",
    "trap": "ловушка",
    "bounce": "прыжок",
    # "hassle": "стычка",
    "shaggy": "лохматый",
    "devotion": "преданность",
    # "cowardly": "трусливый",
    # "apron": "фартук",
    # "mysterious": "загадочный",
    # "readiness": "готовность",
    "grateful": "благодарный",
    "crooked": "кривой",
    # "giggle": "хихикать",
    "plump": "пухлый",
    # "flexible": "гибкий",
    # "lick": "облизывать",
    # "tune": "настраивать",
    "temptation": "соблазн",
    # "coin": "монета",
    "peaceable": "миролюбивый",
    "advise": "советовать",
    "torment": "мучить",
    "sacred": "священный",
    # "bark": "лаять",
    # "sticky": "липкий",
    # "overturn": "опрокидывать",
    "intricate": "запутанный",
    "resilient": "упругий",
    "crave": "жаждать",
    # "choke": "задыхаться",
    # "sensible": "разумный",
    # "loud": "громкий",
    # "bench": "скамейка",
    # "bartender": "бармен",
    "cuddle": "прижиматься",
    # "redhead": "рыжая",
    # "saucy": "дерзкий",
    "delay": "задержка",
    # "scheme": "замышлять",
    "drag": "тащить",
    "mock": "издеваться",
    # "cave": "пещера",
    "astonish": "удивлять",
    "indignant": "возмущенный",
    "foliage": "листва",
    "defend": "защищаться",
    # "cure": "лечить",
    # "enemy": "враг",
    # "fried": "жареный",
    # "peek": "заглядывать",
    "inseparable": "неразлучный",
    # "gifted": "одаренный",
    "psychic": "экстрасенс",
    # "pigeon": "голубь",
    "ponder": "обдумывать",
    "console": "утешать",
    "tender": "нежный",
    "persistent": "настойчивый",
    "repel": "отталкивать",
    # "gossip": "сплетничать",
    "uprising": "восстание",
    # "scent": "запах",
    # "icicle": "сосулька",
    "weary": "уставший",
    # "mannerly": "воспитанный",
    # "prepayment": "аванс",
    # "fate": "судьба",
    "traitor": "изменник",
    "sorrow": "печаль",
    # "brave": "храбрый",
    "wicked": "злой",
    # "aim": "целиться",
    # "touchy": "обидчивый",
    "stubborn": "упрямый",
    "frost": "мороз",
    # "explore": "исследовать",
    "goblet": "бокал",
    # "bitter": "горький",
    "fighter": "боец",
    "bachelor": "холостяк",
    "dread": "бояться",
    # "hook": "подцепить",
    # "shiny": "блестящий",
    # "dislike": "неприязнь",
    # "survivor": "выживший",
    # "compare": "сравнивать",
    # "sneeze": "чихать",
    "spooky": "жуткий",
    # "tail": "хвост",
    "terrific": " потрясающий",
    # "napkin": "салфетка",
    # "knock": "стучать",
    "bubble": "пузырь",
    # "blow": "дуть",
    "chase": "преследовать",
    "cherish": "лелеять",
    "graceful": "изящный",
    "recreation": "отдых",
    # "peck": "долбить",
    "diaphanous": "прозрачный",
    # "friendship": "дружба",
    "steam": "пар",
    "courageous": "мужественный",
    # "oath": " клятва",
    # "luxurious": "роскошный",
    "feeble": "слабый",
    "gazebo": "беседка",
    "fulfill": "выполнять",
    "artificial": "искусственный",
    # "comb": "расческа",
    "accidentally": "случайно",
    "hostage": "заложница",
    # "wise": "мудрый",
    "fastened": "привязанный",
    # "lake": "озеро",
    "splatter": "брызгать",
    # "tie": "галстук",
    "beware": "остерегаться",
    "squat": "приседать",
    "similarity": "сходство",
    "gesture": "жесть",
    "shore": "берег",
    # "iron": "гладить",
    # "blind": "слепой",
    # "quick": "быстрый",
    "naughty": "непослушный",
    "courage": "смелость",
    "purposeful": "целеустремленный",
    # "barefoot": "босиком",
    "fail": "терпеть неудачу",
    "hairdryer": "фен",
    "attractive": "привлекательный",
    "united": "объединенный",
    "inspiration": "вдохновение",
    # "cozy": "уютный",
    "survival": "выживание",
    "elope": "сбежать",
    "sail": "парус",
    # "skinny": "тощий",
    "imagination": "воображение",
    "responsive": "отзывчивый",
    # "jewel": "драгоцунность",
    "savour": "смаковать",
    "unattractive": "непривлекательный",
    # "hard": "жесткий",
    "lively": "оживленный",
    "glorious": "славный",
    # "celebrate": "праздновать",
    "chess": "шахматы",
    # "basket": "корзина",
    # "candy": "конфеты",
    "hasty": "поспешный",
    # "panic": "паниковать",
    "unbelievable": "невероятный",
    "porridge": "каша",
    "corn": "кукуруза",
    "gloves": "перчатки",
    "garbage": "мусор",
    "identical": "одинаковый",
    "envy": "зависть",
    "astound": "пороожать",
    "grain": "зерно",
    "inexplicable": "необъяснимый",
    "descend": "спускаться",

}