slovar = {
    "can you recommend a good pub near here?": "можете порекомендовать хороший паб неподолёку?",
    "do you fancy a pint?": "может выпьем пива? (дружеское)",
    "do you fancy a quick drink?": "может зайдём выпьем что-нибудь? (дружеское)",
    "shall we go for a drink?": "может пойдем выпьем?",
    "do you know any good places to …?": "ты знаешь какое-нибудь хорошее место, чтобы …?",
    "do you know any good places to eat?": "ты знаешь какое-нибудь хорошее место, чтобы поесть?",
    "do you know any good places to get a sandwich?": "ты знаешь какое-нибудь хорошее место, чтобы съесть бутерброд?",
    "do you know any good places to go for a drink?": "ты знаешь какое-нибудь хорошее место, чтобы выпить?",
    "shall we get a take-away?": "может закажем с собой?",
    "let's eat out tonight": "давай поедим где-нибудь сегодня вечером",
    "would you like to …?": "ты хотел бы …?",
    "would you like to come for a drink after work?": "ты хотел бы пойти выпить после работы?",
    "would you like to come for a coffee?": "ты хотел бы выпить кофе?",
    "would you like to join me for lunch?": "ты хотел бы пообедать со мной?",
    "would you like to join me for dinner?": "ты хотел бы поужинать со мной?",
    "Reserved": "Резервировано",
    "No smoking": "Не курить",
    "I'd like to check out": "я хотел бы выехать",
    "I'd like to pay my bill, please": "я хотел бы оплатить счёт, пожалуйста",
    "I think there's a mistake in this bill": "я думаю, что счёт неправильный",
    "how would you like to pay?": "как вы желаете платить?",
    "I'll pay …": "я заплачу …",
    "I'll pay by credit card": "я заплачу кредитной карточкой",
    "I'll pay in cash": "я заплачу наличными",
    "have you used the minibar?": "вы пользовались мини-баром?",
    "we haven't used the minibar": "мы не пользовались мини-баром",
    "could we have some help bringing our luggage down?": "помогите нам снести вниз багаж, пожалуйста",
    "do you have anywhere we could leave our luggage?": "мы могли бы где-то оставить багаж?",
    "could I have a receipt, please?": "могу я получить чек, пожалуйста",
    "I hope you had an enjoyable stay": "надеюсь, ваше пребывание было приятным",
    "I've really enjoyed my stay": "мое пребывание было очень приятным",
    "we've really enjoyed our stay": "наше пребывание было очень приятным",
    "my room number's …": "мой номер …",
    "my room number's 215": "мой номер 215",
    "could I have a wake-up call at seven o'clock?": "могли бы вы разбудить меня в семь часов?",
    "where do we have breakfast?": "где мы завтракаем?",
    "where's the restaurant?": "где находится ресторан?",
    "could you please call me a taxi?": "вызовите мне, пожалуйста, такси",
    "do you lock the front door at night?": "вы закрываете вход на ночь?",
    "if you come back after midnight, you'll need to ring the bell": "если вы вернётесь после полуночи, позвоните в дверь",
    "I'll be back around ten o'clock": "я вернусь около десяти часов",
    "could I see your key, please?": "покажите ваш ключ, пожалуйста",
    "are there any laundry facilities?": "тут можно постирать?",
    "what time do I need to check out?": "во сколько я должен выехать?",
    "would it be possible to have a late check-out?": "возможно ли выехать попозже?",
    "the key doesn't work": "ключ не работает",
    "there isn't any hot water": "нет горячей воды",
    "the room's too …": "в комнате слишком …",
    "the room's too hot": "в комнате слишком жарко",
    "the room's too cold": "в комнате слишком холодно",
    "the room's too noisy": "в комнате слишком шумно",
    "the … doesn't work": "… не работает",
    "the heating doesn't work": "отопление не работает",
    "the shower doesn't work": "душ не работает",
    "the television doesn't work": "телевизор не работает",
    "one of the lights isn't working": "одна лампа не работает",
    "there's no …": "там нет …",
    "there's no toilet paper": "там нет туалетной бумаги",
    "there's no soap": "там нет мыла",
    "there's no shampoo": "там нет шампуня",
    "could I have a towel, please?": "не могли бы вы дать мне полотенце,",
    "could I have an extra blanket?": "не могли бы вы дать мне дополнительное одеяло, пожалуйста?",
    "my room's not been made up": "моя комната не прибрана",
    "could you please change the sheets?": "поменяйте постельное бельё, пожалуйста",
    "I've lost my room key": "я потерял ключ от номера",
    "Do not disturb": "Не беспокоить",
    "Please make up room": "Пожалуйста, приберитесь в комнате",
    "Lift out of order": "Лифт не работает",
    "I've got a reservation": "у меня забронировано",
    "your name, please?": "ваше имя, пожалуйста",
    "my name's …": "мое имя …",
    "my name's Mark Smith": "мое имя Марк Смит",
    "could I see your passport?": "покажите паспорт, пожалуйста",
    "could you please fill in this registration form?": "заполните регистрационную карту, пожалуйста",
    "my booking was for a twin room": "я бронировал номер с двумя кроватями",
    "my booking was for a double room": "я бронировал двухместный номер (с одной кроватью)",
    "would you like a newspaper?": "желаете газету?",
    "would you like a wake-up call?": "желаете, чтобы мы вас разбудили?",
    "what time's breakfast?": "во сколько завтрак?",
    "breakfast's from 7am till 10am": "завтрак с 7 до 10 часов",
    "could I have breakfast in my room, please?": "могу я заказать завтрак в комнату, пожалуйста?",
    "what time's the restaurant open for dinner?": "во сколько ресторан открывается для ужина?",
    "dinner's served between 6pm and 9.30pm": "ужин подается с шести до половины десятого",
    "what time does the bar close?": "во сколько закрывается бар?",
    "would you like any help with your luggage?": "вам нужна помощь с багажом?",
    "here's your room key": "это ваш ключ от номера",
    "your room number's …": "ваш номер …",
    "your room number's 326": "ваш номер 326",
    "your room's on the … floor": "ваш номер на … этаже",
    "your room's on the first floor": "ваш номер на втором этаже",
    "your room's on the second floor": "ваш номер на третьем этаже",
    "your room's on the third floor": "ваш номер на четвертом этаже",
    "where are the lifts?": "где находятся лифты?",
    "enjoy your stay!": "приятного пребывания!",
    "Reception": "Регистрация",
    "Concierge": "Консьерж",
    "Lifts": "Лифты",
    "Bar": "Бар",
    "Restaurant": "Ресторан",
    "do you have any vacancies?": "у вас есть свободные места?",
    "from what date?": "с какого числа?",
    "for how many nights?": "на сколько дней?",
    "how long will you be staying for?": "как долго вы собираетесь пребывать?",
    "one night": "один день",
    "two nights": "два дня",
    "a week": "неделю",
    "a fortnight": "две недели",
    "two weeks": "две недели",
    "what sort of room would you like?": "какую комнату желаете?",
    "I'd like a …": "я желаю …",
    "I'd like a single room": "я желаю номер на одного",
    "I'd like a double room": "я желаю номер на двоих",
    "I'd like a twin room": "я желаю номер с двумя кроватями",
    "I'd like a triple room": "я желаю номер с тремя кроватями",
    "I'd like a suite": "я желаю номер-люкс",
    "I'd like a room with …": "я хотел бы номер с …",
    "I'd like a room with an en-suite bathroom": "я хотел бы номер с ванной комнатой",
    "I'd like a room with a bath": "я хотел бы номер с ванной",
    "I'd like a room with a shower": "я хотел бы номер с душем",
    "I'd like a room with a view": "я хотел бы номер с красивым видом",
}