slovar = {
    "that's fine, keep the change": "все в порядке, оставьте сдачу",
    "would you like a receipt?": "вы желаете чек?",
    "could I have a receipt, please?": "могу я получит чек, пожалуйста?",
    "could you pick me up here at …?": "могли бы вы забрать меня отсюда в …?",
    "could you pick me up here at six o'clock?": "могли бы вы забрать меня отсюда в шесть часов?",
    "Taxis": "Такси",
    "For hire": "Свободно",
    "OK": "ладно",
    "of course": "конечно",
    "of course not": "конечно нет",
    "that's fine": "хорошо",
    "that's right": "точно",
    "sure": "конечно",
    "certainly": "непременно",
    "definitely": "определенно",
    "absolutely": "безусловно",
    "as soon as possible": "как можно быстрее",
    "that's enough": "достаточно",
    "it doesn't matter": "это не важно",
    "it's not important": "это не важно",
    "it's not serious": "это не серьезно",
    "it's not worth it": "это того не стоит",
    "I'm in a hurry": "я тороплюсь",
    "I've got to go": "мне нужно идти",
    "I'm going out я": "собираюсь прогуляться",
    "sleep well": "спи хорошо",
    "same to you!": "и тебе того же!",
    "me too": "я(мне) тоже",
    "not bad": "неплохо",
    "I like …": "мне нравится …",
    "I like him": "мне нравится он",
    "I like her": "мне нравится она",
    "I like it": "мне нравится это",
    "I don't like …": "мне не нравится …",
    "I don't like him": "мне не нравится он",
    "I don't like her": "мне не нравится она",
    "I don't like it": "мне не нравится это",
    "thanks for your …": "спасибо за …",
    "thanks for your help": "спасибо за помощь",
    "thanks for your hospitality": "спасибо за гостепреимство",
    "thanks for your email": "спасибо за имейл",
    "I'm sorry": "извините",
    "I'm really sorry": "прошу прощения",
    "sorry I'm late": "извините за опоздание",
    "sorry to keep you waiting": "прошу прощения за задержку",
    "sorry for the delay": "извините за задержку",
    "look!": "посмотри!",
    "great!": "чудесно!",
    "come on!": "давай!",
    "only joking!": "шутка!",
    "just kidding!": "шутка!",
    "bless you!": "будь здоров! (после чихания)",
    "that's funny!": "прикольно!",
    "that's life!": "такова жизнь!",
    "that's funny, ...": "странно, ...",
    "do you have a boyfriend?": "у тебя есть парень?",
    "do you have a girlfriend?": "у тебя есть девушка?",
    "are you married?": "ты женат?, ты замужем?",
    "are you single?": "ты холостой?, ты незамужняя?",
    "are you seeing anyone?": "ты с кем-нибудь встречаешься?",
    "I'm single": "я холостой (незамужняя)",
    "I'm engaged": "я обручен(а)",
    "I'm married": "я женат (замужем)",
    "I'm divorced": "я в разводе",
    "I'm separated": "я живу отдельно",
    "I'm a widow": "я вдова",
    "I'm a widower": "я вдовец",
    "I'm seeing someone": "у меня уже кто-то есть",
    "help!": "помогите!",
    "be careful!": "будьте осторожны!",
    "look out!": "осторожно!",
    "watch out!": "осторожно!",
    "please help me": "пожалуйста, помогите мне",
    "call an ambulance!": "вызовите скорую помощь!",
    "I need a doctor": "мне нужен доктор",
    "there's been an accident": "произошел несчастный случай",
    "please hurry!": "пожалуйста, поторопитесь!",
    "I've burnt myself": "я обжегся",
    "are you OK?": "вы в порядке?",
    "is everyone OK?": "все в порядке?",
    "stop, thief!": "остановите вора!",
    "call the police!": "вызовите полицию!",
    "my wallet's been stolen": "мой кошелек украли",
    "my purse has been stolen": "мой сумочку украли",
    "my handbag's been stolen": "мою сумку украли",
    "my laptop's been stolen": "мой ноутбук украли",
    "my phone's been stolen": "мой телефон украли",
    "I'd like to report a theft": "я хотел бы заявить о краже",
    "my car's been broken into": "мою машину вскрыли",
    "I've been mugged": "меня ограбили",
    "I've been attacked": "на меня напали",
    "fire!": "пожар!",
    "call the fire brigade!": "вызовите пожарных!",
    "can you smell burning?": "вы чувствуете запах гари?",
    "there's a fire": "там пожар",
    "the building's on fire": "здание горит",
    "I'm lost": "я заблудился",
    "we're lost": "мы заблудились",
    "I can't find my …": "я не могу найти …",
}