slovar = {
    "I'll put the kettle on": "я включу чайник",
    "the kettle's boiled": "чайник вскипел",
    "can you put the light on?": "можешь включить свет?",
    "can you switch the light on?": "можешь включить свет?",
    "can you turn the light off?": "можешь выключить свет?",
    "can you switch the light off?": "можешь выключить свет?",
    "is there anything I can do to help?": "могу я чем-нибудь помочь?",
    "could you help me wash the dishes?": "можешь помочь мне помыть посуду?",
    "I'll wash and you dry": "я буду мыть, а ты вытирай",
    "I'm going to bed": "я пойду спать",
    "is there anything good on TV?": "есть что-нибудь хорошее по телевизору?",
    "is there anything good on television tonight?": "есть что-нибудь хорошее по телевизору сегодня вечером?",
    "there's a good film on later": "попозже будет хороший фильм",
    "do you want to watch a …?": "хочешь посмотреть …?",
    "do you want to watch a film?": "хочешь посмотреть фильм?",
    "do you want to watch a DVD?": "хочешь посмотреть DVD?",
    "do you want me to put the TV on?": "хочешь, я включу телевизор?",
    "could you pass me the remote control?": "можешь передать мне пульт?",
    "do you want a game of …?": "хочешь поиграть в …?",
    "do you want a game of chess?": "хочешь поиграть в шахматы?",
    "do you want a game of cards?": "хочешь поиграть в карты?",
    "what time's the match on?": "во сколько начинается матч?",
    "who's playing?": "кто играет?",
    "who's winning?": "кто выигрывает?",
    "what's the score?": "какой счет?",
    "who won?": "кто выиграл?",
    "it was a draw":"сыграли вничью",
    "what's for …?": "что на …?",
    "what's for breakfast?": "что на завтрак?",
    "what's for lunch?": "что на обед?",
    "what's for dinner?": "что на ужин?",
    "breakfast's ready": "завтрак готов",
    "lunch is ready": "обед готов",
    "dinner's ready": "ужин готов",
    "what would you like for …?": "что ты хотел бы на …?",
    "what would you like for breakfast?": "что ты хотел бы на завтрак?",
    "what would you like for lunch?": "что ты хотел бы на обед?",
    "what would you like for dinner?": "что ты хотел бы на ужин?",
    "would you like some toast?": "хочешь тост?",
    "could you pass the …, please?": "можешь передать мне …, пожалуйста?",
    "could you pass the salt, please?": "можешь передать мне соль, пожалуйста?",
    "could you pass the sugar, please?": "можешь передать мне сахар, пожалуйста?",
    "could you pass the butter, please?": "можешь передать мне масло, пожалуйста?",
    "would you like a glass of …?": "хочешь …?",
    "would you like a glass of water?": "хочешь стакан воды?",
    "would you like a glass of orange juice?": "хочешь стакан апельсинового сока?",
    "would you like a glass of wine?": "хочешь бокал вина?",
    "careful, the plate's very hot!": "осторожно, тарелка горячая!",
    "would you like some more?": "хочешь добавки?",
    "have you had enough to eat?": "ты наелся?",
    "would anyone like dessert?": "кто-нибудь хочет десерт?",
    "would anyone like coffee?": "кто-нибудь хочет кофе?",
    "what's for dessert?": "что на десерт?",
    "I'm full": "я наелся",
    "that was …": "это было …",
    "that was lovely": "это было отлично",
    "that was excellent": "это было превосходно",
    "that was very tasty": "это было очень вкусно",
    "that was delicious": "это было очень вкусно",
    "Beware of the dog": "Осторожно, собака",
}