slovar = {
    "what's the time?": "сколько времени?",
    "what time is it?": "который час?",
    "could you tell me the time, please?": "скажите, пожалуйста, сколько времени?",
    "do you happen to have the time?": "не подскажете который час?",
    "do you know what time it is?": "вы знаете сколько сейчас времени?",
    "it's …": "сейчас …",
    "it's exactly ...": "сейчас ровно ...",
    "it's about ...": "сейчас примерно ...",
    "it's almost ...": "сейчас почти ...",
    "it's just gone ...": "сейчас немного больше, чем ...",
    "one o'clock": "час",
    "two o'clock": "два часа",
    "three o'clock": "три часа",
    "four o'clock": "четыре часа",
    "five o'clock": "пять часов",
    "six o'clock": "шесть часов",
    "seven o'clock": "семь часов",
    "eight o'clock": "восемь часов",
    "ten o'clock": "десять часов",
    "eleven o'clock": "одиннадцать часов",
    "twelve o'clock": "двенадцать часов",
    "nine o'clock": "девять часов",
    "quarter past …": "четверть …",
    "quarter past one": "четверть второго",
    "quarter past two": "четверть третьего",
    "quarter past three": "четверть четвертого",
    "half past …": "половина …",
    "half past one": "половина второго",
    "half past two": "половина третьего",
    "half past three": "половина четвертого",
    "quarter to …": "без четверти …",
    "quarter to one": "без четверти час",
    "quarter to two": "без четверти два",
    "quarter to three": "без четверти три",
    "five past one": "пять минут второго",
    "ten past one": "десять минут второго",
    "twenty past one": "двадцать минут второго",
    "twenty-five past one": "двадцать пять минут второго",
    "five to two": "без пяти два",
    "ten to two": "без десяти два",
    "twenty to two": "без двадцати два",
    "twenty-five to two": "без двадцати пяти два",
    "ten fifteen": "десять часов пятнадцать минут",
    "ten thirty": "десять часов тридцать минут",
    "ten forty-five": "десять часов сорок пять минут",
    "ten am": "десять часов утра",
    "six pm": "шесть часов вечера",
    "noon": "полдень",
    "midday": "полдень",
    "midnight": "полночь",
    "11.47am": "11:47",
    "2.13pm": "14:13",
    "my watch is …": "мои наручные часы …",
    "my watch is fast": "мои наручные часы спешат",
    "my watch is slow": "мои наручные часы отстают",
    "that clock's a little …": "эти часы немного …",
    "that clock's a little fastя": "эти часы немного спешат",
    "that clock's a little slow": "эти часы немного отстают",
}