slovar = {
    "can I buy you a drink?": "могу я купить тебе что-нибудь выпить?",
    "would you like a drink?": "желаешь что-нибудь выпить?",
    "can I get you a drink?": "могу я предложить тебе что-нибудь выпить?",
    "are you on your own?": "ты без компании?",
    "would you like to join us?": "хочешь присоединиться к нам?",
    "do you mind if I join you?": "не против, если я присоединюсь?",
    "do you mind if we join you?": "не против, если мы присоединимся?",
    "do you come here often?": "ты часто здесь бываешь?",
    "is this your first time here?": "ты здесь впервые?",
    "have you been here before?": "ты бывал здесь раньше?",
    "would you like to dance?": "хочешь потанцевать?",
    "do you want to go for a drink sometime?": "давай как-нибудь пойдем вместе выпьем?",
    "I was wondering if you'd like to go out for a drink sometime": "не хочешь как-нибудь пойти вместе выпить?",
    "if you'd like to meet up sometime, let me know!": "если захочешь как-нибудь встретиться, сообщи мне!",
    "would you like to join me for a coffee?": "хочешь выпить со мной кофе?",
    "do you fancy getting a bite to eat?": "хочешь перекусить?",
    "do you fancy lunch sometime?": "хочешь как-нибудь вместе пообедать?",
    "do you fancy dinner sometime?": "хочешь как-нибудь вместе поужинать?",
    "do you fancy going to see a film sometime?": "хочешь сходить как-нибудь в кино?",
    "that sounds good": "хорошее предложение",
    "I'd love to!": "с удовольствием!",
    "sorry, I'm busy": "извини, я занят(а)",
    "sorry, you're not my type!": "прости, ты не в моём вкусе!",
    "here's my number": "вот мой номер",
    "what's your phone number?": "какой у тебя номер телефона?",
    "could I take your phone number?": "можно записать твой телефон?",
    "you look great": "ты прекрасно выглядишь",
    "you look very nice tonight": "ты очень хорошо сегодня выглядишь",
    "I like your outfit": "мне нравится твой наряд",
    "you're beautiful": "ты красивая (женщине)",
    "you're really good-looking": "ты очень хорошо выглядишь",
    "you're really sexy": "ты очень сексуальный/ая",
    "you've got beautiful eyes": "у тебя красивые глаза",
    "you've got a great smile": "у тебя великолепная улыбка",
    "thanks for the compliment!": "спасибо за комплимент!",
    "what do you think of this place?": "что ты думаешь об этом месте?",
    "shall we go somewhere else?": "может пойдем в другое место?",
    "I know a good place": "я знаю хорошее место",
    "can I kiss you?": "можно тебя поцеловать?",
    "can I walk you home?": "можно проводить тебя домой?",
    "can I drive you home?": "можно отвезти тебя домой?",
    "would you like to come in for a coffee?": "хочешь пройти и выпить кофе?",
    "would you like to come back to mine?": "хочешь пойти ко мне?",
    "thanks, I had a great evening": "спасибо, это был прекрасный вечер",
    "when can I see you again?": "когда мы сможем снова увидиться?",
    "give me a call!": "позвони мне!",
    "I'll call you": "я позвоню",
    "what do you think of me?": "что ты обо мне думаешь?",
    "I enjoy spending time with you": "мне нравится быть вместе с тобой",
    "I find you very attractive": "я считаю тебя очень привлекательным/ой",
    "I like you": "ты мне нравишься",
    "I like you a lot": "ты мне очень нравишься",
    "I'm crazy about you": "я без ума от тебя",
    "I love you!": "я люблю тебя!",
    "will you marry me?": "ты выйдешь за меня замуж?",
    "I miss you": "я соскучился",
    "I've missed you": "я очень скучал",
    "do you have any condoms?": "у тебя есть презервативы?",
    "I'm …": "я …",
    "I'm straight": "я традиционной ориентации",
    "I'm gay": "я гомосексуалист/лесбиянка",
    "I'm bisexual": "я бисексуал/бисексуалка",
}