slovar = {
    "I'm looking for a cottage": "я ищу маленький коттедж",
    "I'm looking for a bungalow": "я ищу бунгало",
    "I only need a …": "мне всего лишь нужна…",
    "I only need a one-bedroomed flat": "мне всего лишь нужнаквартира с одной спальней",
    "I only need a studio flat": "мне всего лишь нужнаквартира-студия",
    "are you looking to buy or to rent?": "вы желаете купить или снять?",
    "which area are you thinking of?": "в каком районе вы хотите?",
    "something not too far from the city centre": "что-нибудь недалеко от центра города",
    "how much are you prepared to pay?": "сколько вы готовы заплатить?",
    "what's your budget?": "каков ваш бюджет?",
    "what price range are you thinking of?": "каков предел вашей цены?",
    "how many bedrooms do you want?": "сколько спален вы хотите?",
    "it's got two bedrooms, a kitchen, a living room, and a bathroom": "там есть две спальни, кухня, гостиная и ванная комната",
    "are you looking for furnished or unfurnished accommodation?": "вы ищете меблированное или немеблированное жильё?",
    "do you want a modern or an old property?": "вы хотите новую или старую собственность?",
    "do you want a …?": "вы хотите …?",
    "do you want a garden?": "вы хотите сад?",
    "do you want a garage?": "вы хотите гараж?",
    "do you want a parking space?": "вы хотите место для парковки?",
    "are you going to need a mortgage?": "вам будет нужен жилищный кредит?",
    "have you got a property to sell?": "у вас есть собственность на продажу?",
    "are you a cash buyer?": "у вас уже есть платежные средства? (не нужен жилищный кредит)",
    "do you want us to put you on our mailing list?": "вы хотите, чтобы мы добавили вас в список рассылок?",
    "how much is the rent?": "сколько стоит аренда?",
    "what's the asking price?": "какова запрашиваемая цена?",
    "is the price negotiable?": "цена может быть обговорена?",
    "are they willing to negotiate?": "они собираются торговаться?",
    "how long has it been on the market?": "сколько времени это выставлено на продажу?",
    "is there a … school nearby?": "есть ли там по близости … школа?",
    "is there a primary school nearby?": "есть ли там по близости начальная школа?",
    "is there a secondary school nearby?": "есть ли там по близости средняя школа?",
    "how far is it from the nearest station?": "как далеко это от ближайшей станции?",
    "are there any local shops?": "там рядом есть магазины?",
    "what are the car parking arrangements?": "каковы условия парковки машины?",
    "what sort of view does it have?": "какой там вид?",
    "what floor is it on?": "на каком это этаже?",
    "it's on the …": "это на …",
    "it's on the ground floor": "это на первом этаже",
    "it's on the first floor": "это на втором этаже",
    "it's on the second floor": "это на третьем этаже",
    "it's on the third floor": "это на четвертом этаже",
    "are pets allowed?": "там разрешено держать домашних животных?",
    "I'd like to have a look at this property": "я хотел бы посмотреть на имущество",
    "when would you be available to view the property?": "когда вам будет удобно посмотреть собственность?",
    "the rent's payable monthly in advance": "платить надо вперед ежемесячно",
    "there's a deposit of one month's rent": "надо заплатить депозит в размере месячной платы",
    "how soon would you be able to move in?": "как скоро вы сможете въехать?",
    "I'd like to make an offer": "я хотел бы предложить цену",
    "we'll take it": "мы возьмем",
    "For sale": "Продается",
    "To let": "Сдаётся",
    "Under offer": "Предложение",
    "Sold": "Продано",
    "Reduced": "Уценено",
    "New price": "Новая цена",
    "Offers around £250,000": "Предложения около 250 000 фунтов",
    "Offers in excess of £180,000": "Предложения выше 180 000 фунтов",
    "£200,000 ono": "200 000 фунтов или по договоренности",
    "or nearest offer": "или по договоренности",
    "POA": "Цену надо спросить",
    "price on application": "Цену надо спросить",
    "£280 pw": "280 фунтов в неделю",
    "per week": "в неделю",
    "£1200 pcm": "1200 фунтов в месяц",
    "per calendar month": "1200 фунтов в месяц",
    "I'd like a haircut, please": "я хотел бы постричься",
    "do I need to book?": "я должен записаться?",
    "are you able to see me now?": "я могу прийти сейчас?",
    "would you like to make an appointment?": "вы хотите назначить время?",
    "would you like me to wash it?": "вы хотите, чтобы я помыл вам волосы?",
    "what would you like?": "что вы желаете?",
    "how would you like me to cut it?": "как вы хотите постричься?",
    "I'll leave it to you": "ваш выбор",
    "I'd like a trim": "я желаю стрижку",
    "I'd like a new style": "я желаю новый фасон",
    "I'd like a perm": "я желаю химическую завивку",
    "I'd like a fringe": "я желаю прямую челку",
    "I'd like some highlights": "я желаю мелирование",
    "I'd like it coloured": "я желаю покрасить волосы",
    "just a trim, please": "просто стрижку, пожалуйста",
    "how short would you like it?": "какую длину вы хотите?",
    "not too short": "не слишком коротко",
    "quite short": "довольно коротко",
    "very short": "очень коротко",
    "grade one": "уровень первый (под машинку, длина 3 мм)",
    "grade two": "уровень второй (под машинку, длина 6 мм)",
    "grade three": "уровень третий (под машинку, длина 9 мм)",
    "grade four": "уровень четвертый (под машинку, длина 12 мм)",
    "completely shaven": "полностью сбрить",
    "do you have a parting?": "у вас есть пробор?",
    "square at the back, please": "сзади прямо, пожалуйста",
    "tapered at the back, please": "сзади со скосом, пожалуйста",
    "that's fine, thanks": "так хорошо, спасибо",
    "what colour would you like?": "какой цвет вы хотите?",
    "which of these colours would you like?": "какие из этих цветов вам нравятся?",
    "would you like it blow-dried?": "вам посушить феном?",
    "could you trim my beard, please?": "не могли бы вы подстричь мне бороду?",
    "could you trim my moustache, please?": "не могли бы вы подстричь мне усы?",
    "would you like anything on it?": "вы хотите что-нибудь добавить?",
    "a little wax": "немного воска",
    "some gel": "гель",
    "some hairspray": "лак для волос",
    "nothing, thanks": "спасибо, ничего",
    "how much do I owe you?": "сколько с меня?",
    "Hairdressers": "Парикмахерская",
    "Barbers": "Мужская парикмахерская",
    "I'd like to withdraw £100, please": "я хотел бы снять 100 фунтов, пожалуйста",
    "I want to make a withdrawal": "я хотел бы снять деньги",
    "how would you like the money?": "какими купюрами вы желаете?",
    "in tens, please": "десятками, пожалуйста (банкноты по десять фунтов)",
    "ten pound notes": "десятками, пожалуйста (банкноты по десять фунтов)",
    "could you give me some smaller notes?": "вы могли бы дать мне мелкими банкнотами?",
    "I'd like to pay this in, please": "я хотел бы положить это на свой счет, пожалуйста",
    "I'd like to pay this cheque in, please": "я хотел бы положить этот чек на свой счет, пожалуйста",
}