slovar = {
    "where will you be staying?": "где вы будете жить?",
    "you have to fill in this …": "вы должны заполнить …",
    "you have to fill in this landing card": "вы должны заполнить карту прибытия",
    "you have to fill in this immigration form": "вы должны заполнить иммиграционную карту",
    "enjoy your stay!": "хорошего пребывания!",
    "could you open your bag, please?": "откройте вашу сумку, пожалуйста",
    "do you have anything to declare?": "у вас есть что-нибудь, подлежащее декларации?",
    "you have to pay duty on these items": "вы должны уплатить за это пошлину",
    "EU citizens": "Граждане ЕС",
    "All passports": "Все паспорта",
    "Wait behind the yellow line": "Ждите за жёлтой чертой",
    "Please have your passport ready": "Пожалуйста, приготовьте паспорт",
    "Nothing to declare": "Нечего декларировать",
    "Goods to declare": "Вещи, подлежащие декларации",
    "what time's the next boat to …?": "во сколько следующий корабль на …?",
    "what time's the next boat to Calais?": "во сколько следующий корабль на Кале?",
    "I'd like a … cabin": "я хотел бы … каюту",
    "I'd like a two-berth cabin": "я хотел бы двух-местную каюту",
    "I'd like a four-berth cabin": "я хотел бы четырех-местную каюту",
    "we don't need a cabin": "нам не нужна каюта",
    "I'd like a ticket for a car and two passengers": "я хотел бы билет на машину и двух пассажиров",
    "I'd like a ticket for a foot passenger": "я хотел бы билет для пассажира",
    "how long does the crossing take?": "как долго продлится рейс?",
    "what time does the ferry arrive in …?": "во сколько паром прибывает в …?",
    "what time does the ferry arrive in Stockholm?": "во сколько паром прибывает в Стокгольм?",
    "how soon before the departure time do we have to arrive?": "за какое время до отправления мы должны приехать?",
    "where's the information desk?": "где находится информационный пункт?",
    "where's cabin number …?": "где каюта номер …?",
    "where's cabin number 258?": "где каюта номер 258?",
    "which deck's the … on?": "на какой палубе находится …?",
    "which deck's the buffet on?": "на какой палубе находится буфет?",
    "which deck's the restaurant on?": "на какой палубе находится ресторан?",
    "which deck's the bar on?": "на какой палубе находится бар?",
    "which deck's the shop on?": "на какой палубе находится магазин?",
    "which deck's the cinema on?": "на какой палубе находится кино?",
    "which deck's the bureau de change on?": "на какой палубе находится пункт обмена валюты?",
    "I feel seasick": "у меня морская болезнь",
    "the sea's very rough": "на море шторм",
    "the sea's quite calm": "на море довольно спокойно",
    "all car passengers, please make your way down to the car decks for disembarkation": "все пассажиры, пожалуйста проследуйте на автомобильную палубу для высадки",
    "we will be arriving in port in approximately 30 minutes' time": "мы прибудем в порт примерно через 30 минут",
    "please vacate your cabins": "пожалуйста, освободите каюты",
    "Cabin": "Каюта",
    "Deck": "Палуба",
    "Stairs": "Лестница",
    "Cinema": "Кино",
    "Shop": "Магазин",
    "Lifejackets": "Спасательные жилеты",
    "I've come to collect my tickets": "я хотел бы забрать свой билет",
    "I booked on the internet": "я заказал билет в интернете",
    "do you have your booking reference?": "у вас есть код брони?",
    "your passport and ticket, please": "ваш паспорт и билет, пожалуйста",
    "here's my booking reference": "это мой код бронирования",
    "where are you flying to?": "куда вы летите?",
    "did you pack your bags yourself?": "вы сами упаковывали свои вещи?",
    "has anyone had access to your bags in the meantime?": "кто-нибудь имел доступ к вашим вещам?",
    "do you have any liquids or sharp objects in your hand baggage?": "в важем багаже есть жидкости или острые предметы?",
    "how many bags are you checking in?": "сколько сумок вы сдаёте?",
    "could I see your hand baggage, please?": "покажите вашу ручную кладь, пожалуйста",
    "do I need to check this in or can I take it with me?": "я должен это сдать или могу взять с собой?",
    "there's an excess baggage charge of …": "дополнительная плата за багаж …",
    "there's an excess baggage charge of £30": "дополнительная плата за багаж 30 фунтов",
    "would you like a window or an aisle seat?": "вы хотите сидеть у окна или в проходе?",
    "enjoy your flight!": "счастливого полета!",
    "where can I get a trolley?": "где находятся тележки?",
    "are you carrying any liquids?": "у вас есть с собой какие-либо жидкости?",
    "could you take off your …, please?": "снимите …, пожалуйста",
    "could you take off your coat, please?": "снимите пальто, пожалуйста",
    "could you take off your shoes, please?": "снимите обувь, пожалуйста",
    "could you take off your belt, please?": "снимите ремень, пожалуйста",
    "could you put any metallic objects into the tray, please?": "полажите металлические предметы на поднос, пожалуйста",
    "please empty your pockets": "освободите карманы, пожалуйста",
    "please take your laptop out of its case": "пожалуйста достаньте ноутбук из сумки",
    "I'm afraid you can't take that through": "к сожалению, вы не можете взять это собой",
    "what's the flight number?": "какой номер рейса?",
    "which gate do we need?": "какие у нас ворота?",
    "last call for passenger Smith travelling to Miami, please proceed immediately to Gate number 32": "последний вызов пассажира Смита, путешествующего в Майами, пожалуйста пройдите к воротам номер 32",
    "the flight's been delayed": "рейс задерживается",
    "the flight's been cancelled": "рейс отменён",
    "we'd like to apologise for the delay": "мы хотели бы извиниться за задержку",
    "could I see your passport and boarding card, please?": "покажите ваш паспорт и посадочный билет, пожалуйста",
    "what's your seat number?": "какой у вас номер места?",
    "could you please put that in the overhead locker?": "уберите это, пожалуйста, в верхнее отделение",
    "please pay attention to this short safety demonstration": "пожалуйста, обратите внимание на эту небольшую презентацию",
    "please turn off all mobile phones and electronic devices": "пожалуйста, отключите мобильные телефоны и электронные приборы",
    "the captain has turned off the Fasten Seatbelt sign": "капитан выключил сигнал «Пристегнуть ремни»",
    "how long does the flight take?": "сколько времени продлится полет?",
    "would you like any food or refreshments?": "вы желаете еду или напитки?",
    "the captain has switched on the Fasten Seatbelt sign": "капитан включил сигнал «Пристегнуть ремни»",
    "we'll be landing in about fifteen minutes": "мы приземлимся примерно через 15 минут",
    "please fasten your seatbelt and return your seat to the upright position": "пожалуйста, пристегните ремни и верните кресло в исходное положение",
    "please stay in your seat until the aircraft has come to a complete standstill and the Fasten Seatbelt sign has been switched off": "пожалуйста, не вставайте до полной остановки самолета и выключения сигнала «Пристегнуть ремни»",
    "the local time is …": "местное время …",
    "the local time is 9.34pm": "местное время 21:34",
    "Short stay": "Краткосрочная парковка",
    "Short stay car park": "Краткосрочная парковка",
    "Long stay": "Долгосрочная парковка",
    "Long stay car park": "Долгосрочная парковка",
    "Arrivals": "Прибытие",
    "Departures": "Отправление",
    "International check-in": "Международная регистрация",
    "International departures": "Прибытие международных рейсов",
    "Domestic flights": "Местные рейсы",
    "Toilets": "Туалеты",
    "Information": "Информация",
    "Ticket offices": "Кассы",
    "Lockers": "Хранилище",
    "Payphones": "Телефон-автомат",
    "Restaurant": "Ресторан",
    "Check-in closes 40 minutes before departure": "Регистрация закрывается за 40 минут до отправления",
    "Gates 1-32": "Ворота 1—32",
    "Tax free shopping": "Магазины такс-фри",
    "Duty free shopping": "Магазины дьюти-фри",
    "Transfers": "Пересадка",
    "Flight connections": "Пересадка",
    "Baggage reclaim": "Выдача багажа",
    "Passport control": "Паспортный контроль",
    "Customs": "Таможня",
    "Car hire": "Прокат автомобилей",
    "Departures board": "Отправляющиеся рейсы",
    "Check-in open": "Регистрация открыта",
}