slovar = {
    "I share with one other person": "я живу с одним человеком",
    "I share with … others": "я живу с … другими",
    "I share with two others": "я живу с двумя другими",
    "I share with three others": "я живу с тремя другими",
    "what's your phone number?": "какой у тебя номер телефона?",
    "what's your email address?": "какой у тебя электронный адрес?",
    "what's your address?": "какой твой адрес?",
    "could I take your phone number?": "можно записать твой номер телефона?",
    "could I take your email address?": "можно записать твой электронный адрес?",
    "are you on …?": "ты зарегистрирован в …?",
    "are you on Facebook?": "ты зарегистрирован в Facebook?",
    "are you on Skype?": "ты зарегистрирован в Skype?",
    "what's your username?": "какое у тебя там имя?",
    "have you got any pets?": "у тебя есть домашние животные?",
    "I've got …": "у меня …",
    "I've got a dog and two cats": "у меня собака и две кошки",
    "I've got a Labradorу": "меня лабрадор",
    "what's his name?": "как его зовут?",
    "he's called …": "его зовут …",
    "he's called Tom": "его зовут Том",
    "what's her name?": "как ее зовут?",
    "she's called …": "ее зовут …",
    "she's called Mary": "ее зовут Мери",
    "what are their names?": "как их зовут?",
    "they're called …": "их зовут …",
    "they're called Neil and Anna": "их зовут Нейл и Анна",
    "how old is he?": "сколько ему лет?",
    "he's …": "ему …",
    "he's twelve": "ему двенадцать",
    "how old is she?": "сколько ей лет?",
    "she's …": "ей …",
    "she's fifteen": "ей пятнадцать",
    "how old are they?": "сколько им лет?",
    "they're …": "им …",
    "they're six and eight": "им шесть и восемь",
}