slovar = {
    "here": "здесь (тут)",
    "there": "там",
    "everywhere": "везде",
    "nowhere": "нигде",
    "somewhere": "где-то",
    "where are you?": "где ты?, где вы?",
    "what's this?": "что это здесь?",
    "what's that?": "что это там?",
    "is anything wrong?": "что-то не так?",
    "what's the matter?": "в чем дело?",
    "is everything OK?": "все в порядке?",
    "have you got a minute?": "у тебя есть свободная минутка?",
    "have you got a pen I could borrow?": "можно одолжить ручку?",
    "really?": "правда?",
    "are you sure?": "ты уверен?",
    "why?": "почему?",
    "why not ?": "почему бы и нет?",
    "what's going on?": "что происходит?",
    "what's happening?": "что происходит?",
    "what happened?": "что случилось?",
    "what?": "что?",
    "where?": "где?",
    "when?": "когда?",
    "who?": "кто?",
    "how?": "как?",
    "how many?": "сколько?",
    "how much?": "сколько?",
    "congratulations!": "поздравления!",
    "well done!": "хорошо сработано!",
    "good luck!": "удачи!",
    "bad luck!": "вот незадача!",
    "never mind!": "неважно!",
    "what a pity!": "как жаль!",
    "what a shame!": "как жаль!",
    "happy birthday!": "с днем рождения!",
    "happy New Year!": "с Новым Годом!",
    "happy Easter!": "хороших пасхальных праздников!",
    "happy Christmas!": "счастливого Рождества!",
    "merry Christmas!": "счастливого Рождества!",
    "happy Valentine's Day!": "с днем святого Валентина!",
    "glad to hear it": "рад это слышать",
    "sorry to hear that": "жаль это слышать",
    "I'm tired": "я устал",
    "I'm exhausted": "я изможден",
    "I'm hungry": "я хочу есть",
    "I'm thirsty": "я хочу пить",
    "I'm bored": "мне скучно",
    "I'm worried": "я обеспокоен",
    "I'm looking forward to it": "я с нетерпением жду этого",
    "I'm in a good mood": "я в хорошем настороении",
    "I'm in a bad mood": "я в плохом настроении",
    "I can't be bothered": "не беспокойте меня",
    "welcome!": "добро пожаловать!",
    "welcome to …": "добро пожаловать в …",
    "welcome to England": "добро пожаловать в Англию",
    "long time, no see!": "давно не виделись!",
    "all the best!": "всего хорошего!",
    "see you tomorrow!": "до завтра!",
    "what do you think?": "что ты думаешь?",
    "I think that...": "я думаю, что...",
    "I hope that...": "я надеюсь, что...",
    "I'm afraid that ...": "я боюсь, что...",
    "in my opinion, ...": "по моему мнению, ...",
    "I agree": "я согласен (согласна)",
    "I disagree": "я не согласен (согласна)",
    "I don't agree": "я не согласен (согласна)",
    "that's true": "это правда",
    "that's not true": "это не правда",
    "I think so": "думаю, что так",
    "I don't think so": "я так не думаю",
    "I hope so": "надеюсь",
    "I hope not": "надеюсь, что нет",
    "you're right": "ты прав",
    "you're wrong": "ты не прав",
    "I don't mind": "я не возражаю",
    "it's up to you": "это зависит от тебя",
    "that depends": "смотря как",
    "that's interesting": "это интересно",
    "what languages can you speak?": "на каких языках вы говорите?",
    "I speak …": "я говорю …",
    "I speak French, Spanish, and a little Russian": "я говорю по-французски, по-испански и немного по-русски",
    "I speak fluent German": "я говорю свободно по-немецки",
    "I can get by in …": "я неплохо говорю …",
    "I can get by in Italian": "я неплохо говорю по-итальянски",
    "I'm learning …": "я учу …",
    "I'm learning Chinese": "я учу китайский",
    "where did you learn your English?": "где ты выучил английский?",
    "at school": "в школе",
    "at university": "в университете",
    "I took a course": "я ходил на курсы",
    "I taught myself": "я выучил самостоятельно",
    "do you understand?": "ты понимаешь?",
    "did you understand?": "ты понял?",
    "yes, I understood": "да, я понял",
    "sorry, I didn't understand": "извини, я не понял",
    "sorry?": "простите?",
    "excuse me?": "простите?",
    "how do you say ... in English?": "как будет по-английски ...?",
    "how do you spell that?": "как это пишется?",
    "how do you pronounce this word?": "как произносится это слово?",
    "you speak very good English": "ты очень хорошо говоришь по-английски",
    "your English is very good": "у тебя очень хороший английский",
    "I'm a little out of practice": "мне не хватает практики",
    "I'd like to practise my …": "я хотел бы попрактиковаться в …",
    "I'd like to practise my Portuguese": "я хотел бы попрактиковаться в португальском",
    "let's speak in …": "давайте поговорим …",
    "let's speak in English": "давайте поговорим по-английски",
    "let's speak in Italian": "давайте поговорим по-итальянски",
    "what's this called?": "как это называется?",
}