slovar = {
    "well done": "хорошо прожарить",
    "is that all?": "это всё?",
    "would you like anything else?": "желаете что-нибудь ещё?",
    "nothing else, thank you": "больше ничего, спасибо",
    "we're in a hurry": "мы торопимся",
    "how long will it take?": "как скоро будет готово?",
    "it'll take about twenty minutes": "будет готово примерно через двадцать минут",
    "excuse me!": "извините!",
    "enjoy your meal!": "приятного аппетита!",
    "bon appétit!": "приятного аппетита!",
    "would you like to taste the wine?": "вы желаете попробовать вино?",
    "could we have …?": "мы хотели бы …",
    "could we have another bottle of wine?": "мы хотели бы ещё бутылку винаs",
    "could we have some more bread?": "мы хотели бы ещё хлеба",
    "could we have some more milk?": "мы хотели бы ещё молока",
    "could we have a jug of tap water?": "мы хотели бы кувшин воды из под крана",
    "could we have some water?": "мы хотели бы воды",
    "still or sparkling?": "без газов или с газами?",
    "would you like any coffee or dessert?": "вы хотите кофе или десерт?",
    "do you have any desserts?": "у вас есть какие-нибудь десерты?",
    "could I see the dessert menu?": "принесите меню с десертами",
    "was everything alright?": "всё было в порядке?",
    "thanks, that was delicious": "спасибо, это было очень вкусно",
    "this isn't what I ordered": "это не то, что я заказал(а)",
    "this food's cold": "еда холодная",
    "this is too salty": "блюдо слишком соленое",
    "this doesn't taste right": "вкус какой-то странный",
    "we've been waiting a long time": "мы долго ждали",
    "is our meal on its way?": "наш заказ уже готов?",
    "will our food be long?": "долго ждать пока приготовят?",
    "the bill, please": "счёт, пожалуйста",
    "could we have the bill, please?": "могли бы мы получить счёт, пожалуйста",
    "can I pay by card?": "можно заплатить карточкой?",
    "do you take credit cards?": "вы принимаете кредитные карточки?",
    "is service included?": "плата за обслуживание включена?",
    "can we pay separately?": "можем мы заплатить раздельно?",
    "I'll get this": "я буду это",
    "let's split it": "давайте разделим на двоих",
    "let's share the bill": "давайте заплатим вместе",
    "Please wait to be seated": "Пожалуйста подождите, вас посадят",
    "Reserved": "Зарезервировано",
    "Service included": "Чаевые включены в цену",
    "Service not included": "Чаевые не включены в цену",
    "what would you like to drink?": "что бы вы хотели выпить? , что ты хотел бы выпить? (бармен клиентудруг другу)",
    "what are you having?": "что ты будешь?",
    "what can I get you?": "что я могу предложить?",
    "I'll have …, please": "я бы хотел …, пожалуйста",
    "I'll have a pint of lager, please": "я бы хотел пинту светлого пива (одна пинта немного больше половины литра), пожалуйста",
    "I'll have a pint of bitter, please": "я бы хотел пинту биттера (сорт традиционного английского пиво), пожалуйста",
    "I'll have a glass of white wine, please": "я бы хотел бокал белого вина, пожалуйста",
    "I'll have a glass of red wine, please": "я бы хотел бокал красного вина, пожалуйста",
    "I'll have an orange juice, please": "я бы хотел апельсиновый сок, пожалуйста",
    "I'll have a coffee, please": "я бы хотел кофе, пожалуйста",
    "I'll have a Coke, please": "я бы хотел кока-колу, пожалуйста",
    "I'll have a Diet Coke, please": "я бы хотел диетическую кока-колу, пожалуйста",
    "large or small?": "большой стакан или маленький?",
    "would you like ice with that?": "желаете со льдом?",
    "no ice, please": "без льда, пожалуйста",
    "a little, please": "немного, пожалуйста",
    "lots of ice, please": "много льда, пожалуйста",
    "a beer, please": "пиво, пожалуйста",
    "two beers, please": "два пива, пожалуйста",
    "three shots of tequila, please": "три стопки текилы, пожалуйста",
    "are you being served?": "вас уже обслуживают?",
    "I'm being served, thanks": "меня уже обслуживают, спасибо",
    "who's next?": "кто следующий?",
    "which wine would you like?": "какое вино вы бы хотели?",
    "house wine is fine": "столовое вино подойдёт",
    "which beer would you like?": "какое пиво вы бы хотели?",
    "would you like draught or bottled beer?": "вы желаете разливное или бутылочное пиво?",
    "I'll have the same, please": "я буду то же самое, пожалуйста",
    "nothing for me, thanks": "для меня ничего, спасибо",
    "I'll get these": "я буду это",
    "keep the change!": "оставьте сдачу себе!",
    "cheers!": "за здоровье!",
    "whose round is it?": "чья очередь платить?",
    "it's my round": "моя очередь",
    "it's your round": "твоя очередь",
    "another beer, please": "ещё пива, пожалуйста",
    "another two beers, please": "ещё два пива, пожалуйста",
    "same again, please": "то же самое, пожалуйста",
    "are you still serving drinks?": "вы ещё подаёте выпить?",
    "last orders!": "последние заказы!",
    "do you have any snacks?": "у вас есть какие-нибудь закуски?",
    "do you have any sandwiches?": "у вас есть какие-нибудь бутерброды?",
    "do you serve food?": "вы подаёте поесть?",
    "what time does the kitchen close?": "во-сколько закрывается кухня?",
    "are you still serving food?": "вы ещё подаёте поесть?",
    "a packet of crisps, please": "пачку чипсов, пожалуйста",
    "what flavour would you like?": "с каким вкусом вы бы хотели?",
    "ready salted": "соленые",
    "cheese and onion": "сыр с луком",
    "salt and vinegar": "соль и уксус",
    "what sort of sandwiches do you have?": "какие у вас есть бутерброды?",
    "do you have any hot food?": "у вас есть какая-нибудь горячая еда?",
    "today's specials are on the board": "сегодняшние специальные блюда написаны на доске",
    "is it table service or self-service?": "этот столик обслуживается или надо самим заказывать?",
    "would you like anything to eat?": "вы хотите что-нибудь поесть?",
    "could we see a menu, please?": "мы могли бы посмотреть меню, пожалуйста?",
    "eat in or take-away?": "здесь или с собой?",
    "does anyone fancy a game of …?": "кто-нибудь хочет поиграть в …?",
    "does anyone fancy a game of pool?": "кто-нибудь хочет поиграть в бильярд?",
    "does anyone fancy a game of darts?": "кто-нибудь хочет поиграть в дартс?",
    "does anyone fancy a game of cards?": "кто-нибудь хочет поиграть в карты?",
    "do you have internet access here?": "здесь есть интернет?",
    "do you have wireless internet here?": "здесь есть беспроводной интернет?",
    "what’s the password for the internet?": "какой пароль для интернета?",
    "I feel fine": "я прекрасно себя чувствую",
    "I feel terrible": "я ужасно себя чувствую",
    "I've got a hangover": "у меня похмелье",
    "I'm never going to drink again!": "я никогда больше не буду пить!",
    "do you smoke?": "ты куришь?, вы курите?",
    "no, I don't smoke": "нет, я не курю",
    "I've given up": "я бросил",
    "do you mind if I smoke?": "ты не против, если я закурю?",
    "would you like a cigarette?": "хочешь сигарету?",
    "have you got a light?": "у тебя есть прикурить?",
    "do you know any good restaurants?": "вы знаете какой-нибудь приличный ресторан?",
    "where's the nearest restaurant?": "где находится ближайший ресторан?",
}