slovar = {
    "for two days": "на два дня",
    "for a week": "на неделю",
    "how much does it cost?": "сколько это стоит?",
    "£40 a day with unlimited mileage": "40 фунтов в день без ограничения расстояния",
    "what type of car do you want — manual or automatic?": "какой тип коробки передач вы хотите — мануальный или автоматический?",
    "has this car got …?": "в машине есть …?",
    "has this car got air conditioning?": "в машине есть кондиционер?",
    "has this car got central locking?": "в машине есть центральный замок?",
    "has this car got a CD player?": "в машине есть проигрыватель компакт-дисков?",
    "has this car got child locks?": "в машине есть «детские» замки?",
    "could I see your driving licence?": "покажите ваши водительские права",
    "you have to bring it back with a full tank": "вы должны вернуть её с полным баком",
    "it has to be returned by 2pm on Saturday": "она должна быть возвращена до 2 часов дня в воскресенье",
    "remember to drive on the …": "двигайтесь по …",
    "remember to drive on the left": "двигайтесь по левой стороне",
    "remember to drive on the right": "двигайтесь по правой стороне",
    "does it take petrol or diesel?": "машина бензиновая или дизельная?",
    "is it manual or automatic?": "коробка передач мануальная или автоматическая?",
    "I'll show you the controls": "я покажу вам выключатели",
    "where are the …?": "где включаются …?",
    "where are the lights?": "где включаются фары?",
    "where are the indicators?": "где включаются поворотники?",
    "where are the windscreen wipers?": "где включаются дворники?",
    "how do you open the …?": "как открывается …?",
    "how do you open the petrol tank?": "как открывается топливный бак?",
    "how do you open the boot?": "как открывается багажник?",
    "how do you open the bonnet?": "как открывается капот?",
    "do you know where I can get a taxi?": "ты знаешь, где можно поймать такси?",
    "do you have a taxi number?": "у тебя есть номер такси?",
    "I'd like a taxi, please": "я хотел бы заказать такси, пожалуйста",
    "sorry, there are none available at the moment": "извините, сейчас свободных такси нет",
    "where are you?": "где вы?",
    "what's the address?": "какой адрес?",
    "I'm …": "я …",
    "I'm at the Metropolitan Hotel": "я в отеле «Метрополь»",
    "I'm at the train station": "я на железнодорожном вокзале",
    "I'm at the corner of Oxford Street and Tottenham Court Road": "я на углу Оксфордстрит и Тоттенхэмкортроад",
    "could I take your name, please?": "назовите свое имя, пожалуйста",
    "how long will I have to wait?": "как долго ждать?",
    "how long will it be?": "сколько ждать?",
    "quarter of an hour": "четверть часа",
    "about ten minutes": "около десяти минут",
    "it's on its way": "машина в пути",
    "where would you like to go?": "куда бы вы хотели поехать?",
    "I'd like to go to …": "я хотел бы поехать …",
    "I'd like to go to Charing Cross station": "я хотел бы поехать на станцию «Чаринг Кросс»",
    "could you take me to …?": "не могли бы вы отвезти меня в …?",
    "could you take me to the city centre?": "не могли бы вы отвезти меня в центр города?",
    "how much would it cost to …?": "сколько стоит доехать до …?",
    "how much would it cost to Heathrow Airport?": "сколько стоит доехать до аэропорта «Хитроу»?",
    "how much will it cost?": "сколько это будет стоить?",
    "could we stop at a cashpoint?": "могли бы мы остановиться у банкомата?",
    "is the meter switched on?": "включен ли таксометр?",
    "please switch the meter on": "пожалуйста, включите таксометр",
    "how long will the journey take?": "сколько туда ехать?",
    "do you mind if I close the window?": "вы не против, если я закрою окно?",
    "are we almost there?": "мы уже почти приехали?",
    "how much is it?": "сколько с меня?",
    "have you got anything smaller?": "у вас есть более мелкие деньги?",
    "do you have any brothers or sisters?": "у тебя есть брат или сестра?",
    "yes, I've got …": "да, у меня есть …",
    "yes, I've got a brother": "да, у меня есть брат",
    "yes, I've got a sister": "да, у меня есть сестра",
    "yes, I've got an elder brother": "да, у меня есть старший брат",
    "yes, I've got a younger sister": "да, у меня есть младшая сестра",
    "yes, I've got two brothers": "да, у меня есть два брата",
    "yes, I've got two sisters": "да, у меня есть две сестры",
    "yes, I've got one brother and two sisters": "да, у меня есть брат и две сестры",
    "no, I'm an only child": "нет, я единственный ребенок",
    "have you got any kids?": "у тебя есть дети?",
    "do you have any children?": "у тебя есть дети?",
    "yes, I've got a boy and a girl": "да, у меня мальчик и девочка",
    "yes, I've got a young baby": "да, у меня малыш",
    "yes, I've got three kids": "да, у меня три ребенка",
    "I don't have any children": "у меня нет детей",
    "do you have any grandchildren?": "у вас есть внуки?",
    "where do your parents live?": "где живут твои родители?",
    "what do your parents do?": "чем занимаются твои родители?",
    "what does your father do?": "чем занимается твой отец?",
    "what does your mother do?": "чем занимается твоя мать?",
    "are your grandparents still alive?": "твои бабушка и дедушка еще живы?",
    "let me know if you can make it": "сообщи, если ты сможешь",
    "I'll call you later": "я позвоню тебе позже",
    "what's your address?": "какой твой адрес?",
    "I'm running a little late": "я немного опаздываю",
    "I'll be there in … minutes": "я буду там через … минут",
    "I'll be there in five minutes": "я буду там через пять минут",
    "I'll be there in ten minutes": "я буду там через десять минут",
    "I'll be there in fifteen minutes": "я буду там через пятнадцать минут",
    "have you been here long?": "ты уже давно тут?",
    "have you been waiting long?": "ты долго ждал?",
    "come on in!": "входи!, входите!",
    "good to see you!": "рад тебя видеть, рад вас видеть",
    "you're looking well": "ты прекрасно выглядишь, вы прекрасно выглядите",
    "please take your shoes off": "пожалуйста, сними обувь, пожалуйста, снимите обувь",
    "can I take your coat?": "я возьму твое пальто",
    "sorry we're late": "извини, мы опоздали",
    "did you have a good journey?": "ты хорошо добрался?, вы хорошо добрались?",
    "did you find us alright?": "ты нашел нас без проблем?, вы нашли нас без проблем?",
    "I'll show you your room": "я покажу твою комнату, я покажу вашу комнату",
    "this is your room": "это твоя комната, это ваша комната",
    "would you like a towel?": "тебе нужно полотенце?",
    "make yourself at home": "чувствуй себя как дома, чувствуйте себя как дома",
    "can I get you anything to drink?": "хочешь что-нибудь выпить?, хотите что-нибудь выпить?",
    "would you like a tea or coffee?": "хочешь чай или кофе?, хотите чай или кофе?",
    "how do you take it?": "с чем ты хочешь?",
    "do you take sugar?": "сколько положить сахара?",
    "do you take milk?": "тебе нужно молоко?",
    "how many sugars do you take?": "сколько положить сахара?",
    "would you like a …?": "хочешь …?",
    "would you like a soft drink?": "хочешь попить (буквально: безалкогольный напиток)?",
    "would you like a beer?": "хочешь пиво?",
    "would you like a glass of wine?": "хочешь бокал вина?",
    "would you like a gin and tonic?": "хочешь джин с тоником?",
    "have a seat!": "садись!, садитесь!",
    "let's go into the …": "давай(те) пойдем в …",
    "let's go into the lounge": "давай(те) пойдем в гостиную",
    "let's go into the living room": "давай(те) пойдем в гостиную",
    "let's go into the dining room": "давай(те) пойдем в столовую",
    "do you mind if I smoke here?": "ты не против, если я здесь закурю?",
    "I'd prefer it if you went outside": "будет лучше, если ты выйдешь на улицу",
    "are you ready to eat now?": "ты готов есть?, вы готовы есть?",
    "who's driving tonight?": "кто сегодня за рулем?",
}