slovar = {
    "this evening at seven o'clock": "сегодня вечером в семь часов",
    "this evening at seven thirty": "сегодня вечером в семь тридцать",
    "this evening at eight o'clock": "сегодня вечером в восемь часов",
    "this evening at eight thirty": "сегодня вечером в восемь тридцать",
    "tomorrow at …": "затра в …",
    "tomorrow at noon": "затра в полдень",
    "tomorrow at twelve thirty": "затра в двенадцать тридцать",
    "tomorrow at one o'clock": "затра в час",
    "tomorrow at one thirty": "затра в час тридцать",
    "for how many people?": "на сколько людей?",
    "do you have a reservation?": "у вас зарезервировано?",
    "could I see the menu, please?": "могу я посмотреть меню, пожалуйста?",
    "could I see the wine list, please?": "могу я посмотреть карту вин, пожалуйста?",
    "can I get you any drinks?": "могу я принести вам что-нибудь выпить?",
    "are you ready to order?": "вы готовы заказать?",
    "do you have any specials?": "у вас есть специальные блюда?",
    "what's the soup of the day?": "какой сегодня суп?",
    "what do you recommend?": "что вы порекомендуете?",
    "what's this dish?": "что это за блюдо?",
    "I'm on a diet": "я на диете",
    "I'm allergic to …": "у меня аллергия на …",
    "I'm allergic to wheat": "у меня аллергия на пшеницу",
    "I'm allergic to dairy products": "у меня аллергия на молочные продукты",
    "I'm severely allergic to …": "у меня сильная аллергия на …",
    "I'm severely allergic to nuts": "у меня сильная аллергия на орехи",
    "I'm severely allergic to shellfish": "у меня сильная аллергия на моллюски",
    "I'm a vegetarian": "я вегетарианец / вегетарианка",
    "I don't eat …": "я не ем …",
    "I don't eat meat": "я не ем мясо",
    "I don't eat pork": "я не ем свинину",
    "I'll have the …": "я буду …",
    "I'll have the chicken breast": "я буду куриные грудки",
    "I'll have the roast beef": "я буду ростбиф",
    "I'll have the pasta": "я буду макароны",
    "I'll take this": "я возьму это",
    "I'm sorry, we're out of that": "извините, у нас это закончилось",
    "for my starter I'll have the soup, and for my main course the steak": "для начала я возьму суп, а как основное блюдо — кусок мяса",
    "how would you like your steak?": "какой прожарки вы желаете мясо?",
    "rare": "с кровью",
    "medium-rare": "немного с кровью",
    "medium": "средней прожарки",
    "well done": "хорошо прожарить",
    "is that all?": "это всё?",
    "would you like anything else?": "желаете что-нибудь ещё?",
    "nothing else, thank you": "больше ничего, спасибо",
    "we're in a hurry": "мы торопимся",
    "how long will it take?": "как скоро будет готово?",
    "it'll take about twenty minutes": "будет готово примерно через двадцать минут",
    "excuse me!": "извините!",
    "enjoy your meal!": "приятного аппетита!",
    "bon appétit!": "приятного аппетита!",
    "would you like to taste the wine?": "вы желаете попробовать вино?",
    "could we have …?": "мы хотели бы …",
    "could we have another bottle of wine?": "мы хотели бы ещё бутылку винаs",
    "could we have some more bread?": "мы хотели бы ещё хлеба",
    "could we have some more milk?": "мы хотели бы ещё молока",
    "could we have a jug of tap water?": "мы хотели бы кувшин воды из под крана",
    "could we have some water?": "мы хотели бы воды",
    "still or sparkling?": "без газов или с газами?",
    "would you like any coffee or dessert?": "вы хотите кофе или десерт?",
    "do you have any desserts?": "у вас есть какие-нибудь десерты?",
    "could I see the dessert menu?": "принесите меню с десертами",
    "was everything alright?": "всё было в порядке?",
    "thanks, that was delicious": "спасибо, это было очень вкусно",
    "this isn't what I ordered": "это не то, что я заказал(а)",
    "this food's cold": "еда холодная",
    "this is too salty": "блюдо слишком соленое",
    "this doesn't taste right": "вкус какой-то странный",
    "we've been waiting a long time": "мы долго ждали",
    "is our meal on its way?": "наш заказ уже готов?",
    "will our food be long?": "долго ждать пока приготовят?",
    "the bill, please": "счёт, пожалуйста",
    "could we have the bill, please?": "могли бы мы получить счёт, пожалуйста",
    "can I pay by card?": "можно заплатить карточкой?",
    "do you take credit cards?": "вы принимаете кредитные карточки?",
    "is service included?": "плата за обслуживание включена?",
    "can we pay separately?": "можем мы заплатить раздельно?",
    "I'll get this": "я буду это",
    "let's split it": "давайте разделим на двоих",
    "let's share the bill": "давайте заплатим вместе",
    "Please wait to be seated": "Пожалуйста подождите, вас посадят",
    "Service included": "Чаевые включены в цену",
    "Service not included": "Чаевые не включены в цену",
    "what would you like to drink?": "что бы вы хотели выпить? , что ты хотел бы выпить? (бармен клиентудруг другу)",
    "what are you having?": "что ты будешь?",
    "what can I get you?": "что я могу предложить?",
    "I'll have …, please": "я бы хотел …, пожалуйста",
    "I'll have a pint of lager, please": "я бы хотел пинту светлого пива (одна пинта немного больше половины литра), пожалуйста",
    "I'll have a pint of bitter, please": "я бы хотел пинту биттера (сорт традиционного английского пиво), пожалуйста",
    "I'll have a glass of white wine, please": "я бы хотел бокал белого вина, пожалуйста",
    "I'll have a glass of red wine, please": "я бы хотел бокал красного вина, пожалуйста",
    "I'll have an orange juice, please": "я бы хотел апельсиновый сок, пожалуйста",
    "I'll have a coffee, please": "я бы хотел кофе, пожалуйста",
    "I'll have a Coke, please": "я бы хотел кока-колу, пожалуйста",
    "I'll have a Diet Coke, please": "я бы хотел диетическую кока-колу, пожалуйста",
    "large or small?": "большой стакан или маленький?",
    "would you like ice with that?": "желаете со льдом?",
    "no ice, please": "без льда, пожалуйста",
    "a little, please": "немного, пожалуйста",
    "lots of ice, please": "много льда, пожалуйста",
    "a beer, please": "пиво, пожалуйста",
    "two beers, please": "два пива, пожалуйста",
    "three shots of tequila, please": "три стопки текилы, пожалуйста",
    "are you being served?": "вас уже обслуживают?",
    "I'm being served, thanks": "меня уже обслуживают, спасибо",
    "who's next?": "кто следующий?",
    "which wine would you like?": "какое вино вы бы хотели?",
    "house wine is fine": "столовое вино подойдёт",
    "which beer would you like?": "какое пиво вы бы хотели?",
    "would you like draught or bottled beer?": "вы желаете разливное или бутылочное пиво?",
    "I'll have the same, please": "я буду то же самое, пожалуйста",
    "nothing for me, thanks": "для меня ничего, спасибо",
    "I'll get these": "я буду это",
    "keep the change!": "оставьте сдачу себе!",
    "cheers!": "за здоровье!",
    "whose round is it?": "чья очередь платить?",
    "it's my round": "моя очередь",
    "it's your round": "твоя очередь",
}