slovar = {
    "the day before yesterday": "позавчера",
    "yesterday": "вчера",
    "today": "сегодня",
    "tomorrow": "завтра",
    "the day after tomorrow": "послезавтра",
    "last night": "вчера вечером",
    "tonight": "сегодня вечером",
    "tomorrow night": "завтра вечером",
    "in the morning": "утром",
    "in the afternoon": "днем",
    "in the evening": "вечером",
    "yesterday morning": "вчера утром",
    "yesterday afternoon": "вчера днем",
    "yesterday evening": "вчера вечером",
    "this morning": "сегодня утром",
    "this afternoon": "сегодня днем",
    "this evening": "сегодня вечером",
    "tomorrow morning": "завтра утром",
    "tomorrow afternoon": "завтра днем",
    "tomorrow evening": "завтра вечером",
    "last week": "на прошлой неделе",
    "last month": "в прошлом месяце",
    "last year": "в прошлом году",
    "this week": "на этой неделе",
    "this month": "в этом месяце",
    "this year": "в этом году",
    "next week": "на следующей неделе",
    "next month": "в следующем месяце",
    "next year": "в следующем году",
    "five minutes ago": "пять минут назад",
    "an hour ago": "час назад",
    "a week ago": "неделю назад",
    "two weeks ago": "две недели назад",
    "a month ago": "месяц назад",
    "a year ago": "год назад",
    "a long time ago": "давным-давно",
    "in ten minutes' time": "через десять минут",
    "in ten minutes": "через десять минут",
    "in an hour's time": "через час",
    "in an hour": "через час",
    "in a week's time": "через неделю",
    "in a week": "через неделю",
    "in ten days' time": "через десять дней",
    "in ten days": "через десять дней",
    "in three weeks' time": "через три недели",
    "in three weeks": "через три недели",
    "in two months' time": "через два месяца",
    "in two months": "через два месяца",
    "in ten years' time": "через десять лет",
    "in ten years": "через десять лет",
    "the previous day": "в предыдущий день",
    "the previous week": "на предыдущей неделе",
    "the previous month": "в предыдущем месяце",
    "the previous year": "в предыдущем году",
    "the following day": "на следующий день",
    "the following week": "на следующей неделе",
    "the following month": "в следующем месяце",
    "the following year": "в следующем году",
    "_I lived in Canada for six months": "я жил в Канаде шесть месяцев",
    "I've worked here for nine years": "я работаю здесь девять лет",
    "I'm going to France tomorrow for two weeks": "завтра я уезжаю во Францию на две недели",
    "we were swimming for a long time": "мы долго плавали",
    "excuse me, could you tell me how to get to …?": "простите, вы не скажете как добраться до …?",
    "excuse me, could you tell me how to get to the bus station?": "простите, вы не скажете как добраться до автобусной станции?",
    "excuse me, do you know where the … is?": "простите, вы знаете где находится …?",
    "excuse me, do you know where the post office is?": "простите, вы знаете где находится почта?",
    "I'm sorry, I don't know": "извините, я не знаю",
    "sorry, I'm not from around here": "извините, я не местный",
    "I'm looking for …": "я ищу …",
    "I'm looking for this address": "я ищу этот адрес",
    "are we on the right road for …?": "мы на правильной дороге до …?",
    "are we on the right road for Brighton?": "мы на правильной дороге до Брайтон?",
    "Brighton": "это правильный путь до …?",
    "do you have a map?": "у вас есть карта?",
    "can you show me on the map?": "можете показать мне на карте?",
    "it's this way": "это сюда",
    "it's that way": "это туда",
    "you're going the wrong way": "вы двигаетесь неправильным путем",
    "you're going in the wrong direction": "вы двигаетесь в неправильном направлении",
    "take this road": "следуйте по этой дороге",
    "go down there": "идите туда",
    "take the first on the left": "поверните на первом повороте направо",
    "take the second on the right": "поверните на втором повороте направо",
    "turn right at the crossroads": "на перекрёстке поверните направо",
    "continue straight ahead for about a mile": "проедьте прямо еще примерно одну милю (одна миля — примерно 1,6 километра)",
    "continue past the fire station": "продолжайте двигаться после пожарной станции",
    "you'll pass a supermarket on your left": "слева будет супермаркет",
    "keep going for another …": "пройдите еще …",
    "keep going for another hundred yards": "пройдите еще сто ярдов (примерно 91 метр)",
    "keep going for another two hundred metres": "пройдите еще двести метров",
    "keep going for another half mile": "пройдите еще пол мили (примерно 800 метров)",
    "keep going for another kilometre": "пройдите еще километр",
    "it'll be …": "это будет …",
    "it'll be on your left": "это будет слева",
    "it'll be on your right": "это будет справа",
    "it'll be straight ahead of you": "это будет прямо",
    "how far is it?": "как далеко это находится?",
    "how far is it to …?": "как далеко до …?",
    "No entry": "Вход воспрещен",
}