slovar = {
    "what's the time?": "сколько времени?",
    "what time is it?": "который час?",
    "could you tell me the time, please?": "скажите, пожалуйста, сколько времени?",
    "do you happen to have the time?": "не подскажете который час?",
    "do you know what time it is?": "вы знаете сколько сейчас времени?",
    "it's …": "сейчас …",
    "it's exactly ...": "сейчас ровно ...",
    "it's about ...": "сейчас примерно ...",
    "it's almost ...": "сейчас почти ...",
    "it's just gone ...": "сейчас немного больше, чем ...",
    "one o'clock": "час",
    "two o'clock": "два часа",
    "three o'clock": "три часа",
    "four o'clock": "четыре часа",
    "five o'clock": "пять часов",
    "six o'clock": "шесть часов",
    "seven o'clock": "семь часов",
    "eight o'clock": "восемь часов",
    "ten o'clock": "десять часов",
    "eleven o'clock": "одиннадцать часов",
    "twelve o'clock": "двенадцать часов",
    "nine o'clock": "девять часов",
    "quarter past …": "четверть …",
    "quarter past one": "четверть второго",
    "quarter past two": "четверть третьего",
    "quarter past three": "четверть четвертого",
    "half past …": "половина …",
    "half past one": "половина второго",
    "half past two": "половина третьего",
    "half past three": "половина четвертого",
    "quarter to …": "без четверти …",
    "quarter to one": "без четверти час",
    "quarter to two": "без четверти два",
    "quarter to three": "без четверти три",
    "five past one": "пять минут второго",
    "ten past one": "десять минут второго",
    "twenty past one": "двадцать минут второго",
    "twenty-five past one": "двадцать пять минут второго",
    "five to two": "без пяти два",
    "ten to two": "без десяти два",
    "twenty to two": "без двадцати два",
    "twenty-five to two": "без двадцати пяти два",
    "ten fifteen": "десять часов пятнадцать минут",
    "ten thirty": "десять часов тридцать минут",
    "ten forty-five": "десять часов сорок пять минут",
    "ten am": "десять часов утра",
    "six pm": "шесть часов вечера",
    "noon": "полдень",
    "midday": "полдень",
    "midnight": "полночь",
    "11.47am": "11:47",
    "2.13pm": "14:13",
    "my watch is …": "мои наручные часы …",
    "my watch is fast": "мои наручные часы спешат",
    "my watch is slow": "мои наручные часы отстают",
    "that clock's a little …": "эти часы немного …",
    "that clock's a little fastя": "эти часы немного спешат",
    "that clock's a little slow": "эти часы немного отстают",
    "are you a student?": "ты студент?",
    "what do you study?": "что ты изучаешь?",
    "I'm studying …": "я изучаю …",
    "I'm studying history": "я изучаю историю",
    "I'm studying economics": "я изучаю экономику",
    "I'm studying medicine": "я изучаю медицину",
    "where do you study?": "где ты учишься?",
    "which university are you at?": "в каком университете ты учишься?",
    "what university do you go to?": "в каком университете ты учишься?",
    "I'm at …": "я учусь …",
    "I'm at Liverpool University": "я учусь в Ливерпульском университете",
    "which year are you in?": "на каком ты курсе?",
    "I'm in my … year": "я на … курсе",
    "I'm in my first year": "я на первом курсе",
    "I'm in my second year": "я на втором курсе",
    "I'm in my third year": "я на третьем курсе",
    "I'm in my final year": "я на последнем курсе",
    "I'm in my first year at university": "я учусь на первом курсе в университете",
    "do you have any exams coming up?": "у тебя будут скоро экзамены?",
    "I've just graduated": "я недавно закончил",
    "I'm doing a masters in …": "я в магистратуре по …",
    "I'm doing a masters in law": "я в магистратуре по юриспруденции",
    "law": "я в докторантуре по химии",
    "did you go to university?": "ты учился в университете?",
    "I didn't go to university": "я не учился в университете",
    "I never went to university": "я никогда не учился в университете",
    "where did you go to university?": "где ты учился в университете?",
    "I went to …": "я учился в …",
    "I went to Cambridge": "я учился в Кембридже",
    "what did you study?": "что ты изучал?",
    "I studied …": "я изучал …",
    "I studied maths": "я изучал математику",
    "I studied politics": "я изучал политологию",
    "where did you go to school?": "где ты учился в школе?",
    "I went to school in …": "я учился в школе в …",
    "I went to school in Bristol": "я учился в школе в Бристоле",
    "I left school at sixteen": "я ушел из школы в шестнадцать лет",
    "I'm taking a gap year": "у меня свободный от учебы год (год между окончанием школы и началом учебы в универсиете, обычно используемый для путешествий, волонтерской работы и т.д.)",
    "how many more years do you have to go?": "сколько лет тебе еще учиться?",
    "what do you want to do when you've finished?": "что ты собираешься делать, когда закончишь?",
    "get a job": "устроиться на работу",
    "go travelling": "путешествовать",
    "I don't know what I want to do after university": "я не знаю, что буду делать после университета",
}