slovar = {
    "44 BC — the death of Julius Caesar": "44 год до нашей эры — смерть Юлия Цезаря",
    "79 AD — eruption of Vesuvius": "79 год нашей эры — извержение Везувия",
    "what's the weather like?": "какая сейчас погода?",
    "it's sunny": "сейчас солнечно",
    "it's cloudy": "сейчас облачно",
    "it's windy": "сейчас ветренно",
    "it's foggy": "сейчас туман",
    "it's stormy": "сейчас буря",
    "it's raining": "сейчас идет дождь",
    "it's hailing": "сейчас идет град",
    "it's snowing": "сейчас идет снег",
    "what a nice day!": "какой чудесный день!",
    "what a beautiful day!": "какой прекрасный день!",
    "it's not a very nice day": "это не самый хороший день",
    "what a terrible day!": "какой ужасный день!",
    "what miserable weather!": "какая отвратительная погода!",
    "it's starting to rain": "начинается дождь",
    "it's stopped raining": "дождь закончился",
    "it's pouring with rain": "идет проливной дождь",
    "it's raining cats and dogs": "льет как из ведра",
    "the weather's fine": "отличная погода",
    "the sun's shining": "светит солнце",
    "there's not a cloud in the sky": "на небе ни облачка",
    "the sky's overcast": "небо затянуто облаками",
    "it's clearing up": "проясняется",
    "the sun's come out": "солнце вышло",
    "the sun's just gone in": "солнце зашло",
    "there's a strong wind": "дует сильный ветер",
    "the wind's dropped": "ветер прекратился",
    "that sounds like thunder": "похоже, гром гремит",
    "that's lightning": "молния сверкает",
    "we had a lot of heavy rain this morning": "этим утром шёл проливной дождь",
    "we haven't had any rain for a fortnight": "в течение двух недель не было дождя",
    "what's the temperature?": "какая сейчас температура?",
    "it's 22°C": "сейчас 22°C",
    "temperatures are in the mid-20s": "сейчас около двадцати пяти градусов",
    "what temperature do you think it is?": "как ты думаешь, какая сейчас температура?",
    "probably about 30°C": "возможно около 30°C",
    "it's hot": "сейчас жарко",
    "it's cold": "сейчас холодно",
    "it's baking hot": "сейчас очень жарко",
    "it's freezing": "сейчас очень холодно",
    "it's freezing cold": "сейчас очень холодно",
    "it's below freezing": "минусовая темрпература",
    "what's the forecast?": "какой прогноз погоды?",
    "what's the forecast like?": "какой прогноз погоды?",
    "it's forecast to rain": "будет дождь",
    "it's going to freeze tonight": "ночью будут заморозки",
    "it looks like rain": "похоже, что будет дождь",
    "it looks like it's going to rain": "похоже, что будет дождь",
    "we're expecting a thunderstorm": "ожидается буря",
    "it's supposed to clear up later": "скоро должно проясниться",
    "would anyone like a tea or coffee?": "кто-нибудь хочет чай или кофе?",
    "would anyone like a cup of tea?": "кто-нибудь хочет чашку чая?",
    "what's her name?": "как ее зовут?",
    "she's called …": "ее зовут …",
    "she's called Mary": "ее зовут Мери",
    "what are their names?": "как их зовут?",
    "they're called …": "их зовут …",
    "they're called Neil and Anna": "их зовут Нейл и Анна",
    "how old is he?": "сколько ему лет?",
    "he's …": "ему …",
    "he's twelve": "ему двенадцать",
    "how old is she?": "сколько ей лет?",
    "she's …": "ей …",
    "she's fifteen": "ей пятнадцать",
    "how old are they?": "сколько им лет?",
    "they're …": "им …",
    "they're six and eight": "им шесть и восемь",
    "I'm at Peter's": "я у Питера",
    "are you up to anything this evening?": "у тебя уже есть планы на вечер?",
    "have you got any plans for …?": "у тебя есть планы на …?",
    "have you got any plans for this evening?": "у тебя есть планы на этот вечер?",
    "have you got any plans for tomorrow?": "у тебя есть планы на завтра?",
    "have you got any plans for the weekend?": "у тебя есть планы на выходные?",
    "are you free …?": "ты свободен …?",
    "are you free this evening?": "ты свободен сегодня вечером?",
    "are you free tomorrow afternoon?": "ты свободен завтра днем?",
    "are you free tomorrow evening?": "ты свободен завтра вечером?",
    "what would you like to do this evening?": "чем бы ты хотел заняться сегодня вечером?",
    "do you want to go somewhere at the weekend?": "ты хочешь куда-нибудь поехать на выходных?",
    "would you like to join me for something to eat?": "ты хочешь вместе со мной поесть?",
    "do you fancy going out tonight?": "хочешь прогуляться сегодня вечером?",
    "what's your name?": "как тебя зовут?",
    "my name's Chris": "меня зовут Крис",
    "my name's Emily": "меня зовут Эмили",
    "I'm Ben": "я Бен",
    "I'm Sophie": "я Софи",
    "this is …": "это …",
    "this is Lucy": "это Люси",
    "this is my wife": "это моя жена",
    "this is my husband": "это мой муж",
    "this is my boyfriend": "это мой друг",
    "this is my girlfriend": "это моя подруга",
    "this is my son": "это мой сын",
    "this is my daughter": "это моя дочь",
    "I'm sorry, I didn't catch your name": "извини, я не расслышал как тебя зовут",
    "do you know each other?": "вы знакомы?",
    "nice to meet you": "рад познакомиться",
    "pleased to meet you": "приятно познакомиться",
    "how do you do?": "очень приятно (фраза обычно используется при знакомстве; вежливый ответ — how do you do?)",
    "how do you know each other?": "как вы познакомились?",
    "we work together": "мы вместе работаем",
    "we used to work together": "мы вместе работали",
    "we were at school together": "мы вместе учились в школе",
    "we're at university together": "мы вместе учимся в университете",
    "we went to university together": "мы вместе учились в университете",
    "through friends": "через друзей",
}