slovar = {
    "excuse me, could you tell me how to get to …?": "простите, вы не скажете как добраться до …?",
    "excuse me, could you tell me how to get to the bus station?": "простите, вы не скажете как добраться до автобусной станции?",
    "excuse me, do you know where the … is?": "простите, вы знаете где находится …?",
    "excuse me, do you know where the post office is?": "простите, вы знаете где находится почта?",
    "I'm sorry, I don't know": "извините, я не знаю",
    "sorry, I'm not from around here": "извините, я не местный",
    "I'm looking for …": "я ищу …",
    "I'm looking for this address": "я ищу этот адрес",
    "are we on the right road for …?": "мы на правильной дороге до …?",
    "are we on the right road for Brighton?": "мы на правильной дороге до Брайтон?",
    "Brighton": "это правильный путь до …?",
    "do you have a map?": "у вас есть карта?",
    "can you show me on the map?": "можете показать мне на карте?",
    "it's this way": "это сюда",
    "it's that way": "это туда",
    "you're going the wrong way": "вы двигаетесь неправильным путем",
    "you're going in the wrong direction": "вы двигаетесь в неправильном направлении",
    "take this road": "следуйте по этой дороге",
    "go down there": "идите туда",
    "take the first on the left": "поверните на первом повороте направо",
    "take the second on the right": "поверните на втором повороте направо",
    "turn right at the crossroads": "на перекрёстке поверните направо",
    "continue straight ahead for about a mile": "проедьте прямо еще примерно одну милю (одна миля — примерно 1,6 километра)",
    "continue past the fire station": "продолжайте двигаться после пожарной станции",
    "you'll pass a supermarket on your left": "слева будет супермаркет",
    "keep going for another …": "пройдите еще …",
    "keep going for another hundred yards": "пройдите еще сто ярдов (примерно 91 метр)",
    "keep going for another two hundred metres": "пройдите еще двести метров",
    "keep going for another half mile": "пройдите еще пол мили (примерно 800 метров)",
    "keep going for another kilometre": "пройдите еще километр",
    "it'll be …": "это будет …",
    "it'll be on your left": "это будет слева",
    "it'll be on your right": "это будет справа",
    "it'll be straight ahead of you": "это будет прямо",
    "how far is it?": "как далеко это находится?",
    "how far is it to …?": "как далеко до …?",
    "how far is it to the airport?": "как далеко до аэропорта?",
    "how far is it to … from here?": "как далеко до … отсюда?",
    "how far is it to the beach from here?": "скак далеко до пляжа отсюда?",
    "is it far?": "это далеко?",
    "is it a long way?": "это долгий путь?",
    "it's …": "это …",
    "it's not far": "это недалеко",
    "it's quite close": "это довольно близко",
    "it's quite a long way": "это довольно далеко",
    "it's a long way on foot": "это довольно далеко",
    "it's a long way to walk": "это долгий путь пешком",
    "it's about a mile from here": "это около мили отсюда (одна миля — примерно 1,6 километра)",
    "follow the signs for …": "следуйте указателям для …",
    "follow the signs for the town centre": "следуйте указателям для центра города",
    "follow the signs for Birmingham": "следуйте указателям для Бирменгема",
    "continue straight on past some traffic lights": "после светофора продолжайте прямо",
    "at the second set of traffic lights, turn left": "на втором светофоре поверните налево",
    "go over the roundabout": "проедьте по кольцу",
    "take the second exit at the roundabout": "на кольце воспользуйтесь вторым выездом",
    "turn right at the T-junction": "поверните направо на Т-образном перекрестке",
    "go under the bridge": "проедьте под мостом",
    "go over the bridge": "проедьте по мосту",
    "you'll cross some railway lines": "вы проедете через железнодорожный переезд",
    "where's the ticket office?": "где находятся кассы?",
    "where do I get the … to Southampton from?": "откуда отправляется … на Саусэмптон?",
    "where do I get the bus to Southampton from?": "откуда отправляется автобус на Саусэмптон?",
    "where do I get the train to Southampton from?": "откуда отправляется поезд на Саусэмптон?",
    "where do I get the ferry to Southampton from?": "откуда отправляется паром на Саусэмптон?",
    "what time's the next … to Portsmouth?": "во сколько следующий … на Портмут?",
    "what time's the next bus to Portsmouth?": "во сколько следующий автобус на Портмут?",
    "what time's the next train to Portsmouth?": "во сколько следующий поезд на Портмут?",
    "what time's the next ferry to Portsmouth?": "во сколько следующий паром на Портмут?",
    "this … has been cancelled": "этот … отменили",
    "this bus has been cancelled": "этот автобус отменили",
    "this train has been cancelled": "этот поезд отменили",
    "this flight has been cancelled": "этот рейс (вылет) отменили",
    "this ferry has been cancelled": "этот паром отменили",
    "this … has been delayed": "этот … задерживается",
    "this bus has been delayed": "этот автобус задерживается",
    "this train has been delayed": "этот поезд задерживается",
    "this flight has been delayed": "этот рейс (вылет) задерживается",
    "this ferry has been delayed": "этот паром задерживается",
    "have you ever been to …?": "ты когда-нибудь был в …?",
    "have you ever been to Italy?": "ты когда-нибудь был в Италии?",
    "yes, I went there on holiday": "да, я ездил туда в отпуск",
    "no, I've never been there": "нет, я никогда там не был",
    "I've never been, but I'd love to go someday": "никогда там не был, но очень хочу съездить",
    "how long does the journey take?": "как долго продлится путешествие?",
    "what time do we arrive?": "во сколько мы прибываем?",
    "do you get travel sick?": "тебе становится плохо в дороге?",
    "have a good journey!": "хорошей поездки!",
    "enjoy your trip!": "хорошего путешествия!",
    "I'd like to travel to …": "я хотел бы поехать в …",
    "I'd like to travel to Spain": "я хотел бы поехать в Испанию",
    "I'd like to book a trip to …": "я хотел бы забронировать путевку в …",
    "I'd like to book a trip to Berlin": "я хотел бы забронировать путевку в Берлин",
    "how much are the flights?": "сколько стоит перелет?",
    "do you have any brochures on …?": "у вас есть какие-нибудь брошюры о …?",
    "do you have any brochures on Switzerland?": "у вас есть какие-нибудь брошюры о Швейцарии?",
    "do I need a visa for …?": "мне нужна виза в …?",
    "do I need a visa for Turkey?": "мне нужна виза в Турцию?",
    "where would you like to meet?": "где ты хотел бы встретиться?",
    "I'll see you … at ten o'clock": "увидимся … в десять часов",
    "I'll see you in the pub at ten o'clock": "увидимся в пабе в десять часов",
    "I'll see you at the cinema at ten o'clock": "увидимся в кино в десять часов",
    "I'll meet you there": "встретимся там",
    "see you there!": "увидимся там!",
}