slovar = {
    "what's the last date I can post this to … to arrive in time for Christmas?": "какой последний день для отправки этого в …, чтобы вовремя дошло на Рождество?",
    "what's the last date I can post this to Germany to arrive in time for Christmas?": "какой последний день для отправки этого в Германию, чтобы вовремя дошло на Рождество?",
    "what's the last date I can post this to Australia to arrive in time for Christmas?": "какой последний день для отправки этого в Австралию, чтобы вовремя дошло на Рождество?",
    "I've come to collect a parcel": "я пришел забрать посылку",
    "I'd like to pay this bill": "я хотел бы оплатить этот счет",
    "I'd like to send some money to …": "я хотел бы переслать деньги в …",
    "I'd like to send some money to Poland": "я хотел бы переслать деньги в Польшу",
    "I'd like to send some money to India": "я хотел бы переслать деньги в Индию",
    "do you sell …?": "вы продаёте …?",
    "do you sell postcards?": "вы продаёте открытки?",
    "do you sell birthday cards?": "вы продаёте поздравительные открытки?",
    "do you sell Christmas cards?": "вы продаёте рождественские открытки?",
    "can you fill in this form, please?": "заполните этот бланк, пожалуйста",
    "do you have a …?": "у вас есть …?",
    "do you have a photo booth?": "у вас есть фотобудка?",
    "do you have a photocopier?": "у вас есть копировальный аппарат?",
    "First class": "Первый класс",
    "Second class": "Второй класс",
    "International": "Международный",
    "Airmail": "Авиапочта",
    "we're looking for accommodation": "мы ищем где остановиться",
    "we need somewhere to stay": "нам надо где-то остановиться",
    "do you have a list of …?": "у вас есть список …?",
    "do you have a list of hotels?": "у вас есть список гостиниц?",
    "do you have a list of B&Bs?": "у вас есть список B&Bs?",
    "do you have a list of youth hostels?": "у вас есть список молодежных хостелов?",
    "do you have a list of campsites?": "у вас есть список мест для кемпинга?",
    "what sort of accommodation are you looking for?": "какой тип жилья вы ищите?",
    "can you book accommodation for me?": "вы могли бы забронировть жильё для меня?",
    "do you have a map of the …?": "у вас есть карта …?",
    "do you have a map of the city?": "у вас есть карта города (большой город)?",
    "do you have a map of the town?": "у вас есть карта города (небольшой или маленький город)?",
    "where's the …?": "где находится …?",
    "where's the city centre?": "где находится центр города?",
    "where's the art gallery?": "где находится художественная галерея?",
    "where's the museum?": "где находится музей?",
    "where's the main shopping area?": "где находится главный торговый квартал?",
    "where's the market?": "где находится рынок?",
    "where's the railway station?": "где находится железнодорожная станция?",
    "what's the best way of getting around the city?": "какой самый лучший маршрут по городу?",
    "where can I hire a car?": "где я могу взять на прокат автомобиль?",
    "what are you interested in?": "что вас интересует?",
    "are there any … on at the moment?": "тут сейчас проходят какие-нибудь …?",
    "are there any exhibitions on at the moment?": "тут сейчас проходят какие-нибудь выставки?",
    "are there any cultural events on at the moment?": "тут сейчас проходят какие-нибудь культурные мероприятия?",
    "are there any sporting events on at the moment?": "тут сейчас проходят какие-нибудь спортивные мероприятия?",
    "are there any …?": "есть ли какие-нибудь …?",
    "are there any excursions?": "есть ли какие-нибудь экскурсии?",
    "are there any tours?": "есть ли какие-нибудь туры?",
    "are there any day trips?": "есть ли какие-нибудь дневные путешествия?",
    "is there a city tour?": "есть ли тур по городу?",
    "could you tell us what's on at the …?": "могли бы вы сказать, что идёт в …?",
    "could you tell us what's on at the cinema?": "могли бы вы сказать, что идёт в кино?",
    "could you tell us what's on at the theatre?": "могли бы вы сказать, что идёт в театре?",
    "could you tell us what's on at the concert hall?": "могли бы вы сказать, что идёт в концертном зале?",
    "could you tell us what's on at the opera house?": "могли бы вы сказать, что идёт в опере?",
    "can I book tickets here?": "могу я заказать тут билеты?",
    "do you have any brochures on …?": "у вас есть какие-нибудь брошюры о …?",
    "do you have any brochures on local attractions?": "у вас есть какие-нибудь брошюры о местных развлечениях?",
    "can you recommend a good restaurant?": "вы можете порекоммендовать хороший ресторан?",
    "where can I get a taxi?": "где я могу поймать такси?",
    "excuse me, where's …?": "извините, где находится …?",
    "excuse me, where's the tourist information office?": "извините, где находится пункт туристической информации?",
    "excuse me, where's the bus station?": "извините, где находится автобусная станция?",
    "excuse me, where's the train station?": "извините, где находится железнодорожная станция?",
    "excuse me, where's the police station?": "извините, где находится полицейский участок?",
    "excuse me, where's the harbour?": "извините, где находится порт?",
    "is there a … near here?": "есть ли тут неподалёку …?",
    "is there a cashpoint near here?": "есть ли тут неподалёку банкомат?",
    "is there a bank near here?": "есть ли тут неподалёку банк?",
    "is there a supermarket near here?": "есть ли тут неподалёку супермаркет?",
    "is there a hairdressers near here?": "есть ли тут неподалёку парикмахерская?",
    "is there a chemists near here?": "есть ли тут неподалёку аптека?",
    "do you know where there's an internet café?": "вы не знаете, где здесь интернет-кафе?",
    "do you know where the … embassy is?": "вы знаете, где находится … посольство?",
    "do you know where the Japanese embassy is?": "вы знаете, где находится японское посольство?",
    "do you know where the Russian embassy is?": "вы знаете, где находится российское посольство?",
    "Town centre": "Центр города",
    "Bus stop": "Автобусная остановка",
    "Taxis": "Такси",
    "Underground": "Метро",
    "Hospital": "Больница",
    "Public library": "Публичная библиотека",
    "Post office": "Почта",
    "Keep off the grass": "По траве не ходить",
    "Wet paint": "Окрашено",
    "Look left": "Посмотрите налево",
    "Look right": "Посмотрите направо",
    "do you know where I can get my … repaired?": "вы не знаете, где я могу отремонтировать …?",
    "do you know where I can get my phone repaired?": "вы не знаете, где я могу отремонтировать телефон?",
    "do you know where I can get my watch repaired?": "вы не знаете, где я могу отремонтировать часы?",
    "do you know where I can get my camera repaired?": "вы не знаете, где я могу отремонтировать фотоаппарат?",
    "do you know where I can get my shoes repaired?": "вы не знаете, где я могу отремонтировать обувь?",
    "the screen’s broken": "экран треснул",
    "there's something wrong with …": "что-то не в порядке с …",
    "there's something wrong with my watch": "что-то не в порядке с моими часами",
    "there's something wrong with this radio": "что-то не в порядке с этим радио",
    "do you do … repairs?": "вы ремонтируете …?",
    "do you do television repairs?": "вы ремонтируете телевизоры?",
    "do you do computer repairs?": "вы ремонтируете компьютеры?",
    "do you do laptop repairs?": "вы ремонтируете ноутбуком?",
    "how much will it cost?": "сколько это будет стоить?",
    "when will it be ready?": "когда это будет готово?",
    "how long will it take?": "сколько на это потребуется времени?",
    "I can do it straight away": "я могу это сразу сделать",
    "it'll be ready …": "это будет готово …",
    "it'll be ready by tomorrow": "это будет готово завтра",
    "it'll be ready next week": "это будет готово на следующей неделе",
    "I won't be able to do it for at least two weeks": "я не смогу это сделать ещё по меньшей мере две недели",
    "are you able to repair it?": "вы можете это отремонтировать?",
    "we can't do it here": "мы не можем это здесь сделать",
    "we're going to have to send it back to the manufacturers": "мы собираемся отправить это обратно изготовителю",
    "it's not worth repairing": "это не стоит ремонта",
    "my watch has stopped": "мои часы остановились",
    "can I have a look at it?": "могу я посмотреть?",
    "I think it needs a new battery": "я думаю, нужна новая батарейка",
}