slovar = {
    "what's your name?": "как тебя зовут?",
    "my name's …": "меня зовут …",
    "my name's Chris": "меня зовут Крис",
    "my name's Emily": "меня зовут Эмили",
    "I'm …": "я …",
    "I'm Ben": "я Бен",
    "I'm Sophie": "я Софи",
    "this is …": "это …",
    "this is Lucy": "это Люси",
    "this is my wife": "это моя жена",
    "this is my husband": "это мой муж",
    "this is my boyfriend": "это мой друг",
    "this is my girlfriend": "это моя подруга",
    "this is my son": "это мой сын",
    "this is my daughter": "это моя дочь",
    "I'm sorry, I didn't catch your name": "извини, я не расслышал как тебя зовут",
    "do you know each other?": "вы знакомы?",
    "nice to meet you": "рад познакомиться",
    "pleased to meet you": "приятно познакомиться",
    "how do you do?": "очень приятно (фраза обычно используется при знакомстве; вежливый ответ — how do you do?)",
    "how do you know each other?": "как вы познакомились?",
    "we work together": "мы вместе работаем",
    "we used to work together": "мы вместе работали",
    "we were at school together": "мы вместе учились в школе",
    "we're at university together": "мы вместе учимся в университете",
    "we went to university together": "мы вместе учились в университете",
    "through friends": "через друзей",
    "where are you from?": "откуда ты?",
    "where do you come from?": "откуда ты?",
    "whereabouts are you from?": "из каких ты мест?",
    "I'm from …": "я из …",
    "I'm from England": "я из Англии",
    "whereabouts in … are you from?": "откуда в … ты?",
    "whereabouts in Canada are you from?": "откуда в Канаде ты?",
    "what part of … do you come from?": "из какой части … ты?",
    "what part of Italy do you come from?": "из какой части Италии ты?",
    "where do you live?": "где ты живешь?",
    "I live in …": "я живу …",
    "I live in London": "я живу в Лондоне",
    "I live in France": "я живу во Франции",
    "I'm originally from Dublin but now live in Edinburgh": "я на самом деле из Дублина, но сейчас живу в Эдинбурге",
    "I was born in Australia but grew up in England": "я родился в Австралии, но вырос в Англии",
    "what brings you to …?": "как ты оказался …?",
    "what brings you to England?": "как ты оказался в Англии?",
    "I'm on holiday": "я в отпуске",
    "I'm on business": "я по работе",
    "I live here": "я живу здесь",
    "I work here": "я работаю здесь",
    "I study here": "я учусь здесь",
    "why did you come to …?": "для чего ты приехал …?",
    "why did you come to the UK?": "для чего ты приехал в Великобританию?",
    "the UK": "я приехал работать",
    "I came here to study": "я приехал учиться",
    "I wanted to live abroad": "я хотел жить заграницей",
    "how long have you lived here?": "как долго ты здесь живешь?",
    "I've only just arrived": "недавно приехал",
    "about a year": "около года",
    "just over two years": "чуть больше двух лет",
    "three years": "три года",
    "how long are you planning to stay here?": "как долго ты собираешься здесь оставаться?",
    "until August": "до августа",
    "a few months": "несколько месяцев",
    "another year": "еще год",
    "I'm not sure": "я точно не знаю",
    "do you like it here?": "тебе здесь нравится?",
    "yes, I love it!": "да, очень нравится!",
    "I like it a lot": "очень нравится",
    "it's OK": "нормально",
    "what do you like about it?": "что тебе здесь нравится?",
    "I like the …": "мне нравится/нравятся …",
    "I like the food": "мне нравится/нравятся еда",
    "I like the weather": "мне нравится/нравятся погода",
    "I like the people": "мне нравится/нравятся люди",
    "how old are you?": "сколько тебе лет?",
    "I'm twenty-two": "мне двадцать два",
    "I'm thirty-eight": "мне тридцать восемь",
    "when's your birthday?": "когда у тебя день рождения?",
    "it's …": "он …",
    "it's 16 May": "он 16 мая",
    "it's 2 October": "он 2 октября",
    "who do you live with?": "с кем ты живешь?",
    "do you live with anybody?": "ты живешь с кем-то?",
    "I live with …": "я живу …",
    "I live with my boyfriend": "я живу со своим другом",
    "I live with my girlfriend": "я живу со своей подругой",
    "I live with my partner": "я живу со своим сожителем",
    "I live with my husband": "я живу со своим мужем",
    "I live with my wife": "я живу со своей женой",
    "I live with my parents": "я живу со своими родителями",
    "I live with a friend": "я живу с другом",
    "I live with friends": "я живу с друзьями",
    "I live with relatives": "я живу с родственниками",
    "do you live on your own?": "ты живешь отдельно?",
    "I live on my own": "я живу отдельно",
}