slovar = {
    "what's the problem?": "в чем проблема?",
    "what are your symptoms?": "какие у вас симптомы?",
    "I've got a …": "у меня …",
    "I've got a temperature": "у меня температура",
    "I've got a sore throat": "у меня болит горло",
    "I've been feeling sick": "меня тошнило",
    "I've been having headaches": "у меня болела голова",
    "I'm very congested": "у меня мокрота в легких и насморк",
    "my joints are aching": "у меня болят суставы",
    "I've got diarrhoea": "у меня понос",
    "I'm constipated": "у меня запор",
    "I've got a lump": "у меня опухоль",
    "I've got a swollen …": "у меня опухла …",
    "I've got a swollen ankle": "у меня опухла лодыжка000",
    "I'm in a lot of pain": "у меня очень сильная боль",
    "I've got a pain in my back": "у меня боль в спине",
    "I've got a pain in my chest": "у меня боль в груди",
    "I think I've pulled a muscle in my leg": "я думаю, что растянул мышцу на ноге",
    "I'm asthmatic": "я астматик",
    "I'm diabetic": "я диабетик",
    "I'm epileptic": "я эпилептик",
    "I need …": "мне нужен …",
    "I need another inhaler": "мне нужен ингалятор",
    "I need some more insulin": "мне нужен еще инсулин",
    "I'm having difficulty breathing": "мне трудно дышать",
    "I've got very little energy": "я очень слаб",
    "I've been feeling very tired": "я чувствую большую усталость",
    "I've been feeling depressed": "я чувствую себя подавленным",
    "I've been having difficulty sleeping": "у меня проблемы со сном",
    "how long have you been feeling like this?": "как долго вы уже себя так чувствуете?",
    "how have you been feeling generally?": "как вы вообще себя чувствуете?",
    "is there any possibility you might be pregnant?": "допустимо ли, что вы беременны?",
    "I think I might be pregnant": "я думаю, я беременна",
    "do you have any allergies?": "у вас есть на что-либо аллергия?",
    "I'm allergic to antibiotics": "у меня аллергия на антибиотики",
    "are you on any sort of medication?": "вы принимаете какие-либо лекарства?",
    "I need a sick note": "мне нужна справка о болезни",
    "can I have a look?": "могу я взглянуть?",
    "where does it hurt?": "где болит?",
    "it hurts here": "здесь болит",
    "does it hurt when I press here?": "вам больно, когда я сюда нажимаю?",
    "I'm going to take your …": "я собираюсь измерить …",
    "I'm going to take your blood pressure": "я собираюсь измерить кровяное давление",
    "I'm going to take your temperature": "я собираюсь измерить температуру",
    "I'm going to take your pulse": "я собираюсь измерить пульс",
    "could you roll up your sleeve?": "закатайте рукав",
    "your blood pressure's …": "ваше кровяное давление …",
    "your blood pressure's quite low": "ваше кровяное давление довольно низкое",
    "your blood pressure's normal": "ваше кровяное давление в норме",
    "your blood pressure's rather high": "ваше кровяное давление немного повышено",
    "your blood pressure's very high": "ваше кровяное давление очень высокое",
    "your temperature's …": "ваша температура …",
    "your temperature's normal": "ваша температура нормальная",
    "your temperature's a little high": "ваша температура немного повышена",
    "your temperature's very high": "ваша температура очень высокое",
    "open your mouth, please": "откройте, пожалуйста, рот",
    "cough, please": "покашляйте, пожалуйста",
    "you're going to need a few stiches": "вам придется нанести несколько швов",
    "I'm going to give you an injection": "я собираюсь сделать вам укол",
    "we need to take a …": "нам нужно взять …",
    "we need to take a urine sample": "нам нужно взять анализ мочи",
    "we need to take a blood sample": "нам нужно взять анализ крови",
    "you need to have a blood test": "вы должны сделать анализ крови",
    "I'm going to prescribe you some antibiotics": "я собираюсь выписать вам антибиотики",
    "take two of these pills three times a day": "принимайте по две таблетки три раза в день",
    "take this prescription to the chemist": "возьмите этот рецепт",
    "you should stop smoking": "вы должны бросить курить",
    "how much alcohol do you drink a week?": "сколько алкоголя вы потребляете в неделю?",
    "you should cut down on your drinking": "вы должны бросить пить",
    "you need to try and lose some weight": "вы должны постарвться сбросить немного вес",
    "I want to send you for an x-ray": "я хочу отправить вас на рентген",
    "I want you to see a specialist": "я хочу, чтобы вы посетили специалиста",
    "I'd like some toothpaste": "мне нужна зубная паста",
    "I'd like some paracetamol": "мне нужна парацетамол",
    "I've got a prescription here from the doctor": "у меня есть рецепт от врача",
    "have you got anything for …?": "у вас что-нибудь от …?",
    "have you got anything for cold sores?": "у вас что-нибудь от герписа?",
    "have you got anything for a sore throat?": "у вас что-нибудь от боли в горле?",
    "have you got anything for chapped lips?": "у вас что-нибудь от обветренных губ?",
    "have you got anything for a cough?": "у вас что-нибудь от кашля?",
    "have you got anything for travel sickness?": "у вас что-нибудь от укачивания?",
    "have you got anything for athlete's foot?": "у вас что-нибудь от ножного грибка?",
    "can you recommend anything for a cold?": "вы можете что-нибудь порекомендовать от простуды?",
    "I'm suffering from …": "я страдаю от …",
    "I'm suffering from hay fever": "я страдаю от сенной аллергии",
    "I'm suffering from indigestion": "я страдаю от несварения желудка",
    "I'm suffering from diarrhoea": "я страдаю от диареи",
    "I've got a rash": "у меня сыпь",
    "you could try this cream": "вы можете попробовать этот крем",
    "if it doesn't clear up after a week, you should see your doctor": "если это не пройдет в течение недели, вы должны обратиться к врачу",
    "have you got anything to help me stop smoking?": "у вас есть что-нибудь, чтобы помочь мне бросить курить?",
    "have you tried nicotine patches?": "вы пробовали никотиновые пластыри?",
    "can I buy this without a prescription?": "могу я это купить без рецепта?",
    "it's only available on prescription": "это можно купить только с рецептом",
    "does it have any side-effects?": "есть ли какие-нибудь побочные эффекты?",
    "it can make you feel drowsy": "вы можете почувствовать сонливость",
    "you should avoid alcohol": "вам следует воздержаться от алкоголя",
    "I'd like to speak to the pharmacist, please": "я хотел бы поговорить с аптекарем, пожалуйста",
    "I'm not feeling well": "я нехорошо себя чувствую",
    "I'm not feeling very well": "я нехорошо себя чувствую",
    "I feel ill": "я заболел",
    "I feel sick": "меня тошнит",
    "I've cut myself": "я порезался",
    "I've got a headache": "у меня болит голова",
    "I've got a splitting headache": "у меня ужасная головная боль",
    "I'm not well": "мне нехорошо",
    "I've got flu": "у меня грип",
    "I'm going to be sick": "меня тошнит",
    "I've been sick": "меня тошнило",
    "I've got a pain in my …": "у меня болит …",
    "I've got a pain in my neck": "у меня болит шея",
}