slovar = {
    "are you a student?": "ты студент?",
    "what do you study?": "что ты изучаешь?",
    "I'm studying …": "я изучаю …",
    "I'm studying history": "я изучаю историю",
    "I'm studying economics": "я изучаю экономику",
    "I'm studying medicine": "я изучаю медицину",
    "where do you study?": "где ты учишься?",
    "which university are you at?": "в каком университете ты учишься?",
    "what university do you go to?": "в каком университете ты учишься?",
    "I'm at …": "я учусь …",
    "I'm at Liverpool University": "я учусь в Ливерпульском университете",
    "which year are you in?": "на каком ты курсе?",
    "I'm in my … year": "я на … курсе",
    "I'm in my first year": "я на первом курсе",
    "I'm in my second year": "я на втором курсе",
    "I'm in my third year": "я на третьем курсе",
    "I'm in my final year": "я на последнем курсе",
    "I'm in my first year at university": "я учусь на первом курсе в университете",
    "do you have any exams coming up?": "у тебя будут скоро экзамены?",
    "I've just graduated": "я недавно закончил",
    "I'm doing a masters in …": "я в магистратуре по …",
    "I'm doing a masters in law": "я в магистратуре по юриспруденции",
    "law": "я в докторантуре по химии",
    "did you go to university?": "ты учился в университете?",
    "I didn't go to university": "я не учился в университете",
    "I never went to university": "я никогда не учился в университете",
    "where did you go to university?": "где ты учился в университете?",
    "I went to …": "я учился в …",
    "I went to Cambridge": "я учился в Кембридже",
    "what did you study?": "что ты изучал?",
    "I studied …": "я изучал …",
    "I studied maths": "я изучал математику",
    "I studied politics": "я изучал политологию",
    "where did you go to school?": "где ты учился в школе?",
    "I went to school in …": "я учился в школе в …",
    "I went to school in Bristol": "я учился в школе в Бристоле",
    "I left school at sixteen": "я ушел из школы в шестнадцать лет",
    "I'm taking a gap year": "у меня свободный от учебы год (год между окончанием школы и началом учебы в универсиете, обычно используемый для путешествий, волонтерской работы и т.д.)",
    "how many more years do you have to go?": "сколько лет тебе еще учиться?",
    "what do you want to do when you've finished?": "что ты собираешься делать, когда закончишь?",
    "get a job": "устроиться на работу",
    "go travelling": "путешествовать",
    "I don't know what I want to do after university": "я не знаю, что буду делать после университета",
}