slovar = {
    "I can't find my keys": "я не могу найти мои ключи",
    "I can't find my passport": "я не могу найти мой паспорт",
    "I can't find my mobile": "я не могу найти мой мобильный телефон",
    "I've lost my …": "я потерял …",
    "I've lost my wallet": "я потерял мой кошелек",
    "I've lost my purse": "я потерял мой бумажник",
    "I've lost my camera": "я потерял мой фотоаппарат",
    "I've locked myself out of my …": "моя … закрылась, а ключи внутри",
    "I've locked myself out of my car": "моя машина закрылась, а ключи внутри",
    "I've locked myself out of my room": "моя комната закрылась, а ключи внутри",
    "please leave me alone": "пожалуйста, оставьте меня в покое",
    "go away!": "уйдите!",
    "yes": "да",
    "no": "нет",
    "maybe": "может быть",
    "perhaps": "может быть",
    "please": "пожалуйста",
    "thanks": "спасибо",
    "thank you": "спасибо",
    "thanks very much": "большое спасибо",
    "thank you very much": "большое спасибо",
    "you're welcome": "пожалуйста",
    "don't mention it": "не за что",
    "not at all": "не стоит благодарности",
    "hi": "привет (дружеское)",
    "hello": "здравствуйте",
    "good morning": "доброе утро (используется до полудня)",
    "good afternoon": "добрый день (используется с полудня до 6 часов вечера)",
    "good evening": "добрый вечер (используется после 6 часов вечера)",
    "bye": "пока",
    "goodbye": "до свидания",
    "goodnight": "спокойной ночи",
    "see you!": "увидимся!",
    "see you soon!": "до скорого!",
    "see you later!": "увидимся!",
    "have a nice day!": "хорошего дня!",
    "have a good weekend!": "хороших выходных!",
    "excuse me": "простите (может использоваться для привлечения внимания или при извинении)",
    "sorry": "извините",
    "no problem": "ничего страшного",
    "that's OK": "все в порядке",
    "don't worry about it": "не стоит беспокойства",
    "do you speak English?": "вы говорите по-английски?",
    "I don't speak English": "я не говорю по-английски",
    "I don't speak much English": "я не очень хорошо говорю по-английски",
    "I only speak very little English": "я только чуть-чуть говорю по-английски",
    "I speak a little English": "я немного говорю по-английски",
    "please speak more slowly": "пожалуйста, говорите медленнее",
    "please write it down": "пожалуйста, напишите это",
    "I understand": "я понимаю",
    "I don't understand": "я не понимаю",
    "I know": "я знаю",
    "I don't know": "я не знаю",
    "excuse me, where's the toilet?": "извините, где находится туалет?",
    "excuse me, where's the Gents?": "извините, где мужской туалет?",
    "excuse me, where's the Ladies?": "извините, где женский туалет?",
    "Entrance": "Вход",
    "Exit": "Выход",
    "Emergency exit": "Запасной выход",
    "Push": "От себя",
    "Pull": "На себя",
    "WC": "Туалет",
    "Gentlemen": "Мужчины",
    "Gents": "Мужчины",
    "Ladies": "Женщины",
    "Vacant": "Свободно",
    "Occupied": "Занято",
    "Engaged": "Занято",
    "Out of order": "Не работает",
    "Private": "Частная собственность",
    "the day before yesterday": "позавчера",
    "yesterday": "вчера",
    "today": "сегодня",
    "tomorrow": "завтра",
    "the day after tomorrow": "послезавтра",
    "last night": "вчера вечером",
    "tonight": "сегодня вечером",
    "tomorrow night": "завтра вечером",
    "in the morning": "утром",
    "in the afternoon": "днем",
    "in the evening": "вечером",
    "yesterday morning": "вчера утром",
    "yesterday afternoon": "вчера днем",
    "yesterday evening": "вчера вечером",
    "this morning": "сегодня утром",
    "this afternoon": "сегодня днем",
    "this evening": "сегодня вечером",
    "tomorrow morning": "завтра утром",
    "tomorrow afternoon": "завтра днем",
    "tomorrow evening": "завтра вечером",
    "last week": "на прошлой неделе",
    "last month": "в прошлом месяце",
    "last year": "в прошлом году",
    "this week": "на этой неделе",
    "this month": "в этом месяце",
    "this year": "в этом году",
    "next week": "на следующей неделе",
    "next month": "в следующем месяце",
    "next year": "в следующем году",
    "five minutes ago": "пять минут назад",
}