slovar = {
    "do you have any brothers or sisters?": "у тебя есть брат или сестра?",
    "yes, I've got …": "да, у меня есть …",
    "yes, I've got a brother": "да, у меня есть брат",
    "yes, I've got a sister": "да, у меня есть сестра",
    "yes, I've got an elder brother": "да, у меня есть старший брат",
    "yes, I've got a younger sister": "да, у меня есть младшая сестра",
    "yes, I've got two brothers": "да, у меня есть два брата",
    "yes, I've got two sisters": "да, у меня есть две сестры",
    "yes, I've got one brother and two sisters": "да, у меня есть брат и две сестры",
    "no, I'm an only child": "нет, я единственный ребенок",
    "have you got any kids?": "у тебя есть дети?",
    "do you have any children?": "у тебя есть дети?",
    "yes, I've got a boy and a girl": "да, у меня мальчик и девочка",
    "yes, I've got a young baby": "да, у меня малыш",
    "yes, I've got three kids": "да, у меня три ребенка",
    "I don't have any children": "у меня нет детей",
    "do you have any grandchildren?": "у вас есть внуки?",
    "where do your parents live?": "где живут твои родители?",
    "what do your parents do?": "чем занимаются твои родители?",
    "what does your father do?": "чем занимается твой отец?",
    "what does your mother do?": "чем занимается твоя мать?",
    "are your grandparents still alive?": "твои бабушка и дедушка еще живы?",
    "let me know if you can make it": "сообщи, если ты сможешь",
    "I'll call you later": "я позвоню тебе позже",
    "what's your address?": "какой твой адрес?",
    "I'm running a little late": "я немного опаздываю",
    "I'll be there in … minutes": "я буду там через … минут",
    "I'll be there in five minutes": "я буду там через пять минут",
    "I'll be there in ten minutes": "я буду там через десять минут",
    "I'll be there in fifteen minutes": "я буду там через пятнадцать минут",
    "have you been here long?": "ты уже давно тут?",
    "have you been waiting long?": "ты долго ждал?",
    "come on in!": "входи!, входите!",
    "good to see you!": "рад тебя видеть, рад вас видеть",
    "you're looking well": "ты прекрасно выглядишь, вы прекрасно выглядите",
    "please take your shoes off": "пожалуйста, сними обувь, пожалуйста, снимите обувь",
    "can I take your coat?": "я возьму твое пальто",
    "sorry we're late": "извини, мы опоздали",
    "did you have a good journey?": "ты хорошо добрался?, вы хорошо добрались?",
    "did you find us alright?": "ты нашел нас без проблем?, вы нашли нас без проблем?",
    "I'll show you your room": "я покажу твою комнату, я покажу вашу комнату",
    "this is your room": "это твоя комната, это ваша комната",
    "would you like a towel?": "тебе нужно полотенце?",
    "make yourself at home": "чувствуй себя как дома, чувствуйте себя как дома",
    "can I get you anything to drink?": "хочешь что-нибудь выпить?, хотите что-нибудь выпить?",
    "would you like a tea or coffee?": "хочешь чай или кофе?, хотите чай или кофе?",
    "how do you take it?": "с чем ты хочешь?",
    "do you take sugar?": "сколько положить сахара?",
    "do you take milk?": "тебе нужно молоко?",
    "how many sugars do you take?": "сколько положить сахара?",
    "would you like a …?": "хочешь …?",
    "would you like a soft drink?": "хочешь попить (буквально: безалкогольный напиток)?",
    "would you like a beer?": "хочешь пиво?",
    "would you like a glass of wine?": "хочешь бокал вина?",
    "would you like a gin and tonic?": "хочешь джин с тоником?",
    "have a seat!": "садись!, садитесь!",
    "let's go into the …": "давай(те) пойдем в …",
    "let's go into the lounge": "давай(те) пойдем в гостиную",
    "let's go into the living room": "давай(те) пойдем в гостиную",
    "let's go into the dining room": "давай(те) пойдем в столовую",
    "do you mind if I smoke here?": "ты не против, если я здесь закурю?",
    "I'd prefer it if you went outside": "будет лучше, если ты выйдешь на улицу",
    "are you ready to eat now?": "ты готов есть?, вы готовы есть?",
    "who's driving tonight?": "кто сегодня за рулем?",
    "could I use your phone?": "можно воспользоваться телефоном?",
    "your taxi's here": "твое такси здесь, ваше такси здесь",
    "thanks for coming": "спасибо, что зашел; спасибо, что зашли",
    "have a safe journey home": "безопасного возвращения домой",
    "that's fine, keep the change": "все в порядке, оставьте сдачу",
    "would you like a receipt?": "вы желаете чек?",
    "could I have a receipt, please?": "могу я получит чек, пожалуйста?",
    "could you pick me up here at …?": "могли бы вы забрать меня отсюда в …?",
    "could you pick me up here at six o'clock?": "могли бы вы забрать меня отсюда в шесть часов?",
    "six o'clock": "могли бы вы подождать меня здесь?",
    "Taxis": "Такси",
    "For hire": "Свободно",
    "OK": "ладно",
    "of course": "конечно",
    "of course not": "конечно нет",
    "that's fine": "хорошо",
    "that's right": "точно",
    "sure": "конечно",
    "certainly": "непременно",
    "definitely": "определенно",
    "absolutely": "безусловно",
    "as soon as possible": "как можно быстрее",
    "that's enough": "достаточно",
    "it doesn't matter": "это не важно",
    "it's not important": "это не важно",
    "it's not serious": "это не серьезно",
    "it's not worth it": "это того не стоит",
    "I'm in a hurry": "я тороплюсь",
    "I've got to go": "мне нужно идти",
    "I'm going out я": "собираюсь прогуляться",
    "sleep well": "спи хорошо",
    "same to you!": "и тебе того же!",
    "me too": "я(мне) тоже",
    "not bad": "неплохо",
    "I like …": "мне нравится …",
    "I like him": "мне нравится он",
    "I like her": "мне нравится она",
    "I like it": "мне нравится это",
    "I don't like …": "мне не нравится …",
    "I don't like him": "мне не нравится он",
    "I don't like her": "мне не нравится она",
    "I don't like it": "мне не нравится это",
    "thanks for your …": "спасибо за …",
    "thanks for your help": "спасибо за помощь",
    "thanks for your hospitality": "спасибо за гостепреимство",
    "thanks for your email": "спасибо за имейл",
    "I'm sorry": "извините",
    "I'm really sorry": "прошу прощения",
    "sorry I'm late": "извините за опоздание",
    "sorry to keep you waiting": "прошу прощения за задержку",
    "sorry for the delay": "извините за задержку",
    "look!": "посмотри!",
    "great!": "чудесно!",
    "come on!": "давай!",
    "only joking!": "шутка!",
    "just kidding!": "шутка!",
    "bless you!": "будь здоров! (после чихания)",
    "that's funny!": "прикольно!",
    "that's life!": "такова жизнь!",
    "that's funny, ...": "странно, ...",
}