slovar = {
    "where are you from?": "откуда ты?",
    "where do you come from?": "откуда ты?",
    "whereabouts are you from?": "из каких ты мест?",
    "I'm from …": "я из …",
    "I'm from England": "я из Англии",
    "whereabouts in … are you from?": "откуда в … ты?",
    "whereabouts in Canada are you from?": "откуда в Канаде ты?",
    "what part of … do you come from?": "из какой части … ты?",
    "what part of Italy do you come from?": "из какой части Италии ты?",
    "where do you live?": "где ты живешь?",
    "I live in …": "я живу …",
    "I live in London": "я живу в Лондоне",
    "I live in France": "я живу во Франции",
    "I'm originally from Dublin but now live in Edinburgh": "я на самом деле из Дублина, но сейчас живу в Эдинбурге",
    "I was born in Australia but grew up in England": "я родился в Австралии, но вырос в Англии",
    "what brings you to …?": "как ты оказался …?",
    "what brings you to England?": "как ты оказался в Англии?",
    "I live here": "я живу здесь",
    "I work here": "я работаю здесь",
    "I study here": "я учусь здесь",
    "why did you come to …?": "для чего ты приехал …?",
    "why did you come to the UK?": "для чего ты приехал в Великобританию?",
    "the UK": "я приехал работать",
    "I came here to study": "я приехал учиться",
    "I wanted to live abroad": "я хотел жить заграницей",
    "how long have you lived here?": "как долго ты здесь живешь?",
    "I've only just arrived": "недавно приехал",
    "about a year": "около года",
    "just over two years": "чуть больше двух лет",
    "three years": "три года",
    "how long are you planning to stay here?": "как долго ты собираешься здесь оставаться?",
    "until August": "до августа",
    "a few months": "несколько месяцев",
    "another year": "еще год",
    "I'm not sure": "я точно не знаю",
    "do you like it here?": "тебе здесь нравится?",
    "yes, I love it!": "да, очень нравится!",
    "I like it a lot": "очень нравится",
    "it's OK": "нормально",
    "what do you like about it?": "что тебе здесь нравится?",
    "I like the …": "мне нравится/нравятся …",
    "I like the food": "мне нравится/нравятся еда",
    "I like the weather": "мне нравится/нравятся погода",
    "I like the people": "мне нравится/нравятся люди",
    "how old are you?": "сколько тебе лет?",
    "I'm twenty-two": "мне двадцать два",
    "I'm thirty-eight": "мне тридцать восемь",
    "when's your birthday?": "когда у тебя день рождения?",
    "it's 16 May": "он 16 мая",
    "it's 2 October": "он 2 октября",
    "who do you live with?": "с кем ты живешь?",
    "do you live with anybody?": "ты живешь с кем-то?",
    "I live with …": "я живу …",
    "I live with my boyfriend": "я живу со своим другом",
    "I live with my girlfriend": "я живу со своей подругой",
    "I live with my partner": "я живу со своим сожителем",
    "I live with my husband": "я живу со своим мужем",
    "I live with my wife": "я живу со своей женой",
    "I live with my parents": "я живу со своими родителями",
    "I live with a friend": "я живу с другом",
    "I live with friends": "я живу с друзьями",
    "I live with relatives": "я живу с родственниками",
    "do you live on your own?": "ты живешь отдельно?",
    "I live on my own": "я живу отдельно",
    "I'd love to": "с удовольствием",
    "sounds good": "хорошее предложение",
    "that sounds like fun": "заманчивое предложение",
    "sorry, I can't make it": "извини, не смогу",
    "I'm afraid already have plans": "боюсь, что у меня уже есть планы",
    "I'm too tired": "я слишком устал",
    "I'm staying in tonight": "я останусь сегодня дома",
    "I've got too much work to do": "у меня очень много работы",
    "I need to study": "мне нужно учиться",
    "I'm very busy at the moment": "я сейчас очень занят",
    "what time shall we meet?": "во сколько встретимся?",
    "let's meet at …": "давайте встретимся в …",
    "let's meet at eight o'clock": "давайте встретимся в восемь часов",
    "thanks for a lovely evening": "спасибо за прекрасный вечер",
    "I'm interested in this position": "я заинтересован в этой должности",
    "I'd like to apply for this job": "я хотел бы устроиться на эту работу",
    "is this a temporary or permanent position?": "это временная или постоянная должность?",
    "what are the hours of work?": "какое рабочее время?",
    "will I have to work on Saturdays?": "должен ли я работать по субботам?",
    "will I have to work shifts?": "должен ли я буду работать посменно?",
    "how much does the job pay?": "какая заработная плата?",
    "£10 an hour": "10 фунтов в час",
    "£350 a week": "350 фунтов в неделю",
    "what's the salary?": "какая заработная плата?",
    "£2,000 a month": "2000 фунтов в месяц",
    "£30,000 a year": "30 000 фунтов в год",
    "will I be paid weekly or monthly?": "мне будут платить еженедельно или ежемесячно?",
    "will I get travelling expenses?": "будут ли покрываться транспортные расходы?",
    "will I get paid for overtime?": "мне будут платить за сверхурочное время?",
    "is there …?": "есть ли …?",
    "is there a company car?": "есть ли служебная машина?",
    "is there a staff restaurant?": "есть ли столовая для служащих?",
    "is there a pension scheme?": "есть ли пенсионная схема?",
    "is there free medical insurance?": "есть ли бесплатное медицинское страхование?",
    "how many weeks' holiday a year are there?": "сколько недель составляет отпуск?",
    "who would I report to?": "кому я должен сообщить?",
    "I'd like to take the job": "я хотел бы приступить к работе",
    "when do you want me to start?": "когда я должен начать?",
    "we'd like to invite you for an interview": "мы хотели бы пригласить вас на собеседование",
    "this is the job description": "это – описание работы",
    "have you got any experience?": "у вас есть какой-нибудь опыт?",
    "have you got any qualifications?": "вы обладаете какими-либо качествами?",
    "we need someone with experience": "нам нужен кто-то с опытом",
    "we need someone with qualifications": "нам нужен специалист",
    "what qualifications have you got?": "какими профессиональными качествами вы обладаете?",
}