slovar = {
    "I'd like some oil": "мне нужно масло",
    "can I check my tyre pressures here?": "тут можно проверить давление в колесах?",
    "my car's broken down": "моя машина сломалась",
    "my car won't start": "моя машина не заводится",
    "we've run out of petrol": "у нас закончилось топливо",
    "the battery's flat": "аккамулятор сел",
    "have you got any jump leads?": "у вас есть «крокодилы»?",
    "I've got a flat tyre": "у меня спущены колеса",
    "I've got a puncture": "у меня прокол",
    "the … isn't working": "… не работает",
    "the speedometer isn't working": "спидометр не работает",
    "the petrol gauge isn't working": "топливный датчик не работает",
    "the fuel gauge isn't working": "топливный датчик не работает",
    "the … aren't working": "… не работают",
    "the brake lights aren't working": "стоп-сигналы не работают",
    "the indicators aren't working": "габаритные огни не работают",
    "there's something wrong with the engine": "что-то не в порядке с мотором",
    "there's something wrong with the steering": "что-то не в порядке с рулевым управлением",
    "there's something wrong with the brakes": "что-то не в порядке с тормозами",
    "the car's losing oil": "в машине течет масло",
    "do you know what speed you were doing?": "вы знаете, с какой скоростью вы ехали?",
    "are you insured on this vehicle?": "у вас есть страховка на машину?",
    "could I see your insurance documents?": "покажите вашу страховку",
    "have you had anything to drink?": "вы принимали алкоголь?",
    "how much have you had to drink?": "сколько вы выпили?",
    "could you blow into this tube, please?": "дуньте, пожалуйста, в эту трубку",
    "Stop": "Стоп",
    "Give way": "Уступить дорогу",
    "No entry": "Нет проезда",
    "One way": "Односторонняя дорога",
    "Parking": "Стоянка",
    "No parking": "Стоянка запрещена",
    "No stopping": "Не останавливаться",
    "Vehicles will be clamped": "Транспортные средства будут блокированы",
    "Keep left": "Держитесь левой стороны",
    "Get in lane": "Придерживайтесь полосы",
    "Slow down": "Сбавить скорость",
    "No overtaking": "Обгон запрещен",
    "School": "Школа",
    "Low bridge": "Низкий мост",
    "Level crossing": "Железнодорожный переезд",
    "Bus lane": "Автобусная полоса",
    "No through road": "Нет проезда",
    "Caution": "Внимание",
    "Fog": "Туман",
    "Diversion": "Объезд",
    "Road closed": "Дорога закрыта",
    "Roadworks": "Дорожные работы",
    "Accident ahead": "Впереди авария",
    "Queue ahead": "Впереди пробка",
    "Queues after next junction": "Пробка после следующего перекрестка",
    "On tow":  "На буксире",
    "Services": "Зона отдыха",
    "Air": "Воздух",
    "Water": "Вода",
    "Don't drink and drive": "Не садись за руль, если выпил",
    "how are you?": "как дела?",
    "how's it going?": "как оно? (дружеское)",
    "how are you doing?": "как поживаешь? (дружеское)",
    "how's life?": "как жизнь? (дружеское)",
    "how are things?": "как делишки? (дружеское)",
    "I'm fine, thanks": "прекрасно, спасибо",
    "I'm OK, thanks": "нормально, спасибо",
    "not too bad, thanks": "неплохо, спасибо",
    "alright, thanks": "в порядке, спасибо",
    "not so well": "не особо хорошо",
    "how about you?": "как ты?",
    "and you?": "а ты?",
    "and yourself?": "а сам?",
    "what are you up to?": "чем занимаешься?",
    "what have you been up to?": "чем занимался?",
    "working a lot": "много работал",
    "studying a lot": "много учился",
    "I've been very busy": "я был очень занят",
    "same as usual": "тем же, чем обычно",
    "not much": "ничем особенным",
    "not a lot": "ничем особенным",
    "I've just come back from …": "я только что вернулся из …",
    "I've just come back from Portugal": "я только что вернулся из Португалии",
    "I'm at home": "я дома",
    "I'm at work": "я на работе",
    "I'm in town": "я в городе",
    "I'm in the countryside": "я на природе",
    "I'm at the shops": "я в магазине",
    "I'm on a train": "я в поезде",
    "what do you like doing in your spare time?": "что тебе нравится делать в свободное время?",
    "I like watching TV": "мне нравится смотреть телевизор",
    "I like listening to music": "мне нравится слушать музыку",
    "I like walking": "мне нравится гулять",
    "I like jogging": "мне нравится бегать",
    "I quite like …": "мне в некоторой степени нравится …",
    "I quite like cooking": "мне в некоторой степени нравится готовить",
    "I quite like playing chess": "мне в некоторой степени нравится играть в шахматы",
    "I quite like yoga": "мне в некоторой степени нравится заниматься йогой",
    "I really like …": "мне очень нравится …",
    "I really like swimming": "мне очень нравится плавать",
    "I really like dancing": "мне очень нравится танцевать",
    "I love …": "я люблю …",
    "I love the theatre": "я люблю театр",
    "I love the cinema": "я люблю кино",
    "I love going out": "я люблю тусоваться",
    "I love clubbing": "я люблю ходить в клубы",
    "I enjoy travelling": "я люблю путешествовать",
    "I don't like pubs": "мне не нравятся пабы",
    "I don't like noisy bars": "мне не нравятся шумные бары",
    "I don't like nightclubs": "мне не нравятся ночные клубы",
}