slovar = {
    "what do you like doing in your spare time?": "что тебе нравится делать в свободное время?",
    "I like …": "мне нравится ...",
    "I like watching TV": "мне нравится смотреть телевизор",
    "I like listening to music": "мне нравится слушать музыку",
    "I like walking": "мне нравится гулять",
    "I like jogging": "мне нравится бегать",
    "I quite like …": "мне в некоторой степени нравится …",
    "I quite like cooking": "мне в некоторой степени нравится готовить",
    "I quite like playing chess": "мне в некоторой степени нравится играть в шахматы",
    "I quite like yoga": "мне в некоторой степени нравится заниматься йогой",
    "I really like …": "мне очень нравится …",
    "I really like swimming": "мне очень нравится плавать",
    "I really like dancing": "мне очень нравится танцевать",
    "I love …": "я люблю …",
    "I love the theatre": "я люблю театр",
    "I love the cinema": "я люблю кино",
    "I love going out": "я люблю тусоваться",
    "I love clubbing": "я люблю ходить в клубы",
    "I enjoy travelling": "я люблю путешествовать",
    "I don't like …": "мне не нравятся …",
    "I don't like pubs": "мне не нравятся пабы",
    "I don't like noisy bars": "мне не нравятся шумные бары",
    "I don't like nightclubs": "мне не нравятся ночные клубы",
    "I hate …": "я ненавижу …",
    "I hate shopping": "я ненавижу ходить по магазинам",
    "I can't stand …": "я терпеть не могу …",
    "I can't stand football": "я терпеть не могу футбол",
    "I'm interested in …": "я интересуюсь …",
    "I'm interested in photography": "я интересуюсь фотографией",
    "I'm interested in history": "я интересуюсь историей",
    "I'm interested in languages": "я интересуюсь языками",
    "I read a lot": "я много читаю",
    "have you read any good books lately?": "ты читал какие-нибудь хорошие книги в последнее время?",
    "have you seen any good films recently?": "ты смотрел какие-нибудь хорошие фильмы в последнее время?",
    "do you play any sports?": "ты занимаешься спортом?",
    "yes, I play …": "да, я играю …",
    "yes, I play football": "да, я играю в футбол",
    "yes, I play tennis": "да, я играю в теннис",
    "yes, I play golf": "да, я играю в гольф",
    "I'm a member of a gym": "я член спортклуба",
    "no, I'm not particularly sporty": "нет, я не особенно спортивный",
    "I like watching football": "мне нравится смотреть футбол",
    "which team do you support?": "за какую команду ты болеешь?",
    "I support …": "я болею за …",
    "I support Manchester United": "я болею за «Манчестер Юнайтед»",
    "I support Chelsea": "я болею за «Челси»",
    "I'm not interested in football": "меня не интересует футбол",
    "do you play any instruments?": "ты играешь на каких-либо музыкальных инструментах?",
    "yes, I play the guitar": "да, я играю на гитаре",
    "yes, I've played the piano for … years": "да, я играю на фортепьяно … лет",
    "yes, I've played the piano for five years": "да, я играю на фортепьяно пять лет",
    "I'm learning to play …": "я учусь играть …",
    "I'm learning to play the violin": "я учусь играть на скрипке",
    "I'm in a band": " я играю в группе",
    "I sing in a choir": "я пою в хоре",
    "what sort of music do you like?": "какая музыка тебе нравится?",
    "what sort of music do you listen to?": "какую музыку ты слушаешь?",
    "pop": "поп",
    "rock": "рок",
    "dance": "танцевальную",
    "classical": "классическую",
    "anything, really": "любую",
    "lots of different stuff": "разных стилей и направлений",
    "have you got any favourite bands?": "у тебя есть любимые исполнители?",
    "do you want to watch a …?": "хочешь посмотреть …?",
    "do you want to watch a film?": "хочешь посмотреть фильм?",
    "do you want to watch a DVD?": "хочешь посмотреть DVD?",
    "do you want me to put the TV on?": "хочешь, я включу телевизор?",
    "could you pass me the remote control?": "можешь передать мне пульт?",
    "do you want a game of …?": "хочешь поиграть в …?",
    "do you want a game of chess?": "хочешь поиграть в шахматы?",
    "do you want a game of cards?": "хочешь поиграть в карты?",
    "what time's the match on?": "во сколько начинается матч?",
    "who's playing?": "кто играет?",
    "who's winning?": "кто выигрывает?",
    "what's the score?": "какой счет?",
    "who won?": "кто выиграл?",
    "it was a draw": "сыграли вничью",
    "what's for …?": "что на …?",
    "what's for breakfast?": "что на завтрак?",
    "what's for lunch?": "что на обед?",
    "what's for dinner?": "что на ужин?",
    "breakfast's ready": "завтрак готов",
    "lunch is ready": "обед готов",
    "dinner's ready": "ужин готов",
    "what would you like for …?": "что ты хотел бы на …?",
    "what would you like for breakfast?": "что ты хотел бы на завтрак?",
    "what would you like for lunch?": "что ты хотел бы на обед?",
    "what would you like for dinner?": "что ты хотел бы на ужин?",
    "would you like some toast?": "хочешь тост?",
    "could you pass the …, please?": "можешь передать мне …, пожалуйста?",
    "could you pass the salt, please?": "можешь передать мне соль, пожалуйста?",
    "could you pass the sugar, please?": "можешь передать мне сахар, пожалуйста?",
    "could you pass the butter, please?": "можешь передать мне масло, пожалуйста?",
    "would you like a glass of …?": "хочешь …?",
    "would you like a glass of water?": "хочешь стакан воды?",
    "would you like a glass of orange juice?": "хочешь стакан апельсинового сока?",
    "would you like a glass of wine?": "хочешь бокал вина?",
    "careful, the plate's very hot!": "осторожно, тарелка горячая!",
    "would you like some more?": "хочешь добавки?",
    "have you had enough to eat?": "ты наелся?",
    "would anyone like dessert?": "кто-нибудь хочет десерт?",
    "would anyone like coffee?": "кто-нибудь хочет кофе?",
    "what's for dessert?": "что на десерт?",
    "I'm full": "я наелся",
    "that was …": "это было …",
    "that was lovely": "это было отлично",
}