slovar = {
    "where do you work?": "где ты работаешь?",
    "I work in …": "я работаю …",
    "I work in an office": "я работаю в офисе",
    "I work in a shop": "я работаю в магазине",
    "I work in a restaurant": "я работаю в ресторане",
    "I work in a bank": "я работаю в банке",
    "I work in a factory": "я работаю на заводе",
    "I work in a call centre": "я работаю в телефонном центре",
    "I work from home": "я работаю на дому",
    "I'm training to be …": "я прохожу обучение, чтобы стать …",
    "I'm training to be an engineer": "я прохожу обучение, чтобы стать инженером",
    "I'm training to be a nurse": "я прохожу обучение, чтобы стать медсестрой",
    "I'm a trainee …": "я стажёр-…",
    "I'm a trainee accountant": "я стажёр-бухгалтер",
    "I'm a trainee supermarket manager": "я стажёр-менеджер в супермаркете",
    "I'm on a course at the moment": "я сейчас прохожу обучение",
    "I'm on work experience": "я прохожу практику (короткий период)",
    "I'm doing an internship": "я прохожу практику (более долгий период)",
    "are you a student?": "ты студент?",
    "what do you study?": "что ты изучаешь?",
    "I'm studying …": "я изучаю …",
    "I'm studying history": "я изучаю историю",
    "I'm studying economics": "я изучаю экономику",
    "I'm studying medicine": "я изучаю медицину",
    "where do you study?": "где ты учишься?",
    "which university are you at?/": "в каком университете ты учишься?",
    "what university do you go to?": "в каком университете ты учишься?",
    "I'm at …": "я учусь …",
    "I'm at Liverpool University": "я учусь в Ливерпульском университете",
    "which year are you in?": "на каком ты курсе?",
    "I'm in my … year": "я на … курсе",
    "I'm in my first year": "я на первом курсе",
    "I'm in my second year": "я на втором курсе",
    "I'm in my third year": "я на третьем курсе",
    "I'm in my final year": "я на последнем курсе",
    "I'm in my first year at university": "я учусь на первом курсе в университете",
    "do you have any exams coming up?": "у тебя будут скоро экзамены?",
    "I've just graduated": "я недавно закончил",
    "I'm doing a masters in …": "я в магистратуре по …",
    "I'm doing a masters in law": "я в магистратуре по юриспруденции",
    "law1": "я в докторантуре по …",
    "law": "я в докторантуре по химии",
    "did you go to university?": "ты учился в университете?",
    "I didn't go to university": "я не учился в университете",
    "I never went to university": "я никогда не учился в университете",
    "where did you go to university?": "где ты учился в университете?",
    "I went to …": "я учился в …",
    "I went to Cambridge": "я учился в Кембридже",
    "what did you study?": "что ты изучал?",
    "I studied …": "я изучал …",
    "I studied maths": "я изучал математику",
    "I studied politics": "я изучал политологию",
    "where did you go to school?": "где ты учился в школе?",
    "I went to school in …": "я учился в школе в …",
    "I went to school in Bristol": "я учился в школе в Бристоле",
    "I left school at sixteen": "я ушел из школы в шестнадцать лет",
    "I'm taking a gap year": "у меня свободный от учебы год (год между окончанием школы и началом учебы в универсиете, обычно используемый для путешествий, волонтерской работы и т.д.)",
    "how many more years do you have to go?": "сколько лет тебе еще учиться?",
    "what do you want to do when you've finished?": "что ты собираешься делать, когда закончишь?",
    "get a job": "устроиться на работу",
    "go travelling": "путешествовать",
    "I don't know what I want to do after university": "я не знаю, что буду делать после университета",
    "are you religious?": "ты верующий?",
    "no, I'm …": "нет, я …",
    "no, I'm an atheist": "нет, я атеист",
    "no, I'm agnostic": "нет, я агностик",
    "what religion are you?": "какого ты вероисповедания?",
    "I'm a …": "я …",
    "I'm a Christian": "я христьянин",
    "I'm a Muslim": "я мусульманин",
    "I'm a Buddhist": "я буддист",
    "I'm a Sikh": "я сикх",
    "I'm a Hindu": "я хинду",
    "I'm a Protestant": "я протестант",
    "I'm a Catholic": "я католик",
    "I'm Jewish": "я иудей",
    "do you believe in God?": "ты веришь в Бога?",
    "I believe in God": "я верю в Бога",
    "0I don't believe in God": "я не верю в Бога",
    "do you believe in life after death?": "ты веришь в жизнь после смерти?",
    "do you believe in reincarnation?": "ты веришь в перерождение?",
    "is there a … near here?": "здесь есть поблизости …?",
    "is there a church near here?": "здесь есть поблизости церковь?",
    "is there a mosque near here?": "здесь есть поблизости мечеть?",
    "is there a synagogue near here?": "здесь есть поблизости синагога?",
    "is there a temple near here?": "здесь есть поблизости храм?",
    "what do you do?": "чем ты занимаешься?",
    "what do you do for a living?": "чем ты зарабатываешь на жизнь?",
    "what sort of work do you do?": "какую работу ты выполняешь?",
    "what line of work are you in?": "в какой области ты работаешь?",
    "I'm a teacher": "я учитель",
    "I'm a student": "я студент",
    "I'm a doctor": "я врач",
    "I work as a …": "я работаю …",
    "I work as a journalist": "я работаю журналистом",
    "I work as a programmer": "я работаю программистом",
    "I work in television": "я работаю на телевидении",
    "I work in publishing": "я работаю в издательстве",
    "I work in PR": "я работаю по связям с общественностью",
    "I work in sales": "я работаю в торговле",
    "I work in IT": "я работаю в области инфо-технологий",
    "I work with …": "я работаю …",
    "I work with computers": "я работаю с компьютерами",
    "I work with children with disabilities": "я работаю с детьми-инвалидами",
    "I stay at home and look after the children": "я сижу дома и воспитываю детей",
}