slovar = {
    "OK": "ладно",
    "of course": "конечно",
    "of course not": "конечно нет",
    "that's fine": "хорошо",
    "that's right": "точно",
    "sure": "конечно",
    "certainly": "непременно",
    "definitely": "определенно",
    "absolutely": "безусловно",
    "as soon as possible": "как можно быстрее",
    "that's enough": "достаточно",
    "it doesn't matter": "это не важно",
    "it's not important": "это не важно",
    "it's not serious": "это не серьезно",
    "it's not worth it": "это того не стоит",
    "I'm in a hurry": "я тороплюсь",
    "I've got to go": "мне нужно идти",
    "I'm going out я": "собираюсь прогуляться",
    "sleep well": "спи хорошо",
    "same to you!": "и тебе того же!",
    "me too": "я(мне) тоже",
    "not bad": "неплохо",
    "I like …": "мне нравится …",
    "I like him": "мне нравится он",
    "I like her": "мне нравится она",
    "I like it": "мне нравится это",
    "I don't like …": "мне не нравится …",
    "I don't like him": "мне не нравится он",
    "I don't like her": "мне не нравится она",
    "I don't like it": "мне не нравится это",
    "thanks for your …": "спасибо за …",
    "thanks for your help": "спасибо за помощь",
    "thanks for your hospitality": "спасибо за гостепреимство",
    "thanks for your email": "спасибо за имейл",
    "I'm sorry": "извините",
    "I'm really sorry": "прошу прощения",
    "sorry I'm late": "извините за опоздание",
    "sorry to keep you waiting": "прошу прощения за задержку",
    "sorry for the delay": "извините за задержку",
    "look!": "посмотри!",
    "great!": "чудесно!",
    "come on!": "давай!",
    "only joking!": "шутка!",
    "just kidding!": "шутка!",
    "bless you!": "будь здоров! (после чихания)",
    "that's funny!": "прикольно!",
    "that's life!": "такова жизнь!",
    "damn it!": "проклятие!",
    "come in !": "войдите!",
    "please sit down": "садитесь, пожалуйста",
    "could I have your attention, please?": "пожалуйста, внимание!",
    "let's go!": "пойдемте!",
    "hurry up!": "поторопись!",
    "get a move on!": "пошевеливайся!",
    "calm down": "успокойся",
    "steady on!": "осторожнее!",
    "hang on a second": "подожди секундочку",
    "hang on a minute": "подожди минутку",
    "one moment, please": "один момент, пожалуйста",
    "just a minute": "одну минутку",
    "take your time": "не торопись",
    "please be quiet": "пожалуйста, успокойтесь",
    "shut up!": "замолчи!",
    "stop it!": "прекрати!",
    "don't worry": "не волнуйся",
    "don't forget": "не забудь",
    "help yourself": "угощайся",
    "go ahead": "давай",
    "let me know!": "сообщи мне!",
    "after you!": "после вас!",
    "here": "здесь (тут)",
    "there": "там",
    "everywhere": "везде",
    "nowhere": "нигде",
    "somewhere": "где-то",
    "where are you?": "где ты?, где вы?",
    "what's this?": "что это здесь?",
    "what's that?": "что это там?",
    "is anything wrong?": "что-то не так?",
    "what's the matter?": "в чем дело?",
    "is everything OK?": "все в порядке?",
    "have you got a minute?": "у тебя есть свободная минутка?",
    "have you got a pen I could borrow?": "можно одолжить ручку?",
    "really?": "правда?",
    "are you sure?": "ты уверен?",
    "why?": "почему?",
    "why not ?": "почему бы и нет?",
    "what's going on?": "что происходит?",
    "what's happening?": "что происходит?",
    "what happened?": "что случилось?",
    "what?": "что?",
    "where?": "где?",
    "when?": "когда?",
    "who?": "кто?",
    "how?": "как?",
    "how many?": "сколько?",
    "how much?": "сколько?",
    "congratulations!": "поздравления!",
    "well done!": "хорошо сработано!",
    "good luck!": "удачи!",
    "bad luck!": "вот незадача!",
    "never mind!": "неважно!",
    "what a pity!": "как жаль!",
    "what a shame!": "как жаль!",
    "happy birthday!": "с днем рождения!",
    "happy New Year!": "с Новым Годом!",
    "happy Easter!": "хороших пасхальных праздников!",
    "happy Christmas!": "счастливого Рождества!",
    "merry Christmas!": "счастливого Рождества!",
    "happy Valentine's Day!": "с днем святого Валентина!",
    "glad to hear it": "рад это слышать",
    "sorry to hear that": "жаль это слышать",
    "I'm tired": "я устал",
    "I'm exhausted": "я изможден",
    "I'm hungry": "я хочу есть",
    "I'm thirsty": "я хочу пить",
    "I'm bored": "мне скучно",
    "I'm worried": "я обеспокоен",
    "I'm looking forward to it": "я с нетерпением жду этого",
    "I'm in a good mood": "я в хорошем настороении",
    "I'm in a bad mood": "я в плохом настроении",
    "I can't be bothered": "не беспокойте меня",
    "welcome!": "добро пожаловать!",
    "welcome to …": "добро пожаловать в …",
    "welcome to England": "добро пожаловать в Англию",
    "long time, no see!": "давно не виделись!",
    "all the best!": "всего хорошего!",
    "see you tomorrow!": "до завтра!",
    "what do you think?": "что ты думаешь?",
    "I think that...": "я думаю, что...",
    "I hope that...": "я надеюсь, что...",
    "I'm afraid that ...": "я боюсь, что...",
    "in my opinion, ...": "по моему мнению, ...",
    "I agree": "я согласен (согласна)",
    "I disagree": "я не согласен (согласна)",
    "I don't agree": "я не согласен (согласна)",
    "that's true": "это правда",
    "that's not true": "это не правда",
    "I think so": "думаю, что так",
    "I don't think so": "я так не думаю",
    "I hope so": "надеюсь",
    "I hope not": "надеюсь, что нет",
    "you're right": "ты прав",
    "you're wrong": "ты не прав",
    "I don't mind": "я не возражаю",
    "it's up to you": "это зависит от тебя",
    "that depends": "смотря как",
    "that's interesting": "это интересно",
    "that's funny, ...": "странно, ...",
}