slovar = {
    "I've come to collect my …": "я пришел забрать …",
    "I've come to collect my watch": "я пришел забрать часы",
    "I've come to collect my computer": "я пришел забрать компьютер",
    "could you print the photos on this memory card for me?": "вы могли бы распечать фотографии с этой карты памяти?",
    "could you print the photos on this memory stick for me?": "вы могли бы распечатать фотографии с этой флешки?",
    "would you like matt or gloss prints?": "вы хотите матовые или глянцевые снимки?",
    "what size prints would you like?": "какого размера фотографии вы бы хотели?",
    "could I have this suit cleaned?": "вы могли бы почистить этот костюм?",
    "could you take these trousers up an inch?": "могли бы вы укоротить эти брюки на дюйм?",
    "could you take these trousers down an inch?": "могли бы вы удленить эти брюки на дюйм?",
    "could you take these trousers in an inch?": "могли бы вы ушить эти брюки на дюйм?",
    "could you take these trousers out two inches?": "могли бы вы расширить эти брюки на два дюйма?",
    "could I have these shoes repaired?": "могли бы вы отремонтировать эту обувь?",
    "could you put new … on these shoes for me?": "могли вы сделать новые … для этих ботинок?",
    "could you put new heels on these shoes for me?": "могли вы сделать новые каблуки для этих ботинок?",
    "could you put new soles on these shoes for me?": "могли вы сделать новые подметки для этих ботинок?",
    "could I have this key cut?": "могли бы вы сделать такой ключ?",
    "could I have these keys cut?": "могли бы вы сделать такие ключи?",
    "I'd like one copy of each of these, please": "сделайте по одной копии каждого экземпляра, пожалуйста",
    "could I have a key ring?": "я хотел бы брелок для ключей",
    "could I try this on?": "можно это примерить?",
    "could I try these on?": "можно это примерить? (для обуви, брюк или когда вы хотите примерить несколько вещей)",
    "could I try these shoes on?": "могу я примерить эти ботинки?",
    "do you want to try it on?": "вы хотите это примерить?",
    "do you want to try them on?": "вы хотите их примерить?",
    "what size are you?": "какой у вас размер?",
    "what size do you take?": "какой размер вы возьмёте?",
    "I take a size …": "я возьму размер …",
    "I take a size 10": "я возьму размер 10",
    "do you have this in a size …?": "у вас есть это размера …?",
    "do you have this in a size 7?": "у вас есть это размера 7?",
    "do you have these in a size …?": "у вас есть это размера …?",
    "do you have these in a size 12?": "у вас есть это размера 12?",
    "do you have a fitting room?": "у вас есть примерочная?",
    "where's the fitting room?": "где находится примерочная?",
    "have you got this in a smaller size?": "у вас есть это размером меньше?",
    "have you got this in a larger size?": "у вас есть это размером больше?",
    "could you measure my …?": "вы можете измерить мне …?",
    "could you measure my waist?": "вы можете измерить мне бёдра?",
    "could you measure my neck?": "вы можете измерить мне шею?",
    "could you measure my chest?": "вы можете измерить мне грудь?",
    "is that a good fit?": "хорошо это сидит?",
    "it's much too small": "это слишком сильно мало",
    "it's a little too small": "это немного мало",
    "it's a little too big": "это немного велико",
    "it's much too big": "это слишком сильно велико",
    "it's just right": "это как раз подходит",
    "they're just right": "это как раз подходит",
    "it doesn't fit": "не подходит",
    "they don't fit": "они не подходят",
    "how do they feel?": "как вам в них?",
    "do they feel comfortable?": "вам в них удобно?",
    "it suits you": "это идёт вам",
    "they suit you": "это идёт вам",
    "is this the only colour you've got?": "это только такого цвета?",
    "what do you think of these?": "что вы думаете об этом?",
    "I like them": "мне нравятся",
    "I don't like them": "мне не нравятся",
    "I don't like the colour": "мне не нравится цвет",
    "what are these made of?": "из чего это сделано?",
    "are these washable?": "это можно стирать?",
    "no, they have to be dry-cleaned": "нет, это надо чистить в химчистке",
    "I'll take it": "я возьму",
    "I'll take them": "я возьму",
    "I'll take this": "я возьму это",
    "I'll take these": "я возьму эти",
    "Menswear": "Мужская одежда",
    "Womenswear": "Женская одежда",
    "Ladieswear": "Женская одежда",
    "Childrenswear": "Детская одежда",
    "Babywear": "Одежда для малышей",
    "Fitting room": "Примерочные кабинки",
    "Size": "Размер",
    "S": "Маленький",
    "Small": "Маленький",
    "M": "Средний",
    "Medium": "Средний",
    "L": "Большой",
    "Large": "Большой",
    "XL": "Очень Большой",
    "Extra-large": "Очень Большой",
    "could you tell me where the … is?": "могли бы вы сказать где …?",
    "could you tell me where the milk is?": "могли бы вы сказать где молоко?",
    "could you tell me where the bread counter is?": "могли бы вы сказать где хлебный прилавок?",
    "could you tell me where the meat section is?": "могли бы вы сказать где мясной отдел?",
    "could you tell me where the frozen food section is?": "могли бы вы сказать где отдел замороженной пищи?",
    "are you being served?": "вас обслуживают?",
    "I'd like …": "я хотел бы …",
    "I'd like that piece of cheese": "я хотел бы этот кусочек сыра",
    "I'd like a slice of pizza": "я хотел бы ломтик пиццы",
    "I'd like six slices of ham": "я хотел бы шесть ломтиков ветчины",
    "I'd like some olives": "я хотел бы оливки",
    "how much would you like?": "сколько вы хотели бы?",
    "300 grams": "300 грамм",
    "half a kilo": "полкило",
    "two pounds": "два фунта (один фунт ― приблизительно 450 граммов)",
    "that's £32.47": "это стоит 32,47 фунта",
    "could I have a carrier bag, please?": "можно пакет, пожалуйста?",
    "could I have another carrier bag, please?": "можно ещё пакет, пожалуйста?",
    "do you need any help packing?": "помочь вам упаковать?",
    "do you have a loyalty card?": "у вас есть клиентская карточка?",
    "Checkout": "Касса",
    "8 items or less": "8 предметов или меньше",
    "Basket only": "Только для корзинок",
    "Cash only": "Только наличные",
    "Best before end": "Годен до",
    "Use by": "Использовать до",
    "what times are you open?": "когда вы открыты?",
    "we're open from 9am to 5pm, Monday to Friday": "мы открыты с 9 утра до 5 вечера, с понедельника по пятницу",
    "we're open from 10am to 8pm, seven days a week": "мы открыты с 10 утра до 8 вечера, семь дней в неделю",
    "are you open on …?": "вы открыты в …?",
    "are you open on Saturday?": "вы открыты в субботу?",
    "are you open on Sunday?": "вы открыты в воскресенье?",
    "what time do you close?": "во сколько вы закрываетесь?",
    "what time do you close today?": "во сколько вы сегодня закроетесь?",
    "what time do you open tomorrow?": "во-сколько вы открываетесь завтра?",
    "can I help you?": "могу я вам помочь?",
}