slovar = {
    "could I order a new chequebook, please?": "я хотел бы заказать новую чековую книжку, пожалуйста",
    "I'd like to cancel a cheque": "я хотел бы аннулировать чек",
    "I'd like to cancel this standing order": "я хотел бы прервать постоянное платежное поручение",
    "where's the nearest cash machine?": "где находится ближайший банкомат?",
    "what's the interest rate on this account?": "какая процентная ставка на этом счете?",
    "what's the current interest rate for personal loans?": "какая процентная ставка на персональный заём?",
    "I've lost my bank card": "я потерял свою банковскую карточку",
    "I want to report a …": "я хочу заявить о …",
    "I want to report a lost credit card": "я хочу заявить о потере кредитной карточки",
    "I want to report a stolen credit card": "я хочу заявить о краже кредитной карточки",
    "we've got a joint account": "у нас совместный счет",
    "I'd like to tell you about a change of address": "я хотел бы сообщить вам об изменении адреса",
    "I've forgotten my Internet banking password": "я забыл пароль для интернет-банка",
    "I've forgotten the PIN number for my card": "я забыл пароль моей карточки",
    "I'll have a new one sent out to you": "я вышлю вам новый",
    "could I make an appointment to see …?": "я хотел бы назначить встречу с …",
    "could I make an appointment to see the manager?": "я хотел бы назначить встречу с менеджером",
    "could I make an appointment to see a financial advisor?": "я хотел бы назначить встречу с финансовым советником",
    "I'd like to speak to someone about a mortgage": "я хотел бы поговорить с кем-нибудь о жилищном заёме",
    "Insert your card": "Вставьте карточку",
    "Incorrect PIN": "Неправильный пин-код",
    "Enter": "Ввод",
    "Correct": "Исправить",
    "Cancel": "Отмена",
    "Withdraw cash": "Снять наличные",
    "Other amount": "Другая сумма",
    "Your cash is being counted": "Деньги считаются",
    "Insufficient funds": "Недостаточно денег на счёте",
    "Balance": "Остаток счёта",
    "On screen": "На экране",
    "Printed": "Распечатано",
    "Another service?": "Другая услуга?",
    "Would you like a receipt?": "Желаете чек?",
    "Quit": "Прекратить",
    "how much is a first class stamp?": "сколько стоит марка первого класса?",
    "how much is a second class stamp?": "сколько стоит марка второго класса?",
    "I'd like …, please": "я хотел бы …, пожалуйста",
    "I'd like an envelope, please": "я хотел бы конверт, пожалуйста",
    "I'd like a packet of envelopes, please": "я хотел бы упаковку конвертов, пожалуйста",
    "I'd like a jiffy bag, please": "я хотел бы противоударный пакет, пожалуйста",
    "could I have …, please?": "я хотел бы …, пожалуйста",
    "could I have a first class stamp, please?": "я хотел бы марку первого класса, пожалуйста",
    "could I have a second class stamp, please?": "я хотел бы марку второго класса, пожалуйста",
    "could I have a book of first class stamps, please?": "я хотел бы набор марок первого класса, пожалуйста",
    "could I have some first class stamps, please?": "я хотел бы марки первого класса, пожалуйста",
    "how many would you like?": "сколько штук вы хотите?",
    "I'd like to send this to …": "я хотел бы отправить это в …",
    "I'd like to send this to Canada": "я хотел бы отправить это в Канаду",
    "I'd like to send this parcel to …": "я хотел бы отправить эту посылку в …",
    "I'd like to send this parcel to Brazil": "я хотел бы отправить эту посылку в Бразилию",
    "how much will it cost to send this letter to …?": "сколько будет стоит отправить это письмо в …?",
    "how much will it cost to send this letter to the United States?": "сколько будет стоит отправить это письмо в Америку?",
    "can you put it on the scales, please?": "положите это на весы, пожалуйста",
    "I'd like to send this letter by …": "я хотел бы отправить это письмо …",
    "I'd like to send this letter by Recorded Delivery": "я хотел бы отправить это письмо «Recorded Delivery» (при доставке необходима подпись)",
    "I'd like to send this letter by Special Delivery": "я хотел бы отправить это письмо «Special Delivery» (гарантированная доставка по Великобритании в течение суток с компенсацией потери или ущерба)",
    "where's the postbox?": "где находится почтовый ящик?",
    "what's the last date I can post this to … to arrive in time for Christmas?": "какой последний день для отправки этого в …, чтобы вовремя дошло на Рождество?",
    "what's the last date I can post this to Germany to arrive in time for Christmas?": "какой последний день для отправки этого в Германию, чтобы вовремя дошло на Рождество?",
    "what's the last date I can post this to Australia to arrive in time for Christmas?": "какой последний день для отправки этого в Австралию, чтобы вовремя дошло на Рождество?",
    "I've come to collect a parcel": "я пришел забрать посылку",
    "I'd like to pay this bill": "я хотел бы оплатить этот счет",
    "I'd like to send some money to …": "я хотел бы переслать деньги в …",
    "I'd like to send some money to Poland": "я хотел бы переслать деньги в Польшу",
    "I'd like to send some money to India": "я хотел бы переслать деньги в Индию",
    "do you sell postcards?": "вы продаёте открытки?",
    "do you sell birthday cards?": "вы продаёте поздравительные открытки?",
    "do you sell Christmas cards?": "вы продаёте рождественские открытки?",
    "can you fill in this form, please?": "заполните этот бланк, пожалуйста",
    "do you have a …?": "у вас есть …?",
    "do you have a photo booth?": "у вас есть фотобудка?",
    "do you have a photocopier?": "у вас есть копировальный аппарат?",
    "First class": "Первый класс",
    "Second class": "Второй класс",
    "International": "Международный",
    "Airmail": "Авиапочта",
    "we're looking for accommodation": "мы ищем где остановиться",
    "we need somewhere to stay": "нам надо где-то остановиться",
    "do you have a list of …?": "у вас есть список …?",
    "do you have a list of hotels?": "у вас есть список гостиниц?",
    "do you have a list of B&Bs?": "у вас есть список B&Bs?",
    "do you have a list of youth hostels?": "у вас есть список молодежных хостелов?",
    "do you have a list of campsites?": "у вас есть список мест для кемпинга?",
    "what sort of accommodation are you looking for?": "какой тип жилья вы ищите?",
    "can you book accommodation for me?": "вы могли бы забронировть жильё для меня?",
    "do you have a map of the …?": "у вас есть карта …?",
    "do you have a map of the city?": "у вас есть карта города (большой город)?",
    "do you have a map of the town?": "у вас есть карта города (небольшой или маленький город)?",
    "where's the …?": "где находится …?",
    "where's the city centre?": "где находится центр города?",
    "where's the art gallery?": "где находится художественная галерея?",
    "where's the museum?": "где находится музей?",
    "where's the main shopping area?": "где находится главный торговый квартал?",
    "where's the market?": "где находится рынок?",
    "where's the railway station?": "где находится железнодорожная станция?",
    "what's the best way of getting around the city?": "какой самый лучший маршрут по городу?",
    "where can I hire a car?": "где я могу взять на прокат автомобиль?",
    "what are you interested in?": "что вас интересует?",
    "are there any … on at the moment?": "тут сейчас проходят какие-нибудь …?",
    "are there any exhibitions on at the moment?": "тут сейчас проходят какие-нибудь выставки?",
    "are there any cultural events on at the moment?": "тут сейчас проходят какие-нибудь культурные мероприятия?",
    "are there any sporting events on at the moment?": "тут сейчас проходят какие-нибудь спортивные мероприятия?",
    "are there any …?": "есть ли какие-нибудь …?",
    "are there any excursions?": "есть ли какие-нибудь экскурсии?",
    "are there any tours?": "есть ли какие-нибудь туры?",
    "are there any day trips?": "есть ли какие-нибудь дневные путешествия?",
    "is there a city tour?": "есть ли тур по городу?",
    "could you tell us what's on at the …?": "могли бы вы сказать, что идёт в …?",
    "could you tell us what's on at the cinema?": "могли бы вы сказать, что идёт в кино?",
    "could you tell us what's on at the theatre?": "могли бы вы сказать, что идёт в театре?",
    "could you tell us what's on at the concert hall?": "могли бы вы сказать, что идёт в концертном зале?",
    "could you tell us what's on at the opera house?": "могли бы вы сказать, что идёт в опере?",
    "can I book tickets here?": "могу я заказать тут билеты?",
    "do you have any brochures on …?": "у вас есть какие-нибудь брошюры о …?",
    "do you have any brochures on local attractions?": "у вас есть какие-нибудь брошюры о местных развлечениях?",
}