slovar = {
    "breakfast's from 7am till 10am": "завтрак с 7 до 10 часов",
    "could I have breakfast in my room, please?": "могу я заказать завтрак в комнату, пожалуйста?",
    "what time's the restaurant open for dinner?": "во сколько ресторан открывается для ужина?",
    "dinner's served between 6pm and 9.30pm": "ужин подается с шести до половины десятого",
    "what time does the bar close?": "во сколько закрывается бар?",
    "would you like any help with your luggage?": "вам нужна помощь с багажом?",
    "here's your room key": "это ваш ключ от номера",
    "your room number's …": "ваш номер …",
    "your room number's 326": "ваш номер 326",
    "your room's on the … floor": "ваш номер на … этаже",
    "your room's on the first floor": "ваш номер на втором этаже",
    "your room's on the second floor": "ваш номер на третьем этаже",
    "your room's on the third floor": "ваш номер на четвертом этаже",
    "where are the lifts?": "где находятся лифты?",
    "Reception": "Регистрация",
    "Concierge": "Консьерж",
    "Lifts": "Лифты",
    "Bar": "Бар",
    "do you have any vacancies?": "у вас есть свободные места?",
    "from what date?": "с какого числа?",
    "for how many nights?": "на сколько дней?",
    "how long will you be staying for?": "как долго вы собираетесь пребывать?",
    "one night": "один день",
    "two nights": "два дня",
    "a week": "неделю",
    "a fortnight": "две недели",
    "two weeks": "две недели",
    "what sort of room would you like?": "какую комнату желаете?",
    "I'd like a …": "я желаю …",
    "I'd like a single room": "я желаю номер на одного",
    "I'd like a double room": "я желаю номер на двоих",
    "I'd like a twin room": "я желаю номер с двумя кроватями",
    "I'd like a triple room": "я желаю номер с тремя кроватями",
    "I'd like a suite": "я желаю номер-люкс",
    "I'd like a room with …": "я хотел бы номер с …",
    "I'd like a room with an en-suite bathroom": "я хотел бы номер с ванной комнатой",
    "I'd like a room with a bath": "я хотел бы номер с ванной",
    "I'd like a room with a shower": "я хотел бы номер с душем",
    "I'd like a room with a view": "я хотел бы номер с красивым видом",
    "I'd like a room with a sea view": "я хотел бы номер с видом на море",
    "I'd like a room with a balcony": "я хотел бы номер с балконом",
    "I'd like …": "я хотел бы …",
    "I'd like half board": "я хотел бы половину пансиона",
    "I'd like full board": "я хотел бы полный пансион",
    "could we have an extra bed?": "мы хотели бы дополнительную кровать",
    "does the room have …?": "есть ли в комнате …?",
    "does the room have internet access?": "есть ли в комнате интернет?",
    "does the room have air conditioning?": "есть ли в комнате кондиционер?",
    "does the room have television?": "есть ли в комнате телевизор?",
    "is there a …?": "есть ли тут …?",
    "is there a swimming pool?": "есть ли тут бассейн?",
    "is there a sauna?": "есть ли тут сауна?",
    "is there a gym?": "есть ли тут спортзал?",
    "is there a beauty salon?": "есть ли тут салон красоты?",
    "is there a lift?": "есть ли тут лифт?",
    "do you allow pets?": "здесь можно держать домашних животных?",
    "do you have wheelchair access?": "у вас есть вход для инвалидной коляски?",
    "do you have a car park?": "у вас есть автомобильная стоянка?",
    "the room has a shared bathroom": "туалет и ванная общие",
    "what's the price per night?": "сколько стоит одна ночь?",
    "is breakfast included?": "включен ли завтрак?",
    "that's a bit more than I wanted to pay": "это не много больше, чем я готов заплатить",
    "can you offer me any discount?": "вы можете сделать скидку?",
    "have you got anything …?": "у вас есть что-нибудь …?",
    "have you got anything cheaper?": "у вас есть что-нибудь подешевле?",
    "have you got anything bigger?": "у вас есть что-нибудь побольше?",
    "have you got anything quieter?": "у вас есть что-нибудь поспокойней?",
    "could I see the room?": "мог бы я посмотреть комнату?",
    "OK, I'll take it": "хорошо, я беру",
    "I'd like to make a reservation": "я хотел бы забронировать",
    "what's your name, please?": "ваше имя, пожалуйста",
    "could I take your name?": "назовите ваше имя",
    "can I take your …?": "назовите ваш …",
    "can I take your credit card number?": "назовите ваш номер кредитки",
    "can I take your telephone number?": "назовите ваш номер телефона",
    "what time will you be arriving?": "во сколько вы приедете?",
    "Vacancies": "Свободные места",
    "No vacancies": "Свободных мест нет",
    "can you recommend any good …?": "вы можете порекомендовать хорошие …?",
    "can you recommend any good hotels?": "вы можете порекомендовать хорошие гостиницы?",
    "can you recommend any good B&Bs?": "вы можете порекомендовать хорошие B&Bs (небольшие бюджетные гостиницы, в цену включен завтрак)?",
    "can you recommend any good self-catering apartments?": "вы можете порекомендовать хорошие съёмные квартиры?",
    "can you recommend any good youth hostels?": "вы можете порекомендовать хорошие молодежные хостелы?",
    "can you recommend any good campsites?": "вы можете порекомендовать хорошие места для кемпинга?",
    "how many stars does it have?": "сколько у него звёздочек?",
    "I'd like to stay in the city centre": "я хотел бы остановиться в центре города",
    "how much do you want to pay?": "сколько вы хотите заплатить?",
    "how far is it from the …?": "как далеко это от …?",
    "how far is it from the city centre?": "как далеко это от центра города?",
    "how far is it from the airport?": "как далеко это от аэропорта?",
    "how far is it from the railway station?": "как далеко это от железнодорожного вокзала?",
    "could I see your passport, please?": "пожалуйста, покажите ваш паспорт",
    "where have you travelled from?": "откуда вы прибыли?",
    "what's the purpose of your visit?": "какая цель вашего визита?",
    "I'm on holiday": "я в отпуске",
    "I'm on business": "это деловая поездка",
    "I'm visiting relatives": "я приехал к родственникам",
    "how long will you be staying?": "как долго вы собираетесь здесь пробыть?",
    "where will you be staying?": "где вы будете жить?",
    "you have to fill in this …": "вы должны заполнить …",
    "you have to fill in this landing card": "вы должны заполнить карту прибытия",
    "you have to fill in this immigration form": "вы должны заполнить иммиграционную карту",
    "enjoy your stay!": "хорошего пребывания!",
    "could you open your bag, please?": "откройте вашу сумку, пожалуйста",
    "do you have anything to declare?": "у вас есть что-нибудь, подлежащее декларации?",
    "you have to pay duty on these items": "вы должны уплатить за это пошлину",
    "EU citizens": "Граждане ЕС",
    "All passports": "Все паспорта",
    "Wait behind the yellow line": "Ждите за жёлтой чертой",
    "Please have your passport ready": "Пожалуйста, приготовьте паспорт",
    "Nothing to declare": "Нечего декларировать",
    "Goods to declare": "Вещи, подлежащие декларации",
    "what time's the next boat to …?": "во сколько следующий корабль на …?",
    "what time's the next boat to Calais?": "во сколько следующий корабль на Кале?",
    "I'd like a … cabin": "я хотел бы … каюту",
    "I'd like a two-berth cabin": "я хотел бы двух-местную каюту",
    "I'd like a four-berth cabin": "я хотел бы четырех-местную каюту",
    "we don't need a cabin": "нам не нужна каюта",
    "I'd like a ticket for a car and two passengers": "я хотел бы билет на машину и двух пассажиров",
    "I'd like a ticket for a foot passenger": "я хотел бы билет для пассажира",
}