slovar = {
    "could I use your phone?": "можно воспользоваться телефоном?",
    "your taxi's here": "твое такси здесь, ваше такси здесь",
    "thanks for coming": "спасибо, что зашел; спасибо, что зашли",
    "have a safe journey home": "безопасного возвращения домой",
    "that's fine, keep the change": "все в порядке, оставьте сдачу",
    "would you like a receipt?": "вы желаете чек?",
    "could I have a receipt, please?": "могу я получит чек, пожалуйста?",
    "could you pick me up here at …?": "могли бы вы забрать меня отсюда в …?",
    "could you pick me up here at six o'clock?": "могли бы вы забрать меня отсюда в шесть часов?",
    "six o'clock": "могли бы вы подождать меня здесь?",
    "Taxis": "Такси",
    "For hire": "Свободно",
    "OK": "ладно",
    "of course": "конечно",
    "of course not": "конечно нет",
    "that's fine": "хорошо",
    "that's right": "точно",
    "sure": "конечно",
    "certainly": "непременно",
    "definitely": "определенно",
    "absolutely": "безусловно",
    "as soon as possible": "как можно быстрее",
    "that's enough": "достаточно",
    "it doesn't matter": "это не важно",
    "it's not important": "это не важно",
    "it's not serious": "это не серьезно",
    "it's not worth it": "это того не стоит",
    "I'm in a hurry": "я тороплюсь",
    "I've got to go": "мне нужно идти",
    "I'm going out я": "собираюсь прогуляться",
    "sleep well": "спи хорошо",
    "same to you!": "и тебе того же!",
    "me too": "я(мне) тоже",
    "not bad": "неплохо",
    "I like …": "мне нравится …",
    "I like him": "мне нравится он",
    "I like her": "мне нравится она",
    "I like it": "мне нравится это",
    "I don't like …": "мне не нравится …",
    "I don't like him": "мне не нравится он",
    "I don't like her": "мне не нравится она",
    "I don't like it": "мне не нравится это",
    "thanks for your …": "спасибо за …",
    "thanks for your help": "спасибо за помощь",
    "thanks for your hospitality": "спасибо за гостепреимство",
    "thanks for your email": "спасибо за имейл",
    "I'm sorry": "извините",
    "I'm really sorry": "прошу прощения",
    "sorry I'm late": "извините за опоздание",
    "sorry to keep you waiting": "прошу прощения за задержку",
    "sorry for the delay": "извините за задержку",
    "look!": "посмотри!",
    "great!": "чудесно!",
    "come on!": "давай!",
    "only joking!": "шутка!",
    "just kidding!": "шутка!",
    "bless you!": "будь здоров! (после чихания)",
    "that's funny!": "прикольно!",
    "that's life!": "такова жизнь!",
    "that's funny, ...": "странно, ...",
}