slovar = {
    "what's the date today?": "какое сегодня число?",
    "what's today's date?": "какое сегодня число?",
    "15 October": "15 октября",
    "October 15": "15 октября",
    "Monday, 1 January": "понедельник, 1 января",
    "on 2 February": "2-го февраля",
    "at the beginning of July": "в начале июля",
    "in mid-December": "в середине декабря",
    "at the end of March": "в конце марта",
    "by the end of June": "до конца июня",
    "in 2007": "в 2007 г.",
    "AD": "нашей эры",
    "BC": "до нашей эры",
    "the 17th century": "семнадцатый век",
    "the 18th century": "восемнадцатый век",
    "the 19th century": "девятнадцатый век",
    "the 20th century": "двадцатый век",
    "the 21st century": "двадцать первый век",
    "1066 — Battle of Hastings": "1066 — Битва при Гастинге",
    "1776 — US Declaration of Independence": "1776 — Провозглашение независимости США",
    "1789-1799 — the French Revolution": "1789–1799 — Великая французская революция",
    "1939-1945 — Second World War": "1939–1945 — Вторая мировая война",
    "1989 — Fall of the Berlin Wall": "1989 — Падение Берлинской стены",
    "2012 — London Olympics": "2012 — Олимпиада в Лондоне",
    "44 BC — the death of Julius Caesar": "44 год до нашей эры — смерть Юлия Цезаря",
    "79 AD — eruption of Vesuvius": "79 год нашей эры — извержение Везувия",
    "what's the weather like?": "какая сейчас погода?",
    "it's sunny": "сейчас солнечно",
    "it's cloudy": "сейчас облачно",
    "it's windy": "сейчас ветренно",
    "it's foggy": "сейчас туман",
    "it's stormy": "сейчас буря",
    "it's …": "сейчас …",
    "it's raining": "сейчас идет дождь",
    "it's hailing": "сейчас идет град",
    "it's snowing": "сейчас идет снег",
    "what a nice day!": "какой чудесный день!",
    "what a beautiful day!": "какой прекрасный день!",
    "it's not a very nice day": "это не самый хороший день",
    "what a terrible day!": "какой ужасный день!",
    "what miserable weather!": "какая отвратительная погода!",
    "it's starting to rain": "начинается дождь",
    "it's stopped raining": "дождь закончился",
    "it's pouring with rain": "идет проливной дождь",
    "it's raining cats and dogs": "льет как из ведра",
    "the weather's fine": "отличная погода",
    "the sun's shining": "светит солнце",
    "there's not a cloud in the sky": "на небе ни облачка",
    "the sky's overcast": "небо затянуто облаками",
    "it's clearing up": "проясняется",
    "the sun's come out": "солнце вышло",
    "the sun's just gone in": "солнце зашло",
    "there's a strong wind": "дует сильный ветер",
    "the wind's dropped": "ветер прекратился",
    "that sounds like thunder": "похоже, гром гремит",
    "that's lightning": "молния сверкает",
    "we had a lot of heavy rain this morning": "этим утром шёл проливной дождь",
    "we haven't had any rain for a fortnight": "в течение двух недель не было дождя",
    "what's the temperature?": "какая сейчас температура?",
    "it's 22°C": "сейчас 22°C",
    "temperatures are in the mid-20s": "сейчас около двадцати пяти градусов",
    "what temperature do you think it is?": "как ты думаешь, какая сейчас температура?",
    "probably about 30°C": "возможно около 30°C",
    "it's hot": "сейчас жарко",
    "it's cold": "сейчас холодно",
    "it's baking hot": "сейчас очень жарко",
    "it's freezing": "сейчас очень холодно",
    "it's freezing cold": "сейчас очень холодно",
    "it's below freezing": "минусовая темрпература",
    "what's the forecast?": "какой прогноз погоды?",
    "what's the forecast like?": "какой прогноз погоды?",
    "it's forecast to rain": "будет дождь",
    "it's going to freeze tonight": "ночью будут заморозки",
    "it looks like rain": "похоже, что будет дождь",
    "it looks like it's going to rain": "похоже, что будет дождь",
    "we're expecting a thunderstorm": "ожидается буря",
    "it's supposed to clear up later": "скоро должно проясниться",
    "would anyone like a tea or coffee?": "кто-нибудь хочет чай или кофе?",
    "would anyone like a cup of tea?": "кто-нибудь хочет чашку чая?",
    "what's her name?": "как ее зовут?",
    "she's called …": "ее зовут …",
    "she's called Mary": "ее зовут Мери",
    "what are their names?": "как их зовут?",
    "they're called …": "их зовут …",
    "they're called Neil and Anna": "их зовут Нейл и Анна",
    "how old is he?": "сколько ему лет?",
    "he's …": "ему …",
    "he's twelve": "ему двенадцать",
    "how old is she?": "сколько ей лет?",
    "she's …": "ей …",
    "she's fifteen": "ей пятнадцать",
    "how old are they?": "сколько им лет?",
    "they're …": "им …",
    "they're six and eight": "им шесть и восемь",
    "I'm at Peter's": "я у Питера",
    "are you up to anything this evening?": "у тебя уже есть планы на вечер?",
    "have you got any plans for …?": "у тебя есть планы на …?",
    "have you got any plans for this evening?": "у тебя есть планы на этот вечер?",
    "have you got any plans for tomorrow?": "у тебя есть планы на завтра?",
    "have you got any plans for the weekend?": "у тебя есть планы на выходные?",
    "are you free …?": "ты свободен …?",
    "are you free this evening?": "ты свободен сегодня вечером?",
    "are you free tomorrow afternoon?": "ты свободен завтра днем?",
    "are you free tomorrow evening?": "ты свободен завтра вечером?",
    "what would you like to do this evening?": "чем бы ты хотел заняться сегодня вечером?",
    "do you want to go somewhere at the weekend?": "ты хочешь куда-нибудь поехать на выходных?",
    "would you like to join me for something to eat?": "ты хочешь вместе со мной поесть?",
    "do you fancy going out tonight?": "хочешь прогуляться сегодня вечером?",
}