slovar = {
    "help!": "помогите!",
    "be careful!": "будьте осторожны!",
    "look out!": "осторожно!",
    "watch out!": "осторожно!",
    "please help me": "пожалуйста, помогите мне",
    "call an ambulance!": "вызовите скорую помощь!",
    "I need a doctor": "мне нужен доктор",
    "there's been an accident": "произошел несчастный случай",
    "please hurry!": "пожалуйста, поторопитесь!",
    "I've cut myself": "я порезался",
    "I've burnt myself": "я обжегся",
    "are you OK?": "вы в порядке?",
    "is everyone OK?": "все в порядке?",
    "stop, thief!": "остановите вора!",
    "call the police!": "вызовите полицию!",
    "my wallet's been stolen": "мой кошелек украли",
    "my purse has been stolen": "мой сумочку украли",
    "my handbag's been stolen": "мою сумку украли",
    "my laptop's been stolen": "мой ноутбук украли",
    "my phone's been stolen": "мой телефон украли",
    "I'd like to report a theft": "я хотел бы заявить о краже",
    "my car's been broken into": "мою машину вскрыли",
    "I've been mugged": "меня ограбили",
    "I've been attacked": "на меня напали",
    "fire!": "пожар!",
    "call the fire brigade!": "вызовите пожарных!",
    "can you smell burning?": "вы чувствуете запах гари?",
    "there's a fire": "там пожар",
    "the building's on fire": "здание горит",
    "I'm lost": "я заблудился",
    "we're lost": "мы заблудились",
    "I can't find my …": "я не могу найти …",
    "I can't find my keys": "я не могу найти мои ключи",
    "I can't find my passport": "я не могу найти мой паспорт",
    "I can't find my mobile": "я не могу найти мой мобильный телефон",
    "I've lost my …": "я потерял …",
    "I've lost my wallet": "я потерял мой кошелек",
    "I've lost my purse": "я потерял мой бумажник",
    "I've lost my camera": "я потерял мой фотоаппарат",
    "I've locked myself out of my …": "моя … закрылась, а ключи внутри",
    "I've locked myself out of my car": "моя машина закрылась, а ключи внутри",
    "I've locked myself out of my room": "моя комната закрылась, а ключи внутри",
    "please leave me alone": "пожалуйста, оставьте меня в покое",
    "go away!": "уйдите!",

}