slovar = {
    "the day before yesterday": "позавчера",
    "yesterday": "вчера",
    "today": "сегодня",
    "tomorrow": "завтра",
    "the day after tomorrow": "послезавтра",
    "last night": "вчера вечером",
    "tonight": "сегодня вечером",
    "tomorrow night": "завтра вечером",
    "in the morning": "утром",
    "in the afternoon": "днем",
    "in the evening": "вечером",
    "yesterday morning": "вчера утром",
    "yesterday afternoon": "вчера днем",
    "yesterday evening": "вчера вечером",
    "this morning": "сегодня утром",
    "this afternoon": "сегодня днем",
    "this evening": "сегодня вечером",
    "tomorrow morning": "завтра утром",
    "tomorrow afternoon": "завтра днем",
    "tomorrow evening": "завтра вечером",
    "last week": "на прошлой неделе",
    "last month": "в прошлом месяце",
    "last year": "в прошлом году",
    "this week": "на этой неделе",
    "this month": "в этом месяце",
    "this year": "в этом году",
    "next week": "на следующей неделе",
    "next month": "в следующем месяце",
    "next year": "в следующем году",
    "five minutes ago": "пять минут назад",
    "an hour ago": "час назад",
    "a week ago": "неделю назад",
    "two weeks ago": "две недели назад",
    "a month ago": "месяц назад",
    "a year ago": "год назад",
    "a long time ago": "давным-давно",
    "in ten minutes' time": "через десять минут",
    "in ten minutes": "через десять минут",
    "in an hour's time": "через час",
    "in an hour": "через час",
    "in a week's time": "через неделю",
    "in a week": "через неделю",
    "in ten days' time": "через десять дней",
    "in ten days": "через десять дней",
    "in three weeks' time": "через три недели",
    "in three weeks": "через три недели",
    "in two months' time": "через два месяца",
    "in two months": "через два месяца",
    "in ten years' time": "через десять лет",
    "in ten years": "через десять лет",
    "the previous day": "в предыдущий день",
    "the previous week": "на предыдущей неделе",
    "the previous month": "в предыдущем месяце",
    "the previous year": "в предыдущем году",
    "the following day": "на следующий день",
    "the following week": "на следующей неделе",
    "the following month": "в следующем месяце",
    "the following year": "в следующем году",
    "_I lived in Canada for six months": "я жил в Канаде шесть месяцев",
    "I've worked here for nine years": "я работаю здесь девять лет",
    "I'm going to France tomorrow for two weeks": "завтра я уезжаю во Францию на две недели",
    "we were swimming for a long time": "мы долго плавали",
}