slovar = {
    "I'd like a room with a sea view": "я хотел бы номер с видом на море",
    "I'd like a room with a balcony": "я хотел бы номер с балконом",
    "I'd like …": "я хотел бы …",
    "I'd like half board": "я хотел бы половину пансиона",
    "I'd like full board": "я хотел бы полный пансион",
    "could we have an extra bed?": "мы хотели бы дополнительную кровать",
    "does the room have …?": "есть ли в комнате …?",
    "does the room have internet access?": "есть ли в комнате интернет?",
    "does the room have air conditioning?": "есть ли в комнате кондиционер?",
    "does the room have television?": "есть ли в комнате телевизор?",
    "is there a …?": "есть ли тут …?",
    "is there a swimming pool?": "есть ли тут бассейн?",
    "is there a sauna?": "есть ли тут сауна?",
    "is there a gym?": "есть ли тут спортзал?",
    "is there a beauty salon?": "есть ли тут салон красоты?",
    "is there a lift?": "есть ли тут лифт?",
    "do you allow pets?": "здесь можно держать домашних животных?",
    "do you have wheelchair access?": "у вас есть вход для инвалидной коляски?",
    "do you have a car park?": "у вас есть автомобильная стоянка?",
    "the room has a shared bathroom": "туалет и ванная общие",
    "what's the price per night?": "сколько стоит одна ночь?",
    "is breakfast included?": "включен ли завтрак?",
    "that's a bit more than I wanted to pay": "это не много больше, чем я готов заплатить",
    "can you offer me any discount?": "вы можете сделать скидку?",
    "have you got anything …?": "у вас есть что-нибудь …?",
    "have you got anything cheaper?": "у вас есть что-нибудь подешевле?",
    "have you got anything bigger?": "у вас есть что-нибудь побольше?",
    "have you got anything quieter?": "у вас есть что-нибудь поспокойней?",
    "could I see the room?": "мог бы я посмотреть комнату?",
    "OK, I'll take it": "хорошо, я беру",
    "I'd like to make a reservation": "я хотел бы забронировать",
    "what's your name, please?": "ваше имя, пожалуйста",
    "could I take your name?": "назовите ваше имя",
    "can I take your …?": "назовите ваш …",
    "can I take your credit card number?": "назовите ваш номер кредитки",
    "can I take your telephone number?": "назовите ваш номер телефона",
    "what time will you be arriving?": "во сколько вы приедете?",
    "Vacancies": "Свободные места",
    "No vacancies": "Свободных мест нет",
    "can you recommend any good …?": "вы можете порекомендовать хорошие …?",
    "can you recommend any good hotels?": "вы можете порекомендовать хорошие гостиницы?",
    "can you recommend any good B&Bs?": "вы можете порекомендовать хорошие B&Bs (небольшие бюджетные гостиницы, в цену включен завтрак)?",
    "can you recommend any good self-catering apartments?": "вы можете порекомендовать хорошие съёмные квартиры?",
    "can you recommend any good youth hostels?": "вы можете порекомендовать хорошие молодежные хостелы?",
    "can you recommend any good campsites?": "вы можете порекомендовать хорошие места для кемпинга?",
    "how many stars does it have?": "сколько у него звёздочек?",
    "I'd like to stay in the city centre": "я хотел бы остановиться в центре города",
    "how much do you want to pay?": "сколько вы хотите заплатить?",
    "how far is it from the …?": "как далеко это от …?",
    "how far is it from the city centre?": "как далеко это от центра города?",
    "how far is it from the airport?": "как далеко это от аэропорта?",
    "how far is it from the railway station?": "как далеко это от железнодорожного вокзала?",
    "could I see your passport, please?": "пожалуйста, покажите ваш паспорт",
    "where have you travelled from?": "откуда вы прибыли?",
    "what's the purpose of your visit?": "какая цель вашего визита?",
    "I'm on holiday": "я в отпуске",
    "I'm on business": "это деловая поездка",
    "I'm visiting relatives": "я приехал к родственникам",
    "how long will you be staying?": "как долго вы собираетесь здесь пробыть?",
    "where will you be staying?": "где вы будете жить?",
    "you have to fill in this …": "вы должны заполнить …",
    "you have to fill in this landing card": "вы должны заполнить карту прибытия",
    "you have to fill in this immigration form": "вы должны заполнить иммиграционную карту",
    "enjoy your stay!": "хорошего пребывания!",
    "could you open your bag, please?": "откройте вашу сумку, пожалуйста",
    "do you have anything to declare?": "у вас есть что-нибудь, подлежащее декларации?",
    "you have to pay duty on these items": "вы должны уплатить за это пошлину",
    "EU citizens": "Граждане ЕС",
    "All passports": "Все паспорта",
    "Wait behind the yellow line": "Ждите за жёлтой чертой",
    "Please have your passport ready": "Пожалуйста, приготовьте паспорт",
    "Nothing to declare": "Нечего декларировать",
    "Goods to declare": "Вещи, подлежащие декларации",
    "what time's the next boat to …?": "во сколько следующий корабль на …?",
    "what time's the next boat to Calais?": "во сколько следующий корабль на Кале?",
    "I'd like a … cabin": "я хотел бы … каюту",
    "I'd like a two-berth cabin": "я хотел бы двух-местную каюту",
    "I'd like a four-berth cabin": "я хотел бы четырех-местную каюту",
    "we don't need a cabin": "нам не нужна каюта",
    "I'd like a ticket for a car and two passengers": "я хотел бы билет на машину и двух пассажиров",
    "I'd like a ticket for a foot passenger": "я хотел бы билет для пассажира",
    "how long does the crossing take?": "как долго продлится рейс?",
    "what time does the ferry arrive in …?": "во сколько паром прибывает в …?",
    "what time does the ferry arrive in Stockholm?": "во сколько паром прибывает в Стокгольм?",
    "how soon before the departure time do we have to arrive?": "за какое время до отправления мы должны приехать?",
    "where's the information desk?": "где находится информационный пункт?",
    "where's cabin number …?": "где каюта номер …?",
    "where's cabin number 258?": "где каюта номер 258?",
    "which deck's the … on?": "на какой палубе находится …?",
    "which deck's the buffet on?": "на какой палубе находится буфет?",
    "which deck's the restaurant on?": "на какой палубе находится ресторан?",
    "which deck's the bar on?": "на какой палубе находится бар?",
    "which deck's the shop on?": "на какой палубе находится магазин?",
    "which deck's the cinema on?": "на какой палубе находится кино?",
    "which deck's the bureau de change on?": "на какой палубе находится пункт обмена валюты?",
    "I feel seasick": "у меня морская болезнь",
    "the sea's very rough": "на море шторм",
    "the sea's quite calm": "на море довольно спокойно",
    "all car passengers, please make your way down to the car decks for disembarkation": "все пассажиры, пожалуйста проследуйте на автомобильную палубу для высадки",
    "we will be arriving in port in approximately 30 minutes' time": "мы прибудем в порт примерно через 30 минут",
    "please vacate your cabins": "пожалуйста, освободите каюты",
    "Cabin": "Каюта",
    "Deck": "Палуба",
    "Stairs": "Лестница",
    "Information": "Информация",
    "Restaurant": "Ресторан",
    "Cinema": "Кино",
    "Shop": "Магазин",
    "Lifejackets": "Спасательные жилеты",
    "I've come to collect my tickets": "я хотел бы забрать свой билет",
    "I booked on the internet": "я заказал билет в интернете",
    "do you have your booking reference?": "у вас есть код брони?",
    "your passport and ticket, please": "ваш паспорт и билет, пожалуйста",
    "here's my booking reference": "это мой код бронирования",
    "where are you flying to?": "куда вы летите?",
    "did you pack your bags yourself?": "вы сами упаковывали свои вещи?",
    "has anyone had access to your bags in the meantime?": "кто-нибудь имел доступ к вашим вещам?",
    "do you have any liquids or sharp objects in your hand baggage?": "в важем багаже есть жидкости или острые предметы?",
    "how many bags are you checking in?": "сколько сумок вы сдаёте?",
    "could I see your hand baggage, please?": "покажите вашу ручную кладь, пожалуйста",
    "do I need to check this in or can I take it with me?": "я должен это сдать или могу взять с собой?",
}