slovar = {
    "I'm just browsing, thanks": "я просто присматриваюсь, спасибо",
    "how much is this?": "сколько за это?",
    "how much are these?": "сколько за эти?",
    "how much does this cost?": "сколько это стоит?",
    "how much is that … in the window?": "сколько стоит … на витрине?",
    "how much is that lamp in the window?": "сколько стоит лампа на витрине?",
    "that's cheap": "это дешево",
    "that's good value": "это подходящая цена",
    "that's expensive": "это дорого",
    "do you sell …?": "вы продаёте …?",
    "do you sell stamps?": "вы продаёте марки?",
    "do you have any …?": "у вас есть какие-нибудь …?",
    "do you have any postcards?": "у вас есть какие-нибудь открытки?",
    "sorry, we don't sell them": "извините, их нет в продаже",
    "sorry, we don't have any left": "извините, их не осталось",
    "I'm looking for …": "я ищу …",
    "I'm looking for the shampoo": "я ищу шампунь",
    "I'm looking for a birthday card": "я ищу поздравительную открытку",
    "could you tell me where the … is?": "могли бы вы сказать, где …?",
    "could you tell me where the washing up liquid is?": "могли бы вы сказать, где моющее средство?",
    "where can I find the …?": "где я могу найти …?",
    "where can I find the toothpaste?": "где я могу найти зубную пасту?",
    "have you got anything cheaper?": "у вас есть что-нибудь подешевле?",
    "it's not what I'm looking for": "это не то, что я ищу",
    "do you have this item in stock?": "у вас есть это в продаже?",
    "do you know anywhere else I could try?": "вы знаете, где ещё можно посмотреть?",
    "does it come with a guarantee?": "есть ли на это гарантия?",
    "it comes with a one year guarantee": "на это один год гарантии",
    "do you deliver?": "вы делаете доставку?",
    "I'll take it": "я это возьму",
    "anything else?": "что-то ещё?",
    "would you like anything else?": "желаете что-нибудь ещё?",
    "are you in the queue?": "вы в очереди?",
    "next, please!": "следующий, пожалуйста",
    "do you take credit cards?": "вы принимаете кредитные карточки?",
    "I'll pay in cash": "я заплачу наличными",
    "I'll pay by card": "я заплачу карточкой",
    "could I have a receipt, please?": "могу я получить чек, пожалуйста?",
    "would you be able to gift wrap it for me?": "вы сможете упаковать это как подарок?",
    "would you like a bag?": "вам нужен пакет?",
    "I'd like to return this": "я хотел бы вернуть это",
    "I'd like to change this for a different size": "я хотел бы поменять это на другой размер",
    "it doesn't work": "это не работает",
    "it doesn't fit": "это не подходит",
    "could I have a refund?": "могу я получить деньги обратно?",
    "have you got the receipt?": "у вас есть чек?",
    "could I speak to the manager?": "могу я поговорить с менеджером?",
    "Open": "Открыто",
    "Closed": "Закрыто",
    "Open 24 hours a day": "Открыто 24 часа в день",
    "Special offer": "Спецпредложение",
    "Sale": "Распродажа",
    "Clearance sale": "Окончательная распродажа",
    "Closing down sale": "Распродажа по поводу закрытия",
    "Good value": "Выгодная цена",
    "Buy 1 get 1 free": "Купи 1, получи 1 бесплатно",
    "Buy 1 get 1 half price": "Купи 1, получи 1 за полцены",
    "Reduced to clear": "Уценено (потому что необходимо продать)",
    "Half price": "Полцены",
    "Out to lunch": "Ушёл на обед",
    "Back in 15 minutes": "Вернусь через 15 минут",
    "Shoplifters will be prosecuted": "Воры будут наказаны",
    "Enter your PIN": "Введите пин-код",
    "Please wait": "Пожалуйста, подождите",
    "Remove card": "Заберите карточку",
    "Signature": "Подпись",
    "do you have any free tables?": "у вас есть свободные столики?",
    "a table for …, please": "столик на …, пожалуйста",
    "a table for two, please": "столик на двоих, пожалуйста",
    "a table for three, please": "столик на троих, пожалуйста",
    "a table for four, please": "столик на четверых, пожалуйста",
    "I'd like to make a reservation": "я хотел бы зарезервировать",
    "I'd like to book a table, please": "я хотел бы заказать столик, пожалуйста",
    "when for?": "на когда?",
    "for what time?": "на какое время?",
    "this evening at …": "сегодня вечером в …",
    "this evening at seven o'clock": "сегодня вечером в семь часов",
    "this evening at seven thirty": "сегодня вечером в семь тридцать",
    "this evening at eight o'clock": "сегодня вечером в восемь часов",
    "this evening at eight thirty": "сегодня вечером в восемь тридцать",
    "tomorrow at …": "затра в …",
    "tomorrow at noon": "затра в полдень",
    "tomorrow at twelve thirty": "затра в двенадцать тридцать",
    "tomorrow at one o'clock": "затра в час",
    "tomorrow at one thirty": "затра в час тридцать",
    "for how many people?": "на сколько людей?",
    "I've got a reservation": "у меня зарезервировано",
    "do you have a reservation?": "у вас зарезервировано?",
    "could I see the menu, please?": "могу я посмотреть меню, пожалуйста?",
    "could I see the wine list, please?": "могу я посмотреть карту вин, пожалуйста?",
    "can I get you any drinks?": "могу я принести вам что-нибудь выпить?",
    "are you ready to order?": "вы готовы заказать?",
    "do you have any specials?": "у вас есть специальные блюда?",
    "what's the soup of the day?": "какой сегодня суп?",
    "what do you recommend?": "что вы порекомендуете?",
    "what's this dish?": "что это за блюдо?",
    "I'm on a diet": "я на диете",
    "I'm allergic to …": "у меня аллергия на …",
    "I'm allergic to wheat": "у меня аллергия на пшеницу",
    "I'm allergic to dairy products": "у меня аллергия на молочные продукты",
    "I'm severely allergic to …": "у меня сильная аллергия на …",
    "I'm severely allergic to nuts": "у меня сильная аллергия на орехи",
    "I'm severely allergic to shellfish": "у меня сильная аллергия на моллюски",
    "I'm a vegetarian": "я вегетарианец / вегетарианка",
    "I don't eat …": "я не ем …",
    "I don't eat meat": "я не ем мясо",
    "I don't eat pork": "я не ем свинину",
    "I'll have the …": "я буду …",
    "I'll have the chicken breast": "я буду куриные грудки",
    "I'll have the roast beef": "я буду ростбиф",
    "I'll have the pasta": "я буду макароны",
    "I'll take this": "я возьму это",
    "I'm sorry, we're out of that": "извините, у нас это закончилось",
    "for my starter I'll have the soup, and for my main course the steak": "для начала я возьму суп, а как основное блюдо — кусок мяса",
    "how would you like your steak?": "какой прожарки вы желаете мясо?",
    "rare": "с кровью",
    "medium-rare": "немного с кровью",
    "medium": "средней прожарки",
}