slovar = {
    "come on in!": "входи!, входите!",
    "good to see you!": "рад тебя видеть, рад вас видеть",
    "you're looking well": "ты прекрасно выглядишь, вы прекрасно выглядите",
    "please take your shoes off": "пожалуйста, сними обувь, пожалуйста, снимите обувь",
    "can I take your coat?": "я возьму твое пальто",
    "sorry we're late": "извини, мы опоздали",
    "did you have a good journey?": "ты хорошо добрался?, вы хорошо добрались?",
    "did you find us alright?": "ты нашел нас без проблем?, вы нашли нас без проблем?",
    "I'll show you your room": "я покажу твою комнату, я покажу вашу комнату",
    "this is your room": "это твоя комната, это ваша комната",
    "would you like a towel?": "тебе нужно полотенце?",
    "make yourself at home": "чувствуй себя как дома, чувствуйте себя как дома",
    "can I get you anything to drink?": "хочешь что-нибудь выпить?, хотите что-нибудь выпить?",
    "would you like a tea or coffee?": "хочешь чай или кофе?, хотите чай или кофе?",
    "how do you take it?": "с чем ты хочешь?",
    "do you take sugar?": "сколько положить сахара?",
    "do you take milk?": "тебе нужно молоко?",
    "how many sugars do you take?": "сколько положить сахара?",
    "would you like a …?": "хочешь …?",
    "would you like a soft drink?": "хочешь попить (буквально: безалкогольный напиток)?",
    "would you like a beer?": "хочешь пиво?",
    "would you like a glass of wine?": "хочешь бокал вина?",
    "would you like a gin and tonic?": "хочешь джин с тоником?",
    "have a seat!": "садись!, садитесь!",
    "let's go into the …": "давай(те) пойдем в …",
    "let's go into the lounge": "давай(те) пойдем в гостиную",
    "let's go into the living room": "давай(те) пойдем в гостиную",
    "let's go into the dining room": "давай(те) пойдем в столовую",
    "do you mind if I smoke here?": "ты не против, если я здесь закурю?",
    "I'd prefer it if you went outside": "будет лучше, если ты выйдешь на улицу",
    "are you ready to eat now?": "ты готов есть?, вы готовы есть?",
    "who's driving tonight?": "кто сегодня за рулем?",
    "could I use your phone?": "можно воспользоваться телефоном?",
    "your taxi's here": "твое такси здесь, ваше такси здесь",
    "thanks for coming": "спасибо, что зашел; спасибо, что зашли",
    "have a safe journey home": "безопасного возвращения домой",
    "thanks for a lovely evening": "спасибо за прекрасный вечер",
    "where's the ticket office?": "где находятся кассы?",
    "where do I get the … to Southampton from?": "откуда отправляется … на Саусэмптон?",
    "where do I get the bus to Southampton from?": "откуда отправляется автобус на Саусэмптон?",
    "where do I get the train to Southampton from?": "откуда отправляется поезд на Саусэмптон?",
    "where do I get the ferry to Southampton from?": "откуда отправляется паром на Саусэмптон?",
    "what time's the next … to Portsmouth?": "во сколько следующий … на Портмут?",
    "what time's the next bus to Portsmouth?": "во сколько следующий автобус на Портмут?",
    "what time's the next train to Portsmouth?": "во сколько следующий поезд на Портмут?",
    "what time's the next ferry to Portsmouth?": "во сколько следующий паром на Портмут?",
    "this … has been cancelled": "этот … отменили",
    "this bus has been cancelled": "этот автобус отменили",
    "this train has been cancelled": "этот поезд отменили",
    "this flight has been cancelled": "этот рейс (вылет) отменили",
    "this ferry has been cancelled": "этот паром отменили",
    "this … has been delayed": "этот … задерживается",
    "this bus has been delayed": "этот автобус задерживается",
    "this train has been delayed": "этот поезд задерживается",
    "this flight has been delayed": "этот рейс (вылет) задерживается",
    "this ferry has been delayed": "этот паром задерживается",
    "have you ever been to …?": "ты когда-нибудь был в …?",
    "have you ever been to Italy?": "ты когда-нибудь был в Италии?",
    "yes, I went there on holiday": "да, я ездил туда в отпуск",
    "no, I've never been there": "нет, я никогда там не был",
    "I've never been, but I'd love to go someday": "никогда там не был, но очень хочу съездить",
    "how long does the journey take?": "как долго продлится путешествие?",
    "what time do we arrive?": "во сколько мы прибываем?",
    "do you get travel sick?": "тебе становится плохо в дороге?",
    "have a good journey!": "хорошей поездки!",
    "enjoy your trip!": "хорошего путешествия!",
    "I'd like to travel to …": "я хотел бы поехать в …",
    "I'd like to travel to Spain": "я хотел бы поехать в Испанию",
    "I'd like to book a trip to …": "я хотел бы забронировать путевку в …",
    "I'd like to book a trip to Berlin": "я хотел бы забронировать путевку в Берлин",
    "how much are the flights?": "сколько стоит перелет?",
    "do you have any brochures on …?": "у вас есть какие-нибудь брошюры о …?",
    "do you have any brochures on Switzerland?": "у вас есть какие-нибудь брошюры о Швейцарии?",
    "do I need a visa for …?": "мне нужна виза в …?",
    "do I need a visa for Turkey?": "мне нужна виза в Турцию?",
    "do you have any plans for the summer?": "у тебя есть планы на лето?",
    "what are you doing for …?": "что ты делаешь на …?",
    "what are you doing for Christmas?": "что ты делаешь на Рождество?",
    "what are you doing for New Year?": "что ты делаешь на Новый год?",
    "what are you doing for Easter?": "что ты делаешь на Пасху?",
    "I share with one other person": "я живу с одним человеком",
    "I share with … others": "я живу с … другими",
    "I share with two others": "я живу с двумя другими",
    "I share with three others": "я живу с тремя другими",
    "what's your phone number?": "какой у тебя номер телефона?",
    "what's your email address?": "какой у тебя электронный адрес?",
    "what's your address?": "какой твой адрес?",
    "could I take your phone number?": "можно записать твой номер телефона?",
    "could I take your email address?": "можно записать твой электронный адрес?",
    "are you on …?": "ты зарегистрирован в …?",
    "are you on Facebook?": "ты зарегистрирован в Facebook?",
    "are you on Skype?": "ты зарегистрирован в Skype?",
    "what's your username?": "какое у тебя там имя?",
    "have you got any pets?": "у тебя есть домашние животные?",
    "I've got …": "у меня …",
    "I've got a dog and two cats": "у меня собака и две кошки",
    "I've got a Labradorу": "меня лабрадор",
    "what's his name?": "как его зовут?",
    "he's called …": "его зовут …",
    "he's called Tom": "его зовут Том",
}