slovar = {
    "can you recommend a good restaurant?": "вы можете порекоммендовать хороший ресторан?",
    "where can I get a taxi?": "где я могу поймать такси?",
    "excuse me, where's …?": "извините, где находится …?",
    "excuse me, where's the tourist information office?": "извините, где находится пункт туристической информации?",
    "excuse me, where's the bus station?": "извините, где находится автобусная станция?",
    "excuse me, where's the train station?": "извините, где находится железнодорожная станция?",
    "excuse me, where's the police station?": "извините, где находится полицейский участок?",
    "excuse me, where's the harbour?": "извините, где находится порт?",
    "is there a … near here?": "есть ли тут неподалёку …?",
    "is there a cashpoint near here?": "есть ли тут неподалёку банкомат?",
    "is there a bank near here?": "есть ли тут неподалёку банк?",
    "is there a supermarket near here?": "есть ли тут неподалёку супермаркет?",
    "is there a hairdressers near here?": "есть ли тут неподалёку парикмахерская?",
    "is there a chemists near here?": "есть ли тут неподалёку аптека?",
    "do you know where there's an internet café?": "вы не знаете, где здесь интернет-кафе?",
    "do you know where the … embassy is?": "вы знаете, где находится … посольство?",
    "do you know where the Japanese embassy is?": "вы знаете, где находится японское посольство?",
    "do you know where the Russian embassy is?": "вы знаете, где находится российское посольство?",
    "Town centre": "Центр города",
    "Hospital": "Больница",
    "Public library": "Публичная библиотека",
    "Post office": "Почта",
    "Keep off the grass": "По траве не ходить",
    "Wet paint": "Окрашено",
    "Look left": "Посмотрите налево",
    "Look right": "Посмотрите направо",
    "do you know where I can get my … repaired?": "вы не знаете, где я могу отремонтировать …?",
    "do you know where I can get my phone repaired?": "вы не знаете, где я могу отремонтировать телефон?",
    "do you know where I can get my watch repaired?": "вы не знаете, где я могу отремонтировать часы?",
    "do you know where I can get my camera repaired?": "вы не знаете, где я могу отремонтировать фотоаппарат?",
    "do you know where I can get my shoes repaired?": "вы не знаете, где я могу отремонтировать обувь?",
    "the screen’s broken": "экран треснул",
    "there's something wrong with …": "что-то не в порядке с …",
    "there's something wrong with my watch": "что-то не в порядке с моими часами",
    "there's something wrong with this radio": "что-то не в порядке с этим радио",
    "do you do … repairs?": "вы ремонтируете …?",
    "do you do television repairs?": "вы ремонтируете телевизоры?",
    "do you do computer repairs?": "вы ремонтируете компьютеры?",
    "do you do laptop repairs?": "вы ремонтируете ноутбуком?",
    "when will it be ready?": "когда это будет готово?",
    "I can do it straight away": "я могу это сразу сделать",
    "it'll be ready …": "это будет готово …",
    "it'll be ready by tomorrow": "это будет готово завтра",
    "it'll be ready next week": "это будет готово на следующей неделе",
    "I won't be able to do it for at least two weeks": "я не смогу это сделать ещё по меньшей мере две недели",
    "are you able to repair it?": "вы можете это отремонтировать?",
    "we can't do it here": "мы не можем это здесь сделать",
    "we're going to have to send it back to the manufacturers": "мы собираемся отправить это обратно изготовителю",
    "it's not worth repairing": "это не стоит ремонта",
    "my watch has stopped": "мои часы остановились",
    "can I have a look at it?": "могу я посмотреть?",
    "I think it needs a new battery": "я думаю, нужна новая батарейка",
    "I've come to collect my …": "я пришел забрать …",
    "I've come to collect my watch": "я пришел забрать часы",
    "I've come to collect my computer": "я пришел забрать компьютер",
    "could you print the photos on this memory card for me?": "вы могли бы распечать фотографии с этой карты памяти?",
    "could you print the photos on this memory stick for me?": "вы могли бы распечатать фотографии с этой флешки?",
    "would you like matt or gloss prints?": "вы хотите матовые или глянцевые снимки?",
    "what size prints would you like?": "какого размера фотографии вы бы хотели?",
    "could I have this suit cleaned?": "вы могли бы почистить этот костюм?",
    "could you take these trousers up an inch?": "могли бы вы укоротить эти брюки на дюйм?",
    "could you take these trousers down an inch?": "могли бы вы удленить эти брюки на дюйм?",
    "could you take these trousers in an inch?": "могли бы вы ушить эти брюки на дюйм?",
    "could you take these trousers out two inches?": "могли бы вы расширить эти брюки на два дюйма?",
    "could I have these shoes repaired?": "могли бы вы отремонтировать эту обувь?",
    "could you put new … on these shoes for me?": "могли вы сделать новые … для этих ботинок?",
    "could you put new heels on these shoes for me?": "могли вы сделать новые каблуки для этих ботинок?",
    "could you put new soles on these shoes for me?": "могли вы сделать новые подметки для этих ботинок?",
    "could I have this key cut?": "могли бы вы сделать такой ключ?",
    "could I have these keys cut?": "могли бы вы сделать такие ключи?",
    "I'd like one copy of each of these, please": "сделайте по одной копии каждого экземпляра, пожалуйста",
    "could I have a key ring?": "я хотел бы брелок для ключей",
    "could I try this on?": "можно это примерить?",
    "could I try these on?": "можно это примерить? (для обуви, брюк или когда вы хотите примерить несколько вещей)",
    "could I try these shoes on?": "могу я примерить эти ботинки?",
    "do you want to try it on?": "вы хотите это примерить?",
    "do you want to try them on?": "вы хотите их примерить?",
    "what size are you?": "какой у вас размер?",
    "what size do you take?": "какой размер вы возьмёте?",
    "I take a size …": "я возьму размер …",
    "I take a size 10": "я возьму размер 10",
    "do you have this in a size …?": "у вас есть это размера …?",
    "do you have this in a size 7?": "у вас есть это размера 7?",
    "do you have these in a size …?": "у вас есть это размера …?",
    "do you have these in a size 12?": "у вас есть это размера 12?",
    "do you have a fitting room?": "у вас есть примерочная?",
    "where's the fitting room?": "где находится примерочная?",
    "have you got this in a smaller size?": "у вас есть это размером меньше?",
    "have you got this in a larger size?": "у вас есть это размером больше?",
    "could you measure my …?": "вы можете измерить мне …?",
    "could you measure my waist?": "вы можете измерить мне бёдра?",
    "could you measure my neck?": "вы можете измерить мне шею?",
    "could you measure my chest?": "вы можете измерить мне грудь?",
    "is that a good fit?": "хорошо это сидит?",
    "it's much too small": "это слишком сильно мало",
    "it's a little too small": "это немного мало",
    "it's a little too big": "это немного велико",
    "it's much too big": "это слишком сильно велико",
    "it's just right": "это как раз подходит",
    "they're just right": "это как раз подходит",
    "they don't fit": "они не подходят",
    "how do they feel?": "как вам в них?",
    "do they feel comfortable?": "вам в них удобно?",
    "it suits you": "это идёт вам",
    "they suit you": "это идёт вам",
    "is this the only colour you've got?": "это только такого цвета?",
    "what do you think of these?": "что вы думаете об этом?",
    "I like them": "мне нравятся",
    "I don't like them": "мне не нравятся",
    "I don't like the colour": "мне не нравится цвет",
    "what are these made of?": "из чего это сделано?",
    "are these washable?": "это можно стирать?",
    "no, they have to be dry-cleaned": "нет, это надо чистить в химчистке",
    "I'll take them": "я возьму",
    "I'll take these": "я возьму эти",
    "Menswear": "Мужская одежда",
}