slovar = {
    "Go to Gate ...": "Пройдите к воротам ...",
    "Now boarding": "Посадка",
    "Last call": "Последний вызов",
    "Gate closing": "Ворота закрываются",
    "Gate closed": "Ворота закрыты",
    "Departed": "Вылетел",
    "Arrivals board": "Прибывающие рейсы",
    "Expected 23:25": "Ожидается в 23:25",
    "Landed 09:52": "Приземлился в 09:52",
    "where's the ticket office?": "где находятся кассы?",
    "where are the ticket machines?": "где находятся билетные автоматы?",
    "what time's the next bus to …?": "во сколько идет следующий автобус на …?",
    "what time's the next bus to Camden?": "во сколько идет следующий автобус на Камден?",
    "Camden": "во сколько идет следующий поезд на …?",
    "can I buy a ticket on the bus?": "можно купить билет в автобусе?",
    "can I buy a ticket on the train?": "можно купить билет в поезде?",
    "how much is a … to London?": "сколько стоит … до Лондона?",
    "how much is a single to London?": "сколько стоит билет в один конец до Лондона?",
    "how much is a return to London?": "сколько стоит билет в оба конца до Лондона?",
    "how much is a first class single to London?": "сколько стоит билет первого класса в один конец до Лондона?",
    "how much is a first class return to London?": "сколько стоит билет первого класса в оба конца до Лондона?",
    "I'd like a … to Bristol": "я хотел бы … до Бристоля",
    "I'd like a single to Bristol": "я хотел бы билет в один конец до Бристоля",
    "I'd like a return to Bristol": "я хотел бы билет в оба конца до Бристоля",
    "I'd like a child single to Bristol": "я хотел бы детский билет в один конец до Бристоля",
    "I'd like a child return to Bristol": "я хотел бы детский билет в оба конца до Бристоля",
    "I'd like a senior citizens' single to Bristol": "я хотел бы пенсионерский билет в один конец до Бристоля",
    "I'd like a senior citizens' return to Bristol": "я хотел бы пенсионерский билет в оба конца до Бристоля",
    "I'd like a first class single to Bristol": "я хотел бы билет первого класса в один конец до Бристоля",
    "I'd like a first class return to Bristol": "я хотел бы билет первого класса в оба конца до Бристоля",
    "are there any reductions for off-peak travel?": "есть ли скидки на билеты не в час-пик?",
    "when would you like to travel?": "когда вы хотели бы выехать?",
    "when will you be coming back?": "когда вы хотели бы вернуться?",
    "I'd like a return to …, coming back on Sunday": "я хотел бы билет в оба конца до …, с возвратом в воскресенье",
    "I'd like a return to Newcastle, coming back on Sunday": "я хотел бы билет в оба конца до Ньюкасла, с возвратом в воскресенье",
    "which platform do I need for …?": "какая платформа на …?",
    "which platform do I need for Manchester?": "какая платформа на Манчестер?",
    "is this the right platform for …?": "это правильная платформа для …?",
    "is this the right platform for Cardiff?": "это правильная платформа для Кардиффа?",
    "where do I change for …?": "где мне надо сделать пересадку на …?",
    "where do I change for Exeter?": "где мне надо сделать пересадку на Эксетер?",
    "you'll need to change at …": "вам надо сделать пересадку в …",
    "you'll need to change at Reading": "вам надо сделать пересадку в Рединге",
    "can I have a timetable, please?": "не могли бы вы дать мне расписание, пожалуйста?",
    "how often do the buses run to …?": "как часто ходят автобусы на …?",
    "how often do the buses run to Bournemouth?": "как часто ходят автобусы на Борнмут?",
    "how often do the trains run to …?": "как часто ходят поезда на …?",
    "how often do the trains run to Coventry?": "как часто ходят поезда на Ковентри?",
    "I'd like to renew my season ticket, please": "я хотел бы продлить сезонный билет, пожалуйста",
    "the next train to arrive at Platform 2 is the 16.35 to Doncaster": "следующий поезд, прибывающий на вторую платформу, отправляется в 16:35 в Донкастер",
    "Platform 11 for the 10.22 to Guildford": "платформа 11 в 10:22 на Гилдфорд",
    "the next train to depart from Platform 5 will be the 18.03 service to Penzance": "следующий поезд, отправляющийся с пятой платформы, это рейс в 18:03 на Пензанс",
    "the train's running late": "поезд опаздывает",
    "the train's been cancelled": "поезд был отменен",
    "does this bus stop at …?": "останавливается ли этот автобус в …?",
    "does this bus stop at Trafalgar Square?": "останавливается ли этот автобус в Трафальгарской площади?",
    "does this train stop at …?": "останавливается ли этот поезд в …?",
    "does this train stop at Leicester?": "останавливается ли этот поезд в Лейчестере?",
    "could I put this in the hold, please?": "могу я положить это в багаж, пожалуйста?",
    "could you tell me when we get to …?": "скажите мне, пожалуйста, когда мы доедем до …",
    "could you tell me when we get to the university?": "скажите мне, пожалуйста, когда мы доедем до университета",
    "could you please stop at …?": "остановитесь, пожалуйста, в …",
    "could you please stop at the airport?": "остановитесь, пожалуйста, в аэропорту",
    "is this seat free?": "это место свободно?",
    "is this seat taken?": "это место занято?",
    "do you mind if I sit here?": "не возражаете, если я здесь сяду?",
    "tickets, please": "билеты, пожалуйста",
    "all tickets and railcards, please": "билеты и проездные карты, пожалуйста",
    "could I see your ticket, please?": "покажите ваш билет, пожалуйста",
    "I've lost my ticket": "я потерял билет",
    "what time do we arrive in …?": "во сколько мы прибываем в …?",
    "what time do we arrive in Sheffield?": "во сколько мы прибываем в Шеффилд?",
    "what's this stop?": "что это за остановка?",
    "what's the next stop?": "какая следующая остановка?",
    "this is my stop": "это моя остановка",
    "I'm getting off here": "я выхожу здесь",
    "is there a buffet car on the train?": "есть ли в поезде вагон-ресторан?",
    "do you mind if I open the window?": "вы не возражаете, если я открою окно?",
    "we are now approaching London Kings Cross": "мы прибываем на станцию Кингс-кросс",
    "this train terminates here": "этот поезд дальше не идёт",
    "all change, please": "всем пересесть, пожалуйста",
    "please take all your luggage and personal belongings with you": "пожалуйста заберите багаж и все персональные вещи",
    "could you tell me where the nearest Tube station is?": "не могли бы вы сказать, где ближайшая станция метро?",
    "where's there a map of the Underground?": "где здесь схема метро?",
    "over there": "там",
    "which line do I need for Camden Town?": "на какой линии находится Камден-таун?",
    "how many stops is it to …?": "сколько остановок до …?",
    "how many stops is it to Westminster?": "сколько остановок до Вестминстера?",
    "I'd like a Day Travelcard, please": "я хотел бы билет на день, пожалуйста",
    "which zones?": "в какие зоны?",
    "zones 1-2": "зоны 1—2",
    "I'd like an Oyster card, please": "я хотел бы карту «Ойстер», пожалуйста (карта с предоплатой для путешествия на общественном транспорте в Лондоне)",
    "I'd like to put £10 on it": "я хотел бы положить 10 фунтов",
    "Tickets": "Билеты",
    "Platform": "Платформа",
    "Waiting room": "Зал ожидания",
    "Left luggage": "Багажное отделение",
    "Lost property": "Бюро находок",
    "Underground": "Метро",
    "Bus stop": "Остановка автобуса",
    "Request stop": "Остановка по требованию",
    "On time": "Вовремя",
    "Expected": "Прибывает",
    "Delayed": "Задерживается",
    "Cancelled": "Отменен",
    "Calling at ...": "Останавливается в ...",
    "Seat": "Место",
    "Car": "Купе",
    "Priority seat": "Специальные места (места для беременных, пожилых или инвалидов)",
    "To trains": "К поездам",
    "Trains to London": "Поезда на Лондон",
    "Way out": "Выход",
    "Mind the gap": "Осторожно, щель",
    "Northbound platform": "Платформа северного направления",
    "Eastbound platform": "Платформа восточного направления",
    "Southbound platform": "Платформа южного направления",
    "Westbound platform": "Платформа южного направления",
    "I'd like to hire a car": "я хотел бы взять автомобиль на прокат",
    "how long for?": "как надолго?",
    "for how many days?": "на сколько дней?",
    "for …": "на …",
    "for one day": "на один день",
}