slovar = {
    "are you up to anything this evening?": "у тебя уже есть планы на вечер?",
    "have you got any plans for …?": "у тебя есть планы на …?",
    "have you got any plans for this evening?": "у тебя есть планы на этот вечер?",
    "have you got any plans for tomorrow?": "у тебя есть планы на завтра?",
    "have you got any plans for the weekend?": "у тебя есть планы на выходные?",
    "are you free …?": "ты свободен …?",
    "are you free this evening?": "ты свободен сегодня вечером?",
    "are you free tomorrow afternoon?": "ты свободен завтра днем?",
    "are you free tomorrow evening?": "ты свободен завтра вечером?",
    "what would you like to do this evening?": "чем бы ты хотел заняться сегодня вечером?",
    "do you want to go somewhere at the weekend?": "ты хочешь куда-нибудь поехать на выходных?",
    "would you like to join me for something to eat?": "ты хочешь вместе со мной поесть?",
    "do you fancy going out tonight?": "хочешь прогуляться сегодня вечером?",
    "sure": "конечно",
    "I'd love to": "с удовольствием",
    "sounds good": "хорошее предложение",
    "that sounds like fun": "заманчивое предложение",
    "sorry, I can't make it": "извини, не смогу",
    "I'm afraid already have plans": "боюсь, что у меня уже есть планы",
    "I'm too tired": "я слишком устал",
    "I'm staying in tonight": "я останусь сегодня дома",
    "I've got too much work to do": "у меня очень много работы",
    "I need to study": "мне нужно учиться",
    "I'm very busy at the moment": "я сейчас очень занят",
    "what time shall we meet?": "во сколько встретимся?",
    "let's meet at …": "давайте встретимся в …",
    "let's meet at eight o'clock": "давайте встретимся в восемь часов",
    "where would you like to meet?": "где ты хотел бы встретиться?",
    "I'll see you … at ten o'clock": "увидимся … в десять часов",
    "I'll see you in the pub at ten o'clock": "увидимся в пабе в десять часов",
    "I'll see you at the cinema at ten o'clock": "увидимся в кино в десять часов",
    "I'll meet you there": "встретимся там",
    "see you there!": "увидимся там!",
    "let me know if you can make it": "сообщи, если ты сможешь",
    "I'll call you later": "я позвоню тебе позже",
    "what's your address?": "какой твой адрес?",
    "I'm running a little late": "я немного опаздываю",
    "I'll be there in … minutes": "я буду там через … минут",
    "I'll be there in five minutes": "я буду там через пять минут",
    "I'll be there in ten minutes": "я буду там через десять минут",
    "I'll be there in fifteen minutes": "я буду там через пятнадцать минут",
    "have you been here long?": "ты уже давно тут?",
    "have you been waiting long?": "ты долго ждал?",
}