slovar = {
    "what languages can you speak?": "на каких языках вы говорите?",
    "I speak …": "я говорю …",
    "I speak French, Spanish, and a little Russian": "я говорю по-французски, по-испански и немного по-русски",
    "I speak fluent German": "я говорю свободно по-немецки",
    "I can get by in …": "я неплохо говорю …",
    "I can get by in Italian": "я неплохо говорю по-итальянски",
    "I'm learning …": "я учу …",
    "I'm learning Chinese": "я учу китайский",
    "where did you learn your English?": "где ты выучил английский?",
    "at school": "в школе",
    "at university": "в университете",
    "I took a course": "я ходил на курсы",
    "I taught myself": "я выучил самостоятельно",
    "do you understand?": "ты понимаешь?",
    "did you understand?": "ты понял?",
    "yes, I understood": "да, я понял",
    "sorry, I didn't understand": "извини, я не понял",
    "sorry?": "простите?",
    "excuse me?": "простите?",
    "how do you say ... in English?": "как будет по-английски ...?",
    "how do you spell that?": "как это пишется?",
    "how do you pronounce this word?": "как произносится это слово?",
    "you speak very good English": "ты очень хорошо говоришь по-английски",
    "your English is very good": "у тебя очень хороший английский",
    "I'm a little out of practice": "мне не хватает практики",
    "I'd like to practise my …": "я хотел бы попрактиковаться в …",
    "I'd like to practise my Portuguese": "я хотел бы попрактиковаться в португальском",
    "let's speak in …": "давайте поговорим …",
    "let's speak in English": "давайте поговорим по-английски",
    "let's speak in Italian": "давайте поговорим по-итальянски",
    "what's this called?": "как это называется?",
}