slovar = {
    "I'd like some …": "мне нужна …",
    "I'd like some toothpaste": "мне нужна зубная паста",
    "I'd like some paracetamol": "мне нужна парацетамол",
    "I've got a prescription here from the doctor": "у меня есть рецепт от врача",
    "have you got anything for …?": "у вас что-нибудь от …?",
    "have you got anything for cold sores?": "у вас что-нибудь от герписа?",
    "have you got anything for a sore throat?": "у вас что-нибудь от боли в горле?",
    "have you got anything for chapped lips?": "у вас что-нибудь от обветренных губ?",
    "have you got anything for a cough?": "у вас что-нибудь от кашля?",
    "have you got anything for travel sickness?": "у вас что-нибудь от укачивания?",
    "have you got anything for athlete's foot?": "у вас что-нибудь от ножного грибка?",
    "can you recommend anything for a cold?": "вы можете что-нибудь порекомендовать от простуды?",
    "I'm suffering from …": "я страдаю от …",
    "I'm suffering from hay fever": "я страдаю от сенной аллергии",
    "I'm suffering from indigestion": "я страдаю от несварения желудка",
    "I'm suffering from diarrhoea": "я страдаю от диареи",
    "I've got a rash": "у меня сыпь",
    "you could try this cream": "вы можете попробовать этот крем",
    "if it doesn't clear up after a week, you should see your doctor": "если это не пройдет в течение недели, вы должны обратиться к врачу",
    "have you got anything to help me stop smoking?": "у вас есть что-нибудь, чтобы помочь мне бросить курить?",
    "have you tried nicotine patches?": "вы пробовали никотиновые пластыри?",
    "can I buy this without a prescription?": "могу я это купить без рецепта?",
    "it's only available on prescription": "это можно купить только с рецептом",
    "does it have any side-effects?": "есть ли какие-нибудь побочные эффекты?",
    "it can make you feel drowsy": "вы можете почувствовать сонливость",
    "you should avoid alcohol": "вам следует воздержаться от алкоголя",
    "I'd like to speak to the pharmacist, please": "я хотел бы поговорить с аптекарем, пожалуйста",
    "what's the matter?": "что случилось?",
    "I'm not feeling well": "я нехорошо себя чувствую",
    "I'm not feeling very well": "я нехорошо себя чувствую",
    "I feel ill": "я заболел",
    "I feel sick": "меня тошнит",
    "I've cut myself": "я порезался",
    "I've got a headache": "у меня болит голова",
    "I've got a splitting headache": "у меня ужасная головная боль",
    "I'm not well": "мне нехорошо",
    "I've got flu": "у меня грип",
    "I'm going to be sick": "меня тошнит",
    "I've been sick": "меня тошнило",
    "I've got a pain in my …": "у меня болит …",
    "I've got a pain in my neck": "у меня болит шея",
    "my … are hurting": "у меня болит …",
    "my feet are hurting": "у меня болит ступня",
    "my knees are hurting": "у меня болит колено",
    "my back hurts": "у меня болит спина",
    "have you got any …?": "у тебя есть …?",
    "have you got any painkillers?": "у тебя есть болеутоляющие средства?",
    "have you got any paracetamol?": "у тебя есть парацетамол?",
    "have you got any aspirin?": "у тебя есть аспирин?",
    "have you got any plasters?": "у тебя есть пластыри?",
    "how are you feeling?": "как ты себя чувствуешь?",
    "are you feeling alright?": "ты себя нормально чувствуешь?",
    "are you feeling any better?": "ты себя лучше чувствуешь?",
    "I hope you feel better soon": "я надеюсь, тебе скоро станет лучше",
    "get well soon!": "выздоравливай поскорее!",
    "I need to see a doctor": "мне нужен доктор",
    "I think you should go and see a doctor": "я думаю, тебе следует пойти к врачу",
    "do you know a good …?": "ты знаешь хорошего …?",
    "do you know a good doctor?": "ты знаешь хорошего доктора?",
    "do you know a good dentist?": "ты знаешь хорошего дантиста?",
    "do you know where there's an all-night chemists?": "ты знаешь круглосуточную аптеку?",
    "is there an admission charge?": "за вход надо платить?",
    "only for the exhibition": "только за выставки",
    "the museum's closed on Mondays": "музей закрыт по понедельникам",
    "can I take photographs?": "можно фотографировать?",
    "would you like an audio-guide?": "вы желаете аудио-гида?",
    "are there any guided tours today?": "сегодня есть какие-либо экскурсии с гидом?",
    "what time does the next guided tour start?": "во сколько начинается следующая экскурсия?",
    "where's the cloakroom?": "где находится гардероб?",
    "we have to leave our bags in the cloakroom": "мы должны оставить свои сумки в гардеробе",
    "do you have a plan of the museum?": "у вас есть план музея?",
    "who's this painting by?": "чья это картина?",
    "this museum's got a very good collection of …": "у этого музея очень хорошая коллекция …",
    "this museum's got a very good collection of oil paintings": "у этого музея очень хорошая коллекция картин, написанных маслом",
    "this museum's got a very good collection of watercolours": "у этого музея очень хорошая коллекция акварелей",
    "this museum's got a very good collection of portraits": "у этого музея очень хорошая коллекция портретов",
    "this museum's got a very good collection of landscapes": "у этого музея очень хорошая коллекция пейзажей",
    "this museum's got a very good collection of sculptures": "у этого музея очень хорошая коллекция скульптур",
    "this museum's got a very good collection of ancient artifacts": "у этого музея очень хорошая коллекция старинных предметов",
    "this museum's got a very good collection of pottery": "у этого музея очень хорошая коллекция керамики",
    "do you like …?": "тебе нравится/нравятся …?",
    "do you like modern art?": "тебе нравится/нравятся современное искусство?",
    "do you like classical paintings?": "тебе нравится/нравятся классические картины?",
    "do you like impressionist paintings?": "тебе нравится/нравятся картины импрессионистов?",
    "Free admission": "Вход свободный",
    "No photography": "Не фотографировать",
    "Cloakroom": "Гардероб",
    "Café": "Кафе",
    "Gift shop": "Магазин сувениров",
    "do you want to go to a club tonight?": "ты хочешь пойти сегодня вечером в клуб?",
    "do you know any good clubs near here?": "ты знаешь какие-нибудь хорошие клубы поблизости?",
    "what time are you open until?": "до скольки вы открыты?",
    "what time do you close?": "во сколько вы закрываетесь?",
    "how much is it to get in?": "сколько стоит вход?",
    "is there a dress code?": "дресс-код есть?",
    "what nights are you open?": "по каким дням вы открыты?",
    "what sort of music is it?": "какой это стиль музыки?",
    "what's on tonight?": "какая сегодня программа?",
    "do you have any live music tonight?": "сегодня будет концерт?",
    "sorry, you can't come in": "извините, вы не можете войти",
    "you can't come in with trainers on": "вы не можете войти в спортивных штанах",
    "there's a private party tonight": "сегодня здесь закрытая вечеринка",
    "the club's full": "в клубе нет мест",
    "I'm on the guest list": "я в списке гостей",
    "I'm a member": "я — член",
    "what do you think of the DJ?": "что вы думаете о диджее?",
    "the music's great!": "отличная музыка!",
    "it's very lively tonight": "очень оживленно сегодня",
    "it's a bit empty": "здесь немного пусто",
    "it's dead in here": "здесь тоска (слэнг)",
    "where's the bar?": "где находится бар?",
    "there's a long queue at the bar": "в баре длинная очередь",
}