slovar = {
    "there's an excess baggage charge of …": "дополнительная плата за багаж …",
    "there's an excess baggage charge of £30": "дополнительная плата за багаж 30 фунтов",
    "would you like a window or an aisle seat?": "вы хотите сидеть у окна или в проходе?",
    "enjoy your flight!": "счастливого полета!",
    "where can I get a trolley?": "где находятся тележки?",
    "are you carrying any liquids?": "у вас есть с собой какие-либо жидкости?",
    "could you take off your …, please?": "снимите …, пожалуйста",
    "could you take off your coat, please?": "снимите пальто, пожалуйста",
    "could you take off your shoes, please?": "снимите обувь, пожалуйста",
    "could you take off your belt, please?": "снимите ремень, пожалуйста",
    "could you put any metallic objects into the tray, please?": "полажите металлические предметы на поднос, пожалуйста",
    "please empty your pockets": "освободите карманы, пожалуйста",
    "please take your laptop out of its case": "пожалуйста достаньте ноутбук из сумки",
    "I'm afraid you can't take that through": "к сожалению, вы не можете взять это собой",
    "what's the flight number?": "какой номер рейса?",
    "which gate do we need?": "какие у нас ворота?",
    "last call for passenger Smith travelling to Miami, please proceed immediately to Gate number 32": "последний вызов пассажира Смита, путешествующего в Майами, пожалуйста пройдите к воротам номер 32",
    "the flight's been delayed": "рейс задерживается",
    "the flight's been cancelled": "рейс отменён",
    "we'd like to apologise for the delay": "мы хотели бы извиниться за задержку",
    "could I see your passport and boarding card, please?": "покажите ваш паспорт и посадочный билет, пожалуйста",
    "what's your seat number?": "какой у вас номер места?",
    "could you please put that in the overhead locker?": "уберите это, пожалуйста, в верхнее отделение",
    "please pay attention to this short safety demonstration": "пожалуйста, обратите внимание на эту небольшую презентацию",
    "please turn off all mobile phones and electronic devices": "пожалуйста, отключите мобильные телефоны и электронные приборы",
    "the captain has turned off the Fasten Seatbelt sign": "капитан выключил сигнал «Пристегнуть ремни»",
    "how long does the flight take?": "сколько времени продлится полет?",
    "would you like any food or refreshments?": "вы желаете еду или напитки?",
    "the captain has switched on the Fasten Seatbelt sign": "капитан включил сигнал «Пристегнуть ремни»",
    "we'll be landing in about fifteen minutes": "мы приземлимся примерно через 15 минут",
    "please fasten your seatbelt and return your seat to the upright position": "пожалуйста, пристегните ремни и верните кресло в исходное положение",
    "please stay in your seat until the aircraft has come to a complete standstill and the Fasten Seatbelt sign has been switched off": "пожалуйста, не вставайте до полной остановки самолета и выключения сигнала «Пристегнуть ремни»",
    "the local time is …": "местное время …",
    "the local time is 9.34pm": "местное время 21:34",
    "Short stay": "Краткосрочная парковка",
    "Short stay car park": "Краткосрочная парковка",
    "Long stay": "Долгосрочная парковка",
    "Long stay car park": "Долгосрочная парковка",
    "Arrivals": "Прибытие",
    "Departures": "Отправление",
    "International check-in": "Международная регистрация",
    "International departures": "Прибытие международных рейсов",
    "Domestic flights": "Местные рейсы",
    "Toilets": "Туалеты",
    "Information": "Информация",
    "Ticket offices": "Кассы",
    "Lockers": "Хранилище",
    "Payphones": "Телефон-автомат",
    "Restaurant": "Ресторан",
    "Check-in closes 40 minutes before departure": "Регистрация закрывается за 40 минут до отправления",
    "Gates 1-32": "Ворота 1—32",
    "Tax free shopping": "Магазины такс-фри",
    "Duty free shopping": "Магазины дьюти-фри",
    "Transfers": "Пересадка",
    "Flight connections": "Пересадка",
    "Baggage reclaim": "Выдача багажа",
    "Passport control": "Паспортный контроль",
    "Customs": "Таможня",
    "Taxis": "Такси",
    "Car hire": "Прокат автомобилей",
    "Departures board": "Отправляющиеся рейсы",
    "Check-in open": "Регистрация открыта",
    "Go to Gate ...": "Пройдите к воротам ...",
    "Delayed": "Задержка",
    "Cancelled": "Отмена",
    "Now boarding": "Посадка",
    "Last call": "Последний вызов",
    "Gate closing": "Ворота закрываются",
    "Gate closed": "Ворота закрыты",
    "Departed": "Вылетел",
    "Arrivals board": "Прибывающие рейсы",
    "Expected 23:25": "Ожидается в 23:25",
    "Landed 09:52": "Приземлился в 09:52",
    "where's the ticket office?": "где находятся кассы?",
    "where are the ticket machines?": "где находятся билетные автоматы?",
    "what time's the next bus to …?": "во сколько идет следующий автобус на …?",
    "what time's the next bus to Camden?": "во сколько идет следующий автобус на Камден?",
    "Camden": "во сколько идет следующий поезд на …?",
    "can I buy a ticket on the bus?": "можно купить билет в автобусе?",
    "can I buy a ticket on the train?": "можно купить билет в поезде?",
    "how much is a … to London?": "сколько стоит … до Лондона?",
    "how much is a single to London?": "сколько стоит билет в один конец до Лондона?",
    "how much is a return to London?": "сколько стоит билет в оба конца до Лондона?",
    "how much is a first class single to London?": "сколько стоит билет первого класса в один конец до Лондона?",
    "how much is a first class return to London?": "сколько стоит билет первого класса в оба конца до Лондона?",
    "I'd like a … to Bristol": "я хотел бы … до Бристоля",
    "I'd like a single to Bristol": "я хотел бы билет в один конец до Бристоля",
    "I'd like a return to Bristol": "я хотел бы билет в оба конца до Бристоля",
    "I'd like a child single to Bristol": "я хотел бы детский билет в один конец до Бристоля",
    "I'd like a child return to Bristol": "я хотел бы детский билет в оба конца до Бристоля",
    "I'd like a senior citizens' single to Bristol": "я хотел бы пенсионерский билет в один конец до Бристоля",
    "I'd like a senior citizens' return to Bristol": "я хотел бы пенсионерский билет в оба конца до Бристоля",
    "I'd like a first class single to Bristol": "я хотел бы билет первого класса в один конец до Бристоля",
    "I'd like a first class return to Bristol": "я хотел бы билет первого класса в оба конца до Бристоля",
    "are there any reductions for off-peak travel?": "есть ли скидки на билеты не в час-пик?",
    "when would you like to travel?": "когда вы хотели бы выехать?",
    "when will you be coming back?": "когда вы хотели бы вернуться?",
    "I'd like a return to …, coming back on Sunday": "я хотел бы билет в оба конца до …, с возвратом в воскресенье",
    "I'd like a return to Newcastle, coming back on Sunday": "я хотел бы билет в оба конца до Ньюкасла, с возвратом в воскресенье",
    "which platform do I need for …?": "какая платформа на …?",
    "which platform do I need for Manchester?": "какая платформа на Манчестер?",
    "is this the right platform for …?": "это правильная платформа для …?",
    "is this the right platform for Cardiff?": "это правильная платформа для Кардиффа?",
    "where do I change for …?": "где мне надо сделать пересадку на …?",
    "where do I change for Exeter?": "где мне надо сделать пересадку на Эксетер?",
    "you'll need to change at …": "вам надо сделать пересадку в …",
    "you'll need to change at Reading": "вам надо сделать пересадку в Рединге",
    "can I have a timetable, please?": "не могли бы вы дать мне расписание, пожалуйста?",
    "how often do the buses run to …?": "как часто ходят автобусы на …?",
    "how often do the buses run to Bournemouth?": "как часто ходят автобусы на Борнмут?",
    "how often do the trains run to …?": "как часто ходят поезда на …?",
    "how often do the trains run to Coventry?": "как часто ходят поезда на Ковентри?",
    "I'd like to renew my season ticket, please": "я хотел бы продлить сезонный билет, пожалуйста",
    "the next train to arrive at Platform 2 is the 16.35 to Doncaster": "следующий поезд, прибывающий на вторую платформу, отправляется в 16:35 в Донкастер",
    "Platform 11 for the 10.22 to Guildford": "платформа 11 в 10:22 на Гилдфорд",
    "the next train to depart from Platform 5 will be the 18.03 service to Penzance": "следующий поезд, отправляющийся с пятой платформы, это рейс в 18:03 на Пензанс",
    "the train's running late": "поезд опаздывает",
    "the train's been cancelled": "поезд был отменен",
    "does this bus stop at …?": "останавливается ли этот автобус в …?",
    "does this bus stop at Trafalgar Square?": "останавливается ли этот автобус в Трафальгарской площади?",
    "does this train stop at …?": "останавливается ли этот поезд в …?",
    "does this train stop at Leicester?": "останавливается ли этот поезд в Лейчестере?",
}