slovar = {
    "can I buy you a drink?": "могу я купить тебе что-нибудь выпить?",
    "would you like a drink?": "желаешь что-нибудь выпить?",
    "can I get you a drink?": "могу я предложить тебе что-нибудь выпить?",
    "are you on your own?": "ты без компании?",
    "would you like to join us?": "хочешь присоединиться к нам?",
    "do you mind if I join you?": "не против, если я присоединюсь?",
    "do you mind if we join you?": "не против, если мы присоединимся?",
    "do you come here often?": "ты часто здесь бываешь?",
    "is this your first time here?": "ты здесь впервые?",
    "have you been here before?": "ты бывал здесь раньше?",
    "would you like to dance?": "хочешь потанцевать?",
    "do you want to go for a drink sometime?": "давай как-нибудь пойдем вместе выпьем?",
    "I was wondering if you'd like to go out for a drink sometime": "не хочешь как-нибудь пойти вместе выпить?",
    "if you'd like to meet up sometime, let me know!": "если захочешь как-нибудь встретиться, сообщи мне!",
    "would you like to join me for a coffee?": "хочешь выпить со мной кофе?",
    "do you fancy getting a bite to eat?": "хочешь перекусить?",
    "do you fancy lunch sometime?": "хочешь как-нибудь вместе пообедать?",
    "do you fancy dinner sometime?": "хочешь как-нибудь вместе поужинать?",
    "do you fancy going to see a film sometime?": "хочешь сходить как-нибудь в кино?",
    "that sounds good": "хорошее предложение",
    "I'd love to!": "с удовольствием!",
    "sorry, I'm busy": "извини, я занят(а)",
    "sorry, you're not my type!": "прости, ты не в моём вкусе!",
    "here's my number": "вот мой номер",
    "what's your phone number?": "какой у тебя номер телефона?",
    "could I take your phone number?": "можно записать твой телефон?",
    "you look great": "ты прекрасно выглядишь",
    "you look very nice tonight": "ты очень хорошо сегодня выглядишь",
    "I like your outfit": "мне нравится твой наряд",
    "you're beautiful": "ты красивая (женщине)",
    "you're really good-looking": "ты очень хорошо выглядишь",
    "you're really sexy": "ты очень сексуальный/ая",
    "you've got beautiful eyes": "у тебя красивые глаза",
    "you've got a great smile": "у тебя великолепная улыбка",
    "thanks for the compliment!": "спасибо за комплимент!",
    "what do you think of this place?": "что ты думаешь об этом месте?",
    "shall we go somewhere else?": "может пойдем в другое место?",
    "I know a good place": "я знаю хорошее место",
    "can I kiss you?": "можно тебя поцеловать?",
    "can I walk you home?": "можно проводить тебя домой?",
    "can I drive you home?": "можно отвезти тебя домой?",
    "would you like to come in for a coffee?": "хочешь пройти и выпить кофе?",
    "would you like to come back to mine?": "хочешь пойти ко мне?",
    "thanks, I had a great evening": "спасибо, это был прекрасный вечер",
    "when can I see you again?": "когда мы сможем снова увидиться?",
    "give me a call!": "позвони мне!",
    "I'll call you": "я позвоню",
    "what do you think of me?": "что ты обо мне думаешь?",
    "I enjoy spending time with you": "мне нравится быть вместе с тобой",
    "I find you very attractive": "я считаю тебя очень привлекательным/ой",
    "I like you": "ты мне нравишься",
    "I like you a lot": "ты мне очень нравишься",
    "I'm crazy about you": "я без ума от тебя",
    "I love you!": "я люблю тебя!",
    "will you marry me?": "ты выйдешь за меня замуж?",
    "I miss you": "я соскучился",
    "I've missed you": "я очень скучал",
    "do you have any condoms?": "у тебя есть презервативы?",
    "I'm …": "я …",
    "I'm straight": "я традиционной ориентации",
    "I'm gay": "я гомосексуалист/лесбиянка",
    "I'm bisexual": "я бисексуал/бисексуалка",
    "how far is it to the airport?": "как далеко до аэропорта?",
    "how far is it to … from here?": "как далеко до … отсюда?",
    "how far is it to the beach from here?": "скак далеко до пляжа отсюда?",
    "is it far?": "это далеко?",
    "is it a long way?": "это долгий путь?",
    "it's …": "это …",
    "it's not far": "это недалеко",
    "it's quite close": "это довольно близко",
    "it's quite a long way": "это довольно далеко",
    "it's a long way on foot": "это довольно далеко",
    "it's a long way to walk": "это долгий путь пешком",
    "it's about a mile from here": "это около мили отсюда (одна миля — примерно 1,6 километра)",
    "follow the signs for …": "следуйте указателям для …",
    "follow the signs for the town centre": "следуйте указателям для центра города",
    "follow the signs for Birmingham": "следуйте указателям для Бирменгема",
    "continue straight on past some traffic lights": "после светофора продолжайте прямо",
    "at the second set of traffic lights, turn left": "на втором светофоре поверните налево",
    "go over the roundabout": "проедьте по кольцу",
    "take the second exit at the roundabout": "на кольце воспользуйтесь вторым выездом",
    "turn right at the T-junction": "поверните направо на Т-образном перекрестке",
    "go under the bridge": "проедьте под мостом",
    "go over the bridge": "проедьте по мосту",
    "you'll cross some railway lines": "вы проедете через железнодорожный переезд",
    "I'll put the kettle on": "я включу чайник",
    "the kettle's boiled": "чайник вскипел",
    "can you put the light on?": "можешь включить свет?",
    "can you switch the light on?": "можешь включить свет?",
    "can you turn the light off?": "можешь выключить свет?",
    "can you switch the light off?": "можешь выключить свет?",
    "is there anything I can do to help?": "могу я чем-нибудь помочь?",
    "could you help me wash the dishes?": "можешь помочь мне помыть посуду?",
    "I'll wash and you dry": "я буду мыть, а ты вытирай",
    "I'm going to bed": "я пойду спать",
    "is there anything good on TV?": "есть что-нибудь хорошее по телевизору?",
    "is there anything good on television tonight?": "есть что-нибудь хорошее по телевизору сегодня вечером?",
    "there's a good film on later": "попозже будет хороший фильм",
    "Beware of the dog": "Осторожно, собака",
    "that was excellent": "это было превосходно",
    "that was very tasty": "это было очень вкусно",
    "that was delicious": "это было очень вкусно",
}