slovar = {
    "another beer, please": "ещё пива, пожалуйста",
    "another two beers, please": "ещё два пива, пожалуйста",
    "same again, please": "то же самое, пожалуйста",
    "are you still serving drinks?": "вы ещё подаёте выпить?",
    "last orders!": "последние заказы!",
    "do you have any snacks?": "у вас есть какие-нибудь закуски?",
    "do you have any sandwiches?": "у вас есть какие-нибудь бутерброды?",
    "do you serve food?": "вы подаёте поесть?",
    "what time does the kitchen close?": "во-сколько закрывается кухня?",
    "are you still serving food?": "вы ещё подаёте поесть?",
    "a packet of crisps, please": "пачку чипсов, пожалуйста",
    "what flavour would you like?": "с каким вкусом вы бы хотели?",
    "ready salted": "соленые",
    "cheese and onion": "сыр с луком",
    "salt and vinegar": "соль и уксус",
    "what sort of sandwiches do you have?": "какие у вас есть бутерброды?",
    "do you have any hot food?": "у вас есть какая-нибудь горячая еда?",
    "today's specials are on the board": "сегодняшние специальные блюда написаны на доске",
    "is it table service or self-service?": "этот столик обслуживается или надо самим заказывать?",
    "would you like anything to eat?": "вы хотите что-нибудь поесть?",
    "could we see a menu, please?": "мы могли бы посмотреть меню, пожалуйста?",
    "eat in or take-away?": "здесь или с собой?",
    "does anyone fancy a game of …?": "кто-нибудь хочет поиграть в …?",
    "does anyone fancy a game of pool?": "кто-нибудь хочет поиграть в бильярд?",
    "does anyone fancy a game of darts?": "кто-нибудь хочет поиграть в дартс?",
    "does anyone fancy a game of cards?": "кто-нибудь хочет поиграть в карты?",
    "do you have internet access here?": "здесь есть интернет?",
    "do you have wireless internet here?": "здесь есть беспроводной интернет?",
    "what’s the password for the internet?": "какой пароль для интернета?",
    "I feel fine": "я прекрасно себя чувствую",
    "I feel terrible": "я ужасно себя чувствую",
    "I've got a hangover": "у меня похмелье",
    "I'm never going to drink again!": "я никогда больше не буду пить!",
    "do you smoke?": "ты куришь?, вы курите?",
    "no, I don't smoke": "нет, я не курю",
    "I've given up": "я бросил",
    "do you mind if I smoke?": "ты не против, если я закурю?",
    "would you like a cigarette?": "хочешь сигарету?",
    "have you got a light?": "у тебя есть прикурить?",
    "do you know any good restaurants?": "вы знаете какой-нибудь приличный ресторан?",
    "where's the nearest restaurant?": "где находится ближайший ресторан?",
    "can you recommend a good pub near here?": "можете порекомендовать хороший паб неподолёку?",
    "do you fancy a pint?": "может выпьем пива? (дружеское)",
    "do you fancy a quick drink?": "может зайдём выпьем что-нибудь? (дружеское)",
    "shall we go for a drink?": "может пойдем выпьем?",
    "do you know any good places to …?": "ты знаешь какое-нибудь хорошее место, чтобы …?",
    "do you know any good places to eat?": "ты знаешь какое-нибудь хорошее место, чтобы поесть?",
    "do you know any good places to get a sandwich?": "ты знаешь какое-нибудь хорошее место, чтобы съесть бутерброд?",
    "do you know any good places to go for a drink?": "ты знаешь какое-нибудь хорошее место, чтобы выпить?",
    "shall we get a take-away?": "может закажем с собой?",
    "let's eat out tonight": "давай поедим где-нибудь сегодня вечером",
    "would you like to …?": "ты хотел бы …?",
    "would you like to come for a drink after work?": "ты хотел бы пойти выпить после работы?",
    "would you like to come for a coffee?": "ты хотел бы выпить кофе?",
    "would you like to join me for lunch?": "ты хотел бы пообедать со мной?",
    "would you like to join me for dinner?": "ты хотел бы поужинать со мной?",
    "Reserved": "Резервировано",
    "No smoking": "Не курить",
    "I'd like to check out": "я хотел бы выехать",
    "I'd like to pay my bill, please": "я хотел бы оплатить счёт, пожалуйста",
    "I think there's a mistake in this bill": "я думаю, что счёт неправильный",
    "how would you like to pay?": "как вы желаете платить?",
    "I'll pay …": "я заплачу …",
    "I'll pay by credit card": "я заплачу кредитной карточкой",
    "I'll pay in cash": "я заплачу наличными",
    "have you used the minibar?": "вы пользовались мини-баром?",
    "we haven't used the minibar": "мы не пользовались мини-баром",
    "could we have some help bringing our luggage down?": "помогите нам снести вниз багаж, пожалуйста",
    "do you have anywhere we could leave our luggage?": "мы могли бы где-то оставить багаж?",
    "I hope you had an enjoyable stay": "надеюсь, ваше пребывание было приятным",
    "I've really enjoyed my stay": "мое пребывание было очень приятным",
    "we've really enjoyed our stay": "наше пребывание было очень приятным",
    "my room number's …": "мой номер …",
    "my room number's 215": "мой номер 215",
    "could I have a wake-up call at seven o'clock?": "могли бы вы разбудить меня в семь часов?",
    "where do we have breakfast?": "где мы завтракаем?",
    "where's the restaurant?": "где находится ресторан?",
    "could you please call me a taxi?": "вызовите мне, пожалуйста, такси",
    "do you lock the front door at night?": "вы закрываете вход на ночь?",
    "if you come back after midnight, you'll need to ring the bell": "если вы вернётесь после полуночи, позвоните в дверь",
    "I'll be back around ten o'clock": "я вернусь около десяти часов",
    "could I see your key, please?": "покажите ваш ключ, пожалуйста",
    "are there any laundry facilities?": "тут можно постирать?",
    "what time do I need to check out?": "во сколько я должен выехать?",
    "would it be possible to have a late check-out?": "возможно ли выехать попозже?",
    "the key doesn't work": "ключ не работает",
    "there isn't any hot water": "нет горячей воды",
    "the room's too …": "в комнате слишком …",
    "the room's too hot": "в комнате слишком жарко",
    "the room's too cold": "в комнате слишком холодно",
    "the room's too noisy": "в комнате слишком шумно",
    "the … doesn't work": "… не работает",
    "the heating doesn't work": "отопление не работает",
    "the shower doesn't work": "душ не работает",
    "the television doesn't work": "телевизор не работает",
    "one of the lights isn't working": "одна лампа не работает",
    "there's no …": "там нет …",
    "there's no toilet paper": "там нет туалетной бумаги",
    "there's no soap": "там нет мыла",
    "there's no shampoo": "там нет шампуня",
    "could I have a towel, please?": "не могли бы вы дать мне полотенце,",
    "could I have an extra blanket?": "не могли бы вы дать мне дополнительное одеяло, пожалуйста?",
    "my room's not been made up": "моя комната не прибрана",
    "could you please change the sheets?": "поменяйте постельное бельё, пожалуйста",
    "I've lost my room key": "я потерял ключ от номера",
    "Do not disturb": "Не беспокоить",
    "Please make up room": "Пожалуйста, приберитесь в комнате",
    "Lift out of order": "Лифт не работает",
    "I've got a reservation": "у меня забронировано",
    "your name, please?": "ваше имя, пожалуйста",
    "my name's …": "мое имя …",
    "my name's Mark Smith": "мое имя Марк Смит",
    "could I see your passport?": "покажите паспорт, пожалуйста",
    "could you please fill in this registration form?": "заполните регистрационную карту, пожалуйста",
    "my booking was for a twin room": "я бронировал номер с двумя кроватями",
    "my booking was for a double room": "я бронировал двухместный номер (с одной кроватью)",
    "would you like a newspaper?": "желаете газету?",
    "would you like a wake-up call?": "желаете, чтобы мы вас разбудили?",
    "what time's breakfast?": "во сколько завтрак?",
}