slovar = {
    "not too short": "не слишком коротко",
    "quite short": "довольно коротко",
    "very short": "очень коротко",
    "grade one": "уровень первый (под машинку, длина 3 мм)",
    "grade two": "уровень второй (под машинку, длина 6 мм)",
    "grade three": "уровень третий (под машинку, длина 9 мм)",
    "grade four": "уровень четвертый (под машинку, длина 12 мм)",
    "completely shaven": "полностью сбрить",
    "do you have a parting?": "у вас есть пробор?",
    "square at the back, please": "сзади прямо, пожалуйста",
    "tapered at the back, please": "сзади со скосом, пожалуйста",
    "that's fine, thanks": "так хорошо, спасибо",
    "what colour would you like?": "какой цвет вы хотите?",
    "which of these colours would you like?": "какие из этих цветов вам нравятся?",
    "would you like it blow-dried?": "вам посушить феном?",
    "could you trim my beard, please?": "не могли бы вы подстричь мне бороду?",
    "could you trim my moustache, please?": "не могли бы вы подстричь мне усы?",
    "would you like anything on it?": "вы хотите что-нибудь добавить?",
    "a little wax": "немного воска",
    "some gel": "гель",
    "some hairspray": "лак для волос",
    "nothing, thanks": "спасибо, ничего",
    "how much do I owe you?": "сколько с меня?",
    "Hairdressers": "Парикмахерская",
    "Barbers": "Мужская парикмахерская",
    "I'd like to withdraw £100, please": "я хотел бы снять 100 фунтов, пожалуйста",
    "I want to make a withdrawal": "я хотел бы снять деньги",
    "how would you like the money?": "какими купюрами вы желаете?",
    "in tens, please": "десятками, пожалуйста (банкноты по десять фунтов)",
    "ten pound notes": "десятками, пожалуйста (банкноты по десять фунтов)",
    "could you give me some smaller notes?": "вы могли бы дать мне мелкими банкнотами?",
    "I'd like to pay this in, please": "я хотел бы положить это на свой счет, пожалуйста",
    "I'd like to pay this cheque in, please": "я хотел бы положить этот чек на свой счет, пожалуйста",
    "how many days will it take for the cheque to clear?": "сколько дней потребуется, чтобы активировать чек?",
    "have you got any …?": "у вас есть какое-нибудь …?",
    "have you got any identification?": "у вас есть какое-нибудь удостоверение личности?",
    "have you got any ID?": "у вас есть какое-нибудь удостоверение личности?",
    "I've got my …": "у меня есть …",
    "I've got my passport": "у меня есть паспорт",
    "I've got my driving licence": "у меня есть водительские права",
    "I've got my ID card": "у меня есть карточка удостоверения личности",
    "your account's overdrawn": "вы ушли в минус",
    "I'd like to transfer some money to this account": "я хотел бы положить деньги на этот счет",
    "could you transfer £1000 from my current account to my deposit account?": "могли бы вы перевести 1000 фунтов с моего текущего счёта на депозитный счёт?",
    "I'd like to open an account": "я хотел бы открыть счёт",
    "I'd like to open a personal account": "я хотел бы открыть личный счёт",
    "I'd like to open a business account": "я хотел бы открыть бизнес-счёт",
    "could you tell me my balance, please?": "могли бы вы сказать мой остаток счёта, пожалуйста?",
    "could I have a statement, please?": "могу я получить распечатку, пожалуйста?",
    "I'd like to change some money": "я хотел бы обменять деньги",
    "I'd like to order some foreign currency": "я хотел бы заказать иностранную валюту",
    "what's the exchange rate for euros?": "какой обменный курс евро?",
    "I'd like some …": "я хотел бы …",
    "I'd like some euros": "я хотел бы евро",
    "I'd like some US dollars": "я хотел бы доллары США",
    "could I order a new chequebook, please?": "я хотел бы заказать новую чековую книжку, пожалуйста",
    "I'd like to cancel a cheque": "я хотел бы аннулировать чек",
    "I'd like to cancel this standing order": "я хотел бы прервать постоянное платежное поручение",
    "where's the nearest cash machine?": "где находится ближайший банкомат?",
    "what's the interest rate on this account?": "какая процентная ставка на этом счете?",
    "what's the current interest rate for personal loans?": "какая процентная ставка на персональный заём?",
    "I've lost my bank card": "я потерял свою банковскую карточку",
    "I want to report a …": "я хочу заявить о …",
    "I want to report a lost credit card": "я хочу заявить о потере кредитной карточки",
    "I want to report a stolen credit card": "я хочу заявить о краже кредитной карточки",
    "we've got a joint account": "у нас совместный счет",
    "I'd like to tell you about a change of address": "я хотел бы сообщить вам об изменении адреса",
    "I've forgotten my Internet banking password": "я забыл пароль для интернет-банка",
    "I've forgotten the PIN number for my card": "я забыл пароль моей карточки",
    "I'll have a new one sent out to you": "я вышлю вам новый",
    "could I make an appointment to see …?": "я хотел бы назначить встречу с …",
    "could I make an appointment to see the manager?": "я хотел бы назначить встречу с менеджером",
    "could I make an appointment to see a financial advisor?": "я хотел бы назначить встречу с финансовым советником",
    "I'd like to speak to someone about a mortgage": "я хотел бы поговорить с кем-нибудь о жилищном заёме",
    "Insert your card": "Вставьте карточку",
    "Enter your PIN": "Введите пин-код",
    "Incorrect PIN": "Неправильный пин-код",
    "Enter": "Ввод",
    "Correct": "Исправить",
    "Cancel": "Отмена",
    "Withdraw cash": "Снять наличные",
    "Other amount": "Другая сумма",
    "Please wait": "Подождите, пожалуйста",
    "Your cash is being counted": "Деньги считаются",
    "Insufficient funds": "Недостаточно денег на счёте",
    "Balance": "Остаток счёта",
    "On screen": "На экране",
    "Printed": "Распечатано",
    "Another service?": "Другая услуга?",
    "Would you like a receipt?": "Желаете чек?",
    "Remove card": "Заберите карточку",
    "Quit": "Прекратить",
    "how much is a first class stamp?": "сколько стоит марка первого класса?",
    "how much is a second class stamp?": "сколько стоит марка второго класса?",
    "I'd like …, please": "я хотел бы …, пожалуйста",
    "I'd like an envelope, please": "я хотел бы конверт, пожалуйста",
    "I'd like a packet of envelopes, please": "я хотел бы упаковку конвертов, пожалуйста",
    "I'd like a jiffy bag, please": "я хотел бы противоударный пакет, пожалуйста",
    "could I have …, please?": "я хотел бы …, пожалуйста",
    "could I have a first class stamp, please?": "я хотел бы марку первого класса, пожалуйста",
    "could I have a second class stamp, please?": "я хотел бы марку второго класса, пожалуйста",
    "could I have a book of first class stamps, please?": "я хотел бы набор марок первого класса, пожалуйста",
    "could I have some first class stamps, please?": "я хотел бы марки первого класса, пожалуйста",
    "how many would you like?": "сколько штук вы хотите?",
    "I'd like to send this to …": "я хотел бы отправить это в …",
    "I'd like to send this to Canada": "я хотел бы отправить это в Канаду",
    "I'd like to send this parcel to …": "я хотел бы отправить эту посылку в …",
    "I'd like to send this parcel to Brazil": "я хотел бы отправить эту посылку в Бразилию",
    "how much will it cost to send this letter to …?": "сколько будет стоит отправить это письмо в …?",
    "how much will it cost to send this letter to the United States?": "сколько будет стоит отправить это письмо в Америку?",
    "can you put it on the scales, please?": "положите это на весы, пожалуйста",
    "I'd like to send this letter by …": "я хотел бы отправить это письмо …",
    "I'd like to send this letter by Recorded Delivery": "я хотел бы отправить это письмо «Recorded Delivery» (при доставке необходима подпись)",
    "I'd like to send this letter by Special Delivery": "я хотел бы отправить это письмо «Special Delivery» (гарантированная доставка по Великобритании в течение суток с компенсацией потери или ущерба)",
    "where's the postbox?": "где находится почтовый ящик?",
}