slovar = {
    "do you have any brothers or sisters?": "у тебя есть брат или сестра?",
    "yes, I've got …": "да, у меня есть …",
    "yes, I've got a brother": "да, у меня есть брат",
    "yes, I've got a sister": "да, у меня есть сестра",
    "yes, I've got an elder brother": "да, у меня есть старший брат",
    "yes, I've got a younger sister": "да, у меня есть младшая сестра",
    "yes, I've got two brothers": "да, у меня есть два брата",
    "yes, I've got two sisters": "да, у меня есть две сестры",
    "yes, I've got one brother and two sisters": "да, у меня есть брат и две сестры",
    "no, I'm an only child": "нет, я единственный ребенок",
    "have you got any kids?": "у тебя есть дети?",
    "do you have any children?": "у тебя есть дети?",
    "yes, I've got a boy and a girl": "да, у меня мальчик и девочка",
    "yes, I've got a young baby": "да, у меня малыш",
    "yes, I've got three kids": "да, у меня три ребенка",
    "I don't have any children": "у меня нет детей",
    "do you have any grandchildren?": "у вас есть внуки?",
    "where do your parents live?": "где живут твои родители?",
    "what do your parents do?": "чем занимаются твои родители?",
    "what does your father do?": "чем занимается твой отец?",
    "what does your mother do?": "чем занимается твоя мать?",
    "are your grandparents still alive?": "твои бабушка и дедушка еще живы?"
}