slovar = {
    "it's too loud": "слишком громко",
    "it's too hot in here": "здесь слишком жарко",
    "are you ready to go home?": "ты готов идти домой?",
    "I'm going home": "я пойду домой",
    "is there anything on at the theatre …?": "что-нибудь идет в театре …?",
    "is there anything on at the theatre tonight?": "что-нибудь идет в театре сегодня?",
    "is there anything on at the theatre this week?": "что-нибудь идет в театре на этой неделе?",
    "is there anything on at the theatre this month?": "что-нибудь идет в театре в этом месяце?",
    "when's the play on until?": "во сколько заканчивается спектакль?",
    "what type of production is it?": "что это за представление?",
    "it's …": "это — …",
    "it's a tragedy": "это — трагедия",
    "it's a musical": "это — мюзикл",
    "it's an opera": "это — опера",
    "it's a ballet": "это — балет",
    "have you seen it before?": "ты уже раньше видел это?",
    "what time does the performance start?": "во сколько начинается представление?",
    "what time does it finish?": "во сколько это закачнивается?",
    "where's the cloakroom?": "где находится гардероб?",
    "would you like a programme?": "желаете программку?",
    "could I have a programme, please?": "не могли бы вы дать мне программку, пожалуйста?",
    "shall we order some drinks for the interval?": "закажем в антракте что-нибудь выпить?",
    "we'd better go back to our seats": "нам лучше вернуться на свои места",
    "did you enjoy it?": "тебе понравилось?",
    "Stalls": "Партер",
    "Circle": "Ярус",
    "Balcony": "Балкон",
    "Boxes": "Ложа",
    "what's on at the cinema?": "что идет в кино?",
    "is there anything good on at the cinema?": "в кино идет что-нибудь достойное?",
    "what's this film about?": "о чем это фильм?",
    "have you seen it?": "ты его уже видел?",
    "who's in it?": "кто в нем снимается?",
    "it's a thriller": "это — триллер",
    "it's a comedy": "это — комедия",
    "it's a romantic comedy": "это — романтическая комедия",
    "it's a horror film": "это — фильм ужасов",
    "it's a documentary": "это — документальный фильм",
    "it's an animation": "это — мультфильм",
    "it's a war film": "это — фильм про войну",
    "it's a western": "это — вестерн",
    "it's a science fiction film": "это — научно-популярный фильм",
    "it's a foreign film": "это — зарубежный фильм",
    "it's in …": "он на …",
    "it's in French": "он на французском",
    "it's in Spanish": "он на испанском",
    "with English subtitles": "с английскими субтитрами",
    "it's just been released": "он только что вышел на экраны",
    "it's been out for about two months": "он вышел около двух месяцев назад",
    "it's meant to be good": "он должен быть хорошим",
    "shall we get some popcorn?": "возьмем попкорн?",
    "salted or sweet?": "соленый или сладкий?",
    "do you want anything to drink?": "ты хочешь что-нибудь пить?",
    "where do you want to sit?": "где ты хочешь сидеть?",
    "in the middle": "в середине",
    "what did you think?": "что ты думаешь? (буквально: что ты думал?)",
    "I enjoyed it": "мне понравилось",
    "it was great": "это было великолепно",
    "it was really good": "он был действительно хорош",
    "it wasn't bad": "это было неплохо",
    "I thought it was rubbish": "я думаю это было ужасно",
    "it was one of the best films I've seen for ages": "это был лучший фильм, который я когда-либо видел",
    "it had a good plot": "сюжет был хороший",
    "the plot was quite complex": "сюжет был довольно запутанным",
    "it was too slow-moving": "было слишком затянуто",
    "it was very fast-moving": "было очень захватывающе",
    "the acting was …": "игра актеров была …",
    "the acting was excellent": "игра актеров была отличной",
    "the acting was good": "игра актеров была хорошей",
    "the acting was poor": "игра актеров была плачевной",
    "the acting was terrible": "игра актеров была ужасной",
    "he's a very good actor": "он очень хороший актер",
    "she's a very good actress": "она очень хорошая актриса",
    "Screen": "Экран",
    "do we need to book?": "мы должны забронировать?",
    "what tickets do you have available?": "какие билеты у вас есть в наличии?",
    "I'd like two tickets, please": "мне, пожалуйста, два билета",
    "I'd like two tickets for …": "мне, пожалуйста, два билета на …",
    "I'd like two tickets for tomorrow night": "мне, пожалуйста, два билета на завтрашний вечер",
    "I'd like two tickets for next Saturday": "мне, пожалуйста, два билета на следующую субботу",
    "I'd like four tickets to see …": "мне, пожалуйста, четыре билета на …",
    "I'd like four tickets to see Les Misérables": "мне, пожалуйста, четыре билета на «Отверженные»",
    "I'm sorry, it's fully booked": "извините, всё уже забронировано",
    "sorry, we've got nothing left": "извините, у нас ничего не осталось",
    "how much are the tickets?": "сколько стоят билеты?",
    "is there a discount for …?": "есть ли скидка …?",
    "is there a discount for students?": "есть ли скидка студентам?",
    "is there a discount for senior citizens?": "есть ли скидка пенсионерам?",
    "is there a discount for the unemployed?": "есть ли скидка безработным?",
    "is there a discount for children?": "есть ли скидка детям?",
    "where would you like to sit?": "где бы вы хотели сидеть?",
    "near the front": "впереди",
    "near the back": "сзади",
    "somewhere in the middle": "в центре",
    "how would you like to pay?": "как вы желаете заплатить?",
    "can I pay by card?": "могу я заплатить карточкой?",
    "what's the expiry date?": "когда у неё истекает срок действия?",
    "what's the start date?": "когда у неё начало срока действия?",
    "what's the security number on the back?": "какой секретный код на обратной стороне?",
    "please enter your PIN": "пожалуйста, введите ваш PIN-код",
    "where do I collect the tickets?": "где я могу получить билеты?",
    "the tickets were very cheap": "билеты были очень дешевыми",
    "the tickets were expensive": "билеты были дорогие",
    "Ticket office": "Билетные кассы",
    "Box office": "Билетные кассы",
    "Row": "Ряд",
    "Seat": "Место",
    "where's the …?": "где находится …?",
    "where's the cinema?": "где находится кинотеатр?",
    "where's the theatre?": "где находится театр?",
    "where's the art gallery?": "где находится художественная галерея?",
    "where's the museum?": "где находится музей?",
    "where's the concert hall?": "где находится концертный зал?",
}