slovar = {
    "we'd better go back to our seats": "нам лучше вернуться на свои места",
    "did you enjoy it?": "тебе понравилось?",
    "Stalls": "Партер",
    "Circle": "Ярус",
    "Balcony": "Балкон",
    "Boxes": "Ложа",
    "is there anything good on at the cinema?": "в кино идет что-нибудь достойное?",
    "what's this film about?": "о чем это фильм?",
    "have you seen it?": "ты его уже видел?",
    "who's in it?": "кто в нем снимается?",
    "it's a thriller": "это — триллер",
    "it's a comedy": "это — комедия",
    "it's a romantic comedy": "это — романтическая комедия",
    "it's a horror film": "это — фильм ужасов",
    "it's a documentary": "это — документальный фильм",
    "it's an animation": "это — мультфильм",
    "it's a war film": "это — фильм про войну",
    "it's a western": "это — вестерн",
    "it's a science fiction film": "это — научно-популярный фильм",
    "it's a foreign film": "это — зарубежный фильм",
    "it's in …": "он на …",
    "it's in French": "он на французском",
    "it's in Spanish": "он на испанском",
    "with English subtitles": "с английскими субтитрами",
    "it's just been released": "он только что вышел на экраны",
    "it's been out for about two months": "он вышел около двух месяцев назад",
    "it's meant to be good": "он должен быть хорошим",
    "shall we get some popcorn?": "возьмем попкорн?",
    "salted or sweet?": "соленый или сладкий?",
    "do you want anything to drink?": "ты хочешь что-нибудь пить?",
    "where do you want to sit?": "где ты хочешь сидеть?",
    "in the middle": "в середине",
    "what did you think?": "что ты думаешь? (буквально: что ты думал?)",
    "I enjoyed it": "мне понравилось",
    "it was great": "это было великолепно",
    "it was really good": "он был действительно хорош",
    "it wasn't bad": "это было неплохо",
    "I thought it was rubbish": "я думаю это было ужасно",
    "it was one of the best films I've seen for ages": "это был лучший фильм, который я когда-либо видел",
    "it had a good plot": "сюжет был хороший",
    "the plot was quite complex": "сюжет был довольно запутанным",
    "it was too slow-moving": "было слишком затянуто",
    "it was very fast-moving": "было очень захватывающе",
    "the acting was …": "игра актеров была …",
    "the acting was excellent": "игра актеров была отличной",
    "the acting was good": "игра актеров была хорошей",
    "the acting was poor": "игра актеров была плачевной",
    "the acting was terrible": "игра актеров была ужасной",
    "he's a very good actor": "он очень хороший актер",
    "she's a very good actress": "она очень хорошая актриса",
    "Screen": "Экран",
    "do we need to book?": "мы должны забронировать?",
    "what tickets do you have available?": "какие билеты у вас есть в наличии?",
    "I'd like two tickets, please": "мне, пожалуйста, два билета",
    "I'd like two tickets for …": "мне, пожалуйста, два билета на …",
    "I'd like two tickets for tomorrow night": "мне, пожалуйста, два билета на завтрашний вечер",
    "I'd like two tickets for next Saturday": "мне, пожалуйста, два билета на следующую субботу",
    "I'd like four tickets to see …": "мне, пожалуйста, четыре билета на …",
    "I'd like four tickets to see Les Misérables": "мне, пожалуйста, четыре билета на «Отверженные»",
    "I'm sorry, it's fully booked": "извините, всё уже забронировано",
    "sorry, we've got nothing left": "извините, у нас ничего не осталось",
    "how much are the tickets?": "сколько стоят билеты?",
    "is there a discount for …?": "есть ли скидка …?",
    "is there a discount for students?": "есть ли скидка студентам?",
    "is there a discount for senior citizens?": "есть ли скидка пенсионерам?",
    "is there a discount for the unemployed?": "есть ли скидка безработным?",
    "is there a discount for children?": "есть ли скидка детям?",
    "where would you like to sit?": "где бы вы хотели сидеть?",
    "near the front": "впереди",
    "near the back": "сзади",
    "somewhere in the middle": "в центре",
    "what's the expiry date?": "когда у неё истекает срок действия?",
    "what's the start date?": "когда у неё начало срока действия?",
    "what's the security number on the back?": "какой секретный код на обратной стороне?",
    "please enter your PIN": "пожалуйста, введите ваш PIN-код",
    "where do I collect the tickets?": "где я могу получить билеты?",
    "the tickets were very cheap": "билеты были очень дешевыми",
    "the tickets were expensive": "билеты были дорогие",
    "Ticket office": "Билетные кассы",
    "Box office": "Билетные кассы",
    "Row": "Ряд",
    "where's the cinema?": "где находится кинотеатр?",
    "where's the theatre?": "где находится театр?",
    "where's the concert hall?": "где находится концертный зал?",
    "where's the stadium?": "где находится стадион?",
    "do you want to go out tonight?": "хочешь прогуляться сегодня вечером?",
    "let's go to …": "давай пойдем в …",
    "let's go to the pub": "давай пойдем в паб",
    "let's go to the cinema": "давай пойдем в кино",
    "let's go to the theatre": "давай пойдем в театр",
    "let's go to a concert": "давай пойдем в концерт",
    "let's go to a nightclub": "давай пойдем в ночной клуб",
    "what's on at the …?": "что идет в …?",
    "what's on at the cinema?": "что идет в кино?",
    "what's on at the theatre?": "что идет в театре?",
    "is there anything good on?": "там идет что-нибудь хорошее?",
    "shall we go …?": "может пойдем …?",
    "shall we go swimming?": "может пойдем поплаваем?",
    "shall we go skating?": "может пойдем покатаемся на коньках?",
    "shall we go bowling?": "может пойдем поиграем в боулинг?",
    "shall we go for a walk?": "может пойдем погуляем?",
    "shall we go for a bike ride?": "может покатаемся на велосипеде?",
    "excuse me, could you take a photo for me?": "извините, вы могли бы меня сфотографировать?",
    "excuse me, could you take a photo for us?": "извините, вы могли бы нас сфотографировать?",
    "I'd like to hire a bike": "я хотел бы взять велосипед на прокат",
    "I'd like to hire a canoe": "я хотел бы взять байдарку на прокат",
    "it's a beautiful view": "красивый вид",
    "what kind of accommodation are you looking for?": "какой вид жилья вы ищете?",
    "I'm looking for a flat": "я ищу квартиру",
    "I'm looking for an apartment": "я ищу квартиру",
    "I'm looking for a semi-detached house": "я ищу дом, с одной стороны соединенный с соседним домом стеной",
    "I'm looking for a detached house": "я ищу отдельный дом",
    "I'm looking for a terraced house": "я ищу рядный дом",
}