slovar = {
    "an hour ago": "час назад",
    "a week ago": "неделю назад",
    "two weeks ago": "две недели назад",
    "a month ago": "месяц назад",
    "a year ago": "год назад",
    "a long time ago": "давным-давно",
    "in ten minutes' time": "через десять минут",
    "in ten minutes": "через десять минут",
    "in an hour's time": "через час",
    "in an hour": "через час",
    "in a week's time": "через неделю",
    "in a week": "через неделю",
    "in ten days' time": "через десять дней",
    "in ten days": "через десять дней",
    "in three weeks' time": "через три недели",
    "in three weeks": "через три недели",
    "in two months' time": "через два месяца",
    "in two months": "через два месяца",
    "in ten years' time": "через десять лет",
    "in ten years": "через десять лет",
    "the previous day": "в предыдущий день",
    "the previous week": "на предыдущей неделе",
    "the previous month": "в предыдущем месяце",
    "the previous year": "в предыдущем году",
    "the following day": "на следующий день",
    "the following week": "на следующей неделе",
    "the following month": "в следующем месяце",
    "the following year": "в следующем году",
    "I lived in Canada for six months": "я жил в Канаде шесть месяцев",
    "I've worked here for nine years": "я работаю здесь девять лет",
    "I'm going to France tomorrow for two weeks": "завтра я уезжаю во Францию на две недели",
    "we were swimming for a long time": "мы долго плавали",
    "could I use your phone?": "можно воспользоваться телефоном?",
    "your taxi's here": "твое такси здесь, ваше такси здесь",
    "thanks for coming": "спасибо, что зашел; спасибо, что зашли",
    "have a safe journey home": "безопасного возвращения домой",
    "do you have any plans for the summer?": "у тебя есть планы на лето?",
    "what are you doing for …?": "что ты делаешь на …?",
    "what are you doing for Christmas?": "что ты делаешь на Рождество?",
    "what are you doing for New Year?": "что ты делаешь на Новый год?",
    "what are you doing for Easter?": "что ты делаешь на Пасху?",
    "I share with one other person": "я живу с одним человеком",
    "I share with … others": "я живу с … другими",
    "I share with two others": "я живу с двумя другими",
    "I share with three others": "я живу с тремя другими",
    "what's your email address?": "какой у тебя электронный адрес?",
    "could I take your email address?": "можно записать твой электронный адрес?",
    "are you on …?": "ты зарегистрирован в …?",
    "are you on Facebook?": "ты зарегистрирован в Facebook?",
    "are you on Skype?": "ты зарегистрирован в Skype?",
    "what's your username?": "какое у тебя там имя?",
    "have you got any pets?": "у тебя есть домашние животные?",
    "I've got …": "у меня …",
    "I've got a dog and two cats": "у меня собака и две кошки",
    "I've got a Labradorу": "меня лабрадор",
    "what's his name?": "как его зовут?",
    "he's called …": "его зовут …",
    "he's called Tom": "его зовут Том",
    "what's the time?": "сколько времени?",
    "what time is it?": "который час?",
    "could you tell me the time, please?": "скажите, пожалуйста, сколько времени?",
    "do you happen to have the time?": "не подскажете который час?",
    "do you know what time it is?": "вы знаете сколько сейчас времени?",
    "it's exactly ...": "сейчас ровно ...",
    "it's about ...": "сейчас примерно ...",
    "it's almost ...": "сейчас почти ...",
    "it's just gone ...": "сейчас немного больше, чем ...",
    "one o'clock": "час",
    "two o'clock": "два часа",
    "three o'clock": "три часа",
    "four o'clock": "четыре часа",
    "five o'clock": "пять часов",
    "six o'clock": "шесть часов",
    "seven o'clock": "семь часов",
    "eight o'clock": "восемь часов",
    "ten o'clock": "десять часов",
    "eleven o'clock": "одиннадцать часов",
    "twelve o'clock": "двенадцать часов",
    "nine o'clock": "девять часов",
    "quarter past …": "четверть …",
    "quarter past one": "четверть второго",
    "quarter past two": "четверть третьего",
    "quarter past three": "четверть четвертого",
    "half past …": "половина …",
    "half past one": "половина второго",
    "half past two": "половина третьего",
    "half past three": "половина четвертого",
    "quarter to …": "без четверти …",
    "quarter to one": "без четверти час",
    "quarter to two": "без четверти два",
    "quarter to three": "без четверти три",
    "five past one": "пять минут второго",
    "ten past one": "десять минут второго",
    "twenty past one": "двадцать минут второго",
    "twenty-five past one": "двадцать пять минут второго",
    "five to two": "без пяти два",
    "ten to two": "без десяти два",
    "twenty to two": "без двадцати два",
    "twenty-five to two": "без двадцати пяти два",
    "ten fifteen": "десять часов пятнадцать минут",
    "ten thirty": "десять часов тридцать минут",
}