slovar = {
    "could I put this in the hold, please?": "могу я положить это в багаж, пожалуйста?",
    "could you tell me when we get to …?": "скажите мне, пожалуйста, когда мы доедем до …",
    "could you tell me when we get to the university?": "скажите мне, пожалуйста, когда мы доедем до университета",
    "could you please stop at …?": "остановитесь, пожалуйста, в …",
    "could you please stop at the airport?": "остановитесь, пожалуйста, в аэропорту",
    "is this seat free?": "это место свободно?",
    "is this seat taken?": "это место занято?",
    "do you mind if I sit here?": "не возражаете, если я здесь сяду?",
    "tickets, please": "билеты, пожалуйста",
    "all tickets and railcards, please": "билеты и проездные карты, пожалуйста",
    "could I see your ticket, please?": "покажите ваш билет, пожалуйста",
    "I've lost my ticket": "я потерял билет",
    "what time do we arrive in …?": "во сколько мы прибываем в …?",
    "what time do we arrive in Sheffield?": "во сколько мы прибываем в Шеффилд?",
    "what's this stop?": "что это за остановка?",
    "what's the next stop?": "какая следующая остановка?",
    "this is my stop": "это моя остановка",
    "I'm getting off here": "я выхожу здесь",
    "is there a buffet car on the train?": "есть ли в поезде вагон-ресторан?",
    "do you mind if I open the window?": "вы не возражаете, если я открою окно?",
    "we are now approaching London Kings Cross": "мы прибываем на станцию Кингс-кросс",
    "this train terminates here": "этот поезд дальше не идёт",
    "all change, please": "всем пересесть, пожалуйста",
    "please take all your luggage and personal belongings with you": "пожалуйста заберите багаж и все персональные вещи",
    "could you tell me where the nearest Tube station is?": "не могли бы вы сказать, где ближайшая станция метро?",
    "where's there a map of the Underground?": "где здесь схема метро?",
    "over there": "там",
    "which line do I need for Camden Town?": "на какой линии находится Камден-таун?",
    "how many stops is it to …?": "сколько остановок до …?",
    "how many stops is it to Westminster?": "сколько остановок до Вестминстера?",
    "I'd like a Day Travelcard, please": "я хотел бы билет на день, пожалуйста",
    "which zones?": "в какие зоны?",
    "zones 1-2": "зоны 1—2",
    "I'd like an Oyster card, please": "я хотел бы карту «Ойстер», пожалуйста (карта с предоплатой для путешествия на общественном транспорте в Лондоне)",
    "I'd like to put £10 on it": "я хотел бы положить 10 фунтов",
    "Tickets": "Билеты",
    "Platform": "Платформа",
    "Waiting room": "Зал ожидания",
    "Left luggage": "Багажное отделение",
    "Lost property": "Бюро находок",
    "Underground": "Метро",
    "Bus stop": "Остановка автобуса",
    "Request stop": "Остановка по требованию",
    "On time": "Вовремя",
    "Expected": "Прибывает",
    "Delayed": "Задерживается",
    "Cancelled": "Отменен",
    "Calling at ...": "Останавливается в ...",
    "Seat": "Место",
    "Car": "Купе",
    "Priority seat": "Специальные места (места для беременных, пожилых или инвалидов)",
    "To trains": "К поездам",
    "Trains to London": "Поезда на Лондон",
    "Way out": "Выход",
    "Mind the gap": "Осторожно, щель",
    "Northbound platform": "Платформа северного направления",
    "Eastbound platform": "Платформа восточного направления",
    "Southbound platform": "Платформа южного направления",
    "Westbound platform": "Платформа южного направления",
    "I'd like to hire a car": "я хотел бы взять автомобиль на прокат",
    "how long for?": "как надолго?",
    "for how many days?": "на сколько дней?",
    "for …": "на …",
    "for one day": "на один день",
    "for two days": "на два дня",
    "for a week": "на неделю",
    "how much does it cost?": "сколько это стоит?",
    "£40 a day with unlimited mileage": "40 фунтов в день без ограничения расстояния",
    "what type of car do you want — manual or automatic?": "какой тип коробки передач вы хотите — мануальный или автоматический?",
    "has this car got …?": "в машине есть …?",
    "has this car got air conditioning?": "в машине есть кондиционер?",
    "has this car got central locking?": "в машине есть центральный замок?",
    "has this car got a CD player?": "в машине есть проигрыватель компакт-дисков?",
    "has this car got child locks?": "в машине есть «детские» замки?",
    "could I see your driving licence?": "покажите ваши водительские права",
    "you have to bring it back with a full tank": "вы должны вернуть её с полным баком",
    "it has to be returned by 2pm on Saturday": "она должна быть возвращена до 2 часов дня в воскресенье",
    "remember to drive on the …": "двигайтесь по …",
    "remember to drive on the left": "двигайтесь по левой стороне",
    "remember to drive on the right": "двигайтесь по правой стороне",
    "does it take petrol or diesel?": "машина бензиновая или дизельная?",
    "is it manual or automatic?": "коробка передач мануальная или автоматическая?",
    "I'll show you the controls": "я покажу вам выключатели",
    "where are the …?": "где включаются …?",
    "where are the lights?": "где включаются фары?",
    "where are the indicators?": "где включаются поворотники?",
    "where are the windscreen wipers?": "где включаются дворники?",
    "how do you open the …?": "как открывается …?",
    "how do you open the petrol tank?": "как открывается топливный бак?",
    "how do you open the boot?": "как открывается багажник?",
    "how do you open the bonnet?": "как открывается капот?",
    "do you know where I can get a taxi?": "ты знаешь, где можно поймать такси?",
    "do you have a taxi number?": "у тебя есть номер такси?",
    "I'd like a taxi, please": "я хотел бы заказать такси, пожалуйста",
    "sorry, there are none available at the moment": "извините, сейчас свободных такси нет",
    "where are you?": "где вы?",
    "what's the address?": "какой адрес?",
    "I'm …": "я …",
    "I'm at the Metropolitan Hotel": "я в отеле «Метрополь»",
    "I'm at the train station": "я на железнодорожном вокзале",
    "I'm at the corner of Oxford Street and Tottenham Court Road": "я на углу Оксфордстрит и Тоттенхэмкортроад",
    "could I take your name, please?": "назовите свое имя, пожалуйста",
    "how long will I have to wait?": "как долго ждать?",
    "how long will it be?": "сколько ждать?",
    "quarter of an hour": "четверть часа",
    "about ten minutes": "около десяти минут",
    "it's on its way": "машина в пути",
    "where would you like to go?": "куда бы вы хотели поехать?",
    "I'd like to go to …": "я хотел бы поехать …",
    "I'd like to go to Charing Cross station": "я хотел бы поехать на станцию «Чаринг Кросс»",
    "could you take me to …?": "не могли бы вы отвезти меня в …?",
    "could you take me to the city centre?": "не могли бы вы отвезти меня в центр города?",
    "how much would it cost to …?": "сколько стоит доехать до …?",
    "how much would it cost to Heathrow Airport?": "сколько стоит доехать до аэропорта «Хитроу»?",
    "how much will it cost?": "сколько это будет стоить?",
    "could we stop at a cashpoint?": "могли бы мы остановиться у банкомата?",
    "is the meter switched on?": "включен ли таксометр?",
    "please switch the meter on": "пожалуйста, включите таксометр",
    "how long will the journey take?": "сколько туда ехать?",
    "do you mind if I close the window?": "вы не против, если я закрою окно?",
    "are we almost there?": "мы уже почти приехали?",
    "how much is it?": "сколько с меня?",
    "have you got anything smaller?": "у вас есть более мелкие деньги?",
}