slovar = {
    "yes": "да",
    "no": "нет",
    "maybe": "может быть",
    "perhaps": "может быть",
    "please": "пожалуйста",
    "thanks": "спасибо",
    "thank you": "спасибо",
    "thanks very much": "большое спасибо",
    "thank you very much": "большое спасибо",
    "you're welcome": "пожалуйста",
    "don't mention it": "не за что",
    "not at all": "не стоит благодарности",
    "hi": "привет (дружеское)",
    "hello": "здравствуйте",
    "good morning": "доброе утро (используется до полудня)",
    "good afternoon": "добрый день (используется с полудня до 6 часов вечера)",
    "good evening": "добрый вечер (используется после 6 часов вечера)",
    "bye": "пока",
    "goodbye": "до свидания",
    "goodnight": "спокойной ночи",
    "see you!": "увидимся!",
    "see you soon!": "до скорого!",
    "see you later!": "увидимся!",
    "have a nice day!": "хорошего дня!",
    "have a good weekend!": "хороших выходных!",
    "excuse me": "простите (может использоваться для привлечения внимания или при извинении)",
    "sorry": "извините",
    "no problem": "ничего страшного",
    "it's OK": "все в порядке",
    "that's OK": "все в порядке",
    "don't worry about it": "не стоит беспокойства",
    "do you speak English?": "вы говорите по-английски?",
    "I don't speak English": "я не говорю по-английски",
    "I don't speak much English": "я не очень хорошо говорю по-английски",
    "I only speak very little English": "я только чуть-чуть говорю по-английски",
    "I speak a little English": "я немного говорю по-английски",
    "please speak more slowly": "пожалуйста, говорите медленнее",
    "please write it down": "пожалуйста, напишите это",
    "could you please repeat that?": "не могли бы вы повторить?",
    "I understand": "я понимаю",
    "I don't understand": "я не понимаю",
    "I know": "я знаю",
    "I don't know": "я не знаю",
    "excuse me, where's the toilet?": "извините, где находится туалет?",
    "excuse me, where's the Gents?": "извините, где мужской туалет?",
    "excuse me, where's the Ladies?": "извините, где женский туалет?",
    "Entrance": "Вход",
    "Exit": "Выход",
    "Emergency exit": "Запасной выход",
    "Push": "От себя",
    "Pull": "На себя",
    "Toilets": "Туалеты",
    "WC": "Туалет",
    "Gentlemen": "Мужчины",
    "Gents": "Мужчины",
    "Ladies": "Женщины",
    "Vacant": "Свободно",
    "Occupied": "Занято",
    "Engaged": "Занято",
    "Out of order": "Не работает",
    "No smoking": "Не курить",
    "Private": "Частная собственность",
    "No entry": "Вход воспрещен",
}