slovar = {
    "Dear Mark,": "Дорогой Марк,",
    "Dear Jane,": "Дорогая Джейн,",
    "Thanks for your …": "Спасибо за …",
    "Thanks for your letter": "Спасибо за письмо",
    "Thanks for your postcard": "Спасибо за открытку",
    "Thanks for your present": "Спасибо за подарок",
    "Thanks for your invitation": "Спасибо за приглашение",
    "Sorry it's taken me so long to write.": "Извини, что давно не писал.",
    "I hope you're well.": "Надеюсь, у тебя все хорошо.",
    "Good to see you again last week.": "Рад был тебя видеть на прошлой неделе.",
    "Look forward to seeing you soon!": "С нетерпением жду встречи!",
    "Best wishes,": "С наилучшими пожеланиями,",
    "Love,": "С любовью,",
    "Regards,": "С пожеланиями,",
    "Kind regards,": "С добрыми пожеланиями,",
    "Best regards,": "С наилучшими пожеланиями,",
    "With kind regards,": "С добрыми пожеланиями,",
    "Dear Mr Smith,": "Дорогой мистер Смит,",
    "Dear Mrs Jones,": "Дорогая миссис Джонс",
    "Dear Miss Richards,": "Дорогая мисс Ричардс",
    "Dear Ms Shepherd,": "Дорогая госпожа Шепард",
    "Dear Sir,": "Дорогой Господин,",
    "Dear Madam,": "Дорогая Госпожа,",
    "Dear Sir or Madam,": "Дорогой Господин или дорогая Госпожа,",
    "I am writing in reply to your letter of 4 September regarding your outstanding invoice.": "Пишу Вам в ответ на письмо от 4-го сентября, касательно Вашего неоплаченного счета.",
    "Further to our conversation, I'm pleased to confirm our appointment for 9.30am on Tuesday, 7 January.": "В продолжение нашей беседы я рад подтвердить, что наша встреча состоится во вторник 7-го января в 9:30.",
    "I would be grateful if you could attend to this matter as soon as possible.": "Пожалуйста отреагируйте на это как можно быстрее.",
    "If you would like any further information, please don't hesitate to contact me.": "Если Вы заинтересованы в получении дополнительной информации, пожалуйста свяжитесь со мной.",
    "I look forward to hearing from you.": "С нетерпением жду Вашего ответа.",
    "Yours sincerely,": "Искренне Ваш,",
    "Yours faithfully,": "Искренне Ваш,",
    "hello!": "алло!",
    "John speaking": "говорит Джон",
    "it's Maria here": "это Мария",
    "could I speak to …, please?": "могу я поговорить с …, пожалуйста?",
    "could I speak to Bill, please?": "могу я поговорить с Билом, пожалуйста?",
    "speaking!": "это я! (буквально: говорю!)",
    "who's calling?": "кто звонит?",
    "could I ask who's calling?": "могу я узнать, кто звонит?",
    "where are you calling from?": "откуда вы звоните?",
    "what company are you calling from?": "из какой компании вы звоните?",
    "how do you spell that?": "произнесите как это пишется, пожалуйста",
    "do you know what extension he's on?": "вы знаете на какой он линии?",
    "one moment, please": "один момент, пожалуйста",
    "hold the line, please": "оставайтесь на линии, пожалуйста",
    "I'll put him on": "соединяю с ним",
    "I'll put her on": "соединяю с ней",
    "I'm sorry, he's …": "извините, он …",
    "I'm sorry, he's not available at the moment": "извините, он сейчас занят",
    "I'm sorry, he's in a meeting": "извините, он на встрече",
    "I'm sorry, she's …": "извините, она …",
    "I'm sorry, she's on another call": "извините, она говорит по другому телефону",
    "I'm sorry, she's not in at the moment": "извините, она отсутствует",
    "would you like to leave a message?": "вы хотите оставить сообщение?",
    "could you ask him to call me?": "вы можете попросить его позвонить мне?",
    "could you ask her to call me?": "вы можете попросить её позвонить мне?",
    "can I take your number?": "могу я узнать ваш номер?",
    "what's your number?": "какой у вас номер?",
    "could I take your name and number, please?": "могу я узнать ваше имя и номер, пожалуйста?",
    "I'll call back later": "я перезвоню позже",
    "is it convenient to talk at the moment?": "вам удобно сейчас разговаривать?",
    "can I call you back?": "могу я вам перезвонить?",
    "please call back later": "пожалуйста, перезвоните позже",
    "thanks for calling": "спасибо, что позвонили",
    "how do I get an outside line?": "как выйти на внешнюю линию?",
    "have you got a telephone directory?": "у вас есть телефонный справочник?",
    "can I use your phone?": "можно воспользоваться вашим телефоном?",
    "I'm sorry, I'm not interested": "извините, я не заинтересован",
    "sorry, I'm busy at the moment": "извините, я сейчас занят",
    "I can't get a dialling tone": "нет гудка",
    "the line's engaged": "линия занята",
    "I can't get through at the moment": "я не могу дозвониться",
    "I'm only getting an answering machine": "я попадаю на автоответчик",
    "sorry, you must have the wrong number": "извините, вы ошиблись номером",
    "can you hear me OK?": "вы меня хорошо слышите?",
    "I can't hear you very well": "я плохо вас слышу",
    "it's a bad line": "связь плохая",
    "could you please repeat that?": "повторите это ещё раз, пожалуйста?",
    "I've been cut off": "меня разъединили",
    "do you know the number for …?": "вы знаете номер …?",
    "do you know the number for directory enquiries?": "вы знаете номер справки телефонных номеров?",
    "do you know the number for international directory enquiries?": "вы знаете номер справки международных телефонных номеров?",
    "could you tell me the number for …?": "вы могли бы сказать мне номер …?",
    "could you tell me the number for the National Gallery?": "вы могли бы сказать мне номер Национальной галереи?",
    "do you know the address?": "вы знаете адрес?",
    "I'm afraid that number's ex-directory": "боюсь, что этого номера нет в справочнике",
    "could you tell me the dialing code for …?": "могли бы вы сказать мне код набора …?",
    "could you tell me the dialing code for Manchester?": "могли бы вы сказать мне код набора Манчестера?",
    "my battery's about to run out": "моя батарея почти разрядилась",
    "I need to charge up my phone": "мне нужно зарядить свой телефон",
    "I'm about to run out of credit": "у меня почти закончился кредит",
    "sorry, I ran out of credit": "извините, у меня закончился кредит",
    "I can't get a signal": "я не могу поймать сигнал",
    "I've got a very weak signal": "у меня очень слабый сигнал",
    "I'll send you a text": "я пошлю тебе сообщение",
    "I'll text you later": "я позже пошлю тебе сообщение",
    "could I borrow your phone, please?": "можно воспользоваться твоим телефоном, пожалуйста?",
    "I'd like a phonecard, please": "я хотел бы телефонную карточку, пожалуйста",
    "Thank you for calling.": "Спасибо, что позвонили.",
    "There's no-one here to take your call at the moment.": "Сейчас нет никого, кто мог бы ответить на ваш звонок.",
    "Please leave a message after the tone, and we'll get back to you as soon as possible.": "Пожалуйста, оставьте сообщение после сигнала, и мы свяжемся с вами",
    "I saw your advert in the paper": "я видел ваше объявление в газете",
    "could I have an application form?": "могу я получить анкету?",
    "could you send me an application form?": "могли бы вы прислать мне анкету?",
}