slovar = {
    "it's much too small": "это слишком сильно мало",
    "it's a little too small": "это немного мало",
    "it's a little too big": "это немного велико",
    "it's much too big": "это слишком сильно велико",
    "it's just right": "это как раз подходит",
    "they're just right": "это как раз подходит",
    "they don't fit": "они не подходят",
    "how do they feel?": "как вам в них?",
    "do they feel comfortable?": "вам в них удобно?",
    "it suits you": "это идёт вам",
    "they suit you": "это идёт вам",
    "is this the only colour you've got?": "это только такого цвета?",
    "what do you think of these?": "что вы думаете об этом?",
    "I like them": "мне нравятся",
    "I don't like them": "мне не нравятся",
    "I don't like the colour": "мне не нравится цвет",
    "what are these made of?": "из чего это сделано?",
    "are these washable?": "это можно стирать?",
    "no, they have to be dry-cleaned": "нет, это надо чистить в химчистке",
    "I'll take them": "я возьму",
    "I'll take these": "я возьму эти",
    "Menswear": "Мужская одежда",
    "Womenswear": "Женская одежда",
    "Ladieswear": "Женская одежда",
    "Childrenswear": "Детская одежда",
    "Babywear": "Одежда для малышей",
    "Fitting room": "Примерочные кабинки",
    "Size": "Размер",
    "S": "Маленький",
    "Small": "Маленький",
    "M": "Средний",
    "Medium": "Средний",
    "L": "Большой",
    "Large": "Большой",
    "XL": "Очень Большой",
    "Extra-large": "Очень Большой",
    "could you tell me where the milk is?": "могли бы вы сказать где молоко?",
    "could you tell me where the bread counter is?": "могли бы вы сказать где хлебный прилавок?",
    "could you tell me where the meat section is?": "могли бы вы сказать где мясной отдел?",
    "could you tell me where the frozen food section is?": "могли бы вы сказать где отдел замороженной пищи?",
    "I'd like that piece of cheese": "я хотел бы этот кусочек сыра",
    "I'd like a slice of pizza": "я хотел бы ломтик пиццы",
    "I'd like six slices of ham": "я хотел бы шесть ломтиков ветчины",
    "I'd like some olives": "я хотел бы оливки",
    "how much would you like?": "сколько вы хотели бы?",
    "300 grams": "300 грамм",
    "half a kilo": "полкило",
    "two pounds": "два фунта (один фунт ― приблизительно 450 граммов)",
    "that's £32.47": "это стоит 32,47 фунта",
    "could I have a carrier bag, please?": "можно пакет, пожалуйста?",
    "could I have another carrier bag, please?": "можно ещё пакет, пожалуйста?",
    "do you need any help packing?": "помочь вам упаковать?",
    "do you have a loyalty card?": "у вас есть клиентская карточка?",
    "Checkout": "Касса",
    "8 items or less": "8 предметов или меньше",
    "Basket only": "Только для корзинок",
    "Cash only": "Только наличные",
    "Best before end": "Годен до",
    "Use by": "Использовать до",
    "what times are you open?": "когда вы открыты?",
    "we're open from 9am to 5pm, Monday to Friday": "мы открыты с 9 утра до 5 вечера, с понедельника по пятницу",
    "we're open from 10am to 8pm, seven days a week": "мы открыты с 10 утра до 8 вечера, семь дней в неделю",
    "are you open on …?": "вы открыты в …?",
    "are you open on Saturday?": "вы открыты в субботу?",
    "are you open on Sunday?": "вы открыты в воскресенье?",
    "what time do you close?": "во сколько вы закрываетесь?",
    "what time do you close today?": "во сколько вы сегодня закроетесь?",
    "what time do you open tomorrow?": "во-сколько вы открываетесь завтра?",
    "can I help you?": "могу я вам помочь?",
    "I'm just browsing, thanks": "я просто присматриваюсь, спасибо",
    "how much is this?": "сколько за это?",
    "how much are these?": "сколько за эти?",
    "how much does this cost?": "сколько это стоит?",
    "how much is that … in the window?": "сколько стоит … на витрине?",
    "how much is that lamp in the window?": "сколько стоит лампа на витрине?",
    "that's cheap": "это дешево",
    "that's good value": "это подходящая цена",
    "that's expensive": "это дорого",
    "do you sell …?": "вы продаёте …?",
    "do you sell stamps?": "вы продаёте марки?",
    "do you have any …?": "у вас есть какие-нибудь …?",
    "do you have any postcards?": "у вас есть какие-нибудь открытки?",
    "sorry, we don't sell them": "извините, их нет в продаже",
    "sorry, we don't have any left": "извините, их не осталось",
    "I'm looking for …": "я ищу …",
    "I'm looking for the shampoo": "я ищу шампунь",
    "I'm looking for a birthday card": "я ищу поздравительную открытку",
    "could you tell me where the … is?": "могли бы вы сказать, где …?",
    "could you tell me where the washing up liquid is?": "могли бы вы сказать, где моющее средство?",
    "where can I find the …?": "где я могу найти …?",
    "where can I find the toothpaste?": "где я могу найти зубную пасту?",
    "it's not what I'm looking for": "это не то, что я ищу",
    "do you have this item in stock?": "у вас есть это в продаже?",
    "do you know anywhere else I could try?": "вы знаете, где ещё можно посмотреть?",
    "does it come with a guarantee?": "есть ли на это гарантия?",
    "it comes with a one year guarantee": "на это один год гарантии",
    "do you deliver?": "вы делаете доставку?",
    "I'll take it": "я это возьму",
    "anything else?": "что-то ещё?",
    "are you in the queue?": "вы в очереди?",
    "next, please!": "следующий, пожалуйста",
    "I'll pay by card": "я заплачу карточкой",
    "would you be able to gift wrap it for me?": "вы сможете упаковать это как подарок?",
    "would you like a bag?": "вам нужен пакет?",
    "I'd like to return this": "я хотел бы вернуть это",
    "I'd like to change this for a different size": "я хотел бы поменять это на другой размер",
    "it doesn't work": "это не работает",
    "it doesn't fit": "это не подходит",
    "could I have a refund?": "могу я получить деньги обратно?",
    "have you got the receipt?": "у вас есть чек?",
    "could I speak to the manager?": "могу я поговорить с менеджером?",
    "Open": "Открыто",
    "Closed": "Закрыто",
    "Open 24 hours a day": "Открыто 24 часа в день",
    "Special offer": "Спецпредложение",
    "Sale": "Распродажа",
    "Clearance sale": "Окончательная распродажа",
}