slovar = {
    "£2,000 a month": "2000 фунтов в месяц",
    "£30,000 a year": "30 000 фунтов в год",
    "will I be paid weekly or monthly?": "мне будут платить еженедельно или ежемесячно?",
    "will I get travelling expenses?": "будут ли покрываться транспортные расходы?",
    "will I get paid for overtime?": "мне будут платить за сверхурочное время?",
    "is there …?": "есть ли …?",
    "is there a company car?": "есть ли служебная машина?",
    "is there a staff restaurant?": "есть ли столовая для служащих?",
    "is there a pension scheme?": "есть ли пенсионная схема?",
    "is there free medical insurance?": "есть ли бесплатное медицинское страхование?",
    "how many weeks' holiday a year are there?": "сколько недель составляет отпуск?",
    "who would I report to?": "кому я должен сообщить?",
    "I'd like to take the job": "я хотел бы приступить к работе",
    "when do you want me to start?": "когда я должен начать?",
    "we'd like to invite you for an interview": "мы хотели бы пригласить вас на собеседование",
    "this is the job description": "это – описание работы",
    "have you got any experience?": "у вас есть какой-нибудь опыт?",
    "have you got any qualifications?": "вы обладаете какими-либо качествами?",
    "we need someone with experience": "нам нужен кто-то с опытом",
    "we need someone with qualifications": "нам нужен специалист",
    "what qualifications have you got?": "какими профессиональными качествами вы обладаете?",
    "have you got a current driving licence?": "у вас есть водительские права?",
    "how much were you paid in your last job?": "сколько вы зарабатывали на прежней работе?",
    "do you need a work permit?": "вам нужно разрешение на работу?",
    "we'd like to offer you the job": "мы бы хотели предложить вам работу",
    "when can you start?": "когда вы сможете начать?",
    "how much notice do you have to give?": "как долго вы должны еще оставаться на нынешней работе?",
    "there's a three month trial period": "три месяца — испытательный срок",
    "we'll need to take up references": "нам нужно получить рекомендации",
    "this is your employment contract": "это ваш рабочий договор",
    "Name": "Имя",
    "Address": "Адрес",
    "Telephone number": "Телефонный номер",
    "Email address": "Адрес электронной почты",
    "Date of birth": "Дата рождения",
    "Nationality": "Национальность",
    "Marital status": "Семейное положение",
    "Career objective": "Предположительный карьерный рост",
    "Education": "10",
    "Qualifications": "Качества",
    "Employment history": "История трудоустройства",
    "Leisure interests": "8",
    "Referees": "Поручители",
    "how long have you worked here?": "как долго ты здесь работаешь?",
    "I'm going out for lunch": "я пойду обедать",
    "I'll be back at 1.30": "я вернусь в полвторого",
    "how long does it take you to get to work?": "сколько времени ты добираешься до работы?",
    "the traffic was terrible today": "сегодня было очень много машин",
    "how do you get to work?": "как ты добираешься до работы?",
    "you're fired!": "ты уволен!",
    "she's on maternity leave": "она в декретном отпуске",
    "he's on paternity leave": "он в отпуске по уходу за ребенком",
    "he's off sick today": "он сегодня приболел",
    "he's not in today": "его сегодня нет",
    "she's on holiday": "она в отпуске",
    "I'm afraid I'm not well and won't be able to come in today": "боюсь, что я плохо себя чувствую и не смогу сегодня прийти",
    "he's with a customer at the moment": "он сейчас общается с клиентом",
    "I'll be with you in a moment": "один момент, пожалуйста",
    "do you need any help?": "вам нужна помощь?",
    "what can I do for you?": "что я могу для вас сделать?",
    "he's in a meeting": "он на собрании",
    "what time does the meeting start?": "во сколько начинается собрание?",
    "what time does the meeting finish?": "во сколько заканчивается собрание?",
    "the reception's on the first floor": "приемная на втором этаже",
    "I'll be free after lunch": "я освобожусь после обеда",
    "she's having a leaving-do on Friday": "у нее прощальная вечеринка в пятницу (разговорное)",
    "she's resigned": "она уходит с работы",
    "this invoice is overdue": "этот счет просроченный",
    "he's been promoted": "его повысили в должности",
    "here's my business card": "это моя визитка",
    "can I see the report?": "могу я посмотреть отчет?",
    "I need to do some photocopying": "мне нужно сделать копии",
    "where's the photocopier?": "где копировальная машина?",
    "the photocopier's jammed": "копировальная машина заела",
    "I've left the file on your desk": "я оставил папку на твоем столе",
    "there's a problem with my computer": "у меня проблема с компьютером",
    "the system's down at the moment": "система в данный момент не работает",
    "the internet's down at the moment": "интернета в данный момент нет",
    "I can't access my emails": "я не могу открыть свой почтовый ящик",
    "the printer isn't working": "принтер не работает",
    "do you offer free eye tests?": "вы делаете бесплатную проверку зрения?",
    "I'd like to have an eye test, please": "я хотел бы проверить зрение, пожалуйста",
    "I need a new …": "мне нужны …",
    "I need a new pair of glasses": "мне нужны новые очки",
    "I need a new pair of reading glasses": "мне нужны новые очки для чтения",
    "I need a new glasses' case": "мне нужны новый футляр для очков",
    "could I order some more contact lenses?": "могу я заказать дополнительные контактные линзы?",
    "the frame on these glasses is broken": "оправа этих очков сломана",
    "can you repair it?": "вы можете починить?",
    "do you sell sunglasses?": "у вас продаются солнечные очки?",
    "how much are these designer frames?": "сколько стоят эти дизайнерские оправы?",
    "my eyesight's getting worse": "у меня портится зрение",
    "do you wear contact lenses?": "вы носите контактные линзы?",
    "are you short-sighted or long-sighted?": "вы близорукий или дальнозоркий?",
    "could you read out the letters on the chart, starting at the top?": "прочитайте, пожалуйста, буквы в столбце, начиная сверху",
    "could you close your left eye, and read this with your right?": "закройте, пожалуйста, ваш левый глаз и читайте это правым",
    "do you do hearing tests?": "вы проверяете слух?",
    "can I make an appointment to see the …?": "можно записаться на прием к …?",
    "can I make an appointment to see the dentist?": "можно записаться на прием к дантисту?",
    "can I make an appointment to see the hygienist?": "можно записаться на прием к гигиенисту?",
    "I'd like a check-up": "я бы хотел провериться",
    "please take a seat": "садитесь, пожалуйста",
    "would you like to come through?": "проходите",
    "when did you last visit the dentist?": "когда вы в последний раз посещали дантиста?",
    "have you had any problems?": "у вас есть какие-то жалобы?",
    "I've got toothache": "у меня зубная боль",
    "one of my fillings has come out": "у меня отошла одна из пломб",
    "I've chipped a tooth": "у меня раскрошился зуб",
    "I'd like a clean and polish, please": "я хотел бы сделать чистку и шлифовку, пожалуйста",
    "can you open your mouth, please?": "откройте рот, пожалуйста",
}