slovar = {
    "how are you?": "как дела?",
    "how's it going?": "как оно? (дружеское)",
    "how are you doing?": "как поживаешь? (дружеское)",
    "how's life?": "как жизнь? (дружеское)",
    "how are things?": "как делишки? (дружеское)",
    "I'm fine, thanks": "прекрасно, спасибо",
    "I'm OK, thanks": "нормально, спасибо",
    "not too bad, thanks": "неплохо, спасибо",
    "alright, thanks": "в порядке, спасибо",
    "not so well": "не особо хорошо",
    "how about you?": "как ты?",
    "and you?": "а ты?",
    "and yourself?": "а сам?",
    "what are you up to?": "чем занимаешься?",
    "what have you been up to?": "чем занимался?",
    "working a lot": "много работал",
    "studying a lot": "много учился",
    "I've been very busy": "я был очень занят",
    "same as usual": "тем же, чем обычно",
    "not much": "ничем особенным",
    "not a lot": "ничем особенным",
    "I've just come back from …": "я только что вернулся из …",
    "I've just come back from Portugal": "я только что вернулся из Португалии",
    "where are you?": "где ты?",
    "I'm …": "я …",
    "I'm at home": "я дома",
    "I'm at work": "я на работе",
    "I'm in town": "я в городе",
    "I'm in the countryside": "я на природе",
    "I'm at the shops": "я в магазине",
    "I'm on a train": "я в поезде",
    "I'm at Peter's": "я у Питера",
    "do you have any plans for the summer?": "у тебя есть планы на лето?",
    "what are you doing for …?": "что ты делаешь на …?",
    "what are you doing for Christmas?": "что ты делаешь на Рождество?",
    "what are you doing for New Year?": "что ты делаешь на Новый год?",
    "what are you doing for Easter?": "что ты делаешь на Пасху?",



}