slovar = {
    "act to": "разыгрывать",
    "add on": "прибавлять",
    "add up": "складывать",
    "answer back": "огрызаться",
    "answer to": "соответствовать",
    "ask after": "справляться о",
    "attend to": "обслуживать",
    "back out": "отступаться",
    "back up": "подстраховывать",
    "bank on": "полагаться на",
    "bear out": "поддерживать",
    "bear up": "держаться",
    "beat down": "хлестать, палить",
    "belt out": "горланить",
    "belt up": "заткнуться",
    "blast off": "взлетать, взмывать",
    "blot out": "заслонять",
    "blow out": "гаснуть",
    "blow over": "проходить",
    "boil down to": "сводиться к",
    "book in": "регистрироваться",
    "bottle up": "держать в себе",
    "box off": "окружать",
    "break down": "отгораживать",
    "break in": "вламываться, вмешиваться",
    "break off": "прерывать, расторгать",
    "break open": "взламывать",
    "break out": "разражаться",
    "break through": "прорываться сквозь",
    "bring about": "вызывать, порождать",
    "bring back": "возрождать",
    "bring down": "снижать",
    "bring forward": "выдвигать",
    "bring in": "вводить",
    "bring off": "заключать",
    "bring out": "выявлять",
    "bring round": "приводить в чувство",
    "brush aside": "отметать",
    "brush past": "проноситься мимо",
    "brush up": "освежать",
    "build on": "пользоваться",
    "build up": "наращивать",
    "bump along": "трястись по",
    "bump into": "наталкиваться на",
    "bundle off": "отсылать",
    "bundle out": "быстро уходить",
    "burst into": "врываться",
    "burst open": "распахиваться",
    "burst out": "разразиться",
    "buy in": "закупать",
    "buy into": "входить в долю",
    "buy off": "подкупать",
    "buy out": "выкупать",
    "buy up": "скупать",
    "buzz off": "отваливать",
    "call at": "останавливаться в",
    "call back": "заходить опять, перезванивать",
    "call for": "призывать к",
    "call off": "отменять",
    "call on": "заходить к",
    "call out": "кричать",
    "carry on": "продолжать",
    "carry out": "кричать",
    "cast aside": "отвергать",
    "catch on": "приживаться",
    "catch up": "нагонять",
    "catch up with": "догнать кого-либо",
    "chance on": "случайно наткнуться на",
    "chase up": "напоминать",
    "chat up": "заигрывать",
    "check in": "регистрироваться",
    "check off": "отмечать",
    "check out": "выписываться",
    "check up": "наводить справки",
    "cheer up": "ободрять",
    "chill out": "кайфовать",
    "chip in": "встревать",
    "clear off": "убираться",
    "climb down": "уступать",
    "close in": "опускаться",
    "close off": "огораживать",
    "come across": "наталкиваться",
    "come along": "продвигаться",
    "come apart": "разваливаться",
    "come by": "доставать",
    "come forward": "вызываться",
    "come in for": "подвергаться",
    "come off": "отрываться",
    "come on": "продвигаться",
    "come round": "приходить в себя",
    "come through": "пережить",
    "come up against": "наталкиваться на",
    "come up with": "придумывать",
    "cool down": "остудить пыл",
    "count on": "рассчитывать на",
    "count up": "подсчитывать",
    "cover up": "прикрывать, покрывать кого-либо",
    "crack down on": "расправляться с",
    "crack up": "лопаться от смеха",
    "cross out": "вычеркивать",
    "cry off": "отказываться",
    "cut off": "отключать",
    "cut out": "отключить",
    "deal in": "торговать",
    "die away": "замирать",
    "die down": "угасать",
    "dig into": "докапываться",
    "do away with": "покончить с",
    "do up": "завязывать, застегивать",
    "do without": "обходиться без",
    "double back": "разворачиваться и идти назад",
    "double up": "сгибаться пополам",
    "draw back": "отпрянуть",
    "draw in": "подъезжать",
    "draw on": "использовать",
    "draw out": "растягивать",
    "draw up": "придвигать",
    "dream up": "выдумывать",
    "dress up": "наряжаться",
    "drink in": "упиваться",
    "drive off": "отбрасывать",
    "drive out": "вытеснять",
    "drop in": "заглядывать к кому-либо",
    "drum up": "призывать",
    "dwell on": "задерживаться на",
    "ease off": "становиться тише, замедляться",
    "eat away": "разъедать",
    "eat out": "есть в ресторане",
    "enter upon": "начинать",
    "explain away": "находить оправдание",
    "fade in": "постепенно увеличивать, усиливать",
    "fade out": "постепенно уменьшать, ослаблять",
    "fall apart": "разваливаться по частям",
    "fall back on": "прибегать к",
    "fall behind": "отставать",
    "fall for": "влюбляться в",
    "fall in with": "соглашаться с",
    "fasten on": "сосредотачиваться на",
    "feel about": "искать на ощупь",
    "fetch up": "оказаться",
    "fiddle with": "вертеть на руках",
    "fight back": "защищаться, сдерживать натиск",
    "fight down": "подавлять",
    "figure out": "вычислять, понимать",
    "fill in": "пломбировать зуб",
    "filter in": "просачиваться",
    "find out": "узнавать, разоблачать",
    "finish up": "доедать, допивать",
    "fish out": "выуживать",
    "fit in": "вписываться",
    "fix up": "устраивать",
    "flick through": "просматривать",
    "float around": "носиться в воздухе",
    "flush out": "спугнуть",
    "follow out": "приводить в исполнение",
    "follow up": "расследовать",
    "fool about": "валять дурака",
    "force back": "отражать натиск",
    "forge ahead": "вырываться вперед",
    "fork out": "выкладывать",
    "frown on": "смотреть с неодобрением",
    "fuss over": "трястись над",
    "gasp out": "выпаливать",
    "get about": "распространяться",
    "get across": "объяснять",
    "get along": "ладить с",
    "get at": "придираться",
    "get away": "уходить",
    "get away with": "избежать наказания",
    "get by": "проходить",
    "get off": "сходить с транспорта",
    "get on": "садиться в транспорт",
    "get on to": "переходить к",
    "get out of": "отделываться от",
    "get over": "преодолевать",
    "get round to": "собираться сделать что-либо",
    "get through": "дозвониться, прорваться",
    "get up": "подниматься, вставать с постели",
    "get up to": "заниматься",
    "give in": "подчиниться",
    "give off": "дымить",
    "give up": "отказываться, сдаваться",
    "go about": "прохаживаться",
    "go ahead": "продвигаться",
    "go back on": "не сдерживать",
    "go for": "добиваться",
    "go in for": "принимать участие",
    "go on": "продолжать",
    "go on at": "приставать к",
    "go through with": "осуществлять",
    "go with": "соответствовать",
    "go without": "оставаться без",
    "grow apart": "отдаляться друг от друга",
    "grow up": "взрослеть",
    "hang about": "слоняться",
    "hang on": "подождать",
    "hang up": "вешать трубку",
    "happen on": "натыкаться на",
    "head for": "направляться к",
    "head off": "отводить",
    "hit on": "отыскивать",
    "hit out at": "набрасываться",
    "hold back": "придерживать",
    "hold on": "держаться, ждать",
    "hold on to": "держаться за",
    "hold out": "протягивать",
    "hold over": "откладывать",
    "hold up": "поднимать, поддерживать",
    "hurry up": "торопить",
    "hush up": "умалчивать",
    "inquire into": "расследовать",
    "iron out": "улаживать",
    "jog along": "медленно продвигаться",
    "jump about": "суетиться",
    "jump at": "ухватываться за",
    "keep away from": "держаться подальше от",
    "keep down": "сдерживать",
    "keep in": "держать дома",
    "keep off": "обходить, избегать",
    "keep out": "не впускать",
    "keep up": "поддерживать",
    "knock about": "околачиваться",
    "knock off": "закругляться",
    "knock out": "оглушать",
    "ladle out": "раздавать направо и налево",
    "land up": "очутиться",
    "launch into": "пускаться в",
    "lay in": "запасать",
    "lay into": "набрасываться на",
    "lay off": "увольнять",
    "lay on": "устраивать",
    "lay out": "раскладывать",
    "lead off": "отходить от",
    "lead on": "водить за нос",
    "leave behind": "забыть что-либо",
    "leave off": "не включать",
    "leave on": "не снимать",
    "leave out": "пропускать, оставлять без внимания",
    "let on": "проговариваться",
    "let out": "выпускать",
    "let up": "переставать",
    "lie about": "валяться",
    "lie back": "откидываться",
    "lie up": "скрываться",
    "live down": "заглаживать",
    "live up to": "оправдывать, доходить до какого-либо уровня",
    "lock away": "заключать под стражу",
    "log in": "входить в систему",
    "log into": "входить в",
    "log off": "выходить из системы",
    "look after": "заботиться о",
    "look around": "осматриваться",
    "look down on": "смотреть свысока на",
    "look for": "искать",
    "look forward to": "ждать чего-либо с нетерпением",
    "look into": "расследовать",
    "look on": "наблюдать",
    "look out for": "остерегаться",
    "look through": "просматривать",
    "look up": "находить информацию",
    "look up to": "почитать",
    "make for": "направляться к",
    "make off": "скрываться",
    "make out": "различать",
    "make up": "составлять, делать макияж",
    "make up for": "восполнять",
    "mark down": "снижать, уценивать",
    "mark off": "отмечать",
    "mark out": "размечать, выделять",
    "mark up": "повышать, добавлять стоимость",
    "measure up": "оправдывать",
    "mix up": "путать",
    "mount up": "накапливаться",
    "muddle along": "справляться кое-как",
    "muddle through": "выкарабкиваться",
    "nod off": "задремать",
    "pack off": "отправлять",
    "pass away": "на",
    "pass by": "проходить, проезжать мимо",
    "pass out": "терять сознание",
    "pass up": "упускать",
    "patch up": "улаживать",
    "pick at": "ковырять",
    "pick off": "методично сбивать, отстреливать",
    "pick on": "придираться к",
    "pick out": "разглядеть",
    "play down": "не заострять внимание на",
    "play up": "барахлить",
    "plug in": "включать в розетку",
    "polish off": "покончить с",
    "pop in": "заглядывать, заскакивать к кому-нибудь",
    "pop out": "выскакивать",
    "pop up": "вылезать",
    "pour into": "устремляться в",
    "press ahead": "приступать к делу",
    "press on": "продолжать",
    "pull about": "трепать",
    "pull up": "подтягивать",
    "push in": "влезать",
    "push off": "убираться",
    "push on": "двигаться вперед",
    "push over": "опрокидывать",
    "push up": "повышать",
    "put across": "объяснять",
    "put by": "откладывать",
    "put forth": "объявлять",
    "put forward": "выдвигать, переводить вперед",
    "put in for": "подавать заявление на",
    "put on": "надевать",
    "put out": "тушить, выключать",
    "put through": "соединять, выполнять соединение",
    "put up with": "терпеть, мириться с",
    "reach out": "протягивать",
    "reflect on": "бросать тень на",
    "root about": "рыться",
    "root for": "болеть за",
    "root out": "откопать",
    "round off": "завершать",
    "round up": "округлять",
    "rule out": "исключать",
    "run across": "натыкаться на",
    "run down": "сокращать, сбивать",
    "run into": "сталкиваться с",
    "run off": "сбегать, убегать",
    "run out": "истекать, заканчиваться",
    "run over": "задавить",
    "rush through": "делать в спешке",
    "score out": "вычеркивать",
    "scrape together": "наскребать",
    "screw up": "комкать, портачить",
    "see about": "заниматься",
    "see off": "провожать",
    "see through": "доводить до конца",
    "see to": "позаботиться о",
    "seize up": "глохнуть",
    "send for": "заказывать",
    "send in": "подавать заявление о",
    "send up": "запускать",
    "serve out": "раскладывать",
    "set about": "приступать к",
    "set back": "задерживать",
    "set off": "отправляться",
    "set up": "учреждать",
    "shoot down": "сбивать",
    "shoot in": "стремглав вбегать",
    "shoot out": "стремглав выбегать",
    "shoot up": "подскакивать",
    "shop around": "прицениваться",
    "shout down": "заглушать криками",
    "show in": "проводить внутрь",
    "show off": "отмахиваться от",
    "show out": "провожать к выходу",
    "show up": "виднеться появляться",
    "shrug off": "отмахиваться от",
    "shut off": "отключать",
    "shut out": "не пропускать",
    "shut up": "заткнуться",
    "sign away": "передавать",
    "sign in": "регистрироваться",
    "sign off": "заканчивать",
    "sign out": "выписываться",
    "sign up": "наниматься, подписаться",
    "skate around": "обходить",
    "skate over": "игнорировать",
    "sleep around": "спать с кем попало",
    "sleep in": "просыпать, отсыпаться",
    "slip up": "ошибаться",
    "smooth over": "улаживать дела",
    "sound off": "высказаться о",
    "square up": "поквитаться с кем-либо",
    "stamp out": "затаптывать",
    "stand by": "быть на готове",
    "stand down": "уступать место",
    "stand for": "обозначать, представлять",
    "stand in for": "замещать",
    "stand up for": "отстаивать",
    "stand up to": "выдерживать",
    "stem from": "происходить от",
    "stick up for": "заступаться за",
    "stir up": "вызывать",
    "stop by": "заходить",
    "stop up": "заделывать",
    "strike out": "вычеркивать",
    "take after": "пойти в кого-либо",
    "take down": "сносить",
    "take in": "включать в себя",
    "take off": "взлетать",
    "take on": "сражаться с",
    "take over": "принимать руководство",
    "take to": "пристраститься к",
    "take up": "заняться, подхватить",
    "tear along": "нестись",
    "tell off": "отчитывать кого-либо",
    "tell on": "жаловаться на",
    "think up": "придумывать",
    "throw up": "тошнить со рвотой",
    "touch on": "затрагивать",
    "touch up": "подкрашивать",
    "try on": "мерить, примерить",
    "tuck away": "припрятывать",
    "tuck in": "заправлять, запихивать",
    "tuck up": "укрывать",
    "turn down": "отклонять",
    "turn in": "сворачивать",
    "turn off": "выключать",
    "turn on": "включать",
    "turn up": "объявляться",
    "wait on": "обслуживать",
    "walk out on": "бросать",
    "wash up": "мыть посуду",
    "wear off": "постепенно проходить",
    "wear on": "тянуться",
    "work out": "удаваться, срабатывать",
    "write off": "списывать, аннулировать",
    "write up": "приводить в порядок",
    "From rags to riches": "из грязи в князи.",
    "Money talks": "с деньгами можно добиться всего.",
    "Money to burn / Rolling in money": "денег куры не клюют.",
    "Born with a silver spoon in her mouth": "родиться в богатой семье.",
    "More money than sense": "бросать деньги на ветер.",
    "Gravy train": "легкие деньги.",
    "Cost a pretty penny": "стоить уйму денег.",
    "Worth every penny": "cтоить своих денег; стоить каждой потраченной копейки.",
    "To go Dutch": "платить каждому за себя.",
    "Hit the jackpot": "сорвать куш.",
    "Bet your bottom dollar": "гарантировать что-либо.",
    "Highway robbery": "грабеж средь бела дня.",
    "Be flush with money": "купаться в роскоши.",
    "Buy (something) for a song": "купить что-то очень дешево.",
    "To make ends meet / To live from hand to mouth": "cводить концы с концами.",
    "Flat broke": "на мели; без гроша.",
    "On the breadline": "за чертой бедности.",
    "Scrape together": "поскрести по сусекам; собрать все деньги, которые есть.",
    "Beyond one’s means": "(жить) не по средствам.",
    "As phony as a three-dollar bill": "такой же фальшивый, как трехдолларовая купюра.",
    "Golden handshake": "денежная компенсация для увольняемого или уходящего на пенсию сотрудника.",
    "Let the grass grow under one’s feet": "сидеть сложа руки; терять время попусту.",
    "Around the clock": "круглосуточно.",
    "In the interim": "тем временем; в промежутке.",
    "On the spur of the moment": "спонтанно; необдуманно; в порыве.",
    "Have the time of one’s life": "чудесно провести время.",
    "Against the clock": "торопиться сделать что-либо до определенного времени.",
    "Behind the times": "старомодный.",
    "In broad daylight": "публично; средь бела дня.",
    "Museum piece": "что-то старомодное; музейный экспонат.",
    "Give someone a hard time": "отчитывать; портить кому-либо жизнь.",
    "All in good time": "всему свое время.",
    "The time is ripe": "время пришло.",
    "Beat the clock": "успеть закончить что-то до назначенного времени.",
    "To serve time / To do time": "сидеть в тюрьме; отбывать срок.",
    "Be ahead of time": "опережать время.",
    "Take your time": "не спеши; не торопись",
    "Don’t judge the book by its cover": "не суди книгу по обложке.",
    "A leopard can’t change its spots": "горбатого могила исправит.",
    "Worrywart": "тревожный, мнительный человек.",
    "Bag of wind": "болтун; хвастун.",
    "Armchair critic": "диванный критик; человек, не упускающий возможности покритиковать других.",
    "Charm the birds out of the trees": "добиваться своего обаянием и харизмой; умасливать.",
    "The life and soul of the party": "душа компании.",
    "Would not say boo to a goose": "мухи не обидит; застенчивый; скромный.",
    "Know-it-all / Wise guy": "всезнайка.",
    "Bark is worse than bite": "лает, да не кусает; грозен лишь на словах.",
    "Stickler for the rules": "человек, строго соблюдающий правила; педант.",
    "Go-getter": "предприимчивый; энергичный; легкий на подъем.",
    "Not have a nasty/ mean/ jealous bone in their body": "иметь золотой характер.",
    "The salt of the earth": "лучшие, достойнейшие люди.",
    "Down-to-earth": "реалистичный; приземленный.",
    "Social butterfly": "общительный; коммуникабельный; дружелюбный.",
    "Goody two shoes": "паинька; святоша; правильный до тошноты.",
    "Set in one’s way": "упрямый; уверенный в своей правоте.",
    "Wet blanket / Spoilsport / Killjoy": "тот, кто портит удовольствие другим.",
    "Man of his word / Woman of her word": "человек слова.",
    "Mover and shaker": "первое лицо компании; один из сильных мира сего.",
    "Behind the times / A fuddy-duddy / To stick in the mud": "человек, отставший от времени; консерватор, критикующий все новое.",
    "Down at heel": "бедно одетый; в стоптанной обуви.",
    "Five o’clock shadow": "щетина; небритость.",
    "Look a sight": "представлять собой жалкое зрелище.",
    "As ugly as sin": "страшный как смертный грех; крайне непривлекательный.",
    "Look like a million dollars": "прекрасно выглядеть.",
    "Mutton dressed as lamb": "молодящаяся дама, одетая не по возрасту.",
    "Vertically challenged": "низкого роста.",
    "Thin on the top": "лысеющий.",
    "On cloud nine / Walk on air": "на седьмом небе от счастья; на верху блаженства.",
    "Old flame": "старая любовь; бывший возлюбленный.",
    "Jump for joy": "прыгать от радости.",
    "Thrilled to bits": "в восторге; довольный как слон.",
    "On pins and needles": "нервничать; быть как на иголках.",
    "Bundle of nerves": "взволнованный человек; пучок нервов.",
    "To be in two minds": "сомневаться.",
    "Сut to the quick": "задеть за живое; обидеть.",
    "No hard feelings": "без обид.",
    "Swallow your pride": "поступиться самолюбием; проглотить обиду.",
    "Go spare": "выйти из себя; вспылить.",
    "To be hopping mad": "сильно разозлиться; быть в ярости.",
    "Get a grip on yourself": "взять себя в руки.",
    "To be on the horns of a dilemma": "быть между двух огней, в трудном положении.",
    "To be in one’s element": "быть в своей стихии, в своей тарелке.",
    "Couldn’t care less": "быть безразличным к чему-либо.",
    "Storm in a teacup": "буря в стакане воды; много шума из ничего.",
    "Go to pieces": "утратить контроль над собой; расклеиться; чувствовать себя разбитым.",
    "Look on the bright side": "оптимистично смотреть на вещи.",
    "That’s that": "такие дела; ничего не поделаешь.",
    "Tie the knot": "пожениться.",
    "To eat somebody for breakfast": "легко побеждать других.",
    "Ahead of the pack": "быть впереди всех.",
    "Shake on something": "договориться о чем-то; пожать руки в знак соглашения о чем-либо.",
    "Burn the candle at both ends": "гореть на работе; трудиться без отдыха.",
    "To connect the dots": "связать все факты в единое целое.",
    "Blow smoke": "напускать туману; пудрить мозги; приукрашивать.",
    "Rain on (someone’s) parade": "расстраивать чьи-то планы.",
    "Eat, sleep and breath something": "быть чем-то страстно увлеченным; направлять на что-то всю свою энергию.",
    "To go the extra mile": "делать больше, чем от тебя ожидают; выкладываться на 200 %.",
    "To go halfers": "делить счет в ресторане пополам.",
    "To cherry pick": "снимать сливки; выбирать самые лакомые кусочки; отбирать лучшее.",
    "Tar someone with the same brush": "стричь всех под одну гребенку.",
    "Steal the show / Steal the spotlight": "затмить всех; перетянуть внимание на себя.",
    "To cut to the chase": "переходить к сути, к делу.",
    "To test the waters": "прощупать почву; закинуть удочку; попробовать.",
    "A point of no return": "точка невозврата; момент, когда назад уже не вернуться.",
    "To be fixed for a life": "хорошо устроиться в жизни.",
    "Sell someone out": "предать, «сдать» кого-то.",
    "A friend in need is a friend indeed": "друг познается в беде.",
    "You can’t take it with you": "с собой после смерти ничего не заберешь; живи сейчас, не откладывай на потом.",
    "To keep the pot boiling": "зарабатывать, энергично занимаясь своим делом.",
    "To run out of steam": "выдохнуться; измотаться.",
    "Huff and puff": "тяжело дышать; пыхтеть.",
    "To cause a stir": "вызывать ажиотаж, переполох.",
    "It’s not over till the fat lady sings": "еще не вечер; еще есть шанс все изменить.",
    "That’s (It’s) a wrap": "дело успешно завершено.",
    "Come again": "повторите, пожалуйста.",
    "Bull in a china shop": "слон в посудной лавке.",
    "Cock-and-bull story": "неправдоподобная история; небылица.",
    "Dark horse": "темная лошадка.",
    "Beat a dead horse": "зря тратить силы; стараться впустую.",
    "Horse around": "валять дурака; дурачиться.",
    "Straight from the horse’s mouth": "из первых уст.",
    "Dead duck": "гиблое дело.",
    "Like water off a duck’s back": "как с гуся вода.",
    "Cook someone’s goose": "погубить (кого-либо); угробить.",
    "Ugly duckling": "гадкий утенок.",
    "As a duck takes to water": "как рыба в воде.",
    "Get ducks in a row": "навести порядок; разобраться в делах.",
    "Cat’s meow": "милашка; красавица; милая вещица.",
    "When pigs fly": "когда рак на горе свистнет (то есть никогда).",
    "Buy a pig in a poke": "купить кота в мешке.",
    "To have ants in one’s pants": "быть неугомонным, беспокойным; не мочь усидеть на месте.",
    "As happy as a lark": "очень счастливый, веселый.",
    "To have no dog in this fight": "не быть заинтересованным в ситуации; не волноваться о результате.",
    "Top dog": "вожак; альфа-самец; босс.",
    "Dog-eat-dog": "ситуация, где каждый сам за себя.",
    "Dog in the manger": "собака на сене; ни себе ни людям.",
    "In the doghouse": "(быть) в немилости.",
    "As clean as a hound’s tooth": "очень чистый.",
    "Little bird told me": "сорока на хвосте принесла; мне стало известно.",
    "Chicken out": "трýсить.",
    "To jump the shark": "потерять былую популярность.",
    "Kangaroo court": "несправедливый суд; суд не по закону.",
    "For donkey’s years": "с незапамятных времен; целую вечность.",
    "Barrel of monkeys": "что-то смешное, забавное.",
    "Monkey see, monkey do": "имитация чего-либо без понимания сути.",
    "Monkey business": "несерьезное поведение; озорство; обман; жульничество.",
    "Smell a rat": "чуять недоброе.",
    "To have rats in the attic": "не все дома; тараканы в голове.",
    "Calm as a toad in the sun": "очень спокойный и довольный.",
    "Сast pearls before swine": "метать бисер перед свиньями.",
    "A fine kettle of fish": "затруднительное, неловкое положение.",
    "A different kettle of fish": "совсем другое дело; не то же самое.",
    "Cold fish": "бесчувственный, холодный человек.",
    "Conceited as a barber’s cat": "самодовольный.",
    "Cry wolf": "поднимать ложную тревогу.",
    "Poor as a church mouse": "беден как церковная мышь.",
    "Сash cow": "источник денег; дойная корова.",
    "Eager beaver": "трудяга; усердный работник.",
    "Elephant in the room": "простая истина; то, что всем очевидно.",
    "Cat nap": "короткий сон днем.",
    "Cat gets one’s tongue": "язык проглотить.",
    "Like a cat on a hot tin roof": "не находить себе места; нервничать.",
    "Serve as a guinea pig": "быть подопытным кроликом.",
    "Grab a tiger by the tail": "взяться за дело, которое оказалось неожиданно сложным, но от которого нельзя отказаться.",
    "Have a cake and eat it too": "слишком многого хотеть; желать двух несовместимых вещей сразу.",
    "A piece of cake": "пара пустяков; проще пареной репы.",
    "Sell like hot cakes": "разлетаться как горячие пирожки.",
    "Eat humble pie": "сносить оскорбления; терпеть унижение.",
    "An apple-pie order": "идеальный порядок.",
    "Eat one’s words": "взять свои слова назад.",
    "As warm as toast": "теплый и уютный.",
    "Hard nut to crack": "крепкий орешек; трудный человек; сложная задача.",
    "In a nutshell": "вкратце; в двух словах.",
    "To work for peanuts": "работать за гроши.",
    "Neither fish nor fowl": "ни рыба ни мясо; ни то ни се.",
    "Not my cup of tea": "мне это не подходит, не нравится.",
    "Сouch potato": "лентяй; любитель полежать на диване; «овощ».",
    "Hot potato": "актуальная тема.",
    "As cheap as chips": "очень дешево.",
    "A bad egg / A bad apple": "плохой человек; мошенник; бездельник; негодяй.",
    "A good egg": "парень что надо.",
    "Nest egg": "деньги на черный день; заначка.",
    "Egghead": "умник.",
    "Have egg on one’s face": "выглядеть глупо; попасться на чем-то постыдном.",
    "Beef something up": "усилить, увеличить мощность.",
    "Bread and butter": "средства к существованию.",
    "Butter somebody up": "льстить; умасливать.",
    "Bread-and-butter letter": "благодарственное письмо.",
    "To bring home the bacon": "хорошо зарабатывать; обеспечивать семью.",
    "Save one’s bacon": "спасать свою шкуру.",
    "Big cheese": "влиятельный человек; лидер.",
    "Tough cookie": "крепкий орешек; сильный человек.",
    "Top banana": "важная персона; босс.",
    "Go bananas": "быть вне себя от радости; спятить; сойти с ума.",
    "As cool as a cucumber": "хладнокровный.",
    "Full of beans": "быть оживленным, в приподнятом настроении.",
    "As slow as molasses": "очень медленный.",
    "Сhew the fat": "болтать; чесать языком.",
    "Take something with a pinch of salt": "относиться к чему-либо с сомнением, недоверием.",
    "Cry over spilt milk": "слезами горю не поможешь; прошлого не вернешь.",
    "Everything but the kitchen sink": "все, что только можно; вагон и маленькая тележка.",
    "An arm and a leg": "непомерно высокая цена; безумные деньги.",
    "Not have a leg to stand on": "не иметь поддержки; не иметь шанса доказать что-либо.",
    "Old hand": "тертый калач.",
    "Hand in glove": "в тесной связи; заодно.",
    "Left-handed compliment": "сомнительный, двусмысленный комплимент.",
    "Come away empty-handed": "уйти ни с чем; ничего не добиться.",
    "To get the upper hand (on someone)": "получить преимущество; иметь превосходство над кем-либо.",
    "Keep at arm’s length": "держать дистанцию; держать на почтительном расстоянии.",
    "To have your head screwed on": "иметь голову на плечах.",
    "Head over heels": "по уши влюбленный.",
    "Head in the clouds": "наивный мечтатель; человек не от мира сего.",
    "Hide one’s head in the sand": "прятать голову в песок; игнорировать ситуацию.",
    "Beat one’s head against the wall": "биться головой о стену; вести бесполезную борьбу.",
    "Bite someone’s head off": "огрызаться; хамить.",
    "Able to (do something) standing on one’s head": "уметь делать что-то легко и быстро.",
    "Bonehead": "глупый; тупой.",
    "To have a chip on one’s shoulder": "носить в себе груз обид; обвинять других в своих бедах.",
    "Busybody": "тот, кто сует нос в чужие дела.",
    "Over my dead body": "только через мой труп.",
    "All mouth and no trousers": "пустозвон; человек, который обещает, но ничего не делает.",
    "To foam at the mouth": "быть в ярости; кипеть от злости.",
    "Bite one’s tongue": "прикусить язык.",
    "Don’t lift a finger": "ленивый.",
    "Face only a mother could love / Face that would stop a clock": "уродливое лицо.",
    "A face like thunder": "мрачнее тучи.",
    "Fall flat on one’s face": "провалиться; потерпеть неудачу.",
    "Not a hair out of place": "волосок к волоску; безупречный вид.",
    "Bad hair day": "неудачный день, когда все идет не так, как надо.",
    "Hair-raising": "страшный; жуткий.",
    "To the backbone": "до мозга костей.",
    "All skin and bone": "очень худой; кожа да кости.",
    "Jump out of skin": "вздрогнуть, подпрыгнуть от неожиданности; быть вне себя (от радости, испуга).",
    "Get a slap on the wrist": "понести мягкое наказание; отделаться легким испугом.",
    "Blood runs cold": "кровь стынет в жилах (от ужаса).",
    "Bad blood (between people)": "неприязнь; напряженные отношения.",
    "Eat one’s heart out": "умирать от зависти; изводить себя переживаниями.",
    "To put your heart (and soul) into something": "всеми силами; полностью отдаваясь, вкладывая всю душу.",
    "Wear one’s heart on one’s sleeve": "не скрывать своих чувств; выставлять чувства напоказ.",
    "Have a lump in one’s throat": "почувствовать ком в горле (от волнения).",
    "Count noses": "подсчитать количество людей.",
    "Have one’s nose in (something)": "совать нос в чужие дела.",
    "To give someone the stink eye": "посмотреть на кого-то неодобрительно; наградить ледяным вглядом.",
    "One’s eyes are bigger than one’s stomach": "быть жадным (в еде).",
    "Eyeball-to-eyeball": "лицом к лицу; с глазу на глаз.",
    "With the naked eye": "невооруженным глазом.",
    "In the blink of an eye": "в мгновение ока.",
    "Be all eyes (and ears)": "внимательно смотреть и слушать.",
    "Bend someone’s ear": "вести с кем-то нудный разговор.",
    "Plain as the nose on one’s face": "очевидный.",
    "Break one’s back/ neck (to do something)": "тяжело работать; делать все возможное.",
    "Breathe down someone’s neck": "преследовать; стоять над душой у кого-то.",
    "Hate (someone’s) guts": "ненавидеть кого-то.",
    "Have the ball at one’s feet": "быть хозяином положения.",
    "To be not just a pretty face": "быть не только красивым, но и умным.",
    "All thumbs": "неловкий; неуклюжий.",
    "Button one’s lip": "держать рот на замке.",
    "A no-brainer": "очевидный выбор; ежу понятно.",
    "A feather in one’s cap": "достижение; предмет особой гордости.",
    "Birthday suit": "голый; в чем мать родила.",
    "Comfortable as an old shoe": "очень удобный.",
    "Deep pockets": "богач.",
    "Dressed to kill / Dressed to the nines / Dressed to the teeth": "быть одетым очень модно, стильно, элегантно.",
    "Have (something) up one’s sleeve": "иметь секретный план или идею.",
    "Hit below the belt": "ударить ниже пояса; нечестно поступить.",
    "Hot under the collar": "рассерженный; возмущенный.",
    "I’ll eat my hat": "даю голову на отсечение.",
    "Walk a mile in one’s shoes": "поставить себя на место другого; побыть в чьей-то шкуре.",
    "Keep one’s shirt on": "сохранять спокойствие.",
    "Lose one’s shirt": "потратить, спустить почти все деньги.",
    "Laugh up one’s sleeve": "посмеиваться втихомолку, в кулак, исподтишка.",
    "Money burning a hole in your pocket": "деньги жгут карман, не терпится их потратить.",
    "Quake in one’s boots": "трястись от страха; дрожать как осиновый лист.",
    "To be tied to one’s wife’s apron-string": "быть под каблуком у жены.",
    "If the shoe fits, wear it": "если критическое замечание справедливо по отношению к вам, следует принять его во внимание.",
    "Feel blue": "грустить; печалиться.",
    "To cry the blues": "прибедняться.",
    "Blue devils": "меланхолия; тоска.",
    "Talk until one is blue in the face": "говорить до посинения, до изнеможения.",
    "A bolt out of/ from the blue": "неожиданно; как гром среди ясного неба.",
    "Black eye": "подбитый глаз.",
    "Black sheep": "паршивая овца; белая ворона.",
    "As black as a stack of black cats": "очень черный.",
    "Blue-ribbon": "лучший; престижный; тщательно отобранный.",
    "Burn with a low blue flame": "испытывать сильный гнев, не выражая его явно.",
    "Do something up brown": "делать что-либо хорошо и тщательно.",
    "Green winter": "бесснежная, мягкая зима.",
    "Green with envy": "позеленеть от зависти.",
    "Give the green light": "разрешать.",
    "Green-eyed monster": "ревность.",
    "To have a green thumb": "иметь талант к садоводству.",
    "Red herring": "ложная информация; отвлекающий маневр.",
    "Red tape": "волокита; бюрократия.",
    "In the pink (of something)": "в хорошей форме; в прекрасном состоянии; в порядке.",
    "Tickled pink": "очень довольный.",
    "To be green about the gills": "выглядеть бледным, больным.",
    "To catch red-handed": "поймать с поличным; застать врасплох.",
    "To be in the red": "быть в долгах, в убытке.",
    "To roll out the red carpet": "оказать радушный прием; тепло встретить гостя.",
    "To see red": "выйти из себя; прийти в ярость.",
    "Not to be worth a red cent": "гроша ломаного не стоить.",
    "To show the white feather": "проявить малодушие; струсить.",
    "White fury": "неистовство; бешенство; ярость.",
    "White lie": "невинная ложь; ложь во спасение.",
    "Lily-white reputation": "безупречная репутация.",
    "To bleed white": "обобрать до нитки.",
    "White night": "бессонная ночь.",
    "To have a yellow streak": "бояться; трусить.",
    "A purple patch": "полоса везения, удачи.",
    "Chase rainbows": "пытаться достичь недостижимого; преследовать призрачные цели.",
    "o do the cooking": "(Готовить)",
    "To do the housework": "(Выполнять работу по дому)",
    "To do the shopping": "(Делать покупки)",
    "To do the washing up": "(Мыть посуду)",
    "To do your best": "(Постараться)",
    "To do your hair": "(Причесаться)",
    "To have a good time": "(Хорошо проводить время, чаще используется, как пожелание)",
    "To have a bath": "(Принимать ванну)",
    "To have a drink": "(Выпить)",
    "To have a haircut": "(Подстричься)",
    "To have a holiday": "(Иметь отпуск / каникулы)",
    "To have a problem": "(Иметь проблему, столкнуться с проблемой)",
    "To have a relationship / to be in relationship": "(Быть в отношениях)",
    "To have lunch": "(Обедать, иметь ланч)",
    "To have sympathy": "(Симпатизировать)",
    "To break the law": "(Нарушить закон)",
    "To break a promise": "(Нарушить обещание)",
    "To break a record": "(Побить рекорд)",
    "To break someone’s heart": "(Разбить чье-то сердце)",
    "To break the ice": "(Идиома: растопить лед, сделать первый шаг, смягчить ситуацию, положить начало)",
    "To break the news to someone": "(Сообщить кому-то важные новости)",
    "To break the rules": "(Нарушать правила)",
    "To take a break": "(Сделать перерыв)",
    "To take a chance": "(Рискнуть, использовать шанс)",
    "To take a look": "(Взглянуть)",
    "To take a rest": "(Отдохнуть)",
    "To take a seat": "(Присесть)",
    "To take a taxi": "(Взять такси)",
    "To take an exam": "(Сдавать экзамен)",
    "To take notes": "(Делать заметки)",
    "To take someone’s place": "(Занять чье-то место)",
    "To make a difference": "(Иметь разницу, иметь значение, существенно менять дело)",
    "To make a mess": "(Устраивать беспорядок)",
    "To make a mistake": "(Сделать ошибку)",
    "To make a noise": "(Шуметь)",
    "o make an effort": "(Сделать усилие)",
    "To make money": "(Зарабатывать)",
    "To make progress": "(Прогрессировать)",
    "To make room": "(Предоставить место для кого-то)",
    "To make trouble": "(Доставлять проблемы)",
    "To catch the bus": "(Поймать автобус)",
    "To catch a ball": "(Поймать мяч)",
    "To catch a cold": "(Простудиться)",
    "To catch a thief": "(Поймать вора)",
    "To catch fire": "(Загореться)",
    "To catch sight of": "(Увидеть, заметить)",
    "To catch someone’s attention": "(Поймать чье-то внимание)",
    "To catch someone’s eye": "(Получить чье-то внимание)",
    "To catch the flu": "(Заболеть гриппом)",
    "To pay respect": "(Выражать уважение)",
    "To pay a fine": "(Платить штраф)",
    "To pay attention": "(Обращать внимание)",
    "To pay by credit card": "(Платить кредитной картой)",
    "To pay cash": "(Платить наличными)",
    "To pay interest": "(Выплачивать проценты)",
    "To pay someone a visit": "(Навестить кого-то)",
    "To pay the bill": "(Оплатить счет)",
    "To pay the price": "(Платить цену)",
    "To keep the change": "(Оставить сдачу себе, как обращение: сдачи не надо)",
    "To keep a promise": "(Сдержать обещание)",
    "To keep a secret": "(Сохранить в секрете)",
    "To keep an appointment": "(Приходить в назначенное место)",
    "To keep calm": "(Сохранять спокойствие)",
    "To keep in touch": "(Оставаться на связи)",
    "To keep quiet": "(Соблюдать тишину)",
    "To keep someone’s place": "(Занять, придержать кому-то место)",
    "To save electricity": "(Экономить электричество)",
    "To save energy": "(Экономить, сохранить энергию)",
    "To save money": "(Экономить деньги)",
    "To save a seat for someone": "(Занять, сохранить кому-то место)",
    "To save someone’s life": "(Сохранить чью-то жизнь)",
    "To save something to a disk": "(Сохранить что-то на диск)",
    "To save time": "(Экономить время)",
    "To go bald": "(Лысеть)",
    "To go abroad": "(Поехать за границу)",
    "To go astray": "(Сбиваться с пути)",
    "To go bad": "(Портиться)",
    "To go bankrupt": "(Обанкротиться)",
    "To go blind": "(Слепнуть)",
    "To go crazy": "(Сходить с ума)",
    "To go fishing": "(Отправляться на рыбалку)",
    "To go mad": "(Свихнуться)",
    "To go missing": "(Без вести пропасть)",
    "To go online": "(Выйти в онлайн)",
    "To go out of business": "(Обанкротиться)",
    "To go overseas": "(Ехать за море, ехать за границу)",
    "To go quiet": "(Притихнуть, затихнуть)",
    "To go sailing": "(Ходить под парусом)",
    "To go to war": "(Идти воевать)",
    "To come under attack": "(Попадать под обстрел, под нападение)",
    "To come close": "(Подойти ближе)",
    "To come direct": "(Проходить прямо)",
    "Come early": "(Приходить пораньше)",
    "To come first": "(Приходить первым)",
    "To come into view": "(Внезапно появиться, открыться взгляду)",
    "To come last": "(Приходить в последний раз)",
    "To come late": "(Опаздывать)",
    "To come on time": "(Приходить вовремя)",
    "To come prepared": "(Приходить подготовленным)",
    "To come right back": "(Приходить обратно, возвращаться)",
    "To come to a decision": "(Прийти к решению)",
    "To come to an agreement": "(Прийти к соглашению)",
    "To come to an end": "(Подойти к концу)",
    "To come to a standstill": "(Оказаться в тупике)",
    "To get the sack": "(Быть уволенным)",
    "To get a life": "(Идиома: адресуется скучному человеку, когда хотят, чтобы он делал более интересные вещи)",
    "To get a job": "(Получить работу)",
    "To get a shock": "(Быть шокированным)",
    "To get angry": "(Разозлиться)",
    "To get divorced": "(Развестись)",
    "To get drunk": "(Напиться)",
    "To get frightened": "(Испугаться)",
    "To get home": "(Добраться до дома)",
    "To get lost": "(Потеряться, заблудиться. Если обращено к человеку, то имеется в виду: Отстань, потеряйся, уйди)",
    "To get married": "(Пожениться)",
    "To get permission": "(Получить разрешение)",
    "To get ready": "(Приготовиться)",
    "To get started": "(Начать)",
    "To get the impression": "(Получить впечатление)",
    "To get upset": "(Расстроиться)",
    "To get wet": "(Промокнуть)",
    "To get worried": "(Волноваться)",
    "Bang on time": "(Как раз вовремя)",
    "Dead on time": "(Похоже на предыдущее: вовремя, с точностью до секунды)",
    "Free time": "(Свободное время)",
    "Great deal of time": "(Много времени)",
    "To make time for": "(Уделить время для…)",
    "Right on time": "(Как раз вовремя)",
    "Run out of time": "(Истратить все время, не успевать)",
    "Time goes by": "(Время идет, проходит, течет)",
    "Time passes": "(Время проходит)",
    "Waste time": "(Тратить время)",
    "a ball of string": "(Клубок ниток)",
    "a bar of chocolate": "(Плитка шоколада)",
    "a bottle of water": "(Бутылка воды)",
    "a bunch of carrots": "(Пучок моркови)",
    "a cube of sugar": "(Кубик сахара)",
    "a pack of cards": "(Колода карт)",
    "a pad of paper": "(Блокнот)",
    "A blessing in disguise": "Хорошее дело, казавшееся плохим на первый взгляд 	как часть предложения",
    "A dime a dozen": "Что-то простое, распространённое 	как часть предложения",
    "Beat around the bush": "Избегать говорить прямо, как правило, потому что это доставляет неудобства 	как часть предложения",
    "Better late than never": "Лучше поздно, чем никогда 	как часть",
    "Bite the bullet": "Преодолеть что-то, потому что это неизбежно 	как часть предложения",
    "Break a leg": "Удачи! 	самостоятельно",
    "Call it a day": "Прекратить работу над чем-либо 	как часть предложения",
    "Cut somebody some slack": "Не быть слишком критичным 	как часть предложения",
    "Cutting corners": "Делать что-либо неважно с целью сэкономить время или деньги ( 	как часть предложения",
    "Easy does it": "Сбавить темп, делать что-либо медленнее 	самостоятельно",
    "Get out of hand": "Выйти из-под контроля, потерять управление 	как часть предложения",
    "Get something out of your system": "Сделать давно задуманное, чтобы двигаться дальше 	как часть предложения",
    "Get your act together": "Работай лучше или оставь дело 	самостоятельно",
    "Give someone the benefit of the doubt": "Верь тому, что кто-то говорить 	как часть предложения",
    "Go back to the drawing board": "Начать сначала 	как часть предложения",
    "Hang in there": "Не сдавайся 	самостоятельно",
    "Hit the sack": "Отправиться спать 	как часть предложения",
    "It's not rocket science": "Это несложно 	самостоятельно",
    "Let someone off the hook": "Перестать делать кого-либо ответственным за что-либо 	как часть предложения",
    "Make a long story short": "Рассказывать кратко 	как часть предложения",
    "Miss the boat": "Слишком поздно 	как часть предложения",
    "No pain, no gain": "Необходимо работать, чтобы получить желаемое 	самостоятельно",
    "On the ball": "Выполнять свою работу хорошо 	как часть предложения",
    "Pull someone's leg": "Шутить с кем-то 	как часть предложения",
    "Pull yourself together": "Успокойся 	самостоятельно",
    "So far so good": "Пока что все идёт хорошо 	самостоятельно",
    "Speak of the devil": "Объявился тот, о ком мы говорили. 	самостоятельно",
    "That's the last straw": "Моё терпение закончилось 	самостоятельно",
    "The best of both worlds": "Идеальная ситуация 	как часть предложения",
    "Time flies when you're having fun": "Когда весело, время летит незаметно 	самостоятельно",
    "To get bent out of shape": "Расстроиться 	как часть предложения",
    "To make matters worse": "Усугубить проблему 	как часть предложения",
    "Under the weather": "Нездоровый 	как часть предложения",
    "We'll cross that bridge when we come to it": "Давай не будем прямо сейчас говорить об этой проблеме 	самостоятельно",
    "Wrap your head around something": "Понять что-то сложное 	как часть предложения",
    "You can say that again": "Это правда, согласен 	самостоятельно",
    "Your guess is as good as mine": "Понятия не имею 	самостоятельно",
    "A bird in the hand is worth two in the bush": "Синица в руках лучше, чем журавль в небе 	самостоятельно",
    "A penny for your thoughts": "Расскажи, о чём ты думаешь 	самостоятельно",
    "A penny saved is a penny earned": "Деньги, которые ты сохранишь сегодня, можешь потратить позже 	самостоятельно",
    "A perfect storm": "Худшая из возможных ситуаций 	как часть предложения",
    "A picture is worth 1000 words": "Лучше показать, чем рассказать 	самостоятельно",
    "Actions speak louder than words": "Верьте делам людей, а не словам 	самостоятельно",
    "Add insult to injury": "Усугубить положение 	как часть предложения",
    "Barking up the wrong tree": "Ошибаться, искать решения не в том месте 	как часть предложения",
    "Birds of a feather flock together": "Люди, схожие в чем-либо, часто являются друзьями / Два сапога пара (чаще используется в негативном контексте) 	самостоятельно",
    "Bite off more than you can chew": "Взяться за проект, который сам же не можешь закончить 	как часть предложения",
    "Break the ice": "Позволить людям чувствовать себя более комфортно 	как часть предложения",
    "By the skin of your teeth": "С большим трудом, еле-еле 	как часть предложения",
    "Comparing apples to oranges": "Сравнивать две несравнимые вещи 	как часть предложения",
    "Costs an arm and a leg": "Очень дорого 	как часть предложения",
    "Do something at the drop of a hat": "Делать что-либо, заранее неспланированное 	как часть предложения",
    "Do unto others as you would have them do unto you": "Относиться к людям справедливо. Известно как «золотое правило» 	самостоятельно",
    "Don't count your chickens before they hatch": "Не полагайся на благополучный исход, пока событие не произошло 	самостоятельно",
    "Don't cry over spilt milk": "Нет причин жаловаться на то, чего нельзя изменить 	самостоятельно",
    "Don't give up your day job": "Вы не очень хороши в этом деле 	самостоятельно",
    "Don't put all your eggs in one basket": "То, что вы делаете, слишком рискованно 	самостоятельно",
    "Every cloud has a silver lining": "За плохим следует хорошее 	самостоятельно",
    "Get a taste of your own medicine": "К тебе относятся так, как ты относишься к другим (с негативной окраской) 	как часть предложения",
    "Give someone the cold shoulder": "Игнорировать кого-либо 	как часть предложения",
    "Go on a wild goose chase": "Делать что-либо бессмысленно 	как часть предложения",
    "Good things come to those who wait": "Потерпи 	самостоятельно",
    "He has bigger fish to fry": "У него дела покрупнее тех, о которых мы сейчас говорим 	самостоятельно",
    "He's a chip off the old block": "Сын как отец 	самостоятельно",
    "Hit the nail on the head": "Понять что-то очень точно 	самостоятельно",
    "Ignorance is bliss": "Тебе лучше не знать 	самостоятельно",
    "It ain't over till the fat lady sings": "Это ещё не конец 	самостоятельно",
    "It takes one to know one": "Ты такой же плохой, как и я 	самостоятельно",
    "It's a piece of cake": "Это просто 	самостоятельно",
    "It's raining cats and dogs": "Сильный дождь 	самостоятельно",
    "Kill two birds with one stone": "Сделать две вещи за один раз (Убить двух зайцев одним выстрелом) 	самостоятельно",
    "Let the cat out of the bag": "Выдать тайну 	как часть предложения",
    "Live and learn": "Я допустил ошибку 	самостоятельно",
    "Look before you leap": "Сто раз подумай, прежде чем рисковать 	самостоятельно",
    "On thin ice": "Условно. Если вы допустите еще одну ошибку, будут проблемы. 	как часть предложения",
    "Once in a blue moon": "Редко 	как часть предложения",
    "Play devil's advocate": "Утверждать обратное только ради сохранения аргумента 	как часть предложения",
    "Put something on ice": "Поставить проект на удержание 	как часть предложения",
    "Rain on someone's parade": "Испортить что-либо 	как часть предложения",
    "Saving for a rainy day": "Откладывать деньги на будущее 	как часть предложения",
    "Slow and steady wins the race": "Надёжность важнее скорости 	самостоятельно",
    "Spill the beans": "Раскрыть секрет 	как часть предложения",
    "Take a rain check": "Отложить план 	как часть предложения",
    "Take it with a grain of salt": "Не воспринимайте это слишком серьезно 	как часть предложения",
    "The ball is in your court": "Это ваше решение 	самостоятельно",
    "The best thing since sliced bread": "Действительно хорошее изобретение 	как часть предложения",
    "The devil is in the details": "Хорошо выглядит издалека, но если присмотреться, то будут видны проблемы 	самостоятельно",
    "The early bird gets the worm": "Те, кто приходят первыми, получают лучшее 	самостоятельно",
    "The elephant in the room": "Большая проблема, проблема, которую все избегают 	как часть предложения",
    "The whole nine yards": "Всё, от начала до конца 	как часть предложения",
    "There are other fish in the sea": "Даже если возможность упущена, найдутся другие. 	самостоятельно",
    "There's a method to his madness": "Он кажется сумасшедшим, но на самом деле он умный. 	самостоятельный",
    "There's no such thing as a free lunch": "Ничто не бывает абсолютно бесплатно (Бесплатный сыр только в мышеловке). 	самостоятельно",
    "Throw caution to the wind": "Рискнуть 	как часть предложения",
    "You can't have your cake and eat it too": "Вы не можете иметь всё 	самостоятельно",
    "You can't judge a book by its cover": "Человек или вещь могут казаться некрасивыми внешне, но внутри они хорошие (Не судить книгу по обложке) 	самостоятельно",
    "A little learning is a dangerous thing": "Люди, которые не понимают что-либо до конца, опасны 	самостоятельно",
    "A snowball effect": "События по инерции наслаиваются одно на другое (Снежный ком) 	как часть предложения",
    "A snowball's chance in hell": "Никаких шансов 	как часть предложения",
    "A stitch in time saves nine": "Устраните проблему сейчас, иначе позже будет хуже 	самостоятельно",
    "A storm in a teacup": "Большой шум вокруг маленькой проблемы (Делать из мухи слона) 	как часть предложения",
    "An apple a day keeps the doctor away": "Яблоки полезны для здоровья 	самостоятельно",
    "An ounce of prevention is worth a pound of cure": "Вы можете предотвратить проблему сейчас небольшим усилием. Устранить её позже будет сложнее. 	самостоятельно",
    "As right as rain": "Отлично 	как часть предложения",
    "Bolt from the blue": "То, что происходит без предупреждения 	как часть предложения",
    "Burn bridges": "Разрушить отношения 	как часть предложения",
    "Calm before the storm": "Грядёт что-то плохое, но в данный момент все спокойно (Затишье перед бурей) 	как часть предложения",
    "Come rain or shine": "Несмотря ни на что 	как часть предложения",
    "Curiosity killed the cat": "Хватит задавать вопросы 	самостоятельно",
    "Cut the mustard": "Окажи услугу 	как часть предложения",
    "Don't beat a dead horse": "Всё, эта тема закрыта 	самостоятельно",
    "Every dog has his day": "Каждый получает шанс как минимум один раз 	самостоятельно",
    "Familiarity breeds contempt": "Чем больше ты кого-то знаешь, тем меньше он тебе нравится 	самостоятельно",
    "Fit as a fiddle": "Быть здоровым и крепким 	как часть предложения",
    "Fortune favours the bold": "Рисковать 	самостоятельно",
    "Get a second wind": "Открылось второе дыхание 	как часть предложения",
    "Get wind of something": "Услышать о чём-то тайном 	как часть предложения",
    "Go down in flames": "Провалиться с треском (о неудаче) 	как часть предложения",
    "Haste makes waste": "Вы будете допускать ошибки, если будете спешить 	самостоятельно",
    "Have your head in the clouds": "Быть рассеянным 	как часть предложения",
    "He who laughs last laughs loudest": "Я отплачу вам той же монтеой 	самостоятельно",
    "Hear something straight from the horse's mouth": "Услышать что-либо из первых уст 	как часть предложения",
    "He's not playing with a full deck": "Он глупый 	самостоятельно",
    "He's off his rocker": "Он сумасшедший 	самостоятельно",
    "He's sitting on the fence": "Он не может принять решение 	самостоятельно",
    "It is a poor workman who blames his tools": "Если вы не можете выполнить работу, не обвиняйте в этом других 	самостоятельно",
    "It is always darkest before the dawn": "Дальше будет лучше 	самостоятельно",
    "It takes two to tango": "Один человек не несет всю ответственность, участвуют оба 	самостоятельно",
    "Jump on the bandwagon": "Следуйте тенденции, делайте то, что и остальные 	как часть предложения",
    "Know which way the wind is blowing": "Разобраться в ситуации (обычно с негативным оттенком) 	как часть предложения",
    "Leave no stone unturned": "Оглянуться вокруг тщательно 	как часть предложения",
    "Let sleeping dogs lie": "Прекратите обсуждение вопроса 	как часть предложения",
    "Like riding a bicycle": "Что-то, что вы никогда не забудете, как делать 	как часть предложения",
    "Like two peas in a pod": "Они всегда вместе, неразлучны 	как часть предложения",
    "Make hay while the sun shines": "Воспользуйтесь удачной ситуацией 	как часть предложения",
    "On cloud nine": "Очень счастливый 	как часть предложения",
    "Once bitten, twice shy": "Вы более осторожны после того, как пострадали 	самостоятельно",
    "Out of the frying pan and into the fire": "Дела идут от плохого к худшему 	самостоятельно",
    "Run like the wind": "Беги быстро 	как часть предложения",
    "Shape up or ship out": "Работай лучше или брось эту работу 	самостоятельно",
    "Snowed under": "Занятый 	как часть предложения",
    "That ship has sailed": "Слишком поздно 	самостоятельно",
    "The pot calling the kettle black": "Критикуя кого-то, мы показываемся тебя в таком же свете 	как часть предложения",
    "There are clouds on the horizon": "Грядет беда 	самостоятельно",
    "Those who live in glass houses shouldn't throw stones": "Люди, имеющие плохую репутацию, не должны критиковать других 	самостоятельно",
    "Through thick and thin": "В хорошие времена и в плохие 	как часть предложения",
    "Time is money": "Работай быстро 	самостоятельно",
    "Waste not, want not": "Не разбрасывайтесь вещами, и у вас всегда всего будет достаточно 	самостоятельно",
    "We see eye to eye": "Мы согласны 	самостоятельно",
    "Weather the storm": "Пройти через что-то трудное 	как часть предложения",
    "Well begun is half done": "Хорошее начало это половина дела (очень важно) 	самостоятельно",
    "When it rains it pours": "Всё идёт неправильно с самого начала 	самостоятельно",
    "You can catch more flies with honey than you can with vinegar": "Вы получите всё, что хотите, если будете приятным в общении 	самостоятельно",
    "You can lead a horse to water, but you can't make him drink": "Нельзя заставить кого-то принять правильное решение 	самостоятельно",
    "You can't make an omelet without breaking some eggs": "За всё надо платить 	самостоятельно",
    "rain cats and dogs": "лить как из ведра    ",
    "face like thunder": "мрачнее тучи  ",
    "storm in a teacup": "буря в стакане воды, много шума из ничего",
    "chase rainbows": "гнаться за недостижимым",
    "lightning-fast": "молниеносный ",
    "have one's head in the clouds": "витать в облаках",
    "be snowed under": "быть перегруженным работой",
    "be under the weather": "недомогать",
    "twist in the wind": "томиться",
    "under а cloud": "под подозрением    ",
    "as right as rain": "в полном порядке",
    "for a rainy day": "на черный день      ",
    "bolt from the blue": "как снег на голову",
    "throw caution to the winds": "перестать осторожничать",
    "weather the storm": "пережить трудные времена",
    "sail close to the wind": "ходить по краю пропасти",
    "on cloud nine": "на седьмом небе от счастья",
    "shoot the breeze": "болтать о пустяках",
    "in a fog": "растерянный",
    "go down a storm": "удаться",
    "a piece of the pie": "доля",
    "gravy train": "легкие деньги",
    "bring home the bacon": "обеспечивать семью, преуспевать",
    "make ends meet": "сводить концы с концами",
    "hit the jackpot": "срывать куш",
    "be in the red": "быть в долгу",
    "make a bundle": "сделать кучу денег",
    "bet your bottom dollar": "гарантировать что-либо",
    "look like a million dollars": "выглядеть на все сто",
    "cost a pretty penny": "стоить уйму денег",
    "go Dutch": "платить свою часть",
    "nest egg": "заначка",
    "golden handshake": "большое выходное пособие",
    "cheapskate": "скряга",
    "be flush with money": "купаться в роскоши",
    "at all costs": "любой ценой",
    "live beyond one's means": "жить не по средствам",
    "break the bank": "сильно потратиться",
    "cost a fortune": "стоить целое состояние",
    "on the breadline": "за чертой бедности",
    "once in a blue moon": "очень редко",
    "behind the times": "устаревший",
    "time flies": "время летит",
    "the big time": "большой успех",
    "around the clock": "круглосуточно",
    "dwell on the past": "жить прошлым",
    "have the time of one's life": "отлично провести время",
    "crack of dawn": "с восходом солнца",
    "run out of time": "иссякать",
    "in the blink of an eye": "в одно мгновение",
    "like clockwork": "без перебоя",
    "for donkey's years": "с незапамятных времен",
    "pressed for time": "очень торопиться",
    "give someone a hard time": "отчитывать",
    "be ahead of time": "опережать",
    "to have a whale of a time": "замечательно провести время ",
    "go with the times": "идти в ногу со временем",
    "on the spur of the moment": "с наскока",
    "in broad daylight": "среди бела дня",
    "catch unawares": "застигнуть врасплох",
    "monkey business": "бессмысленная работа",
    "smell a rat": "чуять недоброе",
    "top dog": "победитель",
    "cash cow": "источник денежных средств, дойная корова",
    "eager beaver": "работяга, деловая колбаса",
    "black sheep": "белая ворона",
    "elephant in the room": "слона то я и не приметил, это очевидно",
    "when pigs fly": "когда рак свиснет",
    "like a cat on a hot tin roof": "быть не в своей тарелке",
    "in the doghouse": "в немилости",
    "be as busy as a bee": "трудиться, как пчела",
    "let a cat out of the bag": "выпустить кота из мешка",
    "horse around": "валять дурака",
    "as poor as a church mouse": "бедный, как церковная мышь, без гроша за душой",
    "lion's share of something": "львиная доля",
    "eat like a horse": "иметь волчий аппетит",
    "have a tiger by the tail": "бросать вызов судьбе",
    "hear it straight from the horse's mouth": "из первоисточника",
    "butterflies in the stomach": "ни жив, ни мертв",
    "like water off a duck's back": "как с гуся вода",
    "egghead": "умник",
    "big cheese": "влиятельный человек",
    "couch potato": "бездельник",
    "tough cookie": "хулиган",
    "top banana": "лидер",
    "bad apple": "негодяй",
    "eat one's words": "брать назад свои слова",
    "the apple of one's eye": "зеница ока",
    "hard nut to crack": "трудная задача, крепкий орешек",
    "in a nutshell": "вкратце ",
    "have egg on one's face": "выглядеть глупо",
    "as cool as a cucumber": "хладнокровный ",
    "be full of beans": "быть энергичным",
    "as slow as molasses": "очень медленный",
    "chew the fat": "лясы точить",
    "sell like hot cakes": "быть нарасхват",
    "take something with a pinch of salt": "не доверять",
    "bite off more than one can chew": "переоценить свои возможности",
    "cry over spilt milk": "горевать о непоправимом",
    "hot potato": "актуальная тема",






}
