slovar = {
    "This is my umbrella": "Это мой зонтик  ",
    "Is this my umbrella?": "А это мой зонтик?",
    "This is his tie": "Это его галстук",
    "Whose cat is this?": "Чья это кошка?",
    "This is her cat": "Это ее кошка",
    "Is this his tie?": "А это его галстук? ",
    "These trousers are black": "Эти брюки черные",
    "What colour are these trousers?": "Какого цвета эти брюки? ",
    "Those shoes comfortable": "Те туфли удобные",
    "Are those shoes comfortable?": "А те туфли удобные?",
    "That T-shirt is small": "Та футболка маленька",
    "Is that T-shirt small?": "А та футболка маленькая?",
    "These are my glasses and those are my gloves": "Это мои очки а то мои перчатки",
    "What colour is that house?": "Какого цвета тот дом?",
    "It is grey": "Он серый",
    "What colour are those houses?": "Какого цвета те дома?",
    "They are light yellow": "Они светло - желтые",
    "This is a flower": "Это цветок",
    "These are flowers": "Это цветы ",
    "This is a Child": "Это ребенок ",
    "These are Children": "Это дети ",
    "This is his chair and that is his desk": "Это его стул а то его парта",
    "This is your pencil": "Это твой карандаш",
    "These are your pencils": "Это ваши карандаши",
    "Is this homework easy?": "Эта домашняя работа легкая? ",
    "yes, it is": "Да",
    "Are those men your neighbors?": "Те мужчины твои соседи? ",
    "No, they aren't": "Нет",
    "These tomatoes are not fresh": "Эти помидоры не свежие",
    "This is not our bus": "Это не наш автобус ",
    "Pass me those spoons, please": "Передайте мне те ложки, пожалуйста",
    "pass him that plate": "Передайте ему ту тарелку",
    "Pass her these copybooks": "Передайте ей эти тетрадки",
    "Pass them this box": "Передайте им эту коробку",
    "This is my sister's room": "",
    "Her room is big": "",
    "That hat is mine, not yours": "",
    "Yours is on the shelf": "",
    "Is that tie yours?": "",
    "No, it is my father's": "",
    "What color is your friend's coat?": "",
    "It is dark grey": "",
    "It is not your book": "",
    "Yours is on the table. It is his": "",
    "Whose money is this?": "",
    "It is his friends money": "",
    "My grandmother's watch is always slow": "",
    "It is very old": "",
    "Where are John's cats?": "",
    "They are in the garden": "",
    "What are your parents names?": "",
    "They are Patrick and Sally": "",
    "How old is Jack's sister?": "",
    "She is about five years old": "",
    "What is your sisters phone numbers?": "",
    "It is 02345678": "",
    "Is this your umbrella?": "",
    "No, it isn't mine. It is hers": "",
    "Whose dress is that?": "",
    "Is it yours?": "",
    "This is not my ball": "",
    "It is yellow, but mine is brown": "",
    "Whose glass of milk is this?": "",
    "Is it ours?": "",
    "Are these your earrings?": "",
    "No, they are not mine": "",
    "They are my sister's": "",
    "Where is Marina and Helen's house?": "",
    "It is round the corner": "",
    "Is that fruit yours?": "",
    "Yes, it is": "",
    "Are those flowers ours?": "",
    "No,they aren't": "",
    "Am I late?": "",
    "No, you aren't. You are on time": "",
    "What is your hobby?": "",
    "My hobby is listening to music": "",
    "What is your brother's hobby?": "",
    "His hobby is travelling": "",
    "Is your sister a seamstress?": "",
    "No, she is a fashion designer": "",
    "Is her job difficult?": "",
    "Are you hungry?": "",
    "No, I am not": "",
    "Are you thirsty?": "",
    "Yes, I am": "",
    "Is he angry?": "",
    "No, he isn't": "",
    "Is your sister happy?": "",
    "Yes, she is": "",
    "Is she married?": "",
    "What colour is your hat?": "",
    "It is yellow": "",
    "What colour are your gloves?": "",
    "They are black": "",
    "Your doll is beautiful. What is its name?": "",
    "Its name is Polly": "",
    "Where are you from?": "",
    "I am from Mexico": "",
    "He is from France. He is French": "",
    "What is the capital of South Korea?": "",
    "It is Seoul": "",
    "What is the language in Argentina?": "",
    "It is Spanish": "",
    "How old are you?": "",
    "I'm thirty years old": "",
    "Have you got a wife?": "",
    "Yes, I have": "",
    "How old is she?": "",
    "She is twenty-five years old": "",
    "Have you got any children?": "",
    "Yes, I have two children": "",
    "a daughter and a son": "",
    "How old is your daughter?": "",
    "She is very young": "",
    "She is five years old": "",
    "How old is your son?": "",
    "He is only a baby": "",
    "He is ten months old": "",
    "Where is your son?": "",
    "He is at home": "",
    "Where is your daughter?": "",
    "She is in the kindergarten": "",
    "Have you got a grandmother?": "",
    "Has she got any domestic animals?": "",
    "Yes, she has": "",
    "How many cows has she got?": "",
    "She has got only one": "",
    "cow called Nanny": "",
    "This is my uncle": "",
    "He is my mum's brother": "",
    "What is your uncle's name?": "",
    "His name is Liam": "",
    "My uncle is a driver": "",
    "What kind of car has he got?": "",
    "He has got a Toyota": "",
    "Let's meet at five o'clock in the evening": "",
    "Let's go out in the evening": "",
    "Please, do it by Monday": "",
    "Never stop!": "",
    "Never lose!": "",
    "Always learn!": "",
    "Don't stop here": "",
    "Follow me": "",
    "Open the book, please, and look at the picture": "",
    "It is noon": "",
    "Let's have lunch somewhere": "",
    "It is dirty here": "",
    "Please, take a broom and sweep the floor": "",
    "It is stuffy here": "",
    "Open the window, please": "",
    "Is it cold today?": "",
    "No, it isn't. It is warm": "",
    "Is it the nice weather outside?": "",
    "Yes, it is sunny, but it is a little frosty": "",
    "What day is it today?": "",
    "It is Monday today?": "",
    "What date is it today?": "",
    "It is the 23 of February": "",
    "What time is it?": "",
    "It is half past one": "",
    "What is the weather today?": "",
    "It is rather cold and dull today": "",
    "It's late": "",
    "It's time to go home": "",
    "What a lovely day!": "",
    "It is so sunny today!": "",
    "What a terrible day!": "",
    "It is baking hot": "",
    "What is your favourite weather?": "",
    "I think cold weather is good for health": "",
    "His sister is older than he is": "",
    "Boys are braver than girls": "",
    "He is luckier than other artists": "",
    "The weather this summer is better than last summer": "",
    "I am 10 centimeters taller than my brother": "",
    "Junk food is cheaper than healthy food": "",
    "Better late than never": "",
    "The sooner the better": "",
    "She has got longer hair than I have": "",
    "These apples are less red than those ones": "",
    "Our boss is less busy on Thursdays": "",
    "You have the most beautiful house in our neighbourhood": "",
    "January is the coldest month of the year": "",
    "The Taj Mahal is one of the most famous buildings in the world": "",
    "Who is the kindest person in your family?": "",
    "My wife is the kindest person": "",
    "What is the most difficult subject at school?": "",
    "Chemistry is the most difficult subject": "",
    "My uncle's car is as expensive as yours": "",
    "This house is not as big as that one": "",
    "Is he as tall as she is?": "",
    "No, he is taller": "",
    "You have such a beautiful cat but it is so lazy": "",
    "This sofa is so comfortable!": "",
    "It is more comfortable than ours": "",
    "You have such a good job!": "",
    "It is better than mine": "",
    "He has such an expensive car!": "",
    "But his car is not as fast as mine": "",
    "Oscar is as tall as james": "",
    "But Oscar is not so strong": "",
    "I have got some ham": "",
    "She has got a few napkins": "",
    "Have you got any marmalade?": "",
    "Yes, I have got a lot of marmalade": "",
    "We haven't got many cups": "",
    "She hasn't got much sugar": "",
    "I have got little butter": "",
    "Have they got much sait?": "",
    "Yes, they have got enough salt": "",
    "How many spoons have you got?": "",
    "I have got many spoons": "",
    "How much cheese have you got?": "",
    "I haven't got much cheese": "",
    "I have got little cheese": "",
    "We have got few napkins": "",
    "Have we got many glasses?": "",
    "No, we haven't": "",
    "We have got a few glasses": "",
    "I have got a lot of  forks but I haven't got many plates": "",
    "She has got many rolls but she has got little ham": "",
    "How much time have I got?": "",
    "Have I got much time?": "",
    "No, you have little time": "",
    "There is a table in the meddle of the room": "",
    "There are some plates on the table": "",
    "There are six  spoons next to the plates": "",
    "There is a sandwich on the plate": "",
    "There is some butter on the sandwich": "",
    "There si a cup to the right fo the plate": "",
    "There isn't any cream in the coffee": "",
    "Is there any sugar in the coffee?": "",
    "Yes, there is enough sugar in the coffee": "",
    "There is a shelf above the bed on the wall": "",
    "Is there a vase on the shelf?": "",
    "Yes, there is": "",
    "Is there any water in the vase?": "",
    "Yes, there is": "",
    "How much water is there in the vase?": "",
    "There is little water in the vase": "",
    "How many flowers are there in the vase?": "",
    "There are five flowers in the vase": "",
    "There is a football match on TV today": "",
    "There are two or three good films on TV this evening": "",
    "What is there for breakfast today?": "",
    "There is a fried egg and a sandwich today": "",
    "Is there any fruit in the fridge?": "",
    "Yes, there is an orange and some apples in the fridge": "",
    "There is a big house opposite the supermarket": "",
    "There is red roof on the house": "",
    "There is a high fence around the house": "",
    "There is a garden behind the house": "",
    "There are a lot of apple-trees in the garden": "",
    "What is your book made of?": "",
    "My book is made of paper": "",
    "My pencil is made of wood": "",
    "My key is made of metal": "",
    "My ring is made of gold": "",
    "My handkerchief is made of linen": "",
    "What are your jeans made of?": "",
    "My jeans are made of denim": "",
    "What are your shoes made of?": "",
    "My shoes are made of artificial leather": "",
    "What is her skirt made of?": "",
    "Her skirt is made of silk": "",
    "Her dress is made of velvet": "",
    "His jacket is made of velveteen": "",
    "My mother's dressing gown is made of sateen": "",
    "These tights are made of nylon": "",
    "These earrings are made of silver": "",
    "His T-shirt is made of cotton": "",
    "My socks are made of wool": "",
    "This window is made of plastic and glass": "",
    "The houses are made of iron, bricks and cement": "",
    "This cup is made of porcelain": "",
    "What is this ball made of?": "",
    "It is made of rubber": "",
    "This carpet is made of felt": "",
    "I usually get up at 7 o'clock": "",
    "I put on my clothes": "",
    "I make my bed and go out of the room": "",
    "I go to the bathroom": "",
    "I wash myself with soap and water": "",
    "I dry myself with a towel": "",
    "I clean my teeth with a tooth-brush": "",
    "I shave myself with a shaver": "",
    "I brush my hair": "",
    "I put on makeup": "",
    "I go into the bedroom and come up to the wardrobe": "",
    "I take off my slippers in the hall and put on my shoes": "",
    "I unlock the door with a key and open it": "",
    "I go out of the flat": "",
    "I go down the stairs to the ground floor": "",
    "I go out the entrance": "",
    "I read books every day": "",
    "What do you read every day?": "",
    "She has breakfast at 8 o'clock": "",
    "What time does she have breakfast?": "",
    "I don't usually listen to music in the morning": "",
    "She doesn't often cook salad": "",
    "We don't usually go shopping on Saturdays": "",
    "My sister doesn't always go to bed at 10 o'clock": "",
    "Do you do your homework every evening?": "",
    "yes, I do": "",
    "Does he often go to the cinema?": "",
    "No, he doesn't": "",
    "Do the children have lunch at home every day?": "",
    "No, they don't": "",
    "They usually have lunch at school": "",
    "I usually watch TV when I cook": "",
    "He always listens to music when he drives a car": "",
    "I have breakfast at eight o'clock in the morning": "",
    "I have lunch at twelve o'clock sharp": "",
    "I have dinner at seven o'clock in the evening": "",
    "I like a cup of coffee and rolls with butter for breakfast": "",
    "I like some sandwiches and a glass of milk for lunch": "",
    "I like some soup,meat,vegetables and dessert for dinner": "",
    "I like coffee, but I don't like tea": "",
    "She likes milk, but she doesn't like cereals": "",
    "I like white bread, but I don't like rye bread": "",
    "They like boiled eggs, but they don't like scrambled eggs": "",
    "He likes fried eggs, but he doesn't like omelettes": "",
    "I like ham and eggs, but he likes bacon and eggs": "",
    "You like salt butter, but  I like sweet butter": "",
    "I like rice soup better than tomato soup": "",
    "I like meat better than fish": "",
    "He likes pork better than veal": "",
    "He likes roast beef, but she likes boiled beef": "",
    "I prefer pork chops to lamb chops": "",
    "They prefer chicken to steak": "",
    "He prefer potato salad to lettuce": "",
    "I prefer wine to beer": "",
    "You prefer lamb chops, but I prefer veal chops": "",
    "You prefer beef stew, but they prefer lamb stew": "",
    "He prefers rice pudding, but I prefer apple sauce": "",
    "She prefers icd-cream, but they prefer home made cakes": "",
    "We are very fond of English cooking": "",
    "Do you like potatoes?": "",
    "No, I like tomatoes": "",
    "Do you like fried potatoes?": "",
    "No, I like mashed potatoes": "",
    "Does she like spinach?": "",
    "No, she likes cabbage": "",
    "Does he like green peas?": "",
    "No, he likes string beans": "",
    "Do you like beetroot?": "",
    "No, we like carrots": "",
    "Do they like asparagus?": "",
    "No, they like cauliflower": "",
    "What do you like for desert?": "",
    "I like ice-cream for dessert": "",
    "Does he like apples?": "",
    "No, he prefers pears": "",
    "Do you like peaches?": "",
    "No, I prefer plums": "",
    "Do you like cherries?": "",
    "No, I prefer strawberries": "",
    "Do you like bananas?": "",
    "No, I prefer oranges": "",
    "Does he like grapes?": "",
    "No, he prefers pineapples": "",
    "Does she like apple sauce?": "",
    "No, she prefers stewed prunes": "",
    "Do they like dates and figs?": "",
    "I don't know, but I think so": "",
    "Excuse me, could you tell me how I can get to the post office?": "",
    "Yes, It's over there": "",
    "Thank you very much": "",
    "That's all right": "",
    "Excuse me, I am looking for a pharmacy": "",
    "Is it far from here?": "",
    "No, it isn't very far. Go across the road": "",
    "It is next to the hair salon": "",
    "Is it the right way to the bookshop?": "",
    "Yes, That's right. Go straight ahead": "",
    "It's round the corner": "",
    "Thanks a lot": "",
    "Not at all": "",
    "Excuse me, do you know where the flower market is?": "",
    "Yes, it is in Downing Street": "",
    "How far is it?": "",
    "It is about ten - minute walk": "",
    "Go straight on and take the first turning on the left": "",
    "Thank you": "",
    "You are welcome": "",
    "Can you help me? Am I on the right road for the hostel?": "",
    "Yes, thant's right. Go past the fire station and turn right after it. The hostel is just round the corner": "",
    "Excuse me": "",
    "Yes, can I help you?": "",
    "Yes, could you tell me the way to the railway station?": "",
    "Yes, of course. It's about 15 minutes from here by bus. Go to the bus stop and wait the bus number 57": "",
    "Excuse me, is there a restaurant near here?": "",
    "Sure. It's not very far": "",
    "How can I get there?": "",
    "You should go straight ahead,then turn right and go along the street. The restaurant is ont the left of the corner": "",
    "Is there anything next to the restaurant?": "",
    "Yes, there is a jewellery shop next to it": "",
    "Do you always have breakfast at 9 o'clock?": "",
    "Yes, we do": "",
    "Are you having breakfast now?": "",
    "Yes, we are": "",
    "Do you usually eat salad for breakfast?": "",
    "No, I don't": "",
    "Are you eating salad now?": "",
    "No, I am not": "",
    "Where does he go every day?": "",
    "He goes to school": "",
    "Where is he going now?": "",
    "He is going to the shop": "",
    "Does your brother do his homework now?": "",
    "Yes, he does": "",
    "Is your brother doing his homework now?": "",
    "Yes, he is": "",
    "Does it often rain in spring?": "",
    "Yes, it does": "",
    "Is it raining now?": "",
    "Yes, it is": "",
    "What does your father usually watch on TV?": "",
    "He usually watches news": "",
    "What is he watching now?": "",
    "He is watching a football match": "",
    "Do the children drink juice for lunch?": "",
    "Yes, they do": "",
    "Are they drinking juice now?": "",
    "No, they aren't": "",
    "Does your mother often cook fried potatoes?": "",
    "No, She doesn't": "",
    "Is your mother cooking rice soup now?": "",
    "Yes, she is": "",
    "Does your uncle always read newspapers when he has breakfast?": "",
    "Yes, he does": "",
    "Is your uncle reading and having breakfast now?": "",
    "He is having breakfast, but he isn't reading now": "",
    "I buy meat poultry at the butcher's": "",
    "I buy tinned goods and spices at the grocer's": "",
    "I buy milk, butter and cottage cheese at the dairy": "",
    "I buy bread, rolls and cake, at the baker's": "",
    "I buy fruit and vegetables at the green grocer's": "",
    "I buy seafood at the fishmonger's": "",
    "I buy medicine at the pharmacy's": "",
    "I go to the ironmonger's to buy nails, hemmers and screwdrivers": "",
    "I can buy tracksuit in the sportswear store": "",
    "I can buy pens, colored pencils and copybooks at the stationer's": "",
    "You can buy fridge and washing machine at the appliances department": "",
    "You can find a lot of new clothes at the department store": "",
    "I go to the florist's t buy a bunch of flowers": "",
    "You can find some sockets and light bulbs in the electrical store": "",
    "I go to the hairdresser's to get haircut and get hairdo": "",
    "I go to the bank to deposit or withdraw money": "",
    "I pay money to the cashier and she gives me my change": "",
    "Will you follow my advice?": "",
    "Yes, I'll follow your advice": "",
    "Will you invite all your friends to teh party on Saturday?": "",
    "Yes, I will": "",
    "I think it will rain tomorrow": "",
    "You should take an umbrella": "",
    "My bag is very heavy": "",
    "I will help you": "",
    "Will you be at home at five o'clock?": "",
    "No, I won't I will come back home at six o'clock in the evening": "",
    "Will the firm export coffee to Europe?": "",
    "No, they will export coffee only to Asia": "",
    "Will the pizza be ready in ten minutes?": "",
    "Yes, it will be ready in ten minutes": "",
    "We are the best football team": "",
    "I think we shall win the match tomorrow": "",
    "Will you see Ann next week?": "",
    "Yes, I will": "",
    "This letter is for Ann": "",
    "Ok. I'll give it to her tomorrow": "",
    "I was tired last night": "",
    "Were they in London last summer?": "",
    "No, they weren't. They were in Paris": "",
    "We weren't happy about the hotel": "",
    "Our room was very small and it wasn't very clean": "",
    "When I was a child my favourite toy was a teddy bear": "",
    "Were you in Moscow last year?": "",
    "No, I wasn't. I was in Moscow five years ago": "",
    "Was he ill last week?": "",
    "No, He wasn't. He was well": "",
    "Today the weather is nice, but yesterday it was very cold": "",
    "Last year Ann was 25, so she is 26 now": "",
    "What day was it yesterday?": "",
    "It was Sunday yesterday": "",
    "William Shakespeare was a famous English writer": "",
    "What did you do yesterday?": "",
    "I went to the cinema": "",
    "Did you go there alone?": "",
    "No, I went with my friend": "",
    "What film did you watch?": "",
    "We watched a detective": "",
    "Did you like the film?": "",
    "Yes, I liked it, but my friend didn't like it": "",
    "Did you go to the cafe after the cinema?": "",
    "Yes, we went to the coffee house": "",
    "Did you drink any coffee there?": "",
    "Yes, we drank cappuccino": "",
    "What did you eat?": "",
    "We ate pancakes with strawberry cream": "",
    "Did you walk in the park?": "",
    "No, we didn't, but we walked along the coast": "",
    "Was it warm on the coast?": "",
    "Yes, it was sunny, but it was windy": "",
    "Did oyu see any gulls there?": "",
    "Yes, We did. We fed them with some bread": "",
    "What time did you come home?": "",
    "I came at 10 o'clock in the evening": "",
    "Were you tired?": "",
    "Yes, I was": "",
    "Did you have dinner?": "",
    "No, I didn't. I wasn't hungry. I had a shower and went to bed": "",
    "What time did you go to bed?": "",
    "I went to bed at 11 o'clock": "",
    "be was were been": "",
    "begin began begun": "",
    "break broke broken": "",
    "build built built": "",
    "buy bought bought": "",
    "catch caught caught": "",
    "come came come": "",
    "do did done": "",
    "drink drank drunk": "",
    "eat ate eaten": "",
    "find found found": "",
    "fly flew flown": "",
    "get got got": "",
    "give gave given": "",
    "go went gone": "",
    "have had had": "",
    "hear heard heard": "",
    "keep kept kept": "",
    "leave left left": "",
    "learn learnt learnt": "",
    "lose lost lost": "",
    "make made made": "",
    "read read read": "",
    "ride rode ridden": "",
    "run ran run": "",
    "say said said": "",
    "show showed shown": "",
    "sing sang sung": "",
    "sit sat sat": "",
    "sleep slept slept": "",
    "speak spoke spoken": "",
    "stand stood stood": "",
    "swim swam swum": "",
    "take took taken": "",
    "teach taught taught": "",
    "tell told told": "",
    "think thought thought": "",
    "understand understood understood": "",
    "wake woke woken": "",
    "wear wore worn": "",
}

